### ISSUE TITLE
Expo ejected app crashes (keeps stopping) in Android emulator

### ISSUE THREAD

**Issue by khaja-nizamuddin1** [expo/expo#10006]
## 🐛 Bug Report

I have created an expo project, configured app.json and ejected it with no changes.

In ANdroid studio, 
MainApplication and MainActivity had code: com.appe5 
I was getting build failure, so I changed class names to com.khaja.appE5 
according to what I defined as package name in app.json 
When I build and run it in Android Studio, app gets installed in emulator, but crashes immediately.
error: app stopped or app keepsstopping.

Error reported in logcat is as follows:
2020-08-31 10:41:10.707 28154-28154/com.khaja.appE5 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.khaja.appE5, PID: 28154
    java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
        at expo.modules.updates.loader.EmbeddedLoader.readEmbeddedManifest(EmbeddedLoader.java:78)
        at expo.modules.updates.UpdatesController.start(UpdatesController.java:285)
        at expo.modules.updates.UpdatesController.initialize(UpdatesController.java:96)
        at com.khaja.appE5.MainApplication.onCreate(MainApplication.java:87)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Running it on expo version : 3.25.1
Emulator: pixel XL with API: 29

### Steps to Reproduce
Create an empty expo project
configure ios and android details in app.json
eject
open in android studio
change class names in mainApplication and mainActivity according to package name in app.json and move them to recommended directory
Build and run on emulator with API 29

### Expected Behavior vs Actual Behavior
App should open without crashing

**Comment by byCedric** [comment]
Hi @khaja-nizamuddin1! Thanks for writing in, but without a [repro](https://stackoverflow.com/help/minimal-reproducible-example) I'm not sure what's going on. There are a lot of classes, files, and folders you need to update to rename the `package` identifier. [Here is a list of steps you have to do](https://stackoverflow.com/a/29092698), maybe it can help.

The error you provided is a generic error where Android can't find your manifest, which means you probably missed a step or need to rebuild the project.

Hope this helps!
