### ISSUE TITLE
Expo run err

### ISSUE THREAD

**Issue by AadityaTailor** [expo/expo#10018]
Error: spawn powershell ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.

**Comment by byCedric** [comment]
Hi @AadityaTailor, unfortunately without any context or question there isn't much we can do to help. It looks like node couldn't find the windows powershell. Please double-check if that's working on windows. If that doesn't fix it, please create a new bug report with the template filled in.

Hope this helps
