### ISSUE TITLE
Application stopped, after detaching to use Expokit

### ISSUE THREAD

**Issue by NdozHH** [expo/expo#1012]
I made the detach of my project to continue using Expo APIS and add some native elements to my application, I followed this guide to do the detach: https://docs.expo.io/versions/latest/guides/detach.html and all well, then I followed this one to run the application and continue the development: https://docs.expo.io/versions/latest/guides/expokit.html, I opened the android folder in Android Studio, but when running on a device or emulator, I get "the application stopped", what can I do to fix it and continue with the development?

**Comment by dikaiosune** [comment]
Hi! Can you provide some more details about your environment, along with any error logs you're getting (adb logs, for example)?

**Comment by NdozHH** [comment]
Hi, this is the application log when running it

`11-27 12:37:07.039 1464-1464/com.test E/ActivityThread: Unable to setupGraphicsSupport due to missing cache directory
11-27 12:37:07.048 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/base.apk  /data/app/com.test-1/base.apk   /data/app/com.test-1/base.apk
11-27 12:37:08.206 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_dependencies_apk.apk  /data/app/com.test-1/split_lib_dependencies_apk.apk   /data/app/com.test-1/split_lib_dependencies_apk.apk
11-27 12:37:08.214 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_0_apk.apk  /data/app/com.test-1/split_lib_slice_0_apk.apk   /data/app/com.test-1/split_lib_slice_0_apk.apk
11-27 12:37:08.215 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_1_apk.apk  /data/app/com.test-1/split_lib_slice_1_apk.apk   /data/app/com.test-1/split_lib_slice_1_apk.apk
11-27 12:37:08.224 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_2_apk.apk  /data/app/com.test-1/split_lib_slice_2_apk.apk   /data/app/com.test-1/split_lib_slice_2_apk.apk
11-27 12:37:08.236 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_3_apk.apk  /data/app/com.test-1/split_lib_slice_3_apk.apk   /data/app/com.test-1/split_lib_slice_3_apk.apk
11-27 12:37:08.250 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_4_apk.apk  /data/app/com.test-1/split_lib_slice_4_apk.apk   /data/app/com.test-1/split_lib_slice_4_apk.apk
11-27 12:37:08.251 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_5_apk.apk  /data/app/com.test-1/split_lib_slice_5_apk.apk   /data/app/com.test-1/split_lib_slice_5_apk.apk
11-27 12:37:08.252 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_6_apk.apk  /data/app/com.test-1/split_lib_slice_6_apk.apk   /data/app/com.test-1/split_lib_slice_6_apk.apk
11-27 12:37:08.254 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_7_apk.apk  /data/app/com.test-1/split_lib_slice_7_apk.apk   /data/app/com.test-1/split_lib_slice_7_apk.apk
11-27 12:37:08.261 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_8_apk.apk  /data/app/com.test-1/split_lib_slice_8_apk.apk   /data/app/com.test-1/split_lib_slice_8_apk.apk
11-27 12:37:08.269 1464-1464/com.test E/System: elements.add : /data/app/com.test-1/split_lib_slice_9_apk.apk  /data/app/com.test-1/split_lib_slice_9_apk.apk   /data/app/com.test-1/split_lib_slice_9_apk.apk
11-27 12:37:08.484 1464-1464/com.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                        Process: com.test, PID: 1464
                                                        java.lang.NoClassDefFoundError: Failed resolution of: Lbolts/AppLinks;
                                                            at com.facebook.appevents.internal.SourceApplicationInfo$Factory.create(SourceApplicationInfo.java:131)
                                                            at com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated(ActivityLifecycleTracker.java:131)
                                                            at com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated(ActivityLifecycleTracker.java:77)
                                                            at android.app.Application.dispatchActivityCreated(Application.java:189)
                                                            at android.app.Activity.onCreate(Activity.java:946)
                                                            at android.support.v4.app.BaseFragmentActivityGingerbread.onCreate(BaseFragmentActivityGingerbread.java:54)
                                                            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:319)
                                                            at host.exp.exponent.experience.ReactNativeActivity.onCreate(ReactNativeActivity.java:130)
                                                            at host.exp.expoview.ExponentActivity.onCreate(ExponentActivity.java:69)
                                                            at android.app.Activity.performCreate(Activity.java:6033)
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:135)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5268)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "bolts.AppLinks" on path: DexPathList[[zip file "/data/app/com.test-1/base.apk", zip file "/data/app/com.test-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.test-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.test-1/lib/arm, /vendor/lib, /system/lib]]
                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                            at com.facebook.appevents.internal.SourceApplicationInfo$Factory.create(SourceApplicationInfo.java:131) 
                                                            at com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated(ActivityLifecycleTracker.java:131) 
                                                            at com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated(ActivityLifecycleTracker.java:77) 
                                                            at android.app.Application.dispatchActivityCreated(Application.java:189) 
                                                            at android.app.Activity.onCreate(Activity.java:946) 
                                                            at android.support.v4.app.BaseFragmentActivityGingerbread.onCreate(BaseFragmentActivityGingerbread.java:54) 
                                                            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:319) 
                                                            at host.exp.exponent.experience.ReactNativeActivity.onCreate(ReactNativeActivity.java:130) 
                                                            at host.exp.expoview.ExponentActivity.onCreate(ExponentActivity.java:69) 
                                                            at android.app.Activity.performCreate(Activity.java:6033) 
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288) 
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397) 
                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                            at android.os.Looper.loop(Looper.java:135) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5268) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) 
                                                        	Suppressed: java.lang.ClassNotFoundException: bolts.AppLinks
                                                            at java.lang.Class.classForName(Native Method)
                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                            		... 23 more
                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by jesseruder** [comment]
Can you post your `app/build.gradle` file? `Failed resolution of: Lbolts/AppLinks` looks like an issue we had a while ago but I thought it was fixed.

**Comment by NdozHH** [comment]
Hi @jesseruder I saw a posting of yours on an expo forum and it worked (You need to remove the exclude module block from compile 'com.facebook.android:facebook-android-sdk:4.+').

But now, when the build reaches 100%, the application stops with this exception.

`11-27 14:26:23.466 10443-11144/com.test E/AndroidRuntime: FATAL EXCEPTION: Thread-1742
                                                          Process: com.test, PID: 10443
                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookSdk;`

This is my build.gradle file
`apply plugin: 'com.android.application'

android {
  compileSdkVersion 25
  buildToolsVersion '25.0.2'

  defaultConfig {
    applicationId "com.test"
    minSdkVersion 19
    targetSdkVersion 25
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
    ndk {
      abiFilters 'armeabi-v7a', 'x86'
    }
    manifestPlaceholders = [
      'appAuthRedirectScheme': 'com.test'
    ]
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
  dexOptions {
    javaMaxHeapSize "8g"
  }
  lintOptions {
    abortOnError false
  }
}

task exponentPrebuildStep(type: Exec) {
  workingDir '../../'

  if (System.getProperty('os.name').toLowerCase().contains('windows')) {
    commandLine 'cmd', '/c', '.\\.expo-source\\android\\detach-scripts\\prepare-detached-build.bat'
  } else {
    commandLine './.expo-source/android/detach-scripts/prepare-detached-build.sh'
  }
}
preBuild.dependsOn exponentPrebuildStep

repositories{
  flatDir{
    dirs 'libs'
  }
  mavenLocal()
  maven { url 'https://maven.fabric.io/public' }
}

dependencies {
  compile fileTree(dir: 'libs', include: ['*.jar'])
  testCompile 'junit:junit:4.12'
  compile 'com.android.support:appcompat-v7:25.3.1'
  compile 'com.android.support:multidex:1.0.1'

  
  compile('host.exp.exponent:expoview:22.0.0@aar') {
    exclude group: 'com.facebook.android', module: 'facebook-android-sdk'
    exclude group: 'com.facebook.android', module: 'audience-network-sdk'
    exclude group: 'io.nlopez.smartlocation', module: 'library'
    transitive = true;
  }


  compile('com.facebook.android:audience-network-sdk:4.+') {
    exclude module: 'play-services-ads'
  }
  compile('io.nlopez.smartlocation:library:3.2.11') {
    transitive = false
  }
  
  
}
`

**Comment by jesseruder** [comment]
It looks like you removed this line too `compile 'com.facebook.android:facebook-android-sdk:4.+'`. You need to leave that line

**Comment by NdozHH** [comment]
Thanks, it worked, but now I get a new exception.
`11-27 15:07:34.940 1980-1980/com.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                        Process: com.test, PID: 1980
                                                        java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nostra13/universalimageloader/core/ImageLoader;`

And I have a doubt, it's really so difficult the detach? process, it's normal to have these errors?

**Comment by jesseruder** [comment]
I'm not sure why you're hitting these error, other people have been able to get this working by just deleting that one `exclude` line. Also if you detach an SDK 23 app you shouldn't need to do anything extra. Maybe try it with SDK 23?

**Comment by NdozHH** [comment]
My sdk is 22, so you suggest to upgrade to 23?
