### ISSUE TITLE
App crashes on load when using map and public url 

### ISSUE THREAD

**Issue by dev-sk-master** [expo/expo#10137]
## 🐛 Bug Report
App crashes on android and iOS when using public URL and having the map loaded.

### Summary of Issue 
- Using managed workflow on Expo
- If I use expo build:ios or expo build:android it works well, the App loads ok.
- If I use the following (Android or iOS), the app crashes immediately on load
  expo build:android --public-url https://dev-sk-master.github.io/expoTest/android-index.json
  expo build:ios --public-url https://dev-sk-master.github.io/expoTest/ios-index.json
- This produced the build however it crashes on load on both Android and iOS.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Same issue building on Mac or Windows.

Mac:

Expo CLI 3.23.2 environment info:
System:
OS: macOS 10.15.6
Shell: 2.5.0 - /usr/local/bin/fish
Binaries:
Node: 14.7.0 - /usr/local/bin/node
Yarn: 1.15.2 - /usr/local/bin/yarn
npm: 6.14.7 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.5 AI-191.8026.42.35.5977832
Xcode: 11.7/11E801a - /usr/bin/xcodebuild
npmPackages:
expo: ~38.0.8 => 38.0.10
react: ~16.11.0 => 16.11.0
react-dom: ~16.11.0 => 16.11.0
react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
react-native-web: ~0.11.7 => 0.11.7
npmGlobalPackages:
expo-cli: 3.27.4

Windows:

  Expo CLI 3.23.1 environment info:
    System:
      OS: Windows 7 6.1.7601
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~38.0.8 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

### Reproducible Demo
 https://github.com/dev-sk-master/expotest

### Steps to Reproduce
- git clone https://github.com/dev-sk-master/expotest
- cd expotest && yarn install
- expo build:ios --public-url https://dev-sk-master.github.io/expoTest/ios-index.json
   OR
  expo build:android --public-url https://dev-sk-master.github.io/expoTest/android-index.json
- Open result App on iOS or Android

### Expected Behavior vs Actual Behavior 
Expected behaviour app should work as it does on expo start or how it works when public-url is not specified

**Comment by cruzach** [comment]
can you get the native device logs from the crash? you can do this on android by running `adb logcat` with the device plugged in or emulator running

**Comment by dev-sk-master** [comment]
> can you get the native device logs from the crash? you can do this on android by running `adb logcat` with the device plugged in or emulator running

Native device logs

09-15 11:37:13.599  1287  1521 D HiDATA  : APP type: -1 appName= uk.co.webdigi.affinitycarbondev
09-15 11:37:13.600  1287  1521 D HiDATA  : no game, APP_TYPE_GAME, appName =uk.co.webdigi.affinitycarbondev
09-15 11:37:13.609  2782  2880 I ReactNativeJS: Running "main" with {"initialProps":{"exp":{"lastErrors":[{"isFatal":true,"errorMessage":"API key not found.  Check that <meta-data android:name=\"com.google.android.geo.API_KEY\" android:value=\"your API key\"/> is in the <application> element of AndroidManifest.xml","exceptionId":-972560021}],"initialUri":"https://expoupdates.webdigi.co.uk/affinitycarbonapp-dev/android-index.json","manifest":{"web":{"favicon":"./assets/favicon.png"},"id":"@anonymous/affinitycarbondev","bundleUrl":"https://expoupdates.webdigi.co.uk/affinitycarbonapp-dev/bundles/android-cc09ba319572833e243831ef605f3367.js","revisionId":"mR7pq5OldN","platform":"android","locales":{},"releaseId":"06117220-3eb2-4c46-acae-1100f51bed8b","slug":"affinitycarbondev","name":"affinitycarbondev","icon":"./assets/icon.png","loadedFromCache":true,"splash":{"resizeMode":"contain","backgroundColor":"#ffffff","image":"./assets/splash.png","imageUrl":"https://expoupdates.webdigi.co.uk/affinitycarbonapp-dev/assets/b8895f17edbefb9f51b1f863c9811e44"},"orientation":"portrait","publishedTime":"2020-09-10T07:00:06.653Z","iconUrl":"https://expoupdates.webdigi.co.uk/affinitycarbonapp-dev/assets/41aba486029b982d6f7773e6eed0f5b4","isVerified":true,"version":"1.0.2","bundledAssets":["asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_ca9ce9ff0676a9b04ef0f8a3ad17dd08.ttf","asset_54a5c98d22f313098b3dbe2d5b2e87ba.json","asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf","asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_09dd345dbd4ec5a0874841d5749ac153.json","asset_0886a6b127c6057cee83f9c65c7ffd62.json","asset_f6c6f6c8cb7784254ad00056f6fbd74e.ttf","asset_b70cea0339374107969eb53e5b1f603f.ttf","asset_c39278f7abfc798a241551194f55e29f.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b2e0fc821c6886fb3940f85a3320003e.ttf","asset_3e6805fbc794680014716b8c752f20b8.json","asset_3c851d60ad5ef3f2fe43ebd263490d78.ttf","asset_1a0e3525dd5df87e77057204129a5e6e.json","asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf","asset_7e078700f0c35367a56c5bbb2047dda7.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json","asset_fd0192cf977ddf7b60b4e21e332f6b76.json"],"android":{"versionCode":1,"package":"uk.co.webdigi.affinitycarbondev"},"sdkVersion":"38.0.0","platforms":["ios","android","web"],"commitTime":"2020-09-10T07:00:06.653Z","dependencies":["expo","expo-constants","expo-font","expo-status-bar","expo-updates","native-base","react","react-dom","react-native","react-native-maps","react-native-table-component","react-native-web"],"ios":{"buildNumber":"2","supportsTablet":true,"bundleIdentifier":"uk.co.webdigi.affinitycarbondev"},"updates":{"fallbackToCacheTimeout":0,"checkAutomatically":"ON_ERROR_RECOVERY"},"assetUrlOverride":"./assets"},"shell":true}},"rootTag":1}
09-15 11:37:13.775  2782  2881 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.SizeReportingShadowNode
09-15 11:37:13.784  1831  1831 D HwInnerWifiManagerImpl: fetchWifiSignalInfoForVoWiFi
09-15 11:37:13.785  2782  2782 I v0      : Making Creator dynamically
09-15 11:37:13.787  1287 20431 V ActivityManager: Successfully start provider ContentProviderRecord{5350717 u0 com.google.android.gms/.chimera.container.GmsModuleProvider} launchingApp=null caller pid= 2782
09-15 11:37:13.789  1287 20064 E WificondControl: Noise: 0, Snr: -1, Chload: -1
09-15 11:37:13.791  2782  2782 I DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
09-15 11:37:13.791  2782  2782 I DynamiteModule: Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
09-15 11:37:13.791  2782  2782 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
09-15 11:37:13.792  1287 20064 D HwWifiStateMachine: rssi=-60,nativeTxBad=87, nativeTxGood=67842, dpktcnt=1, linkSpeed=72, frequency=2437, noise=0, mac=9c741a
09-15 11:37:13.792  1831  2564 W VoWifiQoe_N: processSignalInfoInd phoneId 1 is not qoe started!
09-15 11:37:13.792  2782  2782 I DynamiteLoaderV2Impl: [71] Mapsdynamite
09-15 11:37:13.793  2782  2782 W finitycarbonde: Unsupported class loader
09-15 11:37:13.796  2782  2782 W finitycarbonde: Skipping duplicate class check due to unsupported classloader
09-15 11:37:13.818  2782  2782 I Google Maps Android API: Google Play services client version: 12451000
09-15 11:37:13.824  2782  2782 I Google Maps Android API: Google Play services package version: 203315030
09-15 11:37:13.842  2782  2782 W System.err: java.lang.reflect.InvocationTargetException
09-15 11:37:13.843  2782  2782 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:4)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:1)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:5)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:2)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:809)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.os.Handler.handleCallback(Handler.java:907)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.os.Looper.loop(Looper.java:216)
09-15 11:37:13.843  2782  2782 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
09-15 11:37:13.843  2782  2782 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
09-15 11:37:13.843  2782  2782 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
09-15 11:37:13.843  2782  2782 W System.err: Caused by: com.facebook.react.common.JavascriptException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
09-15 11:37:13.843  2782  2782 W System.err: 	at host.exp.exponent.ReactNativeStaticHelpers.handleReactNativeError(ReactNativeStaticHelpers.java:2)
09-15 11:37:13.843  2782  2782 W System.err: 	... 18 more
09-15 11:37:13.994  1831  1831 D HwInnerWifiManagerImpl: fetchWifiSignalInfoForVoWiFi
09-15 11:37:13.994  1287 20895 D HwWifiService: HwWifiService  FETCH_WIFI_SIGNAL_INFO_FOR_VOWIFI 
09-15 11:37:13.997  1287 20895 E WificondControl: Noise: 0, Snr: -1, Chload: -1
09-15 11:37:13.997  1287 20895 D HwWifiStateMachine: rssi=-60,nativeTxBad=87, nativeTxGood=67844, dpktcnt=2, linkSpeed=72, frequency=2437, noise=0, mac=9c741a
09-15 11:37:13.998  1831  2564 W VoWifiQoe_N: processSignalInfoInd phoneId 1 is not qoe started!
09-15 11:37:14.015  1287  1460 D hw_netstat: total/9062/2379,uk.co.webdigi.affinitycarbondev/8559/2379,unknown:0/298/0,unknown:1051/205/0
09-15 11:37:14.126   681  3048 I iked    : [INFO]: ikev2.c:305: ikev2_periodic_task()
09-15 11:37:14.126   681  3048 D iked    : [DEBUG]: ike_sa.c:323: ike_sa: 0x7bb4e44600 state 7 req_ipsecid 0
09-15 11:37:14.127   681  3048 D iked    : [DEBUG]: ike_sa.c:327: child_sa: 0x7bb4e47400 state 4
09-15 11:37:14.176   706   741 D AwareLog: iawared: WorkingsetProcessCommand subCmd = 357, userId=10375, pid=2782, uk.co.webdigi.affinitycarbondev
09-15 11:37:14.177   706   741 D AwareLog: iawared: WorkingsetPauseCollect uk.co.webdigi.affinitycarbondev
09-15 11:37:14.200  1831  1831 D HwInnerWifiManagerImpl: fetchWifiSignalInfoForVoWiFi
09-15 11:37:14.206  1287 20895 E WificondControl: Noise: 0, Snr: -1, Chload: -1
09-15 11:37:14.207  1287 20895 D HwWifiStateMachine: rssi=-60,nativeTxBad=87, nativeTxGood=67844, dpktcnt=0, linkSpeed=72, frequency=2437, noise=0, mac=9c741a
09-15 11:37:14.208  1831  2564 W VoWifiQoe_N: processSignalInfoInd phoneId 1 is not qoe started!
09-15 11:37:14.288  1287  1458 I TrafficMonitor: expired arrive. level:-1
09-15 11:37:14.288  1287  1458 I TrafficMonitor: during_ms:2001,period_ms:2000
09-15 11:37:14.289  1287  1458 I TrafficMonitor: count:13,rx_sum:19,tx_sum:20,rxBytes:7264,during_ms:2001,rx_speed:3630.184907546227,tx_speed:1039.480259870065,rto:0.95
09-15 11:37:14.411  1831  1831 D HwInnerWifiManagerImpl: fetchWifiSignalInfoForVoWiFi
09-15 11:37:14.416  1287 20895 E WificondControl: Noise: 0, Snr: -1, Chload: -1
09-15 11:37:14.416  1287 20895 D HwWifiStateMachine: rssi=-59,nativeTxBad=87, nativeTxGood=67847, dpktcnt=3, linkSpeed=72, frequency=2437, noise=0, mac=9c741a
09-15 11:37:14.417  1831  2564 W VoWifiQoe_N: processSignalInfoInd phoneId 1 is not qoe started!
09-15 11:37:14.433  1287  1287 I MQoS    : onSignal: mSubId=0,currDataSubID=0
09-15 11:37:14.436  1714  1714 D DaemonMessageAdapter: onMobileSignalStrengthChanged, subId: 0, signalStrength: SignalStrength: 0 893357440 -1 -1 -1 -1 -1 -1 -105 -11 2 -1 0 2147483647 0 120 2147483647 255 gsm|lte use_rsrp_and_rssnr_for_lte_level rscp [-128, -118, -108, -98] [-115, -105, -95, -85] 0 0 0 0 0 0
09-15 11:37:14.437  1287  1287 I MQoS    : received cell-signal:5
09-15 11:37:14.438  1287 17672 I MQoS    : QOS_level:0(0),DataDisable;use level-0
09-15 11:37:14.439  1714  1714 D DaemonMessageAdapter: SignalStrength update result, ss: SignalStrengthInfo: 140510341 mGsmSignalStrength: 0 mWcdmaRscp: 2147483647 mWcdmaEcio: 255 mLteRsrp: -105 mLteRsrq: -11 mCdmaDbm: -1 mCdmaEcio: -1 mEvdoDbm: -1 mEvdoEcio: -1 mLteRssnr: 2
09-15 11:37:14.442  1831  1831 D Mapcon  : TelephonyTracker: onSignalStrengthsChanged:phoneId=0, level=4
09-15 11:37:14.445  1831  2462 D Mapcon  : SMVoice-0-Normal: LinkConfigState:defaultStatehandle msg=CMD_SIGNAL_STRENGTH_CHANED_IND
09-15 11:37:14.446  1714  1714 D Hicom_SysEnvMonitor: onMobileSignalStrengthChanged
09-15 11:37:14.448  1714  1873 I HidataAppQoeP: handleStateChanged reason=6
09-15 11:37:14.452  1714  1873 I PreDnsQuery: handleStateChanged reason=6
09-15 11:37:14.454  1585  1687 I HwMobileSignalController(0): subId:0 phoneType:1 networktype:13 targetClass:3 masterLevel:4 slaveLevel:-1
09-15 11:37:14.455  1714  1873 I BrowserChrP: handleStateChanged
09-15 11:37:14.460  1585  1585 I HwMobileSignalController(0): getTypeIconHuawei: mIsShowNetworkType is false and return 0
09-15 11:37:14.600  2782  2792 E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
09-15 11:37:14.619  1831  1831 D HwInnerWifiManagerImpl: fetchWifiSignalInfoForVoWiFi
09-15 11:37:14.620  1287 20895 D HwWifiService: HwWifiService  FETCH_WIFI_SIGNAL_INFO_FOR_VOWIFI 
09-15 11:37:14.625  1287 20895 E WificondControl: Noise: 0, Snr: -1, Chload: -1
09-15 11:37:14.625  1287 20895 D HwWifiStateMachine: rssi=-59,nativeTxBad=87, nativeTxGood=67849, dpktcnt=2, linkSpeed=72, frequency=2437, noise=0, mac=9c741a
09-15 11:37:14.626  1831  2564 W VoWifiQoe_N: processSignalInfoInd phoneId 1 is not qoe started!
09-15 11:37:14.667 16240  2919 I Authzen : [DeviceStateSyncManager] The server is in sync with current state. Nothing to do
09-15 11:37:14.735  2782  2792 I finitycarbonde: Background concurrent copying GC freed 158960(9MB) AllocSpace objects, 23(716KB) LOS objects, 77% free, 3MB/15MB, paused 582us total 134.696ms

**Comment by cruzach** [comment]
@dev-sk-master sorry for the late response- are you still seeing this? From the error message, it looks like the google maps api key is missing, but it's in app.json, so you should open the apk with `apktool` or similar and check the androidmanifest for that property

**Comment by cruzach** [comment]
Closing for inactivity, if you're seeing this behavior please open a new issue
