### ISSUE TITLE
[jest-expo-enzyme] transformIgnorePatterns and possibly other configurations overwritten.

### ISSUE THREAD

**Issue by mlorencs** [expo/expo#10211]
Hello everyone!

Yesterday I came across an interesting problem with [jest-expo-enzyme](https://github.com/expo/expo/tree/master/packages/jest-expo-enzyme) package. When I try to run my tests, I get:

```
SyntaxError: Unexpected token 'export'

      export { NativeRouter as Router, Switch, Route } from "react-router-native";

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/lib/router/index.js:1:1)
```

Alright, this error lets me know that I need to include `react-router-native` in my `transformIgnorePatterns` configuration:

`jest.config.js`
```
...
// An array of regexp pattern strings that are matched against all source file paths, matched files will skip transformation
transformIgnorePatterns: [
    "node_modules/(?!(react-native|react-router-native))",
],
```

After doing so, the error still persists and that is because of this:

`jest.config.js`
```
...
// Run tests from one or more projects
projects: [
    withEnzyme(require("jest-expo/ios/jest-preset")),
    withEnzyme(require("jest-expo/android/jest-preset")),
    withEnzyme(require("jest-expo/web/jest-preset")),
],
```

These `jest-preset` files set their own `transformIgnorePatterns` configuration and ignores mine:

`node_modules/jest-expo/ios/jest-preset.js`
```
const { getIOSPreset } = require('../config/getPlatformPreset');
module.exports = getIOSPreset();
```

`node_modules/jest-expo/android/jest-preset.js`
```
const { getAndroidPreset } = require('../config/getPlatformPreset');
module.exports = getAndroidPreset();
```

`node_modules/jest-expo/web/jest-preset.js`
```
const { getWebPreset } = require('../config/getPlatformPreset');

module.exports = getWebPreset();
```

Let's take a look how `getPlatformPreset.js` looks like:

`node_modules/jest-expo/config/gePlatformPreset.js`

```
'use strict';
const { getManagedExtensions } = require('@expo/config/paths');

const expoPreset = require('../jest-preset'); <-- it uses another jest-preset file as a base configuration
const { withWatchPlugins } = require('./withWatchPlugins');

function getPlatformPreset(displayOptions, extensions) {
  const moduleFileExtensions = getManagedExtensions(extensions);
  const testMatch = ['', ...extensions].reduce((arr, cur) => {
    const platformExtension = cur ? `.${cur}` : '';
    const sourceExtension = `.[jt]s?(x)`;
    return [
      ...arr,
      `**/__tests__/**/*spec${platformExtension}${sourceExtension}`,
      `**/__tests__/**/*test${platformExtension}${sourceExtension}`,
      `**/?(*.)+(spec|test)${platformExtension}${sourceExtension}`,
    ];
  }, []);

  return withWatchPlugins({
    displayName: displayOptions,
    testMatch,
    moduleFileExtensions,
    snapshotResolver: require.resolve(`../src/snapshot/resolver.${extensions[0]}.js`),
    haste: {
      ...expoPreset.haste,
      defaultPlatform: extensions[0],
      platforms: extensions,
    },
  });
}

// Combine React Native for web with React Native
// Use RNWeb for the testEnvironment
function getBaseWebPreset() {
  let reactNativePreset;
  try {
    reactNativePreset = require('react-native-web/jest-preset');
  } catch (error) {
    console.error(error);
    throw error;
  }
  return {
    ...expoPreset,
    ...reactNativePreset,
    setupFiles: reactNativePreset.setupFiles,
    moduleNameMapper: {
      ...expoPreset.moduleNameMapper,
      // Add react-native-web alias
      // This makes the tests take ~2x longer
      ...reactNativePreset.moduleNameMapper,
    },
  };
}

module.exports = {
  getWebPreset() {
    return {
      ...getBaseWebPreset(),
      ...getPlatformPreset({ name: 'Web', color: 'magenta' }, ['web']),
    };
  },
  getNodePreset() {
    return {
      ...getBaseWebPreset(),
      ...getPlatformPreset({ name: 'Node', color: 'cyan' }, ['node', 'web']),
      testEnvironment: 'node',
    };
  },
  getIOSPreset() {
    return {
      ...expoPreset,
      ...getPlatformPreset({ name: 'iOS', color: 'white' }, ['ios', 'native']),
    };
  },
  getAndroidPreset() {
    return {
      ...expoPreset,
      ...getPlatformPreset({ name: 'Android', color: 'blueBright' }, ['android', 'native']),
    };
  },
};
```

Now let's take a look at that other `jest-preset.js` file:

`node_modules/jest-expo/jest-preset.js`
```
'use strict';

const isEqual = require('lodash/isEqual');
// Derive the Expo Jest preset from the React Native one
const jestPreset = require('react-native/jest-preset'); <-- it uses React Native's Jest preset

// transform
if (!jestPreset.transform) {
  jestPreset.transform = {};
}

const defaultAssetNamePattern = '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$';
if (!jestPreset.transform[defaultAssetNamePattern]) {
  console.warn(`Expected react-native/jest-preset to define transform[${defaultAssetNamePattern}]`);
} else {
  delete jestPreset.transform[defaultAssetNamePattern];
}

const assetNamePattern =
  '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp|ttf|otf|m4v|mov|mp4|mpeg|mpg|webm|aac|aiff|caf|m4a|mp3|wav|html|pdf|obj)$';
jestPreset.transform[assetNamePattern] = require.resolve(
  'jest-expo/src/preset/assetFileTransformer.js'
);

// transformIgnorePatterns
if (!Array.isArray(jestPreset.transformIgnorePatterns)) {
  console.warn(`Expected react-native/jest-preset to define a transformIgnorePatterns array`);
} else if (
  !isEqual(jestPreset.transformIgnorePatterns, [
    'node_modules/(?!(jest-)?react-native|@react-native-community)', <-- this is the React Native's Jest preset default `transformIgnorePatterns` configuration
  ])
) {
  console.warn(
    `react-native/jest-preset contained different transformIgnorePatterns than expected`
  );
}

console.log("jestPreset.transformIgnorePatterns:", jestPreset.transformIgnorePatterns);

// Also please keep `testing-with-jest.md` file up to date
jestPreset.transformIgnorePatterns = [
  'node_modules/(?!(jest-)?react-native|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)', <-- and here transformIgnorePatterns configuration is overwritten. If I add `react-router-native` to this list, the error goes away and tests pass
];

// setupFiles
if (!Array.isArray(jestPreset.setupFiles)) {
  jestPreset.setupFiles = [];
}
jestPreset.setupFiles.push(require.resolve('jest-expo/src/preset/setup.js'));

module.exports = jestPreset;
```

I could add `react-router-native` to `jestPreset.transformIgnorePatterns`, but that edit wouldn't stay there permanently. Another fix could be not to use these presets, but I need them to test iOS, Android and Web platforms all at once. Fix number 3 could be to use `jest` and `enzyme` separately as I was doing before I made the change from `react-native-cli` to `expo-cli`, but then again, it wouldn't include the option to test iOS, Android and Web platforms all at once.

Maybe there's something else I can do?

This is my first time posting an issue on here, so I'm sorry if I missed some details. I can try to provide them later.

**Comment by byCedric** [comment]
Hi @mlorencs! Thanks for the issue report. Unfortunately, if you need to add a custom transformIgnorePatterns package, there isn't an easy way to do this.

You are right that the jest projects each define their own `transformIgnorePatterns ` list. And if you have to modify it, you have to do that for all projects. One thing you could try is _adding_ another transform pattern to the existing one, something like:

```js
function withExtraTransform(config) {
    config.transformIgnorePatterns.push("node_modules/(?!(react-router-native))");
    return config;
}

module.exports = {
    projects: [
        withExtraTransform(withEnzyme(require("jest-expo/ios/jest-preset"))),
        withExtraTransform(withEnzyme(require("jest-expo/android/jest-preset"))),
        withExtraTransform(withEnzyme(require("jest-expo/web/jest-preset"))),
    ],
};
```

If that doesn't work, you can also try to replace the existing pattern. You can see the [full list of modules we add by default](https://github.com/expo/expo/blob/876113b085052598e60c17e1da119a68e7f5ac1e/packages/jest-expo/jest-preset.js#L40), based on this I figure this might work:

```js
function withExtraTransform(config) {
    config.transformIgnorePatterns = [
        'node_modules/(?!(jest-)?react-native|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|react-router-native)',
    ];
    return config;
}
```

Hope this helps!
