### ISSUE TITLE
App crashes/shuts down when remote js debug is activated on SDK 39 for Android

### ISSUE THREAD

**Issue by divonelnc** [expo/expo#10284]
### Summary of Issue 
I just upgraded to expo SDK39, since then my app crashes on **Android** if remote js debugging is activated. There are no crash report, the app just immediately shutdowns during the splash screen.

I do get the following error in the console, but it happened since I moved up to sdk 38 and didn't cause a crash before:
```Error: Unable to resolve module `./debugger-ui/debuggerWorker.cff11639.js` from :```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.7 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.5 - E:\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.0, 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^39.0.0 => 39.0.2
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.13
    Expo Workflow: managed
```

package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@chardskarth/react-gateway": "^3.0.3",
    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/async-storage": "~1.12.0",
    "@react-native-community/checkbox": "^0.5.3",
    "@react-native-community/clipboard": "^1.2.3",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "1.6.6",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/material-bottom-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "@reduxjs/toolkit": "^1.4.0",
    "expo": "^39.0.0",
    "expo-asset": "~8.2.0",
    "expo-constants": "~9.2.0",
    "expo-error-recovery": "~1.3.0",
    "expo-font": "~8.3.0",
    "expo-notifications": "~0.7.2",
    "expo-permissions": "~9.3.0",
    "expo-splash-screen": "~0.6.1",
    "expo-web-browser": "~8.5.0",
    "moment": "^2.29.0",
    "moment-countdown": "0.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-paper": "^3.11.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-redash": "^14.2.4",
    "react-native-remote-svg": "^2.0.6",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-svg": "12.1.0",
    "react-native-web": "~0.13.7",
    "react-native-webview": "10.7.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "sentry-expo": "^2.1.2",
    "tinycolor2": "^1.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "babel-preset-expo": "^8.3.0",
    "jest-expo": "^39.0.0"
  },
  "private": true
}

```

### Steps to Reproduce

All I really did was:

- call `npm update` to upgrade the packages
- use `expo upgrade` to install expo SDK 39

Unfortunately, I do not have a specific repro. The crash happens even when my complete app is only made of:

```
import * as React from "react";
import { View } from "react-native";

export default function App(props) {
	return (
		<View/>
	);
}

```
 
### Expected Behavior vs Actual Behavior
It should not crash when remote js debugging is activated.

**Comment by asmailov** [comment]
I am getting the same issue. 
I can reproduce it by simply doing:

- "expo init MyProject" (basic or any other version)
- npm start
- enabling remote js

**Comment by Legi0n1138** [comment]
Same issue with similar configuration. Can't debug at all. Log from logcat:
```
09-23 14:36:05.164  5564  5623 E Expo    : Cannot initialize app loader. host.exp.exponent.taskManager.ExpoHeadlessAppLoader
09-23 14:36:05.164  5564  5623 W System.err: java.lang.ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader
09-23 14:36:05.164  5564  5623 W System.err:    at java.lang.Class.classForName(Native Method)
09-23 14:36:05.164  5564  5623 W System.err:    at java.lang.Class.forName(Class.java:453)
09-23 14:36:05.164  5564  5623 W System.err:    at java.lang.Class.forName(Class.java:378)
09-23 14:36:05.164  5564  5623 W System.err:    at l.d.a.a.a(AppLoaderProvider.java:2)
09-23 14:36:05.164  5564  5623 W System.err:    at l.d.a.a.b(AppLoaderProvider.java:2)
09-23 14:36:05.164  5564  5623 W System.err:    at expo.modules.taskManager.TaskService.getAppLoader(TaskService.java:2)
09-23 14:36:05.164  5564  5623 W System.err:    at expo.modules.taskManager.TaskService.isStartedByHeadlessLoader(TaskService.java:1)
09-23 14:36:05.164  5564  5623 W System.err:    at expo.modules.taskManager.TaskService.setTaskManager(TaskService.java:2)
09-23 14:36:05.164  5564  5623 W System.err:    at expo.modules.taskManager.TaskManagerInternalModule.onCreate(TaskManagerInternalModule.java:5)
09-23 14:36:05.164  5564  5623 W System.err:    at l.d.b.f.h(ModuleRegistry.java:9)
09-23 14:36:05.164  5564  5623 W System.err:    at l.d.b.f.a(ModuleRegistry.java:2)
09-23 14:36:05.164  5564  5623 W System.err:    at org.unimodules.adapters.react.ModuleRegistryReadyNotifier.initialize(ModuleRegistryReadyNotifier.java:1)
09-23 14:36:05.165  5564  5623 W System.err:    at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:9)
09-23 14:36:05.165  5564  5623 W System.err:    at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:7)
09-23 14:36:05.165  5564  5623 W System.err:    at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:5)
09-23 14:36:05.165  5564  5623 W System.err:    at com.facebook.react.bridge.CatalystInstanceImpl$4.run(CatalystInstanceImpl.java:1)
09-23 14:36:05.165  5564  5623 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
09-23 14:36:05.165  5564  5623 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
09-23 14:36:05.165  5564  5623 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
09-23 14:36:05.165  5564  5623 W System.err:    at android.os.Looper.loop(Looper.java:164)
09-23 14:36:05.165  5564  5623 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
09-23 14:36:05.165  5564  5623 W System.err:    at java.lang.Thread.run(Thread.java:764)
09-23 14:36:05.167  5564  5623 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "host.exp.exponent.taskManager.ExpoHeadlessAppLoader" on path: DexPathList[[zip file "/data/app/host.exp.exponent--ZhXAhZMlfU3n
AeYUclcqw==/base.apk"],nativeLibraryDirectories=[/data/app/host.exp.exponent--ZhXAhZMlfU3nAeYUclcqw==/lib/x86, /data/app/host.exp.exponent--ZhXAhZMlfU3nAeYUclcqw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
09-23 14:36:05.167  5564  5623 W System.err:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
09-23 14:36:05.167  5564  5623 W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-23 14:36:05.167  5564  5623 W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-23 14:36:05.169  5564  5623 W System.err:    ... 22 more

```

**Comment by JeriesNasrawi** [comment]
@brentvatne Hi Brent, any updates on this?

**Comment by Definence** [comment]
same issue here

**Comment by sun21170** [comment]
@Definence , I'm having  the same issue since upgrading to SDK version 39. Could you please share the steps you took to downgrade to version 38, since that would be a workaround for this issue.? Thanks and appreciate it.

**Comment by sun21170** [comment]
> Same issue on newly initialized project with typescript. After manually downgrading to version 38 issue does not appear

@Definence , I'm having the same issue since upgrading to SDK version 39. Could you please share the steps you took to downgrade to version 38, since that would be a workaround for this issue.? Thanks and appreciate it

**Comment by brentvatne** [comment]
this is a bug in react-native:

- https://github.com/facebook/react-native/issues/28844
- https://github.com/react-native-community/cli/issues/1081

**Comment by brentvatne** [comment]
related crash logs:

```
09-24 13:58:04.041 11258 11402 E AndroidRuntime: java.lang.AssertionError: No source URL loaded, have you initialised the instance?
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:2)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.modules.debug.SourceCodeModule.getTypedExportedConstants(SourceCodeModule.java:3)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at abi39_0_0.com.facebook.fbreact.specs.NativeSourceCodeSpec.getConstants(NativeSourceCodeSpec.java:1)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:9)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
09-24 13:58:04.041 11258 11402 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
09-24 13:58:04.051  1646  2302 W ActivityManager:   Force finishing activity host.exp.exponent/.experience.HomeActivity
09-24 13:58:04.057  1646  2302 W ActivityManager:   Force finishing activity host.exp.exponent/.experience.ExperienceActivity
```

**Comment by brentvatne** [comment]
note: this does not impact older sdk versions, even on the latest expo client version. so, if your app is using sdk 38 this will continue working as expected. please hold off upgrading to sdk 39 if this is an important feature for you.

locking this issue for now because there isn't much more that can be said, we will work on a fix to release it next week.

**Comment by brentvatne** [comment]
related PRs to fix this:
- https://github.com/expo/expo/pull/10383
- https://github.com/expo/expo/pull/10381

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/10464#issuecomment-703178030
