### ISSUE TITLE
java.lang.ClassNotFoundException: org.unimodules.adapters.react.apploader.RNHeadlessAppLoader

### ISSUE THREAD

**Issue by alexsegura** [expo/expo#10378]
### Summary of Issue 

When using `expo-location` on a **release** build, the error below appears in logcat. 
Please note it works on debug builds. 

```
E Expo    : Cannot initialize app loader. org.unimodules.adapters.react.apploader.RNHeadlessAppLoader
W memtrack@1.0-se: type=1400 audit(0.0:174604): avc: denied { read } for name="driver_stats" dev="debugfs" ack_default:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=0
W System.err: java.lang.ClassNotFoundException: org.unimodules.adapters.react.apploader.RNHeadlessAppLoader
W System.err:    at java.lang.Class.classForName(Native Method)
W System.err:    at java.lang.Class.forName(Class.java:453)
W System.err:    at java.lang.Class.forName(Class.java:378)
W System.err:    at org.unimodules.apploader.a.a(AppLoaderProvider.java:2)
W System.err:    at org.unimodules.apploader.a.b(AppLoaderProvider.java:2)
W System.err:    at expo.modules.taskManager.h.b(TaskService.java:19)
W System.err:    at expo.modules.taskManager.h.c(TaskService.java:1)
W System.err:    at expo.modules.taskManager.d.f(TaskManagerInternalModule.java:1)
W System.err:    at expo.modules.taskManager.d.onHostResume(TaskManagerInternalModule.java:1)
W System.err:    at org.unimodules.adapters.react.services.d$a.onHostResume(UIManagerModuleWrapper.java:2)
W System.err:    at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:5)
W System.err:    at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(
W System.err:    at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:11)
W System.err:    at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:3)
W System.err:    at com.facebook.react.q.g(ReactDelegate.java:5)
W System.err:    at com.facebook.react.n.j(ReactActivityDelegate.java:1)
W System.err:    at com.facebook.react.m.onResume(ReactActivity.java:2)
W System.err:    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1449)
W System.err:    at android.app.Activity.performResume(Activity.java:8762)
W System.err:    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3837)
W System.err:    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3877)
W System.err:    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
W System.err:    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(
W System.err:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
W System.err:    at android.os.Looper.loop(Looper.java:193)
W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6865)
W System.err:    at java.lang.reflect.Method.invoke(Native Method)
W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class apploader.RNHeadlessAppLoader" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file .runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/TZWQ==/base.apk"],nativeLibraryDirectories=[/data/app/fr.coopcycle-iELlRSCBCFdwNFu_wYTZWQ==/lib/arm64, /data/app/TZWQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
W System.err:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E IMGMemtrackHAL: DbgFsParseFile: fopen of /d/pvr/driver_stats failed (Permission denied)
W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W System.err:    ... 31 more
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.24.0 environment info:
    System:
      OS: macOS Mojave 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
      react-navigation: ^4.4.1 => 4.4.1
    npmGlobalPackages:
      expo-cli: 3.24.0
```

I'm targeting Android.

### Reproducible Demo

```es6
const options = {
  accuracy: Location.Accuracy.BestForNavigation,
  distanceInterval: 10,
  deferredUpdatesInterval: 5000,
  foregroundService: {
    notificationTitle: i18n.t('BACKGROUND_GEOLOCATION_NOTIFICATION_TITLE'),
    notificationBody: i18n.t('BACKGROUND_GEOLOCATION_NOTIFICATION_TEXT'),
  },
}
TaskManager.defineTask('location-updates', ({ data: { locations }, error }) => {
   // do stuff
})
Location.requestPermissionsAsync().then((permissions) => {
  if (permissions.status === 'granted') {
    Location.startLocationUpdatesAsync('location-updates', options)
      .then(() => console.log('It works'))
  }
})
```

The source code of the app is [here](https://github.com/coopcycle/coopcycle-app)
The Redux middleware responsible for initializing `expo-location` is [here](https://github.com/coopcycle/coopcycle-app/blob/9d2a0569e37e4ec1cda3768919b42ad944f9c2a2/src/redux/middlewares/GeolocationMiddleware/index.android.js)
 
### Steps to Reproduce

Create a release build of the app. The task is never called. 

### Expected Behavior vs Actual Behavior

The task should be called to post location updates to server.

**Comment by byCedric** [comment]
Hi @alexsegura, thanks for the report. I think you are missing some proguard rules, and because of that, it removes the necessary classes. You can [see the rules you need to add here](https://github.com/expo/expo/tree/master/packages/%40unimodules/core#android). We just encountered some issues with Proguard, and you might have to add additional rules. This should work:

```
# From the core unimodules docs
-keepclassmembers class * {
  @org.unimodules.interfaces.ExpoProp *;
}
-keepclassmembers class * {
  @org.unimodules.interfaces.ExpoMethod *;
}

# Additional rules you might need as well
-keep @org.unimodules.core.interfaces.DoNotStrip class *
-keepclassmembers class * {
  @**.expo.core.interfaces.DoNotStrip *;
}

# And if that doesn't help, try force-including this class directly
-keep org.unimodules.adapters.react.apploader.RNHeadlessAppLoader
```

Hope this helps!

**Comment by alexsegura** [comment]
Thanks!

Unfortunately, I switched to [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) in the meantime because it was a big problem for our users. 

I followed the [installation instructions](https://docs.expo.io/bare/installing-unimodules/) found in the Expo website, and they don't mention the proguard rules, maybe it would be worth to mention them on the docs website too?

**Comment by byCedric** [comment]
That's alright, good that you fixed the issue for your users. Again, sorry for the trouble it caused you and your users.

We are currently double-checking the effects of the changes in our Proguard configuration. Eventually, it shouldn't affect you (or any other react native dev) and you don't have to manually include it. Basically, it should work out of the box. But before the Proguard changes, this wasn't happening.
