### ISSUE TITLE
🐛 App crashes after adding enableDangerousExperimentalLeanBuilds in app.json

### ISSUE THREAD

**Issue by AbdnhVmpr** [expo/expo#10569]
## 🐛 Bug Report

**package.json**

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}
```

**app.json**

```
{
  "expo": {
    "name": "my_app",
    "slug": "my_app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "android": {
      "package": "com.myapp",
      "versionCode": 1,
      "enableDangerousExperimentalLeanBuilds": true
    }
  }
}
```

The app works fine in development, but when I add **enableDangerousExperimentalLeanBuilds** in app.json file and I build the App Bundle, the application crashes after installing and opening it on my device. I thought the problem was from the splash screen package, but after spending the whole day testing. I finally could figure out the problem.

The problem happens only with the latest expo SDK 39

**Comment by brentvatne** [comment]
what do you see in your android device logs?

**Comment by AbdnhVmpr** [comment]
Everything looks fine on my android device logs.
I use this property in order to reduce the app bundle size, **If set to true, APK will contain only unimodules that are explicitly added in package.json and their dependecies**

**Comment by brentvatne** [comment]
try adding `expo-splash-screen` to your app

**Comment by AbdnhVmpr** [comment]
Still not working :/

**Comment by brentvatne** [comment]
sorry, you may have to eject if you would like more control over your app size for now. we'll look into this but it's an experimental feature and we don't offer any stability guarantees for it

**Comment by AbdnhVmpr** [comment]
Unfortunately I'm not able to eject,
Larger apps see lower install and update success rates and take up device storage on user's devices. I hope there will be a solution for this soon, It was working fine with the older expo SDKs but I had to upgrade in order to use Facebook audience network

**Comment by brentvatne** [comment]
it looks like this is caused by notifications:

```
10-05 16:56:04.584 25196 25240 E AndroidRuntime: Process: com.notbrent.experimentallean, PID: 25196
10-05 16:56:04.584 25196 25240 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lexpo/modules/notifications/notifications/scheduling/NotificationScheduler;
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at host.exp.exponent.experience.s.createNativeModules(DetachedModuleRegistryAdapter.java:10)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at versioned.host.exp.exponent.ExponentPackage.createNativeModules(ExponentPackage.java:31)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:7)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:8)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:6)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:8)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:6)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:1)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:12)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "expo.modules.notifications.notifications.scheduling.NotificationScheduler" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.notbrent.experimentallean-vJafEcZPFO6cWcPtLegWlw==/base.apk"],nativeLibraryDirectories=[/data/app/com.notbrent.experimentallean-vJafEcZPFO6cWcPtLegWlw==/lib/x86, /data/app/com.notbrent.experimentallean-vJafEcZPFO6cWcPtLegWlw==/base.apk!/lib/x86, /system/lib]]
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-05 16:56:04.584 25196 25240 E AndroidRuntime: 	... 10 more
10-05 16:56:04.590 19390 20110 W ActivityManager:   Force finishing activity com.notbrent.experimentallean/host.exp.exponent.MainActivity
```

**Comment by AbdnhVmpr** [comment]
Thank you! I will be waiting

**Comment by brentvatne** [comment]
@AbdnhVmpr - you can work around this for now by installing `expo-notifications` - i just tested this. `expo install expo-notifications`

**Comment by brentvatne** [comment]
this is currently being deployed to production and will be live in ~20 minutes.

**Comment by ssiju** [comment]
I have installed expo-notifications, but it enableDangerousExperimentalLeanBuild is not working.

**Comment by brentvatne** [comment]
@ssiju - install expo-updates

**Comment by ssiju** [comment]
Thank You! @brentvatne Right now it's working fine.
and thanks for your support!

**Comment by shahidcodes** [comment]
@brentvatne  Unfortunately for me its throwing this error after installing `expo-updates` and `expo-splash-screen` when I run `expo build:android -t apk`
```
Cannot find module 'jsonfile/utils'
Require stack:
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\configure-splash-screen\node_modules\fs-extra\lib\json\output-json.js
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\configure-splash-screen\node_modules\fs-extra\lib\json\index.js
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\configure-splash-screen\node_modules\fs-extra\lib\index.js
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\configure-splash-screen\build\ios\index.js- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\configure-splash-screen\build\index.js    
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\config-plugins\build\android\SplashScreen.js
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\config-plugins\build\android\index.js     
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\config-plugins\build\index.js
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\config\build\plugins\withConfigPlugins.js 
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\config\build\Config.js
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\node_modules\@expo\config\build\index.js
- E:\projects\react-native\rnapp\node_modules\@expo\metro-config\build\ExpoMetroConfig.js
- E:\projects\react-native\rnapp\metro.config.js
- E:\projects\react-native\rnapp\node_modules\cosmiconfig\node_modules\import-fresh\index.js
- E:\projects\react-native\rnapp\node_modules\cosmiconfig\dist\loaders.js
- E:\projects\react-native\rnapp\node_modules\cosmiconfig\dist\createExplorer.js
- E:\projects\react-native\rnapp\node_modules\cosmiconfig\dist\index.js
- E:\projects\react-native\rnapp\node_modules\metro-config\src\loadConfig.js
- E:\projects\react-native\rnapp\node_modules\metro-config\src\index.js
- E:\projects\react-native\rnapp\node_modules\metro\src\commands\build.js
- E:\projects\react-native\rnapp\node_modules\metro\src\index.js
- C:\Users\shaah\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\@expo\dev-server@0.1.48\node_modules\@expo\dev-server\build\MetroDevServer.js
- C:\Users\shaah\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\@expo\xdl@59.0.14_typescript@4.1.3\node_modules\@expo\xdl\build\Project.js- C:\Users\shaah\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\@expo\xdl@59.0.14_typescript@4.1.3\node_modules\@expo\xdl\build\xdl.js    
- C:\Users\shaah\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\expo-cli@4.0.17_typescript@4.1.3\node_modules\expo-cli\build\exp.js       
- C:\Users\shaah\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\expo-cli@4.0.17_typescript@4.1.3\node_modules\expo-cli\bin\expo.js
