### ISSUE TITLE
[crash] Unable to pause activity: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.unimodules.interfaces.taskManager.TaskInterface.getAppId()' on a null object reference

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#10577]
### Summary of Issue 

Hi, I'm getting this error after the first start my app when I update from Expo SDK 36 to SDK 39.
I've an app with Expo 36 (Bare workflow) and I updating to SDK 39.

I get the crash when I follow this steps:
1. Install my old APK with Expo 36
2. Start the app
3. Install the new APK with Expo 39
4. Start the app
5. Close the app, no kill
6. I get **AppName has stopped** error

This crash appear only one time, after the first close. If I open the app again and close, works perfect. Just happen after an update and after the first close.

If I make a fresh install (uninstall the old version from the device and then install the newest), the app works perfect.

I also updating from `expo-background-fetch: 8.0.0 -> 8.5.0`

Logcat:
```
2020-10-06 11:05:35.234 28413-28413/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxx, PID: 28413
    java.lang.RuntimeException: Unable to pause activity {com.xxx.xxx/host.exp.exponent.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.unimodules.interfaces.taskManager.TaskInterface.getAppId()' on a null object reference
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3912)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.unimodules.interfaces.taskManager.TaskInterface.getAppId()' on a null object reference
        at expo.modules.taskManager.TaskManagerUtils.createTaskIntent(TaskManagerUtils.java:191)
        at expo.modules.taskManager.TaskManagerUtils.createTaskIntent(TaskManagerUtils.java:46)
        at expo.modules.backgroundfetch.BackgroundFetchTaskConsumer.startAlarm(BackgroundFetchTaskConsumer.java:132)
        at expo.modules.backgroundfetch.BackgroundFetchTaskConsumer.onHostPause(BackgroundFetchTaskConsumer.java:167)
        at expo.modules.taskManager.TaskManagerInternalModule.onHostPause(TaskManagerInternalModule.java:136)
        at org.unimodules.adapters.react.services.UIManagerModuleWrapper$3.onHostPause(UIManagerModuleWrapper.java:135)
        at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:267)
        at com.facebook.react.ReactInstanceManager.moveToBeforeResumeLifecycleState(ReactInstanceManager.java:728)
        at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:535)
        at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:557)
        at com.facebook.react.ReactDelegate.onHostPause(ReactDelegate.java:63)
        at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:95)
        at com.facebook.react.ReactActivity.onPause(ReactActivity.java:51)
        at android.app.Activity.performPause(Activity.java:7153)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878) 
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826) 
        at android.app.ActivityThread.-wrap15(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.3
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: bare
```

### Expected Behavior vs Actual Behavior

**Expected Behavior**: _AppName has stopped_ crash
**Actual Behavior**: No Crash

**Comment by cruzach** [comment]
hey @RodolfoGS , could you provide a minimal reproducible demo? without that we can't really investigate much further

**Comment by RodolfoGS** [comment]
How can I create a new Bare project with Expo SDK 36?

**Comment by cruzach** [comment]
I thought the crash started happening after upgrading to SDK 39?

**Comment by RodolfoGS** [comment]
Yes, the crash appear after upgrading to SDK 39 (from sdk 36), but see the steps that I described. Only appears one time, after you install the app's update with SDK 39. If you remove the app and make a fresh install, all works perfect. So, this is the reason that I need to create two repo demos, one with SDK 36 and one with SDK 39 to reproduce installing the update.

**Comment by brentvatne** [comment]
```
expo init --template expo-template-bare-minimum@sdk-36
```

**Comment by RodolfoGS** [comment]
I'm trying to create the repro demos, but in the meanwhile I created a patch.
With this simple patch that can be used with `patch-package` the crash disapear and background tasks works perfect.

```
diff --git a/node_modules/expo-background-fetch/android/src/main/java/expo/modules/backgroundfetch/BackgroundFetchTaskConsumer.java b/node_modules/expo-background-fetch/android/src/main/java/expo/modules/backgroundfetch/BackgroundFetchTaskConsumer.java
index 2ac8b12..104c473 100644
--- a/node_modules/expo-background-fetch/android/src/main/java/expo/modules/backgroundfetch/BackgroundFetchTaskConsumer.java
+++ b/node_modules/expo-background-fetch/android/src/main/java/expo/modules/backgroundfetch/BackgroundFetchTaskConsumer.java
@@ -119,6 +119,10 @@ public class BackgroundFetchTaskConsumer extends TaskConsumer implements TaskCon
   }

   private void startAlarm() {
+    if (mTask == null) {
+      return;
+    }
+
     Context context = getContext();
     AlarmManager alarmManager = getAlarmManager();
```

**Comment by RodolfoGS** [comment]
Sorry but I was not able to create a reproducible demo with `Expo SDK 36` + `expo-task-manager:8.0.0` because I'm getting an error after install `expo-task-manager`.

Steps to get this new error (**not important**):
```
expo init --template expo-template-bare-minimum@sdk-36 ExpoTest
cd ExpoTest
expo install expo-task-manager@8.0.0
Run app in your device and You will get this error when the app start:


E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke interface method 'void org.unimodules.interfaces.taskManager.TaskServiceInterface.setTaskManager(org.unimodules.interfaces.taskManager.TaskManagerInterface, java.lang.String, java.lang.String)' on a null object reference
        at expo.modules.taskManager.TaskManagerInternalModule.onCreate(TaskManagerInternalModule.java:52)
        at org.unimodules.core.ModuleRegistry.initialize(ModuleRegistry.java:149)
        at org.unimodules.core.ModuleRegistry.ensureIsInitialized(ModuleRegistry.java:131)
        at org.unimodules.adapters.react.ModuleRegistryReadyNotifier.initialize(ModuleRegistryReadyNotifier.java:28)
        at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:222)
        at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:97)
        at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:102)
        at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:441)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
```

So, This error is not important because only appear with expo36, but for this reason that I'm unable to create a demo.
As I mentioned, the error only appears when you install an APK with SDK36 and then install an APK updated to SDK39.

I could fixed it adding the condition that I mentioned in my previous comment. I created a PR with this fix https://github.com/expo/expo/pull/10587
