### ISSUE TITLE
[SDK39] Android 10 app crashes at startup : java.lang.RuntimeException: Canvas: trying to draw too large bitmap

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#10580]
### Summary of Issue 

My app after migration from sdk38 to sdk39 is working fine on iOS, on Android 9 (huawei), but no more on Samsung's Android 10 (it worked on sdk38) -> it crashes on Android 10 (real device, reproduced also on Pixel 2XL simulator).
tested with react-native 0.63.3 and sdk-39.0.3.tar.gz, same behaviour.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.27.13 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.20.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 24, 25, 26, 27, 28
        Build Tools: 18.1.0, 21.1.2, 22.0.1, 23.0.1, 23.0.3, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.0
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed
```

### Reproducible Demo

No
 
### Steps to Reproduce

Launch expo, launch app in dev mode, it crashes immediatly

### Expected Behavior vs Actual Behavior

Here is the log from simulator's logcat :

```
2020-10-06 23:19:24.989 8531-8531/host.exp.exponent D/SoLoader: init exiting

    --------- beginning of system
2020-10-06 23:19:25.028 8531-8531/host.exp.exponent W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@9bcb22 0
2020-10-06 23:19:25.050 8531-8531/host.exp.exponent W/c: Could not find listener for key: experienceActivityKernelDidLoad
2020-10-06 23:19:25.051 8531-8531/host.exp.exponent W/c: Could not find listener for key: openOptimisticExperienceActivity
2020-10-06 23:19:25.051 8531-8531/host.exp.exponent W/c: Could not find listener for key: openExperienceActivity
2020-10-06 23:19:25.089 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:25.107 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:25.179 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:25.214 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:25.496 8531-8531/host.exp.exponent W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
2020-10-06 23:19:25.500 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:25.507 8531-8531/host.exp.exponent D/SoLoader: init exiting
2020-10-06 23:19:25.521 8531-8531/host.exp.exponent W/c: Could not find listener for key: loadBundleForExperienceActivity
2020-10-06 23:19:25.521 8531-8531/host.exp.exponent E/q: java.lang.NoSuchFieldException: No field numActivities in class Landroid/app/ActivityManager$RecentTaskInfo; (declaration of 'android.app.ActivityManager$RecentTaskInfo' appears in /system/framework/framework.jar)
2020-10-06 23:19:25.524 8531-8531/host.exp.exponent W/unknown:ReactRootView: Unable to update root layout specs for uninitialized ReactInstanceManager
2020-10-06 23:19:25.528 8531-8622/host.exp.exponent D/q: Successfully called ExponentKernel.addHistoryItem in kernel JS.
2020-10-06 23:19:25.552 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:25.565 8531-8531/host.exp.exponent E/e: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
2020-10-06 23:19:25.570 8531-8531/host.exp.exponent D/SoLoader: init exiting
2020-10-06 23:19:25.572 8531-8531/host.exp.exponent D/SoLoader: About to load: libjscexecutor_abi39_0_0.so
2020-10-06 23:19:25.572 8531-8531/host.exp.exponent D/SoLoader: libjscexecutor_abi39_0_0.so not found on /data/data/host.exp.exponent/lib-main
2020-10-06 23:19:25.572 8531-8531/host.exp.exponent D/SoLoader: libjscexecutor_abi39_0_0.so found on /data/app/host.exp.exponent-Jtb4zHjOqqCwTXoagQYndg==/lib/x86
2020-10-06 23:19:25.572 8531-8531/host.exp.exponent D/SoLoader: Not resolving dependencies for libjscexecutor_abi39_0_0.so
2020-10-06 23:19:25.653 8531-8531/host.exp.exponent D/SoLoader: Loaded: libjscexecutor_abi39_0_0.so
2020-10-06 23:19:25.653 8531-8531/host.exp.exponent D/SoLoader: init exiting
2020-10-06 23:19:25.667 8531-8531/host.exp.exponent W/unknown:ReactNative: Packager connection already open, nooping.
2020-10-06 23:19:25.702 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:25.729 8531-8544/host.exp.exponent I/st.exp.exponen: NativeAlloc concurrent copying GC freed 72637(4122KB) AllocSpace objects, 11(300KB) LOS objects, 49% free, 5901KB/11MB, paused 142us total 115.642ms
2020-10-06 23:19:25.730 8531-8546/host.exp.exponent W/System: A resource failed to call close. 
2020-10-06 23:19:25.976 8531-8590/host.exp.exponent D/EGL_emulation: eglMakeCurrent: 0xe2e1aa80: ver 3 0 (tinfo 0xe2ee91a0)
2020-10-06 23:19:26.441 8531-8531/host.exp.exponent D/AndroidRuntime: Shutting down VM


    --------- beginning of crash
2020-10-06 23:19:26.442 8531-8531/host.exp.exponent E/AndroidRuntime: FATAL EXCEPTION: main
    Process: host.exp.exponent, PID: 8531
    java.lang.RuntimeException: Canvas: trying to draw too large(193632768bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at d.j.a.u.draw(PicassoDrawable.java:11)
        at android.widget.ImageView.onDraw(ImageView.java:1434)
        at android.view.View.draw(View.java:21421)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.draw(View.java:21424)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.draw(View.java:21424)
        at com.android.internal.policy.DecorView.draw(DecorView.java:806)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3610)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3418)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-10-06 23:19:26.462 8531-8531/host.exp.exponent I/Process: Sending signal. PID: 8531 SIG: 9
```

**Comment by lc3t35** [comment]
It seems to be related to the splash screens in splash/android/drawable-[hlm|xh|xxh]dpi/splash.png files ?

**Comment by lc3t35** [comment]
I've noticed also a missing library on expo : 

```
2020-10-06 23:19:25.572 8531-8531/host.exp.exponent D/SoLoader: libjscexecutor_abi39_0_0.so not found on /data/data/host.exp.exponent/lib-main
2020-10-06 23:19:25.572 8531-8531/host.exp.exponent D/SoLoader: libjscexecutor_abi39_0_0.so found on /data/app/host.exp.exponent-Jtb4zHjOqqCwTXoagQYndg==/lib/x86
```

**Comment by brentvatne** [comment]
@lc3t35 - can you share the exact images that you're using?

**Comment by lc3t35** [comment]
Here you are : 
[android.zip](https://github.com/expo/expo/files/5337075/android.zip)

**Comment by bbarthec** [comment]
@lc3t35, some answers for your questions/problems:

#### Regarding config in `app.json`:

> Is there a problem keeping "splash" at top key here when you have "splash" in ios and android?

No, there's no problem with that. You can have more specific platform configuration alongside the more generic one in top-level `splash` config.


#### Regarding `COVER` mode: 

As you're using `resizeMode = COVER` you can drop platform specific splash configuration (with all these `*-dpi` images) & stick with the general one providing only `image, backgroundColor & resizeMode` once in top-level `splash` options.


# Regarding the splash images of yours:

I've checked your images: these are simply too large to fit into device's memory 😞
In `managed workflow` & with the mode `COVER` our app is picking the biggest image available, so it will be this one provided via `xxxhdpi`. As I can see this image is 4968 × 9744 pixels, so it's enormous (4968 * 9744 * 4 color channel = 193632768 bytes (the number that occurs in error stacktrace)) ... 😞

Google is providing some information about screen available screen sizes on the market: https://material.io/blog/device-metrics. My advice for you is to scale down your biggest image to reach dimensions of ~1080 x XXXX px and provide is as a single point of truth for your Android splash.


#### Solution suggestion:

I've checked that the image that you're providing in `mdpi` folder is your baseline (1242 × 2436 pixels) and all the rest are upscaled (all these in `***hdpi` folders.
I advice you to keep only this `mdpi` and drop the rest from your project 💪

**Comment by lc3t35** [comment]
Thank you @bbarthec, FYI splash images were generated by AdobeXP (standard export). Compressed sizes are reasonable (from 131k to 1,1M). The xxxhdpi is a 1,1MB png file, I don't know why it tries to uncompress it as a bitmap ?
So the solution is to provide only one folder (mdpi), remove all the others and change app.json accordingly ?

```
"splash": {
        "ldpi": "./assets/splash/android/drawable-ldpi/splash.png",
        "mdpi": "./assets/splash/android/drawable-mdpi/splash.png",
        "hdpi": "./assets/splash/android/drawable-mdpi/splash.png",
        "xhdpi": "./assets/splash/android/drawable-mdpi/splash.png",
        "xxhdpi": "./assets/splash/android/drawable-mdpi/splash.png",
        "xxxhdpi": "./assets/splash/android/drawable-mdpi/splash.png",
        "backgroundColor": "#6C5AEE",
        "resizeMode": "cover"
      }
```

**Comment by bbarthec** [comment]
@lc3t35, every image has to be uncompressed to raw bitmap in order to be presented on the screen. The problem with the images of yours is not their compressed weight (131k to 1,1M), but their dimensions (up to 4968 * 9744 pixels) what results in lack of memory.

And to answer you question: yes, that is correct.
Side note: our documentation regarding `*dpi` is not up to date from what I can see. These `*dpi` fields are only used in `NATIVE` resizeMode and not in `COVER` mode.

**Comment by lc3t35** [comment]
As it will be an ejected app, I'll have to pay attention to this resizeMode.
But for now with the same splash assigned to all *dpi above mdpi and COVER mode, it works fine.

**Comment by bbarthec** [comment]
Yeah, you're absolutely right that the documentation is lacking at many places 😞 
I'm not an Abode XD expert, but this feel strange to me that the baseline image (`mdpi`) is of size 1242 × 2436 pixels (and thus the 4x image is hitting the 8k resolution - the recent top level devices are having the screens with e.g. [1440 x 3088 pixels](https://www.gsmarena.com/samsung_galaxy_note20_ultra_5g-10261.php), so as you can guess this 8k image is scaled down more than 2 times when displaying on the device) 🤔

**Comment by chengsokdara** [comment]
I just release an bare workflow app, and the only crash  I saw was related to expo-splash-screen, especially on Galaxy S9 devices. I even end up resizing the splash screen to all density from xxxhdpi to ldpi. and it still crash. So I end up removing it by reverse the instruction on installing expo-splash-screen. I have doubt will this effect the app by removing it?

**Comment by yzalvov** [comment]
@chengsokdara hi 👋   Same here. I ejected to bare and am having the same crash on Galaxy S9 at the moment. Did you manage to fix?

**Comment by rideddy84** [comment]
Same here. The crash didn't appear on first manual app bundle upload. But on EAS submit it happened.
```
{
  "workflow": "managed"
}
```

**Comment by brentvatne** [comment]
@yzalvov @rideddy84 - currently we don't support different splash dpis on managed eas build apps, you will need to reduce the size of your splash screen as a workaround for now, sorry!
