### ISSUE TITLE
[expo-notifications] Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#10610]
### Summary of Issue 

Hi, I've this crash in Crashlytics (Android). I couldn't reproduce it, I just see the crashes on Crashlytics. Seems that could be related to `expo-notifications`. I don't know if this happen when the user receive the notification or when tap the notification.

**Devices that reported the crash so far:**
 - OnePlus 7 Pro - Android 10
 - Stylo 6 - Android 10
 - Galaxy S6 Edge - Android 7.0
 - Moto E (4) - Android 7.1.1

I'm using `expo: 39.0.3` and `expo-notifications: 0.7.2`

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.java:82)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:170)
       at expo.modules.notifications.notifications.service.NotificationsHelper.<init>(NotificationsHelper.java:96)
       at expo.modules.notifications.notifications.handling.NotificationsHandler.<init>(NotificationsHandler.java:60)
       at expo.modules.notifications.NotificationsPackage.createExportedModules(NotificationsPackage.java:33)
       at org.unimodules.adapters.react.ReactModuleRegistryProvider.get(ReactModuleRegistryProvider.java:53)
       at org.unimodules.adapters.react.ModuleRegistryAdapter.createNativeModules(ModuleRegistryAdapter.java:31)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
       at java.lang.Thread.run(Thread.java:919)
```

**Another stack trace with little differences:**
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.java:82)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:170)
       at expo.modules.notifications.notifications.service.NotificationsHelper.<init>(NotificationsHelper.java:96)
       at expo.modules.notifications.FirebaseListenerService.createNotificationsHelper(FirebaseListenerService.java:90)
       at expo.modules.notifications.FirebaseListenerService.onMessageReceived(FirebaseListenerService.java:86)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@20.2.4:85)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@20.2.4:55)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@20.2.4:34)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@20.2.4:23)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@20.2.4:43)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.2.1:6)
       at java.lang.Thread.run(Thread.java:919)
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.3
      expo-notifications: 0.7.2
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: bare
```

### Reproducible Demo

I couldn't reproduce the crash, in my device works perfect. I catched this error on Crashlytics and Google Play Console. Sorry for this :(
 
### Steps to Reproduce

Seems could be related when the user receive or tap a push notification.

### Expected Behavior vs Actual Behavior

**Expected Behavior**: no crash
**Actual Behavior**: crash

**Comment by sjchmiela** [comment]
It looks like the `observer` weak reference gets cleared before it's added as the observer (so it's like we're trying to add `null` as an observer). I'll take a look at it.

**Comment by RodolfoGS** [comment]
Hi @sjchmiela, I would like to let you know that I'm testing this fix on production (only for a group of beta testers) and now I'm getting the following error on Crashlytics. I don't know how to reproduce it.

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
       at java.util.ArrayList.remove(ArrayList.java:503)
       at androidx.lifecycle.LifecycleRegistry.popParentState(LifecycleRegistry.java:202)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:301)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
       at expo.modules.notifications.notifications.service.NotificationsHelper.<init>(NotificationsHelper.java:90)
       at expo.modules.notifications.FirebaseListenerService.createNotificationsHelper(FirebaseListenerService.java:90)
       at expo.modules.notifications.FirebaseListenerService.onMessageReceived(FirebaseListenerService.java:86)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@20.2.4:85)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@20.2.4:55)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@20.2.4:34)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@20.2.4:23)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@20.2.4:43)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.2.1:6)
       at java.lang.Thread.run(Thread.java:919)
```

In the line `NotificationsHelper.java:90` I've your changes, so:
```
85.    // Note we're not removing the observer anywhere because NotificationsHelper
86.    // does not receive any information about its removal.
87.    // NotificationsHelperLifecycleObserver does not hold strong reference to this class
88.    // so we try to leak as little as possible.
89.    mLifecycleObserver = new NotificationsHelperLifecycleObserver(this);
90.    ProcessLifecycleOwner.get().getLifecycle().addObserver(mLifecycleObserver);
```

Do you know what could be happen? Thanks!
