### ISSUE TITLE
Issue in expo 39 in start up in android sometimes

### ISSUE THREAD

**Issue by priyankahash** [expo/expo#10660]
Caused by: java.lang.RuntimeException: Expo encountered a fatal error: Attempt to invoke virtual method 'host.exp.exponent.j host.exp.exponent.j.c(java.lang.String, java.lang.Object[])' on a null object reference
        at host.exp.exponent.experience.q.F(BaseExperienceActivity.java:7)
        at host.exp.exponent.experience.a.run(Unknown Source:2)
        at android.app.Activity.runOnUiThread(Activity.java:6973)
        at host.exp.exponent.experience.q.E(BaseExperienceActivity.

I am getting this error sometimes when I open standalone expo apk in android after upgrading expo from 36 to 39..
please let me know stable version  for expo.I used this command to generate build-
 expo build:android

SDK 39

 
### Steps to Reproduce

Expected- Each time there should be no crash
Actual- on app startup 2 times out of 4 there is crash on android

**Comment by AdamJNavarro** [comment]
Hey @priyankahash,

Can you share your `package.json` contents as well as how you have `updates` configured? Could you also try creating a new project and seeing if the crash occurs? That would be helpful in determining if this is project-specifc.

Cheers,
Adam

**Comment by priyankahash** [comment]
this is package.json file-

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@ptomasroos/react-native-multi-slider": "^2.2.0",
    "@react-native-community/async-storage": "~1.12.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "1.6.6",
    "@react-navigation/native": "^5.0.5",
    "@react-navigation/stack": "^5.0.5",
    "axios": "^0.19.2",
    "country-state-city": "^1.0.4",
    "expo": "^39.0.3",
    "expo-av": "~8.6.0",
    "expo-barcode-scanner": "~9.0.0",
    "expo-camera": "~9.0.0",
    "expo-constants": "~9.2.0",
    "expo-document-picker": "~8.4.0",
    "expo-file-system": "~9.2.0",
    "expo-image-manipulator": "~8.3.0",
    "expo-image-picker": "~9.1.0",
    "expo-images-picker": "^1.0.5",
    "expo-linear-gradient": "~8.3.0",
    "expo-media-library": "~9.2.1",
    "expo-multiple-media-imagepicker": "^1.2.1",
    "expo-notifications": "~0.7.2",
    "expo-permissions": "~9.3.0",
    "expo-push-notification-helper": "^0.4.0",
    "expo-splash-screen": "~0.6.1",
    "expokit": "^36.0.1",
    "moment": "^2.24.0",
    "react": "16.13.1",
    "react-country-region-selector": "^2.1.0",
    "react-data-table-component": "^6.3.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
    "react-native-animated-multistep": "^1.0.6",
    "react-native-countdown-component": "^2.7.1",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-modal": "^11.5.6",
    "react-native-multi-slider": "^0.3.6",
    "react-native-paper": "^3.6.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-responsive-screen": "^1.4.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-sass-transformer": "^1.4.0",
    "react-native-screens": "~2.10.1",
    "react-native-searchable-dropdown": "^1.1.1",
    "react-native-table-component": "^1.2.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.7",
    "react-native-webview": "^10.7.0",
    "react-native-youtube-iframe": "^1.3.0",
    "react-navigation": "^3.6.1",
    "react-navigation-drawer": "^2.4.2",
    "react-navigation-stack": "^2.1.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "sentry-expo": "^2.1.2",
    "expo-web-browser": "~8.5.0",
    "expo-intent-launcher": "~8.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-eslint": "^10.1.0",
    "babel-plugin-react-native-classname-to-style": "^1.2.2",
    "babel-plugin-react-native-platform-specific-extensions": "^1.1.1",
    "babel-preset-expo": "^8.3.0",
    "eslint": "^7.9.0",
    "eslint-config-standard": "^14.1.1",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "node-sass": "^4.13.1",
    "reactotron-react-native": "^5.0.0"
  },
  "private": true
}

**Comment by priyankahash** [comment]
app.json--- 
{
  "expo": {
    "name": "BMJ Beta",
    "slug": "BGM",
    "privacy": "public",
    "platforms": [
      "ios",
      "android"
     
    ],
    "version": "1.1.6",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "notification": {
      "icon": "./assets/logoicon.png"
    },
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover"
    },
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [
        "js",
        "jsx",
        "scss",
        "sass",
        "tsx"
      ]
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "userInterfaceStyle": "automatic",
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "package": "com.buymyjewel.test",
      "googleServicesFile": "./google-services.json",
      "useNextNotificationsApi":true,
      "versionCode": 17

    },
    "hooks": {
      "postPublish": [
        {
        "file": "sentry-expo/upload-sourcemaps",
        "config": {
          "organization": "hashstudioz",
          "project": "react-native",
          "authToken": "f4f0e294286c48fe9192619b6c926fe636b8d33b711c439495903044e1be985b"
        }
        }
      ]
      }

  }
}

**Comment by cruzach** [comment]
hey @priyankahash it looks like you still have `expokit` as a dependency in your project, which might cause some weird behavior for you. 

Unfortunately, without a [minimal reproducible demo](https://stackoverflow.com/help/minimal-reproducible-example), there's not much we can do to help in this situation. If you can provide one, please edit your original issue to include it and all the other information we ask for in the bug report template, thanks!

**Comment by priyankahash** [comment]
> Hey @priyankahash,
> 
> Can you share your `package.json` contents as well as how you have `updates` configured? Could you also try creating a new project and seeing if the crash occurs? That would be helpful in determining if this is project-specifc.
> 
> Cheers,
> Adam

please check once I have made reproducible demo sample -

app.json-

{
  "expo": {
    "name": "sample",
    "slug": "sample",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
	 "android": {
      "package": "com.sample.test",
     
      "versionCode": 1
      
  }
}
}

package.json -

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}

**Comment by isthaison** [comment]
````
2020-10-17 09:08:36.864 3229-28852/? W/NetworkScheduler: Error inserting flex_time=2737000 job_id=-1 period=5476000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=203615000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1602900516859 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067]) [CONTEXT service_id=218 ]
2020-10-17 09:08:36.953 1479-2524/? D/MdnieScenarioControlService:  packageName : com.feavn.itsmart    className : host.exp.exponent.MainActivity
2020-10-17 09:08:36.953 1479-2524/? V/MdnieScenarioControlService: setUIMode from UI function(3)
2020-10-17 09:08:36.958 28872-28948/? W/ReactNativeJS: No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
2020-10-17 09:08:36.979 28872-28948/? E/ReactNativeJS: Error: Expo native runtime is not available: something went wrong and we aren't sure what it was. Please post more information and get support at https://forums.expo.io.
2020-10-17 09:08:36.982 28872-28948/? E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_END
2020-10-17 09:08:36.986 28872-28948/? E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
2020-10-17 09:08:36.989 28872-28949/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.common.JavascriptException: Error: Expo native runtime is not available: something went wrong and we aren't sure what it was. Please post more information and get support at https://forums.expo.io., stack:
    <unknown>@13:184
    v@2:1473
    <unknown>@9:66
    v@2:1473
    <unknown>@8:7180
    v@2:1473
    <unknown>@6:45
    v@2:1473
    d@2:875
    global code@1707:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:919)
2020-10-17 09:08:36.989 28872-28949/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: Error: Expo native runtime is not available: something went wrong and we aren't sure what it was. Please post more information and get support at https://forums.expo.io., stack:
    <unknown>@13:184
    v@2:1473
    <unknown>@9:66
    v@2:1473
    <unknown>@8:7180
    v@2:1473
    <unknown>@6:45
    v@2:1473
    d@2:875
    global code@1707:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:919)
````
And more I'ts onlly crash after OTA update.

**Comment by isthaison** [comment]
@brentvatne  please, check again

**Comment by isthaison** [comment]
This is project  simple, It's works with the host server.
[project test with github page](https://github.com/isthaison/Emm)

**Comment by brentvatne** [comment]
@isthaison - please see https://stackoverflow.com/help/mcve for information on how to create a share an reproducible example. once you've created that, please create a new issue. thanks!
