### ISSUE TITLE
Updates are still broken for the very first time they're fetched in Expo client

### ISSUE THREAD

**Issue by d4rky-pl** [expo/expo#10703]
### Summary of Issue 

When we're running our project for the first time, Expo client crashes claiming there are no updates for the specified release channel. Scanning different release channels unblocks this randomly after few tries.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.1 - /var/folders/kc/w3zg_rmd6vnd_5w22fw154yh0000gn/T/yarn--1602838121639-0.5786628383019974/node
      Yarn: 1.22.5 - /var/folders/kc/w3zg_rmd6vnd_5w22fw154yh0000gn/T/yarn--1602838121639-0.5786628383019974/yarn
      npm: 6.14.8 - ~/.asdf/installs/nodejs/14.13.1/bin/npm
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.5 => 0.12.9
      expo: ^37.0.0 => 37.0.11
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7

✨  Done in 3.94s.
```

### Reproducible Demo

It may be hard to create steps to reproduce as it seems to be only happening with one of our projects (`@helpling/helpling-provider`). I think the problem might be on your servers rather than with the Expo Client because we downgraded to the SDK38 version of the client (2.16.1) and the problem still persists.

This particular app was always on SDK37 so it's definitely not the SDK mismatch that is causing any havoc.

#### Expected behavior

App always loads properly when there's an update on the server

#### Actual behavior
```
10-16 10:52:01.194  4218  4218 E LoaderTask: Failed to launch embedded or launchable update
10-16 10:52:01.194  4218  4218 E LoaderTask: java.lang.Exception: No launchable update was found. If this is a bare workflow app, make sure you have configured expo-updates correctly in android/app/build.gradle.
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at expo.modules.updates.launcher.DatabaseLauncher.launch(DatabaseLauncher.java:4)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at expo.modules.updates.loader.LoaderTask.launchFallbackUpdateFromDisk(LoaderTask.java:9)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at expo.modules.updates.loader.LoaderTask.start(LoaderTask.java:11)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at host.exp.exponent.g.F(ExpoUpdatesAppLoader.java:7)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at host.exp.exponent.g.E(ExpoUpdatesAppLoader.java:28)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at host.exp.exponent.p.q.T(Kernel.java:18)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at host.exp.exponent.p.q.S(Kernel.java:1)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at host.exp.exponent.p.q.f(Kernel.java:1)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at host.exp.exponent.p.v.f.a.b(LinkingKernelService.java:5)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at versioned.host.exp.exponent.modules.internal.ExponentIntentModule$1.run(ExponentIntentModule.java:1)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at android.os.Handler.handleCallback(Handler.java:883)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at android.os.Looper.loop(Looper.java:214)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at android.app.ActivityThread.main(ActivityThread.java:7710)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-16 10:52:01.194  4218  4218 E LoaderTask: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by d4rky-pl** [comment]
I just confirmed that upgrading to SDK 38 fixes the issue

**Comment by byCedric** [comment]
Thanks for the issue report and feedback related to SDK 38! Just to confirm, you are using the Expo Client locally when developing, right? If so, there might be a problem with the older Expo Client or the Expo CLI. When you develop locally, this shouldn't be triggered because the "update" is served from your local development environment instead. But, if it's something else, please do correct me!
