### ISSUE TITLE
[expo-image-picker][Android] allowsEditing option makes the app crash

### ISSUE THREAD

**Issue by aprilmintacpineda** [expo/expo#10799]
## 🐛 Bug Report

This is for a bare react-native app, not using expo.

### Summary of Issue 

App crashes when calling `launchImageLibraryAsync` and `launchCameraAsync` with `allowsEditing: true` option.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 170.03 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.8.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Just call:

```js
const picture = await launchCameraAsync({
  allowsEditing: true,
  allowsMultipleSelection: false,
});
```

and

```js
const picture = await launchImageLibraryAsync({
  mediaTypes: MediaTypeOptions.Images,
  allowsEditing: true
});
```

1. After calling the functions above, you can take a photo.
2. Take a photo,
3. Tap on checkmark.
4. App will crash.

This issue is not present in iOS BUT on iOS the edit doesn't allow me to drag the picture on the crop line...

### Expected Behavior vs Actual Behavior

Should not crash

**Comment by byCedric** [comment]
Hi @aprilmintacpineda, thanks for the issue report. Could you share your ADB logcat output too, maybe we can see what's going on by looking at those logs. You can get them by running something like `adb logcat *:S ReactNative:V ReactNativeJS:V`

**Comment by aprilmintacpineda** [comment]
@byCedric Currently out of the office, I will try this out and come back to you with a response tomorrow. Thank you very much.

**Comment by aprilmintacpineda** [comment]
I reduced react to version 16.4 and tried it out, still didn't work. I can't make the `adb logcat` command work on my terminal, so I just used android studio and in the debugger, I saw this:

```
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company.app.local, PID: 21416
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.company.app.local/com.company.app.MainActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.company.app.local/com.theartofdev.edmodo.cropper.CropImageActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5160)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5201)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2224)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7826)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
     Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.company.app.local/com.theartofdev.edmodo.cropper.CropImageActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2062)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
        at android.app.Activity.startActivityForResult(Activity.java:5310)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
        at android.app.Activity.startActivityForResult(Activity.java:5254)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
        at expo.modules.imagepicker.ImagePickerModule.startActivityOnResult(ImagePickerModule.kt:308)
        at expo.modules.imagepicker.ImagePickerModule.startCropIntent(ImagePickerModule.kt:250)
        at expo.modules.imagepicker.ImagePickerModule.handleOnActivityResult(ImagePickerModule.kt:352)
        at expo.modules.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.kt:289)
        at org.unimodules.adapters.react.services.UIManagerModuleWrapper$4.onActivityResult(UIManagerModuleWrapper.java:165)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:8302)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5153)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5201) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2224) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:228) 
        at android.app.ActivityThread.main(ActivityThread.java:7826) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981) 
I/Process: Sending signal. PID: 21416 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
```

**Comment by Lalitj03** [comment]
I was facing a similar issue. The problem was I did not add activity in the `AndroidManifest.xml`.  See the installation guide it may help https://github.com/expo/expo/tree/master/packages/expo-image-picker

**Comment by aprilmintacpineda** [comment]
@Lalitj03 thank you very much for your response. Your suggestion fixed it. Seems I didn't do that part, because it wasn't included here https://docs.expo.io/versions/latest/sdk/imagepicker/#installation, and I didn't click on the "additional install instructions".

**Comment by harrijefria55** [comment]
> @Lalitj03 thank you very much for your response. Your suggestion fixed it. Seems I didn't do that part, because it wasn't included here https://docs.expo.io/versions/latest/sdk/imagepicker/#installation, and I didn't click on the "additional install instructions".

this works for me 🙏🙏

**Comment by R-Sudharsan25** [comment]
This works, could easily have missed this. Thanks a lot.
