### ISSUE TITLE
[camera] Expo camera crash issue

### ISSUE THREAD

**Issue by itlockit2** [expo/expo#10933]
### Summary of Issue 
Previously I got a crash in react-native-camera and changed it to expo-camera, but it still happens. I want to know what is the cause.

### Environment 
Expo CLI 3.9.1 environment info:
System:
- OS: macOS 10.15.6
- Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
- Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
- Yarn: 1.22.4 - /usr/local/bin/yarn
- npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
- Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
- Android Studio: 4.1 AI-201.8743.12.41.6858069
- Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
- react: 16.13.1 => 16.13.1
- react-native: 0.63.2 => 0.63.2
- "expo-camera": "^9.0.0"
android : 10
hardware : Galaxy Note9
### Reproducible Demo
```javascript
import { Camera } from "expo-camera";
<Camera
    ref={(ref) => {
    this.camera = ref;
    }}
    style={
    cameraPreviewType === CAMERA_TYPE.mirror
    ? mirrorCameraStyle
    : fullCameraStyle
    }
    autoFocus={Camera.Constants.AutoFocus.on}
    zoom={0}
    ratio={"4:3"}
    type={Camera.Constants.Type.front}
    captureAudio={false}
    onCameraReady={this.onCameraReady}
    />
```
 
### Crash Log
ExpoCameraView.java line 15
expo.modules.camera.ExpoCameraView.onLayout
#### Fatal Exception: java.lang.RuntimeException java.io.IOException: setPreviewTexture failed
```
Fatal Exception: java.lang.RuntimeException: java.io.IOException: setPreviewTexture failed
       at com.google.android.cameraview.Camera1.setUpPreview(Camera1.java:77)
       at com.google.android.cameraview.Camera1$1.onSurfaceChanged(Camera1.java:6)
       at com.google.android.cameraview.PreviewImpl.dispatchSurfaceChanged(PreviewImpl.java:2)
       at com.google.android.cameraview.TextureViewPreview$1.onSurfaceTextureSizeChanged(TextureViewPreview.java:12)
       at android.view.TextureView.onSizeChanged(TextureView.java:377)
       at android.view.View.sizeChange(View.java:23958)
       at android.view.View.setFrame(View.java:23891)
       at android.view.View.layout(View.java:23750)
       at expo.modules.camera.ExpoCameraView.onLayout(ExpoCameraView.java:15)
       at android.view.View.layout(View.java:23753)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:25)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:90)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:27)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:141)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:728)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8125)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
#### Caused by java.io.IOException setPreviewTexture failed
```
Caused by java.io.IOException: setPreviewTexture failed
       at android.hardware.Camera.setPreviewTexture(Camera.java)
       at com.google.android.cameraview.Camera1.setUpPreview(Camera1.java:8)
       at com.google.android.cameraview.Camera1$1.onSurfaceChanged(Camera1.java:6)
       at com.google.android.cameraview.PreviewImpl.dispatchSurfaceChanged(PreviewImpl.java:2)
       at com.google.android.cameraview.TextureViewPreview$1.onSurfaceTextureSizeChanged(TextureViewPreview.java:12)
       at android.view.TextureView.onSizeChanged(TextureView.java:377)
       at android.view.View.sizeChange(View.java:23958)
       at android.view.View.setFrame(View.java:23891)
       at android.view.View.layout(View.java:23750)
       at expo.modules.camera.ExpoCameraView.onLayout(ExpoCameraView.java:15)
       at android.view.View.layout(View.java:23753)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:25)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:90)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:27)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:141)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:728)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8125)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
ReactViewGroup.java line 3
com.facebook.react.views.view.ReactViewGroup.dispatchDraw
#### Fatal Exception: java.lang.RuntimeException java.io.IOException: setPreviewTexture failed
```
Fatal Exception: java.lang.RuntimeException: java.io.IOException: setPreviewTexture failed
       at com.google.android.cameraview.Camera1.setUpPreview(Camera1.java:77)
       at com.google.android.cameraview.Camera1$1.onSurfaceChanged(Camera1.java:6)
       at com.google.android.cameraview.PreviewImpl.dispatchSurfaceChanged(PreviewImpl.java:2)
       at com.google.android.cameraview.TextureViewPreview$1.onSurfaceTextureAvailable(TextureViewPreview.java:12)
       at android.view.TextureView.getTextureLayer(TextureView.java:400)
       at android.view.TextureView.draw(TextureView.java:349)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23190)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23190)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23190)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1154)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4296)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4080)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3348)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:732)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
#### Caused by java.io.IOException setPreviewTexture failed
```
Caused by java.io.IOException: setPreviewTexture failed
       at android.hardware.Camera.setPreviewTexture(Camera.java)
       at com.google.android.cameraview.Camera1.setUpPreview(Camera1.java:8)
       at com.google.android.cameraview.Camera1$1.onSurfaceChanged(Camera1.java:6)
       at com.google.android.cameraview.PreviewImpl.dispatchSurfaceChanged(PreviewImpl.java:2)
       at com.google.android.cameraview.TextureViewPreview$1.onSurfaceTextureAvailable(TextureViewPreview.java:12)
       at android.view.TextureView.getTextureLayer(TextureView.java:400)
       at android.view.TextureView.draw(TextureView.java:349)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23190)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23190)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23190)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1154)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4296)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4080)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3348)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:732)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by zholmes1** [comment]
I'm getting the exact same error. Unable to reproduce on my own device, but I'm getting Crashlytics reports. Did you ever find a solution?

**Comment by zholmes1** [comment]
Still receiving this report periodically. We had a user today on Android 8.1 that experienced this crash every time they opened the app. 

```
      <Camera
        ratio={ratio}
        ref={setCamera}
        style={{ flex: 1 }}
        flashMode={flashMode}
        pictureSize={pictureSize}
        onMountError={e => {
          setMountError(e)
          recordError(new Error(e.message))
        }}
      />
```

**Comment by GSTJ** [comment]
Having the same issue here

**Comment by sweebee** [comment]
up, same issue over here according to Sentry.

**Comment by karthickraja81222** [comment]
getting same issue suddenly now which was working till morning

**Comment by JeroenDerks** [comment]
Same here. Did anyone find a solution to it?
