### ISSUE TITLE
ViewManager for tag ### could not be found

### ISSUE THREAD

**Issue by asdf23** [expo/expo#10971]
My application is crashing due to this bug captured from logcat:
I'm not sure how I can debug this, and I think this has more to do with the framework than my specific app (https://snack.expo.io/@avitauser01/awkward-donuts)

```
11-09 13:22:16.554 13416 13416 E AndroidRuntime: FATAL EXCEPTION: main
11-09 13:22:16.554 13416 13416 E AndroidRuntime: Process: host.exp.exponent, PID: 13416
11-09 13:22:16.554 13416 13416 E AndroidRuntime: java.lang.IllegalStateException: abi39_0_0.com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 135 could not be found.
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:7)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:1)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:2)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7386)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: Caused by: abi39_0_0.com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 135 could not be found.
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:3)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:4)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:1)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:18)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:10)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:1)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:1)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:1)
11-09 13:22:16.554 13416 13416 E AndroidRuntime: 	... 7 more
```

**Comment by AdamJNavarro** [comment]
Hey @asdf23,

For questions regarding how to approach debugging an issue, please head over to our [Forums](https://forums.expo.io/) and create a post. In addition, we provide some [debugging docs](https://docs.expo.io/workflow/debugging/) that I would recommend reading over. I'm going to close this issue and look forward to helping you our on our forums.

Also, as I mentioned in your other issue, please provide a minimal repro Snack rather than the current one you have.

Cheers,
Adam
