### ISSUE TITLE
Crashing only in Android

### ISSUE THREAD

**Issue by asdf23** [expo/expo#10970]
I get a crash only in Android from https://snack.expo.io/@avitauser01/awkward-donuts 

From logcat the error looks like "textAlignVertical" this 

```
10-22 16:50:39.801  3230  3230 E AndroidRuntime: FATAL EXCEPTION: main
10-22 16:50:39.801  3230  3230 E AndroidRuntime: Process: host.exp.exponent, PID: 3230
10-22 16:50:39.801  3230  3230 E AndroidRuntime: java.lang.IllegalStateException: abi39_0_0.com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'textAlignVertical' of a view managed by: RCTText
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:7)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:2)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:984)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:764)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: Caused by: abi39_0_0.com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'textAlignVertical' of a view managed by: RCTText
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:13)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:2)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:9)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:8)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:9)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:4)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	... 13 more
10-22 16:50:39.801  3230  3230 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:4)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	... 21 more
10-22 16:50:39.801  3230  3230 E AndroidRuntime: Caused by: abi39_0_0.com.facebook.react.bridge.JSApplicationIllegalArgumentException: Invalid textAlignVertical: true
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	at abi39_0_0.com.facebook.react.views.text.ReactTextAnchorViewManager.setTextAlignVertical(ReactTextAnchorViewManager.java:8)
10-22 16:50:39.801  3230  3230 E AndroidRuntime: 	... 23 more
```

**Comment by AdamJNavarro** [comment]
Hey @asdf23,

Thank you for providing a repro here but there is simply too much going on with your Snack. When providing repro cases, please only include the bare minimum implementation that causes the bug/error. If you are confident that it is the use of `textAlignVertical` that is causing the issue, that would be a React Native issue rather than an Expo one so the best course of action would be to open an issue there and provide the aforementioned minimal repro as well as a more detailed explanation of what is occurring, on what platforms, running what versions, etc.

Cheers,
Adam
