### ISSUE TITLE
App crash when returning via deeplink: `ViewManager for tag XX could not be found`

### ISSUE THREAD

**Issue by sun2rise** [expo/expo#1099]
Hi 
my app is detached and maybe this could be related to #779 or #656 
I use SDK 26 because of [this error](https://stackoverflow.com/a/47675309/192914):
`Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.`

When I return to the app from an external deeplink it gives me this error almost every time:
```
Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 93 could not be found
       at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:106)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:523)
       at com.facebook.react.uimanager.NativeViewHierarchyManager$1.onAnimationEnd(NativeViewHierarchyManager.java:421)
       at com.facebook.react.uimanager.layoutanimation.LayoutAnimationController$1.onAnimationEnd(LayoutAnimationController.java:131)
       at android.view.animation.Animation$3.run(Animation.java:381)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

Any ideas?

**Comment by Fsarmento** [comment]
I am getting exactly the same error on Android (didn't test on iOS)

```
com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1560 could not be found
    at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:103)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:528)
    at com.facebook.react.uimanager.NativeViewHierarchyManager$1.onAnimationEnd(NativeViewHierarchyManager.java:426)
    at com.facebook.react.uimanager.layoutanimation.LayoutAnimationController$1.onAnimationEnd(LayoutAnimationController.java:131)
    at android.view.animation.Animation$3.run(Animation.java:376)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

In my case, this happens when I am scrolling a SectionList at a fast pace. The items on my list have LayoutAnimation on componentWillUpdate. Some items have images that, after onLoad, will push the list down to gain space to be visible. This is animated with LayoutAnimation. This is the only place in my app where I have LayoutAnimation.


```
  componentWillUpdate() {
    UIManager.setLayoutAnimationEnabledExperimental &&
      UIManager.setLayoutAnimationEnabledExperimental(true)
    LayoutAnimation.easeInEaseOut()
  }
```

If I remove this componentWillUpdate block, I cannot reproduce the error.

Based on the error, I would say that the item component is unmounted from the SectionList while  LayoutAnimation.easeInEaseOut() is running. Consequently, when the animation ends (`uimanager.NativeViewHierarchyManager$1.onAnimationEnd`), the ViewManager cannot be found. 

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.3.2 => 16.3.1
  react-native: 0.55.2 => 0.55.2

**Comment by AdamJNavarro** [comment]
Hey @sun2rise,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
