### ISSUE TITLE
Unable to start receiver expo.modules.taskManager.TaskBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.getLastLocation()' on a null object reference

### ISSUE THREAD

**Issue by MrHazimAli** [expo/expo#11089]
### Summary of Issue 

Only for some users, the apps crashes randomly on background

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

![image](https://user-images.githubusercontent.com/6757574/99752349-20405680-2b1f-11eb-8044-e1c6e688ff3d.png)

![image](https://user-images.githubusercontent.com/6757574/99752255-f129e500-2b1e-11eb-9232-ba213c925d79.png)

### Reproducible Demo

crashlytics screenshot
![image](https://user-images.githubusercontent.com/6757574/99752060-97c1b600-2b1e-11eb-8ff7-6219265fe39b.png)

sample code
![image](https://user-images.githubusercontent.com/6757574/99753012-6b0e9e00-2b20-11eb-9ed5-c097107a8077.png)

 
### Expected Behavior vs Actual Behavior

The app run normally

**Comment by s3131212** [comment]
I also encountered a similar problem on Android 8.0 (haven't tested on other versions). When the user kill the app and turn off the location service, the app crash immediately. I used EAS build.

```
05-31 23:55:09.669  4932  4932 E AndroidRuntime: Process: <package bundle identifier>, PID: 4932
05-31 23:55:09.669  4932  4932 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver expo.modules.taskManager.TaskBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.getLastLocation()' on a null object reference
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3399)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.getLastLocation()' on a null object reference
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at expo.modules.location.taskConsumers.LocationTaskConsumer.didReceiveBroadcast(LocationTaskConsumer.java:114)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at expo.modules.taskManager.TaskService.handleIntent(TaskService.java:313)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at expo.modules.taskManager.TaskBroadcastReceiver.onReceive(TaskBroadcastReceiver.java:15)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
05-31 23:55:09.669  4932  4932 E AndroidRuntime: 	... 8 more
```

expo diagnostics:
```
  Expo CLI 4.5.0 environment info:
    System:
      OS: Linux 5.10 Manjaro Linux
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.5 - ~/.nvm/versions/node/v14.5.0/bin/yarn
      npm: 7.11.0 - ~/.nvm/versions/node/v14.5.0/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.5.0
    Expo Workflow: managed
```

This code literally do nothing except `console.log`:
```javascript
import * as Location from 'expo-location';
import * as TaskManager from 'expo-task-manager';

const locationTaskName = 'location-tracking';
TaskManager.defineTask(locationTaskName, async (event) => {
    console.log(event.data.locations);
});
```

Is there any update on this bug?

**Comment by binitgurzu** [comment]
still looking for solutions

**Comment by s3131212** [comment]
I use this patch as a workaround. You can patch it with [patch-package](https://www.npmjs.com/package/patch-package), and build it with [EAS Build](https://docs.expo.io/build/introduction/). EAS Build is a great service but currently requires Priority Plan. 
```
diff --git a/node_modules/expo-location/android/src/main/java/expo/modules/location/taskConsumers/LocationTaskConsumer.java b/node_modules/expo-location/android/src/main/java/expo/modules/location/taskConsumers/LocationTaskConsumer.java
index 15ab488..5dc16f4 100644
--- a/node_modules/expo-location/android/src/main/java/expo/modules/location/taskConsumers/LocationTaskConsumer.java
+++ b/node_modules/expo-location/android/src/main/java/expo/modules/location/taskConsumers/LocationTaskConsumer.java
@@ -111,6 +111,9 @@ public class LocationTaskConsumer extends TaskConsumer implements TaskConsumerIn
       maybeReportDeferredLocations();
     } else {
       try {
+        if (mLocationClient == null) {
+          return;
+        }
         mLocationClient.getLastLocation().addOnCompleteListener(new OnCompleteListener<Location>() {
           @Override
           public void onComplete(@NonNull Task<Location> task) {

```

I didn't create a PR because I'm not sure whether this fix breaks anything. I know nearly nothing about Java and Android, and I don't want to break anything with this hacky workaround that might only work on my machine or on my App.
