### ISSUE TITLE
Cannot login via `exp start`

### ISSUE THREAD

**Issue by sylvhama** [expo/expo#1114]
- exp version is 47.1.1
- tried with node 6.11.5 and 8.9.1
The error:
`[exp]
[exp] Error
    at _formatAuth0NodeError (C:\xdl\src\User.js:757:14)
    at C:\xdl\src\User.js:654:15
    at Generator.throw (<anonymous>)
    at step (C:\Users\shamann\AppData\Roaming\npm\node_modules\exp\node_modules\xdl\build\User.js:188:191)
    at C:\Users\shamann\AppData\Roaming\npm\node_modules\exp\node_modules\xdl\build\User.js:188:402
    at <anonymous>`

**Comment by sylvhama** [comment]
My credentials work on the website and on the windows client.

**Comment by sylvhama** [comment]
My bad, I was behind a proxy and I've omited to turn on my VPN.
