### ISSUE TITLE
Expo 2.17.5 crashes on Android device

### ISSUE THREAD

**Issue by afattahi54** [expo/expo#11155]
### Summary of Issue 
I've download expo v 2.17.5 from google play store. The app crashes when I want to start it without any error on screen. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Device is huwavi mate 9. Andriod version is 9.

### The log cat shows:

````
java.lang.RuntimeException: Unable to start activity ComponentInfo{host.exp.exponent/host.exp.exponent.experience.HomeActivity}: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.p.q
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:112)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
11-28 08:44:34.003 29097 29097 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

`

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/11082

**Comment by afattahi54** [comment]
Do you think it is the same issue. I think this is not a build problem I am not building my own app. I can not open expo app ( which I have downloaded from Google)

**Comment by afattahi54** [comment]
The #11082 seems problem with google service. But my error is about not finding some components.

**Comment by afattahi54** [comment]
I don't know why but without reinstalling it works today !!!
