### ISSUE TITLE
[Bare][Expo-Sensor] Crash on app resume

### ISSUE THREAD

**Issue by KDederichs** [expo/expo#11282]
### Summary of Issue 

The accelerometer seems to crash android apps on resume since the subscription has been released.
I haven't been able to reproduce it but it's showing up in our bug catcher

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
      react-native-web: ^0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare
```

### Reproducible Demo

Like I said, haven't been able to reproduce, but basically it's just this in a component:
```

  const [gyro, setGyro] = React.useState<ThreeAxisMeasurement | null>(null);

  React.useEffect(() => {
    const sub = Accelerometer.addListener((result) => {
      setGyro(result);
    });
    Accelerometer.setUpdateInterval(100);
    return () => {
      sub.remove();
    };
  }, []);
```
 
### Steps to Reproduce

 Pause and Resume App it seems

### Expected Behavior vs Actual Behavior

No crash on resume not:

```
java.lang.RuntimeException: Unable to resume activity {com.mayapp/com.mayapp.MainActivity}: java.lang.IllegalStateException: Subscription has been released, cannot call methods on a released subscription.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4321)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4353)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by: java.lang.IllegalStateException: Subscription has been released, cannot call methods on a released subscription.
        at expo.modules.sensors.services.SensorServiceSubscription.assertSubscriptionIsAlive(SensorServiceSubscription.java:60)
        at expo.modules.sensors.services.SensorServiceSubscription.start(SensorServiceSubscription.java:20)
        at expo.modules.sensors.modules.BaseSensorModule.onHostResume(BaseSensorModule.java:98)
        at org.unimodules.adapters.react.services.UIManagerModuleWrapper$3.onHostResume(UIManagerModuleWrapper.java:127)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:715)
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:619)
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:576)
        at com.facebook.react.ReactDelegate.onHostResume(ReactDelegate.java:53)
        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:99)
        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:7972)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4311)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4353)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

**Comment by tourze** [comment]
same problem
