### ISSUE TITLE
TaskManager continue to work after app killing

### ISSUE THREAD

**Issue by ValcasaraBryan** [expo/expo#11395]
Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

This is my code
```
class TrackingSagas {
    static params = {
        accuracy: Location.Accuracy.High,
        timeInterval: SECONDE * 2,
        distanceInterval: 0,
        showsBackgroundLocationIndicator: true,
        pausesUpdatesAutomatically: true,
        activityType: Location.ActivityType.Other,
    };
    static ws = null;
    static token = null;

    static onBackground = (params) => {
        const { data, error, store } = params
        console.log("onBackground", params)
        if (error) {
            console.warn("error onBackground", error);
        } else if (!error && data && data.locations) {
            const { coords } = data.locations[0];
            this.wsFunc({ coords, store });
        }
    }


    static wsFunc = ({ coords, store }) => {
        if (!this.ws && this.token) {
            this.ws = api.createws({ token: this.token });
        } else if (this.ws && this.ws.readyState == this.ws.OPEN) {
            const { speed, heading, latitude, longitude } = coords;
            this.send({ speed, heading, lat: latitude, lng: longitude })
            if (store) store.dispatch(TrackingActions.updatePosition(coords))
        }
    }



    static send = ({ speed, heading, lat, lng }) => {
        this.ws.send(JSON.stringify({ event: 'tracking.updatePosition', data: { speed, heading, lat, lng } }))
    }
};

export default TrackingSagas;
```
```
TaskManager.defineTask('backgroundCurrentPosition', (params) => TrackingSagas.onBackground({ ...params, store }))
```

This is the log of androidStudio with virtual device
OS : Release name R, Android 11 API 30 x86

```AutofillManager: onActivityFinishing(): calling cancelLocked()```
This message is show when I killed app

And TaskManager is called again

```
I / TaskService: Handling intent with task name 'backgroundCurrentPosition' and appId '@xxxx'.
    I / TaskService: Handling job with task name 'backgroundCurrentPosition' for app with ID '@xxxx'.
        I / ReactNativeJS: 'onBackground', {
            data: { locations: [[Object]] },
            error: null,
            executionInfo:
            {
                taskName: 'backgroundCurrentPosition',
                eventId: 'XXXX'
            },
            store:
            {
                subscribe: [Function: E],
                getState: [Function: O],
                replaceReducer: [Function: replaceReducer],
                dispatch: [Function]
            }
        }
I / TaskService: Finished task 'backgroundCurrentPosition' with eventId 'XXXX'.
    D / AutofillManager: onActivityFinishing(): calling cancelLocked()
E / unknown: ReactInstanceManager: ReactInstanceManager.destroy called
java.lang.RuntimeException: ReactInstanceManager.destroy called
at com.facebook.react.ReactInstanceManager.logOnDestroy(ReactInstanceManager.java: 1)
at com.facebook.react.ReactInstanceManager.destroy(ReactInstanceManager.java: 3)
at java.lang.reflect.Method.invoke(Native Method)
at host.exp.exponent.j.f(RNObject.java: 1)
at host.exp.exponent.j.b(RNObject.java: 1)
at host.exp.exponent.experience.w.g(ReactNativeActivity.java: 2)
at host.exp.exponent.experience.w.onDestroy(ReactNativeActivity.java: 2)
at host.exp.exponent.experience.q.onDestroy(BaseExperienceActivity.java: 1)
at android.app.Activity.performDestroy(Activity.java: 8245)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java: 1344)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java: 5096)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java: 5140)
at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java: 44)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java: 176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java: 97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java: 2066)
at android.os.Handler.dispatchMessage(Handler.java: 106)
at android.os.Looper.loop(Looper.java: 223)
at android.app.ActivityThread.main(ActivityThread.java: 7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java: 592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 947)
I / TextToSpeech: Sucessfully bound to com.google.android.tts
I / ReactNative: [GESTURE HANDLER] Tearing down gesture handler registered for root view versioned.host.exp.exponent.ReactUnthemedRootView{ 335e5fa V.E...... ......ID 0, 0 - 1080, 2088 #b }
W / unknown: Fresco: Fresco has already been initialized! `Fresco.initialize(...)` should only be called 1 single time to avoid memory leaks!
D / SoLoader: init exiting
W / unknown: ImagePipelineFactory: ImagePipelineFactory has already been initialized! `ImagePipelineFactory.initialize(...)` should only be called once to avoid unexpected behavior.
    D / j: WARNING: getPackageName called on ScopedContext
I / TaskService: Handling intent with task name 'backgroundCurrentPosition' and appId '@xxxx'.
    I / TaskService: Handling job with task name 'backgroundCurrentPosition' for app with ID '@xxxx'.
    I/ReactNativeJS: 'onBackground', { data: { locations: [ [Object] ] },
      error: null,
      executionInfo: 
       { taskName: 'backgroundCurrentPosition',
         eventId: 'XXXX' },
      store: 
       { subscribe: [Function: E],
         getState: [Function: O],
         replaceReducer: [Function: replaceReducer],
         dispatch: [Function] } }
I/TaskService: Finished task 'backgroundCurrentPosition' with eventId 'XXXX'.
```

How can I stop TaskManager when app was killed ?

**Comment by devashishsethia** [comment]
+1 I have the same problem
