### ISSUE TITLE
Beginning in Expo SDK 39 JS Debugging on iOS simulator no longer works when the code reloads

### ISSUE THREAD

**Issue by blairio** [expo/expo#11411]
### Summary of Issue 
Beginning in Expo SDK 39 JS Debugging on iOS simulator no longer works when the code reloads

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /Users/blair/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

Google Chrome: Version 87.0.4280.88 (Official Build) (x86_64)
```
### Reproducible Demo
- Fresh install of SDK 40 with fresh app based on template
```
$ expo init --npm
✔ What would you like to name your app? … Sample
✔ Choose a template: › tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript
(node:52377) ExperimentalWarning: The fs.promises API is experimental
✔ Downloaded and extracted project files.

📦 Using npm to install packages.
 ```

### Steps to Reproduce
1. `npm run ios`
2. On the simulator Reload the code (Command+R)

#### Expected
- Code reloads and debugging continues

#### Actual
- Code reloads and pops up errors like
  -  Unable to load DevMenu
  - Runtime is not ready for debugging
- App Frozen
- Need to restart simulator and Expo
- See [Video](https://drive.google.com/file/d/1lOpm_fpw0YdLazPMZAW-CM-wM9UhD3d3/view?usp=sharing)

```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.aca173c4.js` from ``: 

None of these files exist:
  * debugger-ui/debuggerWorker.aca173c4.js(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
  * debugger-ui/debuggerWorker.aca173c4.js/index(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (/Users/blair/Projects/Sample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/blair/Projects/Sample/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/blair/Projects/Sample/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at /Users/blair/Projects/Sample/node_modules/metro/src/lib/transformHelpers.js:267:42
    at Server.<anonymous> (/Users/blair/Projects/Sample/node_modules/metro/src/Server.js:841:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/blair/Projects/Sample/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/blair/Projects/Sample/node_modules/metro/src/Server.js:119:9)
```
- Note: JS Debugging on an actual iOS does not appear to freeze or throw errors, but still logs:
```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.aca173c4.js` from ``: 
```

**Comment by AdamJNavarro** [comment]
Hey @blairio, this issue has been documented pretty extensively in the react-native repository. Please take a look at this thread: https://github.com/facebook/react-native/issues/28844 

Seeing as this pertains more so the the React Native scope, I'm going to close this issue and would encourage you to track it there.

Cheers,
Adam

**Comment by blairio** [comment]
I went through the 28844 and it seems to suggest that fixing it requires an upgrade to `react-native-community/cli 4.13.1` and clearing Chrome cache and Application Cache

So, I did that, and I removed any global installations of `react-native` and `expo-cli`

And reinstalled the latest `expo-cli` and recreated the Sample project.

Globally
```
user:Sample blair$ npm list -g @react-native-community/cli-debugger-ui
/Users/user/.nvm/versions/node/v10.15.3/lib
└─┬ expo-cli@4.0.15
  └─┬ @expo/xdl@59.0.13
    └─┬ @expo/dev-server@0.1.47
      └─┬ @react-native-community/cli-server-api@4.9.0. <--- Why is a fresh install of global cli using this?
        └── @react-native-community/cli-debugger-ui@4.13.1 
```

Locally
```
user:Sample blair$ npm list  @react-native-community/cli-debugger-ui
/Users/user/Projects/Sample
└─┬ react-native@0.63.2
  └─┬ @react-native-community/cli@4.13.1
    ├── @react-native-community/cli-debugger-ui@4.13.1 
    └─┬ @react-native-community/cli-server-api@4.13.1
      └── @react-native-community/cli-debugger-ui@4.13.1  deduped
```

The debugger still freezes up after reloading.
I tried it with:
1. Chrome 87.0.4280.88
2. React Native Debugger 0.11.6 <-- This one does **not** complain about missing debugWorker modules
3. Safari 14.0.2

None of them work with the iOS Simulator
