### ISSUE TITLE
SDK 40 Renanimated V2 android standalone apk crashing on load

### ISSUE THREAD

**Issue by Tiltorito** [expo/expo#11529]
### Summary of Issue 
The standalone application crashes on load. Similar to: #10564

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

### Reproducible Demo
Just installing reanimated v2 following the [doc instructions](https://docs.expo.io/versions/latest/sdk/reanimated/#experimental-support-for-v2). Please see the comments in issue #10564 they contain detail crash reports. 
 
### Expected Behavior vs Actual Behavior

Would expect the app not to crash

**Comment by AdamJNavarro** [comment]
@sjchmiela I'll leave it up to you if you want to use this new issue or close this one and re-open #10564.

**Comment by brentvatne** [comment]
@Tiltorito - please provide a repro we can clone to reproduce this

**Comment by Tiltorito** [comment]
> @Tiltorito - please provide a repro we can clone to reproduce this. as far as i know, the example from the docs works as expected. i want to understand here whether the issue is on the integration of reanimated in expo or with reanimated itself.

You are right... I tried myself with the template and it seems to be working alright... I can replicate it with my project but not from the template. 

The following crash report is using adb:
```
// java.lang.RuntimeException: Unable to resume activity {gr.quiz4math/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., stack:
// exports@21:286
// getEnforcing@25:169
// <unknown>@1596:197
// v@2:1473
// <unknown>@1595:156
// v@2:1473
// <unknown>@1590:6077
// v@2:1473
// <un
// 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
// 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
// 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
// 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
// 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:146)
// 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
// 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
// 	at android.os.Handler.dispatchMessage(Handler.java:106)
// 	at android.os.Looper.loop(Looper.java:223)
// 	at android.app.ActivityThread.main(ActivityThread.java:7656)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
// Caused by: java.lang.RuntimeException: Expo encountered a fatal error: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., stack:
// exports@21:286
// getEnforcing@25:169
// <unknown>@1596:197
// v@2:1473
// <unknown>@1595:156
// v@2:1473
// <unknown>@1590:6077
// v@2:1473
// <un
// 	at host.exp.exponent.experience.q.E(BaseExperienceActivity.java:7)
// 	at host.exp.exponent.experience.a.run(Unknown Source:2)
// 	at android.app.Activity.runOnUiThread(Activity.java:7068)
// 	at host.exp.exponent.experience.q.D(BaseExperienceActivity.java:2)
// 	at host.exp.exponent.experience.q.onResume(BaseExperienceActivity.java:5)
// 	at host.exp.exponent.experience.ExperienceActivity.onResume(ExperienceActivity.java:1)
// 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
// 	at android.app.Activity.performResume(Activity.java:8135)
// 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
// 	... 12 more
// 

```

Followed by my package.json

  ```json
  "dependencies": {
    "@hookform/resolvers": "^0.1.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "@types/humps": "^1.1.3",
    "@types/yup": "^0.29.6",
    "axios": "^0.20.0",
    "expo": "^40.0.0",
    "expo-app-loading": "^1.0.1",
    "expo-blur": "~8.2.2",
    "expo-constants": "~9.3.3",
    "expo-firebase-analytics": "~2.6.0",
    "expo-firebase-core": "~1.3.0",
    "expo-secure-store": "~9.3.0",
    "expo-web-browser": "~8.6.0",
    "humps": "^2.0.1",
    "install": "^0.13.0",
    "npm": "^6.14.8",
    "react": "16.13.1",
    "react-async": "^10.0.1",
    "react-dom": "16.13.1",
    "react-hook-form": "^6.5.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-chart-kit": "^5.5.0",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-material-ripple": "git+https://github.com/Tiltorito/react-native-material-ripple.git",
    "react-native-reanimated": "2.0.0-rc.0",
    "react-native-responsive-fontsize": "^0.4.3",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-snap-carousel": "^3.9.0",
    "react-native-svg": "12.1.0",
    "react-native-typography": "^1.4.1",
    "react-native-web": "~0.13.12",
    "react-native-webview": "11.0.0",
    "rn-placeholder": "^3.0.1",
    "rxjs": "^6.6.2",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "babel-preset-expo": "8.3.0",
    "typescript": "~4.0.0"
  },
  ```

**Comment by brentvatne** [comment]
@Tiltorito - do not include this in app.json:

```
{
"expo": {
  "experiments": {
    "turboModules": true
  },
}
```

you should not use this in sdk 40, it was only needed in sdk 39 and will cause issues for you. it's discussed in the thread you linked to in your original post.

**Comment by Tiltorito** [comment]
@brentvatne Thank you for your reply. Just tried what you suggested with no luck. My app still crashes on load. Moreover, yesterday when trying to reproduce it using the template given in the docs I still had nativeModules enabled and was working fine from a clean project. There is definitely an issue I just cannot seem to track it down.

```
CatalystInstanceImpl caught native exception
    com.facebook.react.common.JavascriptException: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., stack:
    exports@21:286
    getEnforcing@27:169
    <unknown>@1645:197
    v@2:1473
    <unknown>@1644:156
    v@2:1473
    <unknown>@1639:6077
    v@2:1473
    <unknown>@1599:1674
    v@2:1473
    <unknown>@1593:190
    v@2:1473
    <unknown>@1592:143
    v@2:1473
    <unknown>@1591:180
    v@2:1473
    <unknown>@1590:133
    v@2:1473
    <unknown>@1589:171
    v@2:1473
    <unknown>@1588:211
    v@2:1473
    <unknown>@778:319
    v@2:1473
    <unknown>@747:399
    v@2:1473
    <unknown>@6:60
    v@2:1473
    d@2:875
    global code@1706:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:923)
        
        
2021-01-06 12:00:41.537 18419-18497/gr.quiz4math E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., stack:
    exports@21:286
    getEnforcing@27:169
    <unknown>@1645:197
    v@2:1473
    <unknown>@1644:156
    v@2:1473
    <unknown>@1639:6077
    v@2:1473
    <unknown>@1599:1674
    v@2:1473
    <unknown>@1593:190
    v@2:1473
    <unknown>@1592:143
    v@2:1473
    <unknown>@1591:180
    v@2:1473
    <unknown>@1590:133
    v@2:1473
    <unknown>@1589:171
    v@2:1473
    <unknown>@1588:211
    v@2:1473
    <unknown>@778:319
    v@2:1473
    <unknown>@747:399
    v@2:1473
    <unknown>@6:60
    v@2:1473
    d@2:875
    global code@1706:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:923)


2021-01-06 12:00:41.539 18419-18419/gr.quiz4math E/AndroidRuntime: FATAL EXCEPTION: main
    Process: gr.quiz4math, PID: 18419
    java.lang.RuntimeException: Expo encountered a fatal error: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., stack:
    exports@21:286
    getEnforcing@27:169
    <unknown>@1645:197
    v@2:1473
    <unknown>@1644:156
    v@2:1473
    <unknown>@1639:6077
    v@2:1473
    <un
        at host.exp.exponent.experience.q.E(BaseExperienceActivity.java:7)
        at host.exp.exponent.experience.a.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Tiltorito** [comment]
@brentvatne also the app crashes half of the time 🤷‍♂️ - sometimes it starts sometimes it does not

**Comment by ivansenic** [comment]
@brentvatne We don't use the `turboModules` in the config and still get this issue. As @Tiltorito says it happens app. on one half of the startups, not sure if this is some race condition.

Anyway, this issue should be reopened.
