### ISSUE TITLE
standalone build crashes when loading a webpage in webview

### ISSUE THREAD

**Issue by viljark** [expo/expo#11612]
### Summary of Issue 
Standalone build of the app crashes when parsing cookies in webview. After crash re-opening also always crashes.

Can this be related to a JS library we added with the latest webpage release, which writes some cookies to webview with Response Headers to set up a session. 
Or OTA being downloaded and writing cookies?

We did not have any other relevant changes to our app or webpage used in webview.

Seems like `okhttp3` is unable to extract some cookie, to my knowledge there is unfortunately no way to retrieve the headers from the expo generated apk.

Maybe it is somehow related to the characters some random generated token which is not be parsed correctly by the `okhttp3`?

Not all devices are affected, here are the affected devices so far:
![image](https://user-images.githubusercontent.com/1067120/104376848-420df680-552e-11eb-9ac6-ef349e7d100c.png)

Any info how I could get some additional information is welcome!

Error in adb:
```
01-12 17:06:16.513 28238 28487 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
01-12 17:06:16.513 28238 28487 E AndroidRuntime: Process: host.exp.exponent, PID: 28238
01-12 17:06:16.513 28238 28487 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at java.lang.String.substring(String.java:1975)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.java:9)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:9)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:17)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-12 17:06:16.513 28238 28487 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-navigation: ^4.4.0 => 4.4.2 
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: managed
```

### Steps to Reproduce
I'm working on creating a minimum test case.

### Expected Behavior vs Actual Behavior
Expected: App does not crash.
Actual: App crashes.

**Comment by viljark** [comment]
Caused by this: https://github.com/square/okhttp/issues/6897

**Comment by viljark** [comment]
@masiamj we disabled the third party plugin In Android which provides the problematic cookie for now until okhttp_3.12.x new release so that I can manually switch out the dependency in react-native.

**Comment by viljark** [comment]
> Interesting, and thanks for the update. For clarity, was the plugin on the _website/html_ you were loading into the `WebView`? We're loading a remote URI so trying to think through this. Thanks so much for your help!

Yes, we have a support chat plugin (HelpCrunch) which is loaded into the WebView. In some cases when setting up a session, an invalid cookie bricked the whole app. Could not find a way to retrieve the cookies before the crash to see which one was problematic.
