### ISSUE TITLE
[15:39:01] EEXIST: file already exists, mkdir 'C:\Users\admin\AppData\Local'

### ISSUE THREAD

**Issue by inimist** [expo/expo#11693]
while start expo app getting error.
`admin@admin-PC MINGW64 ~/Desktop/apps/Facebook (master)
$ expo start

[15:38:56] Starting project at C:\Users\admin\Desktop\apps\Facebook
[15:38:57] Expo DevTools is running at http://localhost:19002
[15:39:01] EEXIST: file already exists, mkdir 'C:\Users\admin\AppData\Local'
[15:39:01] Error: EEXIST: file already exists, mkdir 'C:\Users\admin\AppData\Local'
at Object.mkdirSync (fs.js:753:3)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:72:13)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:78:24)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:79:17)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:79:17)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:79:17)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:79:17)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:79:17)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:79:17)
at sync (C:\Users\admin\Desktop\apps\Facebook\node_modules\mkdirp\index.js:79:17)
`

**Comment by brentvatne** [comment]
can you provide the full trace? or is that all that you see?
