### ISSUE TITLE
[expo-bare] - Task :app:createReleaseExpoManifest FAILED for Release Build

### ISSUE THREAD

**Issue by tattivitorino** [expo/expo#11755]
### Summary of Issue 
App release build fails on Task :app:createReleaseExpoManifest FAILED
and it is related to the lib fs-extra
(see the full error below)

I made sure my node is >=10 (12.14.0)
I cleared the watchman cache, deleted the node_modules, reinstalled and restarted the project several times and the error persists. 

I inspected the yarn.lock and i have different fs-extra versions, (each lib that has fs-extra as a dependency has a different version) is this ok?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 4.1.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
        Android NDK: 20.1.5948944
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.1.0
    Expo Workflow: bare
```

### Here's my package.json
```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "podinstall": "cd ios && pod install && cd ..",
    "ios:device": "react-native run-ios --device \"Tatti Vitorino Iphone 7\"",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest",
    "bundle:ios": "react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios",
    "bundle:android": "react-native bundle --entry-file index.js --platform android --dev false --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/",
    "gradlew:clean": "cd android && ./gradlew clean",
    "gradlew:assemble": "./gradlew assembleRelease",
    "gradlew:bundle": "./gradlew bundleRelease",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/analytics": "^7.6.9",
    "@react-native-firebase/app": "^8.4.7",
    "@react-native-firebase/crashlytics": "^8.4.12",
    "axios": "^0.21.0",
    "expo": "~39.0.2",
    "expo-asset": "~8.2.0",
    "expo-constants": "~9.2.0",
    "expo-device": "~2.3.0",
    "expo-font": "~8.3.0",
    "expo-permissions": "~9.3.0",
    "expo-splash-screen": "~0.6.2",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "^0.4.1",
    "formik": "^2.2.3",
    "js-sha256": "^0.9.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "moment-duration-format": "^2.3.2",
    "moment-timezone": "^0.5.31",
    "native-base": "^2.13.14",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.3",
    "react-native-base64": "^0.1.0",
    "react-native-charts-wrapper": "^0.5.7",
    "react-native-device-info": "^7.0.2",
    "react-native-dotenv": "^2.4.2",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-notifications": "^3.4.0",
    "react-native-ratings": "^7.3.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-scalable-image": "^1.0.0",
    "react-native-screens": "~2.10.1",
    "react-native-svg": "^12.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12",
    "react-navigation": "^4.4.3",
    "react-navigation-drawer": "^2.6.0",
    "react-navigation-header-buttons": "^6.0.0",
    "react-navigation-stack": "^2.10.1",
    "react-navigation-tabs": "^2.10.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "babel-plugin-root-import": "^6.6.0",
    "jest": "~25.2.6",
    "metro-react-native-babel-preset": "^0.64.0",
    "patch-package": "^6.2.2",
    "postinstall-postinstall": "^2.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "~16.13.1",
    "redux-devtools-extension": "^2.13.8"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}


```
 
### Steps to Reproduce

I am following all the steps required for a release build according to the docs for a bare project.. actually this project was built a few months ago when I updated from sdk 36 to 39. 

here're all the steps:

```
react-native bundle --entry-file index.js --platform android --dev false --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

cd android && ./gradlew clean

./gradlew assembleRelease
```
When i run the last command here's the error i get:

```
> Task :app:createReleaseExpoManifest FAILED
/Users/tattivitorino/Dev/cittati/SeiMobCittati/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tattivitorino/Dev/cittati/SeiMobCittati/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createReleaseExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1

```

### Expected Behavior vs Actual Behavior
I expect the App to build the release version with no error.

**Comment by tattivitorino** [comment]
I've just upgraded my project from sdk 39 to 40 and the error persists! but now in different fs-extra libs.. all inside @expo dir inside node_modules.. 

if any of you have any idea of what i could do please help me!! I dont know what else to do.. I even tried patching all packages but that is a horrible workaround.. 

```
> Task :app:createReleaseExpoManifest FAILED
/Users/tattivitorino/Dev/cittati/SeiMobCittati/node_modules/@expo/metro-config/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tattivitorino/Dev/cittati/SeiMobCittati/node_modules/@expo/metro-config/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createReleaseExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1
```

here's my package.json after upgrading

```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "podinstall": "cd ios && pod install && cd ..",
    "ios:device": "react-native run-ios --device \"Tatti Vitorino Iphone 7\"",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest",
    "bundle:ios": "react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios",
    "bundle:android": "react-native bundle --entry-file index.js --platform android --dev false --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/",
    "gradlew:clean": "cd android && ./gradlew clean",
    "gradlew:assemble": "./gradlew assembleRelease",
    "gradlew:bundle": "./gradlew bundleRelease",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-native-community/async-storage": "~1.12.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-firebase/analytics": "^7.6.9",
    "@react-native-firebase/app": "^8.4.7",
    "@react-native-firebase/crashlytics": "^8.4.12",
    "axios": "^0.21.0",
    "expo": "^40.0.0",
    "expo-asset": "~8.2.1",
    "expo-constants": "~9.3.3",
    "expo-device": "~2.4.0",
    "expo-font": "~8.4.0",
    "expo-permissions": "~10.0.0",
    "expo-splash-screen": "~0.8.1",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.1",
    "formik": "^2.2.3",
    "js-sha256": "^0.9.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "moment-duration-format": "^2.3.2",
    "moment-timezone": "^0.5.31",
    "native-base": "^2.13.14",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63.4",
    "react-native-base64": "^0.1.0",
    "react-native-charts-wrapper": "^0.5.7",
    "react-native-device-info": "^7.0.2",
    "react-native-dotenv": "^2.4.2",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-notifications": "^3.4.0",
    "react-native-ratings": "^7.3.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-scalable-image": "^1.0.0",
    "react-native-screens": "~2.15.2",
    "react-native-svg": "12.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-unimodules": "~0.12.0",
    "react-native-web": "~0.13.12",
    "react-navigation": "^4.4.3",
    "react-navigation-drawer": "^2.6.0",
    "react-navigation-header-buttons": "^6.0.0",
    "react-navigation-stack": "^2.10.1",
    "react-navigation-tabs": "^2.10.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "babel-plugin-root-import": "^6.6.0",
    "fs-extra": "^9.1.0",
    "jest": "~25.2.6",
    "metro-react-native-babel-preset": "^0.64.0",
    "patch-package": "^6.2.2",
    "postinstall-postinstall": "^2.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "~16.13.1",
    "redux-devtools-extension": "^2.13.8"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

Expo Diagnostics:

```
Expo CLI 4.1.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
        Android NDK: 20.1.5948944
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.1.0
    Expo Workflow: bare
```

**Comment by tattivitorino** [comment]
@byCedric thx so much for your reply!
heres the output for the ```$ yarn node -e "console.log(process.versions)"```
```
yarn node v1.13.0
{
  node: '12.20.1',
  v8: '7.8.279.23-node.45',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '72',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  http_parser: '2.9.4',
  openssl: '1.1.1i',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```
I work normally with nvm on my regular terminal windows and how do I Check if I have multiple node versions running (besides nvm-selected one)?

thx again

**Comment by tattivitorino** [comment]
@byCedric I forgot to mention that I changed the node version to 12.20.1 which is the same version one work colleague is using to build another app we are working together

**Comment by gretzky** [comment]
@byCedric @tattivitorino is there any update on this? This is a blocking error for us on CircleCI. 

Node v14.15.0, CI also has `max-old-space-size` set for memory increase.

**Comment by brentvatne** [comment]
@gretzky - can you clarify what your issue is? the op is not about memory usage, rather it's about node version.

**Comment by tattivitorino** [comment]
@brentvatne i couldnt find any solution so I started another project and brought my old one into it. Not the best solution but the one I could make my project build. 

I remember before I started using nvm I had node installed maybe thats the problem?
