### ISSUE TITLE
Expo-Updates causes crash on release mode. 

### ISSUE THREAD

**Issue by AlenToma** [expo/expo#11801]
**Summary**

I have recently added and configurated the expo-updates.

Now the app crash on release mode at once.

When I checked the log on the phone, this is what i got .

```
02-01 07:20:07.437 E/AndroidRuntime(26845): FATAL EXCEPTION: main
02-01 07:20:07.437 E/AndroidRuntime(26845): Process: com.novelmanager, PID: 26845
02-01 07:20:07.437 E/AndroidRuntime(26845): java.lang.RuntimeException: Unable to create application com.novelmanager.MainApplication: java.lang.IllegalStateException: UpdatesController.getInstance() was called before the module was initialized
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7428)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7374)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.app.ActivityThread.access$1400(ActivityThread.java:302)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2117)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.os.Looper.loop(Looper.java:246)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.app.ActivityThread.main(ActivityThread.java:8414)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at java.lang.reflect.Method.invoke(Native Method)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
02-01 07:20:07.437 E/AndroidRuntime(26845): Caused by: java.lang.IllegalStateException: UpdatesController.getInstance() was called before the module was initialized
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at expo.modules.updates.UpdatesController.getInstance(UpdatesController.java:77)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at com.novelmanager.MainApplication$1.getJSBundleFile(MainApplication.java:40)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:81)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at com.novelmanager.MainApplication.onCreate(MainApplication.java:82)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
02-01 07:20:07.437 E/AndroidRuntime(26845): 	at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7423) 

```

I think that this is caused by ` UpdatesController.initialize(this);` in the `mainapplication.java`

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40.0.0

**Environment**

```
  Expo CLI 4.1.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 15.6.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.4.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: bare

```

**Reproducible demo or steps to reproduce from a blank project**

Just install and configure `expo updates` then start the application on release mod.  eg run this command `./gradlew assembleRelease` and install it on the phone.

And this is my mainfest if its importend

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.novelmanager">
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
	<application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher" android:allowBackup="false" android:theme="@style/AppTheme" android:requestLegacyExternalStorage="true">
		<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@alentoma/novelmanager" />
      <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="40.0.0" />
      <meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="default" />

  <activity
    android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<action android:name="android.intent.action.DOWNLOAD_COMPLETE" />
			</intent-filter>
		</activity>
		<activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
	</application>
</manifest>

```

**Comment by AlenToma** [comment]
I have fallowed @esamelson [here ](https://github.com/expo/expo/issues/8988#issuecomment-650600534) and he had a fix.

So this thread is not imported anymore
