### ISSUE TITLE
Expo build:android failed

### ISSUE THREAD

**Issue by wyeo** [expo/expo#11890]
**Summary**

Hello !
After running a build for Android devices, i have this error on logs :

```
Parsing json file: /app/turtle/workingdir/android/sdk39/android-shell-app/app/google-services.json
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] FAILURE: 
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] Build failed with an exception.
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] * What went wrong:
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] Execution failed for task ':app:processReleaseGoogleServices'.
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] > Missing project_info object
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] * Try:
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] * Get more help at https://help.gradle.org
Wed, 10 Feb 2021 11:11:53 GMT
[stderr] BUILD FAILED in 1m 2s
Wed, 10 Feb 2021 11:11:53 GMT
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Wed, 10 Feb 2021 11:11:53 GMT
Use '--warning-mode all' to show the individual deprecation warnings.
Wed, 10 Feb 2021 11:11:53 GMT
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
Wed, 10 Feb 2021 11:11:53 GMT
5 actionable tasks: 5 executed
Wed, 10 Feb 2021 11:11:54 GMT
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:976:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:396:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:95:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:43:28)
    at async build (/app/turtle/build/jobManager.js:181:33)
    at async processJob (/app/turtle/build/jobManager.js:118:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:49:5)
    at async main (/app/turtle/build/server.js:66:13)
```

My build id : `728df64c-97f2-4aa4-b6d4-3a208b144b03`

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

39

**Environment**
```
Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed
```

**Reproducible demo or steps to reproduce from a blank project**

`yarn build:android`

**Comment by AdamJNavarro** [comment]
Hey @wyeo, can you double check and make sure you've included a google-services.json file in your project AND that it is the correct one for said project?

Cheers,
Adam

**Comment by wyeo** [comment]
@AdamJNavarro Thanks for your answer
What do you mean by the correct one for said project ? It's different from the `googleServicesFile` for firebase ?
If not, yes i have already set a `googleServicesFile`

**Comment by CarlosEduardoC1** [comment]
Hi, @wyeo. Did you come up with a solution? Had same issue in my project

**Comment by DrNapNap** [comment]
I also have the same problem Two days saw it approx. and even though I create a new Google Service
