### ISSUE TITLE
[media-library] AddAssetsToAlbum crashes with too many sql variables error

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#12059]
**Summary**

AddAssetsToAlbum function crashes with "too many sql variables" error. 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

Bare Workflow
react native 0.63.4
expo-media-library 11.0.0

**Reproducible demo or steps to reproduce from a blank project**

I don't have a reproducible demo at the moment but i think we can figure this out with stack trace.

So i have an app that extracts frames from videos and there is a functionality to save all the frames that extracted. Code that i am using is this;

```
let assets = [];

for (const frame of frames) { //frames array has array of image uri's
     let asset = await MediaLibrary.createAssetAsync(frame.uri); // create asset from each frame uri
     assets.push(asset); // push created assets to new array
}

const albumName = 'FBF-' + dayjs();

let album = await MediaLibrary.createAlbumAsync(albumName, assets[0]); //create an album with first asset in the assets array

assets.shift(); //remove the first asset since we already added to album

await MediaLibrary.addAssetsToAlbumAsync(assets, album); // add other assets to that album
```

addAssetsToAlbum function creates this error in crashlytics;

```
Caused by android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR): , while compiling: SELECT _data FROM files WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (_id IN ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?<truncated: 4745 chars>
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:423)
       at android.content.ContentResolver.query(ContentResolver.java:946)
       at android.content.ContentResolver.query(ContentResolver.java:881)
       at android.content.ContentResolver.query(ContentResolver.java:837)
       at expo.modules.medialibrary.MediaLibraryUtils.a(MediaLibraryUtils.java:40)
       at expo.modules.medialibrary.AddAssetsToAlbum.a(AddAssetsToAlbum.java:14)
       at expo.modules.medialibrary.AddAssetsToAlbum.doInBackground(AddAssetsToAlbum.java:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

There can be so many (thousands) asset in assets array. Is there an upper limit of number of assets that can be added to album in one time?

 I am assuming <truncated 4745 chars> in stack trace corresponds to number of frames that user tries to save. In this [link](https://stackoverflow.com/questions/15312590/what-is-the-limit-of-sql-variables-one-can-specify-in-a-single-execsql-query) it says that maximum number of sql variables is 999.  If the issue caused by this i can split the array and do multiple addAssetsToAlbum call.

Thanks!

**Comment by ahmetbicer** [comment]
Three different variations of the stack trace for the same issue.

```
Caused by android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR): , while compiling: SELECT _data FROM files WHERE (_id IN ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,<truncated: 1113 chars>
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:418)
       at android.content.ContentResolver.query(ContentResolver.java:802)
       at android.content.ContentResolver.query(ContentResolver.java:752)
       at android.content.ContentResolver.query(ContentResolver.java:710)
       at expo.modules.medialibrary.MediaLibraryUtils.a(MediaLibraryUtils.java:40)
       at expo.modules.medialibrary.AddAssetsToAlbum.a(AddAssetsToAlbum.java:14)
       at expo.modules.medialibrary.AddAssetsToAlbum.doInBackground(AddAssetsToAlbum.java:2)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:798)
```

```
Caused by android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _data FROM files WHERE ((is_pending=0 OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'com.<packagename>' ))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (_id IN ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,<truncated: 431 chars>
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:472)
       at android.content.ContentResolver.query(ContentResolver.java:1186)
       at android.content.ContentResolver.query(ContentResolver.java:1118)
       at android.content.ContentResolver.query(ContentResolver.java:1074)
       at expo.modules.medialibrary.MediaLibraryUtils.a(MediaLibraryUtils.java:40)
       at expo.modules.medialibrary.AddAssetsToAlbum.a(AddAssetsToAlbum.java:14)
       at expo.modules.medialibrary.AddAssetsToAlbum.doInBackground(AddAssetsToAlbum.java:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

```
Caused by android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR): , while compiling: SELECT _data FROM files WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' )) AND ((is_drm is null OR is_drm <> 1)) AND (invalid=0)) AND (_id IN ( ?,?,?,?,?,?,?,?,?,?,?,<truncated: 595 chars>
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:423)
       at android.content.ContentResolver.query(ContentResolver.java:963)
       at android.content.ContentResolver.query(ContentResolver.java:898)
       at android.content.ContentResolver.query(ContentResolver.java:854)
       at expo.modules.medialibrary.MediaLibraryUtils.a(MediaLibraryUtils.java:40)
       at expo.modules.medialibrary.AddAssetsToAlbum.a(AddAssetsToAlbum.java:14)
       at expo.modules.medialibrary.AddAssetsToAlbum.doInBackground(AddAssetsToAlbum.java:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```
