### ISSUE TITLE
`takePictureAsync` throws OutOfMemoryError (app crashes)

### ISSUE THREAD

**Issue by muZk** [expo/expo#12184]
### Summary

App crashes when taking a picture using `expo-camera` on an old android device (e.g. Galaxy J3, Android 5.1.1)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/muzk/.rvm/rubies/ruby-2.4.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 27, 28, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0
        System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

This happens in an old android device: Samsung Galaxy J3 (2016) with Android 5.1.1

I have a demo project [here](https://github.com/muZk/expo-camera-out-of-memory):

- Run the app on a real android device (I think it should be an old one, like J3).
- Accept camera permissions.
- It should crash on camera ready callback (because it is going to take a picture).

Alternatively, you can `eject` from [this](https://snack.expo.io/@muzk/expo-camera-out-of-memory) snack.

Code:

```
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import { Camera } from 'expo-camera';

export default function App() {
  const camera = React.useRef(null)
  const [hasCameraPermission, setHasCameraPermission] = React.useState(false)

  React.useEffect(() => {
    Camera.requestPermissionsAsync().then((permissionResponse) => {
      setHasCameraPermission(permissionResponse?.status === 'granted')
    })
  }, [])

  const takePicture = () => {
    camera.current.takePictureAsync().then(console.log)
  };

  return (
    <View style={styles.container}>
      {hasCameraPermission ? (
        <Camera
          ref={camera}
          style={{ flex: 1 }}
          onCameraReady={() => takePicture()}
        />
      ) : (
        <Text>No camera permissions.</Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});
```

## Error logs

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation with 16777168 free bytes and 17MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
       at expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.rotateBitmap(ResolveTakenPictureAsyncTask.java:265)
       at expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:107)
       at expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:27)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

[react-native-camera](https://github.com/react-native-camera) had a similar issues:
- https://github.com/react-native-camera/react-native-camera/issues/590
- https://github.com/react-native-camera/react-native-camera/issues/1507

**Comment by brentvatne** [comment]
do you happen to know if it was resolved in react-native-camera? if so, can you point to the related PR or commits? it doesn't surprise me that they would see the same thing because that library was copy+pasted from expo-camera :) so, if they have solved this issue then it should be simple for us to apply the fix here

**Comment by muZk** [comment]
It also crashes when using react-native-camera (with `fixOrientation = true`)

Hmm... They changed the default value of `fixOrientation` from `true` to `false` (https://github.com/react-native-camera/react-native-camera/pull/682) and they removed`skipProcessing` because it was no longer necessary due to changes in https://github.com/react-native-camera/react-native-camera/pull/2577

**Comment by brentvatne** [comment]
@muZk - does `skipProcessing: false` solve your issue? this should be the same as `fixOrientation: false` except it also skips compression, which you can do with `expo-image-manipulator` if needed

**Comment by muZk** [comment]
Yes, `skipProcessing: false` fixes the issue.

**Comment by complexionpreventive** [comment]
> This issue is stale because it has been open for 60 days with no activity. If there is no activity in the next 7 days, the issue will be closed.





https://lnkr.fun/7ce6ba8
