### ISSUE TITLE
App crashing on load for iOS with following error

### ISSUE THREAD

**Issue by ewein** [expo/expo#1219]
My app is crashing on load only on iOS (SDK 24) and seems to only occur about 30% of the time. The app loads the splash screen and after a few seconds it will crash with the following error: 

```
There was a problem loading this experience.
               Try Again

Error: undefined is not an object (evaluating 'a.remove')
Error Code: CLIENT_LOADING_ERROR
Status Code: 1
```

App.json

```
{
  "expo": {
    "sdkVersion": "24.0.0",
    "primaryColor": "#FB4F94",
    "icon": "./src/assets/appLogo.png",
    "packagerOpts": {
      "assetExts": ["ttf"]
    },
    "android": {
      "package": "com.appidentifier.app",
      "versionCode": 4,
      "config": {
        "googleMaps": {
          "apiKey": "my-api-key"
        }
      }
    },
    "ios": {
      "bundleIdentifier": "co.appidentifer.here",
      "supportsTablet": true,
      "isRemoteJSEnabled": true,
      "infoPlist": {
        "NSCameraUsageDescription": "This app needs permission to use your camera in order to take photos for your posts.",
        "NSLocationWhenInUseUsageDescription": "This app needs permission to use your location in order to pin point your posts."
      }
    },
    "notification": {
      "androidCollapsedTitle": "Here",
      "icon": "./src/assets/logo.png"
    },
    "loading": {
      "hideExponentText": true
    },
    "splash": {
      "image": "./src/assets/splash.png",
      "resizeMode": "cover"
    },
    "assetBundlePatterns": [
      "src/assets/**",
      "node_modules/react-navigation/src/**/*.png",
      "node_modules/@expo/vector-icons/fonts/*.ttf"
    ]
  }
}
```

Package.json

```
{
  "name": "appName",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "^24.0.0",
    "react-native-scripts": "1.5.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^6.2.0",
    "es6-promise": "^4.1.1",
    "expo": "^24.0.0",
    "moment": "^2.19.2",
    "native-base": "^2.3.2",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-map-clustering": "^1.2.8",
    "react-native-maps": "^0.17.1",
    "react-native-slider": "^0.11.0",
    "react-native-swipe-gestures": "^1.0.2",
    "react-navigation": "^1.0.0-beta.19",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
}
```

**Comment by jimmylee** [comment]
Hey @ewein ! Thanks for using Expo, I'm sorry you're having this issue.

Without more information about your application or the problematic code paths, its really hard to diagnose this. Can you share some more details? SDK version? `package.json`? When did this start happening?

**Comment by ewein** [comment]
Updated.

**Comment by jimmylee** [comment]
Thanks @ewein, I'm going to test these dependencies in a blank application and see if they work. Is there any other information you can provide us?

**Comment by ewein** [comment]
There's not much to go on really, it only happens sometimes so I'm not really sure what else would be helpful. Here is my Redux store code:

```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from './reducers/index.js'
import initialState from './reducers/initialState.js';

const composedEnhancers = compose(
    applyMiddleware(thunk)
);

const store = createStore(
    rootReducer,
    initialState,
    composedEnhancers
);

export default store;
```

**Comment by jimmylee** [comment]
This is helpful! 🙌  I'll see if I can reproduce this problem.

**Comment by jimmylee** [comment]
@ewein I can verify that there is nothing wrong with your package.json. Upon destroying `node_modules` and doing a fresh `npm install` everything works as expected and I'm able to load a blank project.

I also wired up `redux` using your current version of redux and I found no issues either.

So I believe the error is occurring somewhere else, in your App config or maybe in your application logic.

**Comment by ewein** [comment]
Hmm ok I will take another look.

**Comment by ewein** [comment]
The only thing I'm doing in my App.js, which is as far as the app is getting I believe, is setting up the StackNavigator for the app and checking the network connection. Maybe it is something to do with NetInfo? 

```
import React, { Component } from 'react';
import { StatusBar, NetInfo } from 'react-native';
import { StackNavigator } from 'react-navigation';
import Expo, { AppLoading } from "expo";
import { Provider } from 'react-redux';
import store from './src/store.js';
import Main from './src/components/main';
import Login from './src/components/login';
import Signup from './src/components/signup';
import ForgotPassword from './src/components/login/forgotPassword';
import ViewPost from './src/components/viewPost';
import Filters from './src/components/map/filters';
import Notifications from './src/components/map/notifications';
import Profile from './src/components/profile';
import EditProfile from './src/components/settings/editProfile';
import ChangePassword from './src/components/settings/changePassword';
import SettingsList from './src/components/settings/settingsList';

class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            isLoaded: false,
            status: false,
            isConnected: true
        };
        
        this._checkNetworkConnection = this._checkNetworkConnection.bind(this);
    }
    
    componentDidMount() {
        Expo.Font.loadAsync({
            Roboto: require("native-base/Fonts/Roboto.ttf"),
            Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
            Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf")
        });
        
        const callback = (isConnected) => {
            NetInfo.isConnected.removeEventListener('connectionChange', callback);
            
            Expo.SecureStore.getItemAsync('hereToken').then((token) => {
                const status = token ? 'loggedIn' : false;
                if (isConnected) {
                    this.setState({
                        isLoaded: true,
                        status
                    });
                } else {
                    this.setState({
                        isLoaded: true,
                        isConnected: false,
                        status
                    });
                    
                    alert('No Connection! Please try again once you have established a connection.');
                }
    
                NetInfo.isConnected.addEventListener('connectionChange', (isConnected) => {
                    if (!isConnected) {
                        alert('You have lost your network connection. Please try again once you have established a connection.');
                    }
                });
            });
        };
        
        this._checkNetworkConnection(callback);
    }
    
    _checkNetworkConnection = (callback) => {
        NetInfo.isConnected.addEventListener('connectionChange', callback);
    };
    
    render() {
        const MainNavigator = StackNavigator({
                Main: {
                    screen: Main,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                Login: {
                    screen: Login,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                ForgotPassword: {
                    screen: ForgotPassword,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                Signup: {
                    screen: Signup,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                ViewPost: {
                    screen: ViewPost,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                Filters: {
                    screen: Filters,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                Notifications: {
                    screen: Notifications,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                Profile: {
                    screen: Profile,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                EditProfile: {
                    screen: EditProfile,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                ChangePassword: {
                    screen: ChangePassword,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                },
                SettingsList: {
                    screen: SettingsList,
                    navigationOptions: ({ navigation }) => ({
                        header: null
                    })
                }
            },{
                headerMode: 'screen',
                cardStyle: {
                    paddingTop: StatusBar.currentHeight
                }
            }
        );
        
        if (!this.state.isLoaded && !this.state.posts) {
            return <AppLoading />
        }
        
        return (
            <Provider store={store}>
                <MainNavigator screenProps={this.state} />
            </Provider>
        );
    }
}

export default App;
```

**Comment by brentvatne** [comment]
@ewein - quick tip for you: try to isolate the error and reproduce on https://snack.expo.io. the only way anyone could possibly help with the code that you have provided is to carefully read every line and guess what error you might be getting and what might cause that

**Comment by ewein** [comment]
This error is happening on both my iOS devices, one is an iPhone 6 running iOS 10.2.1 and on an iPhone 8 running iOS 11.2.2

**Comment by ewein** [comment]
After upgrading to SDK 25 the error has changed to `o.remove` instead of `a.remove` and seems to happen about 1 in every 5 tries on iOS only.

**Comment by ewein** [comment]
If I do a fresh install of the app it loads fine but the second time you go to open it, it shows the splash screen for a second and crashes with that error. This is on iOS 11.2.2

**Comment by ewein** [comment]
Also this only happens in production after the app has been published and built for iOS. Running the app locally with exp start it works fine on both Android and iOS but once its been published on iOS we start seeing this random error.

**Comment by ewein** [comment]
Ok I setup my project with Sentry and here is the error it spits out:

```
TypeError: undefined is not an object (evaluating 'o.remove')
  at watchId(/mnt/c/projects/here/node_modules/expo/src/Location.js:79:56)
  at _currentSubscription(/mnt/c/projects/here/node_modules/expo/src/Location.js:190:10)
  at value(/mnt/c/projects/here/node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:180:16)
  at value(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:349:7)
  at _inCall(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:117:18)
  at this(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:310:10)
  at value(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:116:79)
```

**Comment by terribleben** [comment]
Hey there, sorry for the slow followup here. We have a pending fix being tracked here: https://github.com/expo/expo/issues/1276
