### ISSUE TITLE
Haste Map Collisions in Expo

### ISSUE THREAD

**Issue by davidhenley** [expo/expo#122]
Getting this error all the time in Expo when starting packager. Reformatted computer, reinstalled everything and still issue.

```
Rebuilding haste map to recover from error:
Error: @providesModule naming collision:
  Duplicate module name: readable-stream
  Paths: /Users/david/Dropbox/workspace/exponent/test/node_modules/stream-counter/node_modules/readable-stream/package.json collides with /Users/david/Dropbox/workspace/exponent/test/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/david/Dropbox/workspace/exponent/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/Users/david/Dropbox/workspace/exponent/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
8:20:52 PM
Error: @providesModule naming collision:
  Duplicate module name: string_decoder
  Paths: /Users/david/Dropbox/workspace/exponent/test/node_modules/stream-counter/node_modules/string_decoder/package.json collides with /Users/david/Dropbox/workspace/exponent/test/node_modules/string_decoder/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
8:20:52 PM
Rebuilding haste map to recover from error:
Error: @providesModule naming collision:
  Duplicate module name: string_decoder
  Paths: /Users/david/Dropbox/workspace/exponent/test/node_modules/stream-counter/node_modules/string_decoder/package.json collides with /Users/david/Dropbox/workspace/exponent/test/node_modules/string_decoder/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/david/Dropbox/workspace/exponent/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/Users/david/Dropbox/workspace/exponent/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
8:21:00 PM
Rebuilding haste map to recover from error:
Error: @providesModule naming collision:
  Duplicate module name: wordwrap
  Paths: /Users/david/Dropbox/workspace/exponent/test/node_modules/wordwrap/package.json collides with /Users/david/Dropbox/workspace/exponent/test/node_modules/uglify-js/node_modules/wordwrap/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/david/Dropbox/workspace/exponent/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/Users/david/Dropbox/workspace/exponent/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
```

**Comment by dikaiosune** [comment]
I suspect that watchman (used by the RN packager) may be interacting poorly with Dropbox here -- they both hook into the OS to get filesystem notifications and that can cause problems. If you move your project outside Dropbox and restart your computer, are you able to start the packager?

**Comment by brentvatne** [comment]
I believe we resolved this yesterday on Slack, was perhaps react-navigation related
