### ISSUE TITLE
Encountered internal error running command: TypeError: Invalid Version: android-6.0.1

### ISSUE THREAD

**Issue by binubeee** [expo/expo#1220]
Iam facing this issue after upgrading my appium server and java client.
My current version:
Appium- 1.7.2
appium-java - 5.0.4

its giving error at this line:
driver = new AndroidDriver<AndroidElement>(new URL(
					"http://0.0.0.0:4723/wd/hub"), capabilities);

**Capabilities:**
		capabilities.setCapability("platformName", "android");
		capabilities.setCapability("platformVersion","6.0.1");
		capabilities.setCapability("deviceName", "Android");
		capabilities.setCapability("udid", deviceID);
		capabilities.setCapability("appPackage", pack);
		capabilities.setCapability("appActivity",act);
		capabilities.setCapability("clearSystemFiles", true);

**Error:**
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"xxxxxxxxxx.MainActivity","appPackage":"xxxxxxxxxx","clearSystemFiles":true,"deviceName":"Android","platformName":"Android","platformVersion":"6.0.1","udid”:”6767677”},null,{"desiredCapabilities":{"appActivity":"xxxxxxxxxx.MainActivity","appPackage":"xxxxxxxxxx","clearSystemFiles":true,"deviceName":"Android","platformName":"Android","platformVersion":"6.0.1","udid":"6767677"},"firstMatch":[{"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1515192722200 (17:52:02 GMT-0500 (EST))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"appActivity":"com.gm.o... into desiredCapabilities object {"appActivity":"xxxxxxxxxx.MainActivity","ap...
[Appium] Creating new AndroidDriver (v1.37.0) session
[Appium] Capabilities:
[Appium]   appActivity: xxxxxxxxxx.MainActivity
[Appium]   appPackage: xxxxxxxxxx
[Appium]   clearSystemFiles: true
[Appium]   deviceName: Android
[Appium]   platformName: android
[Appium]   platformVersion: 6.0.1
[Appium]   udid: 6767677
[BaseDriver] Session created with session id: 56291214-5319-4148-87c6-611cc7fbc7bd
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_144
[ADB] Checking whether adb is present
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: TypeError: Invalid Version: android-6.0.1
    at new SemVer (/usr/local/lib/node_modules/appium/node_modules/semver/semver.js:293:11)
    at compare (/usr/local/lib/node_modules/appium/node_modules/semver/semver.js:566:10)
    at rcompare (/usr/local/lib/node_modules/appium/node_modules/semver/semver.js:576:10)
    at Array.sort (native)
    at ADB.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:89:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

Can you please tell me what am I doing wrong. This was working fine before update.
Previous versions were:
Appium- 1.7.1
Java client - 4.1.2

**Comment by binubeee** [comment]
wrong place
