### ISSUE TITLE
exp build:ios fails 

### ISSUE THREAD

**Issue by kadoshms** [expo/expo#1234]
Hey,

Worked perfectly before, now I can't build my ios app using `exp build:ios`.

The stacktrace:
 
```
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[ { action: 'ruby_dir',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx',
    doesExist: false },
  { action: 'app_management',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/app_management',
    doesExist: true },
  { action: 'fetch_cert',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/fetch_cert',
    doesExist: true },
  { action: 'fetch_new_provisioning_profile',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/fetch_new_provisioning_profile',
    doesExist: true },
  { action: 'fetch_push_cert',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/fetch_push_cert',
    doesExist: true },
  { action: 'validate_apple_certs',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/validate_apple_certs',
    doesExist: true },
  { action: 'validate_apple_credentials',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/validate_apple_credentials',
    doesExist: true },
  { action: 'validate_apple_push_certs',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/validate_apple_push_certs',
    doesExist: true } ]
? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? *******
? Password? *********
[exp] Validating Credentials...
[exp] Error while gathering & validating credentials
[exp] {"result":"failure","reason":"Could not understand JSON reply from Ruby local auth scripts","rawDump":"/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:252:in `rescue in lock': There was an error while trying to write to Gemfile.lock. It is likely that  (Bundler::InstallError)\nyou need to allow write permissions for the file at path: \n/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/vendor/Gemfile.lock\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:237:in `lock'\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/environment.rb:34:in `lock'\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:44:in `setup'\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'\n\tfrom /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.2-osx/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'\n"}
[exp] undefined
[exp] undefined
  
```

Thanks in advance!

**Comment by fxfactorial** [comment]
Your permissions at `/usr/local/lib/node_modules` are incorrect. Most likely you installed exp with sudo. 

Choices: 

1. Fix your permissions
2. Use yarn global installed exp
3. Use a local copy of exp in your project as a devDep.
