### ISSUE TITLE
Error when android starting app again when app is already running

### ISSUE THREAD

**Issue by dooboolab** [expo/expo#1254]
In detached expo app for sdk 24,
First time when I open the app it is ok.
However when I press home button and try to run app again it crashes.
(or go to playstore and search app and open)

Below is error logs.

Can anyone try this?

```
01-14 01:03:21.644 21983-21983/com.cooni.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.cooni.app, PID: 21983
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
                                                                   at host.exp.exponent.experience.ExperienceActivity.onNewIntent(ExperienceActivity.java:245)
                                                                   at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
                                                                   at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1236)
                                                                   at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2857)
                                                                   at android.app.ActivityThread.performNewIntents(ActivityThread.java:2872)
                                                                   at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2888)
                                                                   at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1587)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:241)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by dooboolab** [comment]
I found why this is happening.
```
android:launchMode="singleTop"
```
I set above param in .MainActivity as told in [react-native-fcm](https://github.com/evollu/react-native-fcm)

I had to do this because detaching won't let me use push notification in expo.

Also I don't understand why it crash by setting launchMode to singleTop in MainActivity.

**Comment by jesseruder** [comment]
Hello! Changing the `launchMode` will definitely cause problems. If you want to make this many changes to the core Expo code you'll probably need to build everything from source: https://github.com/expo/expo#standalone-apps

**Comment by jesseruder** [comment]
@dooboolab I just pushed a fix for the NPE in `onNewIntent`

**Comment by dooboolab** [comment]
@jesseruder 
Thank you. How can I get updated version for expo android with this commit?
Needing it deperately.

**Comment by dooboolab** [comment]
Issue is solved thanks.
