### ISSUE TITLE
`expo-yarn-workspaces` error when running on Expo Web

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#12674]
### Summary

I configure the monorepo for my application following the guidelines of https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces, the native application works correctly but the web part throws the following error:

```
❯ lerna run --stream --scope @ambito-dolar/client start -- --clear --web
info cli using local version of lerna
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "@ambito-dolar/client"
lerna info filter [ '@ambito-dolar/client' ]
lerna info Executing command in 1 package: "yarn run start --clear --web"
@ambito-dolar/client: yarn run v1.22.10
@ambito-dolar/client: $ expo start --clear --web
@ambito-dolar/client: [15:10:29] Starting project at /Users/outaTiME/Code/ambito-dolar/packages/client
@ambito-dolar/client: [15:10:30] Developer tools running on http://localhost:19007
@ambito-dolar/client: [15:10:32] Starting Metro Bundler
@ambito-dolar/client: [15:10:33] Your JavaScript transform cache is empty, rebuilding (this may take a minute).
@ambito-dolar/client: [15:10:33] Unexpected token '?'
@ambito-dolar/client: [15:10:33] /Users/outaTiME/Code/ambito-dolar/node_modules/expo-yarn-workspaces/webpack.js:31
@ambito-dolar/client:     const patterns = workspacePackage.workspaces ?? [];
@ambito-dolar/client:                                                   ^
@ambito-dolar/client: SyntaxError: Unexpected token '?'
@ambito-dolar/client:     at compileFunction (<anonymous>)
@ambito-dolar/client:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
@ambito-dolar/client:     at Module._compile (internal/modules/cjs/loader.js:963:27)
@ambito-dolar/client:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
@ambito-dolar/client:     at Module.load (internal/modules/cjs/loader.js:863:32)
@ambito-dolar/client:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
@ambito-dolar/client:     at Module.require (internal/modules/cjs/loader.js:887:19)
@ambito-dolar/client:     at require (internal/modules/cjs/helpers.js:74:18)
@ambito-dolar/client:     at Object.<anonymous> (/Users/outaTiME/Code/ambito-dolar/packages/client/webpack.config.js:1:38)
@ambito-dolar/client:     at Module._compile (internal/modules/cjs/loader.js:999:30)
@ambito-dolar/client:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
@ambito-dolar/client:     at Module.load (internal/modules/cjs/loader.js:863:32)
@ambito-dolar/client:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
@ambito-dolar/client:     at Module.require (internal/modules/cjs/loader.js:887:19)
@ambito-dolar/client:     at require (internal/modules/cjs/helpers.js:74:18)
@ambito-dolar/client:     at invokeWebpackConfigAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:624:27)
@ambito-dolar/client:     at createWebpackConfigAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:492:20)
@ambito-dolar/client:     at startAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:168:24)
@ambito-dolar/client:     at Object.openAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:259:5)
@ambito-dolar/client:     at /usr/local/lib/node_modules/expo-cli/src/urlOpts.ts:138:9
@ambito-dolar/client:     at async Promise.all (index 2)
@ambito-dolar/client:     at handleMobileOptsAsync (/usr/local/lib/node_modules/expo-cli/src/urlOpts.ts:113:3)
@ambito-dolar/client: error Command failed with exit code 1.
@ambito-dolar/client: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run start --clear --web exited 1 in '@ambito-dolar/client'
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment

```
  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.1 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/opt/node@12/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Added `expo-yarn-workspaces` dependency.
2. Modification of the "main" entry with `__generated__/AppEntry.js` in `package.json`.
3. Creation of `metro.config.js` and `webpack.config.js`.
4. Execution of `expo start --clear --web` with lerna style `lerna run --stream --scope @ambito-dolar/client start -- --clear --web`).
5. The above-mentioned error is displayed.

**Comment by ajsmth** [comment]
@outaTiME I believe you can work around this for now by running your script with Node v14 instead of 12!

**Comment by outaTiME** [comment]
Thanks, @ajsmth, that's what I did at the moment to avoid the nullish operator error
