### ISSUE TITLE
app crash with Failed to clear legacy OkHttp cache

### ISSUE THREAD

**Issue by superyarik** [expo/expo#12696]
### Summary

update my react+redux+saga app to 41, it work in expo go, but after build apk version it crash at the start

there is error logs from logcat from app

04-23 15:32:27.610 5780-5780/? E/adbd: recv: OPEN 00000017 00000000 0015:73 68 65 6C 6C 3A 6C 6F 67 63 61 74 20 2D 76 20 6C 6F 6E 67 00 
    service_to_fd: shell:logcat -v long
04-23 15:32:27.863 6715-6715/? E/ProActivieLaunch: Sending Broadcast
    
    --------- beginning of system
04-23 15:32:27.874 5111-5111/? E/ActivityManager: TouchDown intent received, starting ActiveLaunch
04-23 15:32:27.898 25569-25569/? E/Zygote: isWhitelistProcess - Process is Whitelisted
04-23 15:32:27.899 25569-25569/? E/libpersona: scanKnoxPersonas
    Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
04-23 15:32:27.965 5111-5201/? E/memtrack: Couldn't load memtrack module
04-23 15:32:27.997 5111-5201/? E/memtrack: Couldn't load memtrack module
04-23 15:32:28.077 5111-5201/? E/memtrack: Couldn't load memtrack module
04-23 15:32:28.138 25569-25569/? E/f: Failed to clear legacy OkHttp cache
    java.io.IOException: not a readable directory: /data/user/0/ru.hubex.engineer/files/okhttp
        at okhttp3.internal.io.FileSystem$1.deleteContents(FileSystem.java:7)
        at okhttp3.internal.cache.DiskLruCache.delete(DiskLruCache.java:2)
        at okhttp3.Cache.delete(Cache.java:1)
        at host.exp.exponent.q.f.b(ExponentNetwork.java:4)
        at host.exp.exponent.q.f.<init>(ExponentNetwork.java:7)
        at host.exp.exponent.m.a.<init>(NativeModuleDepsProvider.java:7)
        at host.exp.exponent.m.a.c(NativeModuleDepsProvider.java:2)
        at g.a.a.b.<init>(Exponent.java:7)
        at g.a.a.b.m(Exponent.java:2)
        at host.exp.exponent.e.onCreate(ExpoApplication.java:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
04-23 15:32:28.180 5111-5201/? E/memtrack: Couldn't load memtrack module
04-23 15:32:28.227 5111-5201/? E/memtrack: Couldn't load memtrack module
04-23 15:32:28.517 25569-25569/? E/j: Runtime exception in RNObject when calling method getCurrentReactContext: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Method[] java.lang.Class.getMethods()' on a null object reference
04-23 15:32:28.518 25569-25569/? E/ExperienceActivity: java.lang.NullPointerException: Attempt to invoke virtual method 'host.exp.exponent.j host.exp.exponent.j.c(java.lang.String, java.lang.Object[])' on a null object reference
04-23 15:32:28.544 25569-25569/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.hubex.engineer, PID: 25569
    java.lang.RuntimeException: Unable to resume activity {ru.hubex.engineer/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: java.lang.IllegalArgumentException: Unexpected type in an array: class org.json.JSONObject
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.RuntimeException: Expo encountered a fatal error: java.lang.IllegalArgumentException: Unexpected type in an array: class org.json.JSONObject
        at host.exp.exponent.experience.q.G(BaseExperienceActivity.java:7)
        at host.exp.exponent.experience.q.H(Unknown Source:0)
        at host.exp.exponent.experience.a.run(Unknown Source:2)
        at android.app.Activity.runOnUiThread(Activity.java:6281)
        at host.exp.exponent.experience.q.F(BaseExperienceActivity.java:2)
        at host.exp.exponent.experience.q.onResume(BaseExperienceActivity.java:5)
        at host.exp.exponent.experience.ExperienceActivity.onResume(ExperienceActivity.java:1)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7415)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
04-23 15:32:28.585 5111-5203/? E/PhoneWindow_APM :: isCalledPackage return true
04-23 15:32:29.117 8509-8537/? E/PBSessionCacheImpl: sessionId[37424596933235955] not persisted.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.22.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/opt/node@10/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: 4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

app work under expo go

**Comment by Kirysha** [comment]
I get the same error, is there a solution?

**Comment by byCedric** [comment]
Without a reproducible example, there isn't a lot we can do. Please provide a repository, with the issue, that we can clone to investigate this further.

**Comment by juanoude** [comment]
I am having the same problem. Have no idea what is causing it. The only error message i get is the same as you. And in the emulator works fine, but the apk crashes in splash screen frequently, after the crash the user has to reinstall the app, completely freezes forever, not even restarting the phone solves it. Did you manage to solve it?

**Comment by juanoude** [comment]
> I am having the same problem. Have no idea what is causing it. The only error message i get is the same as you. And in the emulator works fine, but the apk crashes in splash screen frequently, after the crash the user has to reinstall the app, completely freezes forever, not even restarting the phone solves it. The complaints by users are increasing. Did you manage to solve it?
We solved in our application. It was the background location permission not declared in the android manifest. Since SDK 40, the background location permission in not declared by default anymore, you have to do it in the app.json > android > permissions...
