### ISSUE TITLE
Image asset uri location isn’t readable at published app

### ISSUE THREAD

**Issue by allandiego** [expo/expo#12690]
### Summary

Using Image.resolveAssetSource() to get a imported image asset uri and then reading this uri with FileSystem.readAsStringAsync works in dev env but not in published env

dev env uri log
```
file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540adcr%252Fmy-app/ExponentAsset-0cb836e736f4b116715cf3193823f93e.png
```

In a published app env its returning a error Location isn’t readable.
published uri log
```
file:///data/user/0/host.exp.exponent/files/.expo-internal/c987193e5c0e5820c674dc5951bcbbdf.png
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 2.4.1 - C:\Users\Diego\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 28.0.3, 29.0.2
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

readAsStringAsync works on dev env app but not at published env

```ts
import { Image } from 'react-native';
import * as FileSystem from 'expo-file-system';

import image1 from 'assets/images/image1.png';
import image2 from 'assets/images/image3.png';
import image3 from 'assets/images/image2.png';

const itemsAssets = {
  item1: {
    name: 'test',
    img: image1,
  },
  item2: {
    name: 'test2',
    img: image2,
  },
  item3: {
    name: 'test3',
    img: image3,
  },
};

const parsedBase64Images = {};
for (const [key, item] of Object.entries(itemsAssets)) {
  const imageUri = Image.resolveAssetSource(item.img).uri;

  parsedBase64Images[key] = await FileSystem.readAsStringAsync(imageUri, {
    encoding: FileSystem.EncodingType.Base64,
  });
}
```

**Comment by superyarik** [comment]
facing this with crash on application start:

```
04-23 10:38:18.754 21642-21642/? E/f: Failed to clear legacy OkHttp cache
    java.io.IOException: not a readable directory: /data/user/0/ru.hubex.engineer/files/okhttp
        at okhttp3.internal.io.FileSystem$1.deleteContents(FileSystem.java:7)
        at okhttp3.internal.cache.DiskLruCache.delete(DiskLruCache.java:2)
        at okhttp3.Cache.delete(Cache.java:1)
        at host.exp.exponent.q.f.b(ExponentNetwork.java:4)
        at host.exp.exponent.q.f.<init>(ExponentNetwork.java:7)
        at host.exp.exponent.m.a.<init>(NativeModuleDepsProvider.java:7)
        at host.exp.exponent.m.a.c(NativeModuleDepsProvider.java:2)
        at g.a.a.b.<init>(Exponent.java:7)
        at g.a.a.b.m(Exponent.java:2)
        at host.exp.exponent.e.onCreate(ExpoApplication.java:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

**Comment by superyarik** [comment]
attach error logs from logcat in app crash

`04-23 10:49:10.243 25189-25189/? E/adbd: recv: OPEN 0000001e 00000000 0015:73 68 65 6C 6C 3A 6C 6F 67 63 61 74 20 2D 76 20 6C 6F 6E 67 00 
    service_to_fd: shell:logcat -v long
04-23 10:49:10.561 28999-28999/? E/ProActivieLaunch: Sending Broadcast
    
    --------- beginning of system
04-23 10:49:10.565 5014-5014/? E/ActivityManager: Checking for the Active launch isDataCleared :true, isAutoRunBlocked : false
04-23 10:49:10.719 25280-25280/? E/Zygote: isWhitelistProcess - Process is Whitelisted
04-23 10:49:10.719 25280-25280/? E/libpersona: scanKnoxPersonas
    Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
04-23 10:49:10.945 25280-25280/? E/f: Failed to clear legacy OkHttp cache
    java.io.IOException: not a readable directory: /data/user/0/ru.hubex.engineer/files/okhttp
        at okhttp3.internal.io.FileSystem$1.deleteContents(FileSystem.java:7)
        at okhttp3.internal.cache.DiskLruCache.delete(DiskLruCache.java:2)
        at okhttp3.Cache.delete(Cache.java:1)
        at host.exp.exponent.q.f.b(ExponentNetwork.java:4)
        at host.exp.exponent.q.f.<init>(ExponentNetwork.java:7)
        at host.exp.exponent.m.a.<init>(NativeModuleDepsProvider.java:7)
        at host.exp.exponent.m.a.c(NativeModuleDepsProvider.java:2)
        at g.a.a.b.<init>(Exponent.java:7)
        at g.a.a.b.m(Exponent.java:2)
        at host.exp.exponent.e.onCreate(ExpoApplication.java:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
04-23 10:49:11.313 5014-5108/? E/memtrack: Couldn't load memtrack module
04-23 10:49:11.890 25280-25341/? E/unknown:ReactNative: ReactInstanceManager.createReactContext: mJSIModulePackage not null
04-23 10:49:11.890 25280-25350/? E/ReactNativeJNI: logMarker CREATE_REACT_CONTEXT_END
04-23 10:49:11.920 25280-25280/? E/ExperienceActivity: java.lang.NullPointerException: Attempt to invoke virtual method 'host.exp.exponent.j host.exp.exponent.j.c(java.lang.String, java.lang.Object[])' on a null object reference
04-23 10:49:11.934 25316-25316/? E/dex2oat: <SS>: apk not found at /data/data/ru.hubex.engineer/files/
04-23 10:49:12.097 25280-25341/? E/unknown:ReactNative: ReactInstanceManager.createReactContext: ReactFeatureFlags.useTurboModules == false
04-23 10:49:12.098 25280-25350/? E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_START
04-23 10:49:12.101 25280-25351/? E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-23 10:49:12.127 25280-25351/? E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
04-23 10:49:12.162 25383-25383/? E/Zygote: isWhitelistProcess - Process is Whitelisted
04-23 10:49:12.163 25383-25383/? E/libpersona: scanKnoxPersonas
    Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
04-23 10:49:12.757 3200-3344/? E/Sensors: Sensor : Meta event
04-23 10:49:12.864 25280-25280/? E/unknown:ReactNative: Unable to launch logbox because react was unable to create the root view
04-23 10:49:15.090 25280-25350/? E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_END
04-23 10:49:15.134 25280-25350/? E/ReactNativeJS: s: Native Client is not available, can't start on native.
04-23 10:49:15.317 25280-25351/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.common.JavascriptException: s: Native Client is not available, can't start on native., stack:
    s@1260:161
    <unknown>@1422:5424
    v@2:1473
    <unknown>@1421:203
    v@2:1473
    <unknown>@1419:496
    v@2:1473
    <unknown>@1244:4153
    v@2:1473
    <unknown>@1239:1399
    v@2:1473
    <unknown>@1181:1303
    v@2:1473
    <unknown>@1180:775
    v@2:1473
    <unknown>@1167:627
    v@2:1473
    <unknown>@1140:485
    v@2:1473
    <unknown>@1114:466
    v@2:1473
    <unknown>@473:368
    v@2:1473
    <unknown>@6:60
    v@2:1473
    d@2:875
    global code@3679:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:764)
04-23 10:49:15.317 25280-25351/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: s: Native Client is not available, can't start on native., stack:
    s@1260:161
    <unknown>@1422:5424
    v@2:1473
    <unknown>@1421:203
    v@2:1473
    <unknown>@1419:496
    v@2:1473
    <unknown>@1244:4153
    v@2:1473
    <unknown>@1239:1399
    v@2:1473
    <unknown>@1181:1303
    v@2:1473
    <unknown>@1180:775
    v@2:1473
    <unknown>@1167:627
    v@2:1473
    <unknown>@1140:485
    v@2:1473
    <unknown>@1114:466
    v@2:1473
    <unknown>@473:368
    v@2:1473
    <unknown>@6:60
    v@2:1473
    d@2:875
    global code@3679:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:764)
04-23 10:49:15.326 25280-25280/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.hubex.engineer, PID: 25280
    java.lang.RuntimeException: Expo encountered a fatal error: s: Native Client is not available, can't start on native., stack:
    s@1260:161
    <unknown>@1422:5424
    v@2:1473
    <unknown>@1421:203
    v@2:1473
    <unknown>@1419:496
    v@2:1473
    <unknown>@1244:4153
    v@2:1473
    <unknown>@1239:1399
    v@2:1473
    <unknown>@1181:1303
    v@2:1473
    <unknown>@1180:775
    v@2:1473
    <unknown>@1167:627
    v@2:
        at host.exp.exponent.experience.q.G(BaseExperienceActivity.java:7)
        at host.exp.exponent.experience.q.H(Unknown Source:0)
        at host.exp.exponent.experience.a.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
04-23 10:49:15.383 25423-25423/? E/Zygote: isWhitelistProcess - Process is Whitelisted
04-23 10:49:15.384 25423-25423/? E/libpersona: scanKnoxPersonas
    Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
04-23 10:49:15.434 5014-5108/? E/memtrack: Couldn't load memtrack module
04-23 10:49:15.445 5014-5111/? E/PhoneWindow_APM :: isCalledPackage return false
04-23 10:49:15.463 5014-5108/? E/memtrack: Couldn't load memtrack module
04-23 10:49:15.466 25442-25442/? E/Zygote: isWhitelistProcess - Process is Whitelisted
04-23 10:49:15.467 25442-25442/? E/libpersona: scanKnoxPersonas
    Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
04-23 10:49:15.505 5014-5108/? E/memtrack: Couldn't load memtrack module
04-23 10:49:15.562 5014-5108/? E/memtrack: Couldn't load memtrack module
04-23 10:49:15.587 5014-5108/? E/memtrack: Couldn't load memtrack module
04-23 10:49:15.613 5014-5108/? E/memtrack: Couldn't load memtrack module
04-23 10:49:15.919 12366-12452/? E/PBSessionCacheImpl: sessionId[54387862284744430] not persisted.
`

**Comment by blairio** [comment]
s this a duplicate of https://github.com/expo/expo/issues/10803 ?

**Comment by linaia** [comment]
Hi having the same problem on publish expo managed sdk41 (using https://github.com/reggie3/react-native-webview-leaflet)

```
07-02 11:45:07.960 18386 21192 W ReactNativeJS: [Error: Location 'file:///data/user/0/host.exp.exponent/files/.expo-internal/797430db761ed76b5fd4a49a56dd5d85.html' isn't readable.]
07-02 11:45:07.960 18386 21192 W ReactNativeJS: Unable to resolve index file
```
