### ISSUE TITLE
preset [jest-expo/web] Breaks jest test due to '../Libraries/Image/Image'

### ISSUE THREAD

**Issue by conor909** [expo/expo#12711]
### Summary

Using the react native jest setup, fails on web tests, because the file `../Libraries/Image/Image` doesn't exist for web.

I could be wrong but maybe this is because the jest-setup file references a mock to `../Libraries/Image/Image` but that `/Image` file only has a `.ios` so it doesnt exist in a web environment.

Web tests fail with the following error:
```
  ● Test suite failed to run

    Cannot find module '../Libraries/Image/Image' from '../../node_modules/react-native/jest/setup.js'

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../../node_modules/react-native/jest/setup.js:58:4)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40.0.1

### Environment

```
Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.6 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/conor/.rvm/rubies/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. `expo init my-project`
2. Choose blank managed project 
3. `cd my-project`
4. `yarn add -D jest-expo @testing-library/jest-native @testing-library/react-native`
5.  add test script to package.json `"test": "jest --config jest.config.js"`
6.  add jest config and test files to project root `jest.config.js` & `jest.setup.js` & `App.test.js`and add the content below
7.  When your finished adding the content to the files run `yarn test`

```js

// jest.config.js

const universalConfig = {
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)'
  ],
  setupFiles: [
    './jest.setup.js',
    'react-native/jest/setup.js',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/cypress/'
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70
    }
  }
}

module.exports = {
  projects: [
    { preset: 'jest-expo/web', ...universalConfig },
    { preset: 'jest-expo/ios', ...universalConfig }
  ]
}

``` 

```js

//jest.setup.js

// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper')

```
```js

// App.test.js

import React from 'react'
import { render } from '@testing-library/react-native'

import App from './App'

test('Test the app displays with the Renx Form', async () => {
  const { queryByText } = render(<App />)
  expect(queryByText('Open up App.js to start working on your app!')).toBeTruthy()
})

```

**Comment by estiventhneira** [comment]
really?
