### ISSUE TITLE
Trying to get users location results in error on iOS

### ISSUE THREAD

**Issue by ewein** [expo/expo#1276]
I'm trying to get the users location but on iOS I'm getting the following error: 

**undefined is not an object (evaluating 'subscription.remove')**

It seems to only happen on certain devices, for me its happening on the iPhone 8 running iOS 11.2.2

```
const userLocation = await Location.getCurrentPositionAsync({
       enableHighAccuracy: true
});
```

**Comment by ide** [comment]
Can you provide a stack trace that would better indicate where this error is coming from?

**Comment by ewein** [comment]
The weird thing is its actually working, it does return the users location and the correct data:

```
Object {
   "coords": Object {
         "accuracy": 12,
         "altitude": 445.328388636592,
         "altitudeAccuracy": 20.93479347229004,
         "heading": -1,
         "latitude": 49.269004227997465,
         "longitude": -123.16702837761672,
         "speed": 0.10105473548173904,
     },
   "timestamp": 1516289574003.275,
}
```

However it pops this error message everytime. If I remove the block of code I provided above the error goes away.

![error](https://user-images.githubusercontent.com/2450286/35107368-9bb833c2-fc25-11e7-922b-a1151c0ff9a2.jpg)

**Comment by ewein** [comment]
I am now receiving the following error as well on Android (Samsung Galaxy S8):

![screenshot_20180119-101324](https://user-images.githubusercontent.com/2450286/35165207-3b82573e-fd02-11e7-94f0-d798585293d4.png)

**Comment by terribleben** [comment]
This will be hard for us to debug without an app that reproduces it, since none of the visible code uses anything called "subscription". The error may be buried in a dependency. Can you create a [snack](https://snack.expo.io) that reproduces the error?

**Comment by ewein** [comment]
Its coming from that call to `Location.getCurrentPositionAsync`, like I said if I comment out that block everything works fine which means it must be in the Expo Location module or in one of its dependencies. It works fine on Android but I can reproduce the error on certain versions of iOS such as 10.2.1 and iOS 11.2.2

**Comment by ewein** [comment]
This issue is really causing issues for my users so I enabled Sentry to try and find the root cause of the issue and it is coming from the Expo Location module. Any help with this would be great.

```
TypeError: undefined is not an object (evaluating 'subscription.remove')
  at callback(/mnt/c/projects/here/node_modules/expo/src/Location.js:84:9)
  at ? (/mnt/c/projects/here/node_modules/expo/src/Location.js:193:11)
  at emit(/mnt/c/projects/here/node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:181:11)
  at __callFunction(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:353:20)
  at fn(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:118:7)
  at __guardSafe(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:316:7)
  at callFunctionReturnFlushedQueue(/mnt/c/projects/here/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:117:5)
```

**Comment by brentvatne** [comment]
hi there! you can fork expo-sdk at the version you're using and add this change

```diff
commit 3cd940597876f7e52d60d9660257576432928f92 (HEAD -> master, origin/master, origin/HEAD)
Author: Brent Vatne <brentvatne@gmail.com>
Date:   Tue Feb 13 11:25:33 2018 -0800

    [sdk] Guard subscription removal

diff --git a/libraries/exponent-sdk/src/Location.js b/libraries/exponent-sdk/src/Location.js
index 9c7332ae81..45aae5e063 100644
--- a/libraries/exponent-sdk/src/Location.js
+++ b/libraries/exponent-sdk/src/Location.js
@@ -81,12 +81,14 @@ function getCurrentPositionAsync(options: LocationOptions): Promise<LocationData
           resolve(location);
           done = true;
         }
-        subscription.remove();
+        subscription && subscription.remove();
+        subscription = null;
       });

       // In case the callback is fired before we get here.
       if (done) {
-        subscription.remove();
+        subscription && subscription.remove();
+        subscription = null;
       }
     } catch (e) {
       reject(e);
```

this should fix a race condition where the callback is fired before the subscription object is initialized. it'll be included in sdk 26

**Comment by lgngnr** [comment]
similar issue in Location.getHeadingAsync() ... i'll try adding this code 
subscription && subscription.remove();
subscription = null;
