### ISSUE TITLE
Crash Android bare workflow enabling debug mode.

### ISSUE THREAD

**Issue by marcocesarato** [expo/expo#12947]
### Summary

Crash on android app with bare workflow enabling debug mode.

At first launch when Android is building node console with metro (`yarn start`) crash while Android is building and I need to relaunch it after the debug apk installed.

If I install enable the debug mode the app crash. If I reopen it, the app continue to crash so I need to uninstall it to reset the configs.

I tried to clean all cache of npm and yarn and creating my project from zero. It still happen.

Error enabling debug mode on Android (from Flipper):
```
FATAL EXCEPTION: mqt_js

Cannot figure out the cause

FATAL EXCEPTION: mqt_js
Process: com.testapp, PID: 5989
java.lang.AssertionError: No source URL loaded, have you initialised the instance?
	at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
	at com.facebook.react.modules.debug.SourceCodeModule.getTypedExportedConstants(SourceCodeModule.java:39)
	at com.facebook.fbreact.specs.NativeSourceCodeSpec.getConstants(NativeSourceCodeSpec.java:35)
	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:129)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 6036 (create_react_co), pid 5989 (com.testapp)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-05-16 08:39:03+0000
pid: 5989, tid: 6036, name: create_react_co  >>> com.testapp <<<
uid: 10157
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    eax 00000000  ebx bdeb65e8  ecx bdeb5140  edx 00000000
    edi f0e57410  esi beb85f80
    ebp beb85fb8  esp beb85e20  eip bde5c9e0
backtrace:
      #00 pc 0002c9e0  /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/lib/x86/libreanimated.so (reanimated::NativeProxy::installJSIBindings()+1328) (BuildId: dc3366671b2b6ac42fb5528082a719e3e1293199)
      #01 pc 00037019  /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/lib/x86/libreanimated.so (facebook::jni::detail::MethodWrapper<void (reanimated::NativeProxy::*)(), &(reanimated::NativeProxy::installJSIBindings()), reanimated::NativeProxy, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<reanimated::NativeProxy, facebook::jni::detail::BaseHybridClass>::JavaPart, facebook::jni::JObject, void>::_javaobject*>)+41) (BuildId: dc3366671b2b6ac42fb5528082a719e3e1293199)
      #02 pc 00036f88  /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/lib/x86/libreanimated.so (facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<reanimated::NativeProxy, facebook::jni::detail::BaseHybridClass>::JavaPart, facebook::jni::JObject, void>::_javaobject*>), &(facebook::jni::detail::MethodWrapper<void (reanimated::NativeProxy::*)(), &(reanimated::NativeProxy::installJSIBindings()), reanimated::NativeProxy, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<reanimated::NativeProxy, facebook::jni::detail::BaseHybridClass>::JavaPart, facebook::jni::JObject, void>::_javaobject*>)), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<reanimated::NativeProxy, facebook::jni::detail::BaseHybridClass>::JavaPart, facebook::jni::JObject, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*)+72) (BuildId: dc3366671b2b6ac42fb5528082a719e3e1293199)
      #03 pc 00036f33  /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/lib/x86/libreanimated.so (facebook::jni::detail::MethodWrapper<void (reanimated::NativeProxy::*)(), &(reanimated::NativeProxy::installJSIBindings()), reanimated::NativeProxy, void>::call(_JNIEnv*, _jobject*)+35) (BuildId: dc3366671b2b6ac42fb5528082a719e3e1293199)
      #04 pc 00142132  /apex/com.android.art/lib/libart.so (art_quick_generic_jni_trampoline+82) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #05 pc 0013b922  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #06 pc 001d0381  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+241) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #07 pc 00386701  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+385) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #08 pc 0037aa3e  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1070) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #09 pc 007a4179  /apex/com.android.art/lib/libart.so (MterpInvokeDirect+633) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #10 pc 001358a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_direct+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #11 pc 0000529c  [anon:dalvik-classes23.dex extracted in memory from /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/base.apk!classes23.dex] (com.swmansion.reanimated.NativeProxy.prepare+44)
      #12 pc 007a14fe  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+1806) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #13 pc 001357a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #14 pc 00005216  [anon:dalvik-classes23.dex extracted in memory from /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/base.apk!classes23.dex] (com.swmansion.reanimated.NativeProxy.<init>+130)
      #15 pc 007a44ae  /apex/com.android.art/lib/libart.so (MterpInvokeDirect+1454) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #16 pc 001358a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_direct+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #17 pc 000060fc  [anon:dalvik-classes23.dex extracted in memory from /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/base.apk!classes23.dex] (com.swmansion.reanimated.NodesManager.initWithContext+4)
      #18 pc 007a14fe  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+1806) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #19 pc 001357a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #20 pc 00006654  [anon:dalvik-classes23.dex extracted in memory from /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/base.apk!classes23.dex] (com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules+24)
      #21 pc 007a355e  /apex/com.android.art/lib/libart.so (MterpInvokeInterface+2126) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #22 pc 001359a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #23 pc 002fa2a8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/base.apk] (com.facebook.react.ReactInstanceManager.createReactContext+276)
      #24 pc 007a44ae  /apex/com.android.art/lib/libart.so (MterpInvokeDirect+1454) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #25 pc 001358a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_direct+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #26 pc 002fa178  [anon:dalvik-classes.dex extracted in memory from /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/base.apk] (com.facebook.react.ReactInstanceManager.access$1100)
      #27 pc 007a505e  /apex/com.android.art/lib/libart.so (MterpInvokeStatic+1454) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #28 pc 00135921  /apex/com.android.art/lib/libart.so (mterp_op_invoke_static+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #29 pc 002f9898  [anon:dalvik-classes.dex extracted in memory from /data/app/~~So-OKglwPe_0i51TDMivMw==/com.testapp-tRcf-kHnJikbFu-kheJiqg==/base.apk] (com.facebook.react.ReactInstanceManager$5.run+140)
      #30 pc 007a355e  /apex/com.android.art/lib/libart.so (MterpInvokeInterface+2126) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #31 pc 001359a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #32 pc 000eb7d0  /apex/com.android.art/javalib/core-oj.jar (java.lang.Thread.run+8)
      #33 pc 0036fb02  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.16375758241455872412)+370) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #34 pc 00379b00  /apex/com.android.art/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+176) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #35 pc 0078b325  /apex/com.android.art/lib/libart.so (artQuickToInterpreterBridge+1061) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #36 pc 0014220d  /apex/com.android.art/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #37 pc 0013b922  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #38 pc 001d0381  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+241) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #39 pc 0062f37c  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+620) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #40 pc 0062f595  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+85) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #41 pc 00697701  /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+1537) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #42 pc 000e6974  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #43 pc 00078567  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

It happen also on OSX to me and my coworkers
```
  Expo CLI 4.4.7 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.6.3 - C:\versions\node\v12.7.0\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 25, 28, 29, 30
        Build Tools: 23.0.1, 25.0.1, 28.0.3, 29.0.0, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Just running
1.  `expo init` 
2.  `yarn android`
3.  Enabling debug mode (Ctrl + M and pressing Debug)

**Comment by brentvatne** [comment]
unfortunately this is an expected behavior when using react-native-reanimated@2 - https://github.com/software-mansion/react-native-reanimated/issues/1990 - you can use flipper to debug instead
