### ISSUE TITLE
Expo Barcode Scanner native crash

### ISSUE THREAD

**Issue by Joshandrews43** [expo/expo#13049]
### Summary

Random Android users in production report crashing and 90% of our crashes come from the error below in the standalone production build. 

Important to note it crashes without the user even navigating to the screen.

This is the entirety of the code I use, and I am only scanning QR codes: 
```
import { BarCodeScanner } from 'expo-barcode-scanner';

...

 const [hasPermission, setHasPermission] = useState(false);

  useEffect(() => {
    const requestPermissions = async () => {
      const { status } = await BarCodeScanner.requestPermissionsAsync();
      setHasPermission(status === 'granted');
    };
    requestPermissions();
  }, []);

if (!hasPermission) return null;

return ( 
   <BarCodeScanner
        onBarCodeScanned={() =>   Analytics.logEvent('KioskScan')}
        style={{ width: '100%', height: '100%', position: 'absolute' }}
  />
);
```

Pasting crash from Google Play Crashes & ANR's: 
```
java.lang.RuntimeException: 
  at android.os.AsyncTask$4.done (AsyncTask.java:399)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:289)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
Caused by: java.lang.RuntimeException: 
  at android.hardware.Camera.native_getParameters (Native Method)
  at android.hardware.Camera.getParameters (Camera.java:2132)
  at expo.modules.barcodescanner.BarCodeScannerViewFinder$BarCodeScannerAsyncTask.doInBackground (BarCodeScannerViewFinder.java:198)
  at expo.modules.barcodescanner.BarCodeScannerViewFinder$BarCodeScannerAsyncTask.doInBackground (BarCodeScannerViewFinder.java:179)
  at android.os.AsyncTask$3.call (AsyncTask.java:378)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:289)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0

### Environment

Expo CLI 4.4.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.4.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Can't reliably reproduce, but it's a native crash in the managed workflow so I'm fairly certain it is an SDK issue otherwise Sentry would have thrown something.

**Comment by superyarik** [comment]
facing random android crashes while scaning barcodes too

**Comment by jayala** [comment]
Same error over here in bare workflow, stack:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'org.unimodules.interfaces.barcodescanner.BarCodeScannerResult org.unimodules.interfaces.barcodescanner.BarCodeScanner.scan(byte[], int, int, int)' on a null object reference
        at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:36)
        at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:6)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by Alta1re** [comment]
Same problem here.
Using expo managed workflow.
Just scanning QR-Code, on iOS everything works fine, on android the app crashes (100%) before the camera screen is shown.
I can´t see any error-message in debugger.

**Comment by joewearing** [comment]
I fixed this by editing `scanners/ZxingBarCodeScanner.kt`

```diff
+ override fun scan(data: ByteArray, width: Int, height: Int, rotation: Int): BarCodeScannerResult? {
- override fun scan(data: ByteArray, width: Int, height: Int, rotation: Int): BarCodeScannerResult {
    // rotate for zxing if orientation is portrait
    var innerData = data
    var innerWidth = width
    ...

+   return scan(generateSourceFromImageData(innerData, innerWidth, innerHeight));
-   return requireNotNull(
-     scan(generateSourceFromImageData(innerData, innerWidth, innerHeight))
-   ) { "Scan output cannot be null" }
  }
```

**Comment by timhubert** [comment]
I have the same error when testing automatically in Google Play Console, but I can't reproduce it manually.

**Comment by barbhackk** [comment]
Hi,

I have the same problem with latest Expo SDK43 only on Android device with Android 10 (SDK 29). Work perfect on Android 11 (SDK 30).
The app crash with error:

`11-26 11:19:14.974 21843 21973 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
11-26 11:19:14.974 21843 21973 E AndroidRuntime: Process: com.glibl.gliblclient, PID: 21843
11-26 11:19:14.974 21843 21973 E AndroidRuntime: java.lang.IllegalArgumentException: Scan output cannot be null
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at expo.modules.barcodescanner.scanners.ZxingBarCodeScanner.scan(ZxingBarCodeScanner.kt:56)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend(BarCodeScannerViewFinder.kt:194)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
11-26 11:19:14.980  1990 21974 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
`

For test, run `Expo init my-app`, install expo-barcode-scanner with `expo install expo-barcode-scanner`. Integrate like [https://docs.expo.dev/versions/v43.0.0/sdk/bar-code-scanner/](https://docs.expo.dev/versions/v43.0.0/sdk/bar-code-scanner/)

Next step : `npm run android`.

Try open the app and crash instantly.

`Expo diagnostics`

`Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      npm: 7.22.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 26, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 32.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare`

Thanks

**Comment by barbhackk** [comment]
> I fixed this by editing `scanners/ZxingBarCodeScanner.kt`
> 
> ```diff
> + override fun scan(data: ByteArray, width: Int, height: Int, rotation: Int): BarCodeScannerResult? {
> - override fun scan(data: ByteArray, width: Int, height: Int, rotation: Int): BarCodeScannerResult {
>     // rotate for zxing if orientation is portrait
>     var innerData = data
>     var innerWidth = width
>     ...
> 
> +   return scan(generateSourceFromImageData(innerData, innerWidth, innerHeight));
> -   return requireNotNull(
> -     scan(generateSourceFromImageData(innerData, innerWidth, innerHeight))
> -   ) { "Scan output cannot be null" }
>   }
> ```

Where is this file ?

Thanks

**Comment by julian-maughan** [comment]
> Where is this file ?

[packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/ZxingBarCodeScanner.kt](https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/ZxingBarCodeScanner.kt)

**Comment by 1-alex98** [comment]
How do I patch this file? Just in node_modules?

**Comment by 1-alex98** [comment]
Did that ... did not seem to have an effect

**Comment by 1-alex98** [comment]
```
12-02 11:42:52.743  8567  8744 E AndroidRuntime: java.lang.IllegalArgumentException: Scan output cannot be null
12-02 11:42:52.743  8567  8744 E AndroidRuntime:        at abi43_0_0.expo.modules.barcodescanner.scanners.ZxingBarCodeScanner.scan(ZxingBarCodeScanner.kt:5)
12-02 11:42:52.743  8567  8744 E AndroidRuntime:        at abi43_0_0.expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend(BarCodeScannerViewFinder.kt:13)
```
And I used `patch-package` to persist the change in `node_modules/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/ZxingBarCodeScanner.kt`

Any caches or similar I need to consider?

**Comment by DemoWearing** [comment]
> Any caches or similar I need to consider?

That's the correct file, potentially just:
```
cd android
./gradlew clean
cd ..
npm run android
```

**Comment by 1-alex98** [comment]
There is no gradle wrapper there. But I mean I could install gradle to do this. But there is no build folder which gradle clean could delete

**Comment by Joshandrews43** [comment]
Circling back here, I am now building with `eas build` on expo SDK 44, and I am still getting this issue (from Play store crash logs): 

```
java.lang.RuntimeException: 
  at android.hardware.Camera.native_getParameters (Native Method)
  at android.hardware.Camera.getParameters (Camera.java:2153)
  at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend (BarCodeScannerViewFinder.kt:195)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
```

All of my modules are updated, and while it is definitely less often than before, it is still 5 users in the 24 hours since SDK 44 has been out for my app.

**Comment by lukmccall** [comment]
@Joshandrews43, please open a new issue for that. Thanks ;)
