### ISSUE TITLE
Project works fine on expo host but crashes on Play Store testing

### ISSUE THREAD

**Issue by atalon-kn** [expo/expo#13044]
### Summary

I build standalone bundle with expo build:android and the app works fine on expo host: exp://exp.host/@atalon-kn/lonlonmall

However, after I upload the bundle to Play Store and conduct internal test, this fatal error occurs and crashes the app:
`FATAL EXCEPTION: main
Process: com.xxx.lonlonmall, PID: 6888
java.lang.RuntimeException: Expo encountered a fatal error: TypeError: undefined is not an object (evaluating 'v.init'), stack:
setOptionsAsync@1484:1789
value@1482:322
<unknown>@749:841
v@2:1473
<unknown>@6:54
v@2:1473
d@2:875
global code@2062:3
	at host.exp.exponent.experience.q.E(BaseExperienceActivity.java:7)
	at host.exp.exponent.experience.a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

I used to config "entryPoint" in "app.config.js" which I suspected to be the reason for the error, then I changed the config to "main" in "package.json" like a fresh project and build again, the situation persists.

I tried workaround to eject the project but this issue: [https://github.com/unimodules/react-native-unimodules/issues/128](https://github.com/unimodules/react-native-unimodules/issues/128) prevents me from building a bare android app.

The ios app works perfectly fine, the issue on android has held back my app launching for almost a week.

I tried to start a new template project with expo SDK 41 and upload to Play Store and it worked fine.

What would be the reason that the app works on expo host but crashes on Play Store, is there something that was missing that I have to do?

my project dependencies:
"dependencies": {
    "@expo/html-elements": "~0.0.1",
    "@expo/vector-icons": "~12.0.3",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/drawer": "^5.12.3",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "@reduxjs/toolkit": "^1.5.1",
    "@types/uuid": "^8.3.0",
    "@unimodules/core": "~6.0.0",
    "@unimodules/react-native-adapter": "~5.7.0",
    "agentkeepalive": "^4.1.4",
    "app-module-path": "~2.2.0",
    "axios": "~0.21.1",
    "body-parser": "~1.19.0",
    "compression": "~1.7.4",
    "cookie-parser": "~1.4.5",
    "cors": "~2.8.5",
    "expo": "^40.0.1",
    "expo-apple-authentication": "~2.2.2",
    "expo-asset": "~8.2.1",
    "expo-auth-session": "^3.1.0",
    "expo-constants": "~9.3.3",
    "expo-crypto": "^9.1.0",
    "expo-facebook": "~9.1.0",
    "expo-firebase-recaptcha": "^1.3.0",
    "expo-font": "~8.4.0",
    "expo-linking": "^2.2.0",
    "expo-localization": "~9.1.0",
    "expo-payments-stripe": "~8.4.0",
    "expo-random": "^11.0.0",
    "expo-secure-store": "~9.3.0",
    "expo-splash-screen": "^0.10.0",
    "expo-status-bar": "~1.0.3",
    "expo-web-browser": "~8.6.0",
    "express": "~4.17.1",
    "firebase": "7.9.0",
    "firebase-admin": "~9.5.0",
    "formik": "^2.2.6",
    "helmet": "~4.3.1",
    "i18next": "~19.8.4",
    "locale": "~0.1.0",
    "lodash": "^4.17.21",
    "method-override": "~3.0.0",
    "native-base": "~2.15.2",
    "path": "~0.12.7",
    "qs": "^6.10.1",
    "querystring": "~0.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-i18next": "~11.8.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-appearance": "~0.3.3",
    "react-native-collapsible": "^1.5.3",
    "react-native-dotenv": "^2.5.5",
    "react-native-elements": "^3.4.1",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-get-random-values": "^1.6.0",
    "react-native-google-places-autocomplete": "^2.2.0",
    "react-native-maps": "0.27.1",
    "react-native-reanimated": "^2.0.1",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-section-list-get-item-layout": "^2.2.3",
    "react-native-snap-carousel": "~3.9.1",
    "react-native-svg": "12.1.0",
    "react-native-unimodules": "^0.13.3",
    "react-native-vector-icons": "~8.0.0",
    "react-native-web": "^0.15.0",
    "react-native-web-swiper": "~2.2.1",
    "react-native-webview": "^11.3.2",
    "react-redux": "^7.2.3",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "reselect": "^4.0.0",
    "uuid": "^8.3.2",
    "yup": "^0.32.9"
  }

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.4.8 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ^0.15.0 => 0.15.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

not sure if it can be reproduced on a simple new project

**Comment by atalon-kn** [comment]
build succeeded with @stripe/stripe-react-native
