### ISSUE TITLE
exp build:ios errors during "Compiling resources" step

### ISSUE THREAD

**Issue by tungvi** [expo/expo#1318]
Hey guys, this is my first time building IOS app, just wondering why I kept having this error when trying to exp build:ios

`
...
isSplashScreenDisabled: true }
Configuring iOS Launch Screen...
2018-01-24 02:45:42.907 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:42.947 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.065 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.067 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.067 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.068 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.069 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.070 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.073 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.073 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.073 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.073 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.074 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
2018-01-24 02:45:43.074 ibtoold[40005:237579] WARNING: Unhandled destination metrics: (null)
Compiling resources...
[02:45:46] 'ios-shell-app' errored after 7.05 s
[02:45:46] Error: Process exited with non-zero code: 1
at ChildProcess.child.on (/usr/local/turtle-agent/tools-public/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
at emitTwo (events.js:125:13)
at ChildProcess.emit (events.js:213:7)
at maybeClose (internal/child_process.js:927:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
unable to run shell app builder
`

and here is my App.json

`
{
  "expo": {
    "name": "Qnect Native App",
    "slug":"qnect-native-app",
    "privacy": "public",
    "sdkVersion": "23.0.0",
    "version": "0.0.1",
    "icon": "./assets/img/logo/qnect_new_blue.jpg",
    "ios":{
      "bundleIdentifier": "com.qnect.qnect-native-app",
      "supportsTablet": false
    },
    "android": {
      "package": "com.qnect.qnect-native-app"
    }
  }
}
`

**Comment by terribleben** [comment]
Hi, sorry you ran into this. Can you share your Expo username?

**Comment by tungvi** [comment]
Hi Ben,

Thank you for the reply, I have resolved the issue by restructuring the
app.json , especially the android section. It was difficult to trace the
actual error but all good now.

Kind Regards,
Vi Tung

**Comment by terribleben** [comment]
Interesting. Did you change anything related to your app's icon? (`ios.icon`, `android.icon`, or just `icon` in app.json).

I want to make sure that other people don't have this problem, so if you can remember what you changed to fix the issue, that would be helpful.

I'm glad it's working for you now! Closing the issue, but feel free to reply with any other information.
