### ISSUE TITLE
Expo-updates in bare react native project causing app crash

### ISSUE THREAD

**Issue by vinaygoyal20** [expo/expo#13229]
### Summary

App working fine in debug mode but crashed when build is released.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

38.0.0

### Environment

 java.lang.RuntimeException: Unable to create application com.pranicme.MainApplication: java.lang.IllegalStateException: UpdatesController.getInstance() was called before the module was initialized
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6614)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalStateException: UpdatesController.getInstance() was called before the module was initialized
        at expo.modules.updates.UpdatesController.getInstance(UpdatesController.java:80)
        at com.pranicme.MainApplication$1.getJSBundleFile(MainApplication.java:60)
        at com.reactnativenavigation.react.NavigationReactNativeHost.createReactInstanceManager(NavigationReactNativeHost.java:53)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.reactnativenavigation.react.ReactGateway.<init>(ReactGateway.java:20)
        at com.reactnativenavigation.NavigationApplication.createReactGateway(NavigationApplication.java:40)
        at com.reactnativenavigation.NavigationApplication.onCreate(NavigationApplication.java:27)
        at com.pranicme.MainApplication.onCreate(MainApplication.java:81)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6609)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:226) 
        at android.app.ActivityThread.main(ActivityThread.java:7592) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2021-06-10 12:07:01.676 3773-4203/? E/OOMEventManager: oom event not support this pkg, dismiss this!

### Reproducible demo or steps to reproduce from a blank project

created project with react-native-cli
Also checked
https://github.com/expo/expo/issues/8988

**Comment by cruzach** [comment]
Are you sure you've gone through this whole setup properly- https://docs.expo.io/bare/installing-updates/?

**Comment by vinaygoyal20** [comment]
Yup, it happened when i used react-native-navigation which changes in MainActivity and MainApplication.java such as
import com.reactnativenavigation.NavigationActivity;
and in MainApplication.java
+import com.reactnativenavigation.NavigationApplication;
+import com.reactnativenavigation.react.NavigationReactNativeHost;
-public class MainApplication extends Application implements ReactApplication {
+public class MainApplication extends NavigationApplication {}

I removed react-native-navigatiion and with react-navigation it was working fine

**Comment by filipef101** [comment]
Hey @andrewandersonakido Any update on your side?
