### ISSUE TITLE
UseFonts throws an error in Mac BigSur

### ISSUE THREAD

**Issue by poustchi** [expo/expo#13354]
### Summary

UseFonts throws the following error on BigSur but its ok on Catalina
```
[Error: Unexpected status line: �������~�
                                                     ��#��p����x�����4����b
                                                                           �%������-��%��&-5���1�&
                                                                                                  ��������
                                                                                                          ���������
                                                                                                                   &���,���H����
                                                                                                                                �#��]
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

```
 Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Code:

https://snack.expo.io/@poustchi/smiling-hummus

The above code is working fine when using Mac Catalina but in the BigSur i get the following error

```
FontStatus: null false
FontStatus: [Error: Unexpected status line: �������~�
                                                     ��#��p����x�����4����b
                                                                           �%������-��%��&-5���1�&
                                                                                                  ��������
                                                                                                          ���������
                                                                                                                   &���,���H����
                                                                                                                                �#��] false
```

**Comment by poustchi** [comment]
I forget to mention that I see this error in Android Simulator and Android phones. IOS simulator and IPhone are working fine.

**Comment by poustchi** [comment]
```
[Unhandled promi]e rejection: Error: Unexpected status line: !�
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-file-system/build/FileSystem.js:105:17 in downloadAsync
at node_modules/expo-file-system/build/FileSystem.js:101:7 in downloadAsync
at node_modules/expo-asset/build/PlatformUtils.js:49:25 in _downloadAsyncManagedEnv
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```
