### ISSUE TITLE
takePictureAsync crash on android Nexus 6P

### ISSUE THREAD

**Issue by gpessa** [expo/expo#13631]
### Summary

When I call the takePictureAsync and try to take a picture, the application crash ( at leas on the simulator).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.1.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
import React, { useState, useEffect, useRef } from "react"
import { StyleSheet, Text, View, TouchableOpacity } from "react-native"
import { Camera } from "expo-camera"

export default function App() {
  const [hasPermission, setHasPermission] = useState(null)
  const [type, setType] = useState(Camera.Constants.Type.back)
  const cameraRef = useRef<Camera>()

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestPermissionsAsync()
      setHasPermission(status === "granted")
    })()
  }, [])

  if (hasPermission === null) {
    return <View />
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>
  }

  const snap = async () => {
    if (cameraRef.current) {
      await cameraRef.current.takePictureAsync()
    }
  }

  return (
    <View style={styles.container}>
      <Camera style={styles.camera} type={type} ref={cameraRef}>
        <View style={styles.buttonContainer}>
          <TouchableOpacity
            style={styles.button}
            onPress={() => {
              snap()
            }}>
            <Text style={styles.text}>SHOT</Text>
          </TouchableOpacity>
        </View>
      </Camera>
    </View>
  )
}
const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  camera: {
    flex: 1,
    height: 400
  },
  buttonContainer: {
    flex: 1,
    backgroundColor: "transparent",
    flexDirection: "row",
    margin: 20
  },
  button: {
    flex: 0.1,
    alignSelf: "flex-end",
    alignItems: "center"
  },
  text: {
    fontSize: 18,
    color: "white"
  }
})
```

**Comment by byCedric** [comment]
Hi @gpessa, thanks for writing in. What is the error you get from the crash? You should be able to [find it with logcat](https://docs.expo.io/workflow/logging/#view-logs-from-android-device-or-emulator).

**Comment by gpessa** [comment]
```07-15 23:20:22.491   527  5130 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
07-15 23:20:22.549 19866 20016 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
07-15 23:20:22.549 19866 20016 E AndroidRuntime: Process: host.exp.exponent, PID: 19866
07-15 23:20:22.549 19866 20016 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at abi42_0_0.expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:7)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at abi42_0_0.expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:1)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-15 23:20:22.549 19866 20016 E AndroidRuntime: 	... 4 more
07-15 23:20:22.560   527  5130 W ActivityTaskManager:   Force finishing activity host.exp.exponent/.experience.HomeActivity
07-15 23:20:22.561   527 20071 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-15 23:20:22.585   527  5130 W ActivityTaskManager:   Force finishing activity host.exp.exponent/.experience.ExperienceActivity
07-15 23:20:22.494   527  5130 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
07-15 23:20:22.589   307  1615 D goldfish-address-space: claimShared: Ask to claim region [0x3c6e25000 0x3c7725000]
07-15 23:20:22.633   527  4993 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
07-15 23:20:22.706   527   553 W Looper  : Slow dispatch took 134ms android.fg h=com.android.server.DropBoxManagerService$DropBoxManagerBroadcastHandler c=null m=1
07-15 23:20:22.712   527   562 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
07-15 23:20:22.714   527   562 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
07-15 23:20:22.727 19866 20016 I Process : Sending signal. PID: 19866 SIG: 9
07-15 23:20:22.929   721   745 I ndroid.systemu: NativeAlloc concurrent copying GC freed 8219(436KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7482KB/14MB, paused 5.941ms total 160.186ms
07-15 23:20:23.011   527  2955 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=128, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Uid: 10153 AdministratorUids: [] RequestorUid: 10153 RequestorPackageName: host.exp.exponent] ], android.os.BinderProxy@419c790)
07-15 23:20:23.011   527  3974 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=129, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Uid: 10153 AdministratorUids: [] RequestorUid: 10153 RequestorPackageName: host.exp.exponent] ], android.os.BinderProxy@3280889)
07-15 23:20:23.013   527  2955 I ActivityManager: Process host.exp.exponent (pid 19866) has died: prcp TOP
07-15 23:20:23.016   527   605 I WindowManager: WIN DEATH: Window{253648a u0 host.exp.exponent/host.exp.exponent.experience.ExperienceActivity}
07-15 23:20:23.017   527   605 W InputDispatcher: Attempted to unregister already unregistered input channel '253648a host.exp.exponent/host.exp.exponent.experience.ExperienceActivity (server)'
07-15 23:20:23.026   527  3293 I WindowManager: WIN DEATH: Window{b8a62d3 u0 host.exp.exponent/host.exp.exponent.experience.ExperienceActivity}
07-15 23:20:23.026   527  3293 W InputDispatcher: Attempted to unregister already unregistered input channel 'b8a62d3 host.exp.exponent/host.exp.exponent.experience.ExperienceActivity (server)'
07-15 23:20:23.034   291   291 I Zygote  : Process 19866 exited due to signal 9 (Killed)
07-15 23:20:23.050   527  3974 I WindowManager: WIN DEATH: Window{8e4a39b u0 host.exp.exponent/host.exp.exponent.experience.HomeActivity}
07-15 23:20:23.051   527  3974 W InputDispatcher: Attempted to unregister already unregistered input channel '8e4a39b host.exp.exponent/host.exp.exponent.experience.HomeActivity (server)'
07-15 23:20:23.061   527   566 I libprocessgroup: Successfully killed process cgroup uid 10153 pid 19866 in 45ms```

**Comment by giautm** [comment]
I run into same issue on SDKv43, Android Emulator: `Pixel_4_XL_API_23`
```sh
12-17 18:26:46.768  5827  5922 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
12-17 18:26:46.768  5827  5922 E AndroidRuntime: Process: host.exp.exponent, PID: 5827
12-17 18:26:46.768  5827  5922 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:60)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at abi43_0_0.expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:7)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at abi43_0_0.expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:1)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-17 18:26:46.768  5827  5922 E AndroidRuntime: 	... 4 more
12-17 18:26:46.771  1634  2019 W ActivityManager:   Force finishing activity host.exp.exponent/.experience.ExperienceActivity
12-17 18:26:46.775  1361  1670 D AudioFlinger: mixer(0xb4300000) throttle end: throttle time(3)
```

**Comment by giautm** [comment]
Hey @byCedric, Look like expo-camera doesn't handle correctly `mImageData` when if null (e.g: running on emulator). So It causes Expo Go to crash.

**Comment by giautm** [comment]
Not stale

**Comment by douglasjunior** [comment]
Same here, we are seeing this error on crashlytics.

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Caused by java.lang.NullPointerException: Attempt to get length of null array
       at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
       at expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:95)
       at expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:27)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

OkHttp dev-plaenge-afd-sa.azurefd.net
       at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
       at okio.InputStreamSource.read(JvmOkio.kt:91)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
       at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
       at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

Our code:

```tsx
      <ExpoCamera
        ref={cameraRef}
        autoFocus="on"
        ratio="16:9"
        style={cameraStyle}
        type={ExpoCamera.Constants.Type.back}
      />
```

Then:

```ts
   const picture = await cameraRef.current.takePictureAsync();
```

Versions:

- React Native 0.66.4
- Expo 43.0.2
- Expo Camera 12.0.3

**Comment by douglasjunior** [comment]
Same here, we are seeing this error on crashlytics.

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Caused by java.lang.NullPointerException: Attempt to get length of null array
       at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
       at expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:95)
       at expo.modules.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:27)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

```

Our code:

```tsx
      <ExpoCamera
        ref={cameraRef}
        autoFocus="on"
        ratio="16:9"
        style={cameraStyle}
        type={ExpoCamera.Constants.Type.back}
      />
```

Then:

```ts
   const picture = await cameraRef.current.takePictureAsync();
```

Versions:

- React Native 0.66.4
- Expo 43.0.2
- Expo Camera 12.0.3

**Comment by karthikkncs14** [comment]
PermissionsAndroid from react-native then it will not crash but lot of other error comes with PermissionsAndroid
