### ISSUE TITLE
[expo-calendar] Getting a "Cannot have both DTEND and DURATION in an event" crash when updating a recurring event

### ISSUE THREAD

**Issue by abdullah-kasim** [expo/expo#13658]
### Summary

When updating a recurring event for all future events, I'm getting a `Cannot have both DTEND and DURATION in an event` exception on an app using `unimodules`.

I'm guessing this is happening because there's already a DURATION field in the recurring event that's about to be updated, and adding an `endDate` in `details` broke it when trying to update it. I could always take out the `endDate` (which I tried, and works perfectly) but I'm not sure if that's ideal - I don't think I'll be able to edit the event length for all occurrence if I do that.

In this part of `saveEvent`, around line 719 onwards in `CalendarModule.java`, adding the lines to set a duration and remove DTSTART and DTEND so that those doesn't get updated, seems to work. I copy-pasted some of this part from the code in line 666 to 675 with a few adjustments.  Not fully tested though.

```java
if (details.containsKey("id")) {
      int eventID = Integer.parseInt(details.getString("id"));
      Uri updateUri = ContentUris.withAppendedId(CalendarContract.Events.CONTENT_URI, eventID);

      Long eventStartDate = eventValues.getAsLong(CalendarContract.Events.DTSTART);
      Long eventEndDate = eventValues.getAsLong(CalendarContract.Events.DTEND);
      String rrule = eventValues.getAsString(CalendarContract.Events.RRULE);

      // reference: https://developer.android.com/guide/topics/providers/calendar-provider.html#add-event
      // It's referring to add event, but I guess it applies to updating events too
      if (eventStartDate != null && eventEndDate != null && rrule != null) {
        long duration = (eventEndDate - eventStartDate) / 1000;

        // don't update DTSTART in this case
        eventValues.remove(CalendarContract.Events.DTSTART);
        eventValues.putNull(CalendarContract.Events.LAST_DATE);

        // don't update DTEND either
        eventValues.remove(CalendarContract.Events.DTEND);

        eventValues.put(CalendarContract.Events.DURATION, String.format("PT%dS", duration));
      }

      cr.update(updateUri, eventValues, null, null);

      removeRemindersForEvent(cr, eventID);
      if (details.containsKey("alarms")) {
        createRemindersForEvent(cr, eventID, details.getList("alarms"));
      }
      return eventID;
    }
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.9 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

The following was tested on `expo-calendar: 9.2.2`

1. Get an existing recurring event to update.
2. Update it using the following payload:
```ts
// get an existing event from somewhere... this was the event that I tried to update
const existingRecurringEvent = {
  "calendarId": "6",
  "instanceId": "155",
  "endTimeZone": "Asia/Kuala_Lumpur",
  "title": "Recurring every 2 months",
  "notes": "Event",
  "id": "271",
  "alarms": [],
  "accessLevel": "default",
  "allDay": false,
  "guestsCanSeeGuests": true,
  "availability": "busy",
  "endDate": "2021-07-11T10:00:00.000Z",
  "organizerEmail": "test@example.com",
  "originalId": null,
  "location": "",
  "guestsCanModify": false,
  "recurrenceRule": {
    "frequency": "monthly"
  },
  "timeZone": "Asia/Kuala_Lumpur",
  "guestsCanInviteOthers": true,
  "startDate": "2021-07-11T09:00:00.000Z"
}

const details = {
  "startDate": "2021-07-11T09:00:00.000Z",
  "endDate": "2021-07-11T10:00:00.000Z", // removing this field allows the update to succeed
  "notes": "Event",
  "title": "Recurring every 2 months",
  "location": "",
  "alarms": [
    {
      "relativeOffset": 0
    }
  ],
  "allDay": false,
  "url": "",
  "timeZone": "Europe/Astrakhan",
  "organizerEmail": "test@example.com",
  "recurrenceRule": {
    "frequency": "monthly",
    "interval": 2,
    "occurrence": 10
  },
  "calendarId": "6"
}

await Calendar.updateEventAsync(existingRecurringEvent.id, details), { futureEvents: true })
```

The app will crash, and logcat will then product the following.

```
2021-07-16 22:17:57.180 27614-27629/com.myapp W/System: A resource failed to call close. 
2021-07-16 22:17:57.184 27614-27629/com.myapp I/chatty: uid=10265(com.myapp) FinalizerDaemon identical 19 lines
2021-07-16 22:17:57.184 27614-27629/com.myapp W/System: A resource failed to call close. 
2021-07-16 22:17:58.338 27614-27660/com.myapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.myapp, PID: 27614
    java.lang.IllegalArgumentException: Cannot have both DTEND and DURATION in an event
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.update(ContentProviderNative.java:578)
        at android.content.ContentResolver.update(ContentResolver.java:1993)
        at expo.modules.calendar.CalendarModule.saveEvent(CalendarModule.java:722)
        at expo.modules.calendar.CalendarModule.access$500(CalendarModule.java:35)
        at expo.modules.calendar.CalendarModule$6.run(CalendarModule.java:162)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by abdullah-kasim** [comment]
This needs more work, as I'm still able to get crashes with the code above.

It misses some scenarios where both DURATION and DTEND is appearing, it seems.

I should probably just check if we have both DTEND and DURATION, and get rid of one of them if both exists, rather than try to tackle only a small subset of the issue.
