### ISSUE TITLE
getExpoPushTokenAsync() hangs forever

### ISSUE THREAD

**Issue by jvgeee** [expo/expo#13679]
### Summary

I'm using Expo Go on a physical Android device. 

I've set up push notifications as per [the docs](https://docs.expo.io/push-notifications/push-notifications-setup/), to no avail (see code below). I've also tried:

- Setting up a Firebase project 
- Added a `google-services.json` with my FCM credentials and referenced it in my app.json
- Tried every other random suggestion I've seen here, including making my app name lowercase in app.json 
- Have added `expo-firebase` on the offchance it's needed

None of this has changed...anything. 

I'm just using the stock code straight from the docs, set up in a useEffect hook in my main app file (as per the docs).

**Possible clue: I've never once been prompted to give push notification permission on my device** (I've uninstalled/reinstalled Expo Go to test). With that said, if I log out `await Notifications.requestPermissionsAsync()`, I always get:

```
{
  "android": Object {
    "importance": -1000,
    "interruptionFilter": 1,
  },
  "canAskAgain": true,
  "expires": "never",
  "granted": true,
  "status": "granted",
}
```

Any ideas? 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

 Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
      npm: 7.17.0 - ~/.nvm/versions/node/v14.15.5/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.71 => 0.12.78
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: ^17.0.2 => 17.0.2
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ^0.16.3 => 0.16.5
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
export async function registerForPushNotificationsAsync() {
  let token

  if (Constants.isDevice) {
   
    // This works fine, existing status is "granted". However, I never saw a push notification prompt on my device
   const { status: existingStatus } = await Notifications.getPermissionsAsync();

    let finalStatus = existingStatus
    if (existingStatus !== "granted") {
      const { status } = await Notifications.requestPermissionsAsync()
      finalStatus = status
    }
    if (finalStatus !== "granted") {
      alert("Failed to get push token for push notification!")
      console.log("Failed")
      return
    }
    try {
      // We always successfully get to here
      console.log("FINAL STATUS", finalStatus)
      const tokenObject = await Notifications.getExpoPushTokenAsync())
      token = tokenObject.data
      // We never reach here - No token ever prints
      console.log("TOKEN", { token })
    } catch (e) {
      // No error ever found
      console.error("Error", e)
    }
  } else {
    alert("Must use physical device for Push Notifications")
  }

  return token
}

```

**Comment by cruzach** [comment]
Are you using the most recent version of Expo Go from the play store?

**Comment by jvgeee** [comment]
@cruzach Yes, I uninstalled => reinstalled it to be sure

**Comment by cruzach** [comment]
Okay, please check the logs with 'and logcat' then, that may contain a useful error

**Comment by jvgeee** [comment]
@cruzach Hard to pinpoint exactly where to look in the logs (constantly moving!) but I think this might be it?

```
07-20 09:36:42.556  6731  6779 E nightwatch-target: lmkd signal waiters
07-20 09:36:42.589 22556 23400 I ReactNativeJS: 'RN Permission Status:', { android: { importance: -1000, interruptionFilter: 1 },
07-20 09:36:42.589 22556 23400 I ReactNativeJS:   status: 'granted',
07-20 09:36:42.589 22556 23400 I ReactNativeJS:   canAskAgain: true,
07-20 09:36:42.589 22556 23400 I ReactNativeJS:   granted: true,
07-20 09:36:42.589 22556 23400 I ReactNativeJS:   expires: 'never' }
07-20 09:36:42.612   723 23422 E ResolverController: No valid NAT64 prefix (615, <unspecified>/0)
07-20 09:36:42.621   723 23424 E ResolverController: No valid NAT64 prefix (615, <unspecified>/0)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:1)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:1)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:7)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:1)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:4)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:4)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:2)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:7)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-20 09:36:42.637 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:919)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:1)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:1)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:7)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:1)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:4)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:4)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:2)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:7)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-20 09:36:42.637 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:919)
07-20 09:36:42.638 22556 22777 I chatty  : uid=10380(host.exp.exponent) 1.107:19000/... identical 1 line
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:1)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:1)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:7)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:1)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:4)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:4)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:2)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:7)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-20 09:36:42.638 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:919)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:1)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:1)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:7)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:1)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:4)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:4)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:2)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:7)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:919)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:1)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:1)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:7)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:1)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:4)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:4)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:2)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:7)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-20 09:36:42.638 22556 22834 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:919)
07-20 09:36:42.935 22556 22556 I ReactNative: [GESTURE HANDLER] Gesture handler is already enabled for a parent view
07-20 09:36:42.936 22556 22556 I ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view abi41_0_0.host.exp.exponent.ReactUnthemedRootView{d407ec2 V.E...... ......ID 0,0-1080,2200 #29}
```

**Comment by jvgeee** [comment]
Simplifying my code and implementation:

App.tsx:

```
import { usePushNotifications } from "./utils/push-notifications"

export function App() {
  const { expoPushToken, notification } = usePushNotifications()

  console.log("In App", { expoPushToken, notification })

 // Other app stuff here, navigation etc
```

push-notifications.tsx:

```
import { useState, useEffect } from "react"
import * as Notifications from "expo-notifications"

import { useStores } from "../models"

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
})

export function usePushNotifications() {
  const [expoPushToken, setExpoPushToken] = useState("")
  const [notification, setNotification] = useState(null)

  const { userStore } = useStores()

  useEffect(() => {
    ;(async () => {
      console.log("In UseEffect Function")
      const token = await registerForPushNotificationsAsync()
      console.log("TOKEN!!!", token)
      setExpoPushToken(token)
      userStore.saveUser({ pushToken: token })
    })()
  }, [])

  return {
    expoPushToken,
    notification,
  }
}

export async function registerForPushNotificationsAsync() {
  console.log("Getting Token")
  const tokenObj = await Notifications.getExpoPushTokenAsync()
  console.log("TOKENOBJ", tokenObj)
  const token = tokenObj.data

  return token
}
```


ADB Logs:

```
07-20 09:57:30.119 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: Release
07-20 09:57:30.120 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: InboundFilters
07-20 09:57:30.120 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: FunctionToString
07-20 09:57:30.121 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: Breadcrumbs
07-20 09:57:30.122 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: LinkedErrors
07-20 09:57:30.122 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: UserAgent
07-20 09:57:30.123 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: DebugSymbolicator
07-20 09:57:30.124 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
07-20 09:57:30.126 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: ExpoManagedIntegration
07-20 09:57:30.126 22556 25317 I ReactNativeJS: Sentry Logger [Log]: Integration installed: RewriteFrames
07-20 09:57:30.131  6731  6779 E nightwatch-target: lmkd signal waiters
07-20 09:57:30.143 22556 25317 E ReactNativeJNI: logMarker RUN_JS_BUNDLE_END
07-20 09:57:30.148 22556 25317 I ReactNativeJS: Running "main" with {"initialProps":{"exp": 

// my app.json is stringified here

07-20 09:57:30.171 22556 25317 I ReactNativeJS: 'In App', { expoPushToken: '', notification: null }
07-20 09:57:30.187 22556 25317 I ReactNativeJS: In UseEffect Function
07-20 09:57:30.187 22556 25317 I ReactNativeJS: Getting Token
07-20 09:57:30.226 22556 25317 I ReactNativeJS: 'In App', { expoPushToken: '', notification: null }
07-20 09:57:30.236 22556 22556 E SensorManager: unregisterListenerImpl callingApp: host.exp.exponent,callingPid:22556,callingUid:10380
07-20 09:57:30.237   814   814 I sensors-hal: activate:150, android.sensor.gyroscope/38 en=0
07-20 09:57:30.240   814   814 I sensors-hal: activate:161, android.sensor.gyroscope/38 en=0 completed
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:1)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:1)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at abi41_0_0.com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:7)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:1)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:4)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:4)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:2)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:7)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-20 09:57:30.250 22556 22777 E unknown:ReactContextBaseJavaModule: 	at java.lang.Thread.run(Thread.java:919)

// This error repeats a lot of times

07-20 09:57:30.261   723 25343 E ResolverController: No valid NAT64 prefix (615, <unspecified>/0)
07-20 09:57:30.261   723 25345 E ResolverController: No valid NAT64 prefix (615, <unspecified>/0)
07-20 09:57:30.270 22556 25317 I ReactNativeJS: 'In App', { expoPushToken: '', notification: null }
```

**Comment by cruzach** [comment]
So `console.log("TOKEN!!!", token)` is never run, according to your logs?

**Comment by jvgeee** [comment]
Nope, it never runs. Neither does ` console.log("TOKENOBJ", tokenObj)`

Evidently, it's hanging at `await Notifications.getExpoPushTokenAsync()` and never resolving or erroring.

**Comment by cruzach** [comment]
Can you use the code from the example snack in the docs instead of your code? 

```
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import React, { useState, useEffect, useRef } from 'react';
import { Text, View, Button, Platform } from 'react-native';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [expoPushToken, setExpoPushToken] = useState('');
  const [notification, setNotification] = useState(false);
  const notificationListener = useRef();
  const responseListener = useRef();

  useEffect(() => {
    registerForPushNotificationsAsync().then(token => setExpoPushToken(token));

    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });

    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener.current);
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <Text>Your expo push token: {expoPushToken}</Text>
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
      <Button
        title="Press to schedule a notification"
        onPress={async () => {
          await schedulePushNotification();
        }}
      />
    </View>
  );
}

async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail! 📬",
      body: 'Here is the notification body',
      data: { data: 'goes here' },
    },
    trigger: { seconds: 2 },
  });
}

async function registerForPushNotificationsAsync() {
  let token;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return token;
}

```

**Comment by jvgeee** [comment]
Yep, tried that too and same results.

**Comment by jvgeee** [comment]
Actually, scratch that @cruzach  - when I replace my entire app with this, then it works!

I suppose it's an error in the way I've implemented it though, although it's not directly clear.

So for clarity: If I use the example code, then it works fine.

If I put the code in a custom hook, it no longer works. 

Seems like the potential answer is that I've not implemented the hook correctly? (see push-notification.tsx above)

**Comment by jvgeee** [comment]
Final update: Frustratingly, this magically started working and I'm not exactly clear why. Major apologies to anyone in future who googles and stumbles upon this looking for an answer!

**Comment by peter571** [comment]
I was getting similar problems on android where the function getExpoPushTokenAsync() hangs forever. 
After configuring a new Google Service Account Key in app.json for sending Android Notifications it worked. 

Docs to create the Google Service Account Key: https://docs.expo.dev/push-notifications/fcm-credentials
