### ISSUE TITLE
[Android] Custom Dev Client menu binds to all keyboard shortcuts when open

### ISSUE THREAD

**Issue by jakobo** [expo/expo#13731]
### Summary

When working in a TextInput component, a lowercase "L" immediately shuts down the custom dev client. This also does not happen in iOS builds.

https://user-images.githubusercontent.com/1795/126563385-d6fecdc6-d82b-4e0c-b9ea-102eeabf5c9f.mov

**Former Title**
`[Android] Lowercase "L" in text area crashes custom development client`

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

```
    "expo": "^42.0.0",
    "expo-app-loading": "~1.0.3",
    "expo-constants": "~11.0.1",
    "expo-dev-client": "^0.4.3",
    "expo-status-bar": "~1.0.4",
    "react-native": "0.63.4",
```

### Environment

```
  Expo CLI 4.8.1 environment info:
    System:
      OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.8.0 - ~/.asdf/installs/nodejs/14.8.0/bin/node
      Yarn: 2.4.0 - ~/.asdf/installs/nodejs/14.8.0/.npm/bin/yarn
      npm: 6.14.11 - ~/.asdf/installs/nodejs/14.8.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 26
        Build Tools: 26.0.3
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I was able to reproduce with a minimal example

```js
import React from "react";
import { View, TextInput, Text } from "react-native";
import { useToast } from "react-native-fast-toast";

export default function Login() {
  return (
    <View
      style={{
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        marginTop: 150,
      }}
    >
      <TextInput
        style={{
          backgroundColor: "#cccccc",
        }}
      />
    </View>
  );
}
```

**app.json**
```json
{
  "name": "Demo",
  "displayName": "Demoapp",
  "expo": {
    "name": "Demo",
    "slug": "Demo",
    "owner": "aibex",
    "scheme": "aibex",
    "version": "1.0.0",
    "orientation": "portrait",
    "platforms": ["ios", "android"],
    "icon": "./assets/icon.png",
    "backgroundColor": "#191919",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#191919"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "app.supertak.core",
      "infoPlist": {
        "NSContactsUsageDescription": "Allow Demo to read and write to your contacts"
      }
    },
    "android": {
      "package": "app.demo-aibex.core",
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/icon.png",
        "backgroundColor": "#191919"
      },
      "versionCode": 1,
      "useNextNotificationsApi": true,
      "permissions": ["READ_CONTACTS", "WRITE_CONTACTS"]
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "BUNDLE_IDENTIFIER": "app.demo-aibex.core",
      "ENV": "production",
      "APP_JSON_VERSION": "1.0.0"
    }
  }
}
```

### Stacktrace (if a crash is involved)
**edit** Was able to pull the stack from the Android Emulator's bug report screen. It appears that the `DevMenuManager` is accepting key presses when it's in the closed state.

```
07-21 15:43:06.322   537   662 D InputDispatcher: Waiting to send key to Window{6ad555e u0 app.supertak.core/app.supertak.core.MainActivity} because there are unprocessed events that may cause focus to change
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: ReactInstanceManager.destroy called
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: java.lang.RuntimeException: ReactInstanceManager.destroy called
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at com.facebook.react.ReactInstanceManager.logOnDestroy(ReactInstanceManager.java:656)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at com.facebook.react.ReactInstanceManager.destroy(ReactInstanceManager.java:669)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at com.facebook.react.ReactNativeHost.clear(ReactNativeHost.java:59)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.DevLauncherController.clearHost(DevLauncherController.kt:219)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.DevLauncherController.access$clearHost(DevLauncherController.kt:44)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.DevLauncherController$ensureHostWasCleared$1.invoke(DevLauncherController.kt:195)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.DevLauncherController$ensureHostWasCleared$1.invoke(DevLauncherController.kt:44)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.helpers.DevLauncherCoroutinesExtensionsKt.runBlockingOnMainThread(DevLauncherCoroutinesExtensions.kt:10)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.DevLauncherController.ensureHostWasCleared(DevLauncherController.kt:194)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.DevLauncherController.ensureHostWasCleared$default(DevLauncherController.kt:192)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.DevLauncherController.navigateToLauncher(DevLauncherController.kt:151)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.modules.DevLauncherDevMenuExtensions$devMenuItems$1$1.invoke(DevLauncherDevMenuExtensions.kt:30)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devlauncher.modules.DevLauncherDevMenuExtensions$devMenuItems$1$1.invoke(DevLauncherDevMenuExtensions.kt:15)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devmenu.DevMenuManager.onKeyEvent(DevMenuManager.kt:344)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at expo.modules.devmenu.react.DevMenuAwareReactActivity.onKeyUp(DevMenuAwareReactActivity.kt:29)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.KeyEvent.dispatch(KeyEvent.java:2866)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.app.Activity.dispatchKeyEvent(Activity.java:4090)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5947)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5815)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5518)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5676)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3179)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2721)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2712)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3156)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.os.MessageQueue.next(MessageQueue.java:335)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.os.Looper.loop(Looper.java:183)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-21 15:43:06.346  6660  6660 E unknown:ReactInstanceManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-21 15:43:06.353   537   857 I ActivityTaskManager: START u0 {flg=0x10018000 cmp=app.supertak.core/expo.modules.devlauncher.launcher.DevLauncherActivity} from uid 10153
```

**Comment by tcdavis** [comment]
Thanks for reporting! From our own investigation:
on first boot after expo run:android, r doesn’t work. but if you press l and then choose the app, then r does work and l (lowercase L) doesn’t do anything (as expected)
