### ISSUE TITLE
Could not reach Cloud Firestore backend on Custom Development Client

### ISSUE THREAD

**Issue by gaishimo** [expo/expo#13808]
### Summary

I get an error when I try to access Firebase Firestore by firebase JS SDK in Custom Development Client. This may not be a problem with expo, but I did not have this problem when I ran the same app on Expo Go.

```
[2021-07-28T00:35:18.325Z]  @firebase/firestore:, Firestore (8.2.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
at http://35.213.16.172:19000/index.bundle?platform=android&dev=true&minify=false:198884:27 in defaultLogHandler
at node_modules/@firebase/component/dist/index.esm.js:112:17 in Provider.prototype.getImmediate
at node_modules/@firebase/webchannel-wrapper/dist/index.js:38:38 in H
at node_modules/@firebase/firestore/dist/rn/prebuilt.rn-f9cd27ba.js:6054:0 in ar
at node_modules/@firebase/firestore/dist/rn/prebuilt.rn-f9cd27ba.js:6073:16 in ar#constructor
at http://35.213.16.172:19000/index.bundle?platform=android&dev=true&minify=false:234807:74 in <unknown>
at node_modules/@firebase/firestore/dist/rn/prebuilt.rn-f9cd27ba.js:10172:17 in Oc#r_
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue

Failed to get document because the client is offline.
at [native code]:null in construct
at [native code]:null in construct
at http://35.213.16.172:19000/index.bundle?platform=android&dev=true&minify=false:229611:321 in _createSuperInternal
at node_modules/@firebase/webchannel-wrapper/dist/index.js:42:603 in <anonymous>
at node_modules/@firebase/firestore/dist/rn/prebuilt.rn-f9cd27ba.js:9869:0 in <anonymous>
at node_modules/@firebase/firestore/dist/rn/prebuilt.rn-f9cd27ba.js:8394:4 in so#set
at [native code]:null in callFunctionReturnFlushedQueue
```

It occurs only on android. it doesn't occur on ios.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

- expo-dev-client: 0.4.5
- expo-updates: 0.8.2
- firebase: 8.2.3

### Environment

```
  Expo CLI 4.8.1 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nodebrew/current/bin/node
      Yarn: 2.4.0 - ~/.nodebrew/current/bin/yarn
      npm: 7.12.1 - ~/.nodebrew/current/bin/npm
      Watchman: 20210124.162314.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```
import firebase from "firebase/app"
import "firebase/firestore"

if (firebase.apps.length === 0) {
  firebase.initializeApp({ /* firebase configs */ })
}

const app = firebase.app()

const db = app.firestore()
;(async () => {
  try {
    await db.collection("appInfo").get()
  } catch (err) {
    console.error(err)
  }
})()
```

**Comment by tcdavis** [comment]
I believe this is a firebase issue. I was able to resolve it by calling `firebase.firestore().settings({ experimentalForceLongPolling: true, merge: true });` after initializing the app.

You should be able to use [react-native-firebase instead of the JS module](https://github.com/invertase/react-native-firebase/pull/5548) before too long.

**Comment by gaishimo** [comment]
@tcdavis  Thanks! I solved this error by adding the option `experimentalForceLongPolling: true`.

I'm a little curious why Expo Go Client doesn't have this problem without this option 💭
