### ISSUE TITLE
Unhandled Promise Rejection in AuthSession Google Provider

### ISSUE THREAD

**Issue by timbremer** [expo/expo#13885]
### Summary

Trying to get a refreshToken from Google, I'm stuck with the following GoogleAuthRequestConfig:

```
const [request, response, promptAsync] = Google.useAuthRequest({
    expoClientId:
      "XXX.apps.googleusercontent.com",
    iosClientId:
      "XXXapps.googleusercontent.com",
    androidClientId: "GOOGLE_GUID.apps.googleusercontent.com",
    webClientId: "GOOGLE_GUID.apps.googleusercontent.com",
    scopes: ["https://www.googleapis.com/auth/contacts"],
    prompt: Prompt.Consent,
    responseType: ResponseType.Code,
    extraParams: {
      access_type: "offline",
    },
  });
```

I expected to get back an object containing a refreshToken or at least a response, but instead there seems to be an unhandled promise rejection:

```
[Unhandled promise rejection: Error: The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed.]
at [native code]:null in construct
at [native code]:null in construct
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:106569:321 in _createSuperInternal
at node_modules/@unimodules/react-native-adapter/build/errors/CodedError.js:8:8 in constructor
at [native code]:null in construct
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:160091:321 in _createSuperInternal
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:160146:25 in ResponseError
at [native code]:null in construct
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:160091:321 in _createSuperInternal
at node_modules/expo-auth-session/build/Errors.js:70:26 in TokenError#constructor
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:164486:44 in performAsync$
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

Any further guidance on how to get a refreshToken from Google would be greatly appreciated :)

Thank you!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.1 - ~/.nvm/versions/node/v15.5.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.5.1/bin/yarn
      npm: 7.20.1 - ~/.nvm/versions/node/v15.5.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

- Create a blank project
- Google OAuth ClientIDs will be needed to reproduce
- Snack here: https://snack.expo.dev/@timbremer/google-oauth (keep in mind that this code will not work as-is)
- Try to sign in and approve the consent prompt

**Comment by davidmetcal** [comment]
Hi,

Any update on this? I've also been able to use this method for getting responseType: 'id_token' but when I try and instigate code I am getting the same error. Here is my request:



```
	const [request, response, promptAsync] = Google.useAuthRequest({
		responseType: 'code',
		expoClientId:
			MY_EXPO_CLINT_ID
		iosClientId:
			IOS_CLIENT
		androidClientId:
			ANDROID_CLIENT
		webClientId:
			WEB_CLIENT

		prompt: Prompt.Consent,
	});
```

And the error is:

```
[Unhandled promise rejection: Error: The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed.]
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:110650:321 in _createSuperInternal
at node_modules/expo-modules-core/build/errors/CodedError.js:10:8 in constructor
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:185526:321 in _createSuperInternal
at node_modules/expo-auth-session/build/Errors.js:66:8 in ResponseError#constructor
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:185526:321 in _createSuperInternal
at node_modules/expo-auth-session/build/Errors.js:89:26 in TokenError#constructor
at node_modules/expo-auth-session/build/TokenRequest.js:169:18 in performAsync
```

**Comment by gabeking** [comment]
I am also experiencing a similar issue; see [SO Question](https://stackoverflow.com/questions/71983030/is-it-possible-to-obtain-an-access-token-with-expo-auth-session-providers-google )
