### ISSUE TITLE
Calendar.getCalendarsAsync error on Android

### ISSUE THREAD

**Issue by xcarpentier** [expo/expo#1390]
### Environment
  OS: macOS Sierra 10.12.5
  Node: 8.7.0
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: 4.7.0
  Xcode: Xcode 8.3.3 Build version 8E3004b
  Android Studio: 2.1 AI-143.2821654
  Device: Android v5, Aquaris E5, on Expo client

### Steps to Reproduce

Call `Calendar.getCalendarsAsync()`

### Expected Behavior

List calendars.

### Actual Behavior
Exception: 
```E/AndroidRuntime(22910): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime(22910): Process: host.exp.exponent, PID: 22910
E/AndroidRuntime(22910): java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime(22910):        at android.database.CursorWindow.nativeGetString(Native Method)
E/AndroidRuntime(22910):        at android.database.CursorWindow.getString(CursorWindow.java:438)
E/AndroidRuntime(22910):        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
E/AndroidRuntime(22910):        at android.database.CursorWrapper.getString(CursorWrapper.java:114)
E/AndroidRuntime(22910):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendar(CalendarModule.java:1301)
E/AndroidRuntime(22910):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendars(CalendarModule.java:1287)
E/AndroidRuntime(22910):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.findCalendars(CalendarModule.java:273)
E/AndroidRuntime(22910):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.access$000(CalendarModule.java:36)
E/AndroidRuntime(22910):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule$1.run(CalendarModule.java:61)
E/AndroidRuntime(22910):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(22910):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(22910):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(22910):        at java.lang.Thread.run(Thread.java:818)
```

**Comment by xcarpentier** [comment]
Sorry I missed permissions:
`const response = await Permissions.askAsync('calendar')`

**Comment by xcarpentier** [comment]
Actually I test *Expo APIs* app on expo client with the same android device and I have the issue. So I reopen it.

I joined a new stack trace with some line before and after:

```
I/ActivityManager(  710): Start proc 16161:com.android.providers.calendar/u0a1 for content provider com.android.providers.calendar/.CalendarProvider2
I/CalendarProvider2(16161): Created com.android.providers.calendar.CalendarAlarmManager@19a3d339(com.android.providers.calendar.CalendarProvider2@2c327d7e)
E/CursorWindow(15424): Failed to read row 0, column -1 from a CursorWindow which has 8 rows, 15 columns.
E/AndroidRuntime(15424): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(15424): Process: host.exp.exponent, PID: 15424
E/AndroidRuntime(15424): java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime(15424):        at android.database.CursorWindow.nativeGetString(Native Method)
E/AndroidRuntime(15424):        at android.database.CursorWindow.getString(CursorWindow.java:438)
E/AndroidRuntime(15424):        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
E/AndroidRuntime(15424):        at android.database.CursorWrapper.getString(CursorWrapper.java:114)
E/AndroidRuntime(15424):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendar(CalendarModule.java:1301)
E/AndroidRuntime(15424):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendars(CalendarModule.java:1287)
E/AndroidRuntime(15424):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.findCalendars(CalendarModule.java:273)
E/AndroidRuntime(15424):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule.access$000(CalendarModule.java:36)
E/AndroidRuntime(15424):        at abi25_0_0.host.exp.exponent.modules.api.CalendarModule$1.run(CalendarModule.java:61)
E/AndroidRuntime(15424):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(15424):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(15424):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(15424):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  710):   Force finishing activity 1 host.exp.exponent/.experience.ExperienceActivity
host.exp.exponent/10176/u0 remote:2d430422}: process crashing
I/CalendarProvider2(16161): Sending notification intent: Intent { act=android.intent.action.PROVIDER_CHANGED dat=content://com.android.calendar }
W/ContentResolver(16161): Failed to get type for: content://com.android.calendar (Unknown URL content://com.android.calendar)
I/IcingInternalCorpora( 8437): Received calendar change notification.
I/ActivityManager(  710): Start proc 16192:com.google.android.calendar/u0a29 for broadcast com.google.android.calendar/.alerts.AlertReceiver
```

**Comment by esamelson** [comment]
thanks for reporting, I'm looking into this. Will likely have a fix in SDK 26.

**Comment by esamelson** [comment]
closed bc a fix will be coming in SDK 26. Feel free to reopen if you see this issue again after SDK 26 comes out.
