### ISSUE TITLE
Error loading assets/fonts after GraphQL Mutation

### ISSUE THREAD

**Issue by arrygoo** [expo/expo#1453]
### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/arrygoo-5db7c6de-d171-47f3-930f-d70731423bf7.tar.gz

ios expo app.
### Steps to Reproduce
I have a strange issue that I'm not sure how to narrow down. I have a Graphcool expo app that uses Native-base for UI. I have a mutation in Graphcool that works fine the first time, but after the second time that I run it, I get the following error:

![screen shot 2018-02-20 at 7 55 34 pm](https://user-images.githubusercontent.com/965429/36457451-0f1bcbdc-1678-11e8-9e51-668d683a81a7.png)

When I click on the url of the error, I get the following error:
```
{
"type": "TransformError",
"lineNumber": 0,
"errors": [
{
"description": "/Users/aryan/dev/baobab/mobile/assets/images/robot-dev.png: Cannot find module '/Users/aryan/dev/baobab/mobile/node_modules/expo/tools/hashAssetFiles:168584:47'",
"lineNumber": 0
}
],
"name": "SyntaxError",
"message": "/Users/aryan/dev/baobab/mobile/assets/images/robot-dev.png: Cannot find module '/Users/aryan/dev/baobab/mobile/node_modules/expo/tools/hashAssetFiles:168584:47'",
"stack": "Error: Cannot find module '/Users/aryan/dev/baobab/mobile/node_modules/expo/tools/hashAssetFiles:168584:47'\n    at Function.Module._resolveFilename (module.js:555:15)\n    at Function.Module._load (module.js:482:25)\n    at Module.require (module.js:604:17)\n    at require (internal/module.js:11:18)\n    at /Users/aryan/dev/baobab/mobile/node_modules/metro/src/Assets/index.js:281:33\n    at Generator.next (<anonymous>)\n    at step (/Users/aryan/dev/baobab/mobile/node_modules/metro/src/Assets/index.js:329:347)\n    at /Users/aryan/dev/baobab/mobile/node_modules/metro/src/Assets/index.js:329:577\n    at new Promise (<anonymous>)"
}
```
^ There's also similar errors about the fonts tham I'm loading like:
```
{
"type": "TransformError",
"lineNumber": 0,
"errors": [
{
"description": "/Users/aryan/dev/baobab/mobile/node_modules/@expo/vector-icons/fonts/Entypo.ttf: Cannot find module '/Users/aryan/dev/baobab/mobile/node_modules/expo/tools/hashAssetFiles:13694:16'",
"lineNumber": 0
}
],
"name": "SyntaxError",
"message": "/Users/aryan/dev/baobab/mobile/node_modules/@expo/vector-icons/fonts/Entypo.ttf: Cannot find module '/Users/aryan/dev/baobab/mobile/node_modules/expo/tools/hashAssetFiles:13694:16'",
"stack": "Error: Cannot find module '/Users/aryan/dev/baobab/mobile/node_modules/expo/tools/hashAssetFiles:13694:16'\n    at Function.Module._resolveFilename (module.js:555:15)\n    at Function.Module._load (module.js:482:25)\n    at Module.require (module.js:604:17)\n    at require (internal/module.js:11:18)\n    at /Users/aryan/dev/baobab/mobile/node_modules/metro/src/Assets/index.js:281:33\n    at Generator.next (<anonymous>)\n    at step (/Users/aryan/dev/baobab/mobile/node_modules/metro/src/Assets/index.js:329:347)\n    at /Users/aryan/dev/baobab/mobile/node_modules/metro/src/Assets/index.js:329:577\n    at new Promise (<anonymous>)"
}
```

Here's how my App.js handles the loading:
```
import React from 'react';
import { Platform, StatusBar, StyleSheet, View } from 'react-native';
import { AppLoading, Asset, Font } from 'expo';
import { Ionicons } from '@expo/vector-icons';
import RootNavigation from './navigation/RootNavigation';

export default class App extends React.Component {
  state = {
    isLoadingComplete: false
  };

  render() {
    if (!this.state.isLoadingComplete && !this.props.skipLoadingScreen) {
      return (
        <AppLoading
          startAsync={this._loadResourcesAsync}
          onError={this._handleLoadingError}
          onFinish={this._handleFinishLoading}
        />
      );
    } else {
      return (
        <View style={styles.container}>
          {Platform.OS === 'ios' && <StatusBar barStyle="default" />}
          {Platform.OS === 'android' && (
            <View style={styles.statusBarUnderlay} />
          )}
          <RootNavigation />
        </View>
      );
    }
  }

  _loadResourcesAsync = async () => {
    return Promise.all([
      Asset.loadAsync([
        require('./assets/images/robot-dev.png'),
        require('./assets/images/robot-prod.png')
      ]),
      Font.loadAsync({
        'space-mono': require('./assets/fonts/SpaceMono-Regular.ttf'),
        Roboto: require('native-base/Fonts/Roboto.ttf'),
        Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf')
      })
    ]);
  };

  _handleLoadingError = error => {
    // In this case, you might want to report the error to your error
    // reporting service, for example Sentry
    console.warn(error);
  };

  _handleFinishLoading = () => {
    this.setState({ isLoadingComplete: true });
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff'
  },
  statusBarUnderlay: {
    height: 24,
    backgroundColor: 'rgba(0,0,0,0.2)'
  }
});
```

Note that this error does not show up when the app first loads up. I'm not sure why it only shows up after the 2nd mutation. The response from the mutation (and the value in the database) shows that it ran successfully.

I'm asking for pointers to narrow down the error. Here's how I'm catching errors in my app:

```
const errorLink = onError(({ networkError, graphQLErrors }) => {
  if (graphQLErrors) {
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${JSON.stringify(
          locations,
        )}, Path: ${path}`,
      ),
    );
  }
  if (networkError) {
    if (networkError.status === 401) {
      console.log('Logging out', networkError);
    }
    console.log(`[Network error]: ${networkError}`);
  }
});

const httpLink = new HttpLink({
  uri: 'https://api.graph.cool/simple/v1/......',
});


const withToken = setContext(async (_, { headers }) => {
  // if you have a cached value, return it immediately
  // if (token) return { token };
  const token = await SecureStore.getItemAsync('TOKEN_KEY');
  console.log('setting context', token);
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
    },
  };
});

const link = ApolloLink.from([errorLink, withToken, httpLink]);
```

I don't understand why I'm not able to catch the error earlier. Any pointers would be helpful. Also here's my package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "apollo-cache-inmemory": "^1.1.1",
    "apollo-client": "^2.0.3",
    "apollo-client-preset": "^1.0.3",
    "apollo-link": "^1.1.0",
    "apollo-link-context": "^1.0.5",
    "apollo-link-error": "^1.0.5",
    "apollo-link-http": "^1.2.0",
    "expo": "^25.0.0",
    "google-libphonenumber": "^3.0.9",
    "graphql": "^0.11.7",
    "graphql-tag": "^2.5.0",
    "moment": "^2.20.1",
    "native-base": "^2.3.5",
    "react": "16.2.0",
    "react-apollo": "^2.0.1",
    "react-native":
      "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-actionsheet": "^2.3.0",
    "react-native-datepicker": "^1.6.0",
    "react-native-input-scroll-view": "^1.6.3",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-navigation": "^1.0.3",
    "recompose": "^0.26.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.2",
    "babel-plugin-inline-import-graphql-ast": "^2.0.2",
    "babel-plugin-transform-remove-console": "^6.8.5",
    "eslint": "^4.11.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-graphql": "^1.4.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.5.1",
    "eslint-plugin-react-native": "^3.2.0",
    "jest-expo": "^25.0.0",
    "prettier-eslint": "^8.8.1"
  }
}
```

**Comment by arrygoo** [comment]
Closing this, but for anyone else running into this issue in the future, I was missing `id` from one of my mutation queries
