### ISSUE TITLE
iOS: Attempted to call WebBrowser.openBrowserAsync multiple times warning even with await usage

### ISSUE THREAD

**Issue by soullivaneuh** [expo/expo#14550]
### Summary

I have a 3DS implementation on my expo App. On card data submit, I have to:

1. Open a first browser to fetch the accept header thanks to a redirection
2. Immediately open an another one to fetch another browser information
3. Then open a final browser to the given 3ds protocol URL

On iOS, it is stuck between stage 1 on 2, giving the following warning:

```
Attempted to call WebBrowser.openBrowserAsync multiple times while already active. Only one WebBrowser controller can be active at any given time.
at node_modules/expo-web-browser/build/WebBrowser.js:64:21 in openBrowserAsync
at node_modules/expo-web-browser/build/WebBrowser.js:57:7 in openBrowserAsync
at src/components/payment/CreditCardAdd.tsx:73:17 in setTimeout$argument_0
at http://192.168.1.20:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:258372:51 in _callee
```

I sneaked onto your compiled codebase to identify where the warning is thrown and add some logs:

```javascript
export async function openBrowserAsync(url, browserParams = {}) {
    if (!ExponentWebBrowser.openBrowserAsync) {
        throw new UnavailabilityError('WebBrowser', 'openBrowserAsync');
    }
    if (browserLocked) {
        // Prevent multiple sessions from running at the same time, WebBrowser doesn't
        // support it this makes the behavior predictable.
        if (__DEV__) {
            console.warn('Attempted to call WebBrowser.openBrowserAsync multiple times while already active. Only one WebBrowser controller can be active at any given time.');
        }
        return { type: WebBrowserResultType.LOCKED };
    }
    console.log('browser.lock');
    browserLocked = true;
    let result;
    try {
        result = await ExponentWebBrowser.openBrowserAsync(url, browserParams);
    }
    finally {
        console.log('browser.unlock');
        // WebBrowser session complete, unset lock
        browserLocked = false;
    }
    return result;
}
```

The `browser.unlock` log appears **after** the warning.

This is weird because I prefixed any `WebBrowser.openBrowserAsync` method to ensure a complete process before continuing.

Even more weird, I found a workaround: If I wait 1 seconds before opening the browser, it works! Also, no need to apply the same workaround for the third opening, it is working as shown.

Also, you will agree that is not a really clean fix. :upside_down_face: 

I am opening this as a bug because I don't find any logical explanation to this. Maybe it is a bad usage that need documentation.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.12.0 environment info:
    System:
      OS: Linux 5.9 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.10.0 - /usr/bin/node
      npm: 7.19.1 - /usr/bin/npm
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Here is the complete code of the related screen, including the dirty workaround:

```typescript
export const CreditCardAdd: FC<CreditCardAdd> = ({
  onAdd,
}) => {
  const { client, handleError } = useClient();
  const [number, setNumber] = useState<string>('');
  const [expirationDate, setExpirationDate] = useState<string>('');
  const [csv, setCsv] = useState<string>('');

  const [ready, setReady] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);

  const creditCardRef = useRef<CreditCardsData>();
  const registrationDataRef = useRef<string>();
  const ipAddressRef = useRef<string>();
  const headersRef = useRef<any>();

  const handleCreditCardRegistrationError = (error: FeathersError): void => {
    setLoading(false);
    if (error.code === 402 || error.message === 'credit-cards.register.failure') {
      Alert.alert(
        "Impossible d'enregistrer la carte",
        'Merci de vérifier les données saisies ainsi que la validité de la carte.'
        + '\nSi le problème persiste, contactez-nous.',
      );
    } else {
      handleError(error);
    }
  };

  const urlEventHandler = async (event): Promise<void> => {
    const parsedUrl = queryString.parseUrl(event.url);

    // Works on iOS only and cause a crash on Android will opening an another browser instance.
    if (Platform.OS === 'ios') {
      console.log('WebBrowser.dismissBrowser');
      await WebBrowser.dismissBrowser();
    }

    if (
      parsedUrl.url.endsWith('/headers')
    ) {
      console.log('headers');
      headersRef.current = parsedUrl.query;

      // We have to set a dirty workaround to the "already opened browser" issue.
      setTimeout(async () => {
        await WebBrowser.openBrowserAsync(
          `${Constants.manifest?.extra?.apiEndpoint
          }/browser.html?redirectUrl=${
            Linking.createURL('browser-info')}`,
        );
      }, 1000);
    }

    if (
      parsedUrl.url.endsWith('/browser-info')
    ) {
      console.log('browser-info');
      client.service('credit-cards')
        .patch(creditCardRef.current._id, {
          registrationId: creditCardRef.current.registrationId,
          registrationData: registrationDataRef.current,
          registrationIpAddress: ipAddressRef.current,
          // @ts-expect-error Unable to set the type of the parsed query.
          registrationBrowserInfo: {
            ...parsedUrl.query,
            acceptHeader: headersRef.current.accept,
          },
          secureModeRedirectUrl: Linking.createURL('paybox-3ds', {
            queryParams: { creditCardId: creditCardRef.current._id },
          }),
        })
        .then(ResultHelpers.toOne)
        .then((result) => WebBrowser.openBrowserAsync(result.secureModeUrl, {
          // @see https://github.com/expo/expo/issues/8072#issuecomment-621173298
          showInRecents: true,
        }))
        .catch((error) => {
          handleCreditCardRegistrationError(error);
        });
    }

    if (
      parsedUrl.url.endsWith('/paybox-3ds')
      && typeof parsedUrl.query.creditCardId === 'string'
      && typeof parsedUrl.query.transactionId === 'string'
    ) {
      console.log('paybox-3ds');
      client.service('credit-cards')
        .patch(
          parsedUrl.query.creditCardId,
          {
            transactionId: parsedUrl.query.transactionId,
          },
        )
        .then(ResultHelpers.toOne)
        .then((result) => onAdd(result._id))
        .catch(handleCreditCardRegistrationError);
    }
  };

  useFocusEffect(
    useCallback(() => {
      Linking.addEventListener('url', urlEventHandler);

      return () => Linking.removeEventListener('url', urlEventHandler);
    }, []),
  );

  const handleSubmit: ButtonProps['onPress'] = () => {
    const expirationDateRaw = expirationDate.replace('/', '');
    const numberRaw = number.replace(/\s/g, '');
    setLoading(true);
    client.service('credit-cards').create({
      lastDigits: numberRaw.slice(numberRaw.length - 4),
      expirationDate: expirationDateRaw,
    })
      .then(ResultHelpers.toOne)
      .then(
        (result) => {
          const cardValidationData = {
            accessKeyRef: result.accessKey,
            data: result.preRegistrationData,
            cardNumber: numberRaw,
            cardExpirationDate: expirationDateRaw,
            cardCvx: csv,
          };

          const formBody = Object.keys(cardValidationData)
            .map((key) => `${encodeURIComponent(key)}=${encodeURIComponent(cardValidationData[key])}`).join('&');

          creditCardRef.current = result;

          return Promise
            .all([
              fetch(result.registrationUrl, {
                method: 'POST',
                body: formBody,
                headers: {
                  'Content-type': 'application/x-www-form-urlencoded;charset=UTF-8',
                },
              })
                .then((registrationResult) => registrationResult.text()),
              fetch('https://api.ipify.org').then((ipResult) => ipResult.text()),
            ])
            .then(async ([registrationData, ipAddress]) => {
              registrationDataRef.current = registrationData;
              ipAddressRef.current = ipAddress;

              await WebBrowser.openBrowserAsync(
                `${Constants.manifest?.extra?.apiEndpoint
                }/headers?redirectUrl=${
                  Linking.createURL('headers')}`,
              );
            });
        },
      )
      .catch(handleCreditCardRegistrationError);
  };

  const handleNumberChange = (newNumber: string): void => {
    setNumber(newNumber.length > number.length
      ? newNumber.replace(/\s/g, '').split(/(.{4})/).filter((x) => x).join(' ')
      : newNumber);
  };

  const handleExpirationDateChange = (newExpirationDate: string): void => {
    setExpirationDate(newExpirationDate.length > expirationDate.length
      ? newExpirationDate.replace(/\//g, '').split(/(.{2})/).filter((x) => x).join('/')
      : newExpirationDate);
  };

  useEffect(() => setReady(
    Boolean(number) && number.length === 19
    && Boolean(expirationDate) && expirationDate.length === 5
    && Boolean(csv) && csv.length === 3,
  ), [number, expirationDate, csv]);

  return (
    <ScrollView>
      <Spacer />
      <Input
        label="Numéro de carte"
        value={number}
        onChangeText={handleNumberChange}
        keyboardType="number-pad"
        autoFocus
        maxLength={19}
        editable={!loading}
      />
      <View style={{ flexDirection: 'row' }}>
        <Input
          label="MM/AA"
          value={expirationDate}
          onChangeText={handleExpirationDateChange}
          keyboardType="number-pad"
          maxLength={5}
          editable={!loading}
        />
        <Input
          label="Code de sécurité (CVV)"
          value={csv}
          onChangeText={setCsv}
          keyboardType="number-pad"
          editable={!loading}
        />
      </View>
      <Button
        title="Valider"
        onPress={handleSubmit}
        loading={loading}
        disabled={!ready}
      />
    </ScrollView>
  );
};
```

**Comment by enesozturk** [comment]
I am having this issue but my case is dead simple, trying to open web browser just like the [example in document](https://docs.expo.dev/versions/latest/sdk/webbrowser/#usage); it is opening the browser, I press 'Done', it closes, when I try to open it again, I see the warning with the same message:

```bash
Attempted to call WebBrowser.openBrowserAsync multiple times while already active. Only one WebBrowser controller can be active at any given time.
```

Here is my example code:
```js
import React from "react";

import * as WebBrowser from "expo-web-browser";

const EmbeddedFile = ({ title, link }) => {
  const _handlePressButtonAsync = async () => {
    let result = await WebBrowser.openBrowserAsync(`https://expo.dev/`);
  };

  return (
    <Container onPress={handlePressButtonAsync}>
      <MyContent/>
    </Container>
  );
};

export default EmbeddedFile;
```

Any idea why it can be?

**Comment by enesozturk** [comment]
Looks like it is related to where the component is rendered inside the navigation structure. When I put my component to the Storybook navigation and try to press it, it shows the warning. When I put it to the root, it is ok to open the browser. 

Here is my current setup, it s broken.
```js
 return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{ headerShown: false, presentation: "modal" }}>
        <Stack.Screen name="MainStack" options={{ headerShown: false }} component={MainStack} />
        {/* Here, my component is a story */}
        <Stack.Screen name="Storybook" component={Storybook} options={{ gestureEnabled: true }} />
      </Stack.Navigator>
    </NavigationContainer>
  );
```

When I try to render by comp in this root or maybe inside the `MainStack`, it is ok.
