### ISSUE TITLE
Expo Splash Screen throws error on release and dev client builds

### ISSUE THREAD

**Issue by pheuter** [expo/expo#14703]
### Summary

Appears to be a new issue with Expo SDK 43 beta, tried with and without `<AppLoading>`, keep getting the same error:

```
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
at node_modules/react-native/Libraries/Utilities/RCTLog.js:34:8 in logIfNoNativeHook

[Unhandled promise rejection: Error: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-splash-screen/build/SplashScreen.js:11:17 in preventAutoHideAsync
at node_modules/expo-splash-screen/build/SplashScreen.js:7:7 in preventAutoHideAsync
at node_modules/expo-app-loading/build/AppLoadingNativeWrapper.js:9:8 in AppLoading#constructor
at node_modules/@react-navigation/native/src/useThenable.tsx:26:18 in resolve

[Unhandled promise rejection: Error: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-splash-screen/build/SplashScreen.js:23:17 in hideAsync
at node_modules/expo-splash-screen/build/SplashScreen.js:19:7 in hideAsync
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.11.0 - /opt/homebrew/bin/node
      npm: 8.0.0 - /opt/homebrew/bin/npm
      Watchman: 2021.10.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /Users/mark/.nix-profile/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: next => 43.0.0-beta.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I have exactly this logic in my app: https://docs.expo.dev/versions/v43.0.0/sdk/splash-screen/#usage. Worked just fine on Expo SDK 42.

**Comment by Kudo** [comment]
i am leaving this open and check the eas release build.

**Comment by brentvatne** [comment]
i've confirmed locally using `expo run:ios --configuration Release` that this is resolved in release builds after installing the latest versions of sdk 43 beta packages to get @Kudo's fix. i also no longer see the warning in debug builds.

**Comment by raphaelmsr** [comment]
Hey there ! Also getting a crash upon upgrading to SDK 43 (was building fine on 42) 

*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <EXSplashScreenService 0x600000efc960> for the key path "rootViewController" from <UIWindow 0x7fd6bb729f60>
because it is not registered as an observer.'

Dont know if this is linked to that but thankts to @brentvatne , when I run 

> expo run:ios --configuration Release

I don't get the crash (and I didn't have to update to 43 Beta

**Comment by brentvatne** [comment]
@raphaelmsr - can you please create a new issue and share a reproducible example?

**Comment by raphaelmsr** [comment]
but it would be yet another splash- related bug opened, there are plenty maybe all linked to the same issue 
Will open though !

**Comment by Dakuan** [comment]
`SplashScreen.preventAutoHideAsync` has stopped working, both in custom dev client and production builds

**Comment by Kudo** [comment]
@Dakuan could you check if update `expo-splash-screen@0.13.5` and `expo-updates@0.10.12` help with your problem?

**Comment by raphaelmsr** [comment]
Fixed ! Awesome, you were so fast to address this ticket
Although now I have a Warning saying 
`RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks`

**Comment by Dakuan** [comment]
@Kudo yep, that's fixed it, many thanks

**Comment by Kudo** [comment]
that's great! thank you folks for the confirmation.

@raphaelmsr the RCTDevLoadingView is known issue to react-native 0.64 😔  that's not critical and only happens in debug build.

**Comment by faustoct** [comment]
it happened to me only in production
expo sdk 43

**Comment by astronomyf** [comment]
Happening to me as well, in production only with expo SDK 44.
Some users are complaining that the app is stuck on the splash screen, not all the times thought.

**Comment by WillenOLeal** [comment]
It happens to me as well on my dev build. SDK 45 and `expo-splash-screen": "~0.15.1`. `SplashScreen.preventAutoHideAsync();` does not work.

**Comment by jakobsuckow** [comment]
Same problem, app is stuck on splashscreen, with SDK 43. 

Dependencies:
`  "dependencies": {
    "@expo/ngrok": "^2.5.0",
    "@expo/react-native-action-sheet": "^3.13.0",
    "@gorhom/bottom-sheet": "^4",
    "@react-native-community/datetimepicker": "3.5.2",
    "@react-native-community/hooks": "^2.8.1",
    "@react-native-picker/picker": "2.1.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/material-top-tabs": "^6.0.6",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@react-navigation/stack": "^6.2.1",
    "axios": "^0.21.4",
    "d3-shape": "^3.1.0",
    "dayjs": "^1.10.7",
    "expo": "^43.0.0",
    "expo-blur": "~10.0.3",
    "expo-camera": "~12.0.3",
    "expo-dev-client": "~0.6.3",
    "expo-file-system": "~13.0.3",
    "expo-font": "~10.0.3",
    "expo-haptics": "~11.0.3",
    "expo-image-manipulator": "~10.1.2",
    "expo-image-picker": "~11.0.3",
    "expo-linear-gradient": "~10.0.3",
    "expo-linking": "~2.4.2",
    "expo-notifications": "~0.13.3",
    "expo-secure-store": "~11.0.3",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.15",
    "jwt-decode": "^3.1.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-hook-form": "^7.17.2",
    "react-native": "0.64.3",
    "react-native-blurhash": "^1.1.10",
    "react-native-confirmation-code-field": "^7.1.0",
    "react-native-date-picker": "^4.1.1",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-get-random-values": "~1.7.0",
    "react-native-modal-datetime-picker": "^13.0.0",
    "react-native-pager-view": "5.4.6",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-shared-element": "0.8.2",
    "react-native-svg": "12.1.1",
    "react-native-tab-view": "^3.1.1",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "0.17.1",
    "react-navigation-shared-element": "^3.1.3",
    "react-query": "^3.24.5",
    "uuid": "^8.3.2"
  },`

**Comment by jakobsuckow** [comment]
@WillenOLeal were you able to resolve this issue ?
