### ISSUE TITLE
[expo-file-system] Error when calling downloadAsync on a DownloadResumable

### ISSUE THREAD

**Issue by mackenziekira** [expo/expo#14913]
### Summary

When calling

```
async function downloadFile(uri) {
    try {
        const result = await FileSystem.createDownloadResumable(uri, "", {}).downloadAsync();
    } catch (e) {
        console.log(e)
    }
}
```

I get the following error: 

```
null is not an object (evaluating '(_NativeModules$UMReac = _reactNative.NativeModules.UMReactNativeEventEmitter).addProxiedListener')
at http://127.0.0.1:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:191135:93 in <unknown>
at node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:60:6 in addListener
at node_modules/expo-modules-core/build/EventEmitter.js:17:42 in addListener
at node_modules/expo-file-system/build/FileSystem.js:154:28 in FileSystemCancellableNetworkTask#addSubscription
at node_modules/expo-file-system/build/FileSystem.js:239:8 in DownloadResumable#downloadAsync
at node_modules/react-native-expo-image-cache/dist/module/CacheManager.js:1:257 in <global>
```

My `expo-file-system` version is "13.0.3"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.6 - /var/folders/pp/l_cvj33s4938fc194wqkw0rw0000gp/T/yarn--1635291166577-0.9060108138149592/node
      Yarn: 1.22.10 - /var/folders/pp/l_cvj33s4938fc194wqkw0rw0000gp/T/yarn--1635291166577-0.9060108138149592/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.2 => 0.16.2 
      expo: ^43.0.1 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 3.20.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Was not able to produce a Snack because looks like highest snack sdk is 42, but in a new project, can add

```
"expo": "^43.0.1",
"expo-file-system": "~13.0.3",
```

Build via EAS Build, and then call this function:

```
async function downloadFile(uri) {
    try {
        const result = await FileSystem.createDownloadResumable(uri, "", {}).downloadAsync();
    } catch (e) {
        console.log(e)
    }
}
```

**Comment by cruzach** [comment]
Have you tried this on a brand new `expo init` project using SDK 43? It's working for me:
```
const result = await FileSystem.createDownloadResumable(
              "http://techslides.com/demos/sample-videos/small.mp4",
              FileSystem.documentDirectory + "small.mp4",
              {},
              (downloadProgress) => {
                console.log(downloadProgress);
              }
            ).downloadAsync();
```

**Comment by mackenziekira** [comment]
Hm, apologies for not checking on a fresh setup! I'll close this issue.

It may be related to https://github.com/expo/expo/issues/14186 and https://github.com/expo/expo/issues/14092. When I add `"@unimodules/react-native-adapter": "^6.3.9",` as a dependency, the error no longer occurs. Previously`@unimodules/react-native-adapter` was included in our `yarn.lock` file as a dependency of a dependency, but it was at version `"6.0.0"`
