### ISSUE TITLE
[exp] Error: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by quyettvq** [expo/expo#1492]
I'm attempting to build a signed APK to upload to Google Play.
My app contains some JSON assets, which are 50MB in total.
When I remove them, this error does not occur and my app was built successfully.
So I want to increase `maxBodyLength`, how can I do it?

Below are details log from cmd:
```
exp build:android
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.

? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
[exp] Publishing...
[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Request body larger than maxBodyLength limit
[exp] Error: Request body larger than maxBodyLength limit
    at Writable.RedirectableRequest.write (C:\Users\User\AppData\Roaming\npm\node_modules\exp\node_modules\follow-redirects\index.js:66:24)
    at Writable.RedirectableRequest.end (C:\Users\User\AppData\Roaming\npm\node_modules\exp\node_modules\follow-redirects\index.js:78:10)
    at dispatchHttpRequest (C:\Users\User\AppData\Roaming\npm\node_modules\exp\node_modules\axios\lib\adapters\http.js:228:11)
    at httpAdapter (C:\Users\User\AppData\Roaming\npm\node_modules\exp\node_modules\axios\lib\adapters\http.js:18:10)
    at dispatchRequest (C:\Users\User\AppData\Roaming\npm\node_modules\exp\node_modules\axios\lib\core\dispatchRequest.js:52:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by terribleben** [comment]
Hey there, I think this is a limit imposed by exp and our servers. See also: https://github.com/expo/expo/issues/1307 . Can you try splitting your assets into smaller sections?

**Comment by fson** [comment]
There's currently a 50 MB limit for the total size of JavaScript bundles that are uploaded. JSON files are included in the JavaScript bundle by default. This is fine for small files, but for larger files this might not be ideal, since every time you update your app the users have to download the bundle, including the data (even if it didn't change). A large JS bundle is also slower to load, even if not all of all the data is needed when your app starts.

To have more control over when the JSON files is downloaded, you might want to configure them to be treated as assets. For assets the size limit is 50 MB per asset and there's no limit for the total number of assets.

You probably want to rename the files to some other extension, e.g. `.dat` to distinguish it from JSON files that can be imported and then add that file extension to `assetExts` in your `app.json`:
```
{
  "expo": {
    ...
    "packagerOpts": {
      "assetExts": ["dat"]
    }
  }
}
```
Then in your app you can download the file with `Expo.Asset.fromModule(module).downloadAsync()`:
```js
import { Asset, FileSystem } from 'expo';
import items from './assets/items.dat';
// ...
async function loadData() {
  let asset = Asset.fromModule(items);
  await asset.downloadAsync();
  let json = await FileSystem.readAsStringAsync(asset.localUri);
  return JSON.parse(json);
}
```
There's also [`Asset.loadAsync`](https://docs.expo.io/versions/latest/sdk/asset.html#expoassetloadasyncmodules) that lets you more easily download multiple assets at once. Then, if you need some of the files to be bundled inside your standalone app, you can even do that with [`assetBundlePatterns `](https://docs.expo.io/versions/latest/guides/offline-support.html#bundle-your-assets-inside-your-standalone-binary).

If your app needs to query large data files, you may also want to check out the [SQLite](https://docs.expo.io/versions/latest/sdk/sqlite.html) module, which can be faster since the databases are handled fully in native code. You can upload a `.db` database for SQLite using the same method described above.
