### ISSUE TITLE
How to generating the release APK with detach?

### ISSUE THREAD

**Issue by weeravit** [expo/expo#150]
I try to use `react-native run-android --variant=release`

but exception on log

`
FATAL EXCEPTION: OkHttp Dispatcher
                                                   Process: com.smartactive.pasee, PID: 11027
                                                   java.lang.RuntimeException: Could not load exp://exp.host/@weeravit/smart-active-learning.
                                                       at host.exp.exponent.kernel.ExpoViewKernel.handleError(ExpoViewKernel.java:76)
                                                       at host.exp.expoview.ExponentActivity$1.onError(ExponentActivity.java:109)
                                                       at host.exp.exponent.ExponentManifest$3.onResponse(ExponentManifest.java:217)
                                                       at host.exp.exponent.network.ExponentHttpClient.tryHardCodedResponse(ExponentHttpClient.java:122)
                                                       at host.exp.exponent.network.ExponentHttpClient.access$100(ExponentHttpClient.java:32)
                                                       at host.exp.exponent.network.ExponentHttpClient$2.onResponse(ExponentHttpClient.java:95)
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: Could not load exp://exp.host/@weeravit/smart-active-learning.
`

**Comment by weeravit** [comment]
This article explain clearly for my problem
https://blog.expo.io/publishing-on-exponent-790493660d24

I'm sorry
