### ISSUE TITLE
[expo-updates] Failed to copy embedded asset from APK assets or resources because not enough information was provided.

### ISSUE THREAD

**Issue by Yonom** [expo/expo#15112]
### Summary

We are getting crash reports from production since upgrading to expo-updates 0.10.13. This happens on the first launch after the upgrade, affects 100% of users upgrading

Our users are upgrading from our previous release using SDK 43 expo-updates 0.10.12

```
Fatal Exception: java.lang.AssertionError: Failed to copy embedded asset 2fe047f8618cf7a05eebad78a58752b4 from APK assets or resources because not enough information was provided.
       at expo.modules.updates.loader.EmbeddedLoader.copyAssetAndGetHash(EmbeddedLoader.java:104)
       at expo.modules.updates.loader.EmbeddedLoader.copyAllAssets(EmbeddedLoader.java:182)
       at expo.modules.updates.loader.EmbeddedLoader.processUpdateManifest(EmbeddedLoader.java:150)
       at expo.modules.updates.loader.EmbeddedLoader.loadEmbeddedUpdate(EmbeddedLoader.java:62)
       at expo.modules.updates.loader.LoaderTask.launchFallbackUpdateFromDisk(LoaderTask.java:236)
       at expo.modules.updates.loader.LoaderTask.start(LoaderTask.java:111)
       at expo.modules.updates.UpdatesController.start(UpdatesController.java:332)
       at expo.modules.updates.UpdatesController.initialize(UpdatesController.java:102)
       at expo.modules.updates.UpdatesPackage$1.createReactInstanceManager(UpdatesPackage.java:48)
       at expo.modules.ReactNativeHostWrapper.createReactInstanceManager(ReactNativeHostWrapper.kt:30)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
       at com.app.MainApplication.onCreate(MainApplication.java:69)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7393)
       at android.app.ActivityThread.access$2400(ActivityThread.java:251)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8393)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /var/folders/4l/5q_1bbc93mb221kpmsz41jth0000gn/T/yarn--1636451823142-0.0544419437953072/node
      Yarn: 1.22.17 - /var/folders/4l/5q_1bbc93mb221kpmsz41jth0000gn/T/yarn--1636451823142-0.0544419437953072/yarn
      npm: 8.1.0 - /usr/local/Cellar/node@16/16.13.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- Create a new app with some assets (fonts, images), install expo-updates 0.10.12
- Build and install a production version of the app on Android
- Launch the app once
- Upgrade to expo-updates 0.10.13, create a production build and install the update on the device
- Launch the app again

:x: NOK: app crashes on launch

**Comment by esamelson** [comment]
Thanks for the report, looking into this.

**Comment by esamelson** [comment]
It looks like this is one more remnant from #14930. I've just released expo-updates@0.10.14 with a patch for this fix which should ensure that any clients stuck crashing right now fix themselves after upgrading. Let me know if there continue to be any issues like this. I'm really sorry about the continued troubles here. 😞

**Comment by BrodaNoel** [comment]
Maaaaay https://github.com/expo/expo/pull/15123 fixes this issue

**Comment by Yonom** [comment]
We haven't had any such issue since upgrading to expo updates 0.10.15
