### ISSUE TITLE
Async storage is null when running jest tests

### ISSUE THREAD

**Issue by byCedric** [expo/expo#15161]
### Summary

It seems that we aren't mocking the [`NativeModules.RNCAsyncStorage`](https://github.com/react-native-async-storage/async-storage/blob/v1.15.11/src/RCTAsyncStorage.js#L7) in our `expo-jest` mocks. We [already have some "external" mocks defined there](https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/expoModules.js#L1086-L1123), so I'm not sure why async storage was omitted.

If a project uses the async storage library, it will fail tests with:
```
 ● Test suite failed to run
    [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
    To fix this issue try these steps:
      • Run `react-native link @react-native-async-storage/async-storage` in the project root.
      • Rebuild and restart the app.
      • Run the packager with `--reset-cache` flag.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.
      • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest
    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues
      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.native.js:17:9)
      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/index.js:6:1)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.12.12 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.11.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~43.0.2 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

From the original reporter, this was the basic package file.

```
"expo": "^43.0.1",
"jest": "^27.3.1",
"jest-expo": "^43.0.0",
"ts-jest": "^27.0.7",
"@react-native-async-storage/async-storage": "~1.15.0",
```

**Comment by Simek** [comment]
Refs?
* https://github.com/react-native-async-storage/async-storage/pull/708

**Comment by jgjio** [comment]
I'm also getting the error above when trying to render a component.

Does anyone know why mocking in Jest Setup doesn't work around this issue?

```
import mockAsyncStorage from '@react-native-community/async-storage/jest/async-storage-mock';
jest.mock('@react-native-community/async-storage', () => mockAsyncStorage);
```

The error is the same.

**Comment by adriaanbalt** [comment]
Same is happening to me.

package.json:
```
{
  "name": "projectname",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx"
    ]
  },
  "dependencies": {
    "@apollo/client": "^3.5.5",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "apollo3-cache-persist": "^0.13.0",
    "expo": "~43.0.2",
    "expo-asset": "~8.4.3",
    "expo-constants": "~12.1.3",
    "expo-font": "~10.0.3",
    "expo-linking": "~2.4.2",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-web-browser": "~10.0.3",
    "graphql": "^16.0.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/jest": "^27.4.0",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "@types/react-test-renderer": "^17.0.1",
    "jest": "^27.4.7",
    "jest-expo": "~43.0.0",
    "react-test-renderer": "17",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.4.0",
    "typescript": "~4.3.5"
  },
  "private": true
}
```

**Comment by adriaanbalt** [comment]
I stumbled across this @byCedric https://react-native-async-storage.github.io/async-storage/docs/advanced/jest/ and this seems to get me through the jest test without an error.  It's still early on to be 100% valid but I figured I would share since now I'm no longer seeing that error when running `yarn jest`
