### ISSUE TITLE
Gradle build fail on first time doing expo run:android

### ISSUE THREAD

**Issue by sstephans** [expo/expo#15183]
### Summary

I am trying an intial run of `expo run:android` after installing `expo-dev-client`. Expected behavior is that it would complete successfully so I can run the dev client. Actual behavior is that the gradle build fails with one of two errors: 

```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Cannot query the value of this provider because it has no value available.
```
or
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:lint'.
   > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\saman\Desktop\testExpo\test\android\local.properties'.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

I have a fresh install of expo and am trying to get the dev client set up so I can run from hermes. The process I went through was

1. `expo init` (chose typescript blank setup) (success)
2. `yarn add expo-dev-client` (success)
3. add `"jsEngine": "hermes` to `app.json` in the `"expo"` object
4. `expo run:android`
5. Give android the package name `com.testAndroidPackage`
6. The gradle build fails. Each time I try running this I get two alternating failures:
```
C:\Users\saman\Desktop\testExpo\test>expo run:android
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.13.0).                │
│   You are currently using expo-cli 4.12.10                              │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
› Building app...
Configuration on demand is an incubating feature.

> Configure project :expo-structured-headers
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo
Using expo modules
ù expo-application (4.0.0)
ù expo-constants (12.1.3)
ù expo-error-recovery (3.0.3)
ù expo-file-system (13.0.3)
ù expo-font (10.0.3)
ù expo-json-utils (0.2.0)
ù expo-keep-awake (10.0.0)
ù expo-manifests (0.2.2)
ù expo-modules-core (0.4.8)
ù expo-splash-screen (0.13.5)
ù expo-structured-headers (2.0.0)
ù expo-updates (0.10.15)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Cannot query the value of this provider because it has no value available.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
C:\Users\saman\Desktop\testExpo\test\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\saman\Desktop\testExpo\test\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at spawnGradleAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:83:18)
    at assembleAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:57:16)
    at actionAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\runAndroid.ts:143:9)
```
or
```
C:\Users\saman\Desktop\testExpo\test>expo run:android
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.13.0).                │
│   You are currently using expo-cli 4.12.10                              │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
› Building app...
Configuration on demand is an incubating feature.

> Configure project :expo-structured-headers
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo
Using expo modules
ù expo-application (4.0.0)
ù expo-constants (12.1.3)
ù expo-error-recovery (3.0.3)
ù expo-file-system (13.0.3)
ù expo-font (10.0.3)
ù expo-json-utils (0.2.0)
ù expo-keep-awake (10.0.0)
ù expo-manifests (0.2.2)
ù expo-modules-core (0.4.8)
ù expo-splash-screen (0.13.5)
ù expo-structured-headers (2.0.0)
ù expo-updates (0.10.15)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:lint'.
   > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\saman\Desktop\testExpo\test\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
C:\Users\saman\Desktop\testExpo\test\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\saman\Desktop\testExpo\test\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at spawnGradleAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:83:18)
    at assembleAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:57:16)
    at actionAsync (C:\Users\saman\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\runAndroid.ts:143:9)
```

It says I can run with `--stacktrace` to see more details, however I'm not sure how to insert arguments into the internal gradle task. If you need that, please let me know how I can do that. Thanks!

**Comment by Kudo** [comment]
hi there! as the error message you posted, you may need to specify the `ANDROID_SDK_ROOT` environment to your android sdk. could you double check your `ANDROID_SDK_ROOT` environment variable?

**Comment by sstephans** [comment]
I just checked and it appears to not be set on my machine. That wasn't part of the setup instructions for the client. What should it be set to?

**Comment by sstephans** [comment]
I set it to `C:\Users\<UserName>\AppData\Android\sdk` per this article https://www.geeksforgeeks.org/fix-sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-file-or-with-an-android_home-environment-variable-in-android-studio/ and the gradle task built successfully and the app runs fine now with the `--dev-client` flag.

**Comment by DevKalebe** [comment]
A minha está configurada e continua com o erro, estou rodando npx `expo run:android --device`. Anteriormente estava funcionando.

**Comment by RaghavBhat02** [comment]
We've set this variable and this is still happening. Any other ideas?

**Comment by Raduc4** [comment]
> We've set this variable and this is still happening. Any other ideas?

Any solutions?

**Comment by SorenJ89** [comment]
> > We've set this variable and this is still happening. Any other ideas?
> 
> Any solutions?

In my case, android sdk was located in C:\Users\<username>\AppData\**Local**\Android\Sdk
you can find the location by opening android sdk settings
![image](https://github.com/expo/expo/assets/25386745/d17eb3c9-25bd-42a9-9a7f-d1520ff7b262)
