### ISSUE TITLE
Silent packager errors in `PackageLogsStream`

### ISSUE THREAD

**Issue by vjpr** [expo/expo#1537]
https://github.com/expo/xdl/blob/cf53633e47bdbc56a7a6549a5838f15c6973f4db/src/logs/PackagerLogsStream.js#L96-L119

It matches 4 event types and if it doesn't match it removes the error.

I had to manually add a `console.log` statement to find the reason my build wasn't working.

```
   { type: 'worker_stderr_chunk',
     chunk: 'module.js:538\n    throw err;\n    ^\n\nError: Cannot find module \'babel-template\'\n    at Function.Module._resolveFilename (module.js:536:15)\n    at Function.Module._load (module.js:466:25)\n    at Module.require (module.js:579:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/metro-pnpm/0.24.7-vjpr.1/node_modules/metro-pnpm/src/ModuleGraph/worker/collectDependencies.js:15:23)\n    at Module._compile (module.js:635:30)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)\n' } }
```

**Comment by vjpr** [comment]
So I can confirm changing to `chunk.msg = msg.chunk || ''` works well.

The `|| ''' is neccessary because `chunk.msg` is always expected to be a string.

**Comment by vjpr** [comment]
Also seeing another silenced error:

I added console.log manually.

```
{ msg:
   { buildID: '1',
     bundleDetails:
      { entryFile: 'node_modules/.registry.npmjs.org/react-native-scripts/1.11.1/node_modules/react-native-scripts/build/bin/crna-entry.js',
        platform: 'ios',
        dev: true,
        minify: false,
        bundleType: 'bundle' },
     type: 'bundle_build_started' } }
{ msg:
   { error: { type: 'TransformError', lineNumber: 0, errors: [Array] },
     type: 'bundling_error' } }
{ msg: { buildID: '1', type: 'bundle_build_failed' } }
12:06:46: Failed building JavaScript bundle
```
