### ISSUE TITLE
iOS App Store build failed - MAC verification failed during PKCS12 import 

### ISSUE THREAD

**Issue by ranlopez** [expo/expo#15412]
I’ve been getting this error when doing expo build:ios
I know my password is correct.
I already tried expo build:ios -c several times.
I also recreated all my keys and files from the App Store portal.
I even deleted all Credentials under my Expo Dashboard.
It’s still failing. Please help. I’m on Windows 10.
This is my first attempt to do an iOS build.

importing distribution certificate into keychain... importing certificate into keychain... certificate has password 

stderr]

security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?) unable to import distribution certificate into keychain 

security exited with non-zero code: 1

Error: security exited with non-zero code: 1 at ChildProcess.completionListener (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23) at Object.onceWrapper (events.js:421:26) at ChildProcess.emit (events.js:314:20) at ChildProcess.EventEmitter.emit (domain.js:483:12) at maybeClose (internal/child_process.js:1022:16) at Socket.<anonymous> (internal/child_process.js:444:11) at Socket.emit (events.js:314:20) at Socket.EventEmitter.emit (domain.js:483:12) at Pipe.<anonymous> (net.js:675:12) ... at spawnAsync (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21) at spawnAsyncThrowError (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45) at /usr/local/turtle-js/node_modules/@expo/xdl/build/detach/ExponentTools.js:247:12 at Object.importIntoKeychain (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosKeychain.js:136:9) at Object.importCert (/usr/local/turtle-js/build/builders/utils/ios/keychain.js:70:33) at async Object.buildArchive [as default] (/usr/local/turtle-js/build/builders/ios/archive.js:38:9) at async Object.iosBuilder [as ios] (/usr/local/turtle-js/build/builders/ios/index.js:30:13) at async build (/usr/local/turtle-js/build/jobManager.js:181:33) at async processJob (/usr/local/turtle-js/build/jobManager.js:118:32) at async Object.doJob (/usr/local/turtle-js/build/jobManager.js:49:5) at async main (/usr/local/turtle-js/build/server.js:66:13)

**Comment by ranlopez** [comment]
Closing as I got to make this work. Turns out I needed to properly run OpenSSL and generate the keys there vs. just running openssl.exe ... Not sure why but it now works!
