### ISSUE TITLE
AAB crash java.lang.AssertionError: APK bundle must contain the expected embedded asset index.android.bundle

### ISSUE THREAD

**Issue by hotaryuzaki** [expo/expo#15499]
### Summary

i build bundle for android and crash when open, what i found in adb logcat:

```
12-10 15:04:34.984 27112 27112 E AndroidRuntime: FATAL EXCEPTION: main
12-10 15:04:34.984 27112 27112 E AndroidRuntime: Process: com.brambang.apps, PID: 27112
12-10 15:04:34.984 27112 27112 E AndroidRuntime: java.lang.AssertionError: APK bundle must contain the expected embedded asset index.android.bundle
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.l.e.a(Unknown Source:147)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.l.e.g(Unknown Source:50)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.l.e.e(Unknown Source:10)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.l.g.x(Unknown Source:64)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.l.g.B(Unknown Source:96)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.f.D(Unknown Source:75)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.f.s(Unknown Source:5)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at expo.modules.updates.UpdatesPackage$a.b(Unknown Source:12)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at f.a.e.createReactInstanceManager(Unknown Source:33)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at com.facebook.react.s.a(Unknown Source:9)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at com.brambang.apps.MainApplication.onCreate(Unknown Source:11)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6991)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8056)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
12-10 15:04:34.984 27112 27112 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

---------------------------------------------------------------------------------

12-10 15:05:09.141 27307 27377 E AndroidRuntime: FATAL EXCEPTION: create_react_context
12-10 15:05:09.141 27307 27377 E AndroidRuntime: Process: com.brambang.apps, PID: 27307
12-10 15:05:09.141 27307 27377 E AndroidRuntime: java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(Unknown Source:2)
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(Unknown Source:10)
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(Unknown Source:18)
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at com.facebook.react.p.p(Unknown Source:189)
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at com.facebook.react.p.c(Unknown Source:0)
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at com.facebook.react.p$e.run(Unknown Source:68)
12-10 15:05:09.141 27307 27377 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

actually before this i already encountered the second Fatal [here](https://github.com/expo/expo/issues/15269) and i add `-keep class com.facebook.react.turbomodule.** { *; }` in Proguard to fixed the issue.
after that my apps is works, for debug and release (APK).
but then i found the error still occur in AAB

here is my build gradle,
```
buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            shrinkResources enableShrinkResourcesBuilds // ENABLES RESOURCE SHRINKING, WHICH IS PERFORMED BY THE ANDROID GRADLE PLUGIN
            ndk { debugSymbolLevel = "SYMBOL_TABLE" } // CREATE NATIVE DEBUG SYMBOLS IN PLAY STORE #2
        }
    }
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v14.17.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
    npmPackages:
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

no

**Comment by hotaryuzaki** [comment]
issue solved [here](https://github.com/facebook/react-native/issues/31157#issuecomment-990911849)
