### ISSUE TITLE
Expo remote build for IOS failing in NSBundle Configuration 

### ISSUE THREAD

**Issue by hatim85f** [expo/expo#15536]
### Summary

I am repeatly getting a failure with ios build using expo build:ios -t archive. Log is not showing any data about the issue 

```
Error: xcrun exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
    ...
    at spawnAsync (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
    at Object.buildAssetArchiveAsync (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosAssetArchive.js:96:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.configureAsync (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosNSBundle.js:740:7)
    at async Object.configureAndCopyArchiveAsync (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosShellApp.js:367:3)
    at async Object.runShellAppBuilder [as default] (/usr/local/turtle-js/build/builders/utils/ios/shellAppBuilder.js:67:12)
    at async Object.buildArchive [as default] (/usr/local/turtle-js/build/builders/ios/archive.js:39:26)
    at async Object.iosBuilder [as ios] (/usr/local/turtle-js/build/builders/ios/index.js:30:13)
    at async build (/usr/local/turtle-js/build/jobManager.js:181:33)
    at async processJob (/usr/local/turtle-js/build/jobManager.js:118:32)
    at async Object.doJob (/usr/local/turtle-js/build/jobManager.js:49:5)
    at async main (/usr/local/turtle-js/build/server.js:66:13)
```

Note : that in start og the build I was attaching png as icon but then changed it to jpg as the transparancy is not accecpted and the plugin I am using are ( expo-image-picker, expo-camera and expo-notifications )

I am trying hardly to know where is the issue to solve it 
and here is a my app.json file 

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

```
 Expo CLI 4.12.0 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo

```
{
  "expo": {
    "name": "myApp name",
    "slug": "appName",
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/mainLogo.jpg",
    "splash": {
      "image": "./assets/splash2.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./assets/mainLogo.png",
          "color": "#ffffff",
          "sounds": [
            "./assets/notification-sound.wav",
            "./assets/notification-sound-other.wav"
          ]
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "App is using your camera roll for just allowing you to upload your profile picture"
        }
      ],
      ["expo-camera"]
    ],
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "notification": {
      "icon": "./assets/logo2.png",
      "color": "#e8e8e8",
      "iosDisplayInForeground": true,
      "androidMode": "collapse",
      "androidCollapsedTitle": "New Notification"
    },
    "ios": {
      "bundleIdentifier": "com.hatim85f.appName",
      "supportsTablet": true,
      "infoPlist": {
 "NSCameraUsageDescription": "App is using your camera roll for just allowing you to upload your profile picture",
        "buildNumber": "1.0.0",
        "CFBundleVersion": "1.0.0",
        "CFBundleShortVersionString": "1.0.0"
      }
    },
    "android": {
      "versionCode": 2,
      "adaptiveIcon": {
        "foregroundImage": "./assets/mainLogo.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.hatim85f.alaa_clinic",
      "googleServicesFile": "./google-services.json"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

**Comment by brentvatne** [comment]
hi there! i'd recommend using [turtle-cli](https://github.com/expo/turtle) to debug it locally, or use the new service that is replacing `expo build` - [EAS Build](https://docs.expo.dev/build/introduction/). this service is much easier to debug. let us know what you find.

**Comment by hatim85f** [comment]
@brentvatne yes it's done by EAS Build ... thanks
