### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by sadia-onyxtec** [expo/expo#15549]
### Android project is not being build.

**_BUILD FAILED in 17s**

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :app
         project :app > project :react-native-community_masked-view
         project :app > project :expo
         project :app > project :react-native-blob-util
         project :app > project :react-native-gesture-handler
         project :app > project :react-native-image-picker
         project :app > project :react-native-safe-area-context
         project :app > project :react-native-screens
         project :app > project :react-native-vector-icons
         project :app > project :expo > project :expo-modules-core
      > Failed to list versions for com.facebook.react:react-native.
         > **Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml.**
            > **Could not get resource 'https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml'.**
               > **Could not GET 'https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway**
   > **Could not resolve com.google.android.exoplayer:exoplayer:2.9.2.**
     Required by:
         project :app > project :expo > project :expo-av
      > Skipped due to earlier error
   > Could not resolve com.google.android.exoplayer:extension-okhttp:2.9.2.
     Required by:
         project :app > project :expo > project :expo-av
      > Skipped due to earlier error
   > Could not resolve com.yqritc:android-scalablevideoview:1.0.1.
     Required by:
         project :app > project :expo > project :expo-av
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

    at makeError (/Users/<user>/Applications/<project>/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/<user>/Applications/<project>/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/<user>/Applications/<project>/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/<user>/Applications/<project>/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details._

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

^43.0.4

### Environment

 Expo CLI 5.0.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.4 => 43.0.4 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.3 => 0.66.3 
    npmGlobalPackages:
      expo-cli: 5.0.0
    Expo Workflow: bare

### Reproducible demo

This is my android/build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        maven {
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
        google()
        maven { url 'https://www.jitpack.io' }
    
  
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
    }
}

**Comment by sadia-onyxtec** [comment]
I have resolved this issue by commenting
 maven {
        url 'https://google.bintray.com/exoplayer/'
    }
    in build.gradle.
