### ISSUE TITLE
expo-keep-awake install removes expo from project

### ISSUE THREAD

**Issue by Engazan** [expo/expo#15589]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by Engazan** [comment]
Today after updating Expo CLI from v4 to v5 i m unable to install packages with "expo command"

Expo: 5.0.1
npm: 7.20.3
node: 16.6.1

1. open project
2. run ```yarn```, to install dep.
3. run ``` expo install expo-keep-awake```

error: 
```
error An unexpected error occurred: "EPERM: operation not permitted, unlink '...\\node_modules\\.bin\\expo'".

Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.cp.emit (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at Object.spawnAsync [as default] (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:309:31)
    at YarnPackageManager.addAsync (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:258:16)
    at actionAsync (...\AppData\Roaming\npm\node_modules\expo-cli\src\commands\installAsync.ts:125:3)

```

any solution ?

**Comment by brentvatne** [comment]
https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows
