### ISSUE TITLE
[SDK 43] BugSnag not usable in SDK 44 or SDK 45

### ISSUE THREAD

**Issue by adriaanbalt** [expo/expo#15609]
### Summary

```
Constants.installationId has been deprecated in favor of generating and storing your own ID. Implement it using expo-application's androidId on Android and a storage API such as expo-secure-store on iOS and localStorage on the web. This API will be removed in SDK 44.
at node_modules/expo-constants/build/Constants.js:64:12 in constantsPropertiesGetter.installationId
at node_modules/@bugsnag/plugin-expo-device/device.js:25:19 in module.exports.load
at node_modules/@bugsnag/core/client.js:162:19 in Client#_loadPlugin
at node_modules/@bugsnag/core/client.js:63:14 in map$argument_1
at node_modules/@bugsnag/core/lib/es-utils/map.js:5:54 in reduce$argument_1
at node_modules/@bugsnag/core/lib/es-utils/reduce.js:4:58 in module.exports
at node_modules/@bugsnag/core/lib/es-utils/map.js:5:8 in module.exports
at node_modules/@bugsnag/core/client.js:62:7 in Client#constructor
at node_modules/@bugsnag/expo/src/notifier.js:59:20 in Bugsnag.createClient
at node_modules/@bugsnag/expo/src/notifier.js:74:22 in Bugsnag.start
at src/utils/bugsnag.js:2:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at src/modals/ModalWhereToWatch/index.js:27:21 in ModalWhereToWatch#componentDidMount```
```
```
Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.
at node_modules/expo-constants/build/Constants.js:136:16 in definePropertiesGetter$argument_1.model
at node_modules/@bugsnag/plugin-expo-device/device.js:31:10 in module.exports.load
at node_modules/@bugsnag/core/client.js:162:19 in Client#_loadPlugin
at node_modules/@bugsnag/core/client.js:63:14 in map$argument_1
at node_modules/@bugsnag/core/lib/es-utils/map.js:5:54 in reduce$argument_1
at node_modules/@bugsnag/core/lib/es-utils/reduce.js:4:58 in module.exports
at node_modules/@bugsnag/core/lib/es-utils/map.js:5:8 in module.exports
at node_modules/@bugsnag/core/client.js:62:7 in Client#constructor
at node_modules/@bugsnag/expo/src/notifier.js:59:20 in Bugsnag.createClient
at node_modules/@bugsnag/expo/src/notifier.js:74:22 in Bugsnag.start
at src/utils/bugsnag.js:2:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at src/modals/ModalWhereToWatch/index.js:27:21 in ModalWhereToWatch#componentDidMount
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment
```
    "expo": "^43.0.2",
    "react-native": "0.64.3",
    "react": "17.0.1",
    "yarn": "^1.22.17"
```

### Reproducible demo

BugSnag is going to need to be updated otherwise it will not be usable with SDK 44 or 45.

**Comment by brentvatne** [comment]
we "undeprecated" `Constants.installationId` so will not be a problem. done in https://github.com/expo/expo/pull/15280

model will indeed be gone. same pr. if this ends up causing issues for you please report it to the bugsnag repository.
