### ISSUE TITLE
Expo upgrade SDK 44 Failed

### ISSUE THREAD

**Issue by ahmetbasdan** [expo/expo#15631]
### Summary

× Failed to install expo package with error: yarnpkg exited with non-zero code: 1

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 5.0.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1
      expo: ^43.0.0 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-43.tar.gz => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

yarnpkg exited with non-zero code: 1
Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\ahmet\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (C:\Users\ahmet\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\ahmet\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (C:\Users\ahmet\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:309:31)
    at YarnPackageManager.addAsync (C:\Users\ahmet\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:258:16)
    at upgradeAsync (C:\Users\ahmet\AppData\Roaming\npm\node_modules\expo-cli\src\commands\info\upgradeAsync.ts:496:7)
    at actionAsync (C:\Users\ahmet\AppData\Roaming\npm\node_modules\expo-cli\src\commands\info\upgradeAsync.ts:42:3)

**Comment by mariomurrent-softwaresolutions** [comment]
I just saw, that SDK43 was managed and when I switched to SDK44 it seems like it switched somehow to bare workflow.

**Comment by Aryk** [comment]
@ahmetbasdan Did you put `EXPO_BETA=1 ` like it said in the docs? Me too...got the same error...try without that

**Comment by brentvatne** [comment]
@Aryk - so you ran `EXPO_BETA=1 expo upgrade` after sdk 44 was fully released and got this error? it sounds like we need to account better for this if so

**Comment by Aryk** [comment]
That is correct. I for some reason missed the [official release page](https://blog.expo.dev/expo-sdk-44-4c4b8306584a) and tried to run it with that flag. Removing it fixed it.
