### ISSUE TITLE
[expo-yarn-workspaces] Not using metro.config.js when running app from XCode on device

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo#15765]
### Summary

When first running, I was seeing a problem where the main js file wasn't being found. This was fixed by prepending my folder (`mobile/`) to the URL:
```objc
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"mobile/index" fallbackResource:nil];
 #else
  return [[NSBundle mainBundle] URLForResource:@"mobile/main" withExtension:@"jsbundle"];
 #endif
}
```

However, now it's clear that the metro bundler isn't finding my metro.config.js, because I'm seeing an error where it can't resolve `@apollo/client` because it's not finding the `.cjs` file, which is fixed in my `metro.config.js` (also, the console log isn't being printed when running on device, only on simulator or Expo Go):
```js
const { createMetroConfiguration } = require('expo-yarn-workspaces')
const path = require('path')

const config = createMetroConfiguration(__dirname)

config.resolver.nodeModulesPath = [
  path.resolve(__dirname, 'node_modules'),
  path.resolve(__dirname, '..', 'node_modules'),
]

config.resolver.sourceExts.push('cjs')

console.log('Created Metro config', config)

module.exports = config
```

The specific error is:
```
Metro has encountered an error: While trying to resolve module `@apollo/client` from file `/Users/gsquare567/Sites/blogcast/mobile/App.tsx`, the package `/Users/gsquare567/Sites/blogcast/node_modules/@apollo/client/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/gsquare567/Sites/blogcast/node_modules/@apollo/client/main.cjs`. Indeed, none of these files exist:

  * /Users/gsquare567/Sites/blogcast/node_modules/@apollo/client/main.cjs(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/gsquare567/Sites/blogcast/node_modules/@apollo/client/main.cjs/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx): /Users/gsquare567/Sites/blogcast/node_modules/metro/src/node-haste/DependencyGraph.js (436:17)

  434 |
  435 |         if (error instanceof InvalidPackageError) {
> 436 |           throw new PackageResolutionError({
      |                 ^
  437 |             packageError: error,
  438 |             originModulePath: from,
  439 |             targetModuleName: to

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
338F58B1-9B75-38A0-B908-E2574AB1D39A
338F58B1-9B75-38A0-B908-E2574AB1D39A
CFRunLoopRunSpecific
GSEventRunModal
41D9BF62-8439-3B21-9959-4E27E75C294E
UIApplicationMain
main
FF7D2567-9277-3AA6-B3DD-2C5748E432A6
```

And without the modifications to `AppDelegate.m`, here is the complete XCode output:
```
2022-01-02 17:36:24.907195-0500 blogcast[8570:2310771] [connection] nw_endpoint_handler_set_adaptive_read_handler [C1 192.168.50.133:8081 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
2022-01-02 17:36:24.908505-0500 blogcast[8570:2310771] [connection] nw_endpoint_handler_set_adaptive_write_handler [C1 192.168.50.133:8081 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
2022-01-02 17:36:24.952048-0500 blogcast[8570:2310569] [native] Running application main ({
    initialProps =     {
    };
    rootTag = 1;
})
2022-01-02 17:36:24.974306-0500 blogcast[8570:2310772] [connection] nw_endpoint_handler_set_adaptive_read_handler [C2 192.168.50.133:8081 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
2022-01-02 17:36:24.974381-0500 blogcast[8570:2310772] [connection] nw_endpoint_handler_set_adaptive_write_handler [C2 192.168.50.133:8081 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
2022-01-02 17:36:25.021535-0500 blogcast[8570:2310569] [native] <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: EISDIR: illegal operation on a directory, read<br> &nbsp; &nbsp;at Object.readSync (fs.js:568:3)<br> &nbsp; &nbsp;at tryReadSync (fs.js:353:20)<br> &nbsp; &nbsp;at Object.readFileSync (fs.js:390:19)<br> &nbsp; &nbsp;at UnableToResolveError.buildCodeFrameMessage (/Users/gsquare567/Sites/blogcast/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)<br> &nbsp; &nbsp;at new UnableToResolveError (/Users/gsquare567/Sites/blogcast/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (/Users/gsquare567/Sites/blogcast/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (/Users/gsquare567/Sites/blogcast/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)<br> &nbsp; &nbsp;at /Users/gsquare567/Sites/blogcast/node_modules/metro/src/lib/transformHelpers.js:317:42<br> &nbsp; &nbsp;at /Users/gsquare567/Sites/blogcast/node_modules/metro/src/Server.js:1471:14<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)</pre>
</body>
</html>
````

How can you set up your Expo bare project with yarn workspaces to find the right `metro.config.js`, or even run from the right directory?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.22.7 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.11.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
        Build Tools: 19.1.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 28.0.2, 28.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.39.0
    Expo Workflow: bare

### Reproducible demo

1. Create Expo bare project within a package inside of a Yarn workspace
2. `yarn add @apollo/client` and import it to `App.tsx`
3. Set up `expo-yarn-workspaces`
4. Run on an iOS device from XCode (select the device and hit play)

**Comment by garrett-gottlieb** [comment]
The EISDIR issue was fixed by patching metro 0.64.
The bundle missing error was fixed by recreating the bundle in `ios/main.jsbundle` using `react-native bundle ...`.
The missing index file was fixed by adding `index.js` as a copy of `__generated__/AppEntry.js`.
I also added to Info.plist:
```
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
		<key>NSAllowsLocalNetworking</key>
		<true/>
```
Although it works when running from XCode, you can't include environment variables, so instead I use `MY_ENV_VAR=x expo run:ios --device ...`.
