### ISSUE TITLE
SDK 44 : React Native 0.64.3 is not exist 

### ISSUE THREAD

**Issue by hayukataishi** [expo/expo#15819]
I'm Japanese. I'm not good at English.

I want to upgrade expo sdk44,
> Warning: Invalid version react-native@0.63.4 for expo sdkVersion 44.0.0. Use react-native@0.64.3
> MacBook-Air:repo_main mac$ npx react-native upgrade 0.64.3
> info Fetching diff between v0.63.4 and v0.64.3...
> error Fetch request failed with status 404: 404: Not Found.
> error Failed to fetch diff for react-native@0.64.3. Maybe it's not released yet?
> info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#diff-table-full-table-here

not exists React Native 0.64.3 Release notes
https://github.com/facebook/react-native/releases?page=3

**Comment by byCedric** [comment]
Hi @hayukataishi!

You can find React Native 0.64.3 here:
- [react-native 0.64.3 on npm](https://www.npmjs.com/package/react-native/v/0.64.3)
- [react-native 0.64.3 tag on github](https://github.com/facebook/react-native/releases/tag/v0.64.3)

The error is telling you to upgrade from `0.63.4` to `0.64.3`. Open up `package.json` and update your React Native version to fix the issue :)
```json
  "react-native": "~0.64.3",
```

Hope this helps!

**Comment by hayukataishi** [comment]
@byCedric 
When I  install react-native, error occured.

MacBook-Air:repo_main mac$ expo install react-native
Installing 1 other package using Yarn.
> yarn add react-native@0.64.3
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "/Users/mac/Desktop/business/src/repo_main/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
**error An unexpected error occurred: "expected hoisted manifest for \"metro-react-native-babel-transformer#metro-react-native-babel-preset#@babel/core#@babel/helper-compilation-targets#browserslist\"".**
yarnpkg exited with non-zero code: 1
Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at Object.spawnAsync [as default] (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:309:31)
    at YarnPackageManager.addAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:258:16)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/installAsync.ts:125:3)
