### ISSUE TITLE
Execution failed for task ':app:bundleReleaseExpoAssets' 

### ISSUE THREAD

**Issue by pdlm95** [expo/expo#15961]
### Summary

Since yesterday I've been trying to build release apk and everytime I'm getting Execution failed for task ':app:bundleReleaseExpoAssets' in Android Studio. 
I don't know whats wrong since last week was working just fine and there's no dependency changes. Already run expo publish multiple times but nothing changed. I know that Expokit is deprecated and we're in the works to migrate to bare workflow, but we need to compile our app urgently. Please help

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

"dependencies": {
    "expo": "^36.0.0",
    "expo-device": "^2.0.0",
    "expokit": "^36.0.1",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-web": "^0.11.7",
    "react-native-webview": "^9.2.1",
    "react-native-unimodules": "^0.7.0",
     "metro-symlinked-deps": "^2.0.0",
     "jetifier": "^1.6.5",
},

### Environment

 Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
      react-navigation: ^4.0.9 => 4.1.1

### Reproducible demo

Happens everytime I want to build the release apk

### Stacktrace (if a crash is involved)

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:bundleReleaseExpoAssets'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'cmd'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:409)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
	at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)

**Comment by osimakoff** [comment]
We have been having the same issue and it happened right before our important Production launch.

Link to Expo forum - https://forums.expo.dev/t/production-build-cant-be-created/60917


Error:
_[20:02:17] Error: getaddrinfo ENOTFOUND assets
[20:02:17] Before making a release build, make sure you have run ‘expo publish’ at least once. Learn more. (​https://expo.fyi/release-builds-with-expo-updates​)

> Task :app:bundleReleaseExpoAssets FAILED

FAILURE: Build failed with an exception.

** What went wrong:*
Execution failed for task ‘:app:bundleReleaseExpoAssets’.
> Process ‘command ‘./node_modules/expokit/detach-scripts/run-exp.sh’’ finished with non-zero exit value 1

I noticed also resources were not added to the folder
android/app/build/intermediates/merged_assets/release/out_

**Comment by osimakoff** [comment]
@pdlm95 Damiel, have you found a solution.

We have tried a million ways and up to upgrading to sdk 38

Our setup:

    npmPackages:
      expo: ^38.0.0 => 38.0.11 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.3 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.5.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 4.1.3

**Comment by pdlm95** [comment]
@osimakoff No solution yet. We have the same setup.

I think they have removed all the legacy SDK versions. This is from their docs

https://docs.expo.dev/expokit/expokit/#android-1
https://expo.dev/--/api/v2/versions

**Comment by vivek751** [comment]
Please check this solution @pdlm95

**Comment by vivek751** [comment]
[Error_ getaddrinfo ENOTFOUND assets (1).pdf](https://github.com/expo/expo/files/7913162/Error_.getaddrinfo.ENOTFOUND.assets.1.pdf)

**Comment by pdlm95** [comment]
It worked for me! Didn't have to apply everything in the pdf though. The app.json and the metro.config.js parts along with copying the fonts into adroid/app/src/main/assets/fonts made the trick.

Thank you very much @vivek751 !

**Comment by creativemind1** [comment]
> [Error_ getaddrinfo ENOTFOUND assets (1).pdf](https://github.com/expo/expo/files/7913162/Error_.getaddrinfo.ENOTFOUND.assets.1.pdf)
![simulator_screenshot_25EC66B6-DF99-417C-B0F4-D4E740A4C02B](https://user-images.githubusercontent.com/5234185/150743942-0eb5d8b4-8d48-461d-bf73-652b40d2edb2.png)

@vivek751 In the pdf, you asked to remove `Font.Async`. After following your advice, it's asking to load fontFamily "Regular" to load System font

**Comment by vivek751** [comment]
@creativemind1  i already said that please follow postscript font name like Muli-Regular.. currently you are assign only variable name

**Comment by creativemind1** [comment]
I did but i'm getting same error for while building for `prod`

**Comment by vivek751** [comment]
@creativemind1  can you please share me 
assets/font screenshot 
IOS/Resource screenshot

also your js file any text css which are you using font-family

**Comment by anns-carveniche** [comment]
@vivek751  i tried the pdf still getting the error please check this 
<img width="794" alt="Screenshot 2022-02-02 at 10 36 47 PM" src="https://user-images.githubusercontent.com/48617381/152202164-d8ee2408-e013-4ecf-b802-2e6ac6a847a5.png">

**Comment by jeremiahlachica** [comment]
Having the same issue. Tried the pdf but still getting the error. We're not in the position to migrate to bare workflow as of the moment. If anyone has found a solution, please help. thanks a lot.

**Comment by pdlm95** [comment]
@jeremiahlachica have you tried to build the apk with gradle offline?

**Comment by jeremiahlachica** [comment]
@pdlm95 Haven't tried. Can you provide instructions or reference? thanks

**Comment by pdlm95** [comment]
@jeremiahlachica In Android Studio go to View > Tool Windows > Gradle from the menu bar. Then, near the top of the Gradle window, click Toggle Offline Mode Gradle offline button in the Gradle panel.

**Comment by jeremiahlachica** [comment]
@pdlm95  Thanks for your suggestion. It didn't work for me though. I get this error:
```
Could not resolve all artifacts for configuration ':classpath'.
   > Could not download build-scan-plugin.jar (com.gradle:build-scan-plugin:1.16): No cached version available for offline mode
```

I saw some article that we can build offline using some command:
`expo export --dev --public-url http://127.0.0.1:8000`

It did work for me. Now I'm trying to build an APK. Will give an update if this will work.

**Comment by anns-carveniche** [comment]
Had the same problem for me 
https://blog.expo.dev/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf
Followed the steps in the above and it worked for me

**Comment by anns-carveniche** [comment]
> Having the same issue. Tried the pdf but still getting the error. We're not in the position to migrate to bare workflow as of the moment. If anyone has found a solution, please help. thanks a lot.

@jeremiahlachica  pls check this 
https://blog.expo.dev/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf

**Comment by jeremiahlachica** [comment]
I was able to resolve the issue on my project. I posted the solution on StackOverflow. Here's the link:
https://stackoverflow.com/a/71061254/12799103

Hope this helps someone 🚀

**Comment by evertonalmeida16** [comment]
![image](https://user-images.githubusercontent.com/43793955/154086968-ccd1e8cd-5a13-46e4-bfa6-39160635a665.png)
Is this error common after making the pdf modifications? My application still didn't work even after following the steps in the file, did you make any changes to the metro.config.js file @pdlm95 ?

**Comment by pdlm95** [comment]
@evertonalmeida16 as I said, following the steps for app.json and metro.config.js solved the issue for me. And about the errors you're receiving, I didn't got those
