### ISSUE TITLE
Custom development client cannot connect to locally hosted files with expo export

### ISSUE THREAD

**Issue by Silvest89** [expo/expo#16064]
### Summary

I am trying to get my android and ios simulator dev client to connect to a server where I host my updates.
I execute this to get the static files
`expo export -c -p http://10.0.2.2/ --dev --output-dir local`

`python -m SimpleHTTPServer`

And then just simply use the client to connect to url/android-index.json

iOS works perfectly.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

```
"expo-dev-client": "~0.8.2",
"expo-updates": "~0.11.5",
```

Expo cli is at 5.0.3, 
Eas cli is at 0.45.1

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.14 Ubuntu 21.10 21.10 (Impish Indri)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 8.3.0 - /usr/bin/npm
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

This happens as well with a minimal project
`expo init my-app`
`expo install expo-dev-client`
`expo prebuild`
`expo export -c -p http://10.0.2.2:8000/ --dev --output-dir local`

`python -m SimpleHTTPServer`

`expo run:android --no-bundler`  // run it on simulator

### Stacktrace (if a crash is involved)

```
FATAL EXCEPTION: AsyncTask #13

Caused by: java.lang.IllegalArgumentException: Invalid URL port: "-1"

FATAL EXCEPTION: AsyncTask #13
Process: *hidden*, PID: 3618
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Invalid URL port: "-1"
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1394)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.Request$Builder.url(Request.java:165)
	at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.connect(InspectorPackagerConnection.java:249)
	at com.facebook.react.devsupport.InspectorPackagerConnection.connect(InspectorPackagerConnection.java:47)
	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:228)
	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:222)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
![Screenshot from 2022-01-25 21-15-38](https://user-images.githubusercontent.com/2388338/151053281-895b2e28-898d-4e5d-baef-b0d7c3ed8a6a.png)
![Screenshot from 2022-01-26 10-38-20](https://user-images.githubusercontent.com/2388338/151139251-e2cf2c5e-f283-436e-bed7-d7dade907e8f.png)

This is what I get

**Comment by lukmccall** [comment]
Hi @Silvest89, I think that your server has to return a response with certain headers. We firstly make a `HEAD` request to the provided URL to check what type of bundler we are dealing with. Here you have two options. For the `HEAD` request, you can try to respond with a non-successful status code or response with the following headers: 
- "Content-Type" has to be set to "application/json"
- "Exponent-Server" has to have some value (shouldn't matter what value)

Please, try and tell me if that helps.

**Comment by Silvest89** [comment]
@lukmccall 
I found that if you don't have a port set for your export 
`expo export -c -p http://10.0.2.2:80/ --dev --output-dir local` works

`expo export -c -p http://10.0.2.2/ --dev --output-dir local` does not work

It will throw the 

```
FATAL EXCEPTION: AsyncTask #13

Caused by: java.lang.IllegalArgumentException: Invalid URL port: "-1"

FATAL EXCEPTION: AsyncTask #13
Process: *hidden*, PID: 3618
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Invalid URL port: "-1"
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1394)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.Request$Builder.url(Request.java:165)
	at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.connect(InspectorPackagerConnection.java:249)
	at com.facebook.react.devsupport.InspectorPackagerConnection.connect(InspectorPackagerConnection.java:47)
	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:228)
	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:222)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```
That's the stacktrace for the doInBackground() error

**Comment by Silvest89** [comment]
@lukmccall 
Now my android does not want to connect even with returning headers for the HEAD request or a non succesful status code

![Screenshot from 2022-02-03 23-43-38](https://user-images.githubusercontent.com/2388338/152441698-fda20e3c-e3d8-4486-8283-0b9ffc6ab80b.png)

**Comment by lukmccall** [comment]
Could you share the codebase of your server part responsible for serving the update?

**Comment by Silvest89** [comment]
@Silvest89 
I just use a plain simple nginx docker image with the following config:

```
  location /  {
    expires -1;
    add_header Cache-Control no-store;
    if ($request_method = HEAD) {
      add_header Content-Type application/json;
      add_header Exponent-Server shiftbase;
      return 200 'gangnam style!';
    }
    try_files $uri /index.html;
  }


  location ~* \.(json|js)$ {
    expires -1;
    add_header Cache-Control no-store;
    if ($request_method = HEAD) {
      add_header Content-Type application/json;
      add_header Exponent-Server shiftbase;
      return 200 'gangnam style!';
    }
    try_files $uri /index.html;
  }
  ```

**Comment by Silvest89** [comment]
@lukmccall

**Comment by lukmccall** [comment]
We are still looking for a root cause of your problem :/
