### ISSUE TITLE
jest-expo-enzyme – requiring the proper enzyme-adapter during jest-enzyme setup failed

### ISSUE THREAD

**Issue by Bartozzz** [expo/expo#16086]
### Summary

When running unit tests w/ `jest`, `jest-expo` and `jest-expo-enzyme`, **the tests are passing** but I am getting the following annoying error on every test case:

```
    console.error
      
            Requiring the proper enzyme-adapter during jest-enzyme setup failed.
            This most likely happens when your application does not properly list the
            adapter in your devDependencies. Run this line to add the correct adapter:
      
            > yarn add --dev enzyme-adapter-react-16
      
            or with npm
            
            > npm i --save-dev enzyme-adapter-react-16
             ModuleNotFoundError: Cannot find module 'enzyme-adapter-react-16' from 'node_modules/jest-environment-enzyme/lib/setup.js'
          at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
          at Resolver._getVirtualMockPath (node_modules/jest-resolve/build/index.js:445:14)
          at Resolver._getAbsolutePath (node_modules/jest-resolve/build/index.js:431:14)
          at Resolver.getModuleID (node_modules/jest-resolve/build/index.js:404:31)
          at Runtime._shouldMock (node_modules/jest-runtime/build/index.js:1521:37)
          at Runtime.requireModuleOrMock (node_modules/jest-runtime/build/index.js:916:16)
          at exposeGlobals (node_modules/jest-environment-enzyme/lib/setup.js:39:15)
          at Object.<anonymous> (node_modules/jest-enzyme/lib/index.js:23:3)
          at Runtime._execModule (node_modules/jest-runtime/build/index.js:1299:24)
          at Runtime._loadModule (node_modules/jest-runtime/build/index.js:898:12) {
        code: 'MODULE_NOT_FOUND',
        hint: '',
        requireStack: undefined,
        siblingWithSimilarExtensionFound: false,
        moduleName: 'enzyme-adapter-react-16',
        _originalMessage: "Cannot find module 'enzyme-adapter-react-16' from 'node_modules/jest-environment-enzyme/lib/setup.js'"
      }
```

I use Expo 44 (React `17.0.1`) and cannot install `enzyme-adapter-react-16` because its peer dependency is React v16. From what I saw, `jest-expo-enzyme` uses `@wojtekmaj/enzyme-adapter-react-17`. I tried adding it to my `devDependencies` but no luck, the same error shows up.

Is there any way to get rid of this?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

44

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

`package.json`:

```json
{
  "devDependencies": {
    "@wojtekmaj/enzyme-adapter-react-17": "^0.6.6",
    "jest": "^26.6.3",
    "jest-expo": "^44.0.0",
    "jest-expo-enzyme": "1.2.5"
  }
}
```

`jest.config.js`:

```js
const { withEnzyme } = require("jest-expo-enzyme");

module.exports = {
  projects: [
    withEnzyme(require("jest-expo/ios/jest-preset")),
    withEnzyme(require("jest-expo/android/jest-preset")),
  ],
};
```

Running tests with:

```sh
$ npx jest
```

**Comment by Shizerq** [comment]
Hi,
I found the cause of this issue.

Enzyme uses a package called `jest-environment-enzyme` [which supports Enzyme adapters up to React 16](https://github.com/enzymejs/enzyme-matchers/blob/master/packages/jest-environment-enzyme/src/setup.js). 

Someone [created a PR with unofficial adapter,](https://github.com/enzymejs/enzyme-matchers/pull/357) but a member of Enzyme closed it saying that they won't use any unofficial adapters.  

It's really up to them right now, [here's the issue about support for React 17.](https://github.com/enzymejs/enzyme/issues/2429), it looks pretty dead though.
