### ISSUE TITLE
[expo-camera] [Android] Random ratio error

### ISSUE THREAD

**Issue by DCKT** [expo/expo#16292]
### Summary

Hello, 

This error occures randomly on Android devices. Even with `getSupportedRatiosAsync`.
That can occures on Android 9/10/11.

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.SortedSet.last()' on a null object reference
    at com.google.android.cameraview.Camera2.setAspectRatio(Camera2.java:402)
    at com.google.android.cameraview.Camera2.start(Camera2.java:282)
    at com.google.android.cameraview.CameraView.start(CameraView.java:284)
    at expo.modules.camera.ExpoCameraView.onHostResume(ExpoCameraView.java:299)
    at expo.modules.adapters.react.services.UIManagerModuleWrapper$3.onHostResume(UIManagerModuleWrapper.java:127)
    at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:200)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8031)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-6123857/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-6123857/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.3 => 44.0.3 
      react: 17.0.2 => 17.0.1 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

[Here a repo with my camera solution](https://github.com/DCKT/expo-camera-bug) (my original codebase is in ReScript sorry for that)
We didn't manage to reproduce this at my company.

[The main part is located here I guess](https://github.com/DCKT/expo-camera-bug/blob/main/src/Camera.res#L119). I tried a trick seems on another issue with `getAvailablePictureSizesAsync ` but it didn't works.

**Comment by RodrigoAWeber** [comment]
The problema still occurs in expo 44

**Comment by lamualfa** [comment]
The problem still occurs on expo 50 and expo-camera 14.1.1.
