### ISSUE TITLE
[expo-store-review] Promise rejection is called in the wrong way for StoreReviewModule

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#16363]
### Summary

Take a look at the `StoreReviewModuel.kt`line number 50:

` promise.resolve(null)`

According to the Promise implementation in `expo.modules.core.Promise` the reject method accepts a `Throwable`.
If the parameter is not of type `CodedThrowable`the default `reject`method will be used, which is:

`  default void reject(String code, Throwable e) {
    reject(code, e.getMessage(), e);
  }`

So if you call `promise.resolve(null)` then `e.getMessage` will trigger an error and the app crashes.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

44.0.6

### Environment

 expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/npm
      Watchman: 2022.01.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 26, 27, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ~44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.5
    Expo Workflow: managed

### Reproducible demo

- Use the StoreReview Module on and Android device without GooglePlayStore installed
- Trigger the a store review
- Is available delivers true
- Request review delivers and error and app crashes

Log output from simulator:

`02-17 15:55:55.147 17927 17927 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
02-17 15:55:55.147 17927 17927 E AndroidRuntime:        at expo.modules.core.Promise$-CC.$default$reject(Promise.java:27)
02-17 15:55:55.147 17927 17927 E AndroidRuntime:        at expo.modules.adapters.react.PromiseWrapper.reject(Unknown Source:0)
02-17 15:55:55.147 17927 17927 E AndroidRuntime:        at expo.modules.core.Promise$-CC.$default$reject(Promise.java:18)
02-17 15:55:55.147 17927 17927 E AndroidRuntime:        at expo.modules.adapters.react.PromiseWrapper.reject(Unknown Source:0)
02-17 15:55:55.147 17927 17927 E AndroidRuntime:        at expo.modules.storereview.StoreReviewModule$requestReview$1.onComplete(StoreReviewModule.kt:56)
02-17 15:55:55.147 17927 17927 E AndroidRuntime:        at com.google.android.play.core.tasks.a.run(Unknown Source:23)`

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this?

**Comment by mariomurrent-softwaresolutions** [comment]
#16365 still in progress

**Comment by mariomurrent-softwaresolutions** [comment]
https://github.com/expo/expo/pull/16365 is already merged so this issue can be closed

**Comment by mariomurrent-softwaresolutions** [comment]
Already fixed
