### ISSUE TITLE
expo-camera with barcode reading enabled on Google Play Store prelaunch tests crashes: java.lang.IllegalArgumentException: Scan output cannot be null

### ISSUE THREAD

**Issue by FrancescoBonizzi** [expo/expo#16867]
### Summary

If you use expo-camera with barcode reading enabled and then you create a release on Google Play Store, it does all prelaunch tests and reports a crash: `java.lang.IllegalArgumentException: Scan output cannot be null`.

It's clear from their videos that this happens when the page with the camera (with barcode scan enabled) is opened.
I also read that this problem was solved with `expo-barcode-scanner`, but it seems it doesn't with `expo-camera`.

Full stack trace:

```
FATAL EXCEPTION: AsyncTask #1
Process: com.myapp.myapp, PID: 10550
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: Scan output cannot be null
	at expo.modules.barcodescanner.scanners.ZxingBarCodeScanner.scan(ZxingBarCodeScanner.kt:56)
	at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:36)
	at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:6)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.5

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2021.12.13.00 - /opt/homebrew/bin/watchman
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.48.1
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo

```
const BarcodeScanPage = (props: Props) => {
    const [hasCameraPermission, setHasCameraPermission] = React.useState<boolean | null>(null);
    const [scanned, setScanned] = React.useState<boolean>(false);

    useEffect(() => {
        (async () => {
            await requestCameraPermissionAsync();
        })();
    }, []);

    const isFocused = useIsFocused();

    // Run when the focused page changes (ie: navigatedTo, navigatedFrom)
    React.useLayoutEffect(() => {
        (async () => {

            const onPageOpenedUnsubscribe = props.navigation.addListener('focus', () => {
                setScanned(false);
            });

            // Return the function to unsubscribe from the event so it gets removed on unmount
            return onPageOpenedUnsubscribe;
        })();
    }, []);

    const requestCameraPermissionAsync = async () => {
        const { status } = await Camera.requestCameraPermissionsAsync();
        setHasCameraPermission(status === 'granted');
    };

    const handleBarCodeScanned = (params: BarCodeScanningResult) => {
        // Do something with the scanned EAN
    };

    if (hasCameraPermission === null) {
        return (
            <View style={styles.screenNoPermissions}>
                <EmptyPageText text='Requesting permission...' />
            </View>
        );
    }

    if (hasCameraPermission === false) {
        return (
            <View style={styles.screenNoPermissions}>
                <EmptyPageText text='Permission not granted' />
            </View>
        );
    }

    return (
        <View>
            {isFocused && (
                <Camera
                    onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
                    style={[StyleSheet.absoluteFillObject, styles.barcodeBox]}>
                    <View style={styles.barcodeCenterBorder} />
                </Camera>
            )}
        </View>
    );
};
```

**Comment by fantasyado** [comment]
We run into the same issue

**Comment by leeleoo** [comment]
same problem on android 9
