### ISSUE TITLE
Crash on android with Expo dev client and Facebook auth session

### ISSUE THREAD

**Issue by ScreamZ** [expo/expo#17011]
### Summary

Hello,

I have the following setup, this works well on IOS with the dev client.
On android, It crashes after accepting permissions in the modal, I got a white screen in the modal then crash with the following log. (see below)

I'm on managed workflow, apk built with `eas build --profile development --local` for Android platform.

No issue with Expo GO

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

```json
{
"expo": "~44.0.0",
"expo-app-loading": "~1.3.0",
"expo-auth-session": "~3.5.0",
"expo-constants": "~13.0.1",
"expo-dev-client": "~0.8.4",
"expo-random": "~12.1.1",
"expo-status-bar": "~1.2.0",
"expo-updates": "~0.11.6"
}
```
### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
      Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
      npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 26, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed
```

### Reproducible demo

```tsx
import React from "react";
import { SafeAreaView } from "react-native-safe-area-context";
import { Text, Image, Vie, Button } from "react-native";
import * as Facebook from "expo-auth-session/providers/facebook";
import * as WebBrowser from "expo-web-browser";

WebBrowser.maybeCompleteAuthSession();

export const HomeScreen: React.FC = () => {
  const [request, response, prompt] = Facebook.useAuthRequest({
    clientId: "<YOUR ID>", // Also ensure you have scheme and facebookScheme defined in app.json
  });

// Expecting to have response with good values

  return (
    <SafeAreaViewstyle={{flex:1}}>
          <Button onPress={() => prompt()} title="Login with FB" />
    </SafeAreaView>
  );
};
```

### Stacktrace (if a crash is involved)

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.CustomTabActivity" on path: DexPathList[[zip file "/data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/lib/arm64, /data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]

FATAL EXCEPTION: main
Process: io.codingspark.jerry, PID: 9515
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.codingspark.jerry/com.facebook.CustomTabActivity}: java.lang.ClassNotFoundException: Didn't find class "com.facebook.CustomTabActivity" on path: DexPathList[[zip file "/data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/lib/arm64, /data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.CustomTabActivity" on path: DexPathList[[zip file "/data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/lib/arm64, /data/app/io.codingspark.jerry-gvoJME3Itse7tM4n3d2lEQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1262)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
	... 11 more
```

**Comment by PeterAbdalla** [comment]
Facing same issue

**Comment by otaviogaiao** [comment]
I'm facing the same issue

**Comment by ick56** [comment]
Facing same issue

**Comment by mgretz** [comment]
i have the same issue

**Comment by ScreamZ** [comment]
@brentvatne Can you have a look at it please ? Seems a core feature and a core library of expo ? Thanks :-)

**Comment by brentvatne** [comment]
@ScreamZ - can you share an example app that we can clone and run?

**Comment by offminded** [comment]
I have removed com.facebook.CustomTabActivity via android-manifest.plugin.js 

```
const { AndroidConfig, withAndroidManifest } = require('@expo/config-plugins')

module.exports = function withCustomConfig(config) {
	return withAndroidManifest(config, async (config) => {
		config.modResults.manifest.application[0].activity =
			config.modResults.manifest.application[0].activity.filter(
				(item) => item.$['android:name'] !== 'com.facebook.CustomTabActivity'
			)
		return config
	})
}
```

There are some discussions about the issue here if you are interested:
[(https://github.com/expo/expo/issues/9917)]
