### ISSUE TITLE
Tests are failing with SDK 27

### ISSUE THREAD

**Issue by MainAero** [expo/expo#1705]
Tests are failing with sdk 27 even in the example project.
  
### Environment
```bash
Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2
```
### Steps to Reproduce

(Write your steps here:)

1. `exp init test`
2. Chose tab layout
3. `cd test`
4. `npm install`
5. `npm test`

### Expected Behavior

Test should run fine.

### Actual Behavior

Actual test output:
```bash
PASS  components/__tests__/StyledText-test.js

RUNS  __tests__/App-test.js

Test Suites: 1 passed, 1 of 2 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        3s/app/test/node_modules/react-native/Libraries/Interaction/TaskQueue.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){'use strict';var _extends=Object.assign||function(target){for(var i=1;i<arguments.length;i++){var source=arguments[i];for(var key in source){if(Object.prototype.hasOwnProperty.call(source,key)){target[key]=source[key];}}}return target;};var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();function _classCallCheck(instance,Constructor){if(!(instance instanceof Construc

TypeError: TaskQueue: Error with task : Cannot read property 'Object.<anonymous>' of null
   at Runtime._execModule (/app/test/node_modules/jest-runtime/build/index.js:447:72)
   at Runtime.requireModule (/app/test/node_modules/jest-runtime/build/index.js:265:14)
   at Runtime.requireModuleOrMock (/app/test/node_modules/jest-runtime/build/index.js:337:19)
   at parseErrorStack (/app/test/node_modules/react-native/Libraries/Core/Devtools/parseErrorStack.js:1:179)
   at updateWarningMap (/app/test/node_modules/react-native/Libraries/ReactNative/YellowBox.js:1:3858)
   at BufferedConsole.Object.<anonymous>.console.warn (/app/test/node_modules/react-native/Libraries/ReactNative/YellowBox.js:1:2598)
   at Component.measureInWindow (/app/test/node_modules/react-native/jest/setup.js:1:2534)
   at SafeView._this._onLayout (/app/test/node_modules/react-native
RUNS  __tests__/App-test.js

Test Suites: 1 passed, 1 of 2 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        5s
```

Not sure if it's a expo related bug. After upgrading my project from sdk 26 to 27 it appears.

**Comment by esamelson** [comment]
@ide - any idea what's going on here?

**Comment by ide** [comment]
Not sure what it is off the top of my head. Jest internals often take time to look into so if someone wants to forge ahead they might find a solution before I look into this.

**Comment by MainAero** [comment]
The tests are failing (or running forever) when a console warn message occurs. Which is the case in the example project:
```bash
console.warn node_modules/react-native/Libraries/ReactNative/YellowBox.js:85
      Calling .measureInWindow() in the test renderer environment is not supported. Instead, mock out your components that use findNodeHandle with replacements that don't rely on the native environment.
```

This will trigger a call to `parseErrorStack()` a react-native devtools library method. Inside this method a other module is required. The [require](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/parseErrorStack.js#L30) call is done after torn down of jest which will lead to the unexpected behavior of jest.

My workaround for now is to add `require('stacktrace-parser');` to my own `setupJest.js` file:

package.json:
```json
...
"jest": {
    "preset": "jest-expo",
    "setupTestFrameworkScriptFile": "./setupJest"
},
...
```

setupJest.js:
```js
require('stacktrace-parser');
...
```

I will investigate further how to get a serious fix for that.

**Comment by renefs** [comment]
Same problem here. The following line makes the tests fail:
```javascript
import { Constants } from 'expo'
````
Dependencies:
```json
"devDependencies": {
    "react-native-scripts": "1.14.0",
    "jest-expo": "~27.0.0",
    "react-test-renderer": "16.3.1"
  },
  "dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2"
  }
```

Above solution worked to fix it temporally, as well as downgrading expo and jest-expo to 26

**Comment by brunohkbx** [comment]
@MainAero did you found a fix for that?

**Comment by brunohkbx** [comment]
@MainAero have you found a fix for that?

**Comment by brunohkbx** [comment]
@ide ?

**Comment by ide** [comment]
@brunohkbx I don't have any updates on this.

**Comment by mazmrini** [comment]
@MainAero anything new ?

**Comment by ide** [comment]
The original repro commands with the current version of Expo (SDK 35) work now:

```
expo init test
# follow setup instructions. i used yarn instead of npm.
cd test
yarn test
# tests pass
```

![tests](https://user-images.githubusercontent.com/379606/68708132-ee79d480-0547-11ea-8ce8-5226a590d2d8.png)
