### ISSUE TITLE
textinput crash sdk44 expo go app

### ISSUE THREAD

**Issue by superyarik** [expo/expo#17335]
### Summary

when in start screen textInput present - have this error in expo go app.
builded standalone version worked great.

found this issue in RN
https://github.com/facebook/react-native/issues/31572
how it can be fixed in expo go app?

```
2022-05-04 16:58:55.070 9131-9131/? E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean abi44_0_0.com.facebook.react.uimanager.FabricViewStateManager.hasStateWrapper()' on a null object reference
        at abi44_0_0.com.facebook.react.views.textinput.ReactEditText.updateCachedSpannable(ReactEditText.java:1)
        at abi44_0_0.com.facebook.react.views.textinput.ReactEditText.access$300(ReactEditText.java:1)
        at abi44_0_0.com.facebook.react.views.textinput.ReactEditText$TextWatcherDelegator.onTextChanged(ReactEditText.java:5)
        at android.widget.TextView.sendOnTextChanged(TextView.java:10578)
        at android.widget.TextView.setText(TextView.java:6314)
        at android.widget.TextView.setText(TextView.java:6139)
        at android.widget.EditText.setText(EditText.java:121)
        at android.widget.TextView.setText(TextView.java:6091)
        at android.widget.TextView.setEditableFactory(TextView.java:6048)
        at s4.a$a.<init>(EmojiEditTextHelper.java:5)
        at s4.a.<init>(EmojiEditTextHelper.java:5)
        at androidx.appcompat.widget.m.<init>(AppCompatEmojiEditTextHelper.java:3)
        at androidx.appcompat.widget.l.<init>(AppCompatEditText.java:12)
        at androidx.appcompat.widget.l.<init>(AppCompatEditText.java:2)
        at androidx.appcompat.widget.l.<init>(AppCompatEditText.java:1)
        at abi44_0_0.com.facebook.react.views.textinput.ReactEditText.<init>(ReactEditText.java:1)
        at abi44_0_0.com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:2)
        at abi44_0_0.com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:1)
        at abi44_0_0.com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:1)
        at abi44_0_0.com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:2)
        at abi44_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:4)
        at abi44_0_0.com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
        at abi44_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:9)
        at abi44_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:4)
        at abi44_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
        at abi44_0_0.com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
        at abi44_0_0.com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

![telegram-cloud-photo-size-2-5447436652675972184-y](https://user-images.githubusercontent.com/1265590/166703449-672a0ee5-25fc-480f-a084-e881e2022ef8.jpg)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.10.04.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-navigation: 4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

.

**Comment by superyarik** [comment]
also https://github.com/microsoft/react-native-test-app/pull/643/files

**Comment by thanhlieng** [comment]
same problem here on my  SamSung M52 but work fine on my Xiaomi redmi note 7 and emulator Pixel 3a

**Comment by IMSBuSu** [comment]
I am facing this issue new EXPO Apk update. it is working fine in the old expo version.

**Comment by brentvatne** [comment]
@IMSBuSu - please refer to https://github.com/expo/expo/issues/17372#issuecomment-1119866941 for a workaround while we work to resolve this issue in the latest version of Expo Go
