### ISSUE TITLE
expo start failed after SDK 45 upgrade - expo-keep-awake function could not be cloned

### ISSUE THREAD

**Issue by TeChn4K** [expo/expo#17427]
### Summary

`expo start` failed systematically after upgrading to SDK 45.

```
node_modules/expo-keep-awake/build/index.js: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.
Error: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.
    at Object.serialize (node:v8:333:7)
    at _default (/home/me/project/node_modules/@babel/core/lib/transformation/util/clone-deep.js:22:34)
    at normalizeFile (/home/me/project/node_modules/@babel/core/lib/transformation/normalize-file.js:84:36)
    at normalizeFile.next (<anonymous>)
    at run (/home/me/project/node_modules/@babel/core/lib/transformation/index.js:31:50)
    at run.next (<anonymous>)
    at /home/me/project/node_modules/@babel/core/lib/transform-ast.js:26:41
    at Generator.next (<anonymous>)
    at evaluateSync (/home/me/project/node_modules/gensync/index.js:251:28)
```

Note that I do not use `expo-keep-awake` directly, it is not linked in my package.json

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/bin/node
      Yarn: 1.22.18 - /usr/bin/yarn
      npm: 8.7.0 - /usr/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.2 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Reproducible demo

None

**Comment by seedalri** [comment]
It seems I have the same problem here. Updated to Expo 45 (from 37) and now I get this error.

iOS Bundling failed 113ms
node_modules/expo-keep-awake/build/index.js: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.
Error: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.
    at Object.serialize (v8.js:249:7)
    at _default (/Users/user/project/node_modules/@babel/core/lib/transformation/util/clone-deep.js:22:34)
    at normalizeFile (/Users/user/project/node_modules/@babel/core/lib/transformation/normalize-file.js:84:36)
    at normalizeFile.next (<anonymous>)
    at run (/Users/user/project/node_modules/@babel/core/lib/transformation/index.js:31:50)
    at run.next (<anonymous>)
    at /Users/user/project/node_modules/@babel/core/lib/transform-ast.js:26:41
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/user/project/node_modules/gensync/index.js:251:28)

**Comment by TeChn4K** [comment]
@Simek How I am supposed to create a SDK 45 Snack ?
@seedalri thanks, exactly same issue as me

**Comment by efraindev117** [comment]
Alguien pudo resolver este problema?  actualice expo de 35 a 45....
node_modules\expo-keep-awake\build\index.js: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.

**Comment by alirasheedmd** [comment]
I am facing same issue any solution

**Comment by manumid** [comment]
Facing the same problem as well

**Comment by wyknmjj** [comment]
Facing the same problem as well

for this project https://github.com/Doha26/Instagram-clone/

**Comment by randiekas** [comment]
i have same issue after upgrade to sdk 45. this way is really work for me 


- delete yarn.lock
- delete forder node_modules
- yarn install

**Comment by gabriel-envoi** [comment]
Same problem on PopOS. I can run my expo project on a MAC, but not on PopOS anymore.
