### ISSUE TITLE
expo-location crashes with Unable to resume activity

### ISSUE THREAD

**Issue by edi** [expo/expo#17426]
### Summary

https://forums.expo.dev/t/unable-to-resume-activity/63114

I've decided to create this here, hoping for some kind of answer, since the expo forums are a no-go, most of the time.

The bug is surely with the expo-location module, and not with the app, since there are multiple users having the same issue, and the crash occurs thousands of times on our customer's devices, as we have about ~50K devices with the app installed, so it affects quite a lot of people.

I've tried describing it into the forum thread, so I'm not sure if I should paste it here as well, but as a summary, this seems to happen when you leave the app in the background during the night, and open it in the morning, since it mostly occurs during the morning, as another developer mentioned on the forum.

```
Caused by java.lang.NullPointerException
       at java.util.Objects.requireNonNull(Objects.java:220)
       at expo.modules.location.LocationModule.handleForegroundLocationPermissions(LocationModule.java:839)
       at expo.modules.location.LocationModule.lambda$requestForegroundPermissionsAsync$2$LocationModule(LocationModule.java:195)
       at expo.modules.location.-$$Lambda$LocationModule$D--6Q7JrlKjA_yBo0ZZZH8hwBGk.onResult(:4)
       at org.unimodules.adapters.react.permissions.PermissionsService$createListenerWithPendingPermissionsRequest$1.onRequestPermissionsResult(PermissionsService.kt:255)
       at com.facebook.react.ReactActivityDelegate$2.invoke(ReactActivityDelegate.java:171)
       at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:102)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44 and 45

### Environment

This is applicable to all devices .. not environment dependent

### Reproducible demo

It's hard to reproduce, but the stack traces from all the users mentioning the issue I guess should be enough.

**Comment by byCedric** [comment]
> `at org.unimodules.adapters.react.permissions...`

This indicates that you still have `react-native-unimodules` installed. This is deprecated since October 2021, [see npm](https://www.npmjs.com/package/react-native-unimodules). You can check if you have this installed in your project somewhere with:

- `$ yarn why react-native-unimodules`
- `$ npm list react-native-unimodules`

Please make sure that this is not within your project.

**Comment by edi** [comment]
@byCedric I don't seem to have it installed anywhere in the project.

```
edi@MBP byspark % npm list react-native-unimodules
BySpark@ /Users/edi/Desktop/BySpark
└── (empty)
```

Here's one of my crash logs, as the one I pasted was from the last guy who replied to my thread on the forum, as I assumed it's the same.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4638)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4670)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2253)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:245)
  at android.app.ActivityThread.main (ActivityThread.java:8024)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:631)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:978)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at expo.modules.ReactActivityDelegateWrapper.invokeDelegateMethod (ReactActivityDelegateWrapper.kt:166)
  at expo.modules.ReactActivityDelegateWrapper.onResume (ReactActivityDelegateWrapper.kt:82)
  at com.facebook.react.ReactActivity.onResume (ReactActivity.java:58)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1571)
  at android.app.Activity.performResume (Activity.java:8141)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4628)
Caused by: java.lang.NullPointerException: 
  at java.util.Objects.requireNonNull (Objects.java:220)
  at expo.modules.location.LocationModule.handleForegroundLocationPermissions (LocationModule.java:839)
  at expo.modules.location.LocationModule.lambda$requestForegroundPermissionsAsync$2$LocationModule (LocationModule.java:195)
  at expo.modules.location.-$$Lambda$LocationModule$BTuImArYyLs9EqpIXxluCGJIymU.onResult (Unknown Source:4)
  at expo.modules.adapters.react.permissions.PermissionsService$createListenerWithPendingPermissionsRequest$1.onRequestPermissionsResult (PermissionsService.kt:271)
  at com.facebook.react.ReactActivityDelegate$2.invoke (ReactActivityDelegate.java:178)
  at com.facebook.react.ReactActivityDelegate.onResume (ReactActivityDelegate.java:103)
```

**Comment by edi** [comment]
Any updates on this one? Has someone managed to look into it?

**Comment by edi** [comment]
Let's see what @byCedric comes up with. I gather it can't be that hard to fix, since it's just a graceful failure to implement. But then I may be worng, since I have no experience with native code on Android's end.

**Comment by endruuu** [comment]
In my case, it happened after user reopened the app (after being backgrounded before, hence activity resumes ) and the app immediately called `requestForegroundPermissionsAsync()` function.
My workaround was to add a delay before calling that function, e.g. 2 seconds.

**Comment by edi** [comment]
@endruuu I cannot do anything about that because this method is called by the `react-native-maps` screen, when you bring the app to foreground. I can't do much about it there, so there must be a more graceful way to avoid a simple crash, directly in the native code from within Expo.

**Comment by MorganTrudeau** [comment]
I can't reproduce this myself using any android device I own. If someone has some reproduction steps that would be great.
 
In my app I am not calling requestForegroundPermissionsAsync() on any app start, but I am calling getForegroundPermissionsAsync(). @kevinbraun mentioned switching to getForegroundPermissionsAsync() fixed his issue, but it seems that must be the root of my issue.

**Comment by jonrh** [comment]
Been getting this native crash as well. Seems to be originating from `handleForegroundLocationPermissions()` after a Android devices resumes activity in rare cases.

```java
 private Bundle handleForegroundLocationPermissions(Map<String, PermissionsResponse> result) {
    PermissionsResponse accessFineLocation = result.get(Manifest.permission.ACCESS_FINE_LOCATION);
    PermissionsResponse accessCoarseLocation = result.get(Manifest.permission.ACCESS_COARSE_LOCATION);
    Objects.requireNonNull(accessFineLocation); 
    Objects.requireNonNull(accessCoarseLocation);
    
    // ... rest of function
}
```

The problem might be in line [844](https://github.com/expo/expo/blob/759bc6940172782fd978ed2f8a85faaa6a488fdc/packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java#L844) and [845](https://github.com/expo/expo/blob/759bc6940172782fd978ed2f8a85faaa6a488fdc/packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java#L845), `Objects.requireNonNull(accessFineLocation);`. According to the Java documentation the function `Objects.requireNonNull(obj)` returns `obj` if not `null`, otherwise it throws a `NullPointerException`. From a glance it seems the exception is never caught nor handled when `accessFineLocation` and `accessCoarseLocation` are potentially `null`.

Not sure what the best course of action would be in the case of a `null`. Maybe return that the permissions were declined. The change seems to have been added in commit 827cc93aa1d5de1c6d2f72dc47faac590f30f4ba in the PR #12063 by @lukmccall (tagging in case there are additional context/insights).

**Comment by TitanShala** [comment]
> In my case, it happened after user reopened the app (after being backgrounded before, hence activity resumes ) and the app immediately called `requestForegroundPermissionsAsync()` function. My workaround was to add a delay before calling that function, e.g. 2 seconds.

Soo you did a sleep function with the setTimeOut to prevent that error ?

**Comment by endruuu** [comment]
> Soo you did a sleep function with the setTimeOut to prevent that error ?

Yes, something like this
```
setTimeout(async () => {
    const { status } = await Location.requestForegroundPermissionsAsync();
    // ...
}, 2000);
```

**Comment by jayshah123** [comment]
This is how to reproduce this issue -> request location permission  -> Do not wait for dialog -> press home -> press lock screen -> Unlock the lock screen -> open app from launcher.

**Comment by jayshah123** [comment]
Expo devs, it looks like expected behavior sometimes as per android OS docs, you can see it [here](https://developer.android.com/reference/androidx/core/app/ActivityCompat.OnRequestPermissionsResultCallback#onRequestPermissionsResult(int,java.lang.String[],int[])).
I think we can remove extra strict null checks as it is expected OS behavior, and have some gracefule degraded behavior.

**Comment by jayshah123** [comment]
Temporary patch that works for now:
```
diff --git a/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java b/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java
index 9a66033..14cfa41 100644
--- a/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java
+++ b/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java
@@ -841,6 +841,16 @@ public class LocationModule extends ExportedModule implements LifecycleEventList
   private Bundle handleForegroundLocationPermissions(Map<String, PermissionsResponse> result) {
     PermissionsResponse accessFineLocation = result.get(Manifest.permission.ACCESS_FINE_LOCATION);
     PermissionsResponse accessCoarseLocation = result.get(Manifest.permission.ACCESS_COARSE_LOCATION);
+    /**
+     * Missing permissions from OS callback should be considered as denied permissions
+     */
+    if(accessFineLocation == null) {
+      accessFineLocation = new PermissionsResponse(PermissionsStatus.DENIED, true);
+    }
+    if(accessCoarseLocation == null) {
+      accessCoarseLocation = new PermissionsResponse(PermissionsStatus.DENIED, true);
+    }
+
     Objects.requireNonNull(accessFineLocation);
     Objects.requireNonNull(accessCoarseLocation);
```

**Comment by forki** [comment]
@jayshah123 are you sending this as pull request?

**Comment by jayshah123** [comment]
Let me raise a PR. Will do by EOD

**Comment by forki** [comment]
The part with 

      Objects.requireNonNull(accessFineLocation);
      Objects.requireNonNull(accessCoarseLocation);

could be removed then

**Comment by forki** [comment]
@jayshah123 I can do it if you don't have time

**Comment by jayshah123** [comment]
some personal emergency has come up. thanks if u can use patch i mentioned in comments.

**Comment by edi** [comment]
Great thing this got fixed!

**Comment by Pjexaf** [comment]
So in which SDK the fix included?

**Comment by jonrh** [comment]
> So in which SDK the fix is included?

Expo v48.
