### ISSUE TITLE
Error when calling eas build -p ios

### ISSUE THREAD

**Issue by ushyDev** [expo/expo#17465]
### Summary

When i want to build app with `eas build -p ios` and login to Apple account i have this error:
`Authentication with Apple Developer Portal failed!
    Error: Apple Service Error -1018. Could Not Complete Request. Your request could not be completed because of an 
    error. Please try again later. Apple servers may be down right now, please try again in about 10-20 minutes`

I have all agreements accepted on my appla developer account.

### SDK Version

44

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: 4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.0
    Expo Workflow: bare
```

### Reproducible demo

```
> eas build -p ios
If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … uszackip@gmail.com
› Using password for uszackip@gmail.com from your local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✖ Logging in...
Authentication with Apple Developer Portal failed!
    Error: Apple Service Error -1018. Could Not Complete Request. Your request could not be completed because of an 
    error. Please try again later. Apple servers may be down right now, please try again in about 10-20 minutes
    at assertServiceErrors (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:881374)
    at attemptLoginRequestAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:880939)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.loginWithUserCredentialsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:879421)
    at loginWithUserCredentialsAsync (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:133:22)
    at loginAsync (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)
    at Context.ensureAppleCtx (/usr/local/lib/node_modules/expo-cli/src/credentials/context.ts:83:24)
    at IOSBuilder.bestEffortAppleCtx (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:95:14)
    at IOSBuilder.prepareCredentials (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:151:5)

```

**Comment by brentvatne** [comment]
@ushyDev - can you try running `EXPO_NO_KEYCHAIN=1 EXPO_APP_STORE_DEBUG=1 npx @expo/apple-utils login` and share the output please?

**Comment by ushyDev** [comment]
`EXPO_NO_KEYCHAIN=1 EXPO_APP_STORE_DEBUG=1 npx @expo/apple-utils login`

This command helped me!
Thank you 💪

**Comment by alkunde** [comment]
for me not.
Skip storing Apple ID password in the local Keychain.
⠋ Logging in...GET https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42
⠏ Logging in...200  (GET https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42)
⠋ Logging in...POST https://idmsa.apple.com/appleauth/auth/signin/init
⠸ Logging in...200  (POST https://idmsa.apple.com/appleauth/auth/signin/init)
POST https://idmsa.apple.com/appleauth/auth/signin/complete
⠦ Logging in...Error: Request failed with status code 503 (POST https://idmsa.apple.com/appleauth/auth/signin/complete)
✖ Logging in...
