### ISSUE TITLE
"Could not reload the application after an edit." after upgrading the SDK45

### ISSUE THREAD

**Issue by haibert** [expo/expo#17485]
### Summary

After upgrading to SDK 45 I cannot use fast refresh anymore. Anytime I save changes I see the following warning. 

``` log 
Could not reload the application after an edit.
at node_modules/@sentry/utils/dist/instrument.js:111:20 in <anonymous>
at node_modules/metro-runtime/src/polyfills/require.js:804:8 in performFullRefresh
at node_modules/metro-runtime/src/polyfills/require.js:530:28 in topologicalSort$argument_1
at node_modules/metro-runtime/src/polyfills/require.js:667:37 in traverseDependentNodes
at node_modules/metro-runtime/src/polyfills/require.js:678:30 in dependentNodes.forEach$argument_0
at node_modules/metro-runtime/src/polyfills/require.js:673:6 in traverseDependentNodes
at node_modules/metro-runtime/src/polyfills/require.js:678:30 in dependentNodes.forEach$argument_0
at node_modules/metro-runtime/src/polyfills/require.js:673:6 in traverseDependentNodes
at node_modules/metro-runtime/src/polyfills/require.js:678:30 in dependentNodes.forEach$argument_0
at node_modules/metro-runtime/src/polyfills/require.js:673:6 in traverseDependentNodes
at node_modules/metro-runtime/src/polyfills/require.js:685:30 in roots.forEach$argument_0
at node_modules/metro-runtime/src/polyfills/require.js:683:4 in topologicalSort
at node_modules/metro-runtime/src/polyfills/require.js:486:44 in metroHotUpdateModule
at node_modules/metro-runtime/src/polyfills/require.js:53:8 in define
at http://192.168.1.4:8081/src/screens/GalleryView.bundle?platform=ios&hot=false&strict=false&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:1:3 in global
at node_modules/react-native/node_modules/metro-runtime/src/modules/HMRClient.js:18:4 in inject
at node_modules/react-native/node_modules/metro-runtime/src/modules/HMRClient.js:27:2 in injectUpdate
- ... 11 more stack frames from framework internals
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
   System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.02.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/haibert/SplashScreenIssueRepo

**Comment by haibert** [comment]
@byCedric sorry for the delay here is the repo. 

https://github.com/haibert/SplashScreenIssueRepo

**Comment by MatheusBlanco** [comment]
I saw that this has been marked as completed. I am having the same problem with sdk 45, on top of expo publish not updating OTA anymore. Were you able to fix it?

**Comment by jakrim** [comment]
Also having this issue right as I upgraded to SDK 45

**Comment by haibert** [comment]
Upgrading to the latest dev client fixed it for me. Run expo upgrade again let the packages upgrade they upgraded some stuff after the release of V45

**Comment by jakrim** [comment]
@haibert why was this closed? How did you fix it?

**Comment by haibert** [comment]
@paulkuhle i personally don't have this issue anymore but I'm not sure what I did to fix it, I did upgrade expo cli now that you mention it, everyone should give that a try.

**Comment by flashjames** [comment]
> I see you're using `expo-cli: 5.4.3`, which was released 2 months ago. Have you tried upgrading to the latest version (5.4.9)?

@paulkuhle 
I'm using 5.4.9 and I still have that error with auto reload.

The project:
- Expo bare workflow
- Contains some native android code for flipper-plugin
- I build and test on android with 'yarn android'

### yarn envinfo
```
`

  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 10.66 GB / 39.08 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.1 - /tmp/yarn--1655554984987-0.5220990909018917/node
    Yarn: 1.22.19 - /tmp/yarn--1655554984987-0.5220990909018917/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 20200920.192359.0 - /usr/local/bin/watchman
  Managers:
    Apt: 2.0.9 - /usr/bin/apt
    Cargo: 1.46.0 - ~/.cargo/bin/cargo
    pip3: 20.1.1 - ~/storage/anaconda3/bin/pip3
  Utilities:
    CMake: 3.16.3 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.4.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
    Clang: 10.0.0 - /usr/bin/clang
    Mercurial: 5.3.1 - /usr/bin/hg
    Subversion: 1.13.0 - /usr/bin/svn
    FFmpeg: 4.2.7 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 20.10.12 - /usr/bin/docker
    VirtualBox: 6.1.32 - /usr/bin/vboxmanage
  IDEs:
    Emacs: 29.0.50 - /usr/bin/emacs
    Nano: 4.8 - /usr/bin/nano
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Java: 1.8.0_312 - /usr/bin/javac
    Perl: 5.30.0 - /usr/bin/perl
    Python: 3.8.3 - ~/storage/anaconda3/bin/python
    Python3: 3.8.3 - ~/storage/anaconda3/bin/python3
    Rust: 1.46.0 - ~/.cargo/bin/rustc
  Databases:
    SQLite: 3.32.3 - ~/storage/anaconda3/bin/sqlite3
  Browsers:
    Chrome: 102.0.5005.115
    Chromium: 102.0.5005.115
    Firefox: 101.0.1

Done in 16.64s.`

```
### package.json
```
`{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@expo/react-native-action-sheet": "^3.9.0",
    "@feathersjs/client": "^3.3.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/cli": "^5.0.1-alpha.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "8.2.0",
    "@react-native-cookies/cookies": "^6.2.1",
    "@react-native-picker/picker": "2.4.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/elements": "^1.2.1",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "@reduxjs/toolkit": "^1.4.0",
    "@sentry/cli": "^1.71.0",
    "@sentry/react-native": "^3.2.8",
    "@testing-library/dom": "^7.30.3",
    "@testing-library/react": "^11.2.6",
    "@types/react": "~17.0.21",
    "await-lock": "^2.0.1",
    "axios": "^0.24.0",
    "base-64": "^0.1.0",
    "buffer": "^6.0.3",
    "classnames": "^2.2.5",
    "date-fns": "^2.9.0",
    "dayjs": "^1.10.4",
    "depcheck": "^1.4.3",
    "events": "^3.2.0",
    "expo": "^45.0.0",
    "expo-application": "~4.1.0",
    "expo-asset": "~8.5.0",
    "expo-constants": "~13.1.1",
    "expo-device": "~4.2.0",
    "expo-file-system": "~14.0.0",
    "expo-linking": "~3.1.0",
    "expo-secure-store": "~11.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.2",
    "expo-web-browser": "~10.2.1",
    "flipper": "^0.149.0",
    "flipper-plugin": "^0.149.0",
    "flipper-plugin-react-native-redux-debugger": "^1.0.7",
    "flipper-plugin-redux-debugger": "^1.2.2",
    "flipper-plugin-reduxinspector": "^1.0.4",
    "formik": "^2.1.3",
    "jquery": "^3.6.0",
    "lodash": "^4.17.15",
    "mixpanel-react-native": "^1.3.4",
    "moment": "^2.24.0",
    "qs": "^6.10.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-credit-card-input-plus": "^0.4.2",
    "react-native-elements": "^2.0.4",
    "react-native-flipper": "^0.146.1",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-webview": "11.18.1",
    "react-navigation-header-buttons": "^7.0.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-flipper": "^1.4.2",
    "redux-thunk": "^2.3.0",
    "sentry-expo": "^4.2.0",
    "socket.io-client": "^4.0.1",
    "url": "^0.11.0",
    "yup": "^0.28.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "babel-jest": "~25.2.6",
    "babel-preset-expo": "~9.1.0",
    "expo-cli": "^5.4.9",
    "jest": "^26.6.3",
    "jest-expo": "^45.0.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
  "private": true,
  "version": "2.0.0"
}
```

**Comment by paulvelk** [comment]
> I see you're using `expo-cli: 5.4.3`, which was released 2 months ago. Have you tried upgrading to the latest version (5.4.9)?

I am using managed workflow and after upgrade to SDK45, I am also getting the same issue and warning "Could not reload the application after an edit." when saving changes. Expo Go is at latest version and expo-cli at 5.4.12 (latest). Any hint to what maybe causing this ? Tks to all !

**Comment by paulvelk** [comment]
@jakrim 
@MatheusBlanco 

After some "head-crunching" I finally solved the issue. It seems it was **related to the metro package version**. Expo upgrade to SDK45 apparently does not include checking if metro is outdated (why should it ?). Once updated, I got my Fast Refresh working again ! 

So I suggest to check the metro version you are using (see package.json or run: npm list).

In my case it was still  ate version 0.59.0  (more than 2 years old ! :( while latest version ist at 0.71 !
To update run: npm install --save-dev metro metro-core
  
I hope thismay also solve the issue for others.

Ps. @flashjames : Just wondering why I did not see any refeference to metro package in your package.json file ?

**Comment by hrmoller** [comment]
@paulvelk while what you suggest solves the problem locally it does however (for me at least) cause an error in EAS builds failing at the "Run fastlane" step. 

Removing the two dependencies from package.json makes the build error disappear so I'm pretty sure that's why it fails.

**Comment by nchechik** [comment]
After about 60 years I realized that the react-native-animated-rating package causes this problem. I removed it and finally it works!

**Comment by natsumican63** [comment]
This solution worked for me:

`”resolutions": { "metro": "0.70.1" }` to package.json and running yarn install again fixed the error.
