### ISSUE TITLE
Build:android -> Request failed with status code 500

### ISSUE THREAD

**Issue by nguyenminhtri2903** [expo/expo#1749]
Please anyone help me, morning I use exp build:android is fine, but in this evening, I did it again then it show error 500 :(

```
23:44:45 [exp] Uploading assets
23:44:46 [exp] No assets changed, skipped.
23:44:46 [exp] Uploading JavaScript bundles
23:44:50 [exp] Request failed with status code 500
23:44:50 [exp] Error: Request failed with status code 500
    at createError (C:\Users\Kay\AppData\Roaming\npm\node_modules\exp\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Kay\AppData\Roaming\npm\node_modules\exp\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Kay\AppData\Roaming\npm\node_modules\exp\node_modules\axios\lib\adapters\http.js:191:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by esamelson** [comment]
Hi @nguyenminhtri2903 - this may have just been an intermittent error. Could you try running the build again? If you still see this error, could you try logging in again with `exp logout && exp login`?

**Comment by nicknovitski** [comment]
@nguyenminhtri2903 Have you been able to build your app?

**Comment by nguyenminhtri2903** [comment]
@nicknovitski @esamelson  Thanks any way, I solve my problem as well

This is only if we keep "slug": "your-app-slug" at the same url from the demo was built. It will throw an error

Just renew the slug url.

**Comment by ideesys** [comment]
I am getting same error.
![screen shot 2018-12-21 at 11 29 34 am](https://user-images.githubusercontent.com/44016862/50327149-dbb37700-0513-11e9-8f1d-b3cd54d1bcaa.png)

**Comment by jakubste** [comment]
@ideesys there is a solution on the screenshot you posted...

**Comment by jakubste** [comment]
@ideesys try upgrading `expo-cli`
