### ISSUE TITLE
Specifying android.kotlinVersion in gradle.properties does not change kotlin version

### ISSUE THREAD

**Issue by louiszawadzki** [expo/expo#17564]
### Summary

When adding a `android.kotlinVersion` in the `gradle.properties`, the kotlin version isn't affected.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

expo-dev-client 0.9.5

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8.1 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 18.0.0 - /opt/homebrew/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.6.0 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/louis.zawadzki/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.4
    Expo Workflow: bare

### Reproducible demo

# Steps to reproduce the issue

- Create new project with `expo init`
- Install development client `expo install expo-dev-client`
- At the end of `gradle.properties`, specify a kotlin version by adding `android.kotlinVersion=1.5.31` for instance

# Expected behaviour

I am working on adding Expo support to `@datadog/mobile-react-native` that requires kotlin 1.5.31, and I got compilation errors when running `expo run:android`. This isn't the quickest way to test it, so I'll also suggest something easier:

- Add `println kotlinVersion` in the project's `build.gradle` after the block where it is supposed to be set:
```
if (hasProperty('android.kotlinVersion')) {
    kotlinVersion = findProperty('android.kotlinVersion')
}
println kotlinVersion
```
- Run `expo run:android`
- You should see `1.5.31`

# Actual behaviour

- You'll get an error `Could not get unknown property 'kotlinVersion' for object of type org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.`

### Stacktrace (if a crash is involved)

The issue for me is that `hasProperty('android.kotlinVersion')` returns `null` every time.

According to https://stackoverflow.com/a/31066699, we should instead call `project.hasProperty('android.kotlinVersion')`.
I've tested it on my project and it works both when I specify a kotlin version, and when I don't specify a kotlin version.

I've read in the contributing guide that the `android/` part is hard to setup, but I'm happy to open a PR with the change to [this file](https://github.com/expo/expo/blob/main/templates/expo-template-bare-minimum/android/build.gradle) if that helps :)

**Comment by Kudo** [comment]
hi there! we've released the fix. please let us know whether it works for you. thank you!

**Comment by a-eid** [comment]
@Kudo changing KotlinVersion breaks the build. 

for example `1.3.50`.

```bash
> Task :expo-modules-core:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 1m 9s
163 actionable tasks: 163 executed
/Users/aeid/accelerate/el3yada/android/gradlew exited with non-zero code: 1
Error: /Users/aeid/accelerate/el3yada/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/aeid/.n/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:640:26)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/aeid/.n/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/Users/aeid/.n/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/Users/aeid/.n/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/Users/aeid/.n/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by anabeatrizzz** [comment]
I'm experiencing the same as @a-eid

**Comment by KeunwooPark** [comment]
changing `android.kotlinVersion` in `app.json` does not update the android file outputs.
