### ISSUE TITLE
[SDK45][expo-notifications] EAS build crash on iOS when upgrading to SDK 45

### ISSUE THREAD

**Issue by eeynard** [expo/expo#17610]
### Summary

Hello ! This morning I tries to upgrade my app to expo SDK 45 but I'm stuck with an error why trying to build the iOS binary in EAS in the Prebuild phase.
I get this error :
```
- Creating native project directories (./ios and ./android) and updating .gitignore
✔ Created native project
- Adding Metro bundler config
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro
- Updating your package.json scripts, dependencies, and main file
✔ Updated package.json and added index.js entry point for iOS and Android
[01:55:10] › Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead
- Config syncing
[stderr] Using node to generate images. This is much slower than using native packages.
[stderr] › Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
- Config syncing
[stderr] Using node to generate images. This is much slower than using native packages.
[stderr] › Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
- Config syncing
✖ Config sync failed
[stderr] [01:55:14] [ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr] [01:55:14] UnexpectedError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr]     at getAppDelegateFilePath (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
[stderr]     at getAppDelegate (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
[stderr]     at Object.getSourceRoot (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
[stderr]     at setNotificationSounds (/Users/expo/workingdir/build/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:39:57)
[stderr]     at /Users/expo/workingdir/build/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:19:9
[stderr]     at action (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
[stderr]     at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:14)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
bash exited with non-zero code: 1
```

I already achieve to fix the same error with other config plugins by just updating them (`@config-plugins/android-jsc-intl`, `@config-plugins/react-native-adjust`, `@config-plugins/react-native-branch`). So I was wondering if the `expo-notifications` config plugin hasn't been updated to support SDK 45 ?

Thanks for your help !

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v14.17.5/bin/npm
      Watchman: 2022.01.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.6
    Expo Workflow: managed
 ```

### Reproducible demo

Init a new project with SDK45, add expo-notifications as a dependency and add the config plugins in your app.config.js.

**Comment by eeynard** [comment]
Hey @byCedric, thank you for your answer. I'm talking about the main plugin from `expo-notifications` => https://github.com/expo/expo/blob/master/packages/expo-notifications/app.plugin.js
Here is an implementation example :
```js
plugins: {
  ['expo-notifications', { icon: './assets/icon-notification.png', color: '#16a085' }],
}
```

I'll try to provide a reproduction repository.

**Comment by danscan** [comment]
Related: https://github.com/expo/expo/issues/17303#issuecomment-1135300407

**Comment by brentvatne** [comment]
`expo doctor` will validate config plugin versions now and you'll see warnings for this in eas build
