### ISSUE TITLE
Getting dependency errors upon expo-update on mac for ios-build, unable to install node-modules

### ISSUE THREAD

**Issue by Prasad-03** [expo/expo#17703]
### Summary

npm ERR! path /Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3

npm ERR! command failed

npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c

npm ERR! Failed to execute ‘/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/lib/binding/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93’ (1)

npm ERR! node-pre-gyp info it worked if it ends with ok

npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0

npm ERR! node-pre-gyp info using node@16.14.2 | darwin | x64

npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download

npm ERR! node-pre-gyp info check checked for “/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node” (not found)

npm ERR! node-pre-gyp WARN Tried to download(403):

npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)

npm ERR! node-pre-gyp http 403 status code downloading tarball

npm ERR! gyp info it worked if it ends with ok

npm ERR! gyp info using node-gyp@8.4.1

npm ERR! gyp info using node@16.14.2 | darwin | x64

npm ERR! gyp info ok

npm ERR! gyp info it worked if it ends with ok

npm ERR! gyp info using node-gyp@8.4.1

npm ERR! gyp info using node@16.14.2 | darwin | x64

npm ERR! gyp info find Python using Python version 3.8.9 found at “/Applications/Xcode.app/Contents/Developer/usr/bin/python3”

npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3

npm ERR! gyp info spawn args [

npm ERR! gyp info spawn args ‘/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py’,

npm ERR! gyp info spawn args ‘binding.gyp’,

npm ERR! gyp info spawn args ‘-f’,

npm ERR! gyp info spawn args ‘make’,

npm ERR! gyp info spawn args ‘-I’,

npm ERR! gyp info spawn args ‘/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/build/config.gypi’,

npm ERR! gyp info spawn args ‘-I’,

npm ERR! gyp info spawn args ‘/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi’,

npm ERR! gyp info spawn args ‘-I’,

npm ERR! gyp info spawn args ‘/Users/admin/Library/Caches/node-gyp/16.14.2/include/node/common.gypi’,

npm ERR! gyp info spawn args ‘-Dlibrary=shared_library’,

npm ERR! gyp info spawn args ‘-Dvisibility=default’,

npm ERR! gyp info spawn args ‘-Dnode_root_dir=/Users/admin/Library/Caches/node-gyp/16.14.2’,

npm ERR! gyp info spawn args ‘-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp’,

npm ERR! gyp info spawn args ‘-Dnode_lib_file=/Users/admin/Library/Caches/node-gyp/16.14.2/<(target_arch)/node.lib’,

npm ERR! gyp info spawn args ‘-Dmodule_root_dir=/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3’,

npm ERR! gyp info spawn args ‘-Dnode_engine=v8’,

npm ERR! gyp info spawn args ‘–depth=.’,

npm ERR! gyp info spawn args ‘–no-parallel’,

npm ERR! gyp info spawn args ‘–generator-output’,

npm ERR! gyp info spawn args ‘build’,

npm ERR! gyp info spawn args ‘-Goutput_dir=.’

npm ERR! gyp info spawn args ]

npm ERR! gyp info ok

npm ERR! gyp info it worked if it ends with ok

npm ERR! gyp info using node-gyp@8.4.1

npm ERR! gyp info using node@16.14.2 | darwin | x64

npm ERR! gyp info spawn make

npm ERR! gyp info spawn args [ ‘BUILDTYPE=Release’, ‘-C’, ‘build’ ]

npm ERR! /bin/sh: python: command not found

npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127

npm ERR! gyp ERR! build error

npm ERR! gyp ERR! stack Error: make failed with exit code: 2

npm ERR! gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)

npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:526:28)

npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

npm ERR! gyp ERR! System Darwin 21.5.0

npm ERR! gyp ERR! command “/usr/local/bin/node” “/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js” “build” “–fallback-to-build” “–module=/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node” “–module_name=node_sqlite3” “–module_path=/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/lib/binding/node-v93-darwin-x64” “–napi_version=8” “–node_abi_napi=napi” “–napi_build_version=0” “–node_napi_label=node-v93”

npm ERR! gyp ERR! cwd /Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3

npm ERR! gyp ERR! node -v v16.14.2

npm ERR! gyp ERR! node-gyp -v v8.4.1

npm ERR! gyp ERR! not ok

npm ERR! node-pre-gyp ERR! build error

npm ERR! node-pre-gyp ERR! stack Error: Failed to execute ‘/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3/lib/binding/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93’ (1)

npm ERR! node-pre-gyp ERR! stack at ChildProcess. (/Users/admin/Documents/New/my-app/frontend/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

npm ERR! node-pre-gyp ERR! stack at ChildProcess.emit (node:events:526:28)

npm ERR! node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1092:16)

npm ERR! node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

npm ERR! node-pre-gyp ERR! System Darwin 21.5.0

npm ERR! node-pre-gyp ERR! command “/usr/local/bin/node” “/Users/admin/Documents/New/my-app/frontend/node_modules/.bin/node-pre-gyp” “install” “–fallback-to-build”

npm ERR! node-pre-gyp ERR! cwd /Users/admin/Documents/New/my-app/frontend/node_modules/sqlite3

npm ERR! node-pre-gyp ERR! node -v v16.14.2

npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0

npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:

npm ERR! /Users/admin/.npm/_logs/2022-05-31T05_31_43_462Z-debug-0.lo

I’m using the node -:16.15.0, expo-cli -:5.3.1, and expo-:41 versions and I’m getting above error whenever I’m running “npm install” command.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.3 environment info:

    System:

      OS: macOS 12.4

      Shell: 5.8.1 - /bin/zsh

    Binaries:

      Node: 16.14.0 - /usr/local/bin/node

      npm: 8.3.1 - /usr/local/bin/npm

      Watchman: 2022.05.30.00 - /usr/local/bin/watchman

    SDKs:

      iOS SDK:

        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5

    IDEs:

      Xcode: 13.4/13F17a - /usr/bin/xcodebuild

    npmGlobalPackages:

      eas-cli: 0.53.0

      expo-cli: 5.0.3

    Expo Workflow: managed

### Reproducible demo

"dependencies": {
    "@expo-google-fonts/montserrat": "^0.1.0",
    "@expo-google-fonts/poppins": "^0.2.0",
    "@expo/ngrok": "^2.4.3",
    "@invertase/react-native-apple-authentication": "^2.1.2",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/datetimepicker": "^3.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/material-top-tabs": "^5.3.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "expo": "^41.0.0",
    "expo-app-auth": "~10.1.2",
    "expo-apple-authentication": "~3.1.0",
    "expo-av": "~9.1.2",
    "expo-cli": "^5.3.1",
    "expo-crypto": "~9.1.0",
    "expo-device": "~3.2.0",
    "expo-facebook": "~11.0.5",
    "expo-firebase-analytics": "~4.0.2",
    "expo-firebase-core": "~3.0.0",
    "expo-google-sign-in": "~9.1.0",
    "expo-image-manipulator": "~9.1.0",
    "expo-image-picker": "~10.1.4",
    "expo-linking": "~2.2.3",
    "expo-location": "~12.0.4",
    "expo-modules-core": "^0.6.3",
    "expo-notifications": "~0.11.6",
    "expo-permissions": "~12.0.1",
    "expo-random": "~11.1.2",
    "expo-secure-store": "^11.0.3",
    "expo-store-review": "~4.0.2",
    "expo-web-browser": "~9.1.0",
    "firebase": "^8.2.3",
    "indexeddbshim": "^7.0.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-check-box": "^2.1.7",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-svg": "12.1.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-web": "~0.13.12",
    "react-native-webview": "11.2.3",
    "expo-updates": "~0.5.4"
  },

**Comment by vinaciotm** [comment]
same issue here
