### ISSUE TITLE
Can't log in: [exp] the connection was disabled

### ISSUE THREAD

**Issue by seunlanlege** [expo/expo#1777]
```zsh
[exp] the connection was disabled
[exp] Error: the connection was disabled
    at _formatAuth0NodeError (/xdl/src/User.js:757:14)
    at /xdl/src/User.js:654:15
    at Generator.throw (<anonymous>)
    at step (/usr/local/share/.config/yarn/global/node_modules/xdl/build/User.js:188:191)
    at /usr/local/share/.config/yarn/global/node_modules/xdl/build/User.js:188:402
    at <anonymous>
```

version: v54.0.0

**Comment by quinlanj** [comment]
hi @seunlanlege  this is very odd -- this code path should have been completely removed. Could you please double check that you have v54 by running `exp --version`, and that you have the most up to date `xdl` dependency (ie) v 50.0.0 ?

**Comment by seunlanlege** [comment]
Ok so turns out i was using v49.0.0

i had to manually rm it at `/usr/local/bin/exp`

re intalled from npm, and and i can now log in. :clap:

**Comment by giautm** [comment]
Hi, I got the same error with 49.0.8
```
[exp] the connection was disabled
[exp] Error: the connection was disabled
    at _formatAuth0NodeError (/xdl/src/User.js:751:3)
    at /xdl/src/User.js:655:7
    at Generator.throw (<anonymous>)
    at step (/node_modules/xdl/build/User.js:188:191)
    at /node_modules/xdl/build/User.js:188:402
    at <anonymous>
```
