### ISSUE TITLE
ENOENT AppBundle path

### ISSUE THREAD

**Issue by edi** [expo/expo#17794]
### Summary

So, on Android, for some reason the path of the AppBundle file that it is trying to fetch, is relative, instead of absolute.

Basically, it tries fetching `/Users/edi/Desktop/Swup/http:/192.168.3.12:8081/node_modules/expo/AppEntry.bundle [etc]`

When in fact, the file is actually available, but `http:/192.168.3.12:8081/node_modules/expo/AppEntry.bundle [etc]` is available with the proper info.

So for some reason, it tries parsing the file with current working dirrectory in front `/Users/edi/Desktop/Swup/` 
I've tried reinstalling everything, but the same happens .. any clue what could cause this? iOS works fine.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

"@react-native-async-storage/async-storage": "~1.17.3",
"@react-native-community/netinfo": "8.2.0",
"@react-native-picker/picker": "2.4.0",
"@stripe/stripe-react-native": "0.6.1",
"axios": "^0.27.2",
"expo": "^45.0.0",
"expo-barcode-scanner": "~11.3.0",
"expo-camera": "~12.2.0",
"expo-constants": "~13.1.1",
"expo-font": "~10.1.0",
"expo-image-manipulator": "~10.3.1",
"expo-image-picker": "~13.1.1",
"expo-linear-gradient": "~11.3.0",
"expo-linking": "~3.1.0",
"expo-localization": "~13.0.0",
"expo-location": "~14.2.2",
"expo-media-library": "~14.1.0",
"expo-notifications": "~0.15.2",
"expo-print": "~11.2.0",
"expo-sharing": "~10.2.0",
"expo-splash-screen": "~0.15.1",
"expo-status-bar": "~1.3.0",
"expo-store-review": "~5.2.0",
"expo-system-ui": "~1.2.0",
"expo-updates": "~0.13.1",
"expo-web-browser": "~10.2.1",
"firebase": "^9.8.2",
"lottie-react-native": "5.0.1",
"moment": "^2.29.3",
"numbro": "^2.3.6",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-native": "0.68.2",
"react-native-confirmation-code-field": "^7.3.0",
"react-native-error-boundary": "^1.1.13",
"react-native-flash-message": "^0.2.1",
"react-native-gesture-handler": "~2.2.1",
"react-native-maps": "0.30.2",
"react-native-safe-area-context": "4.2.4",
"react-native-svg": "12.3.0",
"react-native-webview": "11.18.1",
"react-redux": "^8.0.2",
"react-router-native": "^6.3.0",
"redux": "^4.2.0",
"redux-thunk": "^2.4.1",
"styled-components": "^5.3.5",
"supercluster": "^7.1.5",
"toggle-switch-react-native": "^3.3.0",
"expo-dev-client": "~0.10.0"

### Environment

expo-env-info 1.0.3 environment info:
System:
  OS: macOS 12.4
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.15.0 - /opt/homebrew/opt/node@16/bin/node
  npm: 8.5.5 - /opt/homebrew/opt/node@16/bin/npm
Managers:
  CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
IDEs:
  Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
npmPackages:
  expo: ^45.0.0 => 45.0.5 
  react: 17.0.2 => 17.0.2 
  react-dom: 17.0.2 => 17.0.2 
  react-native: 0.68.2 => 0.68.2 
npmGlobalPackages:
  eas-cli: 0.53.0
  expo-cli: 5.4.9
Expo Workflow: managed

### Reproducible demo

None

### Stacktrace (if a crash is involved)

```
Error: ENOENT: no such file or directory, open '/Users/edi/Desktop/Swup/http:/192.168.3.12:8081/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.rideswup.app&modulesOnly=false&runModule=true'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/Users/edi/Desktop/Swup/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/edi/Desktop/Swup/node_modules/metro/src/Server.js:1022:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server._processRequest (/Users/edi/Desktop/Swup/node_modules/metro/src/Server.js:429:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/edi/Desktop/Swup/http:/192.168.3.12:8081/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.rideswup.app&modulesOnly=false&runModule=true'
}
```

**Comment by edi** [comment]
Alright, I came back with a minimal example. As I've said initially, it only seems to happen on Android's development client.

https://github.com/edi/test

Clone the repo and start it within any dev client you have on your phone. 
It doesn't have any custom config, no plugins, nothing aside firebase.

- **web**, works fine (expo go and dev client).
- **iOS**, works fine (expo go and dev client).
- **android** works fine in Expo go, but dies when using the dev client, with the above error.

I doubt it's an issue with Firebase since it works just fine in a production build, on all platforms, as well as within expo go  directly, just fails for some unknown reason on Android's dev client, which makes development impossible.

What I've tried so far:

1. Tried with most Firebase v9 versions, starting with 9.0.0, all the way to 9.8.3 which requires that metro.config.js file to support .cjs extensions, issue is the same.

2. Tried modifying readFileSync directly in node's FS source code (node_modules), just to make sure it's not that AppEntry.bundle file that cannot be loaded and causes it, still, even when loaded, issue is the smae.

3. Tried on a different laptop (macOS) as well as a different PC (Windows), result is the same.

4. Tried on a different phone (even though it should have nothing to do with it) as well as on different development builds, all cleaned up, same story.
