### ISSUE TITLE
Issue on double shareAsync call

### ISSUE THREAD

**Issue by zaibimajdi** [expo/expo#17926]
### Summary

I have two screens on my app. on each screen I have a call to shareAsync method. When I call shareAsync a second time then I have a warning and the share does not work.
The issue happen only on IOS

Error stack strace:

[Unhandled promise rejection: Error: Another item is being shared. Await the `shareAsync` request and then share the item again.]
at node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:104:50 in promiseMethodWrapper
at node_modules\expo-modules-core\build\NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules\expo-sharing\build\Sharing.js:23:7 in shareAsync
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:190:16 in PromiseImpl$argument_0

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43.0.0

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      @expo/metro-config: ^0.3.9 => 0.3.9
      expo: ~43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

Scenario of bug:
1- I call shareAsync  on screen A and cancel it.
2- Then I move to screen B and call shareAsync => error

**Comment by brentvatne** [comment]
hi there! as mentioned above, we need a reproducible example to investigate. that said, from the message you shared it looks like this is actually expected behavior - you can only have one share dialog open at any given time.
