### ISSUE TITLE
Expo don't support "babel-root-slash-import" plugin

### ISSUE THREAD

**Issue by highlabs** [expo/expo#1794]
### Environment

Exp Version: 53.1.0
OS version: Ubuntu 18.04

### Steps to Reproduce

1. Install `babel-root-slash-import` package
2. Add `babel-root-slash-import` to `.babelrc`
3. Load component or files using root path (exampĺe: `/components/mycomponent.js`)
4. Run `exp:build android`

### Expected Behavior

Run and finish build.

### Actual Behavior

During build exp cannot find files under `/` (I get 500 error) path. So I need to add `../../` to work.
Maybe this is a expected behavior, but will be nice use `babel-root-slash-import` to avoid `../../../` nightmares.

The error:
```
11:09:10 [exp] 500 - "{\"originModulePath\":\"/home/user/my_project_directory/screens/cars/FinishCars.js\",\"targetModuleName\":\"/assets/fonts/Icomoon.json\",\"message\":\"Unable to resolve module `/assets/fonts/Icomoon.json` from `/home/user/my_project_directory/screens/cars/FinishCars.js`: The module `/assets/fonts/Icomoon.json` could not be found from `/home/user/my_project_directory/screens/cars/FinishCars.js`. Indeed, none of these files exist:\\n\\n  * `/assets/fonts/Icomoon.json(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`\\n  * `/assets/fonts/Icomoon.json/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`\",\"errors\":[{\"description\":\"Unable to resolve module `/assets/fonts/Icomoon.json` from `/home/user/my_project_directory/screens/cars/FinishCars.js`: The module `/assets/fonts/Icomoon.json` could not be found from `/home/user/my_project_directory/screens/cars/FinishCars.js`. Indeed, none of these files exist:\\n\\n  * `/assets/fonts/Icomoon.json(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`\\n  * `/assets/fonts/Icomoon.json/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`\"}],\"name\":\"Error\",\"stack\":\"Error: Unable to resolve module `/assets/fonts/Icomoon.json` from `/home/user/my_project_directory/screens/cars/FinishCars.js`: The module `/assets/fonts/Icomoon.json` could not be found from `/home/user/my_project_directory/screens/cars/FinishCars.js`. Indeed, none of these files exist:\\n\\n  * `/assets/fonts/Icomoon.json(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`\\n  * `/assets/fonts/Icomoon.json/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`\\n    at ModuleResolver.resolveDependency (/home/user/my_project_directory/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)\\n    at ResolutionRequest.resolveDependency (/home/user/my_project_directory/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)\\n    at DependencyGraph.resolveDependency (/home/user/my_project_directory/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)\\n    at dependencies.map.relativePath (/home/user/my_project_directory/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)\\n    at Array.map (native)\\n    at resolveDependencies (/home/user/my_project_directory/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)\\n    at /home/user/my_project_directory/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33\\n    at Generator.next (<anonymous>)\\n    at step (/home/user/my_project_directory/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)\\n    at /home/user/my_project_directory/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467\"}!
```

P.S: The plugin works fine in development (genymotion or devices). These erros happens only in build process.

**Comment by jesseruder** [comment]
I'm not sure how `babel-root-slash-import` works, but I'm guessing this would also be an issue with raw react-native. I'd suggest diving into the plug code and figure out what's going on. I don't think this is going to be a priority for us to look at.

**Comment by cruzach** [comment]
Hi! I'm closing some inactive and old issues. If you are having trouble with this (or something similar) now and come across this issue, I recommend trying to use the library in a bare RN project first, and if it works there, then definitely open a github issue here with a full repro 😄
