### ISSUE TITLE
[expo-barcode-scanner] Random Native crash on Android

### ISSUE THREAD

**Issue by TrustyTechSG** [expo/expo#17973]
### Summary

Random Native crash (Android only) constantly happens after update to SDK 45,  we received feedbacks from our customers and monitoring this issue for about one month now, we only can see the error from Google play console, but we can not reproduce if on our devices. it effect about 1 out of 10 of our customers.

We tried many hours but failed to reproduce this, all we got is just error log from Google Play console, before upgrade to SDK45 we using SDK 43 and do not have this issue.

We see other people also did mentioned the same issue
https://github.com/expo/expo/issues/13049#issuecomment-1071006229
https://github.com/expo/expo/issues/6950#issuecomment-1054235641

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
      Yarn: 1.22.18 - ~/Documents/EasyBus/easybus-mobile/node_modules/.bin/yarn
      npm: 8.10.0 - ~/.nvm/versions/node/v14.19.2/bin/npm
      Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.2 => 45.0.2 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: ^0.68.2 => 0.68.2 
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: bare

### Reproducible demo

java.lang.RuntimeException: 
  at android.hardware.Camera.native_getParameters (Native Method)
  at android.hardware.Camera.getParameters (Camera.java:2153)
  at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend (BarCodeScannerViewFinder.kt:195)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:749)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:664)

**Comment by Kudo** [comment]
hi there! please provide a minimal reproducible example for us to further investigate and verifying the issue. thank you!

**Comment by NikhilVashistha** [comment]
@TrustyTechSG  I am also facing the same issue. Did you get any solution for this?

**Comment by juanmigdr** [comment]
Same here, I am not able to reproduce it since it is happening to my mobile app users.
```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed
```

**Comment by douglasjunior** [comment]
We are seeing this error on crashlytics too.

```log
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2215)
       at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend(BarCodeScannerViewFinder.kt:196)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

We can't reproduce the problem yet, but look to the screen events seems that the problem happens when the Stack Screen is closed/replaced when the `<BarcodeScanner />` still initializing the camera.
