### ISSUE TITLE
[expo update] Error upgrading to SDK 45

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#17971]
### Summary

There is an error while running `expo update`

```
➜  no-filter-app git:(master) expo update
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard
✔ You are currently using SDK 44.0.0. Would you like to update to the latest version, 45.0.0? … yes


✖ Failed to install expo package with error: yarnpkg exited with non-zero code: 1
yarnpkg exited with non-zero code: 1
Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/noel/.nvm/versions/node/v16.4.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:662:12)
    ...
    at spawnAsync (/Users/noel/.nvm/versions/node/v16.4.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (/Users/noel/.nvm/versions/node/v16.4.0/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:314:31)
    at YarnPackageManager.addWithParametersAsync (/Users/noel/.nvm/versions/node/v16.4.0/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:259:16)
    at YarnPackageManager.addAsync (/Users/noel/.nvm/versions/node/v16.4.0/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:263:5)
    at upgradeAsync (/Users/noel/.nvm/versions/node/v16.4.0/lib/node_modules/expo-cli/src/commands/info/upgradeAsync.ts:496:7)
    at actionAsync (/Users/noel/.nvm/versions/node/v16.4.0/lib/node_modules/expo-cli/src/commands/info/upgradeAsync.ts:42:3)
➜  no-filter-app git:(master)
```

### SDK Version

44, trying to migrate to 45

### Environment

```
➜  no-filter-app git:(master) npx expo-env-info

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 27, 31
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.3, 29.0.2
        System Images: android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
    Expo Workflow: managed
```

### Reproducible demo

Just run `expo update` from a SDK 44.

**Comment by Kudo** [comment]
hi there! i tried the `expo update` from a sdk 44 project and it works. please try to provide a minimal reproducible example for us to further investigation. thank you!

**Comment by BrodaNoel** [comment]
Related: https://github.com/expo/expo-cli/issues/4366

**Comment by BrodaNoel** [comment]
Workaround:

```
rm -rf node_modules
rm yarn.lock
yarn add expo
expo update
```

**Comment by BrodaNoel** [comment]
Worked properly after:

```
rm -rf .expo
rm yarn.lock
```

**Comment by leonardosarmentocastro** [comment]
@BrodaNoel Thank you, sir! Saved me some time. 👍🏽
