### ISSUE TITLE
[Expo SDK 45][expo-updates] Launch a release build app on Android, it crashes instantly. 

### ISSUE THREAD

**Issue by mone9610** [expo/expo#18003]
### Summary

- After upgrading from Expo44 to Expo45 and release build Android from gradlew, I get the following error after launching the app and the app crashes.
```
    --------- beginning of crash
2022-06-24 13:48:34.975 14784-14784/jp.MyApp.app.dev2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jp.MyApp.app.dev2, PID: 14784
    java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
        at expo.modules.updates.manifest.EmbeddedManifest.get(EmbeddedManifest.kt:31)
        at expo.modules.updates.loader.LoaderTask.launchFallbackUpdateFromDisk(LoaderTask.kt:238)
        at expo.modules.updates.loader.LoaderTask.start(LoaderTask.kt:99)
        at expo.modules.updates.UpdatesController.start(UpdatesController.kt:290)
        at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:464)
        at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:41)
        at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:28)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
        at jp.MyApp.app.MainApplication.onCreate(MainApplication.java:66)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
- The following steps have already been implemented.  
In fact, it worked in Expo44, but when I upgraded to Expo45, the error occurred even with the same settings.  
https://docs.expo.dev/bare/installing-updates/#configuration-for-android

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.6

### Environment

```
 expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 11.6.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /var/folders/7p/63f1ry0s00v25qmd8ftbwl3m0000gn/T/yarn--1656389778021-0.5219689612973404/node
      Yarn: 1.22.11 - /var/folders/7p/63f1ry0s00v25qmd8ftbwl3m0000gn/T/yarn--1656389778021-0.5219689612973404/yarn
      npm: 8.12.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.21 => 0.16.25 
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.9
    Expo Workflow: bare
```
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Amazon.com Inc. 11.0.15+9-LTS)
OS:           Mac OS X 11.6.5 x86_64
```
```
Android SDK: API Levels: 29, 30, 31
```

### Reproducible demo

- Upgrade from Expo SDK 44 to Expo SDK 45
- Upgrade gradle wrapper 6.9 to 7.4
- Create a release build using the gradle wrapper and install it on the android device.
  ```
  ./gradlew clean :app:bundleRelease
  bundletool build-apks --bundle=./app/build/outputs/bundle/release/app-release.aab --output=./app/build/outputs/apk/app-release.apks --mode=universal
  unzip ./app/build/outputs/apk/app-release.apks
  adb install -r ./universal.apk
  ```
- When the app is started, the error listed in Summary occurs and crashes immediately.

**Comment by dhiogocorrea** [comment]
Im facing the same issue...

**Comment by brentvatne** [comment]
@dhiogocorrea - see the @expo-bot comment above
