### ISSUE TITLE
Error: DocumentPicker requires the iCloud entitlement INSIDE of Expo Go App for IOS

### ISSUE THREAD

**Issue by djtaraz** [expo/expo#18057]
### Summary

Hi,

I have a problem with the DocumentPicker module, googled around for days now and cannot find a solution.

I am getting this warning/error when trying to open DocumentPicker within my app, inside of the Expo Go App:
`[Unhandled promise rejection: Error: DocumentPicker requires the iCloud entitlement. If you are using ExpoKit, you need to add this capability to your App Id. See `https://docs.expo.io/versions/latest/expokit/advanced-expokit-topics#using-documentpicker` for more info.]`

I followed the link in the warning and it says that I should open the project in XCode and enable ICloud entitlement. My project is on **Managed Workflow,** which means I cannot open it in XCode afaik. 

[Here](https://docs.expo.dev/versions/latest/sdk/document-picker/#managed-workflow), it says: _For iOS, outside of the Expo Go app, the DocumentPicker module requires the iCloud entitlement_. I have enabled all the ICloud capabilities in Apple Developer interface and I am enrolled in the program. I have even added this to my app.json

```
    "plugins": [
      [
        "expo-document-picker",
        {
          "appleTeamId": "55G59Q77Q7"
        }
      ]
    ],
```

Yet, within the Expo Go App, with all that enabled and configured I am still getting the _requires ICloud entitlement warning/error_, and as the docs say for DocumentPicker **Outside of the Expo Go App** this module requires the entitlement but again, I am within the Expo Go App. 

Here is my code to open the document picker:

`const res = await getDocumentAsync({});`

Lmk if anything else needed to debunk this.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    Expo Workflow: managed

### Reproducible demo

Lmk if this is still needed.

**Comment by djtaraz** [comment]
**Solved this issue by downgrading to** `expo-document-picker@9.2.4`.

I also tried with v10.2.1 which is latest. In that version the app would not start at all and I got this error:

```
TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExpoDocumentPicker')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:200:6 in runApplication
```

@mods, for future reference is this an issue with the shipped version or is it just a mismatch with expo versions?

**Comment by brentvatne** [comment]
use `expo install expo-document-picker` to get the appropriate version

**Comment by djtaraz** [comment]
> use `expo install expo-document-picker` to get the appropriate version

@brentvatne by the way, ive manually upgraded expo and all related packages as well and I used expo install to do this, expo is now v45.0.0 and document picker is on v10.2.1. 

seeing weird behaviour now: expo go app on my Mac, in the IOS simulator is letting me open the document picker but not select any documents, but on my iPhone it does. That is only if I have mime type */*. 
But if I choose mime type application/pdf it produces the error again - Unhandled promise rejection: Error: DocumentPicker requires the iCloud entitlement.
