### ISSUE TITLE
[SKD 46] development build crash after splash screen

### ISSUE THREAD

**Issue by itsramiel** [expo/expo#18314]
### Summary

After upgrading to expo sdk 46, I got the following error:
```
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
- ... 6 more stack frames from framework internals

Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:127:23 in metroRequire
at http://192.168.3.112:8081/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.mobilon.feedmecyprus&modulesOnly=false&runModule=true:358845:3 in global
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

46

### Environment

```
  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.06.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0-beta.6 => 46.0.0-beta.6
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.1 => 0.69.1
      react-native-web: ~0.18.7 => 0.18.7
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed
```

### Reproducible demo

I am not sure how to reproduce it. I basically just upgraded to expo sdk 46 from expo sdk45 which was working fine

**Comment by brentvatne** [comment]
thanks for trying out the beta! hopefully the above link helps

**Comment by bcteam2020** [comment]
we also facing the same issue, build which is working perfectly fine in sdk 45 upgraded to 46 and crash, with same above error

**Comment by rahmanharoon** [comment]
Facing this same issue when trying to upgrade to expo sdk 46..

**Comment by thareekanvar** [comment]
Facing same crash please help me out of this ..above error 
also i have ViewPropTypes deprecated error along

**Comment by rahmanharoon** [comment]
[Try this](https://github.com/psycheangel/deprecated-with-module-resolver/blob/master/README.md) @thareekanvar

**Comment by thareekanvar** [comment]
@rahmanharoon i tried the above fix after that i have an error like this 

```
Invariant Violation: requireNativeComponent: "RNGestureHandlerRootView" was not found in the UIManager.

This error is located at:
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by DrawerView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by DrawerNavigator)
    in DrawerNavigator (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by RootNavigator)
    in RootNavigator (created by Navigation)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Navigation)
    in Navigation (created by App)
    in ThemeProvider (created by Provider)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in Provider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

even i tried this fix 

Recently I had the same problem. Here's the solution:

expo install react-native-gesture-handler
and

import 'react-native-gesture-handler';
On the root of the Project, the App.js file probably.

but no use , any help ..

**Comment by rahmanharoon** [comment]
Did you try removing node modules and re installing again and clearing cache

**Comment by Wei102193** [comment]
For the Invariant Violation: ViewPropTypes issue, just try to carefully locate where the issue comes from. Probably it is an outdated dependency that causing this issue. For me it is react-native-elements.

**Comment by thareekanvar** [comment]
> For the Invariant Violation: ViewPropTypes issue, just try to carefully locate where the issue comes from. Probably it is an outdated dependency that causing this issue. For me it is react-native-elements.

yea i fixd

**Comment by eatanga-git** [comment]
> > For the Invariant Violation: ViewPropTypes issue, just try to carefully locate where the issue comes from. Probably it is an outdated dependency that causing this issue. For me it is react-native-elements.
> 
> yea i fixd

You fixed it? How? What did you do?
