### ISSUE TITLE
Build failing with "Could not determine the dependencies of task ':expo-modules-core:compileDebugJavaWithJavac'."

### ISSUE THREAD

**Issue by n1xx1** [expo/expo#18357]
### Summary

I'm trying to setup a Expo app with expo-dev-client, but I'm having issues ejecting with `expo run:android`.

```
$ yarn create expo-app my-expo-app
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > ts-node@10.2.1" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...

success Installed "create-expo-app@1.0.4" with binaries:
      - create-expo-app
√ Downloaded and extracted project files.
√ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd my-expo-app
- yarn android
- yarn ios # you need to use macOS to build the iOS project - use the Expo app if you need to do iOS development without a Mac
- yarn web
Done in 82.16s.
```

```
$ expo run:android

📝  Android package Learn more: https://expo.fyi/android-package

√ What would you like your Android package name to be? ... me.n1xx1.app
✔ Created native project
✔ Added Metro config
✔ Updated package.json and added index.js entry point for iOS and Android
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead

🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 8206ms
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
✔ Config synced
› Building app...
Configuration on demand is an incubating feature.

> Task :react-native-gradle-plugin:compileKotlin
'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (155, 32): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (161, 31): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (169, 36): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactPlugin.kt: (100, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with rootto point to your root project and reactNativeDir to point to the folder of the react-native NPM package
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (28, 51): 'BaseVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (131, 12): 'ApplicationVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (132, 12): 'LibraryVariant' is deprecated. Deprecated in Java
w: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (252, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Task :react-native-gradle-plugin:compileJava
Note: C:\Users\n1xx1\Development\my-expo-app\node_modules\react-native-gradle-plugin\src\main\java\com\facebook\react\codegen\generator\SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Configure project :expo

Using expo modules
  - expo-application (4.1.0)
  - expo-constants (13.1.1)
  - expo-error-recovery (3.1.0)
  - expo-file-system (14.0.0)
  - expo-font (10.1.0)
  - expo-keep-awake (10.1.1)
  - expo-modules-core (0.9.2)
  - expo-splash-screen (0.15.1)


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':expo-modules-core:compileDebugJavaWithJavac'.
> Cannot query the value of this provider because it has no value available.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 20s
6 actionable tasks: 6 executed
C:\Users\n1xx1\Development\my-expo-app\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\n1xx1\Development\my-expo-app\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\n1xx1\AppData\Local\Yarn\Data\global\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.cp.emit (C:\Users\n1xx1\AppData\Local\Yarn\Data\global\node_modules\@expo\spawn-async\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
    ...
    at spawnAsync (C:\Users\n1xx1\AppData\Local\Yarn\Data\global\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)    at spawnGradleAsync (C:\Users\n1xx1\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:83:18)
    at assembleAsync (C:\Users\n1xx1\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:57:16)
    at actionAsync (C:\Users\n1xx1\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\commands\run\android\runAndroid.ts:143:9)

```

### What platform(s) does this occur on?

Android

### Environment

    expo-env-info 1.0.5 environment info:

    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31, 32
        Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Reproducible demo

```
    yarn create expo-app my-expo-app
    cd my-expo-app
    expo run:android
```

**Comment by TheLukaDragar** [comment]
I am experiencing the same problem!

**Comment by ejkkan** [comment]
Same here. Did anyone resolve this?

**Comment by saintilien** [comment]
how to solve??

**Comment by saintilien** [comment]
Could not determine the dependencies of task ':expo-modules-core:generateJsonModelRelease'.
[stderr] 
> Could not resolve all files for configuration ':expo-modules-core:releaseCompileClasspath'.
[stderr] 
   > Could not find com.facebook.react:react-native:0.71.8.
[stderr] 
     Required by:
[stderr] 
         project :expo-modules-core

**Comment by TonyGTH** [comment]
Same here.

**Comment by m6265m** [comment]
Same here, was anyone able to find the solution to this?

**Comment by rafaelcanical** [comment]
Anything?

**Comment by chptlouis** [comment]
experiencing similar problems with expo-modules-core, it just happened without me touching anything, I can't figure it out

**Comment by pmMarciniakIT** [comment]
@chptlouis  same, today I tried to compile a new expo version with eas build and I got an error:

Could not determine the dependencies of task ':expo-modules-core:compileReleaseRenderscript'.
> Could not resolve all task dependencies for configuration ':expo-modules-core:releaseCompileClasspath'.
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :expo-modules-core
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/org/webkit/android-jsc/maven-metadata.xml.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/org/webkit/android-jsc/maven-metadata.xml'. Received status code 503 from server: Service Temporarily Unavailable

**Comment by pmMarciniakIT** [comment]
The fix: force update expo-modules-core to version 1.5.12

**Comment by chptlouis** [comment]
@pmMarciniakIT yes I got pretty much the same problems, would you mind share the command you used to do so ?

**Comment by pmMarciniakIT** [comment]
@chptlouis I added "expo-modules-core": "~1.5.12", to my package.json
