### ISSUE TITLE
Upgrade to expo 46 breaks web app using NativeBase

### ISSUE THREAD

**Issue by danielantelo** [expo/expo#18380]
### Summary

Upgraded my project to sdk 46.0.1 and the web app is breaking with the following error:

```
Uncaught Error: Cannot find module 'react-native-web/dist/exports/StyleSheet/createCompileableStyle'
    at webpackMissingModule (useResponsiveQuery.web.ts:2:1)
    at ./node_modules/native-base/lib/module/utils/useResponsiveQuery/useResponsiveQuery.web.js (useResponsiveQuery.web.ts:2:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/utils/useResponsiveQuery/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/hooks/useStyledSystemPropsResolver.js (useScreenReaderEnabled.ts:36:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/hooks/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/components/primitives/Box/index.js (index.ts:150:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/components/composites/AspectRatio/index.js (index.tsx:17:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/components/composites/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/native-base/lib/module/index.js (index.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.tsx (App.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (routing.tsx:98:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
 
```
    
After upgrade on first run i got the warning:
  
```
Please install @expo/webpack-config@^0.17.0 by running:

npx expo install @expo/webpack-config@^0.17.0
```

I installed that and ran Expo doctor with fix-deps too, but still the error persists on web. iOS is working fine on the mac simulator.
 
These are my dependencies:
 
 ```
  "dependencies": {
    "@expo/webpack-config": "^0.17.0",
    "expo": "^46.0.1",
    "native-base": "^3.4.9",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.3",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-svg": "12.3.0",
    "react-native-use-stored-state": "^0.2.3",
    "react-native-web": "~0.18.7",
    "react-router-dom": "^6.3.0",
    "react-router-native": "^6.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.18.0",
    "@types/jest": "^28.1.0",
    "@types/react": "^18.0.0",
    "@types/react-native": "^0.69.0",
    "@typescript-eslint/eslint-plugin": "^5.30.0",
    "@typescript-eslint/parser": "^5.30.0",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-react": "^7.30.0",
    "eslint-plugin-react-native": "^4.0.0",
    "jest": "^28.1.0",
    "prettier": "^2.7.0",
    "typescript": "^4.7.0"
  }
  ```
  
  what could be causing the issue?
  

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

46.0.1

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 3.2.1 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.0 
      expo: ^46.0.1 => 46.0.1 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 6.0.0
    Expo Workflow: managed

```

### Reproducible demo

Can be reproduced in this barebones repo: https://github.com/danielantelo/expo-template-reactrouter-nativebase/tree/expo-46

**Comment by danielantelo** [comment]
Expo doctor actually throws a warning about expo-configs

```
➜  expo-template-reactrouter-nativebase git:(expo-46) ✗ expo-cli doctor --fix-dependencies
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
```
forcing resolutions for config-plugins@5, gets rid of the warnings, but the web app still breaks with same error.

**Comment by amandeepmittal** [comment]
Hey @danielantelo, thanks for digging in with `expo doctor`. The issue here is that the nativebase library version `3.4.9` has compatibility issues with `react-native-web` 0.18 or above. After digging in their repo, I found that it's an open issue: https://github.com/GeekyAnts/NativeBase/issues/5075. I'd suggest taking a look into it there and following the [conversation](https://github.com/GeekyAnts/NativeBase/issues/5075#issuecomment-1179852818).

**Comment by danielantelo** [comment]
Thanks @amandeepmittal, will keep an eye out on that open issue.

**Comment by amandeepmittal** [comment]
Awesome @danielantelo. As an alternative, if your project requirements allow, you can still use Expo SDK 45 and native-base as a workaround for "web" for now.
