### ISSUE TITLE
Mail composer attachment error

### ISSUE THREAD

**Issue by BenGMiles** [expo/expo#1838]
See https://forums.expo.io/t/multiple-email-attachments/10246/4 for more info.

Adding multiple files to attachments for MailComposer causes an error and only sends 1 attachment.

### Environment
Linux/Android

### Steps to Reproduce

1. Add multiple files in assets folder
2. Load files in component mount using `Asset.fromModule(require('./assets/test.pdf')).downloadAsync();`
3. On button click, get local file URI's via `Asset.fromModule(require('./assets/test2.pdf')).localUri;`
4. Call MailComposer like:
```
MailComposer.composeAsync({
        recipients: ['test@example.com'],
        subject: 'Attachment Test',
        body: 'Testing multiple Attachments',
        attachments: [attachment1, attachment2]
    })
```

### Expected Behavior

When button is clicked email client opens with both attachments available. When email is sent both files should be received.

### Actual Behavior

When button is clicked following error shows in Logcat
```
Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
        at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1233)
        at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1024)
        at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:7159)
        at android.content.Intent.migrateExtraStreamToClipData(Intent.java:9904)
        at android.content.Intent.migrateExtraStreamToClipData(Intent.java:9867)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1794)
        at android.app.ContextImpl.startActivity(ContextImpl.java:879)
        at android.app.ContextImpl.startActivity(ContextImpl.java:856)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:367)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:367)
        at versioned.host.exp.exponent.modules.api.MailComposerModule.composeAsync(MailComposerModule.java:107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:764)
```
email client opens with 2 attachments but both have the same name, suggesting only one has been picked up. When email is sent only the first attachment is received.

### Reproducible Demo
https://snack.expo.io/rkchE4py7

**Comment by aalices** [comment]
A fix should be available with a minor release probably this week
