### ISSUE TITLE
SDK 44: `expo-asset` package lost `expo-file-system` in its `dependencies` but uses it

### ISSUE THREAD

**Issue by psnet** [expo/expo#18406]
### Summary

`expo-asset@8.4.6` (current version for SDK 44) has usage of `expo-file-system` module in its `build/PlatformUtils.js` file but doesnt have such dep in `package.json`. So sometimes npm can install `expo-file-system` as dep of `expo` but not in root `node_modules` so build at `gradlew` step will fail:
```ts
> Task :app:bundleReleaseJsAndAssets

warning: the transform cache was reset.

Welcome to Metro!

              Fast - Scalable - Integrated

...

[stderr] FAILURE: Build failed with an exception.

[stderr] * What went wrong:

[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.

[stderr] > Process 'command 'node'' finished with non-zero exit value 1

[stderr] * Try:

[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 1m 26s

Error: Unable to resolve module expo-file-system from /home/expo/workingdir/build/node_modules/expo-asset/build/PlatformUtils.js: expo-file-system could not be found within the project or in these directories:

  node_modules

If you are sure the module exists, try these steps:

 1. Clear watchman watches: watchman watch-del-all

 2. Delete node_modules and run yarn install

 3. Reset Metro's cache: yarn start --reset-cache

 4. Remove the cache: rm -rf /tmp/metro-*

  1 | import computeMd5 from 'blueimp-md5';

  2 | import Constants from 'expo-constants';

> 3 | import * as FileSystem from 'expo-file-system';

    |                              ^

  4 | import { NativeModulesProxy } from 'expo-modules-core';

  5 | import { getManifestBaseUrl } from './AssetUris';

  6 | // Constants.appOwnership is only available in managed apps (Expo client and standalone)

    at ModuleResolver.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)

    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)

    at Object.resolve (/home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:317:42)

    at resolve (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)

    at /home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26

    at Array.reduce (<anonymous>)

    at resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)

    at /home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33

    at Generator.next (<anonymous>)

    at asyncGeneratorStep (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)

info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED
```

so it can be cured by installing and deinstalling `expo-file-system`  into project but in normal way this dep should be added to `expo-asset`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.4 - 44.0.6

### Environment

https://github.com/expo/expo/blob/main/packages/expo-asset/src/PlatformUtils.ts#L4

### Reproducible demo

https://github.com/expo/expo/blob/main/packages/expo-asset/src/PlatformUtils.ts#L4

**Comment by Simek** [comment]
Hello @psnet, thank you for the report! 👍 

It looks like the issue has been fixed in this commit:
* https://github.com/expo/expo/commit/94de075611d1cfbfdf88e7cd069a1c1fb6bfec4f

Can you try to update `expo-asset` package to the latest version (`8.6.1`) to see if the problem no longer occur?

**Comment by psnet** [comment]
Latest recommended by `expo install` is version `expo-asset@8.4.6` for SDK 44, so maybe need to lift up allowed version
