### ISSUE TITLE
Branch: userCompletedAction() crashing in Expo client on Android

### ISSUE THREAD

**Issue by feelepxyz** [expo/expo#1841]
Seems like a Branch instance is not created in development when running Expo client on Android, this causes the app to blow up when calling `Branch.userCompletedAction('event', {})`.

This is only an issue on Android when running in development using the Expo client. No issues when running a standalone build.

### Reproduced in Snack
1. https://snack.expo.io/@hedvig-dev/debug-branch
2. Connect with Expo client on Android

### Error message

```
Attempt to invoke virtual method 'void io.branch.referral.Branch.a(java.lang.String, org.json.JSONObject)' on a null object reference
```

![screenshot_20180607-161332](https://user-images.githubusercontent.com/20165/41108273-6b221346-6a74-11e8-8b00-48beb2e69b33.png)

### Environment

```
[~/code/app]—[tags/app/1.3.8^0*] EXPO_DEBUG=true exp diagnostics
16:34:48 [exp] Generating diagnostics report...
16:34:48 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.1
  react: 16.4.0 => 16.4.0
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
-16:34:52 [exp] Request failed with status code 500
16:34:52 [exp] Error: Request failed with status code 500
    at createError (/Users/pmph/.nodenv/versions/9.11.1/lib/node_modules/exp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/pmph/.nodenv/versions/9.11.1/lib/node_modules/exp/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/pmph/.nodenv/versions/9.11.1/lib/node_modules/exp/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by hedvigoscar** [comment]
This issue is still present, any news?

**Comment by hugogrochau** [comment]
@feelepxyz 
I'm pretty sure that the Branch API only works in standalone builds. As per the documentation: https://docs.expo.io/versions/latest/sdk/branch.html

You could use the `__DEV__` global constant to check if you're running in development.

Ex:
```js
const  completeAction = (event) => {
  if (__DEV__) {
    return
  }

  Branch.userCompletedAction(event, {})
}
```

**Comment by sjchmiela** [comment]
That is 100%-true, @hugogrochau!
