### ISSUE TITLE
[ios] expo-firebase-analytics incompatibility with react-native-firebase/app

### ISSUE THREAD

**Issue by edgaraskazlauskas** [expo/expo#18450]
### Summary

After some investigation I found that there's an incompatibility between expo-firebase-analytics library and react-native-firebase libraries (which causes `pod install` to fail in the prebuild command):

https://github.com/expo/expo/blob/main/packages/expo-firebase-analytics/ios/EXFirebaseAnalytics.podspec#L5 must match https://github.com/invertase/react-native-firebase/blob/v15.2.0/packages/app/package.json#L68 

Currently the only matching `react-native-firebase/app` version is https://github.com/invertase/react-native-firebase/blob/v14.7.0/packages/app/package.json#L68, but it doesn't support ios platform's AppDelete being written in Objective C++, which it is written in when performing expo publish.

The support has been added in a later `react-native-firebase/app` version (https://github.com/invertase/react-native-firebase/blob/main/packages/app/plugin/src/ios/appDelegate.ts#L74), but expo's `expo-firebase-analytics` needs to catch up to match the firebase core pod version.

`expo prebuild --clean` logs:

```
[ios.dangerous]: withIosDangerousBaseMod: Cannot add Firebase code to AppDelegate of language "objcpp"
Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot add Firebase code to AppDelegate of language "objcpp"
    at /Users/edgarask/sites/ekk/firebase-demo/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js:71:23
    at action (/Users/edgarask/sites/ekk/firebase-demo/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:23)
    at interceptingMod (/Users/edgarask/sites/ekk/firebase-demo/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/edgarask/sites/ekk/firebase-demo/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at action (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:21)
    at interceptingMod (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at evalModsAsync (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
    at compileModsAsync (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
    at configureManagedProjectAsync (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:58:12)
    at prebuildAsync (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:88:21)
    at actionAsync (/Users/edgarask/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:34:3)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.0
    Expo Workflow: bare

### Reproducible demo

Since this is a bare project, I think a snack is not going to work, here's a minimal project with the issue reproducible: https://github.com/edgaraskazlauskas/expo-firebase-analytics-mismatch (both expo cli 5 and 6 don't work by the way).

**Comment by barthap** [comment]
You can patch-package `@react-native-firebase/app@14.7.0` by replacing the contents of the `node_modules/@react-native-firebase/app/plugin/build` directory with the contents of the same directory but from the `@latest` tag.

Also, the incompatibility related issue: #17543

**Comment by amandeepmittal** [comment]
Using latest `@react-native-firebase/app` and SDK 46 with `expo-firebase-analytics` should not be incompatible anymore since this was addressed in: https://github.com/expo/expo/pull/18908

I'm going to close this one now. Feel free to open it or create a new one if there is a version compatibility issue.

**Comment by mejokkurian** [comment]
Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot add Firebase code to AppDelegate of language "objcpp"
