### ISSUE TITLE
[SDK46] Can't build Android app on AppCenter if Hermes is enabled

### ISSUE THREAD

**Issue by TomCorvus** [expo/expo#18473]
### Summary

Hi 👋
Since I updated Expo to SDK46, I can't build Android app on AppCenter if Hermes is enabled.
Here the error:
```
> Task :expo-modules-core:configureCMakeRelWithDebInfo FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/***guide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
350 actionable tasks: 338 executed, 12 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeRelWithDebInfo'.
> C/C++: /Users/runner/work/1/s/node_modules/expo-modules-core/android/CMakeLists.txt release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  HERMES_LIB
      linked by target "expo-modules-core" in directory /Users/runner/work/1/s/node_modules/expo-modules-core/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 6s
Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
##[error]Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1
##[section]Finishing: Gradle Task
##[section]Starting: Checkout AwesomeProject@main to s
```

Its seems to be related to this new file in `expo-modules-core`: `CMakeLists.txt` but I don't know how to debug this and why it is here.
Since this PR: https://github.com/expo/expo/pull/16977

My main project is a monorepo but I can reproduce this error with a minimal repo. See below.
You can find the full report here:
[1_Build (1).txt](https://github.com/expo/expo/files/9250079/1_Build.1.txt)

Thanks

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.8.1
      expo-cli: 6.0.1
    Expo Workflow: bare
```

### Reproducible demo

https://github.com/TomCorvus/AwesomeProject

I just:
 - `expo init AwesomeProject`
 - `expo upgrade`
 - install and configure AppCenter

**Comment by skinnynpale** [comment]
same

**Comment by BrodaNoel** [comment]
I'm probably in the same situation.

```
The class is loaded from /home/expo/.gradle/caches/transforms-3/f9a6c4180d9d810f143b823eeeb39ba3/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
[stderr] 
e: /home/expo/workingdir/build/node_modules/react-native-purchases/android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt: (84, 44): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[stderr] 
The class is loaded from /home/expo/.gradle/caches/transforms-3/f9a6c4180d9d810f143b823eeeb39ba3/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
[stderr] 
e: /home/expo/workingdir/build/node_modules/react-native-purchases/android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt: (85, 43): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
```

**Comment by BrodaNoel** [comment]
Some minutes you just love programming. Just wait for the next task/bug 😂

**Comment by Kudo** [comment]
thanks @EdwardDrapkin! it's hard to find this kind of problem and you did it great!

**Comment by TomCorvus** [comment]
Thanks @EdwardDrapkin!
I see that HERMES_LIB is used by the latest version of react-native-reanimated 3.0.0 RC. Do you think your fix need to be applied on it too?

**Comment by TomCorvus** [comment]
Alright, thanks @EdwardDrapkin and @Kudo 👍

**Comment by KrisLau** [comment]
> I haven't had a chance to upgrade any of my projects to try the new version of reanimated, but based on a quick skim of their repository, it does seem like they might have the same issue. If you're getting the same error building that RC, try changing `task prepareHermes() {` to `task prepareHermes(dependsOn: createNativeDepsDirectories) {`. If you're not already familiar with it, you can use [patch-package](https://www.npmjs.com/package/patch-package) for stuff like this while you wait on fixes to get released. It's saved me a ton over the years.

@EdwardDrapkin I got a `Error: spawnSync git ENOBUFS` error when trying to use patch-package with this change

**Comment by KrisLau** [comment]
@TomCorvus @EdwardDrapkin @Kudo I applied the patch and still getting Execution failed for task ':expo-modules-core:configureCMakeRelWithDebInfo[arm64-v8a]'

**Comment by KrisLau** [comment]
@TomCorvus I was on expo 46.0.7 so I'll try that and leave a comment here if that works, thanks!

**Comment by TomCorvus** [comment]
@KrisLau Yes with expo-modules-core 0.11.4, dependency of expo 46.0.8

**Comment by ClaudionorJunior** [comment]
> #18518

hey @EdwardDrapkin I have your new fix in my project, but this don`t work for me, do you have any idea why I have this error?
```

Task :expo-modules-core:configureCMakeDebug[arm64-v8a] FAILED
C/C++: prefabcom.google.prefab.api.NoMatchingLibraryException: No compatible library found for //fbjni/fbjni. Rejected the following libraries:
C/C++: prefabandroid.arm64-v8a: User is using a static STL but library requires a shared STL
C/C++: prefabandroid.armeabi-v7a: User is targeting arm64-v8a but library is for armeabi-v7a
C/C++: prefabandroid.x86: User is targeting arm64-v8a but library is for x86
C/C++: prefabandroid.x86_64: User is targeting arm64-v8a but library is for x86_64
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
```
