### ISSUE TITLE
ExpoKit builds constantly failing

### ISSUE THREAD

**Issue by ahmetabdi** [expo/expo#1856]
```
~/Projects/ios/dummy ~/Projects/ios/dummy/ios
Error: getaddrinfo ENOTFOUND d1wp6m56sqw74a.cloudfront.net d1wp6m56sqw74a.cloudfront.net:443
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
Command /bin/sh failed with exit code 1
```

I constantly get the above error in iOS and Android detached mode when compiling with xCode and andriod studio

**Comment by terribleben** [comment]
Are you able to reach that address in your browser?

**Comment by ahmetabdi** [comment]
@terribleben  Yes when I go there it returns this XML

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3B5B2F6F1AF9F3ED</RequestId>
<HostId>
Lm5Mk/oTFhYqdOO6wiGDdNF9M97AHMBeNLjqLgyOJ2LTioN/KW2WUrL1oFbWbT1Qr3jVPcUwP30=
</HostId>
</Error>
```

I can also ping the hostname

```
ping d1wp6m56sqw74a.cloudfront.net                                                                                                                                      08:44:18
PING d1wp6m56sqw74a.cloudfront.net (52.222.233.207): 56 data bytes
64 bytes from 52.222.233.207: icmp_seq=0 ttl=248 time=4.232 ms
64 bytes from 52.222.233.207: icmp_seq=1 ttl=248 time=4.176 ms
64 bytes from 52.222.233.207: icmp_seq=2 ttl=248 time=5.630 ms
```

I've noticed if I keep trying to do a build like 20x times it does eventually succeed

**Comment by miraan** [comment]
I'm also getting this error building in Android Studio. Going to the url https://d1wp6m56sqw74a.cloudfront.net in my browser gives me:

AccessDeniedAccess DeniedB84DFD11D7A81425Cd/c24boapO46fL6NMUoIqN/FIdzLFE51zfyM2SSlzazMnZp3+5UCSi0wnDdNpKiTJQGACA2pUA=

**Comment by miraan** [comment]
I tried building again from Android Studio, but this time just used the V1 (Jar Signature) Signature Version on the final step of the 'Generated Signed APK' dialog, and it worked. Not sure if this was related to the problem

**Comment by tunguyenbhtech** [comment]
I also can't 'Generated Signed APK' with voth V1 and V2 signature but
According to this link: [signature help](https://developer.android.com/about/versions/nougat/android-7.0.html#apk_signature_v2)

APK Signature Scheme v2 offers:

Faster app install times

> More protection against unauthorized alterations to APK files.
> Android 7.0 introduces APK Signature Scheme v2, a new app-signing scheme that offers faster app install times and more protection against unauthorized alterations to APK files. By default, Android Studio 2.2 and the Android Plugin for Gradle 2.2 sign your app using both APK Signature Scheme v2 and the traditional signing scheme, which uses JAR signing.

It is recommended to use APK Signature Scheme v2 but is not mandatory.

> Although we recommend applying APK Signature Scheme v2 to your app, this new scheme is not mandatory. If your app doesn't build properly when using APK Signature Scheme v2, you can disable the new scheme.

so i still want to sign my app using V2 signature

**Comment by tunguyenbhtech** [comment]
I've builded successfully by using US vpn (i'm in Vietnam). Seems like the url is location restricted

**Comment by atothewest** [comment]
@terribleben any updates/ideas regarding this issue? 

It's a big problem that is turning building Expo apps into a bit of a lottery for our team (UK based).

**Comment by ide** [comment]
Hi, this is an overview of what network connections the Expo dev tools need to make and which network settings they load so you can make the necessary configuration changes on your ends.

### Servers

- The Expo service for logging in, publishing, and fetching the app manifest is hosted by Google Cloud, specifically in the US. The server is https://expo.io and at the time of this writing the IP address should not vary between people looking to connect to it.
- Published JS bundles are served using AWS CloudFront, specifically a worldwide distribution. At the time of this post, that server is https://d1wp6m56sqw74a.cloudfront.net. The IP address will vary between people because AWS tries to connect clients to a server that is geographically nearby to reduce latency and flakiness.
- You must be able to connect to both of these servers. They are hosted by two of the world's leading hosting providers and use fairly common configurations so unless AWS and GCP are blocked for you, you shouldn't have do anything special.
- Expo doesn't restrict requests based on location; if this is happening it's probably between your computer, your ISP, and GCP.
- Pragmatically speaking we're going to keep using GCP and AWS since they are so standard and work for huge parts of the internet. (We do recognize that sometimes enterprises have internal firewall rules, for example, and are thinking about ways to address that without changing our cloud infrastructure.)

### Client network configuration

- The Expo dev tools use Node.js's networking stack (e.g. you can see `dns.js` in the stack trace above in this issue).
- They also look for the `http_proxy` and `https_proxy` environment variables (and their all-caps counterparts) and attempt to honor those. So if you find yourself able to connect to expo.io and d1wp6m56sqw74a.cloudfront.net with other programs, perhaps the issue is with a proxy.

These are the basic requirements and description of the dev tools' network connections. If you are experiencing issues, the solution depends on your computer, your network configuration (ex: firewall, proxies), and your internet connection (ex: ISP) and often two people experiencing similar ambiguous symptoms have two different root causes. So the thing we can do to help is to describe how Expo's side works to give you the knowledge to diagnose and fix the actual cause.

**Comment by lilosir** [comment]
Same issue on IOS, I tried 5 times, it successfully archived... BTW, I could't access the url, but I can access the JS bundle url

**Comment by llamaluvr** [comment]
I've experienced this issue about a dozen times over the past month. I'm not on a VPN, proxy, or corporate network, just my personal mac working remotely. It usually happens 1-3 times in a row- I keep restarting the build and it eventually goes through. It's happened to me on several different home and public wifi networks I've connected to in both Ohio and Indiana. On each occasion, I did not perceive anything else wrong with my network connection (i.e., I was browsing to other sites just fine, no blips in the music streaming in the background, etc.). I do have around 100-150 image assets in my app.

This morning, it happened three times in a row on an Android build. After that, I decided to run some pings to see if the connection was interrupted. On 500 pings, I had 0.7% packet loss (request timed out errors) going to d1wp6m56sqw74a.cloudfront.net. Then I tried both goole.com and d1wp6m56sqw74a.cloudfront.net for about 1000 pings. This time, 0.6% on google and 0.2% on cloudfront.

I'm not big into networking, but from googling around it sounds like that amount of packet loss on wifi is generally not a major cause for concern and generally shouldn't have adverse effects perceptible to a user. It doesn't seem like something specific to cloudfront/ AWS. From here, it seems like perhaps this process has a rather low tolerance for a momentary blip in the network. Since it's built on standard node.js networking, curious if anyone knows of any way to increase the timeout on the OS or node.js side (e.g., something any of us can do now without there being retry logic added to this build phase).
