### ISSUE TITLE
[expo-calendar] Failed to create a monthly event with "daysOfTheMonth"

### ISSUE THREAD

**Issue by ytakzk** [expo/expo#18617]
### Summary

Failed to create a monthly event because the value of `daysOfTheMonth` was lost in `stringifyDateValues(obj)`.

```
const event = {
  title: 'test',
  startDate: new Date(),
  allDay: true,
  recurrenceRule: {
    daysOfTheMonth: [1],
    frequency: "monthly",
  },
}
```

This is a simple example of creating an event that occurs on the first of each month, however `daysOfTheMonth` cannot be mapped correctly through `stringifyDateValues(obj)`:

https://github.com/expo/expo/blob/54b2c8c7e4d619b3ea0f6ad60dc4765079346f2b/packages/expo-calendar/src/Calendar.ts#L1345-L1347

The should be something like this to check if the values in an array are objects or primitive values, with which I can successfully save the event.
```
if (Array.isArray(value)) {
  if (value.length == 0 || typeof value[0] == 'object') {
    // for objects i.e, dictionaries
    return { ...acc, [key]: value.map((stringifyDateValues)) };
  } else {
    // for primitive values
    return { ...acc, [key]: value }
  }
}
```

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.n/bin/node
      Yarn: 1.22.19 - ~/.n/bin/yarn
      npm: 8.11.0 - ~/.n/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed
```

### Sample code

```JavaScript
const calendarId = "{{ any calendar id }}";

const dic = {
  title: 'test',
  startDate: new Date(),
  allDay: true,
  recurrenceRule: {
    daysOfTheMonth: [1],
    frequency: "monthly",
  },
}

await ExpoCalendar.createEventAsync(calendarId, dic)
```

### error raised

Apparently, the value in `daysOfTheMonth` is missing.

```
An exception was thrown while calling `ExpoCalendar.saveEventAsync` with arguments `(
        {
        allDay = 1;
        calendarId = "7AF8B579-A6D1-49A7-A774-AE2A76D943D1";
        recurrenceRule =         {
            daysOfTheMonth =             (
                                {
                }
            );
            frequency = monthly;
        };
        startDate = "2022-08-12T05:35:11.702Z";
        title = test;
    },
        {
    }
)`: -[__NSDictionaryM integerValue]: unrecognized selector sent to instance 0x600002c41160
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-calendar/build/Calendar.js:203:11 in createEventAsync
at node_modules/expo-calendar/build/Calendar.js:183:7 in createEventAsync
at src/models/event.ts:77:38 in Event.create
at src/models/event.ts:54:4 in Event.create
at src/screens/eventInsert/eventInsertScreeen.tsx:213:18 in upsert
at src/screens/eventInsert/eventInsertScreeen.tsx:138:4 in upsert
at src/screens/eventInsert/eventInsertScreeen.tsx:229:41 in ButtonElement.props.onPress
at node_modules/react-native-elements/src/buttons/Button.js:37:13 in handleOnPress
at node_modules/react-native/Libraries/Pressability/Pressability.js:702:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:639:6 in _receiveSignal
at node_modules/react-native/Libraries/Pressability/Pressability.js:520:8 in responderEventHandlers.onResponderRelease
```

**Comment by AchrafBn** [comment]
I'm having this exact same issue, @ytakzk  Did you find the solution ?

**Comment by ytakzk** [comment]
@AchrafBn I should send a PR, but I am too lazy to do this, so I just copied `expo/packages/expo-calendar/src/Calendar.ts` to my local directory and modified the `stringifyDateValues` as follows to avoid the problem.
Then import the copied `Calendar.ts`, not the one under `node_modules`. 

```
function stringifyDateValues(obj: object): object {
  return Object.keys(obj).reduce((acc, key) => {
      const value = (obj as any)[key];
      console.log('-----')
      console.log(key, value)
      console.log(stringifyIfDate(value))
      if (value != null && typeof value === 'object' && !(value instanceof Date)) {
          if (Array.isArray(value)) {
              if (value.length == 0 || typeof value[0] == 'object') {
                  return { ...acc, [key]: value.map((stringifyDateValues)) };
              } else {
                  return { ...acc, [key]: value }
              }
          }
          return { ...acc, [key]: stringifyDateValues(value) };
      }
      (acc as any)[key] = stringifyIfDate(value);
      return acc;
  }, {});
}
```

**Comment by jmn6554** [comment]
bump
