### ISSUE TITLE
exp build:ios -e -c failed – `build_failure!’: [!] Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure) 

### ISSUE THREAD

**Issue by zhaozhiming** [expo/expo#1877]
Hi, I use command `exp build:ios -e -c` to build ios ipa file.
But I get the error as follow and I don’t known what it mean.
Please help. Thanks.

PS: I use the same upload files and build successful last week, but it failed today.

```
generating IPA...
[stderr] /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': [!] Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure)
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/error_handler.rb:112:in `handle_package_error'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/runner.rb:121:in `block in package_app'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/command_executor.rb:93:in `execute'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/runner.rb:117:in `package_app'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/runner.rb:27:in `run'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/manager.rb:19:in `work'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/commands_generator.rb:44:in `block (2 levels) in run'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/commands_generator.rb:75:in `run'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/gym/lib/gym/commands_generator.rb:15:in `start'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/bin/fastlane:20:in `<top (required)>'
[stderr] 	from /usr/local/bin/fastlane:23:in `load'
[stderr] 	from /usr/local/bin/fastlane:23:in `<main>'
[stderr] [01:41:31] 'ios:build-and-sign-ipa' errored after 4.33 min
[stderr] [01:41:31] Error: Process exited with non-zero code: 1
[stderr]     at ChildProcess.child.on (/usr/local/turtle-agent/tools-public/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
[stderr]     at emitTwo (events.js:125:13)
[stderr]     at ChildProcess.emit (events.js:213:7)
[stderr]     at maybeClose (internal/child_process.js:927:16)
[stderr]     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

My build id is: 93b45e87-e83b-4c2a-b3c5-d3a8f2b304c3
My env:  

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: 1.5.1
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2
```

**Comment by casperstr** [comment]
Got the exact same error

**Comment by leesiongchan** [comment]
Got the same error without `-e` and manual certs upload. Is this the expo server issue or my cert problem?

**Comment by leesiongchan** [comment]
Ok for me apparently is because of the ad hoc provisioning cert. As exp is currently not supporting ad hoc build.

**Comment by johanroureb** [comment]
any update?

**Comment by zhaozhiming** [comment]
My problem was solved. Thanks. @dsokal   
More detail see:  #1893
