### ISSUE TITLE
Fatal Exception when `expo-av` used with `react-native-track-player`

### ISSUE THREAD

**Issue by KrisLau** [expo/expo#18937]
### Summary

I get a fatal exception when I call `createAsync` when `expo-av` used with `react-native-track-player`. It crashes without throwing an error so I only got the log on Android Studio logcat

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appname, PID: 17129
    java.lang.RuntimeException: Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@c92725: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
        at android.app.ActivityThread.handleStopService(ActivityThread.java:4375)
        at android.app.ActivityThread.access$1900(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1956)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
        at com.doublesymmetry.trackplayer.service.MusicService.onDestroy(MusicService.kt:471)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:4355)
        at android.app.ActivityThread.access$1900(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1956) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

### What platform(s) does this occur on?

Android

### Environment

```
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 54.57 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Minimal reproducible example
https://github.com/KrisLau/reproExoplayer

**Comment by KrisLau** [comment]
@Kudo @TomCorvus @nomi9995

**Comment by KrisLau** [comment]
https://github.com/doublesymmetry/react-native-track-player/issues/1678 suggests that it might be a version mismatch for exoplayer

**Comment by KrisLau** [comment]
@Kudo @TomCorvus @nomi9995 @brentvatne @mnightingale

**Comment by Kudo** [comment]
@KrisLau you could add the following gradle expression to `android/app/build.gradle` for pinning down the exoplayer version

```gradle
configurations.all {
    resolutionStrategy {
        force 'com.google.android.exoplayer:exoplayer:2.18.1', 'com.google.android.exoplayer:extension-okhttp:2.18.1'
    }
}
```

**Comment by KrisLau** [comment]
@Kudo Doing so crashes the app with
```
```

**Comment by Kudo** [comment]
@KrisLau oh that's bad. i'm accepting this issue and plan to upgrade exoplayer. thanks for reporting this.

**Comment by KrisLau** [comment]
@Kudo No thank you for all the work you guys put in, I really appreciate it!

**Comment by fbotalla** [comment]
Same exact problem here.
Thank you for working on this issue @Kudo!

Is there an ETA on this ? no rush or stress, just trying to decide a few things based on its timing.

**Comment by KrisLau** [comment]
@fbotalla hey just thought I'd let you know that it is just waiting to be merged so it should be done soon https://github.com/expo/expo/pull/19332

**Comment by fbotalla** [comment]
So now do we just have to wait until the expo-av gets published?

**Comment by KrisLau** [comment]
@fbotalla yeah basically but I'm not sure which version it is releasing in and when. you could also just use patch-package in the meantime

**Comment by KrisLau** [comment]
@Kudo Just out of curiosity is there a way to see the estimated date for a version to be released?

**Comment by fbotalla** [comment]
@KrisLau It's out for beta testing at the moment.

**expo-av@13.0.0-beta.1**

I tested it and it worked as expected.. so that's great news!

**Comment by KrisLau** [comment]
@fbotalla Oh that's good! i did a `yarn outdated` and couldn't see it hahah I'll try it in a second

**Comment by Kudo** [comment]
> Oh that's good! i did a `yarn outdated` and couldn't see it hahah I'll try it in a second

because it's for sdk 47 which will be open to beta 😅

**Comment by fbotalla** [comment]
@KrisLau 
I also had to use 
**expo@47.0.0-alpha.1**
in order to use expo-av properly in my tests. 

But from my tests it has been working like a champ.. so.. thank you @Kudo !

**Comment by KrisLau** [comment]
Ohh ok sorry for all the trouble and thanks for all the help @Kudo @fbotalla

**Comment by Kudo** [comment]
as expo sdk 47 is released, i'm closing this issue. thanks for everyone to report this.
