### ISSUE TITLE
Metro bundler fails on Ubuntu during publish, works on macOS

### ISSUE THREAD

**Issue by 0xClpz** [expo/expo#1922]
### Environment

[12:10:11] Generating diagnostics report...
[12:10:11] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: Linux 4.4 (Ubuntu 16.04)
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/test6565-2018-576ad7c9-13ab-4d7a-b993-de91de6cc8c0.tar.gz

### Steps to Reproduce

When trying to publish the expo app from my Ubuntu server, the process crashes without any useful information to debug, it publishes just fine on any OSX machine though

### Expected Behavior

Publish the app just fine, it works without any issue 
### Actual Behavior

Output after running EXPO_DEBUG=true exp publish

[12:13:41] Unable to find an existing exp instance for this directory, starting a new one...
[12:13:48] Starting Metro Bundler on port 19001.
[12:13:49] Metro Bundler ready.
[12:13:50] Tunnel ready.
[12:13:50] Publishing to channel 'default'...
[12:13:57] Building iOS bundle
[12:14:00] 500 - "{\"type\":\"InternalError\",\"errors\":[],\"message\":\"Metro Bundler has encountered an internal error, please check your terminal error output for more details\"}"
[12:14:00] StatusCodeError: 500 - "{\"type\":\"InternalError\",\"errors\":[],\"message\":\"Metro Bundler has encountered an internal error, please check your terminal error output for more details\"}"
    at new StatusCodeError (/usr/lib/node_modules/exp/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/exp/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/exp/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/exp/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/exp/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/exp/node_modules/request/request.js:1079:12)
Building JavaScript bundle [===========================================================================                         ] 75%ub

**Comment by Nesqwik** [comment]
Hello !

Same issue here...

Its working on my linux but if i try to publish within a docker container (for my gitlab-CI), i got the error : 

> $ export EXPO_DEBUG=true && exp publish
> [14:19:27] Publishing to channel 'default'...
> [14:19:29] Building iOS bundle
> [14:19:29] 500 - "{\"type\":\"InternalError\",\"errors\":[],\"message\":\"Metro Bundler has encountered an internal error, please check your terminal error output for more details\"}"
> [14:19:29] StatusCodeError: 500 - "{\"type\":\"InternalError\",\"errors\":[],\"message\":\"Metro Bundler has encountered an internal error, please check your terminal error output for more details\"}"
>     at new StatusCodeError (/usr/local/lib/node_modules/exp/node_modules/request-promise-core/lib/errors.js:32:15)
>     at Request.plumbing.callback (/usr/local/lib/node_modules/exp/node_modules/request-promise-core/lib/plumbing.js:104:33)
>     at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/exp/node_modules/request-promise-core/lib/plumbing.js:46:31)
>     at Request.self.callback (/usr/local/lib/node_modules/exp/node_modules/request/request.js:185:22)
>     at emitTwo (events.js:126:13)
>     at Request.emit (events.js:214:7)
>     at Request.<anonymous> (/usr/local/lib/node_modules/exp/node_modules/request/request.js:1161:10)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/exp/node_modules/request/request.js:1083:12)

I tried with two different docker images, node:8 and node:8-alpine, same issue. 

Environment: node:8-alpine    (**NOT** working)
>   OS: Linux 4.4
>   Node: 8.11.4
>   Yarn: 1.6.0
>   npm: 5.6.0
>   Watchman: Not Found
>   Xcode: N/A
>   Android Studio: Not Found
> 
> Packages: (wanted => installed)
>   expo: ^28.0.1 => 28.0.1
>   react: 16.3.1 => 16.3.1
>   react-native: ~0.55.4 => 0.55.4
> 
> Diagnostics report:
>   https://exp-xde-diagnostics.s3.amazonaws.com/louis-energic-f8e500b5-e3c4-4462-833a-c29a3f80d7d4.tar.gz

Environment: My linux (Working)
>   OS: Linux 4.4
>   Node: 8.11.2
>   Yarn: 1.9.4
>   npm: 5.6.0
>   Watchman: 4.7.0
>   Xcode: N/A
>   Android Studio: Not Found
> 
> Packages: (wanted => installed)
>   expo: ^28.0.1 => 28.0.1
>   react: 16.3.1 => 16.3.1
>   react-native: ~0.55.4 => 0.55.4
> 
> Diagnostics report:
>   https://exp-xde-diagnostics.s3.amazonaws.com/louis-energic-4cc9559b-5e84-4b04-ae9a-2c5f12d8f5bb.tar.gz

I think it started to crash when i upgrade expo from 27 to 28.

**Comment by dmydry** [comment]
Hello guys! Same issue here. Trying to deploy with GitLab CI following the example here https://docs.expo.io/versions/v31.0.0/guides/setting-up-continuous-integration

The stack trace is the same as @Nesqwik has.
Except I'm using next packages versions:
```
"expo": "31.0.4",
"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
"expo-cli": "^2.6.5",
```

**Comment by cruzach** [comment]
Hi! Are you guys still seeing this problem? I'd make sure that you've followed the docs:
> Windows users must have WSL enabled. You can follow the installation guide [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10). We recommend picking Ubuntu from the Windows Store. Be sure to launch Ubuntu at least once. After that, use an Admin powershell to run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

If you are still seeing this, lmk and also please run `expo diagnostics` and paste the output here

**Comment by netpoe** [comment]
Getting a "socket hang up" error on Ubuntu 18.04 LTS:

```
$ expo publish --release-channel somename
Unable to find an existing Expo CLI instance for this directory, starting a new one...
Starting Metro Bundler on port 19001.
Tunnel ready.
Publishing to channel 'roysterladonnagmailcom'...
Building iOS bundle
We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN.
› Closing Expo server
› Stopping Metro bundler
socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Building JavaScript bundle [==================                                                                                  ] 18%#
```

```
$ expo diagnostics
npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      @types/expo: ^32.0.9 => 32.0.13
      @types/react: ^16.8.10 => 16.9.8
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.6 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.4.1

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

My `app.json`

```
{
  "expo": {
    "name": "My App",
    "slug": "acp-5-6-11",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./src/assets/images/icon.png",
    "splash": {
      "image": "./src/assets/images/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "updates": { "fallbackToCacheTimeout": 0 },
    "assetBundlePatterns": ["**/*"],
    "ios": { "supportsTablet": false },
    "extra": { "CONTEXT": "staging" },
    "description": "desc",
    "packagerOpts": {
      "nonPersistent": true
    }
  }
}
```

**Comment by cruzach** [comment]
@netpoe I don't think that's related to this issue, I recommend you take a look at [this forum thread](https://forums.expo.io/t/cant-expo-publish-socket-hang-up/18080/3) for the fix/reason

Closing this for inactivity. If you still see this error on a more recent version fo expo-cli, please open a new issue with a method to reproduce it 👍
