### ISSUE TITLE
App crashes on redirect back on AuthSession to Android detached app (sdk 27)

### ISSUE THREAD

**Issue by dlndev** [expo/expo#1928]
Following the discussion started in issue #1703 , 
I have an app that was detached from Expo. 
After detaching, first the app didn't redirected back to the app at AuthSession.
Updating the scheme in the AndroidManifest.xml to the latest advise 

> <activity
>         android:name="net.openid.appauth.RedirectUriReceiverActivity"
>         tools:node="replace">
>       <intent-filter>
>         <data android:scheme="expe3d1afcbafc44b40b3550fcb48ff955a"/>
> 
>         <action android:name="android.intent.action.VIEW"/>
>         <category android:name="android.intent.category.DEFAULT"/>
>         <category android:name="android.intent.category.BROWSABLE"/>
>       </intent-filter>
>       <intent-filter>
>         <action android:name="android.intent.action.VIEW"/>
>         <category android:name="android.intent.category.DEFAULT"/>
>         <category android:name="android.intent.category.BROWSABLE"/>
>         <data android:scheme="com.****.*******" android:path="oauthredirect"/>
>       </intent-filter>
>     </activity>

didn't solve it, the app still crashes. 
here's the full log from from the logs (adb logcat -v time)

```
06-28 05:36:33.514 E/AndroidRuntime( 7402): java.lang.RuntimeException: Unable to resume activity {com.dealna.dealnaapp/net.openid.appauth.AuthorizationManagementActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3400)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.os.Handler.dispatchMessage(Handler.java:102)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.os.Looper.loop(Looper.java:154)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.ActivityThread.main(ActivityThread.java:6077)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at java.lang.reflect.Method.invoke(Native Method)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
06-28 05:36:33.514 E/AndroidRuntime( 7402): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1516)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.Activity.startActivityForResult(Activity.java:4224)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.Activity.startActivityForResult(Activity.java:4183)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.Activity.startActivity(Activity.java:4507)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.Activity.startActivity(Activity.java:4475)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at net.openid.appauth.AuthorizationManagementActivity.onResume(AuthorizationManagementActivity.java:200)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.Activity.performResume(Activity.java:6766)
06-28 05:36:33.514 E/AndroidRuntime( 7402):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
```

**Comment by dlndev** [comment]
@esamelson , I had a thought that might lead somewhere.
Are there required parameters on the server response to auth.expo.io ?
As we build the response in our server, we use our internal query string params.
Before the detachment it worked fine, but after detaching, the casting might be stricter and it cause the app to crash.

Is there a format that the Expo expects of the server response, that we must follow?

**Comment by esamelson** [comment]
Hi @dlndev - there should be no difference between a plain and detached app, so if your server response worked before detaching, it should work after. It's more likely that there's still something wrong with your app's configuration. Could you try reproducing this on a blank detached app?

Also maybe worth noting that google tells me the error you're getting seems to result from devices that don't have Google Play Services installed. Are you by any chance testing on a different device than before?

**Comment by dlndev** [comment]
Thanks @esamelson for your reply.
Unfortunately, it didn't work.

We went back to the prior to the detach version on GIT.
Ran the app on Expo on the Emulator, logged in, and afterwards expo redirected smoothly.

Then we did detach, these are the messages we got from the detach process:

> PS C:\b4_detach> exp detach
> Validating project manifest...
> Skipping iOS because you are not running macOS.
> Moving Android project files...
> Downloading Android code...
> Updating Android app...
> { buildPhase: 'running shell app modifications' } 'Warning: No config file specified.'
> (node:16152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: (_fsExtra || _load_fsExtra(...)).default.copyFileSync is not a function
> Cleaning up Android...
> There was an issue cleaning up, but your project should still work. You may need to manually remove C:\b4_detach\temp-android-directory. (Error: ENOTEMPTY: directory not empty, rmdir 'C:\b4_detach\temp-android-directory\app\src\devRemoteKernel')
> Android detach is complete!
> 
> Writing ExpoKit configuration...
> Finished detaching your project! Look in the `android` and `ios` directories for the respective native projects. Follow the ExpoKit guide at https://docs.expo.io/versions/latest/guides/expokit.html to get your project running.


The manifest was generated with the first section:
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.****.*******" android:path="oauthredirect"/>
      </intent-filter>
    </activity>
```

we ran the app again on the same emulator, logged in, but the app was stuck on the return to app (link didn't help).

we added to the manifest.xml the additional block, you've previously mentioned (with the new app identifier):
```
    <activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
      <intent-filter>
        <data android:scheme="expde7c7b0260e145cdb50b0bbdfb4366fd"/>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.****.*******" android:path="oauthredirect"/>
      </intent-filter>
    </activity>
```
but still, nothing happened, but as the first attempt, linking back to the app failed.

However, this time the change didn't make the app crash, as before, but still the same state, unresponsive to link back to the app.

the emulator log shows: 

> "Navigation is unreachable: expde7c7b0260e145cdb50b0bbdfb4366fd://+expo-auth-session?userId=****&regToken=dbac80e6-e5fa-4b17-9331-94cf8971e083&type=success", source: https://auth.expo.io/@***/*******?userId=****&regToken=dbac80e6-e5fa-4b17-9331-94cf8971e083&type=success (0)

**Comment by esamelson** [comment]
Hi @dlndev - sorry, I'm realizing now I was not clear in my original message in the other thread. You need to put the intent-filter inside of the `MainActivity` <activity> tag, not the `RedirectUriReceiverActivity` tag.

You should end up with something like this:
```
    <activity
      android:name=".MainActivity"
      android:launchMode="singleTask"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:theme="@style/Theme.Exponent.Splash"
      android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <data android:scheme="expde7c7b0260e145cdb50b0bbdfb4366fd"/>

        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>

        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>

...

    <activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="host.exp.imageperf" android:path="oauthredirect"/>
      </intent-filter>
    </activity>
```

Sorry again for the confusion!! I am wondering if you might be running an outdated version of `exp` and that is why this is not happening automatically? And which SDK version are you running?

**Comment by dlndev** [comment]
It was a long run. We did this change with sdkVersion 26.0.0, which doesn't generate the manifest automatically. After changing the manifest according to your advice, on pressing return to app, the response had an impact, but led to the app restarted, and the auth message was not delivered to the react-native code.
Tried again, this time we started by upgrading Expo to 28.0.0, but leaving the Scheme in the app.json before the detach. Again, the app was stuck and didn't redirected.

Last, we upgraded to v27.0.0 and removed the scheme param from the app.json, so a new scheme was generated on detaching. 
The manifest was generated automatically right, and the **redirect worked fine**!

**Comment by esamelson** [comment]
Hi @dlndev - glad to hear you got it resolved! Sorry the path was so painful. We'll look into why the manifest was not generated properly with SDK 26. Let us know if you run into this issue again the future.
