### ISSUE TITLE
Android java.lang.RuntimeException: abi27_0_0.com.facebook.react.uimanager.IllegalViewOperationException:

### ISSUE THREAD

**Issue by wpconsulate** [expo/expo#1931]
#Issue
I don't know how to debug on Android device. But When I'm testing the App on Android in Development Mode or on Emulator. App is Crashing right away. 

I tried generating the APK file where App works at first then crashes after Login Screen. Crash Log is same.

Now I don't know how to debug an find out what's wrong in the code ( FYI: App works fine on iOS )
Below is the debug Log

java.lang.RuntimeException: abi27_0_0.com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 25
 detail: View tag:32
  children(0): [
 ],
  viewsToAdd(1): [
[0,25],
 ],

	at abi27_0_0.com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:311)
	at abi27_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at abi27_0_0.com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
	at abi27_0_0.com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1024)
	at android.view.Choreographer.doCallbacks(Choreographer.java:838)
	at android.view.Choreographer.doFrame(Choreographer.java:766)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:171)
	at android.app.ActivityThread.main(ActivityThread.java:6684)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: abi27_0_0.com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 25
 detail: View tag:32
  children(0): [
 ],
  viewsToAdd(1): [
[0,25],
 ],

	at abi27_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:308)
	at abi27_0_0.com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
	at abi27_0_0.com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
	at abi27_0_0.com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
	at abi27_0_0.com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
	at abi27_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988)
	at abi27_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	... 13 more

### Demo
can be tested here
https://expo.io/@iterationgroup/petmeds

  
### Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/iterationgroup-794d4b54-9302-4970-93fb-c2ee2d7e5cf3.tar.gz

**Comment by wpconsulate** [comment]
I further tried to debug this and got this error http://prntscr.com/k0hkwl
