### ISSUE TITLE
Running any `exp push:android` command yields "An unknown error occurred."

### ISSUE THREAD

**Issue by AbdulazizGH** [expo/expo#1936]
### Environment

Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/abdulazizgh-53db38f6-f342-41ff-94af-fa4874a166fc.tar.gz

### Steps to Reproduce

1. Run `exp push:android:show` or `exp push:android:clear` or `exp push:android:upload --api-key <KEY>`

### Expected Behavior

Show, clear, or upload android keys depending on executed command.

### Actual Behavior

Displays "An unknown error occurred."

### Additional information

Upon debugging the expo CLI code, I found that the returned APIV2Error to indicate a server error:
```
{ ApiV2Error: An unknown error occurred.
    at C:\xdl@50.4.2\src\ApiV2.js:203:19
    at Generator.throw (<anonymous>)
    at step (npm\node_modules\exp\node_modules\xdl\build\ApiV2.js:48:191)
    at \npm\node_modules\exp\node_modules\xdl\build\ApiV2.js:48:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'INTERNAL_SERVER_ERROR',
  _isApiError: true,
  serverStack: undefined,
  details: undefined }
```

**Comment by AbdulazizGH** [comment]
@quinlanj Thank you so much for the quick response. Good luck!
