### ISSUE TITLE
Expo Go crashed after upgraded to SDK 46

### ISSUE THREAD

**Issue by alickcai** [expo/expo#19568]
### Summary

Followed instruction from https://blog.expo.dev/expo-sdk-46-c2a1655f63f7
I upgraded SDK 46 as well as Expo Go (to 2.25.2) but failed to start App anymore.

Error message when Expo Go terminal (physical phones android & ios) was trying to connect local server:
=============================================================

 ERROR  TypeError: undefined is not an object (evaluating 'navigator.userAgent.match')
Error: ENOENT: no such file or directory, open 'D:\Sunflower\webpackUniversalModuleDefinition@http:\192.168.2.105:19000\node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (D:\Sunflower\node_modules\metro\src\Server.js:979:18)
    at Server._symbolicate (D:\Sunflower\node_modules\metro\src\Server.js:1052:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (D:\Sunflower\node_modules\metro\src\Server.js:443:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Sunflower\\webpackUniversalModuleDefinition@http:\\192.168.2.105:19000\\node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false'
}

### What platform(s) does this occur on?

Android, iOS

### Environment

    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^46.0.16 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.9 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

import "expo-dev-client";
import React from "react";
import { View } from "react-native";
import ErrorBoundary from "react-native-error-boundary";
import SctxtProvider from "./se-context/keyResource/SctxtProvider";
import * as sc from "./sb-const/basic/Sconstant";
import * as sw from "./sc-ui/widget/Swidget";
import { Styles } from "./sc-ui/style/Styles";
import AppSF from "./AppSF";

function App() {
  const CustomFallback = (props) => {
    return (
      <View style={Styles.customFallback}>
        <sw.StextM content={sc.SysMsg.exception} style={Styles.customFallbackTitle}></sw.StextM>
        <sw.StextS content={props.error.toString()} style={Styles.customFallbackError}></sw.StextS>
        <sw.ButtonText onPress={props.resetError} title={sc.Sphrase.retry} />
      </View>
    );
  };

  return (
    <ErrorBoundary FallbackComponent={CustomFallback}>
      <SctxtProvider>
        <AppSF></AppSF>
      </SctxtProvider>
    </ErrorBoundary>
  );
}

export default App;

**Comment by alickcai** [comment]
it's caused by package cos-js-sdk-v5, closed this issue
