### ISSUE TITLE
`npx expo run:android` build failed

### ISSUE THREAD

**Issue by StephenChips** [expo/expo#19614]
#### Background

I installed a mapview library `@rnmapbox/maps` to my project. Since it contains native codes, I have to create a development build for debugging. I followed the guide on Expo's official website, installed `OpenJDK 11` then type in `npx expo run:android`. Sadly, the build failed, producing following error which I utterly don't understand. 

Later I created an brand new Expo project with command `npx create-expo-app --template`, installed the dependency with `yarn`, then type in `npx expo run:android` again. The build still failed and same error message is produced.

I also tried creating a new bare react-native project (no expo), and tried building it with `npx react-native run-android`. The project successfully built the app without any problem.

Maybe it is the gradle configuration generated has some error, or maybe it is some of my environment settings aren't correct? I don't know.

I have been stuck on this problem for over two days, so I really hope and appreciate someone and solve and explain it to me. 

#### The Failed Building Process

Following errors are produced in my brand new Expo project: `expo-bugs`.

At first it looks normal, it created, installed and configured a bunch of stuffs:

```

📝  Android package Learn more: https://expo.fyi/android-package

√ What would you like your Android package name to be? ... com.anonymous.expobugs

√ Created native project | gitignore skipped
√ Added Metro config
√ Updated package.json and added index.js entry point for iOS and Android
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead

› Installing using Yarn
Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
√ Config synced
› Building app...
Configuration on demand is an incubating feature.

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-error-recovery
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
```

Then when it was configuring the project `:expo-modules-core`, errors occurred and the build failed.

```
> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* Where:
Script 'C:\Users\23324\Documents\Codes\running-app\node_modules\expo-modules-autolinking\scripts\android\autolinking_implementation.gradle' line: 272

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > Failed to notify project evaluation listener.
      > java.lang.RuntimeException: Unsupported ABI for NDK r19+: ARMEABI
      > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
6 actionable tasks: 4 executed, 2 from cache
Error: C:\Users\23324\Documents\Codes\running-app\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\23324\Documents\Codes\running-app\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\23324\Documents\Codes\running-app\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (C:\Users\23324\Documents\Codes\running-app\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\23324\Documents\Codes\running-app\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\23324\Documents\Codes\running-app\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\23324\Documents\Codes\running-app\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\23324\Documents\Codes\running-app\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:31:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

#### Workarounds

I can just quit using Expo and move all codes to another bare react-native project, but to be honest I don't want to do that, so it will be my last resort.

### What platform(s) does this occur on?

Android

####  `npx expo-env-info`

```
expo-env-info 1.0.5 environment info:
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
  npmPackages:
    expo: ~46.0.13 => 46.0.15
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-web: ~0.18.7 => 0.18.9
  Expo Workflow: bare
```

#### `package.json`

```
{
  "name": "expo-bugs",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~46.0.13",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-web": "~0.18.7",
    "expo-splash-screen": "~0.16.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~18.0.14",
    "@types/react-native": "~0.69.1",
    "typescript": "~4.3.5"
  },
  "private": true
}

```

### Minimal reproducible example

Emm... Just create a new expo project and build it with `npx expo run:android`, though I don't expect anyone can reproduce same errors.

**Comment by seyofori** [comment]
> I worked it out finally! I just deleted all NDK files, typed `npx expo run:android` in the terminal, and let expo install NDK again, then this error didn't come up again! I guess the problem occurred because my NDK is broken.
> 
> The NDK is located in `%LOCALAPPDATA %\Android\Sdk\ndk`. Just delete clear out everything of this folder and you're good to go.
> 
> If you have a bad network connection, you can download it from Android Studio manually. First you should find out what version of NDK Expo requires, which will be printed on the terminal when expo cannot find the required version and prepares to download it. Remember the NDK version, then go to _Android Studio_, open the _SDK manager_, select the tag _SDK Tools_, click the checkbox _Show Package Detail_, scroll down and find *NDK (Side by Side), then select the required version and click _Apply_ to download it.
> 
> Also If your computer has a unstable connection to some resource website, it is recommend to setup a proxy before doing above. If you're using powershell, this can be done by entering this command: `Env:http_proxy="{{your proxy address}}"`.


this worked for me!! whew I'm so relieved

**Comment by Super1Windcloud** [comment]
don't need    so hard ,   just need   delete package-lock.json and then  npm run start ,  it's  work  wondelful

**Comment by hnagar-hbk** [comment]
> I worked it out finally! I just deleted all NDK files, typed `npx expo run:android` in the terminal, and let expo install NDK again, then this error didn't come up again! I guess the problem occurred because my NDK is broken.
> 
> The NDK is located in `%LOCALAPPDATA %\Android\Sdk\ndk`. Just delete clear out everything of this folder and you're good to go.
> 
> If you have a bad network connection, you can download it from Android Studio manually. First you should find out what version of NDK Expo requires, which will be printed on the terminal when expo cannot find the required version and prepares to download it. Remember the NDK version, then go to _Android Studio_, open the _SDK manager_, select the tag _SDK Tools_, click the checkbox _Show Package Detail_, scroll down and find *NDK (Side by Side), then select the required version and click _Apply_ to download it.
> 
> Also If your computer has a unstable connection to some resource website, it is recommend to setup a proxy before doing above. If you're using powershell, this can be done by entering this command: `Env:http_proxy="{{your proxy address}}"`.

This worked! Thanks
