### ISSUE TITLE
Release Build Crash on real device

### ISSUE THREAD

**Issue by kotsh23** [expo/expo#19624]
### Summary

My app working perfect in development mode
but when i tried to build apk using eas build -p android --profile preview
app keep crashing when i try open it

the interested part when i use expo build:android
and choose apk its worked fine

i tried to use logcat in adb and i found this error

```
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at expo.modules.updates.manifest.EmbeddedManifest.get(EmbeddedManifest.kt:31)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at expo.modules.updates.loader.LoaderTask.launchFallbackUpdateFromDisk(LoaderTask.kt:238)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at expo.modules.updates.loader.LoaderTask.start(LoaderTask.kt:99)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at expo.modules.updates.UpdatesController.start(UpdatesController.kt:290)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:464)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:41)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:27)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at tv.dibi.rewards.MainApplication.onCreate(MainApplication.java:66)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.app.ActivityThread.access$1600(ActivityThread.java:310)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8669)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-19 19:27:45.525 31466 31466 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)10-19 19:27:47.590 31518 31518 E AndroidRuntime: FATAL EXCEPTION: main
10-19 19:27:47.590 31518 31518 E AndroidRuntime: Process: tv.dibi.rewards, PID: 31518
10-19 19:27:47.590 31518 31518 E AndroidRuntime: java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
```

### What platform(s) does this occur on?

Android

### Environment

  System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~46.0.13 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed

### Minimal reproducible example

  System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~46.0.13 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed

### eas.json
```
{
  "cli": {
    "version": ">= 0.48.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "releaseChannel": "development"
    },
    "preview": {
      "distribution": "internal",
      "releaseChannel": "preview"
    },
    "production": {
      "releaseChannel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}
```
### app.json
```
{
  "expo": {
    "name": "MyApp",
    "slug": "MyApp",
    "version": "1.0.1",
    "scheme": "tv.dibi.rewards",
    "userInterfaceStyle": "light",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#212121"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "tv.dibi.rewards",
      "buildNumber": "1.0.1"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "googleServicesFile": "./google-services.json",
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-3727431509971519~4740244067"
      },
      "package": "tv.dibi.rewards",
      "versionCode": 101,
      "useNextNotificationsApi": true,
      "permissions": [
        "NOTIFICATIONS"
      ]
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./assets/nicon.png",
          "color": "#ffffff",
          "sounds": [
            "./assets/nsound1.wav",
            "./assets/nsound2.wav"
          ]
        }
      ]
    ],
    "extra": {
      "eas": {
        "projectId": "496fc296-5e6b-4218-99b1-2aa64ba90fa4"
      }
    }
  }
}
```
### package.json
```
{
  "name": "rewardapp",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/core": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "@react-navigation/stack": "^6.3.2",
    "@types/react-native": "~0.69.1",
    "apisauce": "^2.1.6",
    "expo": "~46.0.13",
    "expo-application": "~4.2.2",
    "expo-auth-session": "~3.7.1",
    "expo-constants": "~13.2.4",
    "expo-dev-client": "~1.3.1",
    "expo-device": "~4.3.0",
    "expo-font": "~10.2.0",
    "expo-linear-gradient": "~11.4.0",
    "expo-notifications": "~0.16.1",
    "expo-random": "~12.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.6",
    "expo-web-browser": "~11.0.0",
    "jsc-android": "^294992.0.0",
    "jsonwebtoken": "^8.5.1",
    "jwt-decode": "^3.1.2",
    "lottie-react-native": "5.1.3",
    "react": "18.0.0",
    "react-native": "0.69.6",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-paper": "^4.12.5",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6"
  },
  "private": true
}
```

**Comment by vladis-c** [comment]
@kotsh23 could you leave also app.json, eas.json and package.json configurations here?

**Comment by kotsh23** [comment]
> @kotsh23 could you leave also app.json, eas.json and package.json configurations here?

Updated the main post 
thank you for your answer

**Comment by kotsh23** [comment]
how i can fix this error

i get it from adb logcat
```
java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
```

my build log for expo updates
```
Setting the update response headers in 'AndroidManifest.xml' to '{"expo-channel-name":"preview"}'
```

**Comment by vladis-c** [comment]
> @vladis-c 
> 
> Updated the main post 
> thank you for your answer
> 

Ok, having a look on the configs now. Could you please tell me, of you are using `expo-updates` module in your app, and if you are using `eas update` to update your app over the air?

**Comment by douglowder** [comment]
@kotsh23 did you run

`eas update:configure`

before doing the build?

**Comment by kgbrideau** [comment]
I've also been running into this issue. I'm getting the error
```
FATAL EXCEPTION: main

java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle.app.manifest
```

I ran eas update:configure successfully. The command that I used to create the android apk was `eas build --profile preview --platform android`

My eas.json is
```
{
  "cli": {
    "version": ">= 2.1.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development"
    },
    "preview": {
      "distribution": "internal",
      "channel": "preview"
    },
    "production": {
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}
```

I am able to run the android app on my emulator or doing a development build. No issues with iOS. I am pretty stumped with what is going on, please let me know if there is something else i can try.

**Comment by kgbrideau** [comment]
My apologies, I was looking at the documentation but not at the right location. It was related around the runtimeVersion in app.json. I reverted it to what i previously was using and what matched in AndroidManifest and the build is working for android now.

Thanks for your help!

**Comment by vladis-c** [comment]
> My apologies, I was looking at the documentation but not at the right location. It was related around the runtimeVersion in app.json. I reverted it to what i previously was using and what matched in AndroidManifest and the build is working for android now.
> 
> Thanks for your help!

No worries!

**Comment by zahir-dct** [comment]
The app works well on the Expo Go, but the built version crashes.

When I comment out these lines, it works well.

import Active from "@app/assets/active.svg";
import Disabled from "@app/assets/disabled.svg";

```
<View>
    {!loading ?
            <Active width={18} height={18} />
        :
            <Disabled width={18} height={18} />}
 </View>
```

I encountered a similar issue in the past when attempting to rotate an SVG using CSS, which caused the application to crash.

```
//package.json

"dependencies": {
    "expo": "~47.0.12",
    "react-native": "0.70.8",
}

"devDependencies": {
    "react-native-svg-transformer": "^1.0.0",
},
```

**Comment by hanyaonian** [comment]
> react-native-svg-transformer

same here, do you find any solutions?
