### ISSUE TITLE
expo run:android produces "Uninitialized object exists on backward branch 45"

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo#19686]
### Summary

When I run `expo run:android` I get the following error:

```
› Building app...
Starting a Gradle Daemon (subsequent builds will be faster)
⚠️  Cannot resolve the path to "graphql-scalars" package.
⚠️  Cannot resolve the path to "graphql-scalars" package.
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/gsquare567/Sites/blogcast/mobile/android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Uninitialized object exists on backward branch 45
  Exception Details:
    Location:
      com/android/tools/build/jetifier/core/proguard/ProGuardTypesMap.<init>([Lkotlin/Pair;)V @101: goto
    Reason:
      Error exists in the bytecode
    Bytecode:
      0000000: 2b12 ffb8 00d2 2a2b 4d3a 0d03 3e2c 3a04
      0000010: bb00 7359 2cbe b700 7ac0 007c 3a05 0336
      0000020: 0619 043a 0719 07be 3608 0336 0915 0915
      0000030: 08a2 0037 1907 1509 323a 0a19 0519 0a3a
      0000040: 0b3a 0e03 360c 190b b601 1319 0bb6 0116
      0000050: b800 f8b8 00b5 3a0f 190e 190f b900 a902
      0000060: 0057 8409 01a7 ffc8 1905 c000 ab3a 0e19
      0000070: 0d19 0ec0 009c b800 b9b7 0060 b1
    Stackmap Table:
      full_frame(@45,{UninitializedThis,Object[#270],Object[#270],Integer,Object[#270],Object[#124],Integer,Object[#270],Integer,Integer,Top,Top,Top,UninitializedThis},{})
      same_frame(@104)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
/Users/gsquare567/Sites/blogcast/mobile/android/gradlew exited with non-zero code: 1
Error: /Users/gsquare567/Sites/blogcast/mobile/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/gsquare567/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
    ...
    at spawnAsync (/Users/gsquare567/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/Users/gsquare567/.config/yarn/global/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/Users/gsquare567/.config/yarn/global/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/Users/gsquare567/.config/yarn/global/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:145:9)
error Command failed with exit code 1.
```

### What platform(s) does this occur on?

Android

### SDK Version

44

### Environment

gsquare567@GG-MBP ~/S/b/mobile> npx expo-env-info
npx: installed 2 in 1.601s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.19.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 33.0.0
        System Images: android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.4
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: bare

### Minimal reproducible example

Create a Yarn workspace with a bare Expo project with the following structure:
```
/workspace_root
  /mobile
    /android
```
In `/mobile` run `expo run:android`

**Comment by garrett-gottlieb** [comment]
Got it - we're here to close issues, not fix the bugs. Can you reproduce my exact environment, because the bug here looks more like the inability for expo to depend on its own environment than mine.
