### ISSUE TITLE
java.io.FileNotFoundException: app.manifest

### ISSUE THREAD

**Issue by DianaKoenraadt** [expo/expo#19721]
### Summary

We're migrating to EAS build. The .apk we built crashes immediately, before any splash screen occurs. (Similar issue reported by **someone else** on SO: https://stackoverflow.com/questions/74093233/apk-created-using-eas-cli-crashing-on-physical-device-before-splash-screen-witho)

The log shows the following:

```
2022-10-27 13:15:39.262 11342-11342/? E/EmbeddedManifest: Could not read embedded manifest
    java.io.FileNotFoundException: app.manifest
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:824)
        at android.content.res.AssetManager.open(AssetManager.java:801)
        at expo.modules.updates.manifest.EmbeddedManifest.get(EmbeddedManifest.kt:22)
        at expo.modules.updates.loader.LoaderTask.launchFallbackUpdateFromDisk(LoaderTask.kt:238)
        at expo.modules.updates.loader.LoaderTask.start(LoaderTask.kt:99)
        at expo.modules.updates.UpdatesController.start(UpdatesController.kt:290)
        at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:464)
        at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:41)
        at expo.modules.ReactNativeHostWrapper.createReactInstanceManager(ReactNativeHostWrapper.kt:28)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.foo.bar.MainApplication.onCreate(MainApplication.java:63)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6673)
        at android.app.ActivityThread.access$1400(ActivityThread.java:233)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
2022-10-27 13:15:39.263 11342-11342/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.foo.bar, PID: 11342
    java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
        at expo.modules.updates.manifest.EmbeddedManifest.get(EmbeddedManifest.kt:31)
        at expo.modules.updates.loader.LoaderTask.launchFallbackUpdateFromDisk(LoaderTask.kt:238)
        at expo.modules.updates.loader.LoaderTask.start(LoaderTask.kt:99)
        at expo.modules.updates.UpdatesController.start(UpdatesController.kt:290)
        at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:464)
        at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:41)
        at expo.modules.ReactNativeHostWrapper.createReactInstanceManager(ReactNativeHostWrapper.kt:28)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.foo.bar.MainApplication.onCreate(MainApplication.java:63)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6673)
        at android.app.ActivityThread.access$1400(ActivityThread.java:233)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

### What platform(s) does this occur on?

Android

### SDK Version

44

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.2.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      @expo/metro-config: ^0.1.40 => 0.1.84 
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-navigation: ^4.4.0 => 4.4.4 
    Expo Workflow: managed

### Minimal reproducible example

N/a

**Comment by douglowder** [comment]
@DianaKoenraadt we believe this should be fixed by https://github.com/expo/expo/pull/19731

**Comment by DianaKoenraadt** [comment]
@douglowder I'm sorry, what is `create-manifest-android`? I see no mention of it in the ticket you linked

**Comment by douglowder** [comment]
Specifically, that PR changes `node_modules/expo-updates/scripts/create-manifest-android.gradle` in your build.

https://github.com/expo/expo/pull/19731/files#diff-2cc0935355b481026394cac2ef41f28136186082e23d1d36c588dd17a501e3d9

**Comment by DianaKoenraadt** [comment]
Ah, ok thanks, will see if hacking my node_modules helps. Will this fix be in the next SDK?

**Comment by douglowder** [comment]
Yes it is in the SDK 47 branch already. If this doesn't fix the issue for you, please let us know and we will investigate further.

**Comment by DianaKoenraadt** [comment]
Thanks. Say, I've been working with Expo EAS for two days now, my compliments to you and your colleagues. Of course a migration is always a headache, but the EAS Build process works really well.

**Comment by gabrieldonadel** [comment]
Hi @DianaKoenraadt just a quick tip here while SDK 47 isn't officially released. You can use [patch-package](https://github.com/ds300/patch-package) to apply these changes to your node_module and that way you and your team members don't need to keep updating these files manually.

**Comment by DianaKoenraadt** [comment]
@gabrieldonadel Thanks.

By the way, out of curiosity: Which file is it exactly that ends up missing? (I'd like to check an .aab file I built earlier against the one I built now.)

**Comment by douglowder** [comment]
@DianaKoenraadt thank you very much for the kind words :)

The missing file is `app.manifest`. In Android builds, it should be in the build directory somwhere under `generated/assets/expo-updates`

**Comment by douglowder** [comment]
@DianaKoenraadt please also see the discussion in #19693

**Comment by R4m0nz3r4** [comment]
> Specifically, that PR changes `node_modules/expo-updates/scripts/create-manifest-android.gradle` in your build.
> 
> https://github.com/expo/expo/pull/19731/files#diff-2cc0935355b481026394cac2ef41f28136186082e23d1d36c588dd17a501e3d9

Hello guys patching this fixed the error, I can confirm.

**Comment by douglowder** [comment]
Thanks @R4m0nz3r4  !

**Comment by eduardoschneider** [comment]
Hi! I'm having the same issue, my apk crashes before splash screen, how did you managed to get the error log?

**Comment by endruuu** [comment]
Try using expo-updates@0.16.4 if you have multiple product flavors
https://github.com/expo/expo/issues/21382#issuecomment-1494748946
