### ISSUE TITLE
[SDK 47 beta 8] Error: ENOENT C:\Users\kudo\01_Work

### ISSUE THREAD

**Issue by luluhoc** [expo/expo#19831]
### Summary

Using Hermes

EXPO GO Android Simulator
```
Error: ENOENT: no such file or directory, open 'C:\Users\kudo\01_Work\Repos\expo\expo\android\versioned-react-native\ReactAndroid\hermes-engine\.cxx\MinSizeRel\2q85j1u4\x86\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:594:3)
    at Object.readFileSync (node:fs:462:35)
    at getCodeFrame (C:\Users\admin\Desktop\newss\fidelity-client\node_modules\metro\src\Server.js:1028:18)
    at Server._symbolicate (C:\Users\admin\Desktop\newss\fidelity-client\node_modules\metro\src\Server.js:1101:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (C:\Users\admin\Desktop\newss\fidelity-client\node_modules\metro\src\Server.js:458:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\kudo\\01_Work\\Repos\\expo\\expo\\android\\versioned-react-native\\ReactAndroid\\hermes-engine\\.cxx\\MinSizeRel\\2q85j1u4\\x86\\lib\\InternalBytecode\\InternalBytecode.js'
}

```

Expo Go iOS

```
Error: ENOENT: no such file or directory, open 'C:\private\var\folders\yw\6bx918xn4671rggfcdxz7fph0000gn\T\hermes\build_iphoneos\lib\InternalBytecode\InternalBytecode.js'
    at Object.openSync (node:fs:594:3)
    at Object.readFileSync (node:fs:462:35)
    at getCodeFrame (C:\Users\admin\Desktop\newss\fidelity-client\node_modules\metro\src\Server.js:1028:18)
    at Server._symbolicate (C:\Users\admin\Desktop\newss\fidelity-client\node_modules\metro\src\Server.js:1101:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (C:\Users\admin\Desktop\newss\fidelity-client\node_modules\metro\src\Server.js:458:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\private\\var\\folders\\yw\\6bx918xn4671rggfcdxz7fph0000gn\\T\\hermes\\build_iphoneos\\lib\\InternalBytecode\\InternalBytecode.js'
}
```

### What platform(s) does this occur on?

iOS, Web

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3
      expo: ^47.0.0-beta.8 => 47.0.0-beta.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.4 => 0.70.4
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: bare

````

### Minimal reproducible example

@Kudo

**Comment by kud** [comment]
I see what you did @luluhoc 👀

**Comment by Kudo** [comment]
hi there! could you elaborate how to repro the problem?

**Comment by thedoublejay** [comment]
@Kudo I have the same problem. Updated from Expo 46 to 47.0.3. This was the error on Expo Go:
![Screenshot_20221109_120805](https://user-images.githubusercontent.com/25013382/200736464-22a5af75-4c93-44e3-ab5f-a5d67e0133fe.jpg)

**Comment by Kudo** [comment]
@thedoublejay do you have any repro?

**Comment by thedoublejay** [comment]
@Kudo Hi, you can use my branch - https://github.com/DeFiCh/wallet/pull/3765

1. `npm ci`
2. Run `npm run start`
3. Open on Expo Go

**Comment by Kudo** [comment]
@thedoublejay checking the great repro and noticed the `react-native-svg` is outdated. please upgrade `react-native-svg@13.4.0`.
