### ISSUE TITLE
Android app crashes on launch with Failed resolution of: Lorg/koin/dsl/ModuleKt

### ISSUE THREAD

**Issue by AlexCatch** [expo/expo#19842]
### Summary

When `expo-dev-client` is installed alongside specific other libraries (https://github.com/primer-io/primer-sdk-react-native etc.) the app will crash on launch on Android with  `java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleKt;`.

Removing `expo-dev-client` fixes the crash.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

`expo-dev-client` -> `~1.3.1`
`expo` -> `~46.0.16`
`React` -> `18.0.0`
`React Native` -> `0.69.6`
`@primer-io/react-native` -> `^2.14.0`

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/hoppa/expo-crash-example

### Stacktrace (if a crash is involved)

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.catchpole.hoppa.primertest, PID: 14253
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleKt;
        at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.<clinit>(DevLauncherKoinApp.kt:16)
        at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.access$getKoinAppFactory$p(DevLauncherKoinApp.kt:1)
        at expo.modules.devlauncher.koin.DevLauncherKoinContext.<clinit>(DevLauncherKoinApp.kt:35)
        at expo.modules.devlauncher.DevLauncherController$Companion.wasInitialized(DevLauncherController.kt:345)
        at expo.modules.devlauncher.DevLauncherPackageDelegate$shouldEnableAutoSetup$2.invoke(DevLauncherPackageDelegate.kt:31)
        at expo.modules.devlauncher.DevLauncherPackageDelegate$shouldEnableAutoSetup$2.invoke(DevLauncherPackageDelegate.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at expo.modules.devlauncher.DevLauncherPackageDelegate.getShouldEnableAutoSetup(DevLauncherPackageDelegate.kt:26)
        at expo.modules.devlauncher.DevLauncherPackageDelegate.access$getShouldEnableAutoSetup(DevLauncherPackageDelegate.kt:23)
        at expo.modules.devlauncher.DevLauncherPackageDelegate$createApplicationLifecycleListeners$1.onCreate(DevLauncherPackageDelegate.kt:52)
        at expo.modules.ApplicationLifecycleDispatcher.onApplicationCreate(ApplicationLifecycleDispatcher.kt:20)
        at com.catchpole.hoppa.primertest.MainApplication.onCreate(MainApplication.java:67)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.dsl.ModuleKt" on path: DexPathList[[dex file "/data/data/com.catchpole.hoppa.primertest/code_cache/.overlay/base.apk/classes19.dex", zip file "/data/app/~~wVL1zaZOD_oNHuUn7NvluA==/com.catchpole.hoppa.primertest-Zbo9yLi1kUMYhfqyUHKEXA==/base.apk"],nativeLibraryDirectories=[/data/app/~~wVL1zaZOD_oNHuUn7NvluA==/com.catchpole.hoppa.primertest-Zbo9yLi1kUMYhfqyUHKEXA==/lib/arm64, /data/app/~~wVL1zaZOD_oNHuUn7NvluA==/com.catchpole.hoppa.primertest-Zbo9yLi1kUMYhfqyUHKEXA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.<clinit>(DevLauncherKoinApp.kt:16) 
        at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.access$getKoinAppFactory$p(DevLauncherKoinApp.kt:1) 
        at expo.modules.devlauncher.koin.DevLauncherKoinContext.<clinit>(DevLauncherKoinApp.kt:35) 
        at expo.modules.devlauncher.DevLauncherController$Companion.wasInitialized(DevLauncherController.kt:345) 
        at expo.modules.devlauncher.DevLauncherPackageDelegate$shouldEnableAutoSetup$2.invoke(DevLauncherPackageDelegate.kt:31) 
        at expo.modules.devlauncher.DevLauncherPackageDelegate$shouldEnableAutoSetup$2.invoke(DevLauncherPackageDelegate.kt:26) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at expo.modules.devlauncher.DevLauncherPackageDelegate.getShouldEnableAutoSetup(DevLauncherPackageDelegate.kt:26) 
        at expo.modules.devlauncher.DevLauncherPackageDelegate.access$getShouldEnableAutoSetup(DevLauncherPackageDelegate.kt:23) 
        at expo.modules.devlauncher.DevLauncherPackageDelegate$createApplicationLifecycleListeners$1.onCreate(DevLauncherPackageDelegate.kt:52) 
        at expo.modules.ApplicationLifecycleDispatcher.onApplicationCreate(ApplicationLifecycleDispatcher.kt:20) 
        at com.catchpole.hoppa.primertest.MainApplication.onCreate(MainApplication.java:67) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by AlexCatch** [comment]
Closing as this ended up being an issue with an unrelated third party package.
