### ISSUE TITLE
SDK47 Android app fails at launch when built with eas and fabric + turbomodules - TurboModules are enabled, but mTurboModuleRegistry hasn't been set.

### ISSUE THREAD

**Issue by evelant** [expo/expo#19866]
### Summary

Per the title, when trying to build an android app with eas build having turbomodules and fabric enabled the app will compile but fail at launch with `java.lang.AssertionError: TurboModules are enabled, but mTurboModuleRegistry hasn't been set.`

Further description in reproduction repo here: https://github.com/evelant/test_fabric_eas_build

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

```
 "dependencies": {
    "expo": "^47.0.1",
    "expo-dev-client": "~2.0.0",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.15.4",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.4",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@types/react": "~18.0.24",
    "@types/react-native": "~0.70.6",
    "typescript": "^4.6.3"
  },
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 0.70.0 - /Users/imagio/.cargo/bin/nu
    Binaries:
      Node: 16.17.0 - ~/Library/Caches/fnm_multishells/74054_1667587892543/bin/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 7.18.1 - ~/Library/Caches/fnm_multishells/74054_1667587892543/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/imagio/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.1 => 47.0.1
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.4 => 0.70.4
      react-native-web: ~0.18.7 => 0.18.10
    npmGlobalPackages:
      eas-cli: 2.4.1
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/evelant/test_fabric_eas_build

APK and further description is included in that repo.

### Stacktrace (if a crash is involved)

```
FATAL EXCEPTION: mqt_native_modules
Process: com.evelant.test_fabric_eas_build, PID: 5278
java.lang.AssertionError: TurboModules are enabled, but mTurboModuleRegistry hasn't been set.
    at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:19)
    at com.facebook.react.bridge.CatalystInstanceImpl.getTurboModuleRegistry(CatalystInstanceImpl.java:483)
    at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:494)
    at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:478)
    at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:89)
    at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
    at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1240)
    at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1182)
    at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:136)
    at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1136)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:237)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
    at java.lang.Thread.run(Thread.java:919)
```

**Comment by evelant** [comment]
It seems like this would be in your wheelhouse @Kudo or @tsapeta since you've done recent work on the fabric-tester and PRs like https://github.com/expo/expo/pull/17630 and https://github.com/expo/expo/pull/19083. If I can do anything else to help figure out how to get fabric and turbomodules running smoothly on dev-client builds please let me know.
