### ISSUE TITLE
React Refresh Babel transform should be able to enable it in different environments 

### ISSUE THREAD

**Issue by Rebal67** [expo/expo#19875]
### Summary

I have made multiple environments inside my babel for different configurations and file linking.
whenever the environment isn't development i keep getting the error: ` React Refresh Babel transform should only be enabled in development environmen If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "base$0")`

i tried passing skipEnvCheck in babel: `    plugins: [
                    ['react-refresh/babel', { skipEnvCheck: true }] ]`
but it doesn't pass the argument to the function

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

     "expo": "~45.0.0",
        "expo-dev-client": "~1.0.1",
        "expo-secure-store": "~11.2.0",
        "expo-status-bar": "~1.3.0",
        "react": "17.0.2",
        "react-dom": "17.0.2",
      "@babel/core": "^7.12.9",

### Environment

    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Reproducible demo

babel.config.js

````
return {
        presets: ['babel-preset-expo'],
        plugins: ['react-native-paper/babel', 'transform-inline-environment-variables'],
        env: {
            designonly: {
                plugins: [
                    ['react-refresh/babel', { skipEnvCheck: true }],
                    [
                        'module-resolver',
                        {
                            root: ['.'],
                            extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
                            alias: {
                                '@': './src/components',
                                utils: './src/utils',
                                sdk: 'example mock',
                            },
                        },
                    ],
                ],
            },

            development: {
                plugins: [
                    [
                        'module-resolver',
                        {
                            root: ['.'],
                            extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
                            alias: {
                                '@': './src/components',
                                utils: './src/utils',
                                sdk: 'example real development',
                            },
                        },
                    ],
                ],
            },
            production: {
                plugins: [
                    [
                        'module-resolver',
                        {
                            root: ['.'],
                            extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
                            alias: {
                                '@': './src/components',
                                utils: './src/utils',
                                sdk: 'example real minified',
                            },
                        },
                    ],
                ],
            },
        },
    }
```;`

### Stacktrace (if a crash is involved)

 | [12:59:55] index.js: [BABEL] /home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/index.js: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "designonly". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "base$0")
2|id       | [12:59:55] Error: [BABEL] /home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/index.js: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "designonly". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "base$0")
2|id       | [12:59:55]     at ReactFreshBabelPlugin (/home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/node_modules/react-refresh/cjs/react-refresh-babel.development.js:27:13)
2|id       | [12:59:55]     at sync (/home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/node_modules/@babel/core/lib/gensync-utils/async.js:38:25)
2|id       | [12:59:55]     at sync (/home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/node_modules/gensync/index.js:182:19)
2|id       | [12:59:55]     at /home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/node_modules/gensync/index.js:210:24
2|id       | [12:59:55]     at Generator.next (<anonymous>)
2|id       | [12:59:55]     at /home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/node_modules/@babel/core/lib/config/full.js:229:21
2|id       | [12:59:55]     at Generator.next (<anonymous>)
2|id       | [12:59:55]     at Function.<anonymous> (/home/dev/repos/Tonomy-ID-Integration/Tonomy-ID/node_modules/@babel/core/lib/gensync-utils/async.js:25:3)
2|id       | [12:59:55]     at Generator.next (<anonymous>)

**Comment by ashutosh887** [comment]
Why am I getting this Error?
```
Error: [BABEL] E:\SPYK\grafana\public\app\core\components\Branding\Branding.tsx: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "hot". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "E:\\SPYK\\grafana\\.yarn\\cache\\react-refresh-npm-0.14.0-78ef5eeb73-dc69fa8c99.zip\\node_modules\\react-refresh\\babel.js")
```

**Comment by quan-nm-nexlesoft** [comment]
> Why am I getting this Error?
> 
> ```
> Error: [BABEL] E:\projectName\componentName.tsx: 
> React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "hot". 
> 
> If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing:
> "E:\\project\\.yarn\\cache\\react-refresh-npm-0.14.0-78ef5eeb73-dc69fa8c99.zip\\node_modules\\react-refresh\\babel.js")
> ```

Did you fix it ? Please share it with me, because I'm facing the same problem.

**Comment by vivar20** [comment]
Same problem with Craco

**Comment by thanet-s** [comment]
> Same problem with Craco

export NODE_ENV=production
before build work for me
