### ISSUE TITLE
create-expo-module fails in installing module dependencies stage

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#20018]
### Summary

Creating a module with `npx create-expo-module` fails in `installing module dependencies` stage.

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
      Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild

### Minimal reproducible example

create a new module with `npx create-expo-module`, it fails in Installing module dependencies stage with following message.

```
✔ Downloaded module template from npm
✔ Created the module from template files
✔ Created an empty Git repository
✖ Installing module dependencies
Error: yarn exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/user/.npm/_npx/79332/lib/node_modules/create-expo-module/node_modules/@expo/spawn-async/build/spawnAsync.js:41:23)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/Users/user/.npm/_npx/79332/lib/node_modules/create-expo-module/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at installDependencies (/Users/user/.npm/_npx/79332/lib/node_modules/create-expo-module/build/packageManager.js:9:37)
    at /Users/user/.npm/_npx/79332/lib/node_modules/create-expo-module/build/create-expo-module.js:74:56
    at newStep (/Users/user/.npm/_npx/79332/lib/node_modules/create-expo-module/build/utils.js:21:22)
    at Command.main (/Users/user/.npm/_npx/79332/lib/node_modules/create-expo-module/build/create-expo-module.js:73:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  pid: 79355,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null
}
```

**Comment by brentvatne** [comment]
it looks like you may be using an old version of `create-expo-module`. `npx` is pretty janky when it comes to caching. i recommend running `npx create-expo-module@latest` to ensure you get the latest version. `yarn create expo-module` is much more reliable. let me know if this doesn't fix the issue for you

**Comment by githubjeka** [comment]
Same error. What version of Node I should use? 
```
node -v
v18.12.1
```

**Comment by himrocks33** [comment]
Same issue anyone fix this issue? @githubjeka @ahmetbicer

**Comment by ahmetbicer** [comment]
@himrocks33 i updated my node version to 16.0.0 it fixed the issue. https://github.com/expo/expo/issues/20018#issuecomment-1315344946

**Comment by jean553** [comment]
Still having the same issue on this.

```
node --version
v18.15.0

create-expo-module@0.5.13
```

Did anyone fixed this ?

**Comment by jean553** [comment]
I have also opened a thread on Expo forum, link it here if it helps https://forums.expo.dev/t/npx-create-npx-module-returns-npm-install-exited-with-non-zero-code-127/70730/2

**Comment by HialeahLiam** [comment]
In the case someone is being stupid like me, I got error because I included hyphens in my native module name i.e. `ios-app-extension`, which resulted in import statements looking like `import ios-app-extension ...`. Obviously invalid code lol

**Comment by ibmmt** [comment]
I tried 
`yarn add -D expo-module-scripts`

I got error in windows

set -eo pipefail
        ^^^^^^^^

SyntaxError: Unexpected identifier
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.13.0

yarn 1.22.19

**Comment by amrhassab** [comment]
Steps that fixed this issue for me on Mac (For non-mac see issue 2 perhaps that's why? you only need example app for android anyways to start working on your module):

Please note that there are two steps that can fail this fixed both for me:

1) Failure at the "Installing module dependencies" step
2) Failure at the "Installing dependencies in the example app" step

The example app is created automatically by the expo module bootstrapper

**Steps I took that fixed issue 1:**

1) `rm /Users/mac/package.json`
2) `rm /Users/mac/yarn.lock`
3) `cd ~`
4) `yarn set version classic`
5) `cd Documents`
6) `yarn create expo-module my-module` (don't use npx ... not sure why this is how I made it work)

**Steps I took that fixed issue 2:**

1) Install XCode (The XCode CLI tool kit is sadly not enough on its own)

2) Open XCode > Preferences > Location if no path is shown under Command Line tools just reselect the path

**Comment by andrija29** [comment]
I have gotten a headache from this error but I finally figured out how to make it work
Solution: You can run `npx create-expo-module` from the WSL (just open Linux shell in your desired location).

**Comment by AyubTouba** [comment]
> I have gotten a headache from this error but I finally figured out how to make it work Solution: You can run `npx create-expo-module` from the WSL (just open Linux shell in your desired location).

I think this is the only solution that works on Windows

**Comment by nikocraft** [comment]
> > I have gotten a headache from this error but I finally figured out how to make it work Solution: You can run `npx create-expo-module` from the WSL (just open Linux shell in your desired location).
> 
> I think this is the only solution that works on Windows

yeah it works just fine with WSL... 

![image](https://github.com/expo/expo/assets/443080/570984e2-cde6-462c-b077-f54b890047bd)

**Comment by nikocraft** [comment]
expo-module prepare

![image](https://github.com/expo/expo/assets/443080/28148061-c9e4-4f02-93e2-f8614ce302ca)

**Comment by SerSerch** [comment]
@brentvatne the same error
```
npx create-expo-module@latest my-module
```

**Comment by mortocks** [comment]
Still an issue 

```npx create-expo-module@latest myModule```

Node: v20.11.0
Pnpm: v9.0.3 (and others)

```
✔ Downloaded module template from npm
✔ Created the module from template files
✖ Installing module dependencies
Error: npm install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/XX/.npm/_npx/df6d79204f77d516/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/XX/.npm/_npx/df6d79204f77d516/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at installDependencies (/Users/XX/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/packageManager.js:9:37)
    at /Users/XX/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/create-expo-module.js:86:60
    at newStep (/Users/XX/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/utils.js:21:22)
    at Command.main (/Users/XX/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/create-expo-module.js:85:35) {
  pid: 59603,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null
}
```

**Comment by RomainBitard** [comment]
Still a problem on windows

**Comment by fsobh** [comment]
Still a problem on Windows AND WSL

**Comment by xuergo** [comment]
Not a good idea, but I solved it with a bun.
