### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by chinamcafee** [expo/expo#20015]
### Summary

When I use @expo/cli  : npx expo run:ios -d 'iPhoneSE'  instead of expo run:ios -d 'iPhoneSE', I got an error:

_TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /Users/changzechuan/ReactNativeProjects/reanimated3-rc4-test/node_modules/@expo/cli/build/src/run/ios/options/resolveDevice.js:74:56
    at Array.find (<anonymous>)
    at findDeviceFromSearchValue (/Users/changzechuan/ReactNativeProjects/reanimated3-rc4-test/node_modules/@expo/cli/build/src/run/ios/options/resolveDevice.js:74:29)
    at Object.resolveDeviceAsync (/Users/changzechuan/ReactNativeProjects/reanimated3-rc4-test/node_modules/@expo/cli/build/src/run/ios/options/resolveDevice.js:67:94)
    at async Object.resolveOptionsAsync (/Users/changzechuan/ReactNativeProjects/reanimated3-rc4-test/node_modules/@expo/cli/build/src/run/ios/options/resolveOptions.js:19:20)
    at async runIosAsync (/Users/changzechuan/ReactNativeProjects/reanimated3-rc4-test/node_modules/@expo/cli/build/src/run/ios/runIosAsync.js:54:19)_

**but use expo run:ios -d 'iPhoneSE' works well**

### What platform(s) does this occur on?

iOS

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.11 => 0.3.22 
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

1. expo init xxx
2. choose bare template
3. **npx expo run:ios -d 'iPhoneSE'**  got error
4. **expo run:ios -d 'iPhoneSE'**  works fine

**Comment by chinamcafee** [comment]
If iphone is busy, @expo/cli will get error above before build process, but expo-cli will get error after build success.
