### ISSUE TITLE
`Task :expo-updates:createDebugExpoManifest FAILED` on Expo v47 yarn workspace after `expo run:android`

### ISSUE THREAD

**Issue by garrettg123** [expo/expo#20080]
### Summary

It's not clear what the actual error here is, although I think it's this bit: `Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.` I am using `index.js` for my `main` after following this: https://docs.expo.dev/guides/monorepos/.

```
> Task :expo-updates:createDebugExpoManifest FAILED
Execution optimizations have been disabled for task ':expo-updates:createDebugExpoManifest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:compileDebugAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:compileDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:generateDebugBuildConfig' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:javaPreCompileDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:mergeDebugAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:mergeDebugNativeDebugMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gsquare567/Sites/blogcast/mobile/android'. Reason: Task ':expo-updates:createDebugExpoManifest' uses this output of task ':app:mergeDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Error: @build-script-error-begin
Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.
@build-script-error-end

    at /Users/gsquare567/Sites/blogcast/node_modules/expo-updates/scripts/createManifest.js:36:11
    at Object.<anonymous> (/Users/gsquare567/Sites/blogcast/node_modules/expo-updates/scripts/createManifest.js:99:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-updates:createDebugExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 56s
129 actionable tasks: 14 executed, 110 from cache, 5 up-to-date
Error: /Users/gsquare567/Sites/blogcast/mobile/android/gradlew exited with non-zero code: 1
```

### What platform(s) does this occur on?

Android

### SDK Version

47.0.6

### Environment

```
> npx expo-env-info
npm WARN ignoring workspace config at /Users/gsquare567/Sites/blogcast/mobile/.npmrc

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Minimal reproducible example

1. Create bare monorepo Expo v47 project
2. `expo run:android`

**Comment by bombillazo** [comment]
Also happening to me, same platform ("Android")

**Comment by bombillazo** [comment]
Im using a managed app client with the expo-dev-client

**Comment by brentvatne** [comment]
will reopen if this persists but as far as we can tell this solves the issue

**Comment by triztian** [comment]
I'm experiencing this issue with android, environment:

```
...
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.n/bin/node
      Yarn: 1.22.19 - ~/Src/mobile/NativeApp/node_modules/.bin/yarn
      npm: 8.19.4 - ~/.n/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/tristianazuara/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.10.0
    Expo Workflow: managed
```

Command:

```
HUSKY=0 eas build --platform android --profile company-store-qa --local --non-interactive
```

Output:
```
[RUN_GRADLEW] Error: @build-script-error-begin
[RUN_GRADLEW] Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.
[RUN_GRADLEW] @build-script-error-end
[RUN_GRADLEW]     at /private/var/folders/nb/86cv01nj2ks3619hyzg0xtpr0000gn/T/eas-build-local-nodejs/e43588ae-33f6-4148-a786-47448ad4ba78/build/node_modules/expo-updates/scripts/createManifest.js:36:11
[RUN_GRADLEW]     at Object.<anonymous> (/private/var/folders/nb/86cv01nj2ks3619hyzg0xtpr0000gn/T/eas-build-local-nodejs/e43588ae-33f6-4148-a786-47448ad4ba78/build/node_modules/expo-updates/scripts/createManifest.js:99:3)
[RUN_GRADLEW]     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[RUN_GRADLEW]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
[RUN_GRADLEW]     at Module.load (node:internal/modules/cjs/loader:1074:32)
[RUN_GRADLEW]     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[RUN_GRADLEW]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[RUN_GRADLEW]     at node:internal/main/run_main_module:22:47
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
...
```

I tried setting the `ENTRY_FILE` and haven't had much success; if I set it to this:

```shell
export ENTRY_FILE=$(pwd)/main.js
ls -la main.js && grep main.js package.json 
-rw-r--r--  1 tristianazuara  staff  319 Feb 28 13:30 main.js
  "main": "main.js",
```

I get the following:
```
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem was found with the configuration of task ':app:createBundleReleaseJsAndAssets' (type 'BundleHermesCTask').
[RUN_GRADLEW]   - In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '/private/var/folders/nb/86cv01nj2ks3619hyzg0xtpr0000gn/T/eas-build-local-nodejs/285eb828-8c6a-4dd7-b391-5fcacf6e5203/build/Users/tristianazuara/Src/mobile/NativeApp/main.js' which doesn't exist.
[RUN_GRADLEW]     
[RUN_GRADLEW]     Reason: An input file was expected to be present but it doesn't exist.
[RUN_GRADLEW]     
[RUN_GRADLEW]     Possible solutions:
[RUN_GRADLEW]       1. Make sure the file exists before the task is called.
[RUN_GRADLEW]       2. Make sure that the task which produces the file is declared as an input.
[RUN_GRADLEW]     
[RUN_GRADLEW]     Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
```

Anything I could try? Many thanks in advance, any help is appreciated!

**Comment by triztian** [comment]
I was able to produce a build after using the following config plugin. The main issue I think was the Android SDK level, I had warnings about it being 28 below a certain minimum mentioned in the logs:

**expo-plugin/gradle-properties/index.js**:
```javascript
const { withGradleProperties, withAppBuildGradle } = require('@expo/config-plugins');

module.exports = (config) => {
  const gradleProperties = [
    {
      type: 'property',
      key: 'org.gradle.welcome',
      value: 'never',
    },
    {
      type: 'property',
      key: 'android.disableAutomaticComponentCreation',
      value: 'true',
    },
  ];

  let result = withGradleProperties(config, (config) => {
    gradleProperties.forEach((gradleProperty) => config.modResults.push(gradleProperty));
    return config;
  });

  result = withAppBuildGradle(config, (config) => {
    config.modResults.contents += `
        android {
            compileSdkVersion 31
            buildToolsVersion "31.0.0"
   
            defaultConfig {
                targetSdkVersion 31
                missingDimensionStrategy "store", "play"
            }
        }
    `;
    return config;
  });

  return result;
};
```

**app.config.json** (excerpt):
```json
{
   "expoConfig": {
      "plugins": [ "./expo-plugin/gradle-properties" ]
   }
}
```
