### ISSUE TITLE
"main.jsbundle does not exist" error when building iOS version locally with Expo SDK 47

### ISSUE THREAD

**Issue by izakfilmalter** [expo/expo#20129]
### Summary

Running `EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build -p ios --local` in a Yarn Workspace Monorepo with Yarn 3 and Typescript leads to the following build failure: 

```
+ /Users/izakfilmalter/.nvm/versions/node/v16.13.2/bin/node /private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/react-native/cli.js bundle --entry-file ../../../../../../../../../../../var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/apps/my-app/index.js --platform ios --dev false --reset-cache --bundle-output /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/main.jsbundle --assets-dest /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/myapp.app
warning: the transform cache was reset.
                Welcome to Metro v0.72.3
              Fast - Scalable - Integrated


error Unable to resolve module ./App from /var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/apps/my-app/index.js: 

None of these files exist:
  * ../../../../../../../../../../../var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/apps/my-app/App(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * ../../../../../../../../../../../var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/apps/my-app/App/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
[0m [90m 1 |[39m [36mimport[39m { registerRootComponent } [36mfrom[39m [32m'expo'[39m[33m;[39m[0m
[0m [90m 2 |[39m[0m
[0m[31m[1m>[22m[39m[90m 3 |[39m [36mimport[39m [33mApp[39m [36mfrom[39m [32m'./App'[39m[33m;[39m[0m
[0m [90m   |[39m                  [31m[1m^[22m[39m[0m
[0m [90m 4 |[39m[0m
[0m [90m 5 |[39m [90m// registerRootComponent calls AppRegistry.registerComponent('main', () => App);[39m[0m
[0m [90m 6 |[39m [90m// It also ensures that whether you load the app in Expo Go or in a native build,[39m[0m.
Error: Unable to resolve module ./App from /var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/apps/my-app/index.js: 

None of these files exist:
  * ../../../../../../../../../../../var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/apps/my-app/App(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * ../../../../../../../../../../../var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/apps/my-app/App/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
[0m [90m 1 |[39m [36mimport[39m { registerRootComponent } [36mfrom[39m [32m'expo'[39m[33m;[39m[0m
[0m [90m 2 |[39m[0m
[0m[31m[1m>[22m[39m[90m 3 |[39m [36mimport[39m [33mApp[39m [36mfrom[39m [32m'./App'[39m[33m;[39m[0m
[0m [90m   |[39m                  [31m[1m^[22m[39m[0m
[0m [90m 4 |[39m[0m
[0m [90m 5 |[39m [90m// registerRootComponent calls AppRegistry.registerComponent('main', () => App);[39m[0m
[0m [90m 6 |[39m [90m// It also ensures that whether you load the app in Expo Go or in a native build,[39m[0m
    at ModuleResolver.resolveDependency (/private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:152:15)
    at DependencyGraph.resolveDependency (/private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async traverseDependenciesForSingleFile (/private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/private/var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/baed0d87-946f-4d19-847b-e1481f467e96/build/node_modules/metro/src/DeltaBundler/graphOperations.js:204:3)
info Run CLI with --verbose flag for more details.
+ [[ '' != true ]]
+ cp /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/main.jsbundle /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/myapp.app/
cp: /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/main.jsbundle: No such file or directory
+ BUNDLE_FILE=/Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/myapp.app/main.jsbundle
+ [[ false != true ]]
+ [[ ! -f /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/myapp.app/main.jsbundle ]]
+ echo 'error: File /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/myapp.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues'
error: File /Users/izakfilmalter/Library/Developer/Xcode/DerivedData/myapp-bmecscwniznmmuggxlitcsmprohj/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/myapp.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```

This is related to #20001 but not the same issue.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 3.2.2 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

Here is a repo with a simple yarn workspace: https://github.com/izakfilmalter/expo-build-failure

```
$ cd apps/my-app
$ EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build -p ios --local
```

**Comment by izakfilmalter** [comment]
This worked for me, thanks!

**Comment by byCedric** [comment]
Can confirm that this should solve the remaining case with monorepos: 
- Ubuntu / Android - https://github.com/byCedric/expo-issue-20129/actions/runs/3533299675/jobs/5928752884
- MacOS / iOS - https://github.com/byCedric/expo-issue-20129/actions/runs/3533299675/jobs/5928753038

**Comment by izakfilmalter** [comment]
@byCedric ya everything built fine for me locally using `47.0.8`.

**Comment by brentvatne** [comment]
thanks for following up @izakfilmalter!

**Comment by daviddalmaso** [comment]
Still seeing this issue on 47.0.8

**Comment by izakfilmalter** [comment]
@daviddalmaso what error do you get in the log when you run `EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build -p ios --local`?

You need to go to the directory that it spits out and open the log file in there. Typically the error that you initially see isn't the real error.

**Comment by daviddalmaso** [comment]
Thanks for the tip! Was able to get a little further seeing those logs. I initially had to work through a Distribution certificate issue that was resolved using the thread [here](https://github.com/expo/eas-cli/issues/1331). Now, I'm seeing an issue with my `aws-exports.json` file.

```
error src/aws-exports.json: Unexpected token: punc (;) in file src/aws-exports.json at 2:19.
Error: Unexpected token: punc (;) in file src/aws-exports.json at 2:19
    at minifyCode (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/metro-transform-worker/src/index.js:99:13)
    at transformJSON (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/metro-transform-worker/src/index.js:427:28)
    at Object.transform (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/metro-transform-worker/src/index.js:552:20)
    at transformFile (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/metro/src/DeltaBundler/Worker.flow.js:82:36)
    at Object.transform (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/metro/src/DeltaBundler/Worker.flow.js:55:10)
    at execFunction (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/jest-worker/build/workers/processChild.js:137:17)
    at execHelper (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/jest-worker/build/workers/processChild.js:116:5)
    at execMethod (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/jest-worker/build/workers/processChild.js:120:5)
    at process.messageListener (/private/var/folders/0l/wd_zmvz91r51ts_5np0jx0xm0000gn/T/eas-build-local-nodejs/9f692af3-7371-4f87-9e30-1815e9709052/build/node_modules/jest-worker/build/workers/processChild.js:38:7)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:946:14)
```

**Comment by jjenzz** [comment]
experiencing this on 47.0.8 in a pnpm monorepo which also includes [the following patch](https://github.com/byCedric/expo-monorepo-example/blob/main/apps/mobile/patches/react-native%400.70.5.patch).

> You need to go to the directory that it spits out and open the log file in there. 

i've run `EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build -p ios --local` but i don't see anywhere where i can look for the logs afaict other than the error in the console that matches the GH issue title. which directory are you referring to here @izakfilmalter?

**Comment by izakfilmalter** [comment]
@jjenzz You should see an output that ends with something like this:

```sh
Build failed
Skipping cleanup, /var/folders/3b/fc0h95t92rsf5s4vw9z15qmm0000gn/T/eas-build-local-nodejs/d6aea21d-0325-47d2-a8b3-5230322c6050 won't be removed.
Unknown error. See logs for more information.
    Error: npx exited with non-zero code: 1
```

You then go to that path, and there is a log file in there with way more details on what went wrong.
