### ISSUE TITLE
Web platform broken in SDK 46

### ISSUE THREAD

**Issue by bobOnGitHub** [expo/expo#20205]
### Summary

Web platform broken in SDK 46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.18 AlmaLinux 8.6 (Sky Tiger)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.3 
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    Expo Workflow: managed

```

### Please specify your device/emulator/simulator platform, model and version

web

### Error output

```
Starting Metro Bundler
Error: Cannot find module '@expo/dev-server/build/webpack/symbolicateMiddleware'
Require stack:
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/startAsync.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/index.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/bin/cli
Error: Cannot find module '@expo/dev-server/build/webpack/symbolicateMiddleware'
Require stack:
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/startAsync.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/index.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/bin/cli
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js:6:30)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.webpack (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:41:18)
    at DevServerManager.startAsync (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:133:63)
    at async startAsync (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/startAsync.js:115:5)

```

### Reproducible demo or steps to reproduce from a blank project

```
[bob@wsa NetBeansProjects]$ npx create-expo-app webTest --template blank@46
✔ Downloaded and extracted project files.
✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd webTest
- npm run android
- npm run ios # you need to use macOS to build the iOS project - use the Expo app if you need to do iOS development without a Mac
- npm run web
[bob@wsa NetBeansProjects]$ cd webTest
[bob@wsa webTest]$ npm run web

> webtest@1.0.0 web
> expo start --web

Starting project at /home/bob/NetBeansProjects/webTest
CommandError: It looks like you're trying to use web support but don't have the required dependencies installed.

Please install react-native-web@~0.18.7, react-dom@18.0.0, @expo/webpack-config@^0.17.0 by running:

npx expo install react-native-web@~0.18.7 react-dom@18.0.0 @expo/webpack-config@^0.17.0

If you're not using web, please ensure you remove the "web" string from the platforms array in the project Expo config.

[bob@wsa webTest]$ npx expo install react-native-web@~0.18.7 react-dom@18.0.0 @expo/webpack-config@^0.17.0
› Installing 3 SDK 46.0.0 compatible native modules using npm
> npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 689 packages, and audited 1822 packages in 23s

126 packages are looking for funding
  run `npm fund` for details

23 vulnerabilities (2 moderate, 17 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

[bob@wsa webTest]$ npm run web

> webtest@1.0.0 web
> expo start --web

Starting project at /home/bob/NetBeansProjects/webTest
Starting Metro Bundler
Error: Cannot find module '@expo/dev-server/build/webpack/symbolicateMiddleware'
Require stack:
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/startAsync.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/index.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/bin/cli
Error: Cannot find module '@expo/dev-server/build/webpack/symbolicateMiddleware'
Require stack:
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/startAsync.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/index.js
- /home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/bin/cli
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js:6:30)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.webpack (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:41:18)
    at DevServerManager.startAsync (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:133:63)
    at async startAsync (/home/bob/NetBeansProjects/webTest/node_modules/@expo/cli/build/src/start/startAsync.js:115:5)

```

**Comment by 1OneGroup** [comment]
same issue

**Comment by jeffthompson1971** [comment]
me too...

**Comment by julian-hecker** [comment]
Any resolution or workarounds to this for now?

**Comment by jjorian** [comment]
me too

**Comment by jeffthompson1971** [comment]
I'm totally blocked by this.  I haven't found any solution to use native-base with expo on anything greater than expo sdk 44.   Been trying for over a week.   Is this issue going to be resolved any time soon?   The native-base team says they support 45, but I've not found anyone with web builds working.

**Comment by LinusU** [comment]
We worked around this issue by pinning to `@expo/dev-server` to `0.1.120`.

After upgrading to SDK 47 we were able to again use the latest version of `@expo/dev-server`.

**Comment by byCedric** [comment]
This has been resolved a while ago, closing the issue.
