### ISSUE TITLE
SQLITE_CONSTRAINT_FOREIGNKEY Crash in expo.modules.updates.db.BuildData.clearAllUpdatesFromDatabase

### ISSUE THREAD

**Issue by celandro** [expo/expo#20306]
### Summary

Saw this crash. Looks like there there are other tables to update before the delete is called

Stack trace:

Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6733)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:247)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2057)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7842)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
Caused by android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
  at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount
  at android.database.sqlite.SQLiteConnection.executeForChangedRowCount (SQLiteConnection.java:892)
  at android.database.sqlite.SQLiteSession.executeForChangedRowCount (SQLiteSession.java:756)
  at android.database.sqlite.SQLiteStatement.executeUpdateDelete (SQLiteStatement.java:67)
  at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete (FrameworkSQLiteStatement.java:46)
  at androidx.room.EntityDeletionOrUpdateAdapter.handleMultiple (EntityDeletionOrUpdateAdapter.java:88)
  at expo.modules.updates.db.dao.UpdateDao_Impl.deleteUpdates (UpdateDao_Impl.java:217)
  at expo.modules.updates.db.BuildData.clearAllUpdatesFromDatabase (BuildData.kt:51)
  at expo.modules.updates.db.BuildData.ensureBuildDataIsConsistent (BuildData.kt:44)
  at expo.modules.updates.UpdatesController.start (UpdatesController.kt:258)
  at expo.modules.updates.UpdatesController$Companion.initialize (UpdatesController.kt:506)
  at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager (UpdatesPackage.kt:46)
  at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager (ReactNativeHostWrapperBase.kt:27)
  at com.facebook.react.ReactNativeHost.getReactInstanceManager (ReactNativeHost.java:42)
  at com.pokebattler.raidParty.MainApplication.onCreate (MainApplication.java:72)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1211)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6728)

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ^47.0.8 => 46.0.10
      react: 18.1.0 => 18.0.0
      react-dom: 18.1.0 => 18.0.0
      react-native: 0.70.6 => 0.69.5
      react-native-web: ~0.18.10 => 0.18.9
    Expo Workflow: bare

### Minimal reproducible example

Not possible to provide. 

Similar to another bug, this may be due to the very large number of assets in my app.

**Comment by douglowder** [comment]
We will take a look to see how this can be reproduced.

**Comment by douglowder** [comment]
We are not able to reproduce this -- if you can provide a working app that crashes in this way, we will take a look.

**Comment by AndreiCalazans** [comment]
@douglowder we have two users who seem to be consistently getting this on our latest production Android app. I can't reproduce either but seems like something that is preventable? Given this is a delete, ideally it shouldn't hard crash just log? or something...

```
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
       at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
       at androidx.room.EntityDeletionOrUpdateAdapter.handleMultiple(EntityDeletionOrUpdateAdapter.java:88)
       at expo.modules.updates.db.dao.UpdateDao_Impl.deleteUpdates(UpdateDao_Impl.java:217)
       at expo.modules.updates.db.Reaper.reapUnusedUpdates(Reaper.kt:36)
       at expo.modules.updates.loader.LoaderTask.runReaper$lambda-3(LoaderTask.kt:380)
       at expo.modules.updates.loader.LoaderTask.$r8$lambda$lgc-1-5BMmAebH8NIGxU0OiFsKo()
       at expo.modules.updates.loader.LoaderTask$$ExternalSyntheticLambda0.run(:2)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)  
```

It seems like unless they uninstall and install our app again they are stuck on this crash.
<img width="881" alt="Screenshot 2023-07-12 at 14 04 37" src="https://github.com/expo/expo/assets/20777666/1bb0ba7c-918d-4182-94e2-300ff9d865b9">

**Comment by douglowder** [comment]
@AndreiCalazans we will take a look at this. The original report here says that it was happening on SDK 46. Are the affected customers still using apps built with that version?

**Comment by douglowder** [comment]
ENG-9296

**Comment by AndreiCalazans** [comment]
@douglowder that version of our app is on SDK 48.0.19
