### ISSUE TITLE
I can't run ejected expo.

### ISSUE THREAD

**Issue by HosseinAlipour** [expo/expo#2041]
I ejected exactly as the documentation suggests when I run `./gradlew installDevMinSdkDevKernelDebug` i get 

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDevMinSdkDevKernelDebug' not found in root project 'android'.

```
* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 45.541 secs

```

**Comment by sjchmiela** [comment]
Hi @HosseinAlipour, sorry for the inconvenience! The `exp` tool hasn't been updated for SDK29 and you'll have to follow some additional steps to set the project up:

- **add `expokit@1.3.0` to your project's dependencies** (add `"expokit": "^1.3.0",` to the `dependencies` in your `package.json` and install the dependencies by running `yarn` or `npm install`)
- open up `android/app/build.gradle` and remove lines from `// WHEN_DISTRIBUTING_REMOVE_FROM_HERE` up to `// WHEN_DISTRIBUTING_REMOVE_TO_HERE`

Then, running `./gradlew installDevMinSdkDevKernelDebug` should succeed. 🙂 Let me know if it helped!

**Comment by iamsolankiamit** [comment]
@sjchmiela this worked, I can create a PR regarding this, can you point me where should I start.

**Comment by sjchmiela** [comment]
Great news! :+1: When it comes to submitting a PR, proper behavior is already in code (see below), but it has not been released yet. I think it should come out some time this week.

- add expokit — https://github.com/expo/xdl/commit/7a1ce5808038a8a0d77d45fe3479639bb6bdc646
- remove those lines — https://github.com/expo/xdl/blob/f68802bf033f844e85d97baff7832a6b458ec65a/src/detach/AndroidShellApp.js#L450-L454

**Comment by HosseinAlipour** [comment]
I get exp latest version(56), and i instaled "expokit": "^1.3.0", but is no `//WHEN_DISTRIBUTING_REMOVE_FROM_HERE` or `// WHEN_DISTRIBUTING_REMOVE_TO_HERE` in `android/app/build.gradle` and this is what happened after I executed `./gradlew installDevMinSdkDevKernelDebug`

```
$ ./gradlew installDevMinSdkDevKernelDebug
Parallel execution with configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to G:\dl\ashkan\Android\sdk3\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.RuntimeException: The SDK directory 'G:\dl\ashkan\Android\sdk3' does not exist.
        at com.android.build.gradle.internal.SdkHandler.getSdkLoader(SdkHandler.java:183)
        at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:126)
        at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.java:671)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:570)
        at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:81)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$2.execute(DefaultGradleLauncher.java:185)
        at org.gradle.initialization.DefaultGradleLauncher$2.execute(DefaultGradleLauncher.java:182)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:182)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\workspace\react\resttest3\android\app\build.gradle' line: 172

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':expoview' could not be found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.984 secs

```

**Comment by simb4** [comment]
Same issue here. Trying to debug it for 2 days. Can someone provide any context?
I ejected from CRNA to ExpoKit. 
In documentation, its wirtten that you can rollback to not detached state by just modifying app.json and removing android and ios folders. 
But there are 2 lines that incompatible in my understanding:
```
  compile('host.exp.exponent:expoview:27.0.0@aar') {
    transitive = true
  }
  compile project(path: ':expoview')
```
Both were generated during `exp detach`

**Comment by sjchmiela** [comment]
Hi @simb4! To be able to compile your detached project, remove the `compile project` line and just leave the three first lines of your snippet. 🙂 Sorry for the inconvenience!

**Comment by sixmoraltales** [comment]
Hi @sjchmiela. I just encountered all of these same issues and have tried the solutions proposed in this thread. I am using SDK 26 as outlined in the expo eject documentation. My two problems are outlined below. Please let me know what other information you need to help diagnose where the ejection process is failing!

**1. When I open the /android directory of my project folder with Android Studio, the build fails:**
(Cause: error=2, No such file or directory)

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:exponentPrebuildStep'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command './android/detach-scripts/run-exp.sh''
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:198)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:329)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	... 5 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start './android/detach-scripts/run-exp.sh'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
	... 5 more
Caused by: java.io.IOException: Cannot run program "./android/detach-scripts/run-exp.sh" (in directory "/Users/me/arbtr-rn-v01"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more


**2. If I go back to command line and try to install ./gradlew installDevMinSdkDevKernelDebug, I get:**

Parallel execution with configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/me/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Could not find google-services.json while looking in [src/dev/remote/kernel/debug, src/dev/remote/debug, src/dev/remote/kernel, src/dev/remote/kernelDebug, src/devRemoteKernel/debug, src/debug/devRemoteKernel, src/dev/debug, src/dev/remote, src/dev/remoteDebug, src/devRemoteKernel, src/debug, src/devRemoteKernelDebug, src/dev, src/devDebug]
Could not find google-services.json while looking in [src/dev/remote/kernel/release, src/dev/remote/release, src/dev/remote/kernel, src/dev/remote/kernelRelease, src/devRemoteKernel/release, src/release/devRemoteKernel, src/dev/release, src/dev/remote, src/dev/remoteRelease, src/devRemoteKernel, src/release, src/devRemoteKernelRelease, src/dev, src/devRelease]
Could not find google-services.json while looking in [src/prod/debug, src/debug/prod, src/prod, src/debug, src/prodDebug]
Could not find google-services.json while looking in [src/prod/release, src/release/prod, src/prod, src/release, src/prodRelease]
Could not find google-services.json while looking in [src/dev/debug, src/debug/dev, src/dev, src/debug, src/devDebug]
Could not find google-services.json while looking in [src/dev/release, src/release/dev, src/dev, src/release, src/devRelease]
Could not find google-services.json while looking in [src/dev19/debug, src/debug/dev19, src/dev19, src/debug, src/dev19Debug]
Could not find google-services.json while looking in [src/dev19/release, src/release/dev19, src/dev19, src/release, src/dev19Release]

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDevMinSdkDevKernelDebug' not found in root project 'android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.607 secs

**Comment by sjchmiela** [comment]
Hi, @sixmoraltales!

1. **`Execution failed for task ':app:exponentPrebuildStep'`**
  The log states that the execution failed due to `IOException` — `Cannot run program "./android/detach-scripts/run-exp.sh" (in directory "/Users/me/arbtr-rn-v01"): error=2, No such file or directory`. In fact in SDK26 instead of `run-exp.sh`, there is a `prepare-detached-build.sh` script in the `detached-scripts` directory. Are you sure you are running Expo SDK 26? Or maybe you have modified some Gradle scripts after detaching?
2. **`NDK is missing a "platforms" directory.`**
    Seems like your NDK, well, is missing a `platforms` directory. 😃 I have an NDK of version r10e downloaded from [here](https://developer.android.com/ndk/downloads/older_releases) and it's listing looks like this:
    ```
    GNUmakefile			ndk-depends			prebuilt
    README.TXT			ndk-gdb				remove-windows-symlink.sh
    RELEASE.TXT			ndk-gdb-py			samples
    build				ndk-gdb-py.cmd			sources
    docs				ndk-gdb.py			tests
    find-win-host.cmd		ndk-stack			toolchains
    ndk-build			ndk-which
    ndk-build.cmd			platforms
    ```
    What does your NDK directory look like? (In your case it's `/Users/me/Library/Android/sdk/ndk-bundle`.)

**Comment by sixmoraltales** [comment]
Hi @sjchmiela thanks for the response. I was wrong. It was a two or three month old SDK (I was confused with the android SDK I was running, which was 26). But now I have upgraded to expo SDK 29 and am still getting the same error. I opened a new issue where I have provided more detail. Thanks for any suggestions you might have! https://github.com/expo/expo/issues/2296
