### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_ExponentPrint.default.Orientation')

### ISSUE THREAD

**Issue by vincent-odukwe** [expo/expo#20542]
### Summary

I cannot install, import and use the expo print in my project (both for expo-go and dev-client).
I keep getting the error below
```
 ERROR  TypeError: undefined is not an object (evaluating '_ExponentPrint.default.Orientation')
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

```

```
TypeError: undefined is not an object (evaluating '_ExponentPrint.default.Orientation')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:237:40 in guardedLoadModule
at http://172.20.10.7:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

### What platform(s) does this occur on?

Android, iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.1.3 - /usr/local/bin/npm
      Watchman: 2022.08.29.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

```
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import * as Print from 'expo-print';
import { shareAsync } from 'expo-sharing';

const TestGround = ({}) => (
  <View style={styles.container}>
    <Text>I'm Test Ground</Text>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default TestGround;

```

![image](https://user-images.githubusercontent.com/103431476/208639432-e277a6d8-de06-4d45-8d1a-0758a976f463.png)

**Comment by Kudo** [comment]
hi there! i tested your example but it works for me. could you create a whole minimal reproducible example project to some git repository and we could investigate for you?

**Comment by nlarif** [comment]
Hi @vincent-odukwe, did you find a way to fix this? I am facing the same issue with expo-dev-client and expo-print. I tried to pod install but no way to make it work.

**Comment by vincent-odukwe** [comment]
you have to rebuild your dev-client `eas build --profile development --platform all`

**Comment by nlarif** [comment]
argh I always forget to do that for modules not added in the "plugins" sections of Apps.js.
Thank you very much!

**Comment by oussamachah2020** [comment]
m having a similar error but with the following message: 
`undefined is not an object (evaluating 'ErrorUtils.setGloabalHandler')`

here my package.json
```json
{
  "name": "sacrearmand-pro",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start",
    "start-dev": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "lint": "eslint --fix {src}/**/*.{js,ts,jsx,tsx} --no-error-on-unmatched-pattern",
    "prettier-format": "prettier --write {src}/**/* ./*.{json,*.json} !package-lock.json -u --no-error-on-unmatched-pattern",
    "prepare": "husky install"
  },
  "lint-staged": {
    "src/**/*.{ts,js,json,tsx}": [
      "eslint --fix",
      "prettier --write"
    ]
  },
  "dependencies": {
    "@arelstone/react-native-swipe-button": "^0.3.0",
    "@expo/vector-icons": "^14.0.0",
    "@expo/webpack-config": "~19.0.1",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/blur": "^4.4.0",
    "@react-native-community/datetimepicker": "7.6.1",
    "@react-native-masked-view/masked-view": "0.3.0",
    "@react-native-picker/picker": "2.6.1",
    "@rneui/base": "^4.0.0-rc.8",
    "@rneui/themed": "^4.0.0-rc.8",
    "@shopify/flash-list": "1.6.3",
    "@syncfusion/ej2-react-buttons": "^24.1.46",
    "@types/base-64": "^1.0.0",
    "@types/i18n-js": "^3.8.9",
    "axios": "^1.6.7",
    "axios-hooks": "^5.0.2",
    "base-64": "^1.0.0",
    "dotenv": "^16.4.1",
    "expo": "^50.0.3",
    "expo-app-loading": "~2.1.1",
    "expo-av": "~13.10.4",
    "expo-background-fetch": "~11.8.0",
    "expo-clipboard": "~5.0.1",
    "expo-constants": "~15.4.5",
    "expo-dev-client": "~3.3.7",
    "expo-device": "~5.9.3",
    "expo-document-picker": "~11.10.1",
    "expo-font": "~11.10.2",
    "expo-intent-launcher": "~10.11.0",
    "expo-keep-awake": "~12.8.2",
    "expo-linear-gradient": "~12.7.1",
    "expo-linking": "~6.2.2",
    "expo-localization": "~14.8.3",
    "expo-location": "~16.5.2",
    "expo-notifications": "~0.27.5",
    "expo-print": "~12.8.1",
    "expo-router": "~3.4.5",
    "expo-secure-store": "~12.8.1",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-updates": "~0.24.8",
    "firebase": "^9.8.3",
    "i18n-js": "^3.9.2",
    "jwt-decode": "^3.1.2",
    "lint-staged": "^15.2.0",
    "moment": "2.21.0",
    "moment-range": "3.1.1",
    "react": "18.2.0",
    "react-content-loader": "^6.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.2",
    "react-native-calendario": "^3.3.2",
    "react-native-callkeep": "^4.3.12",
    "react-native-custom-switch": "^1.0.7",
    "react-native-dashed-line": "^1.1.0",
    "react-native-device-info": "^9.0.2",
    "react-native-dropdown-picker": "^5.4.2",
    "react-native-dropdown-select-list": "^2.0.4",
    "react-native-elements": "^3.4.2",
    "react-native-event-listeners": "^1.0.7",
    "react-native-expo-popup-notifications": "0.1.1",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-localization": "^2.3.1",
    "react-native-map-link": "^2.9.4",
    "react-native-maps": "1.8.0",
    "react-native-maps-directions": "^1.8.0",
    "react-native-mask-input": "^1.2.0",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-month-selector": "^1.4.0",
    "react-native-month-switch": "^0.3.2",
    "react-native-month-year-picker": "^1.9.0",
    "react-native-onth-year-picker": "^1.0.9",
    "react-native-pager-view": "6.2.3",
    "react-native-paper": "^5.11.6",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-select-dropdown": "^3.3.4",
    "react-native-svg": "14.1.0",
    "react-native-svg-transformer": "^1.3.0",
    "react-native-swipe-button": "^0.0.4",
    "react-native-tab-view": "^3.3.4",
    "react-native-toast-message": "^2.2.0",
    "react-native-v8": "^2.3.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.6.4",
    "react-redux": "^8.0.2",
    "sentry-expo": "~7.0.0",
    "v8-android-jit": "^11.1000.4",
    "zustand": "^4.4.6",
    "zustand-persist": "^0.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@types/react": "~18.2.45",
    "@typescript-eslint/eslint-plugin": "^6.19.1",
    "@typescript-eslint/parser": "^6.19.1",
    "babel-plugin-module-resolver": "^5.0.0",
    "babel-plugin-root-import": "^6.6.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-config-react": "^1.1.7",
    "eslint-plugin-jest": "^27.6.3",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-react": "^7.33.2",
    "husky": "^9.0.6",
    "prettier": "^3.2.4",
    "typescript": "^5.3.3"
  },
  "private": true
}

```
