### ISSUE TITLE
Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. While trying to resolve module `@custom/module` .. 

### ISSUE THREAD

**Issue by a-eid** [expo/expo#20648]
### Summary

```bash
[RUN_GRADLEW] Error: @build-script-error-begin
[RUN_GRADLEW] Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. While trying to resolve module `@x/validation` from file `/private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/69b729aa-6770-41c1-aba1-9fb21188fe10/build/apps/mobile/src/screens/profile/sub-account-form.tsx`, the package `/private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/69b729aa-6770-41c1-aba1-9fb21188fe10/build/packages/validation/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/69b729aa-6770-41c1-aba1-9fb21188fe10/build/packages/validation/dist/index.js`. Indeed, none of these files exist:
[RUN_GRADLEW]   * /private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/69b729aa-6770-41c1-aba1-9fb21188fe10/build/packages/validation/dist/index.js(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
[RUN_GRADLEW]   * /private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/69b729aa-6770-41c1-aba1-9fb21188fe10/build/packages/validation/dist/index.js/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
[RUN_GRADLEW] @build-script-error-end
[RUN_GRADLEW]     at /private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/69b729aa-6770-41c1-aba1-9fb21188fe10/build/node_modules/expo-updates/scripts/createManifest.js:59:11
[RUN_GRADLEW]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[RUN_GRADLEW] > Task :expo-updates:createDebugExpoManifest FAILED
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-updates:createDebugExpoManifest'.
[RUN_GRADLEW] > Process 'command 'node'' finished with non-zero exit value 1
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] java.lang.StackOverflowError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 1m 50s
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
[RUN_GRADLEW] Execution optimizations have been disabled for 3 invalid unit(s) of work during this build to ensure correctness.
[RUN_GRADLEW] Please consult deprecation warnings for more details.
[RUN_GRADLEW] 168 actionable tasks: 168 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
    Error: npx exited with non-zero code: 1
```

my android build is filing with this error, the package the log is mentioning is a custom one that I'm sharing between projects.
the ios build is fine.

### What platform(s) does this occur on?

Android

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.n/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.n/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

todo.

will post shortly.

**Comment by Noitham** [comment]
What was the fix?
@a-eid

**Comment by mariomurrent-softwaresolutions** [comment]
@a-eid Yeah that would be nice to know, having the same issue right now

**Comment by a-eid** [comment]
I think you need to build your packages using `eas-build-pre-install` hook.

**Comment by mariomurrent-softwaresolutions** [comment]
Which package you mean?

**Comment by a-eid** [comment]
which error are you getting ? 
are you using a monorepo setup ?

**Comment by mariomurrent-softwaresolutions** [comment]
It's a bit different than your error:
```
error: index.js: .plugins[0] must be a string, object, function
SyntaxError: index.js: .plugins[0] must be a string, object, function
Error: .plugins[0] must be a string, object, function
    at Object.transformSync (/private/tmp/expo/build/node_modules/@expo/metro-config/node_modules/@babel/core/lib/transform.js:43:76)
    at parseWithBabel (/private/tmp/expo/build/node_modules/@expo/metro-config/build/transformSync.js:45:18)
    at transformSync (/private/tmp/expo/build/node_modules/@expo/metro-config/build/transformSync.js:35:10)
    at Object.transform (/private/tmp/expo/build/node_modules/@expo/metro-config/build/babel-transformer.js:148:55)
    at transformJSWithBabel (/private/tmp/expo/build/node_modules/@expo/metro-config/build/transform-worker/metro-transform-worker.js:409:45)
    at Object.transform (/private/tmp/expo/build/node_modules/@expo/metro-config/build/transform-worker/metro-transform-worker.js:526:10)
```

**Comment by jimjam88** [comment]
One of my monorepo packages had a outdated dependency on babel-preset-expo that was causing this issue. Removing the dependancy and reinstalling solved this problem for me.
