### ISSUE TITLE
expo-location crash on Android when using in the background

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#20663]
### Summary

My app has a recurring location check every 15 minutes. I keep the app from being affected by Doze mode by a recurring alarm every 60 seconds, with wake locks, a foreground notification, and with disabling battery optimization. 
It worked well for almost 2 years, but after upgrading Expo SDK from 44 to 47, the app is killed every night.
The foreground notification is still running but all periodic tasks are stopped.
Finally, tonight, a found that making a full bug report with Android Developer Options contains the FATAL EXCEPTION at the exact time of the tasks being stopped.

```
--------- beginning of crash
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: FATAL EXCEPTION: expo.modules.AsyncFunctionQueue
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: Process: com.mobile, PID: 2037
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: java.lang.RuntimeException: callback 2 arg cannot be called more than once
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.kotlin.jni.JavaCallback.invoke(Native Method)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt:25)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke(Promise.kt:22)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke(Promise.kt:22)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.kotlin.PromiseKt$toBridgePromise$1.resolve(Promise.kt:29)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.adapters.react.PromiseWrapper.resolve(PromiseWrapper.java:27)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.location.LocationHelpers$1.onLocationChanged(LocationHelpers.java:157)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at expo.modules.location.LocationModule$1.onLocationResult(LocationModule.java:557)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.0.1:2)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-31 03:47:29.935 10465  2037  2148 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

I seems to me that this is caused by my implementation of the NativeModule, but I can't seem to pinpoint it. 

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD

### Minimal reproducible example

https://github.com/hanselsen/expo-location-stopping

**Comment by kdthomas2121** [comment]
I'm also seeing this issue

**Comment by hanselsen** [comment]
I am still investigating/debugging and on of my current suspicions was indeed this method. @kdthomas2121 do you always have this? I am only seeing this while charging at night.

**Comment by kdthomas2121** [comment]
> I am still investigating/debugging and on of my current suspicions was indeed this method. @kdthomas2121 do you always have this? I am only seeing this while charging at night.

Yea so it's when my app enters the foreground and I reopen it after a few hours

**Comment by kdthomas2121** [comment]
I think I've managed a workaround for now by removing the location
subscription when the component unmounts, haven't seen it since

**Comment by kdthomas2121** [comment]
Thought I had fixed this, but still occurring. The code is exactly as above when watchPosiiton is used, and the app is in the background for a while and is reopened

**Comment by michaek** [comment]
I am also seeing this triggered intermittently under the conditions described, from expo.modules.location.LocationHelpers.onLocationChanged. It will be hard to say whether a reproducible example will reliably reproduce (the problem being intermittent), but I will create one to reopen this issue.

**Comment by hanselsen** [comment]
@brentvatne I have made a reproduceable demo.

https://github.com/hanselsen/expo-location-stopping

It contains the essence of what we are supposed to accomplish. If you run `yarn android` it will start the app and it will log certain lines to a Telegram group chat. Both our app and this demo quit this night.

It supposed to log this set of lines over and over:

```
ExpoLocationBot, [18-Jan-23 01:12] Heartbeat!
ExpoLocationBot, [18-Jan-23 01:12] Releasing wake lock
ExpoLocationBot, [18-Jan-23 01:12] Acquiring wake lock
ExpoLocationBot, [18-Jan-23 01:12] heartbeat:emitting
ExpoLocationBot, [18-Jan-23 01:12] Getting location
ExpoLocationBot, [18-Jan-23 01:12] Got location: {"timestamp":1674000728989,"mocked":false,"coords":{"altitude":73.5999984741211,"heading":0,"altitudeAccuracy":2.2362146377563477,"latitude":51.4421011,"speed":0,"longitude":5.4085551,"accuracy":11.649999618530273}}
```

Instead, in the end, it stopped sending log lines and the last lines were:

```
ExpoLocationBot, [18-Jan-23 01:12] OnCreate called
ExpoLocationBot, [18-Jan-23 01:12] notification is not null
ExpoLocationBot, [18-Jan-23 01:12] onStartCommand called: no intent
```
 
What also is interesting is that my original application has implemented some more log lines:

```
MyBot, [18-Jan-23 01:11] Heartbeat!
MyBot, [18-Jan-23 01:11] Releasing wake lock 
MyBot, [18-Jan-23 01:11] heartbeat:emitting
MyBot, [18-Jan-23 01:12] MainApplication:onCreate (1069949074)
MyBot, [18-Jan-23 01:12] OnCreate called
MyBot, [18-Jan-23 01:12] onStartCommand called: no intent
MyBot, [18-Jan-23 01:26] MainApplication:onTrimMemory: 5
MyBot, [18-Jan-23 01:26] MainApplication:onTrimMemory: 5
```

In the Android bug report I see the same lines for both the apps:

```
01-18 01:12:21.494 10383 17191 17258 E AndroidRuntime: FATAL EXCEPTION: expo.modules.AsyncFunctionQueue
01-18 01:12:21.494 10383 17191 17258 E AndroidRuntime: Process: com.mobile, PID: 17191
01-18 01:12:21.494 10383 17191 17258 E AndroidRuntime: java.lang.RuntimeException: callback 2 arg cannot be called more than once
...
01-18 01:12:21.497 10377 18649 18689 E AndroidRuntime: FATAL EXCEPTION: expo.modules.AsyncFunctionQueue
01-18 01:12:21.497 10377 18649 18689 E AndroidRuntime: Process: com.myapp, PID: 18649
01-18 01:12:21.497 10377 18649 18689 E AndroidRuntime: java.lang.RuntimeException: callback 2 arg cannot be called more than once
```

I hope this demo can provide enough to go with.

**Comment by hanselsen** [comment]
I ran the same app tonight, but instead of `Location.getCurrentLocation(...)` I left it blank. The app survived through the night.
This night, I will test with `Geolocation.getCurrentPosition(...)`. I will keep you posted about the results.

**Comment by kdthomas2121** [comment]
I think watchPositionAsync is the culprit for me

**Comment by hanselsen** [comment]
> I ran the same app tonight, but instead of `Location.getCurrentLocation(...)` I left it blank. The app survived through the night. This night, I will test with `Geolocation.getCurrentPosition(...)` from https://github.com/Agontuk/react-native-geolocation-service. I will keep you posted about the results.

To come back to this, I can confirm that with another library it keeps working. The problem only seems to occur when I use the expo-location package.

**Comment by buraks** [comment]
I have seen the same crash happening very frequently on our Android app on Crashlytics. We switched to using `getLastKnownPositionAsync` instead of `getCurrentPositionAsync`

It's not ideal, however, a temporary workaround for us until the issue is fixed.

**Comment by buraks** [comment]
@brentvatne could you reopen this issue please?

**Comment by brentvatne** [comment]
@hanselsen - are you able to reproduce it without notifee? ideally this should be isolated to zero extraneous dependencies

**Comment by hanselsen** [comment]
@brentvatne I actually tried to reproduce it using Expo-only, but I cannot anymore. I will try to figure out why. Notifee itself should not be the problem because it is not implemented in my original app. I will keep you up-to-date.

**Comment by jonrh** [comment]
Started to receive this app crash on Android after upgrading from Expo v46 to v48. From the crash data reported in Sentry so far the trigger seems to be a call to `Location.getCurrentPositionAsync()` on component mount after a prolonged time (for example overnight). Suspect doze mode. Been unable to find reliable steps to reproduce despite many hours of trying via various `adb` commands to force doze and/or app standby.

Stacktrace:
```
java.lang.RuntimeException: callback 2 arg cannot be called more than once
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt)
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt:25)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke(Promise.kt:22)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke(Promise.kt:22)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$1.resolve(Promise.kt:29)
    at expo.modules.adapters.react.PromiseWrapper.resolve(PromiseWrapper.java:27)
    at expo.modules.location.LocationHelpers$1.onLocationChanged(LocationHelpers.java:157)
    at expo.modules.location.LocationModule$1.onLocationResult(LocationModule.java:557)
    at com.google.android.gms.internal.location.zzau.notifyListener
    at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal
    at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by GonzaloGCV** [comment]
Any updates? I am facing the same issue. Could you fix it, @jonrh ?

**Comment by nixolas1** [comment]
This issue happens when waking the app after it has entered DREAMING state, from what our logs say. But unsure if it only happens when a `currentlocation` request is running when the app is minimized.

Activity log (most recent event first):

```
- RuntimeException: callback 2 arg cannot be called more than once
- console Foreground! (JS event callback)
- app.lifecycle state: foreground
- app.lifecycle state: start
- device.event action: SCREEN_ON, 
- 14:27:35 device.event action: DREAMING_STOPPED
- 14:06:12 device.event action action: DREAMING_STARTED

```
It is a major issue for us, and are getting several percent of our users crashing every day. It is making us look for other Geolocation frameworks as this issue does not seem to be on the radar of the Expo team.

**Comment by buraks** [comment]
Is there another issue open? @brentvatne could you kindly re-open this if not?

**Comment by xlozinguez** [comment]
@nixolas1 we're also seeing this issue on our app, would you mind sharing what you ended up opting for to solve this problem?

**Comment by nixolas1** [comment]
No solution yet sadly. Tried out a the community location package, but
that has its own issues.
So currently hoping this one gets resolved, or we have to do some more
research with other packages.

On May 22, 2023, GitHub notification ***@***.***> wrote:
> @nixolas1 <https://github.com/nixolas1> we're also seeing this issue
> on our app, would you mind sharing what you ended up opting for to
> solve this problem?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/expo/expo/issues/20663#issuecomment-1557271046>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AA27KBWJ6QTLN4JF6IJ7O5LXHNWJJANCNFSM6AAAAAATNRMDN4>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by alanjhughes** [comment]
Would anyone be able to provide a reproduction with just `expo-location`?

**Comment by michaek** [comment]
There's no reason to think that notifee has anything to do with the problem, so the minimal example provided in the initial report is almost there. @hanselsen can you update the minimal reproducible example to remove notifee?

@alanjhughes is there something else you were looking for in a reproduction? I did not find a reliable way to reproduce the issue when I tested it, but it continued to occur intermittently.

**Comment by alanjhughes** [comment]
@michaek - yes, I don't see notifee having anything to do with the issue. The issue with the repro provided is the module uses its own threads and calls the event emitter from them, which then calls expo location. I would like to see a reproduction with fairly typical usage.

**Comment by nixolas1** [comment]
Many thanks @alanjhughes! Hoping this fixes the issue :D

**Comment by alanjhughes** [comment]
@nixolas1 - no problem, I wasn't able to reproduce so if you could report back if it fixes the issue that would be great 👍

**Comment by nixolas1** [comment]
How can I test if it's fixed? Tried updating `expo-location` but no new release has been created. Is it possible to point the package.json to a specific github commit/repo maybe?

**Comment by joelngwt** [comment]
@alanjhughes 
I used patch-package to test the fix out. I don't know if it fixes the issue as it seems pretty difficult to reproduce it (I only see it _a lot_ on Sentry), but the location stuff is working normally, so no regression there.

But, the changes seem to break EAS Build. EAS Update is working fine. Logs:

```
> Task :expo-location:compileReleaseJavaWithJavac FAILED
[stderr] 
/home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationHelpers.java:122: error: cannot find symbol
[stderr] 
  public static LocationRequest.Builder prepareLocationRequest(Map<String, Object> options) {
[stderr] 
                               ^
[stderr] 
  symbol:   class Builder
[stderr] 
  location: class LocationRequest
[stderr] 
/home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationHelpers.java:149: error: cannot find symbol
[stderr] 
  static void requestSingleLocation(final LocationModule locationModule, final LocationRequest.Builder locationRequest, final Promise promise) {
[stderr] 
                                                                                              ^
[stderr] 
  symbol:   class Builder
[stderr] 
  location: class LocationRequest
[stderr] 
/home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java:278: error: cannot find symbol
[stderr] 
    final LocationRequest.Builder builder = LocationHelpers.prepareLocationRequest(options);
[stderr] 
                         ^
[stderr] 
  symbol:   class Builder
[stderr] 
  location: class LocationRequest
[stderr] 
/home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java:339: error: cannot find symbol
[stderr] 
    final LocationRequest.Builder locationRequest = LocationHelpers.prepareLocationRequest(options);
[stderr] 
                         ^
[stderr] 
  symbol:   class Builder
[stderr] 
  location: class LocationRequest
[stderr] 
/home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java:446: error: cannot find symbol
[stderr] 
    LocationRequest.Builder locationRequest = LocationHelpers.prepareLocationRequest(new HashMap<>());
[stderr] 
                   ^
[stderr] 
  symbol:   class Builder
[stderr] 
  location: class LocationRequest
[stderr] 
/home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationHelpers.java:126: error: cannot find symbol
[stderr] 
    return new LocationRequest.Builder(locationParams.getInterval())
[stderr] 
                              ^
[stderr] 
  symbol:   class Builder
[stderr] 
  location: class LocationRequest
[stderr] 
Note: Some input files use or override a deprecated API.
[stderr] 
Note: Recompile with -Xlint:deprecation for details.
[stderr] 
Note: /home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/taskConsumers/GeofencingTaskConsumer.java uses unchecked or unsafe operations.
[stderr] 
Note: Recompile with -Xlint:unchecked for details.
[stderr] 
6 errors
```

**Comment by alanjhughes** [comment]
Hi @joelngwt - thanks for the report. What version of the SDK are you using?

**Comment by joelngwt** [comment]
@alanjhughes I'm using 48.0.0.

Anyway, the latest expo-location 15.3.0 works with both build and update, no idea why the patch-package method didn't work 🤔 

I'll be pushing the update to my users in about 2 weeks, I'll let you know if it resolves the issue I'm seeing on Sentry. Hopefully I'll have good news 🙏

**Comment by jonrh** [comment]
Our app has been running in production with Expo v49 and expo-location v16.1.0 for a few days (about 50% of users). So far the native crash not yet surfaced for that new app version but continues on the older ones as expected. Perhaps a bit early to celebrate but the data so far looks very promising that this is indeed solved. Thanks a lot Alan!

**Comment by Luluno01** [comment]
Expo SDK 47 with expo-location v15.0.1 reproduces the problem in simulator, but it seems to be rare.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
because the issue is so old and lacks recent comments, I'm going to close it, as it the library has evolved since then.
Feel free to reopen (please follow the issue template).
Thank you 🙂
