### ISSUE TITLE
The recorded base64 not working on IOS

### ISSUE THREAD

**Issue by omkhetwal** [expo/expo#20841]
### Summary

I'm using expo-av to record voice notes but I'm afraid the audio file recorded on ios works totally fine on android as well as ios but if I record an audio on android it doesn't work on IOS device It gives error if I download the base64 string as audio file it works on both devices though *we want to avoid the step of converting the file on server instead we want to use stored base64*

```jsx
[Error: The AVPlayerItem instance has failed with the error code 1718449215 and domain "CoreMediaErrorDomain".]


[Unhandled promise rejection: Error: The AVPlayerItem instance has failed with the error code 1718449215 and domain "CoreMediaErrorDomain".]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-av/build/Audio/Sound.js:155:16 in Promise$argument_0
at node_modules/expo-av/build/Audio/Sound.js:141:19 in loadAsync


```

```

Error: The AVPlayerItem instance has failed with the error code -16172 and domain "CoreMediaErrorDomain"

```

### What platform(s) does this occur on?

iOS

### Environment

```jsx
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.2.1
      expo-cli: 6.0.5
    Expo Workflow: bare
```

### Minimal reproducible example

```jsx


const AUDIO_BASE64_URL="data:audio/mpeg;base64,theBase64StrinGGGGGG=";
const DOWNLOADED_MP4_FILE_FROM_BASE64 =
  "https://res.cloudinary.com/dxifv208w/video/upload/v1673619080/nowandme/download_vin2sa.mp4" (being downloaed as .mp4 for some reason but it plays the audio)


const playRecordingUsingBase64Source = async () => {
    try {
      const soundObject = new Audio.Sound()

      const { sound, status } = await soundObject.loadAsync(
        {
          uri: AUDIO_BASE64_URL,
        },
        {
          shouldPlay: true,
        }
      )

      await sound.playAsync()
    } catch (error) {
      alert(error)
    }
  }

  /**
   * Using hosted audio file
   */

  const playRecordingUsingUrl = async () => {
    try {
      const { sound, status } = await Audio.Sound.createAsync(
        {
          uri: DOWNLOADED_MP4_FILE_FROM_BASE64,
        },
        {
          shouldPlay: true,
        }
      )

      await sound.playAsync()
    } catch (error) {
      alert(error)
    }
  }

```

### The catch is  if I download this file as mp4 [base64 converter](https://base64.guru/converter/decode/audio) ( doesn't let me download as .m4a) it works totally fine on IOS as well as android

# [Snack link](https://snack.expo.dev/@khetwalom/expo-av-bug)

**Comment by omkhetwal** [comment]
Solved using react-native-fetch-blob

[Solution link](https://github.com/zmxv/react-native-sound/issues/650)

1. Download the file on client side 
2. Append "file://" to the source file


```jsx

 const file =
        RNFetchBlob.fs.dirs.CacheDir +
        `/${Math.random().toString(36).substring(7)}.mp4`

      let base64 = base64String
      RNFetchBlob.fs
        .writeFile(file, base64, "base64")
        .then((len) => {
          console.log("qr image to " + file + " with len " + len)
          setSourceFile(file)
        })
        .catch((reason) => {
          console.log(reason)
        })
      console.log(sourceFile, "source file")
      const { sound, status } = await Audio.Sound.createAsync(
        {
          uri: "file://" + sourceFile,
        },
        {
          shouldPlay: true,
        }
      )

      await sound.playAsync()
      

```
