### ISSUE TITLE
class expo.modules.av.video.f doesn't have a primary constructor

### ISSUE THREAD

**Issue by parice02** [expo/expo#20852]
### Summary

Hello.

I work on an application that uses expo-av. The application was working well with the SDK 46 of expo. I made an update of the application to SDK 47 then ejected (```npx expo prebuild --clean```).
In debug mode I have no problem (at least in appearance). But in release (```npx expo run:andoid --variant release``` or ```npx react-native run-andoird --variant=release``` or ```./gradelw assembleRelease```) , the application crashes at startup. The logcat of android studio shows: 

```bash
win=Window{2271c02 u0 Splash Screen com.parice02.video EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5251 com.android.server.wm.ActivityRecord.destroySurfaces:5232 com.android.server.wm.WindowState.onExitAnimationDone:5623 com.android.server.wm.WindowStateAnimator.onAnimationFinished:332 com.android.server.wm.WindowState.onAnimationFinished:6088 com.android.server.wm.-$$Lambda$dwJG8BAnLlvKNGuDY9U3-haNY4M.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:112
FATAL EXCEPTION: main
 Process: com.parice02.video, PID: 20238
 java.lang.IllegalArgumentException: class expo.modules.av.video.f doesn't have a primary constructor
at expo.modules.kotlin.views.d$a.a(Unknown Source:182)
at expo.modules.kotlin.views.d$a.y(Unknown Source:4)
at expo.modules.kotlin.views.f.a(Unknown Source:12)
at expo.modules.kotlin.views.g.b(Unknown Source:19)
at expo.modules.kotlin.views.GroupViewManagerWrapper.createViewInstance(Unknown Source:9)
...
```
![Screenshot from 2023-01-15 15-05-16](https://user-images.githubusercontent.com/36199587/212699322-c2c09024-9a48-44bc-8056-513e174173d5.png)

### What platform(s) does this occur on?

Android

### Environment

```expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - /usr/bin/node
      npm: 9.3.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64
        Android NDK: 22.1.7171670
    npmGlobalPackages:
      expo-cli: 6.1.0
```

### Minimal reproducible example

[Test video](https://snack.expo.dev/@parice02/test-expo-video)

**Comment by getadapt** [comment]
We just got this, are replacing expo-av until a fix is released

Our android studio traceback, running emulator with --variant=release:
`
    --------- beginning of crash
2023-01-24 07:50:49.097 6447-6447/com.adaptapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adaptapp, PID: 6447
    java.lang.IllegalArgumentException: class expo.modules.av.video.f doesn't have a primary constructor
        at expo.modules.kotlin.views.d$a.a(Unknown Source:182)
        at expo.modules.kotlin.views.d$a.invoke(Unknown Source:4)
        at expo.modules.kotlin.views.f.a(Unknown Source:12)
        at expo.modules.kotlin.views.g.b(Unknown Source:19)
        at expo.modules.kotlin.views.GroupViewManagerWrapper.createViewInstance(Unknown Source:9)
        at expo.modules.kotlin.views.GroupViewManagerWrapper.createViewInstance(Unknown Source:0)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(Unknown Source:27)
        at com.facebook.react.uimanager.ViewManager.createView(Unknown Source:0)
        at com.facebook.react.uimanager.o.createView(Unknown Source:40)
        at com.facebook.react.uimanager.b1$e.l(Unknown Source:23)
        at com.facebook.react.uimanager.b1$j.a(Unknown Source:58)
        at com.facebook.react.uimanager.b1$j.doFrameGuarded(Unknown Source:23)
        at com.facebook.react.uimanager.f.doFrame(Unknown Source:0)
        at com.facebook.react.modules.core.g$d.doFrame(Unknown Source:46)
        at com.facebook.react.modules.core.a$a$a.doFrame(Unknown Source:2)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`

**Comment by parice02** [comment]
I am doing the same.

**Comment by steve-rodri** [comment]
Having the same issue, @getadapt what do you suggest replacing with?

**Comment by getadapt** [comment]
@steve-rodri Ah we were only using it for the `Video` component so far, and even then there's not many other options around. For now we're just splitting the code by platform with `VideoPlayer.android.js` and using `react-native-video-player` in the `.android` file. It's a bit awkward, we're mainly just just hoping for a fix in `expo-av` soon, trying to look into it ourselves but we don't know kotlin...

**Comment by parice02** [comment]
We use *react-native-video* for video. It is not bad. For audio, there is *react-native-track-player*. With *expo-av*, we had the advantage of having both in one.

**Comment by gloredo** [comment]
Error caused by `ProGuard`, disable it is a workaround:
```js
plugins: [
  [
    'expo-build-properties',
    {
      android: {
        enableProguardInReleaseBuilds: false,
      },
    },
  ],
],
```

**Comment by gloredo** [comment]
@lukmccall think it's related to #20197

**Comment by shynonagons** [comment]
Same issue here, following

**Comment by lukmccall** [comment]
Which version of the `expo-camera` and `expo-modules-core` do you have installed?

**Comment by gloredo** [comment]
@lukmccall `expo-modules-core@1.1.1`, I don't have `expo-camera` installed

**Comment by lukmccall** [comment]
Sorry, I meant the `expo-av` version.

**Comment by getadapt** [comment]
looking at our yarn.lock:
expo-modules-core 1.1.1
expo-av: 13.0.2

**Comment by lukmccall** [comment]
Could you bump the `expo-av` to `13.1.0`?

**Comment by getadapt** [comment]
@lukmccall we have our expo-av as "^13.0.2" in package.json I think because of a build error... I'll give it a go soon

**Comment by gloredo** [comment]
@lukmccall no problem, `expo-av@13.1.0` with ProGuard

**Comment by lukmccall** [comment]
Hmm, that is weird. It should work in `13.1.0`. I'll take a look into this issue that week.

**Comment by lukmccall** [comment]
Also, could you share which exactly version of AGP and Kotlin are you using in your project

**Comment by gloredo** [comment]
### Minimal reproducible example

1. `npx create-expo-app my-app`
2. `npx expo install expo-av expo-build-properties`
3. add in `app.json`: 
```json
  "jsEngine": "hermes or jsc",
  "plugins": [
    [
      "expo-build-properties",
      {
        "android": {
          "enableProguardInReleaseBuilds": true,
        },
      },
    ],
  ],
```
4. mount `Video` component with any `uri`
```js
import * as React from 'react';
import { Video } from 'expo-av';

export default function App() {
  return (
    <Video
      source={{
        uri: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
      }}
    />
  );
}
```
5. `eas build -e staging -p android`
6. app crashes when mounting `Video` component

### Kotlin and AGP versions

@lukmccall how do I get the versions? But they are the default of `expo@47.0.13`

**Comment by lukmccall** [comment]
@gloredo thanks for the repro. I've managed to get the same behavior as you did. However, shortly after that, I realized the `expo-av` which was installed automatically isn't the latest one. The project uses `13.0.2` instead of `13.1.0`. So I've bumped it manually. Everything starts working as expected. 

Here https://drive.google.com/file/d/1vq_fv7wJ3OEoFe-xEVJtYlXCpdZsjCEC/view?usp=share_link, you can find a prebuild version of an example app.

**Comment by lukmccall** [comment]
I'll backport my previous fix to the SDK 47. After that, the correct version should be automatically installed.

**Comment by lukmccall** [comment]
Now also `13.0.3` contains a fix and this version is bundled with SDK 47.

**Comment by gloredo** [comment]
This is weird, I'm sure the error happened before with `expo-av@13.1.0` haha, but I tested again and now it works perfectly (with `ProGuard`). Thank you @lukmccall!

**Comment by this-is-aryan** [comment]
I have tried this solution, upgraded the expo-av package but still getting this error. 

PS: This error is not appearing on Staging builds, only release ones where minifyEnabled is true with Proguard.

java.lang.IllegalArgumentException: class expo.modules.av.video.VideoViewWrapper doesn't have a primary constructor
```
at expo.modules.kotlin.views.d$a.a(SourceFile:17)
at expo.modules.kotlin.views.d$a.invoke(Unknown Source:4)
at expo.modules.kotlin.views.f.a(Unknown Source:2)
at expo.modules.kotlin.views.g.b(SourceFile:2)
at expo.modules.kotlin.views.GroupViewManagerWrapper.createViewInstance(SourceFile:2)
at expo.modules.kotlin.views.GroupViewManagerWrapper.createViewInstance(SourceFile:1)
at com.facebook.react.uimanager.ViewManager.createViewInstance(SourceFile:4)
at com.facebook.react.uimanager.ViewManager.createView(SourceFile:1)
at com.facebook.react.uimanager.o.createView(SourceFile:8)
at com.facebook.react.uimanager.b1$e.E(SourceFile:2)
at com.facebook.react.uimanager.b1$j.a(SourceFile:9)
at com.facebook.react.uimanager.b1$j.doFrameGuarded(SourceFile:4)
at com.facebook.react.uimanager.f.doFrame(SourceFile:1)
at com.facebook.react.modules.core.g$d.doFrame(SourceFile:7)
```

The version details are as follows: 
`expo-av: 13.1.0`
`expo-modules-core: 1.1.1`
`react-native: 0.70.14`
