### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by BerkeAras** [expo/expo#20983]
### Summary

I get an error "Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference" every time on Android. I do not use any svg's in Gradients.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
    at com.horcrux.svg.SVGLength.from(SVGLength.java:111)
    at com.horcrux.svg.LinearGradientView.setX1(LinearGradientView.java:53)
    at com.horcrux.svg.RenderableViewManager$LinearGradientManager.setX1(RenderableViewManager.java:1959)
    at com.horcrux.svg.RenderableViewManager$LinearGradientManager.setX1(RenderableViewManager.java:1904)
    at com.facebook.react.viewmanagers.RNSVGLinearGradientManagerDelegate.setProperty(RNSVGLinearGradientManagerDelegate.java:67)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:84)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
    at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:306)
    at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:402)
    at com.facebook.react.animated.PropsAnimatedNode.restoreDefaultValues(PropsAnimatedNode.java:90)
    at com.facebook.react.animated.NativeAnimatedNodesManager.restoreDefaultValues(NativeAnimatedNodesManager.java:500)
    at com.facebook.react.animated.NativeAnimatedModule$20.execute(NativeAnimatedModule.java:910)
    at com.facebook.react.animated.NativeAnimatedModule$ConcurrentOperationQueue.executeBatch(NativeAnimatedModule.java:191)
    at com.facebook.react.animated.NativeAnimatedModule$2.execute(NativeAnimatedModule.java:373)
    at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
    at android.view.Choreographer.doCallbacks(Choreographer.java:796)
    at android.view.Choreographer.doFrame(Choreographer.java:727)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7701)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - ~/Documents/DeliverOne-Code/deliveroneapp/node_modules/.bin/npm
      Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 6.2.1
    Expo Workflow: managed
```

### Minimal reproducible example

Cannot reproduce on new created project 😞

**Comment by gijsjager** [comment]
I have the same issue! Did you already fixed this?

**Comment by OwenMelbz** [comment]
Funnily enough, we started encountering this last night, have not yet found a fix.

**Comment by TijsM** [comment]
We are experiencing the same issue on Android. 
The error only occurs when we run our app in a dev-client, there are no issues when running it in expo go.

**Comment by nmassey** [comment]
Hey - any chance updating _react-native-svg_ fixes the problem?
See https://github.com/software-mansion/react-native-svg/issues/1899

**Comment by anasmohana** [comment]
I'm experiencing the same issue on Android.
The error only occurs when we run our app in a dev-client, there are no issues when running it in expo go.

**Comment by kios19** [comment]
same issue on expo , this will be the last time i use react native, anyone have a fix?

**Comment by lewisd1996** [comment]
Same here, on Android and in development build.

**Comment by codinsonn** [comment]
@BerkeAras are you still having the issue?
- If not, what was the fix?
- If you are, could you add a reproducible minimal demo so the Expo team might be more inclined to have a look?

**Comment by OliverWeitman** [comment]
Same issue here when running dev build on Android. Anyone found a fix?

**Comment by NicodemosSantos** [comment]
Hey people, seems like the problem in this case have to do with `'react-content-loader/native'` or any other Skeleton library on your project.
In my  case try to follow this [Issue #304](https://github.com/danilowoz/react-content-loader/issues/304) on react-content-loader

**Comment by OliverWeitman** [comment]
> Hey people, seems like the problem in this case have to do with `'react-content-loader/native'` or any other Skeleton library on your project. In my case try to follow this [Issue #304](https://github.com/danilowoz/react-content-loader/issues/304) on react-content-loader
> 
> Update: In my case just passing the prop `animate={false}` from the component `ContentLoader` worked as temporary fix, as mentioned @TijsM But the real fix it would be to Expo update the requirement of `react-native-svg` to the version (v13.5.0) or greater.

Saved me a lot of headache. Using react-native-svg 13.5.0 fixed the issue for me!

**Comment by lewisd1996** [comment]
> > Hey people, seems like the problem in this case have to do with `'react-content-loader/native'` or any other Skeleton library on your project. In my case try to follow this [Issue #304](https://github.com/danilowoz/react-content-loader/issues/304) on react-content-loader
> 
> > 
> 
> > Update: In my case just passing the prop `animate={false}` from the component `ContentLoader` worked as temporary fix, as mentioned @TijsM But the real fix it would be to Expo update the requirement of `react-native-svg` to the version (v13.5.0) or greater.
> 
> 
> 
> Saved me a lot of headache. Using react-native-svg 13.5.0 fixed the issue for me!

Same worked for me also

**Comment by nimeshmaharjan1** [comment]
For me it was because i was importing ScrollView from 'react-native-gesture-handler' instead of 'react-native'
