### ISSUE TITLE
Clean project created and installed, but doesn't load

### ISSUE THREAD

**Issue by HamedMP** [expo/expo#21008]
### Summary

I just followed the [tutorial](https://docs.expo.dev/get-started/create-a-new-app/#initializing-the-project) and started the web version using ```npm run web``` (after installing libraries required for Web). 

The command works, but the application on the browser is a blank screen with the following errors in the browser console (nothing on the shell):

![image](https://user-images.githubusercontent.com/3755031/215666112-a56863c5-af08-4c50-bfb4-989cd55fe638.png)

Probably an issue with the current version and mismatched dependency. Also the error on `react-dom` sounds scary (to use React 17 instead of 18). 

```shell
Running application "main" with appParams:
 {rootTag: '#root'} 
Development-level warnings: ON.
Performance optimizations: OFF.
index.js:1 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
render @ react-dom.development.js:29670
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
index.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.<computed> @ index.js:1
printWarning @ react.development.js:207
error @ react.development.js:181
resolveDispatcher @ react.development.js:1590
useContext @ react.development.js:1600
(anonymous) @ index.js:63
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
index.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.<computed> @ index.js:1
printWarning @ react.development.js:207
error @ react.development.js:181
resolveDispatcher @ react.development.js:1590
useContext @ react.development.js:1600
(anonymous) @ index.js:63
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
react.development.js:1616 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (react.development.js:1616:1)
    at index.js:63:1
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at flushSync (react-dom.development.js:26201:1)
    at legacyCreateRootFromDOMContainer (react-dom.development.js:29575:1)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:29601:1)
    at render (react-dom.development.js:29685:1)
    at render (index.js:17:1)
    at renderApplication (renderApplication.js:23:1)
    at Object.run (index.js:38:1)
    at Function.runApplication (index.js:81:1)
    at registerRootComponent (registerRootComponent.tsx:29:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:5:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (log.js:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
useContext @ react.development.js:1616
(anonymous) @ index.js:63
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
index.js:1 The above error occurred in the <View> component:

    at http://localhost:19006/static/js/bundle.js:45081:25
    at AppContainer (http://localhost:19006/static/js/bundle.js:42048:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
react.development.js:1616 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (react.development.js:1616:1)
    at index.js:63:1
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at flushSync (react-dom.development.js:26201:1)
    at legacyCreateRootFromDOMContainer (react-dom.development.js:29575:1)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:29601:1)
    at render (react-dom.development.js:29685:1)
    at render (index.js:17:1)
    at renderApplication (renderApplication.js:23:1)
    at Object.run (index.js:38:1)
    at Function.runApplication (index.js:81:1)
    at registerRootComponent (registerRootComponent.tsx:29:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:5:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (log.js:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
useContext @ react.development.js:1616
(anonymous) @ index.js:63
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
index.js:1 Fetch finished loading: GET "http://localhost:19006/static/js/bundle.js".
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
$ @ index.js:1
W @ index.js:1
ee @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
error (async)
o @ index.js:1
(anonymous) @ index.js:1
ge @ index.js:1
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:45
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
index.js:1 Fetch finished loading: GET "http://localhost:19006/static/js/bundle.js".
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
W @ index.js:1
ee @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
error (async)
o @ index.js:1
(anonymous) @ index.js:1
ge @ index.js:1
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:45
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
index.js:1 Fetch finished loading: GET "http://localhost:19006/static/js/bundle.js.map".
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
Promise.then (async)
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
V @ index.js:1
H @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
Promise.then (async)
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
$ @ index.js:1
W @ index.js:1
ee @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
error (async)
o @ index.js:1
(anonymous) @ index.js:1
ge @ index.js:1
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:45
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
index.js:1 Fetch finished loading: GET "http://localhost:19006/static/js/bundle.js.map".
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
Promise.then (async)
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
H @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
Promise.then (async)
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
D @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
W @ index.js:1
ee @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
error (async)
o @ index.js:1
(anonymous) @ index.js:1
ge @ index.js:1
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:45
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
VM1802:2 Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)
4043 @ VM1802:2
r @ VM1802:2
8048 @ VM1802:2
r @ VM1802:2
8641 @ VM1802:2
r @ VM1802:2
(anonymous) @ VM1802:2
(anonymous) @ VM1802:2
(anonymous) @ VM1802:2
e.onload @ index.js:1
load (async)
be @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
Promise.then (async)
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:29
./node_modules/expo/AppEntry.js @ AppEntry.js:5
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
error (async)
o @ index.js:1
(anonymous) @ index.js:1
ge @ index.js:1
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:45
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ log.js:59
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
webpackHotDevClient.js:76 The development server has disconnected.
Refresh the page if necessary.

```

### What platform(s) does this occur on?

Web

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
      Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.12
    Expo Workflow: managed

### Minimal reproducible example

Literally the starter code:

``` shell
npx create-expo-app Test
```

```shell
npx expo install react-native-web@~0.18.9 @expo/webpack-config@^0.17.2

# Errors out with peer dependency issue
› Installing 2 SDK 47.0.0 compatible native modules using npm
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test@1.0.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"18.1.0" from the root project
npm ERR!   peer react@"^17.0.2 || ^18.0.0" from react-native-web@0.18.12
npm ERR!   node_modules/react-native-web
npm ERR!     react-native-web@"~0.18.9" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^17.0.2 || ^18.0.0" from react-native-web@0.18.12
npm ERR!   node_modules/react-native-web
npm ERR!     react-native-web@"~0.18.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/hamed/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hamed/.npm/_logs/2023-01-31T04_25_28_658Z-debug-0.log

Error: npm exited with non-zero code: 1
Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/hamed/dev/finna/Test/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (/Users/hamed/dev/finna/Test/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at NpmPackageManager._runAsync (/Users/hamed/dev/finna/Test/node_modules/@expo/package-manager/build/NodePackageManagers.js:133:51)
    at NpmPackageManager.installAsync (/Users/hamed/dev/finna/Test/node_modules/@expo/package-manager/build/NodePackageManagers.js:59:20)
    at NpmPackageManager.addWithParametersAsync (/Users/hamed/dev/finna/Test/node_modules/@expo/package-manager/build/NodePackageManagers.js:72:24)
    at async installPackagesAsync (/Users/hamed/dev/finna/Test/node_modules/@expo/cli/build/src/install/installAsync.js:82:5)

```

```shell
# Installed using --legacy 
npx expo install react-native-web@~0.18.9 @expo/webpack-config@^0.17.2 -- --legacy-peer-deps

cd Test

npm run web
```

**Comment by HamedMP** [comment]
Created a new project, this time using `--force` instead of `--legacy--peer-deps`, and the project loads, with only one warning about the `react-dom`. 🙃 

```shell
index.js:1 Warning: ReactDOM.render is no longer supported in React 18. 
Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. 
Learn more: https://reactjs.org/link/switch-to-createroot

```

Now the question is:
1. Why the peer dependency is incorrect and how to fix it. 
2. Will the `react-dom` migration happen? 

![image](https://user-images.githubusercontent.com/3755031/215667313-68b39b3c-8152-491b-8188-013aae2479c6.png)

**Comment by HamedMP** [comment]
Though using `--force` is not a good idea because every other install throughs an error

<img width="700" alt="image" src="https://user-images.githubusercontent.com/3755031/215668541-5523dfb1-b6b9-4fec-ba64-3263791b6199.png">


```shell
npm install dotenv --save

# Output
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-dom@18.2.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.1.0" from react-native@0.70.5
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.70.5" from the root project
npm ERR!   peer react@"^17.0.2 || ^18.0.0" from react-native-web@0.18.12
npm ERR!   node_modules/react-native-web
npm ERR!     react-native-web@"~0.18.9" from the root project
npm ERR!   3 more (react-shallow-renderer, use-sync-external-store, the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^17.0.2 || ^18.0.0" from react-native-web@0.18.12
npm ERR!   node_modules/react-native-web
npm ERR!     react-native-web@"~0.18.9" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0" from react-native-web@0.18.12
npm ERR!     node_modules/react-native-web
npm ERR!       react-native-web@"~0.18.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
