### ISSUE TITLE
[expo-image] Android: Crash on devices lower than SDK 28

### ISSUE THREAD

**Issue by normenster** [expo/expo#21010]
### Summary

expo-image version: 1.0.0-beta.3

On devices lower than SDK 28, expo-image crashes our App instantly while the component is rendered on the screen with the following error:

 FATAL EXCEPTION: main
    Process: com.music2me.app, PID: 12700
    com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:161)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:428)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.NoSuchMethodError: No virtual method setScreenReaderFocusable(Z)V in class Lexpo/modules/image/ExpoImageView; or its super classes (declaration of 'expo.modules.image.ExpoImageView' appears in /data/app/com.music2me.app-46cFKPOk892EVBHfthcFmQ==/base.apk!classes11.dex)
        at expo.modules.image.ExpoImageViewWrapper.copyProps(ExpoImageViewWrapper.kt:184)
        at expo.modules.image.ExpoImageViewWrapper.configureView(ExpoImageViewWrapper.kt:285)
        at expo.modules.image.ExpoImageViewWrapper.onResourceReady(ExpoImageViewWrapper.kt:228)
        at expo.modules.image.ImageViewWrapperTarget.onResourceReady(ImageViewWrapperTarget.kt:45)
        at expo.modules.image.ImageViewWrapperTarget.onResourceReady(ImageViewWrapperTarget.kt:19)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:657)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:596)

I think its because this method **setScreenReaderFocusable** is only available since SDK 28. Is it planned to be fixed? 

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ^0.18.10 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

- Integrate expo image component 
- Build and Run App on a Device with API Level lower than 28 (for example Android 8)

**Comment by magrinj** [comment]
Same thing for us, happening on all the users with android 8 and under.
We also have another error on the same kind of devices:
```
Error while updating property 'proxiedProperties' of a view managed by: ViewManagerAdapter_ExpoImage
```

**Comment by RohovDmytro** [comment]
fxd in beta.4
