### ISSUE TITLE
Getting error(withIosInfoPlistBaseMod: Cannot read property 'nodeName' of null) while using expo eject

### ISSUE THREAD

**Issue by sourabhsingla1997** [expo/expo#21051]
### Summary

sourabh@Sourabhs-MacBook-Pro oms-app % expo eject
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

✔ The android and ios projects are malformed, would you like to clear the project files and reinitialize them? … yes
✔ Cleared android, ios code
✔ Created native projects
✔ Added Metro config
✔ Updated package.json and added index.js entry point for iOS and Android
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead

📦 Using npm to install packages.
✔ Cleaned JavaScript dependencies 10431ms
✔ Installed JavaScript dependencies 29595ms
✖ Config sync failed
[ios.infoPlist]: withIosInfoPlistBaseMod: Cannot read property 'nodeName' of null
TypeError: [ios.infoPlist]: withIosInfoPlistBaseMod: Cannot read property 'nodeName' of null
    at Object.parse (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/node_modules/@expo/plist/src/parse.ts:75:25)
    at readGoogleServicesInfoPlist (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Google.ts:39:16)
    at getGoogleSignInReservedClientId (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Google.ts:56:21)
    at setGoogleSignInReservedClientId (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Google.ts:70:28)
    at setGoogleConfig (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Google.ts:84:15)
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Google.ts:17:25
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/ios-plugins.ts:84:22)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:14)

NOT ABLE TO EJECT FROM EXPO TO REACT NATIVE CLI

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

45.0.5

### Environment

 "dependencies": {
    "@expo/config-plugins": "^5.0.4",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-firebase/analytics": "^16.5.0",
    "@react-native-firebase/app": "^16.5.0",
    "@react-native-firebase/crashlytics": "^16.5.0",
    "@react-native-firebase/perf": "^16.5.0",
    "@react-native-picker/picker": "2.4.0",
    "@react-navigation/native": "^6.0.0",
    "@react-navigation/stack": "^6.2.2",
    "@sentry/cli": "^2.0.4",
    "@sentry/react-native": "^3.1.1",
    "@types/react-native-calendar-picker": "^7.0.2",
    "@types/react-native-simple-radio-button": "^2.7.2",
    "axios": "^0.21.4",
    "expo": "^45.0.5",
    "expo-application": "~4.1.0",
    "expo-auth-session": "~3.6.1",
    "expo-camera": "~12.2.0",
    "expo-constants": "~13.1.1",
    "expo-device": "~4.2.0",
    "expo-document-picker": "~10.2.1",
    "expo-file-system": "~14.0.0",
    "expo-font": "~10.1.0",
    "expo-image-manipulator": "~10.3.1",
    "expo-image-picker": "~13.1.1",
    "expo-intent-launcher": "~10.2.0",
    "expo-linear-gradient": "~11.3.0",
    "expo-linking": "~3.1.0",
    "expo-mail-composer": "~11.2.0",
    "expo-modules-core": "~0.9.2",
    "expo-notifications": "~0.15.4",
    "expo-random": "~12.2.0",
    "expo-screen-capture": "~4.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.4",
    "expo-web-browser": "~10.2.1",
    "immer": "^9.0.6",
    "intl": "^1.2.5",
    "js-base64": "^3.7.2",
    "metro": "^0.65.0",
    "metro-react-native-babel-preset": "^0.65.0",
    "moment": "^2.29.4",
    "native-base": "^3.3.0",
    "patch-package": "^6.4.7",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-bouncy-checkbox": "^2.1.2",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-dotenv": "^3.0.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-input-spinner": "^1.7.11",
    "react-native-pager-view": "5.4.15",
    "react-native-paper": "^4.12.1",
    "react-native-paper-dates": "^0.8.7",
    "react-native-read-more-text": "^1.1.2",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-svg": "12.3.0",
    "react-native-tab-view": "^3.3.4",
    "react-native-toast-message": "^1.5.0",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "sentry-expo": "^4.2.0",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "twrnc": "^3.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-transform-async-to-generator": "^7.16.8",
    "@react-native-community/eslint-config": "^3.0.1",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/jest-native": "^4.0.1",
    "@testing-library/react-native": "^7.2.0",
    "@types/jest": "^26.0.24",
    "@types/node": "^16.11.19",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-native-read-more-text": "^1.0.1",
    "@types/react-redux": "^7.1.17",
    "@types/react-test-renderer": "^17.0.1",
    "@types/redux": "^3.6.31",
    "@types/redux-thunk": "^2.1.32",
    "@typescript-eslint/eslint-plugin": "^5.19.0",
    "@typescript-eslint/parser": "^5.19.0",
    "babel-jest": "^27.4.6",
    "babel-loader": "^8.2.3",
    "core-js": "^3.16.0",
    "eslint": "^8.13.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.4.0",
    "eslint-plugin-react-native": "^4.0.0",
    "husky": "^7.0.1",
    "jest": "^26.6.3",
    "jest-config": "^27.4.6",
    "jest-expo": "^45.0.0",
    "prettier": "^2.3.2",
    "pretty-quick": "^3.1.1",
    "react-test-renderer": "^17.0.2",
    "ts-node": "^10.1.0",
    "typescript": "~4.3.5"
  },

### Minimal reproducible example

<img width="1553" alt="Screenshot 2023-02-02 at 11 16 23 AM" src="https://user-images.githubusercontent.com/42861582/216242525-15612b62-31ab-4155-8e90-b1b7f88d5ecb.png">

Expo app required, run expo eject and getting this error

**Comment by EvanBacon** [comment]
`expo eject` is deprecated, please use `npx expo prebuild` to generate native code for building. You may need to downgrade your version of the global (legacy) Expo CLI to get things working correctly otherwise. The new CLI is versioned and always matches the project it's being used in.

**Comment by artiphishle** [comment]
I've got the same error while `pnpx expo prebuild`. When I remove the `expo.ios.InfoPlist` key from `app.config.ts` it works.

I have no more details so far, it just threw at me 🫣 Maybe it helps to bypass it until it's solved.

**Comment by miguelx97** [comment]
In my case, I had a miss-configuration in my app.json.
Make sure this is correct:
```
    "ios": {
      "supportsTablet": true,
      "googleServicesFile": "./GoogleService-Info.plist",
      "bundleIdentifier": "xxxx",
      "package": "xxxx"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff",
        "googleServicesFile": "./google-services.json",
        "package": "xxxx",
        "bundleIdentifier": "xxxx"
      },
```

You can also ask this to Chat GPT:

> I'm adding firebase to my react native project, and I'm getting this error:
> TypeError: [ios.infoPlist]: withIosInfoPlistBaseMod: Cannot read properties of null (reading 'nodeName')
> 
> My app.json:
> xxxxx
