### ISSUE TITLE
Apple Authentication fail - Cookie not in this host's domain

### ISSUE THREAD

**Issue by dani-z** [expo/expo#21090]
### Summary

Hi Expo team!

I have just updated to the latest CLI and now when I am running `eas build` I am getting the following error:
```Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com```

Here's the full debug log, hope it helps:
```
› Restoring session /Users/dani/.app-store/auth/XYZ@gmail.com/cookie
POST https://developer.apple.com/services-account/QH65B2/account/listTeams.action
200 OK (POST https://developer.apple.com/services-account/QH65B2/account/listTeams.action)
› Session expired Local session
› Using password for XYZ@gmail.com from your local Keychain. Learn more: https://docs.expo.io/distribution/security#keychain
⠋ Logging in...POST https://idmsa.apple.com/appleauth/auth/signin
⠹ Logging in...200  (POST https://idmsa.apple.com/appleauth/auth/signin)
✔ Logged in New session
POST https://developer.apple.com/services-account/QH65B2/account/listTeams.action
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
POST https://developer.apple.com/services-account/QH65B2/account/listTeams.action
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
POST https://developer.apple.com/services-account/QH65B2/account/listTeams.action
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
POST https://developer.apple.com/services-account/QH65B2/account/listTeams.action
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
    at CookieJar.setCookie (/Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:1126369)
    at CookieJar.setCookie (/Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:773190)
    at /Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:1089393
    at new Promise (<anonymous>)
    at /Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:1089174
    at Object.apply (/Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:1090191)
    at /Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:1059084
    at Array.forEach (<anonymous>)
    at responseInterceptor (/Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:1059057)
    at /Users/dani/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:1056969

```

### What platform(s) does this occur on?

iOS

### SDK Version

47.0.12

### Environment

```
➜ npx expo-env-info
Need to install the following packages:
  expo-env-info
Ok to proceed? (y) 

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - ~/Sites/projects/sagedspace.v2/node_modules/.bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2023.01.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/dani/.rvm/gems/ruby-2.7.7/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ^0.18.10 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.5.1
      expo-cli: 6.1.0
    Expo Workflow: bare
```

### Minimal reproducible example

Just running `eas build`.
Expo CLI version: 6.1.0
EAS CLI version: 3.5.1

**Comment by jakoblind** [comment]
I got the same error. I noticed that the Apple site was down for maintenance for 40 mins. And when it was up again I got this error.

**Comment by dani-z** [comment]
Hmm from what I see here all is green https://developer.apple.com/system-status/ still have the issue :-/

**Comment by ishikawa** [comment]
I also got the same error. I’ve tried removing the stored authentication cookie and signing in again. But the error is not resolved.

```
> eas build --platform ios --profile development-client

✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … xxxxx
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more: https://bit.ly/2VtGWhU
✔ Password (for xxxxx): … ****************
› Saving Apple ID password to the local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✔ Logged in, verify your Apple account to continue
Two-factor Authentication (6 digit code) is enabled for xxxxx. Learn more: https://support.apple.com/en-us/HT204915

✔ How do you want to validate your account? … device / sms
✔ Please enter the 6 digit code you received at xxxx
✔ Valid code
✔ Logged in and verified
Authentication with Apple Developer Portal failed!
    Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
```

**Comment by ishikawa** [comment]
The issue is reported in https://github.com/expo/eas-cli/issues/1220 too.

**Comment by kbrandwijk** [comment]
**We're monitoring the situation after the release of eas-cli@3.5.2. If you run into any new issues after installing the new eas-cli version, please report them in https://github.com/expo/eas-cli/issues/1220. Thank you for your patience!**

**Comment by ishikawa** [comment]
The new version of eas-cli (3.5.2) fixes the issue. Thanks a lot!

**Comment by TristaoEzio** [comment]
I upgraded to `npm i eas-cli@3.8.1`
Close **Terminal**, open it again and **run your command**.

Hope this helps.

**Comment by zero19124** [comment]
solved after uppdating esa version
