### ISSUE TITLE
[SDK 48][expo-updates] Could not read embedded manifest; java.io.FileNotFoundException: app.manifest

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#21239]
### Minimal reproducible example

```
"expo": "^48.0.1",
"expo-dev-client": "~2.1.1",
"expo-modules-core": "~1.2.1",
"expo-updates": "~0.16.1",
```

### Summary

After updating to SDK 48, my release builds are throwing this error in logcat. Seems related to https://github.com/expo/expo/issues/19721 https://github.com/expo/expo/issues/19693 https://github.com/expo/expo/issues/19624

```
java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
     at vh.b.a(EmbeddedManifest.kt:102)
     at th.i.x(LoaderTask.kt:39)
     at th.i.D(LoaderTask.kt:106)
     at expo.modules.updates.b.P(UpdatesController.kt:132)
     at expo.modules.updates.b$a.b(UpdatesController.kt:22)
     at expo.modules.updates.UpdatesPackage$b.g(UpdatesPackage.kt:19)
     at be.f.createReactInstanceManager(ReactNativeHostWrapperBase.kt:23)
     at com.facebook.react.w.b(ReactNativeHost.java:10)
     at com.cams.cams_app.MainApplication.onCreate(MainApplication.java:12)
     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
     at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loopOnce(Looper.java:201)
     at android.os.Looper.loop(Looper.java:288)
     at android.app.ActivityThread.main(ActivityThread.java:7872)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Environment

```sh
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.asdf/installs/nodejs/16.15.0/bin/node
      Yarn: 1.22.19 - ~/Documents/GitHub/CAMS_App/node_modules/.bin/yarn
      npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/thespacemanatee/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Giraffe 2022.3.1 Canary 4 Giraffe 2022.3.1 Canary 4
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.1 => 48.0.1 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    Expo Workflow: bare
```

**Comment by endruuu** [comment]
You can try using `useClassicUpdates: true` in the expo config.
https://github.com/expo/expo/issues/21238#issuecomment-1638450974

**Comment by rafahoro** [comment]
In my case, was fixed by running
```
eas update:configure 
```
as suggested in https://github.com/expo/expo/issues/21238
(SDK : "expo": "^49.0.0",)

**Comment by endruuu** [comment]
Try using expo-updates@0.16.4 if you have multiple product flavors
https://github.com/expo/expo/issues/21382#issuecomment-1494748946
