### ISSUE TITLE
jest-expo fails to run tests after SDK 48 upgrade

### ISSUE THREAD

**Issue by yolpsoftware** [expo/expo#21409]
### Minimal reproducible example

https://github.com/yolpsoftware/expo-jest-48-isolation

### Summary

We have a couple of Jest tests which ran fine for a long time. Since we upgraded to Expo SDK 48, a few of those tests fail.

To see the error, please check out our minimal reproducible example here:

https://github.com/yolpsoftware/expo-jest-48-isolation

After that, run `yarn` and then `yarn test`. You will see the following error:

```
    Details:

    /Users/jonas/git/tests/expo-jest-48-isolation/node_modules/firebase/app/dist/index.esm.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { registerVersion } from '@firebase/app';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { setLogLevel } from 'firebase/app';
        | ^
      2 |
      3 | setLogLevel('debug');
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)
      at Object.require (SomeFile.ts:1:1)
      at Object.require (Test.test.ts:1:1)

```

If you checkout `expo-47` instead of `master`, the test will run fine.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.0
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
you will need to add firebase to your `transformIgnorePatterns`: https://docs.expo.dev/guides/testing-with-jest/#configuration

**Comment by yolpsoftware** [comment]
I see, thanks! Strange that this was not necessary in Expo 47, but anyway.

So I added the following snippet to my package.json, this snippet is from the page you linked:

```
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ]
```

Here I add Firebase:

```
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|.*firebase.*)"
    ]
```

That way, my tests are working again. However, the text execution seems to be slower, maybe because of the costly Regex?

So I want to narrow down the Regex. Instead of `.*firebase.*`, I tried all these (some of them found on the web):

```
firebase.*|react-native-firebase.*
react-native-firebase.*|@react-native-firebase.*
@react-native-firebase/firestore|@firebase/testing|@react-native-firebase/app
```

But now I have the same error again. I have no idea how to approach this. Which `transformIgnorePatterns` should I use for Firebase?
