### ISSUE TITLE
[expo-image] Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by magrinj** [expo/expo#21488]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/packages/expo-image

### Summary

I'm actually using `expo-image`, and I got some crash on android devices, here the stack trace returned by sentry:
It's little but I actually can't reproduce it on my android phone. Seems to happen from android 11 to newer versions.
```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@d948cf6
    at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:66)
    at android.graphics.MiuiCanvas.throwIfCannotDraw(MiuiCanvas.java:329)
    at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:277)
    at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
    at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
    at android.widget.ImageView.onDraw(ImageView.java:1436)
    at expo.modules.image.ExpoImageView.onDraw(ExpoImageView.kt:186)
    at android.view.View.draw(View.java:22670)
    at expo.modules.image.ExpoImageView.draw(ExpoImageView.kt:182)
    at android.view.View.updateDisplayListIfDirty(View.java:21498)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at android.view.View.updateDisplayListIfDirty(View.java:21489)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at android.view.View.updateDisplayListIfDirty(View.java:21489)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:838)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:810)
    at android.view.View.updateDisplayListIfDirty(View.java:21489)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:838)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:810)
    at android.view.View.draw(View.java:22677)
    at android.view.View.updateDisplayListIfDirty(View.java:21498)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:838)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:810)
    at android.view.View.updateDisplayListIfDirty(View.java:21489)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:838)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:810)
    at android.view.View.updateDisplayListIfDirty(View.java:21489)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:838)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:810)
    at com.shopify.reactnative.flash_list.AutoLayoutView.dispatchDraw(AutoLayoutView.kt:32)
    at android.view.View.updateDisplayListIfDirty(View.java:21489)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:838)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:810)
    at android.view.View.updateDisplayListIfDirty(View.java:21489)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at android.view.View.draw(View.java:22677)
    at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1743)
    at com.facebook.react.views.scroll.ReactHorizontalScrollView.draw(ReactHorizontalScrollView.java:745)
    at android.view.View.updateDisplayListIfDirty(View.java:21498)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.View.draw(View.java:22384)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4595)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4354)
    at android.view.View.draw(View.java:22677)
    at android.widget.ScrollView.draw(ScrollView.java:1833)
    at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:577)
    at android.view.View.updateDisplayListIfDirty(View.java:21498)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4579)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4552)
    at android.view.View.updateDisplayListIfDirty(View.java:21448)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4371)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4076)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3334)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2134)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8614)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
    at android.view.Choreographer.doCallbacks(Choreographer.java:858)
    at android.view.Choreographer.doFrame(Choreographer.java:789)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1020)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8051)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-29 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: managed

**Comment by magrinj** [comment]
After a lot of debugging, it seems to appear often when we have nested `FlashList`.
Like, on a screen we have a vertical list containing horizontal list of items with expo-image.
If we scroll a lot in that list after some time the UI freeze and crash with the above error.
As a quick fix we have replaced the parent list by a classic `FlatList`, it's less performant but we don't have any crash.

**Comment by Kudo** [comment]
hi there! could you get a chance to create a minimal reproducible example for us to repro and investigate?

**Comment by lukmccall** [comment]
Hi @magrinj, Could you try to apply https://github.com/expo/expo/pull/21658 and check if that will resolve this problem for you?

**Comment by magrinj** [comment]
Hey @Kudo, I'll try to do that next week but it's a bit random, I wasn't able to reproduce it the time I create the issue.

**Comment by magrinj** [comment]
@lukmccall Of course I'll try next week, thanks for your PR !

**Comment by TheRafaelFarias** [comment]
@lukmccall I was having the same problem and your PR solved. Now it is working as normally

**Comment by magrinj** [comment]
@lukmccall Thanks a lot, your patch fix the issue !
