### ISSUE TITLE
Android EAS build failed with expo-updates, TS and a custom entry file

### ISSUE THREAD

**Issue by devalnor** [expo/expo#21748]
### Summary

Android `eas build` failed for project with expo-updates in Typescript and a custom `main` entry file.

```
[RUN_GRADLEW] > Task :expo-updates:createReleaseExpoManifest FAILED
[RUN_GRADLEW] Execution optimizations have been disabled for task ':expo-updates:createReleaseExpoManifest' to ensure correctness due to the following reasons:
[RUN_GRADLEW] - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:checkReleaseAarMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:compileReleaseAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:compileReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:compileReleaseShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:createBundleReleaseJsAndAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:generateReleaseBuildConfig' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:generateReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:javaPreCompileRelease' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:mapReleaseSourceSetPaths' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:mergeReleaseAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW]   - Gradle detected a problem with the following location: '/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/android'. Reason: Task ':expo-updates:createReleaseExpoManifest' uses this output of task ':app:mergeReleaseShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW] Error: @build-script-error-begin
[RUN_GRADLEW] Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.
[RUN_GRADLEW] @build-script-error-end
[RUN_GRADLEW]     at /private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/node_modules/expo-updates/scripts/createManifest.js:36:11
[RUN_GRADLEW]     at Object.<anonymous> (/private/var/folders/rj/_tc8c6cs3t9gsc1815_ydm340000gn/T/eas-build-local-nodejs/4d215411-1e8e-4c30-af75-edafa6c2ba38/build/node_modules/expo-updates/scripts/createManifest.js:99:3)
[RUN_GRADLEW]     at Module._compile (node:internal/modules/cjs/loader:1126:14)
[RUN_GRADLEW]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
[RUN_GRADLEW]     at Module.load (node:internal/modules/cjs/loader:1004:32)
[RUN_GRADLEW]     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
[RUN_GRADLEW]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[RUN_GRADLEW]     at node:internal/main/run_main_module:17:47
[RUN_GRADLEW] > Task :expo-updates:kaptReleaseKotlin
[RUN_GRADLEW] Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
[RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
[RUN_GRADLEW] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[RUN_GRADLEW] Please consult deprecation warnings for more details.
[RUN_GRADLEW] 348 actionable tasks: 348 executed
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-updates:createReleaseExpoManifest'.
[RUN_GRADLEW] > Process 'command 'node'' finished with non-zero exit value 1
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] java.lang.StackOverflowError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 38s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.volta/tools/image/node/16.17.0/bin/node
      Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 8.15.0 - ~/.volta/tools/image/node/16.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.6 => 48.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

Git Repository:
* Use this git repository: https://github.com/devalnor/expo-bug-reports/tree/issue-21748

Or create it manually:
* Start from a blank typescript project `npx create-expo-app -t expo-template-blank-typescript`
* Move `index.ts` and `App.tsx` to a `src` folder
* Change main in `package.json` to `./src/index.ts`
* Install expo-updates `npx install expo-updates`

Run
* Run a build ```eas build -p android -e preview --clear-cache  --local ```

**Comment by douglowder** [comment]
The `blank-typescript` template does not generate an `index.ts` file, at least in my local testing when creating a new app from that template.

You can use the `index.ts` from your repo, but I would move it to the root directory and rename to `index.js`, as recommended in https://reactnative.dev/docs/typescript .

If you do that, and the file looks like this, then the build should succeed.

```js
import 'expo-asset';
import { registerRootComponent } from 'expo'
import App from './src/App'

registerRootComponent(App)
```

**Comment by devalnor** [comment]
Indeed. Thanks for your response 👍

**Comment by JClackett** [comment]
This just saved my bacon! im sure ive seen docs using index.ts as the root - may be worth adding to docs somewhere

**Comment by JS-GitRepo** [comment]
This also resolved my issue, thanks @douglowder !

**Comment by EmmanuelStocco** [comment]
Hello Everyone,

After two weeks stop in this problem and reading all articles and blog about this error, i finish find a solution. 
EAS updated your intern node from 16 to 18. For any reazon, gradlew is incompatable. So you need define in your eas settings your node version local, for eas build 

Go to eas settings and set for example:

 "production": {
      "android": {
        "node": "16.18.0",
        "buildType": "apk"
      }
    }
    
    eas build --profile production --platform android
    
    I hope it helps you,
    
    Greting from Brazil
