### ISSUE TITLE
Expo Updates Configured in app.json breaks iOS build on ExpoGo app locally

### ISSUE THREAD

**Issue by andy-HM** [expo/expo#21780]
### Summary

I am running Expo SDK 48 and getting setup with EAS.  In publishing an update to a branch in EAS, the "updates" section was added to my app.json.  

After this happened, my local running of my app in ExpoGo broke.  Through some troubleshooting I was able to determine I can get the app to load in ExpoGo by removing the updates section all together.  

The Error I am receiving in the CLI when opening the app in ExpoGo:
TypeError: Cannot read property 'version' of null
TypeError: Cannot read property 'version' of null
    at ?anon_0_ (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:101579:51)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4638:26)
    at _next (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4657:29)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4662:14)
    at tryCallTwo (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4654:25)
    at apply (native)
    at loadSentry (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:101585:27)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:101614:17)
    at tryCallOne (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29738:26)
    at _callTimer (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29657:17)
    at _callReactNativeMicrotasksPass (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29687:17)
    at callReactNativeMicrotasks (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29850:44)
    at __callReactNativeMicrotasks (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2787:46)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2599:45)
    at __guard (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2771:15)
    at flushedQueue (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2598:21)
    at invokeCallbackAndReturnFlushedQueue (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2592:33)
 WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'version' of null
TypeError: Cannot read property 'version' of null
    at ?anon_0_ (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:101579:51)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4638:26)
    at _next (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4657:29)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4662:14)
    at tryCallTwo (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:4654:25)
    at apply (native)
    at loadSentry (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:101585:27)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:101614:17)
    at tryCallOne (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29738:26)
    at _callTimer (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29657:17)
    at _callReactNativeMicrotasksPass (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29687:17)
    at callReactNativeMicrotasks (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:29850:44)
    at __callReactNativeMicrotasks (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2787:46)
    at anonymous (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2599:45)
    at __guard (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2771:15)
    at flushedQueue (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2598:21)
    at invokeCallbackAndReturnFlushedQueue (http://192.168.1.11:19000/index.bundle?platform=ios&dev=true&hot=false:2592:33)
› Stopped server

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1 
      babel-preset-expo: ^9.3.0 => 9.3.0 
      expo: ~48.0.6 => 48.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: managed

### Minimal reproducible example

My the updates section of app.json:

    "updates": {
      "enabled":true,
      "fallbackToCacheTimeout": 0,
      "url": "https://u.expo.dev/ebcc54be-9df3-48fb-a45b-1139a9daa9e0"
    },

**Comment by andy-HM** [comment]
I forgot to add that this was an existing project (pre EAS) and I added updates to my project.  Though I simply followed the SDK upgrade steps and documentation provided on the Expo website.

**Comment by douglowder** [comment]
@andy-HM is the "updates" section the only part of your app.json that changed? The runtime version also needs to be different for EAS updates and for Expo Go. See https://docs.expo.dev/eas-update/runtime-versions/ .

Which SDK version was the project originally created with?

**Comment by andy-HM** [comment]
Hello @douglowder.  Correct, the updates section is the only thing that changes.  If I remove this section, the ExpoGo app will work as expected.  

I'm not 100% sure on the original SDK version but it was a mid to late 30s version.  34 or 35 sounds right.  

I did look at setting the runtime-version per the documentation.  However, when I change the runtimeVersion to anything other than:

    "runtimeVersion": {
      "policy": "sdkVersion"
    }

I will see the following in the app:
![IMG_8207C56B5FB7-1](https://user-images.githubusercontent.com/74470025/227081241-d421f4c6-44e2-4e49-a4e8-d7d5e513aaf8.jpeg)

**Comment by douglowder** [comment]
Correct, if you are running in Expo Go you use "sdkVersion". For EAS updates you should use one of the version types that are recommended in the doc referenced above.

**Comment by andy-HM** [comment]
Are you saying it's not possible to both use ExpoGo for local development / testing and EAS updates?  

If you must use "sdkVersion" policy for ExpoGo to function but you need one of the other runtime versions for EAS updates to funciton, are you not able to have both?  

I feel like I'm missing something here because that doesn't sound correct.

**Comment by douglowder** [comment]
https://docs.expo.dev/build/updates#previewing-updates-in-development-builds

**Comment by andy-HM** [comment]
Thank you @douglowder .  I think this is one of those "can't see the forest through the trees" scenarios.

I was able to configure a development build following the link above.  However, the app will still not launch and ultimately I'm seeing the errors I posted in my original post.

This is now coming from binaries created using EAS, running in the development build configuration.

The error from the CLI:

```
TypeError: Cannot read property 'version' of null
    at ?anon_0_ (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:101582:51)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:1396:26)
    at _next (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:1415:29)
    at anonymous (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:1420:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:1412:25)
    at apply (native)
    at loadSentry (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:101588:27)
    at anonymous (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:101617:17)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:29689:26)
    at _callTimer (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:29608:17)
    at _callReactNativeMicrotasksPass (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:29638:17)
    at callReactNativeMicrotasks (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:29801:44)
    at __callReactNativeMicrotasks (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:2753:46)
    at anonymous (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:2565:45)
    at __guard (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:2737:15)
    at flushedQueue (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:2564:21)
    at invokeCallbackAndReturnFlushedQueue (http://192.168.1.11:8081/index.bundle?platform=ios&dev=true&hot=false:2558:33)
```

eas.json for build:
 ```
 "dev": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "dev"
    },
```

app.json runtimeVersion:
   ```
 },
    "runtimeVersion": {
      "policy": "nativeVersion"
    }
```

app.json updates section:
```
"updates": {
      "enabled":true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0,
      "url": "https://u.expo.dev/ebcc54be-9df3-48fb-a45b-1139a9daa9e0"
    },
```

**Comment by douglowder** [comment]
If you can provide a repo, and the detailed steps leading to the above error, we will investigate.

**Comment by nympheastudio** [comment]
you can try to specify 

 "runtimeVersion": "exposdk:48.0.0" in app.json

in bare workflow  ,add this to info.plist: 
  <key>EXUpdatesRuntimeVersion</key>
  <string>exposdk:48.0.0</string>

**Comment by louislatreille** [comment]
I am getting the exact same bug as @andy-HM 

I was going through setting up expo-updates, and after I added the "updates" section to my app.config.js, my app doesn't load on ExpoGo anymore. The app works fine on web.

I came to the same conclusion, by removing the "updates" section, and the app loads fine afterwards.

**Comment by louislatreille** [comment]
Adding more flavor to my comment above. It seems like the issue is with the updates URL. I think expo go doesn't work with that field set. When removing it, everything now loads fine.

So
```
updates: {
  enabled: true,
  url: "string",
},
```

to

```
updates: {
  enabled: true,
},
```

I ended up checking a field that tells me if I'm running a dev build, and setting `url` to undefined, else using the right url string.

**Comment by andy-HM** [comment]
Hello @louislatreille , are you receiving the same error I am in my original post? Is your `eas publish` command working when you remove the url from your app.json?  

When you say "else using the right url string", what are you using to set the URL if you are not defining it in the app.json? 

Thanks for your help.

**Comment by louislatreille** [comment]
@andy-HM I had the exact same error.

I am using a `app.config.js` file instead of the `app.json`. It allows you to do a bunch of additional things, like conditionally setting some parameters based on environment variables. See https://docs.expo.dev/workflow/configuration/#dynamic-configuration

I have an environment variable that defines the stage I'm running. So for the `dev` stage, I set the url to undefined, which works with expo go. For other stages (e.g. prod), I set the url to my update manifest URL.

**Comment by douglowder** [comment]
I think @louislatreille has a very reasonable solution for pivoting between dev (Expo Go) and prod (EAS Update). Closing this for now, but will continue to discuss this internally.

**Comment by andy-HM** [comment]
Thank you @louislatreille , this is very helpful. I will check it out!

**Comment by wschurman** [comment]
@andy-HM is using the following an option for you?
```
"runtimeVersion": {
  "policy": "sdkVersion"
}
```
Or, put another way, is there a runtime that you need that is not in the Expo SDK (custom native modules, etc)?

cc @jonsamp for info about reverting the default policy back to `sdkVersion`.

**Comment by louislatreille** [comment]
As a note, I've deployed a new version of my app with the `updates.url` field defined, and it broke my standalone application. I think I've narrowed down the issue to an incompatibility between expo-updates and expo-constants.

I've opened a new issue for that: https://github.com/expo/expo/issues/22046

**Comment by karimcambridge** [comment]
Hi, there is something seriously weird with eas update and expo go. I looked at @louislatreille's issue and I had already changed all `constants.manifest` to `constants.expoConfig`.

app.json
```{
  "expo": {
    "version": "0.1.01",
    "android": {
      "runtimeVersion": "0.1.01"
    },
    "ios": {
      "runtimeVersion": {
        "policy": "sdkVersion"
      }
    },
    "updates": {
      "enabled": true,
      "fallbackToCacheTimeout": 0,
      "url": "https://u.expo.dev/67c49406-6634-447c-877e-f1405a87b60b"
    }
  }
}
```

package.json
```
    "publish": "eas update --branch master",
```

eas.json
```
{
  "cli": {
    "version": ">= 0.34.0",
    "appVersionSource": "remote"
  },
  "build": {
    "base": {
      "env": {},
      "channel": "base"
    },
    "master": {
      "extends": "base",
      "developmentClient": false,
      "distribution": "internal",
      "channel": "master"
    },
    "development": {
      "extends": "base",
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development"
    },
    "production": {
      "extends": "base",
      "distribution": "store",
      "channel": "production",
      "android": {
        "buildType": "app-bundle"
      },
      "autoIncrement": true
    }
  },
  "submit": {
    "production": {
      "android": {
        "serviceAccountKeyPath": "./utils/google-services.json",
        "track": "production"
      },
      "ios": {
        "appleId": "karimcambridge@gmail.com",
        "ascAppId": "commented_out",
        "appleTeamId": "commented_out"
      }
    }
  }
}
```

I tried following all the issues but nothing seems to work for me. As long as `url` is in `updates` in `app.json` my app crashes on load.

Am I still doing something wrong? (I'm only using ios at the moment).

**Comment by sean-fletching** [comment]
It could be a stretch, but I experienced some unexpected behaviors after setting `sdkVersion` in `app.json` to the exact package of `expo` from `package.json`... which is what the docs said to do... and I submitted a bug in teh docs for that. https://github.com/expo/expo/issues/23092

🍻
