### ISSUE TITLE
Android build failed in EAS ([stderr] androidManifest.manifest.hasOwnProperty is not a function )

### ISSUE THREAD

**Issue by HimanshuCF** [expo/expo#22083]
### Summary

When creating a EAS build for Android, it fails with error below. it builds successfully on iOS.
 
**Error code in prebuild(run expo doctor passed)**

```
yarn run v1.22.17
$ /home/expo/workingdir/build/node_modules/.bin/expo prebuild --no-install --platform android
- Creating native project directories (./ios and ./android) and updating .gitignore
✔ Created native project | gitignore skipped
- Adding Metro bundler config
- Updating your package.json scripts, dependencies, and main file
✔ Updated package.json and added index.js entry point for iOS and Android
- Config syncing
[stderr] 
Using node to generate images. This is much slower than using native packages.
[stderr] 
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
- Config syncing
✖ Config sync failed
[stderr] 
TypeError: [android.manifest]: withAndroidManifestBaseMod: androidManifest.manifest.hasOwnProperty is not a function
[stderr] 
TypeError: [android.manifest]: withAndroidManifestBaseMod: androidManifest.manifest.hasOwnProperty is not a function
[stderr] 
    at setAndroidPermissions (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/android/Permissions.js:151:33)
[stderr] 
    at /home/expo/workingdir/build/node_modules/@expo/config-plugins/build/android/Permissions.js:51:31
[stderr] 
    at action (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:29)
[stderr] 
    at interceptingMod (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:27)
[stderr] 
    at action (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:240:14)
[stderr] 
    at async interceptingMod (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
[stderr] 
    at async action (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:71:21)
[stderr] 
    at async interceptingMod (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
[stderr] 
    at async evalModsAsync (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:256:25)
[stderr] 
    at async Object.compileModsAsync (/home/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:160:10)
[stderr] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn exited with non-zero code: 1
```

### What platform(s) does this occur on?

Android

### SDK Version

Expo SDK 48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.9.0
      expo-cli: 6.3.2
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/HimanshuCF/cfApp

**Comment by brentvatne** [comment]
you can get more information to help you debug the config plugin with `DEBUG=* npx expo prebuild -p android`

**Comment by HimanshuCF** [comment]
@brentvatne Thanks for the suggestion. Can you please have a look at my app.json and app.config.js and see if you can help in any way. 
Thanks.

**Comment by TMaszko** [comment]
@HimanshuCF It's not an issue in the expo itself you can check issue that I linked. Just use older version of the xml2js lib.
