### ISSUE TITLE
web build [npx expo export:web] getting failed - TypeError: tapable_1.AsyncSeriesWaterfallHook is not a constructor 

### ISSUE THREAD

**Issue by viveksc1994** [expo/expo#22155]
### Summary

When I try to build for web with `npx expo export:web ` It throws below error and build getting failed
`TypeError: tapable_1.AsyncSeriesWaterfallHook is not a constructor
TypeError: tapable_1.AsyncSeriesWaterfallHook is not a constructor
    at createWebpackPluginHooks (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\@expo\webpack-config\webpack\plugins\JsonWebpackPlugin.js:7:21)
    at Function.getHooks (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\@expo\webpack-config\webpack\plugins\JsonWebpackPlugin.js:48:21)     
    at D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\@expo\webpack-config\webpack\plugins\ModifyJsonWebpackPlugin.js:20:35
    at AsyncParallelHook.eval [as callAsync] (eval at create (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:76:17)
    at AsyncParallelHook.lazyCompileHook (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)     
    at D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\lib\Compiler.js:669:20
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)       
    at Compiler.compile (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\lib\Compiler.js:662:28)
    at D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\lib\Compiler.js:321:11
    at Compiler.readRecords (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\lib\Compiler.js:529:11)
    at D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\lib\Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)       
    at D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\lib\Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Demo\npx-expo-export-web-getting-failed\npx-expo-export-web-getting-failed\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)`

When I check with old command `expo build:web` It is working fine and generating build in `web-build` folder.

but as per official document it says to build with `npx expo export:web` (https://docs.expo.dev/distribution/publishing-websites/#create-a-build)

Am I doing something wrong?

### What platform(s) does this occur on?

Web

### SDK Version

48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      babel-preset-expo: ^9.3.0 => 9.3.2 
      expo: ~48.0.0 => 48.0.11
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.8 => 0.70.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/viveksc1994/npx-expo-export-web-getting-failed

**Comment by viveksc1994** [comment]
Hi @Kudo,
It is working with `"tapable": "~2.2.1"`.
