### ISSUE TITLE
exp start : Could not access packager status at http://localhost:19002/status. Are you sure the packager is running and reachable?

### ISSUE THREAD

**Issue by LeDoudou** [expo/expo#2219]
Does anyone know how to solve the following error ? 
(I have the same error with "exp" and "expo")

 **exp start**
We've built a brand new CLI for Expo!
Expo CLI is a drop in replacement for exp.
Install: npm install -g expo-cli
Use: expo --help
Read more: https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c
[14:56:41] Using project at /Users/edouardmalot/Desktop/test/FirstExpo
[14:56:47] Starting Metro Bundler on port 19002.
[14:56:47] Metro Bundler ready.
[14:57:14] Could not access packager status at http://localhost:19002/status. Are you sure the packager is running and reachable?
[14:57:14] Error: Could not access packager status at http://localhost:19002/status. Are you sure the packager is running and reachable?
    at Timeout._onTimeout (/xdl@51.3.0/src/Project.js:1490:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by ugurdonmez** [comment]
I have same issue. I have spent half of the day but did not find any solution.

**Comment by emmanuel-2u** [comment]
I also have same issue. Though, am able to get the project to build and work before (and if it's not working, I'll just clear the metro cache in temp folder), but nothing is now working again!

**Comment by acomito** [comment]
same issue

**Comment by ugurdonmez** [comment]
I changed node version with nvm and it looks fine now.

**Comment by acomito** [comment]
I see, what version did the trick @ugurdonmez ?

**Comment by ugurdonmez** [comment]
@acomito I was using node 10, Then I installed node 8 with nvm.

**Comment by acomito** [comment]
```
[09:42:40] Starting Metro Bundler on port 19001.
[09:42:40] Metro Bundler ready.
[09:43:03] Metro Bundler process exited with code null
[09:43:03] Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
now I still get an error at Metro Bundler ready.

**Comment by acomito** [comment]
```
[10:04:20] Starting Metro Bundler on port 19001.
[10:04:21] Metro Bundler ready.
[10:04:49] Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
[10:04:49] Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
```

yet when I go to `http://localhost:19001/status` I see:

```
packager-status:running
```

**Comment by esamelson** [comment]
Hi all - we're tracking issues with the CLI tools on the `expo-cli` repo now, so I'm going to close this in favor of https://github.com/expo/expo-cli/issues/52 (thanks for posting that, @acomito ).

**Comment by nitin78654** [comment]
Hii friends , just go and open your network & internet settings and change the network mode from public to private or vice-a -versa this will probably solve the issue

**Comment by elhoussine** [comment]
`expo start --tunnel` fixed it for me
