### ISSUE TITLE
[docs]  https://docs.expo.dev/guides/linking/ has incorrect url

### ISSUE THREAD

**Issue by marchingband** [expo/expo#22207]
### Summary

Docs state:
Open mail app, eg: `mailto: support@expo.dev`
but this fails `Unable to open URL:`
Correct URL is `mailto://support@expo.dev`
the `//` seems to be needed.

### Link to the related docs page

https://docs.expo.dev/guides/linking/

**Comment by dimonnwc3** [comment]
for me `mailto:support@expo.dev` is not working as well

expo 48.0.11
react-native 0.71.6
expo-linking 4.0.1

**Comment by Kudo** [comment]
hi there! could you help to double confirm what os version you have? e.g. android 13 or ios 16.4. that would help us to clarify if the issue is a regression from specific os version. thanks!

**Comment by dimonnwc3** [comment]
ios 16.4

**Comment by marchingband** [comment]
iOS 16.4

**Comment by Kudo** [comment]
hi there! i am testing this with expo go on ios 16.4. the problem is the space after the `mailto: ` scheme. removing the space should work: `mailto:support@expo.dev`. we've fixed [the document](https://docs.expo.dev/guides/linking/) already. thanks!

**Comment by dimonnwc3** [comment]
Issue stays for me

this is the code I'm running
and this code was working before 16.4

```
const mail = `mailto:meterable.app@gmail.com?body=
Device info: ${Platform.OS} ${Platform.Version ?? ""}
App version: ${nativeApplicationVersion}
License: ${license}`

if (await Linking.canOpenURL(mail)) {
    await Linking.openURL(mail)
}
```

And the error I receive
```
Error: Unable to open URL: file:///Users/dimonn/Library/Developer/CoreSimulator/Devices/E6197F31-D93E-4A25-9094-DF054A25C807/data/Containers/Bundle/Application/9FD541F8-86B0-4BCA-B0BE-3B3B531AECA4/Meterable.app/mailto:support@expo.dev%3Fbody=%0A%20%20%20%20%20%20%20%20%20%20%20%20Device%20info:%20ios%2016.4%0A%20%20%20%20%20%20%20%20%20%20%20%20App%20version:%202.6.17%0A%20%20%20%20%20%20%20%20%20%20%20%20License:%20pro
Error: Unable to open URL: file:///Users/dimonn/Library/Developer/CoreSimulator/Devices/E6197F31-D93E-4A25-9094-DF054A25C807/data/Containers/Bundle/Application/9FD541F8-86B0-4BCA-B0BE-3B3B531AECA4/Meterable.app/mailto:support@expo.dev%3Fbody=%0A%20%20%20%20%20%20%20%20%20%20%20%20Device%20info:%20ios%2016.4%0A%20%20%20%20%20%20%20%20%20%20%20%20App%20version:%202.6.17%0A%20%20%20%20%20%20%20%20%20%20%20%20License:%20pro
    at promiseMethodWrapper (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:3888:45)
    at openURL (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:96303:81)
    at ?anon_0_ (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:361717:48)
    at next (native)
    at asyncGeneratorStep (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4652:26)
    at _next (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4671:29)
    at anonymous (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4676:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4668:25)
    at apply (native)
    at openURL (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:361712:26)
    at ?anon_0_ (http://192.168.70.59:8081/screens/more-screen.bundle?platform=ios&hot=false&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:406:36)
    at next (native)
    at asyncGeneratorStep (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4652:26)
    at _next (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:4671:29)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29752:26)
    at _callTimer (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29671:17)
    at _callReactNativeMicrotasksPass (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29701:17)
    at callReactNativeMicrotasks (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:29864:44)
    at __callReactNativeMicrotasks (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2801:46)
    at anonymous (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2613:45)
    at __guard (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2785:15)
    at flushedQueue (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2612:21)
    at invokeCallbackAndReturnFlushedQueue (http://192.168.70.59:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:2606:33)
```

**Comment by Kudo** [comment]
@dimonnwc3 you have spaces in the url and i think you should encode them. please try with the following code:

```tsx
  const body = `
Device info: ${Platform.OS} ${Platform.Version ?? ""}
App version: ${Application.nativeApplicationVersion},
License: unknown`;
  const mail = `mailto:meterable.app@gmail.com?body=${encodeURIComponent(
    body
  )}`;

```

**Comment by dimonnwc3** [comment]
@Kudo  thanks, encoded url component works I confirm 👍
