### ISSUE TITLE
eas submit -p ios --latest --non-interactive fastlane fails in CI

### ISSUE THREAD

**Issue by wollerman** [expo/expo#22262]
### Summary

A github action set up to run `eas submit -p ios --latest --non-interactive` is failing with an obscure fastlane bug.

Link to eas submission: https://expo.dev/accounts/froggytales/projects/froggytales-app/submissions/89ed563f-85f0-4f9d-bca8-e0a4ffa79117

```Starting the submit process
Downloading archive
Preparing artifact
Verifying archive
Creating ascApiJsonKey.json file with ASC credentials
Submitting iOS app to TestFlight...
Submitting the app with fastlane pilot
[stderr] 
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
: /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.121.0/lib/aws-sdk-s3/encryption/io_auth_decrypter.rb:23: syntax error, unexpected end, expecting ')' (SyntaxError)
[stderr] 
        end
[stderr] 
        ^~~
[stderr] 
/Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.121.0/lib/aws-sdk-s3/encryption/io_auth_decrypter.rb:55: syntax error, unexpected end, expecting ')'
[stderr] 
      end
[stderr] 
      ^~~
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.121.0/lib/aws-sdk-s3/encryption.rb:10:in `<top (required)>'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.121.0/lib/aws-sdk-s3/customizations.rb:5:in `<top (required)>'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.121.0/lib/aws-sdk-s3.rb:43:in `require_relative'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.121.0/lib/aws-sdk-s3.rb:43:in `<top (required)>'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/helper/s3_client_helper.rb:1:in `<top (required)>'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/s3.rb:2:in `<top (required)>'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:113:in `block in load_default_actions'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:112:in `each'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:112:in `load_default_actions'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane.rb:38:in `load_actions'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:34:in `start'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
[stderr] 
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
[stderr] 
	from /usr/local/bin/fastlane:23:in `load'
[stderr] 
	from /usr/local/bin/fastlane:23:in `<main>'
Fastlane pilot failed
fastlane exited with non-zero code: 1
Failed to submit the app
We couldn't figure out what went wrong. See logs to learn more.
```

### What platform(s) does this occur on?

iOS

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.8 => 0.70.8
      react-native-web: ~0.18.9 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.10.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

Configure `eas.json` with the following: 

```
  "submit": {
    "production": {
      "ios": {
        "ascAppId": "my-app-id"
      }
    }
  }
```

Ensure `Apple Distribution Certificate` and `App Store Connect API Key` are defined in `Expo Account Info`

Start a submit based on `--latest` build via `eas submit`.

**Comment by wollerman** [comment]
Turns out it was a transient issue and a run in a few hours eventually went through with no changes.
