### ISSUE TITLE
Legacy "expo doctor" command fails

### ISSUE THREAD

**Issue by danish-dct** [expo/expo#22301]
### Summary

While running EAS Build for android, it fails saying `Build failed: Failed to find 'build.gradle' file for project: /home/expo/workingdir/build/android/app.`

The build was working fine until morning but is not working since few hours. It shows a lot of warnings and throws a `TypeError` while running `expo doctor`:

```
Running "expo doctor"
- Validating global prerequisites versions...
✔ Validating global prerequisites versions passed
- Checking for incompatible packages...
✖ Checking for incompatible packages failed
[stderr] 
Error: Failed to find dependency tree for @unimodules/react-native-adapter: npm exited with non-zero code: 7
- Checking for conflicting global packages in project...
✖ Checking for conflicting global packages in project failed
- Verifying prebuild support package versions are compatible...
[stderr] 
Error: Failed to find dependency tree for expo-cli: npm exited with non-zero code: 7
✖ Verifying prebuild support package versions are compatible failed
- Checking dependency versions for compatibility with the installed Expo SDK...
[stderr] 
Error: Failed to find dependency tree for @expo/config-plugins: npm exited with non-zero code: 7
✖ Checking dependency versions for compatibility with the installed Expo SDK failed
Issues:
[stderr] 
/home/expo/workingdir/build/node_modules/npm/lib/cli.js:35
[stderr] 
      throw err
[stderr] 
      ^
[stderr] 
  
[stderr] 
  TypeError: Class extends value #<Object> is not a constructor or null
[stderr] 
      at Object.<anonymous> (/home/expo/workingdir/build/node_modules/npm/node_modules/fs-minipass/lib/index.js:136:4)
[stderr] 
      at Module._compile (node:internal/modules/cjs/loader:1155:14)
[stderr] 
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[stderr] 
      at Module.load (node:internal/modules/cjs/loader:1033:32)
[stderr] 
      at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[stderr] 
      at Module.require (node:internal/modules/cjs/loader:1057:19)
[stderr] 
      at require (node:internal/modules/cjs/helpers:103:18)
[stderr] 
      at Object.<anonymous> (/home/expo/workingdir/build/node_modules/npm/node_modules/cacache/lib/content/read.js:4:13)
[stderr] 
      at Module._compile (node:internal/modules/cjs/loader:1155:14)
[stderr] 
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
Advice:
  • Use npx expo install --check to review and upgrade your dependencies.
- Validating Expo Config...
✔ Validating Expo Config passed
- Checking package.json for common issues...
✔ Checking package.json for common issues passed
[stderr] 
✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.
Command "expo doctor" failed.
npx exited with non-zero code: 1
```

Note that when I run `expo doctor` in my local, it does not show any warning or error.
Please help.

### What platform(s) does this occur on?

Android

### SDK Version

47

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.3.1 - ~/Documents/MobileApps/dct/node_modules/.bin/npm
      Watchman: 20230108.221750.0 - /usr/local/bin/watchman
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed
```

### Minimal reproducible example

Here is my `eas.json`

```
{
	"cli": {
		"appVersionSource": "remote"
	},
	"build": {
		"preview": {
			"android": {
				"buildType": "apk"
			},
			"ios": {
				"simulator": true
			},
			"channel": "preview"
		},
		"preview2": {
			"android": {
				"gradleCommand": ":app:assembleRelease"
			},
			"channel": "preview2"
		},
		"preview3": {
			"developmentClient": true,
			"channel": "preview3"
		},
		"staging": {
			"channel": "staging"
		},
		"production": {
			"autoIncrement": true,
			"channel": "production"
		}
	}
}
```

Here is my `app.json`:

```
{
	"expo": {
		"name": "App",
		"slug": "app",
		"version": "1.0.5",
		"orientation": "portrait",
		"icon": "./src/assets/icon.png",
		"userInterfaceStyle": "light",
		"splash": {
			"image": "./src/assets/splash.png",
			"resizeMode": "contain",
			"backgroundColor": "#ffffff"
		},
		"updates": {
			"fallbackToCacheTimeout": 0
		},
		"assetBundlePatterns": [
			"**/*"
		],
		"ios": {
			"supportsTablet": true,
			"bundleIdentifier": "com.test.app"
		},
		"android": {
			"adaptiveIcon": {
				"foregroundImage": "./src/assets/icon.png",
				"backgroundColor": "#FFFFFF"
			},
			"package": "com.test.app",
			"versionCode": 6
		},
		"plugins": [
			[
				"expo-media-library",
				{
					"photosPermission": "Allow test to access your photos.",
					"savePhotosPermission": "Allow test to save photos.",
					"isAccessMediaLocationEnabled": true
				}
			],
			[
				"expo-image-picker",
				{
					"photosPermission": "The app accesses your photos to let you share them with your friends."
				}
			],
			[
				"expo-build-properties",
				{
					"android": {
						"enableProguardInReleaseBuilds": true,
						"extraProguardRules": "-keep public class com.horcrux.svg.** {*;}",
						"allowBackup": false
					}
				}
			]
		],
		"web": {
			"favicon": "./src/assets/favicon.png"
		},
		"extra": {
			"eas": {
        "projectId": "sadsad-sadsadsad-sa-dsadsad"
			}
		},
		"owner": "danishiqbal4"
	}
}
```

**Comment by brentvatne** [comment]
what do you see when you run `npx expo-doctor` locally?

**Comment by brentvatne** [comment]
also, can you share a link to your build page please?

**Comment by brentvatne** [comment]
actually, i suspect i know what the problem is. you likely have added an `android` directory to your project, which is not a valid android project. the expo doctor error is a red herring.
