### ISSUE TITLE
[CXX1400] More than one externalNativeBuild path specified

### ISSUE THREAD

**Issue by LouisMuriuki** [expo/expo#22455]
### Summary

I get this error when building a dev client of my app.(npx expo run:android -d)
it was an expo project that i prebuild, then i build apk with no issue. I decided to update to latest expo Sdk and react native version then it shows me the error.
I also have enabled hermes

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

 "@expo/html-elements": "^0.4.2",
    "@expo/vector-icons": "^13.0.0",
    "@fortawesome/fontawesome-svg-core": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/checkbox": "^0.5.15",
    "@react-native-community/netinfo": "9.3.7",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.5",
    "@realm/react": "^0.4.3",
    "@tanstack/react-query": "^4.29.5",
    "axios": "^1.4.0",
    "expo": "~48.0.16",
    "expo-asset": "~8.9.1",
    "expo-blur": "~12.2.2",
    "expo-constants": "~14.2.1",
    "expo-font": "~11.1.1",
    "expo-image-manipulator": "^11.1.1",
    "expo-network": "~5.2.1",
    "expo-notifications": "~0.18.1",
    "expo-print": "~12.2.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "immer": "^9.0.18",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-react-native": "5.1.4",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.7",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modalize": "^2.1.1",
    "react-native-pager-view": "6.1.2",
    "react-native-portalize": "^1.0.7",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-thermal-printer": "^2.3.5",
    "react-native-toast-notifications": "^3.3.1",
    "react-native-web": "~0.18.10",
    "react-phone-number-input": "^3.2.21",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "realm": "^11.8.0"

### Environment

System:
OS: Windows 10 10.0.19045
Binaries:
Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
SDKs:
Android SDK:
API Levels: 33
Build Tools: 33.0.2
IDEs:
Android Studio: AI-213.7172.25.2113.9123335
npmPackages:
expo: ~48.0.16 => 48.0.16
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.71.7 => 0.71.7
react-native-web: ~0.18.10 => 0.18.12
Expo Workflow: bare

### Reproducible demo

here is the repo with the reproducable
https://github.com/LouisMuriuki/automatic-eureka

##############################

Using react.gradle in your project is deprecated! You should move to "apply plugin: com.facebook.react"
react.gradle is going to be removed in a future React Native project and your project will not build anymore.
You can use the template as a reference:
https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle

##############################
[CXX1400] More than one externalNativeBuild path specified
[CXX1400] More than one externalNativeBuild path specified

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> [CXX1400] More than one externalNativeBuild path specified

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 59s
5 actionable tasks: 5 up-to-date
Error: C:\Users\Kinglui\Desktop\Work\Bizplus\BarPoint-App\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\Kinglui\Desktop\Work\Bizplus\BarPoint-App\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (C:\Users\Kinglui\Desktop\Work\Bizplus\BarPoint-App\node_modules\cross-spawn\lib\enoent.js:34:29)
    at Object.spawnAsync [as default] (C:\Users\Kinglui\Desktop\Work\Bizplus\BarPoint-App\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\Kinglui\Desktop\Work\Bizplus\BarPoint-App\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\Kinglui\Desktop\Work\Bizplus\BarPoint-App\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\Kinglui\Desktop\Work\Bizplus\BarPoint-App\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:31:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by LouisMuriuki** [comment]
I found out that you could rebuild your prebuild by ` npx expo prebuild --clean`
