### ISSUE TITLE
Crash during module dependency installation phase of `create-expo-module`

### ISSUE THREAD

**Issue by jameswilddev** [expo/expo#22534]
### Summary

`create-expo-module` appears to be broken.  It crashes out during module dependency installation (see minimal reproducible example).

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.1.0 - /opt/homebrew/bin/node
      npm: 9.6.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/jameswilddev/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.2
    Expo Workflow: bare
```

### Minimal reproducible example

```
npx create-expo-module@latest                
✔ What is the name of the npm package? … machine-learning-for-expo
✔ What is the native module name? … MachineLearningForExpo
✔ How would you describe the module? … Some tools for working with ML models in Expo applications.
✔ What is the Android package name? … jameswilddev.machinelearningforexpo
✔ What is the name of the package author? … jameswilddev
✔ What is the email address of the author? … jameswilddev@outlook.com
✔ What is the URL to the author's GitHub profile? … https://github.com/jameswilddev
✔ What is the URL for the repository? … https://github.com/jameswilddev/machine-learning-for-expo

✔ Downloaded module template from npm
✔ Created the module from template files
✖ Installing module dependencies
Error: npm install exited with non-zero code: 127
    at ChildProcess.completionListener (/Users/jameswilddev/.npm/_npx/df6d79204f77d516/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:626:26)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (/Users/jameswilddev/.npm/_npx/df6d79204f77d516/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at installDependencies (/Users/jameswilddev/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/packageManager.js:9:37)
    at /Users/jameswilddev/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/create-expo-module.js:86:60
    at newStep (/Users/jameswilddev/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/utils.js:21:22)
    at Command.main (/Users/jameswilddev/.npm/_npx/df6d79204f77d516/node_modules/create-expo-module/build/create-expo-module.js:85:35) {
  pid: 31192,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 127,
  signal: null
}
```

**Comment by jameswilddev** [comment]
Additional: the tool created some files which looks like a templating engine has not run, is this expected?

![image](https://github.com/expo/expo/assets/3138458/622f064e-3368-4e83-86dc-c2a6c8031f1f)

**Comment by jameswilddev** [comment]
It looks like the root cause might be that this needs `yarn` installed.

Is it correct that `yarn` needs to be installed, or is this documentation incomplete: https://docs.expo.dev/modules/native-module-tutorial/

**Comment by tsapeta** [comment]
Having `yarn` installed shouldn't be necessary. The script uses `yarn` only if you use `yarn create expo-module` which is an equivalent of `npx create-expo-module`.
Does it succeed after installing `yarn`?

**Comment by jameswilddev** [comment]
Yes.

**Comment by tsapeta** [comment]
This issue should be fixed as of `create-expo-modules@0.6.2` 😉

**Comment by floka94** [comment]
@tsapeta unfortunately it isn´t fixed. Just tried it, same error :-(

**Comment by rmmeans** [comment]
This was also hitting me. I just insured I was using create-expo-module@latest (0.6.3). For whatever reason, my default node was on v18.15, when i switched to node 16 everything was fine. I'm on expo 49.

**Comment by mattsellars123** [comment]
I get this on 0.6.4 using npx or yarn

**Comment by voxlz** [comment]
i just got this on create-expo-module@0.6.7 using npx. using node 21.

**Comment by weilantian** [comment]
For those who may encounter the issue due to use yarn not npm to initialize the expo project, try to use yarn instaed of npm when creating the expo module.

In my case `yarn create expo-module` successfully created the module

**Comment by ahmed-zhran** [comment]
I have this problem now, I tried many combinations of node versions and create-expo-module versions but nothing working out same error for all (npx and yarn way both of them neither worked out).... any solution for that or at least some working version combination!!

**Comment by germy-BD** [comment]
yeah, so `yarn create expo-module your_module` work as expected (if using `yarn`). the previous result doing `npx create-expo-module your_module` returned this error:
```
✖ Installing module dependencies
Error: npm install exited with non-zero code: 243
    at ChildProcess.completionListener (node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
```
this creates a folder with bad naming of folders and files (look [here](https://github.com/expo/expo/issues/22534#issuecomment-1552791193) for images).

I recommend closing the comment section for this bug!

**Comment by ahmed-zhran** [comment]
@germy-BD it didn't work for me even after trying yarn, still getting this: "Error: npm install exited with non-zero code: 127
    at ChildProcess.completionListener (/Users/jameswilddev/.npm/_npx/df6d79204f77d516/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)", and if it works for you shall I ask about node and expo-module version that worked out.
    I tried a lot [.......](https://github.com/expo/expo/issues/22534#issuecomment-2384607871)

**Comment by Aperezpe** [comment]
I'm having same issue when trying `npx expo install -- --save-dev jest-expo jest @types/jest`.
Any idea?
