### ISSUE TITLE
Android debug build Failure happening. No changes in code was made, it was working fine earlier.

### ISSUE THREAD

**Issue by Kailash-MAF** [expo/expo#22577]
### Minimal reproducible example

If this is not quick one I will help u replicating the issue.

### Summary

Yesterday, our project was working perfectly fine with no reported issues or errors. However, today, while trying to run the project, we encountered error that we have been unable to resolve on our own. I suspect this issue seems to have originated from the recent developments or changes that have been made on your end.

```
kailashuniyal@C02F5D1BMD6M cwings-delivery-app % yarn && yarn run android:cwings:stg
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ patch-package
patch-package 6.5.1
Applying patches...
@react-navigation/bottom-tabs@5.11.15 ✔
react-native-signature-capture@0.4.12 ✔
$ husky install
husky - Git hooks installed
✨  Done in 1.23s.
yarn run v1.22.19
$ react-native run-android --variant=cwingsstagingdebug --port $npm_package_config_port
info JS server already running.
info Installing the app...

> Configure project :
VersionName is set to 0.0.1
VersionCode is set to 1

> Configure project :app
Reading env from: .env
Reading env from: .env.cwings.stg
[react-native-background-geolocation] Purging debug resources in release build
[react-native-background-geolocation] Purging debug resources in release build
[react-native-background-geolocation] Purging debug resources in release build
[react-native-background-geolocation] Purging debug resources in release build
[react-native-background-geolocation] Purging debug resources in release build
[react-native-background-geolocation] Purging debug resources in release build

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-av
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-barcode-scanner
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-battery
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-camera
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-error-recovery
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-loader
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-location
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/expo/android/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':expo'.
> Cannot invoke method multiply() on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file '/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/expo/android/build.gradle' line: 78

* What went wrong:
A problem occurred configuring project ':expo'.
> Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installCwingsstagingdebug -PreactNativeDevServerPort=9000

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/expo/android/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':expo'.
> Cannot invoke method multiply() on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file '/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/expo/android/build.gradle' line: 78

* What went wrong:
A problem occurred configuring project ':expo'.
> Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at makeError (/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/execa/index.js:174:9)
    at /Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/kailashuniyal/Desktop/cwings-delivery-app/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
kailashuniyal@C02F5D1BMD6M cwings-delivery-app % 
```

### Environment

kailashuniyal@C02F5D1BMD6M cwings-delivery-app % npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.2.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.6 - /usr/local/bin/npm
      Watchman: 2023.05.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/kailashuniyal/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.16 => 46.0.21 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.9 => 0.70.9 
    Expo Workflow: bare

**Comment by Kailash23** [comment]
This is due to disk permission issue.

**Comment by mTdev1** [comment]
Same issue
