### ISSUE TITLE
expo-secure-store fails to decrypt on Android 13 Google Pixel family

### ISSUE THREAD

**Issue by james-em** [expo/expo#22805]
### Minimal reproducible example

N/A

### Summary

Non ejected app crash at startup on EAS build.
Appears to only happen on Google Pixel family running Android 13.
The error doesn't happen on a Samsung Galaxy S22 running Android 13.

Only happens on builds generated in expo.dev. **Running the app in Expo.go works fine.**

Happens on both SDK 47/48. Havn't tried older version of the SDK.

```
    "expo-secure-store": "~12.1.1",
    "expo": "^48.0.0",
    "react-native": "0.71.8",
```

As an extra note, when my client reported to me for the first time some people wasn't able to launch the app, I wasn't able to reproduce it on my Pixel until I uninstall and reinstall the app. It could be something about having a clean empty storage or some OS update that screwed something. It used to work and not a single line of code changed, but I did get OS updates for the past months. Updating from SDK 47 to 48 did not fix the issue.

Here is the ADB logcat of the crash

```
06-08 10:50:49.444 12921 12961 I ExpoModulesCore: ✅ JSI interop was installed
06-08 10:50:49.454 12921 12961 I ExpoModulesCore: ✅ Constants were exported
06-08 10:50:49.615 12921 12961 I ReactNativeJS: Running "main
06-08 10:50:49.631   566   566 E TrustyKeymaster: Response of size 4 contained error code -30
06-08 10:50:49.633   566   566 E trusty_keymaster_hal: Cmd 12 returned error: -30
06-08 10:50:49.633   563  9923 E keystore2: keystore2::error: In KeystoreOperation::finish
06-08 10:50:49.633   563  9923 E keystore2: 
06-08 10:50:49.633   563  9923 E keystore2: Caused by:
06-08 10:50:49.633   563  9923 E keystore2:     0: In finish: KeyMint::finish failed.
06-08 10:50:49.633   563  9923 E keystore2:     1: Error::Km(ErrorCode(-30))
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: javax.crypto.AEADBadTagException
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:611)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule$AESEncrypter.lambda$decryptItem$1(SecureStoreModule.java:466)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule$AESEncrypter$$ExternalSyntheticLambda0.run(Unknown Source:2)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.AuthenticationHelper.handleEncryptionCallback(AuthenticationHelper.kt:86)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.AuthenticationHelper$defaultCallback$1.checkAuthentication(AuthenticationHelper.kt:73)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule$AESEncrypter.decryptItem(SecureStoreModule.java:464)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule.readJSONEncodedItem(SecureStoreModule.java:205)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule.getItemImpl(SecureStoreModule.java:177)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule.getValueWithKeyAsync(SecureStoreModule.java:165)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.core.ExportedModule.invokeExportedMethod(ExportedModule.java:98)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.adapters.react.NativeModulesProxy.callMethod(NativeModulesProxy.java:178)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.kotlin.defaultmodules.NativeModulesProxyModule$definition$lambda$1$$inlined$AsyncFunction$1.invoke(ObjectDefinitionBuilder.kt:387)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.kotlin.defaultmodules.NativeModulesProxyModule$definition$lambda$1$$inlined$AsyncFunction$1.invoke(ObjectDefinitionBuilder.kt:248)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.kotlin.functions.AsyncFunctionWithPromiseComponent.callUserImplementation$expo_modules_core_release(AsyncFunctionWithPromiseComponent.kt:19)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at expo.modules.kotlin.functions.AsyncFunction$attachToJSObject$2$1.invokeSuspend(AsyncFunction.kt:69)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.os.Handler.handleCallback(Handler.java:942)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.os.Looper.loopOnce(Looper.java:201)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.os.Looper.loop(Looper.java:288)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: Caused by: android.security.KeyStoreException: Signature/MAC verification failed (internal Keystore code: -30 message: In KeystoreOperation::finish
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: Caused by:
06-08 10:50:49.634 12921 12953 W ExpoSecureStore:     0: In finish: KeyMint::finish failed.
06-08 10:50:49.634 12921 12953 W ExpoSecureStore:     1: Error::Km(ErrorCode(-30))) (public error code: 10 internal Keystore code: -30)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
06-08 10:50:49.634 12921 12953 W ExpoSecureStore: 	... 23 more
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.13.3
    Expo Workflow: managed
```

**Comment by james-em** [comment]
If anyone ever have the same error

https://stackoverflow.com/questions/55665337/keystoreexception-signature-mac-verification-failed-when-trying-to-decrypt
