### ISSUE TITLE
[expo-image-picker] launchMediaLibraryAsync returns empty object in android release builds

### ISSUE THREAD

**Issue by CoffeeFlux** [expo/expo#22811]
### Minimal reproducible example

https://github.com/CoffeeFlux/expo-proguard-test2

### Summary

Similar to https://github.com/expo/expo/issues/19509 it seems to be ProGuard-related.

It only allows selecting a single image and returns an empty object when ProGuard is enabled. To see in the example, just `npm i && npm run android`, and it'll build release.

The difference here is that to trigger it from a sample project, the Gradle build tools version needs to be 7.3x or below. It seems to not happen on 7.4.1, but for many projects bumping this is impossible due to dependencies with hard-coded Kotlin version limits.

I'm unclear whether this is something you're willing to fix upstream or if I'll just need custom ProGuard rules, but I'm not sure how to even go about putting together a custom rule for this.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.2.15 - /opt/homebrew/opt/bash/bin/bash
    Binaries:
      Node: 16.20.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.3.x => 0.3.22 
      expo: ^47.0.13 => 47.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.7
    Expo Workflow: bare

**Comment by CoffeeFlux** [comment]
If it's helpful, I see the following in logcat after opening the image picker (with the log level set to warning):
```06-08 14:32:11.147  4170  4220 E HYPER-HAL: [HandlerSysfs.cpp]doResourceHandling(): Couldn't Open Sysfs - /sys/kernel/mm/vmscan/am_app_launch
06-08 14:32:11.153  4565  6785 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (38962059)
06-08 14:32:11.157  4565  6785 W WindowManager: Execute app transition: mNextAppTransition=TRANSIT_ACTIVITY_OPEN, displayId: 0 Callers=com.android.server.wm.RootWindowContainer.executeAppTransitionForAllDisplay:2609 com.android.server.wm.ActivityStackSupervisor.reportResumedActivityLocked:2265 com.android.server.wm.ActivityRecord.completeResumeLocked:5710 com.android.server.wm.ActivityStack.minimalResumeActivityLocked:1225 com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked:1152 
06-08 14:32:11.163  4565  4800 W PkgPredictorService: background app without no launcher icon com.google.android.documentsui for.uid: 10280 userId: 0
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: Failed to resume: 
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: java.io.FileNotFoundException: name
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.base.DocumentInfo.asFileNotFoundException(DocumentInfo.java:427)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.base.DocumentInfo.updateFromUri(DocumentInfo.java:221)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.base.DocumentInfo.updateSelf(DocumentInfo.java:205)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.base.DocumentStack.updateDocuments(DocumentStack.java:240)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.base.DocumentStack.fromLastAccessedCursor(DocumentStack.java:255)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.picker.LastAccessedStorage$RuntimeLastAccessedStorage.getLastAccessed(LastAccessedStorage.java:66)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.picker.ActionHandler.initLoadLastAccessedStack(ActionHandler.java:176)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.picker.ActionHandler.initLocation(ActionHandler.java:135)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.picker.PickActivity.onCreate(PickActivity.java:162)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.Activity.performCreate(Activity.java:8198)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.Activity.performCreate(Activity.java:8182)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3773)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3976)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.os.Looper.loop(Looper.java:246)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.app.ActivityThread.main(ActivityThread.java:8550)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: Caused by: java.lang.NullPointerException: name
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at java.util.Objects.requireNonNull(Objects.java:245)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at android.content.ContentResolver.acquireUnstableContentProviderClient(ContentResolver.java:2594)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.DocumentsApplication.acquireUnstableProviderOrThrow(DocumentsApplication.java:85)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	at com.android.documentsui.base.DocumentInfo.updateFromUri(DocumentInfo.java:213)
06-08 14:32:11.200 32181 32181 W LastAccessedStorage: 	... 22 more
06-08 14:32:11.201 32181 32181 E oid.documentsu: No package ID ff found for ID 0xffffffff.
06-08 14:32:11.213 32181 32181 W SelectionTracker: Setting gestureTooltypes is likely to result in unexpected behavior.
06-08 14:32:11.229 32181 32181 E oid.documentsu: No package ID ff found for ID 0xffffffff.
06-08 14:32:11.229 32181  7553 W RefreshTask: Failed to refresh
06-08 14:32:11.229 32181  7553 W RefreshTask: java.lang.NullPointerException: name
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at java.util.Objects.requireNonNull(Objects.java:245)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at android.content.ContentResolver.acquireUnstableContentProviderClient(ContentResolver.java:2594)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at com.android.documentsui.DocumentsApplication.acquireUnstableProviderOrThrow(DocumentsApplication.java:85)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at com.android.documentsui.RefreshTask.run(RefreshTask.java:108)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at com.android.documentsui.RefreshTask.run(RefreshTask.java:43)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at com.android.documentsui.base.CheckedTask.doInBackground(CheckedTask.java:65)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-08 14:32:11.229 32181  7553 W RefreshTask: 	at com.android.documentsui.ProviderExecutor.run(ProviderExecutor.java:104)
06-08 14:32:11.250 32181 32181 E oid.documentsu: No package ID ff found for ID 0xffffffff.
06-08 14:32:11.418 32181 32181 E oid.documentsu: No package ID ff found for ID 0xffffffff.
06-08 14:32:11.434 32181 32181 E oid.documentsu: No package ID ff found for ID 0xffffffff.
06-08 14:32:11.508  4170  4220 E HYPER-HAL: [Request.cpp]acquire(): Request:: id : 10499670, No Resource to set
06-08 14:32:11.836  4232  5415 E BufferQueueProducer: [com.expoproguardtest/com.expoproguardtest.MainActivity$_9776#0](id:10880000034a,api:0,p:-1,c:4232) disconnect: not connected (req=1)
06-08 14:32:11.836  9776 10458 W libEGL  : EGLNativeWindowType 0x799613d010 disconnect failed
06-08 14:32:11.852  4565  6754 E WindowManager: win=Window{4f5689d u0 com.expoproguardtest/com.expoproguardtest.MainActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5251 com.android.server.wm.ActivityRecord.destroySurfaces:5232 com.android.server.wm.ActivityRecord.notifyAppStopped:5291 com.android.server.wm.ActivityRecord.activityStopped:5918 com.android.server.wm.ActivityTaskManagerService.activityStopped:2584 android.app.IActivityTaskManager$Stub.onTransact:2215 android.os.Binder.execTransactInternal:1190 
06-08 14:32:13.074  4565  4590 E Watchdog: !@Sync: 1307 heap: 70 / 81 [2023-06-08 15:32:13.074] sdogWay: softdog
06-08 14:32:14.162  4565  6460 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
06-08 14:32:15.148  4170 11018 E HYPER-HAL: [HandlerSysfs.cpp]doResourceHandling(): Couldn't Open Sysfs - /sys/kernel/mm/vmscan/am_app_launch```

**Comment by CoffeeFlux** [comment]
This issue still exists.
