### ISSUE TITLE
[docs] "yarn create expo" suggests commands that don't work

### ISSUE THREAD

**Issue by crummy** [expo/expo#23116]
### Summary

1. `yarn create expo` - finishes with this output:
```
To run your project, navigate to the directory and run one of the following yarn commands.

- cd app-name
- yarn android
- yarn ios
- yarn web
```
3. Enter an app name
4. `cd app-name`
5. `yarn ios`
```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at spawn (/Users/crummy/code/earth/mobile/parent-app-2/.yarn/cache/cross-spawn-npm-6.0.5-2deab6c280-f893bb0d96.zip/node_modules/cross-spawn/index.js:12:24)
    at run (/Users/crummy/code/earth/mobile/parent-app-2/.yarn/unplugged/expo-npm-48.0.19-3d5e78cd8e/node_modules/expo/bin/cli.js:11:12)
    at Object.<anonymous> (/Users/crummy/code/earth/mobile/parent-app-2/.yarn/unplugged/expo-npm-48.0.19-3d5e78cd8e/node_modules/expo/bin/cli.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at require$$0.Module._extensions..js (/Users/crummy/code/earth/mobile/parent-app-2/.pnp.cjs:21798:33)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at require$$0.Module._load (/Users/crummy/code/earth/mobile/parent-app-2/.pnp.cjs:21617:22) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'spawn'
}

Node.js v18.14.0
```

Either `yarn ios` should work out of the box like this, or it should not be a suggestion. I see the same with `yarn web` and `yarn android`.

### Link to the related docs page

`yarn create expo` is suggested here: https://docs.expo.dev/get-started/installation/

### Anything else?
```
> yarn --version
3.5.1
```

**Comment by brentvatne** [comment]
it looks like you're using yarn plug-n-play with yarn v2. unfortunately this isn't yet supported in react-native. maybe we should validate against this in our cli and warn, cc @byCedric / @keith-kurak 

to fix this, add the `nodeLinker` in your yarn config.
-> In .yarnrc.yml in your project, add `nodeLinker: node-modules`
