### ISSUE TITLE
Expo Barcode Scanner bug "invokeSuspend"

### ISSUE THREAD

**Issue by juanmigdr** [expo/expo#23198]
### Minimal reproducible example

I am not able to reproduce it locally, I get this error reported from the Play Console Crashes and ANR page

### Summary

I am seeing the following error in my expo app, I am not able to reproduce it and therefore I dont know when the error is thrown.

**Error**
expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend
`Exception java.lang.RuntimeException: getParameters failed (empty parameters)
  at android.hardware.Camera.native_getParameters
  at android.hardware.Camera.getParameters (Camera.java:2111)
  at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend (BarCodeScannerViewFinder.kt:196)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)`

**Code**
const handleBarCodeScanned = async ({ data }: any) => {
  setIsScanning(false);
  setSearchText(data);
  await handleSearch(data);
};

<SafeAreaView style={styles.container}>
  {isScanning ? (
    <View style={{ flex: 1 }}>
      <BarCodeScanner
        onBarCodeScanned={handleBarCodeScanned}
        style={StyleSheet.absoluteFillObject}
      />
    </View>
  ) : ( ...More code... )}
</SafeAreaView>

**Managed or bare workflow?**
Managed

**What platform(s) does this occur on?**
Android

**Expo version**
48.0.4

**expo-barcode-scanner version**
12.3.2

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

**Comment by mccraveiro** [comment]
@juanmigdr I'm seeing the same errors with `"expo-barcode-scanner": "12.5.1"`. I have no idea how to reproduce this.

**Comment by Glaubenio** [comment]
I'm having this error too, i think this issue should be reopened

**Comment by douglasjunior** [comment]
@Kudo sorry for tag you here, but we need some assistance on this issue, maybe you just can reopen the issue for us.

This seems related to camera component, I found a discussion here https://github.com/journeyapps/zxing-android-embedded/issues/270#issuecomment-287733422

I know that this type of crash is hard to debug, but a workaround can be just to put the `camera.getParameters` inside a try/cache to avoid these crashes.

I think that is on this line: https://github.com/expo/expo/blob/ab69adb122beabdcfb53620f3b8c11a00ac09241/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt#L196

Here we are seeing these logs on crashlytics:

```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2167)
       at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend(BarCodeScannerViewFinder.kt:196)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
