### ISSUE TITLE
Android prebuild does not work

### ISSUE THREAD

**Issue by laptou** [expo/expo#23208]
### Summary

The Android project generated by `expo prebuild` does not compile, and has resisted all of my attempts to debug it using the information I could glean from #18129.

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 Manjaro Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.2.0 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.19.2 - /usr/bin/npm
    SDKs:
      Android SDK:
        Android NDK: 25.2.9519653
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    Expo Workflow: bare
```

### Minimal reproducible example

I created a brand-new Expo project using a template:

```
yarn create expo-app AwesomeProject
```

Then I prebuild it so that I can later add native modules like Reanimated 3:

```
cd AwesomeProject
yarn expo prebuild
yarn android
````

And it does not compile:
```
yarn run v1.22.19
$ expo run:android
› Building app...
Configuration on demand is an incubating feature.

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/mnt/bigboy/scratch/AwesomeProject/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 326

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > Failed to notify project evaluation listener.
      > Process 'command '/home/ibiyemi/.local/bin/cmake'' finished with non-zero exit value 1
      > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
5 actionable tasks: 4 executed, 1 from cache
Error: /mnt/bigboy/scratch/AwesomeProject/android/gradlew exited with non-zero code: 1
Error: /mnt/bigboy/scratch/AwesomeProject/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/mnt/bigboy/scratch/AwesomeProject/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:626:26)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at Object.spawnAsync [as default] (/mnt/bigboy/scratch/AwesomeProject/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/mnt/bigboy/scratch/AwesomeProject/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/mnt/bigboy/scratch/AwesomeProject/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/mnt/bigboy/scratch/AwesomeProject/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:31:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brentvatne** [comment]
> process 'command '/home/ibiyemi/.local/bin/cmake'' finished with non-zero exit value 1

it looks like your cmake installation is broken. make sure the android sdk is installed and working properly on your machine

**Comment by laptou** [comment]
That was indeed the issue. Thanks!

**Comment by Elozino** [comment]
I have the same issue. Thanks
