### ISSUE TITLE
[Andoid][SDK 49 beta] java.lang.NoSuchMethodError: No virtual method getOnBackInvokedDispatcher()

### ISSUE THREAD

**Issue by kylegillen** [expo/expo#23236]
### Minimal reproducible example

https://github.com/nextriot/expobug-sdk49

### Summary

Bare workflow. Adding Expo 49 beta to RN 72 or 72.1 causes the following crash as soon as the app opens on an emulator.

```
FATAL EXCEPTION: main
Process: com.expobug, PID: 5561
java.lang.NoSuchMethodError: No virtual method getOnBackInvokedDispatcher()Landroid/window/OnBackInvokedDispatcher; in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
	at androidx.activity.ComponentActivity$Api33Impl.getOnBackInvokedDispatcher(ComponentActivity.java:1139)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:383)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217)
	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:8257)
	at android.app.Activity.performCreate(Activity.java:8237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1339)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3660)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3816)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:99)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2299)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7850)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.7
      Shell: 5.1.16 - /opt/homebrew/bin/bash
    Binaries:
      Node: 20.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - /opt/homebrew/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/[HOME]/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-32 | Google APIs ARM 64 v8a, android-Tiramisu | Google APIs ARM 64 v8a, android-Tiramisu | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0-beta.2 => 49.0.0-beta.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
    Expo Workflow: bare

**Comment by Kudo** [comment]
hi there! what is the android emulator you tested and what's the android api level?

**Comment by nextriot** [comment]
Hi Kudo. The emulator was a Pixel 6, and the API level was technically 33, however, the image that was used from Android studio was the 'Android Tiramisu' one, not the 'Android 33' one.

**Comment by Kudo** [comment]
does it happen on other android emulator images? i tried your repo on both android 31 with google-apis and android 33 with google-apis, both works. since the stacktrace shows that the call is actually from androidx, and not specific expo or react-native related. i am wondering if that's some android emulator specific.

**Comment by nextriot** [comment]
No, I actually can't reproduce it on another emulator. It was only that specific API disk image / emulator combination 🤷‍♂️
