### ISSUE TITLE
Jest broken in tabs@49 template

### ISSUE THREAD

**Issue by mikeylemmon** [expo/expo#23400]
### Summary

The jest test built into the create-expo-app tabs@49 template fails, seemingly due to a lack of configured support for tsconfig path aliases:

```
npx create-expo-app@latest --template tabs@49 jest-broken
cd jest-broken
npm run test

 FAIL  components/__tests__/StyledText-test.js
  ● Test suite failed to run

    Cannot find module '@/constants/Colors' from 'components/Themed.tsx'

    Require stack:
      components/Themed.tsx
      components/StyledText.tsx
      components/__tests__/StyledText-test.js

       6 | import { Text as DefaultText, useColorScheme, View as DefaultView } from 'react-native';
       7 |
    >  8 | import Colors from '@/constants/Colors';
         | ^
       9 |
      10 | type ThemeProps = {
      11 |   lightColor?: string;

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (components/Themed.tsx:8:1)
      at Object.require (components/StyledText.tsx:1:1)
      at Object.require (components/__tests__/StyledText-test.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.017 s
Ran all test suites.
```

### SDK Version

49.0.1

### Environment

  ```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.8
      Shell: 5.0.7 - /usr/local/bin/bash
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/<user>/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.1 => 49.0.1
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: managed
```

### Minimal reproducible example

```
npx create-expo-app@latest --template tabs@49 jest-broken
cd jest-broken
npm run test
```

**Comment by mikeylemmon** [comment]
Updating the "jest" field in the project's package.json to the following resolves the issue:

```
  "jest": {
    "preset": "jest-expo",
    "moduleNameMapper": {
      "@/(.*)": "<rootDir>/$1"
    }
  },
```

To avoid duplicating the alias mappings, it appears another approach would be to use ts-jest, though I have not attempted this myself: https://kulshekhar.github.io/ts-jest/docs/getting-started/paths-mapping/#jest-config-with-helper
