### ISSUE TITLE
Android SDK 31 does not compile

### ISSUE THREAD

**Issue by ide** [expo/expo#2347]
There were many Gradle changes. The `sdk-31-candidate` branch fails on the step `:ReactAndroid:prepareJSC`. Run `yarn` in `tools-public` and then run `./run.sh` in `android`:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ide/sdks/android/ReactAndroid/build.gradle' line: 143

* What went wrong:
Execution failed for task ':ReactAndroid:prepareJSC'.
> Expected configuration ':ReactAndroid:compile' to contain exactly one file, however, it contains no files.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ReactAndroid:prepareJSC'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Expected configuration ':ReactAndroid:compile' to contain exactly one file, however, it contains no files.
        at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:59)
        at build_2djqh2xzm6mzczvqynvew2jal$_run_closure11$_closure24.doCall(/Users/ide/sdks/android/ReactAndroid/build.gradle:143)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.file.copy.FileCopier.createCopySpec(FileCopier.java:45)
        at org.gradle.api.internal.file.copy.FileCopier.copy(FileCopier.java:50)
        at org.gradle.api.internal.file.DefaultFileOperations.copy(DefaultFileOperations.java:157)
        at org.gradle.api.internal.project.DefaultProject.copy(DefaultProject.java:1040)
        at org.gradle.groovy.scripts.DefaultScript.copy(DefaultScript.java:206)
        at org.gradle.groovy.scripts.DefaultScript.copy(DefaultScript.java:201)
        at build_2djqh2xzm6mzczvqynvew2jal$_run_closure11.doCall(/Users/ide/sdks/android/ReactAndroid/build.gradle:142)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:718)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:691)
        at org.gradle.api.internal.tasks.TaskMutator$LeftShiftTaskAction.execute(TaskMutator.java:107)
        at org.gradle.api.internal.tasks.TaskMutator$LeftShiftTaskAction.execute(TaskMutator.java:96)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
```

**Comment by aniltirola** [comment]
I also checked out this branch:
Not exactly the same, but slightly similar errors I fixed with changing in file
`android/ReactAndroid/build.gradle` inside `task buildReactNdkLib` the line
`inputs.file('src/main/jni/react')`
to 
`inputs.files('src/main/jni/react')`

...but now I have the next problem:

```
make: Leaving directory `/Users/anil/my/code/expoClone/try31/android/ReactAndroid/src/main/jni/react/jni'

/Users/anil/Library/Android/sdk/ndk-bundle/build/core/add-application.mk:178: 

*** Android NDK: APP_STL gnustl_shared is no longer supported. Please switch to either c++_static or c++_shared. 

See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.

:ReactAndroid:buildReactNdkLib (Thread[Task worker for ':' Thread 5,5,main]) completed. Took 0.044 secs.

```

**Comment by sjchmiela** [comment]
My guess would be that changing
```diff
-     compile 'org.webkit:android-jsc:r174650'
+     api 'org.webkit:android-jsc:r174650'
```
in `android/ReactAndroid/build.gradle` in [`b3014cf`](https://github.com/expo/expo/commit/b3014cf708e3215e6dee41d0bfb71495954723a2#diff-4d432d65e62c0c8e8a3070d61bb22533R309) moved `android-jsc` dependency from `compile` configuration into the `api` configuration. In `prepareJSC` task we select exactly one file representing the `android-jsc` dependency:
https://github.com/expo/expo/blob/b3014cf708e3215e6dee41d0bfb71495954723a2/android/ReactAndroid/build.gradle#L143

So the error says that it could not find the file-dependency of `android-jsc` because `android-jsc` is now in the `api` configuration.

I had a go at changing `configurations.compile` to `configurations.api`, but that resulted in an error saying that `api` configuration is not directly resolvable now, see https://github.com/gradle/gradle/pull/1351.

To fix this error (and in fact move to another error) change `android-jsc` configuration back 🙂 :
```diff
-     api 'org.webkit:android-jsc:r174650'
+     compile 'org.webkit:android-jsc:r174650'
```

This is in fact on par with what React Native does — https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle#L307.

_After fixing this problem I got another error (running macOS Mojave fwiw) 😢 :_
```
make: Entering directory `/Users/sjchmiela/Applications/expo/android/ReactAndroid/src/main/jni/react/jni'
[armeabi-v7a] Compile++ thumb: reactnativejni <= AndroidJSCFactory.cpp
// ...
[armeabi-v7a] SharedLibrary  : libglog.so
[armeabi-v7a] SharedLibrary  : libyoga.so
[armeabi-v7a] Compile++ thumb: folly_json <= json.cpp
/Users/sjchmiela/Library/Android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:324: error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
/Users/sjchmiela/Library/Android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:324: error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
/Users/sjchmiela/Library/Android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_vector.h:898: error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
/Users/sjchmiela/Library/Android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_vector.h:898: error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
collect2: error: ld returned 1 exit status
make: *** [/Users/sjchmiela/Applications/expo/android/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/libyoga.so] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/Users/sjchmiela/Applications/expo/android/ReactAndroid/src/main/jni/react/jni'
```
