### ISSUE TITLE
eas update error after installing react-native-maps

### ISSUE THREAD

**Issue by hyochan** [expo/expo#23480]
### Minimal reproducible example

Installing react-native-maps and running eas updates.

### Summary

After installing `react-native-maps` and running eas update, it throws below error. I think this is related to https://github.com/react-native-maps/react-native-maps/issues/4641

```
[expo-cli] Starting Metro Bundler
[expo-cli] 
[expo-cli] 
[expo-cli] Error: Unable to resolve module ../Utilities/Platform from /Users/hyo/Github/dooboolab/dooboo-expo/node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js: 
[expo-cli] 
[expo-cli] None of these files exist:
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.cjs|.native.cjs|.cjs)
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.cjs|.native.cjs|.cjs)
[expo-cli]   22 | import typeof deepFreezeAndThrowOnMutationInDev from '../Utilities/deepFreezeAndThrowOnMutationInDev';
[expo-cli]   23 | import typeof deepDiffer from '../Utilities/differ/deepDiffer';
[expo-cli] > 24 | import typeof Platform from '../Utilities/Platform';
[expo-cli]      |                              ^
[expo-cli]   25 |
[expo-cli]   26 | import {type DangerouslyImpreciseStyleProp} from '../StyleSheet/StyleSheet';
[expo-cli]   27 |
[expo-cli] Error: Unable to resolve module ../Utilities/Platform from /Users/hyo/Github/dooboolab/dooboo-expo/node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js: 
[expo-cli] 
[expo-cli] None of these files exist:
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.cjs|.native.cjs|.cjs)
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.cjs|.native.cjs|.cjs)
[expo-cli]   22 | import typeof deepFreezeAndThrowOnMutationInDev from '../Utilities/deepFreezeAndThrowOnMutationInDev';
[expo-cli]   23 | import typeof deepDiffer from '../Utilities/differ/deepDiffer';
[expo-cli] > 24 | import typeof Platform from '../Utilities/Platform';
[expo-cli]      |                              ^
[expo-cli]   25 |
[expo-cli]   26 | import {type DangerouslyImpreciseStyleProp} from '../StyleSheet/StyleSheet';
[expo-cli]   27 |
[expo-cli]     at ModuleResolver.resolveDependency (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
[expo-cli]     at DependencyGraph.resolveDependency (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
[expo-cli]     at Object.resolve (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/lib/transformHelpers.js:169:21)
[expo-cli]     at Graph._resolveDependencies (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/DeltaBundler/Graph.js:472:35)
[expo-cli]     at Graph._processModule (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/DeltaBundler/Graph.js:260:38)
[expo-cli]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[expo-cli]     at async Graph._addDependency (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/DeltaBundler/Graph.js:371:20)
[expo-cli]     at async Promise.all (index 0)
[expo-cli]     at async Graph._processModule (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/DeltaBundler/Graph.js:321:5)
[expo-cli]     at async Graph._addDependency (/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/metro/src/DeltaBundler/Graph.js:371:20)
✖ Export failed
/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/expo/bin/cli exited with non-zero code: 1
```

### Environment

```
expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 13.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.6.1 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  npmPackages:
    @expo/webpack-config: ^18.1.0 => 18.1.1 
    expo: ^49.0.0 => 49.0.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.72.1 => 0.72.1 
    react-native-web: ~0.19.6 => 0.19.6 
  npmGlobalPackages:
    eas-cli: 3.15.1
  Expo Workflow: bare
```

**Comment by cirogithub1** [comment]
Same errors for me. It seems to be a single config json path but ain't realized where...

**Comment by brentvatne** [comment]
are you using metro for web in your app? if you aren't actually using web, you can remove that from your app config

**Comment by hyochan** [comment]
@brentvatne I am using web but I seperated branch with SDK 48 because of the issue in #23412 😔

**Comment by brentvatne** [comment]
you can disable metro web on your branch with sdk 49 to get past this bundling error

**Comment by hyochan** [comment]
Removing below in `app.config.ts` solved the problem 😃

```
  web: {
    bundler: 'metro',
  },
```

@brentvatne Feel free to close the issue if you think this should be considered as other problem.

**Comment by brentvatne** [comment]
i believe that ideally we shouldn't be bundling for web when running `eas update`, given that EAS Update does not in fact publish updates for web, so i'll close this when that is handled

**Comment by hyochan** [comment]
By the way, I also think it'd be great the tackle issue on bundling failure for expo-web users like me.

I also tried this https://github.com/react-native-web-community/react-native-web-maps but no luck 🥲

**Comment by cirogithub1** [comment]
thank U guys. It's working

**Comment by zoontek** [comment]
I'm closing this as this has been addressed  since: `eas update` lets you target platforms with `--platform` and doesn't publish web updates, so it no longer forces a web bundle.
