### ISSUE TITLE
Expo eas build failed

### ISSUE THREAD

**Issue by dalley8626** [expo/expo#23575]
### Summary

I am having issue with my eas build by running this command `expo prebuild && NODE_ENV=development eas build --profile development --platform ios --auto-submit`. I am using turborepo, but it seems like when i moved the repo out to an individual package, the build seems to be working fine

metro.config.js
```
const { getDefaultConfig } = require("expo/metro-config");

const path = require("path");

// Find the project and workspace directories
const projectRoot = __dirname;
// This can be replaced with `find-yarn-workspace-root`
const workspaceRoot = path.resolve(projectRoot, "../..");

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, {
  // [Web-only]: Enables CSS support in Metro.
  isCSSEnabled: true,
});

// 1. Watch all files within the monorepo
config.watchFolders = [workspaceRoot];
// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
];
// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true;

config.resolver.sourceExts.push("mjs");

module.exports = config;
```

Error
```
+ /Users/expo/.nvm/versions/node/v16.18.1/bin/node /Users/expo/workingdir/build/node_modules/@expo/cli/build/bin/cli export:embed --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/main.jsbundle --assets-dest /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/KlottiDEV.app --minify false
Using src/app as the root directory for Expo Router.
Experimental path aliases feature is enabled. Learn more: https://docs.expo.dev/guides/typescript/#path-aliases
warning: Bundler cache is empty, rebuilding (this may take a minute)
TypeError: isAssetFile is not a function
TypeError: isAssetFile is not a function
    at resolveFile (/Users/expo/workingdir/build/node_modules/metro-resolver/src/resolve.js:272:7)
    at resolveFileOrDir (/Users/expo/workingdir/build/node_modules/metro-resolver/src/resolve.js:198:22)
    at resolve (/Users/expo/workingdir/build/node_modules/metro-resolver/src/resolve.js:105:20)
    at doResolve (/Users/expo/workingdir/build/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:181:24)
    at /Users/expo/workingdir/build/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:217:48
    at resolveRequest (/Users/expo/workingdir/build/node_modules/@expo/cli/build/src/start/server/metro/withMetroResolvers.js:26:44)
    at Object.resolve (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-resolver/src/resolve.js:47:12)
    at ModuleResolver.resolveDependency (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Promise.all (index 0)
    at async Graph.initialTraverseDependencies (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:233:5)
    at async DeltaCalculator._getChangedDependencies (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:229:25)
    at async DeltaCalculator.getDelta (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:112:16)
    at async DeltaBundler.buildGraph (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler.js:54:5)
    at async IncrementalBundler.buildGraphForEntries (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/IncrementalBundler.js:66:19)
    at async IncrementalBundler.buildGraph (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/IncrementalBundler.js:146:19)
    at async Server.build (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:104:32)
    at async buildBundleWithConfig (/Users/expo/workingdir/build/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js:88:20)
    at async exportEmbedAsync (/Users/expo/workingdir/build/node_modules/@expo/cli/build/src/export/embed/exportEmbedAsync.js:20:5)
+ [[ '' == false ]]
+ EXTRA_COMPILER_ARGS=
+ [[ false == true ]]
+ EXTRA_COMPILER_ARGS=-O
+ [[ '' == true ]]
+ /Users/expo/workingdir/build/apps/klotti-app/ios/Pods/hermes-engine/destroot/bin/hermesc -emit-binary -max-diagnostic-width=80 -O -out /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/KlottiDEV.app/main.jsbundle /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/main.jsbundle
Error! Failed to open file: /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/main.jsbundle
+ [[ '' == true ]]
+ BUNDLE_FILE=/Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/KlottiDEV.app/main.jsbundle
+ [[ false != true ]]
+ [[ ! -f /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/KlottiDEV.app/main.jsbundle ]]
+ echo 'error: File /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/KlottiDEV.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues'
error: File /Users/expo/Library/Developer/Xcode/DerivedData/KlottiDEV-hfrssdwsihbmtibkxenusyagszbn/Build/Intermediates.noindex/ArchiveIntermediates/KlottiDEV/BuildProductsPath/Release-iphoneos/KlottiDEV.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```

### What platform(s) does this occur on?

iOS

### SDK Version

49

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.asdf/installs/nodejs/18.12.1/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.12.1/bin/yarn
      npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/senghuotlay/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.10
    Expo Workflow: bare

### Minimal reproducible example

Turborepo

**Comment by dalley8626** [comment]
All sorted, issue with node_modules

**Comment by dalley8626** [comment]
Seems to be an issue with yarn conflicting packages

**Comment by corasan** [comment]
> Seems to be an issue with yarn conflicting packages

What do you mean? How did you solve it?

**Comment by dalley8626** [comment]
Usually this issue with when multiple apps or package that difference versioning . And due to the nature of yarn v1, with everything hoisted up, the app that you're using now might not use the correct version of the package. 

```
i.e
app1
babel: 4.2

app2:
babel: 4.1
```

There are multiple solutions that i can think of:
1. switch to pnpm or yarn v3, because of how they configure your linking of your node_modules
2. use manypkg, this ensures that the package that you installed will always use the same versioning
3. For temporary fix, in my case i was re-writing my project, therefore, a simple delete of a package.json of my previous fixed it

**Comment by corasan** [comment]
@dalley8626 I am using manypkg, and yarn 3 with node_modules linking. My issue is with path aliases not being found during the build (android).

**Comment by dalley8626** [comment]
one more thing would probably be, extract your repo out to a single repo, and tries to build. see whether you'd still have the same issue
