### ISSUE TITLE
Unable to customize webpack in new expo app

### ISSUE THREAD

**Issue by K20shores** [expo/expo#23829]
### Summary

```
npx create-expo-app  myapp
cd my app
npx expo customize
```

choose webpack and press enter:

```
✔ Which files would you like to generate? › webpack.config.js
› Installing 1 other package using npm
> npm install --save --dev @expo/webpack-config
npm WARN config dev Please use --include=dev instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@1.0.0
npm ERR! Found: expo@49.0.6
npm ERR! node_modules/expo
npm ERR!   expo@"~49.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer expo@"^48.0.17" from @expo/webpack-config@18.1.2
npm ERR! node_modules/@expo/webpack-config
npm ERR!   @expo/webpack-config@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/kyle/.npm/_logs/2023-08-05T14_01_35_748Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/kyle/.npm/_logs/2023-08-05T14_01_35_748Z-debug-0.log
Error: npm exited with non-zero code: 1
Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/kyle/Downloads/myapp/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:626:26)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (/Users/kyle/Downloads/myapp/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at NpmPackageManager.runAsync (/Users/kyle/Downloads/myapp/node_modules/@expo/package-manager/build/node/BasePackageManager.js:38:42)
    at /Users/kyle/Downloads/myapp/node_modules/@expo/package-manager/build/node/NpmPackageManager.js:39:20
    at /Users/kyle/Downloads/myapp/node_modules/@expo/package-manager/build/utils/spawn.js:19:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### What platform(s) does this occur on?

Web

### SDK Version

49.0.5

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.0 - /usr/local/bin/node
      npm: 9.8.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    Expo Workflow: managed
```

### Minimal reproducible example

See summary above

**Comment by K20shores** [comment]
Related https://github.com/expo/expo-cli/issues/4729

**Comment by K20shores** [comment]
Why do I need webpack? I'm trying to render one component for web and another for mobile devices. When I try that I get an error `Module not found: Can't resolve '../../Utilities/Platform'`, like in https://github.com/expo/expo/issues/16513. That can apparently be resolved with an [alias in webpack](https://stackoverflow.com/a/72225795/5217293). Though it appears the recommended solution is to [use the metro bundler](https://github.com/expo/expo-cli/issues/4729#issuecomment-1652302622). But the metro bundler can't handle the relative import

**Comment by biplobsd** [comment]
Is there any update?

**Comment by K20shores** [comment]
> Is there any update?

Sorta. In app.json, under the web section, you can add "bundler": "metro" and customize the metro.config.js file to enable css imports.

**Comment by xugy0926** [comment]
> Why do I need webpack? I'm trying to render one component for web and another for mobile devices. When I try that I get an error `Module not found: Can't resolve '../../Utilities/Platform'`, like in #16513. That can apparently be resolved with an [alias in webpack](https://stackoverflow.com/a/72225795/5217293). Though it appears the recommended solution is to [use the metro bundler](https://github.com/expo/expo-cli/issues/4729#issuecomment-1652302622). But the metro bundler can't handle the relative import


I have a similar issue when using Metro. I don't know how to replace the alias config in Metro's config.

```js
const createExpoWebpackConfigAsync = require("@expo/webpack-config");
const path = require("path");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  // How to config in metro??
  config.resolve.alias["lottie-react-native"] = "react-native-web-lottie";

  return config;
};
```
