### ISSUE TITLE
FetchError: request to https://api.expo.dev/graphql failed, reason: connect ETIMEDOUT 104.18.4.104:443

### ISSUE THREAD

**Issue by miki07** [expo/expo#23921]
### Summary

This error is being thrown during Jenkins job that is running behind the corporate proxy:
```
CombinedError: [Network] request to https://api.expo.dev/graphql failed, reason: connect ETIMEDOUT 104.18.5.104:443
    at makeErrorResult (/usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/urql-core-chunk.js:495:10)
    at fetchOperation (/usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/urql-core-chunk.js:756:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/lib/node_modules/eas-cli/node_modules/wonka/dist/wonka.js:346:20 {
  graphQLErrors: [],
  networkError: FetchError: request to https://api.expo.dev/graphql failed, reason: connect ETIMEDOUT 104.18.5.104:443
      at ClientRequest.<anonymous> (/usr/local/lib/node_modules/eas-cli/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (node:events:513:28)
      at TLSSocket.socketErrorListener (node:_http_client:494:9)
      at TLSSocket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT'
  },
  response: undefined
}
```

To test connectivity we tried:

```
curl --verbose -I https://api.expo.dev

Uses proxy env variable HTTPS_PROXY == 'http://proxy:3128'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying *****...
* Connected to proxy***** (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to api.expo.dev:443
> CONNECT api.expo.dev:443 HTTP/1.1
> Host: api.expo.dev:443
> User-Agent: curl/7.74.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* CONNECT phase completed!
* CONNECT phase completed!
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2327 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [80 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Oct 16 00:00:00 2022 GMT
*  expire date: Oct 16 23:59:59 2023 GMT
*  subjectAltName: host "api.expo.dev" matched cert's "*.expo.dev"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x5568c4bff2c0)
} [5 bytes data]
> HEAD /v2/versions/latest HTTP/2
> Host: api.expo.dev
> user-agent: curl/7.74.0
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [238 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [238 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
} [5 bytes data]
< HTTP/2 200 
< date: Wed, 09 Aug 2023 03:54:44 GMT
< content-type: application/json; charset=utf-8
< content-length: 28138
< vary: Accept-Encoding, Origin
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< etag: "6dea-OPQLK4q2jhdTT92mxTzIkMCBmGo"
< via: 1.1 google
< strict-transport-security: max-age=31536000; includeSubDomains
< alt-svc: h3=":443"; ma=86400
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 7f3d0f3d9f3fa93e-SYD
< 

  0 28138    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host proxy****** left intact
HTTP/1.1 200 Connection established

HTTP/2 200 
date: Wed, 09 Aug 2023 03:54:44 GMT
content-type: application/json; charset=utf-8
content-length: 28138
vary: Accept-Encoding, Origin
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
etag: "6dea-OPQLK4q2jhdTT92mxTzIkMCBmGo"
via: 1.1 google
strict-transport-security: max-age=31536000; includeSubDomains
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 7f3d0f3d9f3fa93e-SYD

```

### SDK Version

48

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.14 Alpine Linux
      Shell: 1.36.1 - /bin/ash
    Binaries:
      Node: 16.20.1 - /usr/local/bin/node
      npm: 8.19.4 - /usr/local/bin/npm
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

npx --yes --package eas-cli@latest eas build --branch master --message 'testing' --non-interactive

**Comment by Kudo** [comment]
hi there! for eas-cli, the environment variable to set is `https_proxy` (lowercases). please try `https_proxy=https://proxy:3128 npx --yes --package eas-cli@latest eas build --branch master --message 'testing' --non-interactive`. thanks!

**Comment by miki07** [comment]
hi @Kudo we have all env vars set up, HTTP_PROXY, HTTPS_PROXY, http_proxy and https_proxy, the curl from above logs is using HTTPS_PROXY

**Comment by Kudo** [comment]
interesting! please try to add more debug log: e.g. `DEBUG='*' npx --yes --package eas-cli@latest eas build --branch master --message 'testing' --non-interactive`

**Comment by miki07** [comment]
```
eas-cli/4.1.2 linux-x64 node-v16.20.1
+ eas build --branch master --message testing eas update --non-interactive
2023-08-15T05:57:13.461Z config reading core plugin /usr/local/lib/node_modules/eas-cli
2023-08-15T05:57:13.463Z config loadJSON /usr/local/lib/node_modules/eas-cli/package.json
2023-08-15T05:57:13.465Z config loadJSON /usr/local/lib/node_modules/eas-cli/oclif.manifest.json
2023-08-15T05:57:13.467Z config:eas-cli using manifest from /usr/local/lib/node_modules/eas-cli/oclif.manifest.json
2023-08-15T05:57:13.479Z config reading user plugins pjson /root/.local/share/eas-cli/package.json
2023-08-15T05:57:13.479Z config loadJSON /root/.local/share/eas-cli/package.json
2023-08-15T05:57:13.479Z config loading plugins [
  '@oclif/plugin-autocomplete',
  '@expo/plugin-help',
  '@expo/plugin-warn-if-update-available'
]
2023-08-15T05:57:13.483Z config reading core plugin /usr/local/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete
2023-08-15T05:57:13.483Z config loadJSON /usr/local/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/package.json
2023-08-15T05:57:13.483Z config reading core plugin /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-help
2023-08-15T05:57:13.483Z config loadJSON /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-help/package.json
2023-08-15T05:57:13.483Z config reading core plugin /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available
2023-08-15T05:57:13.483Z config loadJSON /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/package.json
2023-08-15T05:57:13.484Z config loadJSON /usr/local/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json
2023-08-15T05:57:13.484Z config loadJSON /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-help/oclif.manifest.json
2023-08-15T05:57:13.485Z config loadJSON /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json
2023-08-15T05:57:13.485Z config:@oclif/plugin-autocomplete using manifest from /usr/local/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json
2023-08-15T05:57:13.486Z config:@expo/plugin-help using manifest from /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-help/oclif.manifest.json
2023-08-15T05:57:13.486Z config:@expo/plugin-warn-if-update-available using manifest from /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json
2023-08-15T05:57:13.490Z config config done
2023-08-15T05:57:13.490Z config start init hook
2023-08-15T05:57:13.508Z eas:@expo/plugin-warn-if-update-available:hooks:init start (require) /usr/local/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/lib/hooks/init/check-update.js
2023-08-15T05:57:13.510Z eas:@expo/plugin-warn-if-update-available:hooks:init done
2023-08-15T05:57:13.511Z config init hook done
2023-08-15T05:57:13.511Z config runCommand build [ '--branch', 'master', '--message', 'testing eas update', '--non-interactive' ]
2023-08-15T05:57:14.817Z config:eas-cli (require) /usr/local/lib/node_modules/eas-cli/build/commands/build/index.js
2023-08-15T05:57:14.817Z config start prerun hook
2023-08-15T05:57:14.817Z config prerun hook done
2023-08-15T05:57:14.818Z eas:build init version: @oclif/core@1.23.2 argv: [ '--branch', 'master', '--message', 'testing eas update', '--non-interactive' ]
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
    at getAllowUnauthorized (node:internal/options:58:13)
    at Object.connect (node:_tls_wrap:1610:29)
    at Agent.createConnection (node:https:147:22)
    at Agent.createSocket (node:_http_agent:347:26)
    at Agent.addRequest (node:_http_agent:294:10)
    at new ClientRequest (node:_http_client:335:16)
    at request (node:https:357:10)
    at /usr/local/lib/node_modules/eas-cli/node_modules/node-fetch/lib/index.js:1468:15
    at new Promise (<anonymous>)
    at fetch (/usr/local/lib/node_modules/eas-cli/node_modules/node-fetch/lib/index.js:1437:9)
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
    at getAllowUnauthorized (node:internal/options:58:13)
    at Object.connect (node:_tls_wrap:1610:29)
    at Agent.createConnection (node:https:147:22)
    at Agent.createSocket (node:_http_agent:347:26)
    at Agent.addRequest (node:_http_agent:294:10)
    at new ClientRequest (node:_http_client:335:16)
    at request (node:https:357:10)
    at /usr/local/lib/node_modules/eas-cli/node_modules/node-fetch/lib/index.js:1468:15
    at new Promise (<anonymous>)
    at fetch (/usr/local/lib/node_modules/eas-cli/node_modules/node-fetch/lib/index.js:1437:9)
CombinedError: [Network] request to https://api.expo.dev/graphql failed, reason: connect ETIMEDOUT 104.18.4.104:443
    at makeErrorResult (/usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/urql-core-chunk.js:495:10)
    at fetchOperation (/usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/urql-core-chunk.js:756:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/lib/node_modules/eas-cli/node_modules/wonka/dist/wonka.js:346:20 {
  graphQLErrors: [],
  networkError: FetchError: request to https://api.expo.dev/graphql failed, reason: connect ETIMEDOUT 104.18.4.104:443
      at ClientRequest.<anonymous> (/usr/local/lib/node_modules/eas-cli/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (node:events:513:28)
      at TLSSocket.socketErrorListener (node:_http_client:494:9)
      at TLSSocket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT'
  },
  response: undefined
}
```

**Comment by miki07** [comment]
i also tried:

```
curl --verbose -X POST https://api.expo.dev/graphql
* Uses proxy env variable HTTPS_PROXY == 'http://proxy.awshosting.rms.nsw.gov.au:3128'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.219.229.68:3128...
* Connected to proxy.awshosting.rms.nsw.gov.au (10.219.229.68) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to api.expo.dev:443
> CONNECT api.expo.dev:443 HTTP/1.1
> Host: api.expo.dev:443
> User-Agent: curl/7.74.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* CONNECT phase completed!
* CONNECT phase completed!
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2327 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Oct 16 00:00:00 2022 GMT
*  expire date: Oct 16 23:59:59 2023 GMT
*  subjectAltName: host "api.expo.dev" matched cert's "*.expo.dev"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x55991a8c02c0)
} [5 bytes data]
> POST /graphql HTTP/2
> Host: api.expo.dev
> user-agent: curl/7.74.0
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [238 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [238 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
} [5 bytes data]
< HTTP/2 411 
< date: Tue, 15 Aug 2023 05:54:36 GMT
< content-type: text/html; charset=UTF-8
< content-length: 286
< referrer-policy: no-referrer
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 7f6f2f127d00a8d1-SYD
< alt-svc: h3=":443"; ma=86400
< 
{ [5 bytes data]

100   286  100   286    0     0   1692      0 --:--:-- --:--:-- --:--:--  1692
* Connection #0 to host proxy.awshosting.rms.nsw.gov.au left intact

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>411 Length Required</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Length Required</h1>
<h2>POST requests require a <code>Content-length</code> header.</h2>
<h2></h2>
</body></html>
```

**Comment by Kudo** [comment]
if you setup `https_proxy` environment variable correctly, you should see the `https-proxy-agent:agent` from the `DEBUG='*'` log.

e.g.

```
  https-proxy-agent:agent creating new HttpsProxyAgent instance: { host: 'localhost', port: '3128', protocol: 'https:', path: '/', auth: null, ca: null, cert: null, key: null, timeout: 300001, localAddress: null, maxSockets: 15, rejectUnauthorized: true } +0ms
  agent-base Resolving socket for 'https:' request: 'GET /eas-cli' +0ms
  https-proxy-agent:agent Creating `tls.Socket`: { host: 'localhost', port: 8088, protocol: 'https:', auth: null, ca: null, cert: null, key: null, timeout: 300001, localAddress: null, maxSockets: 15, rejectUnauthorized: true, ALPNProtocols: [ 'http 1.1' ] } +4ms
```

**Comment by miki07** [comment]
hi @Kudo, when npm install is executed ww can see https-proxy-agent:agent, but not when running eas command

![image](https://github.com/expo/expo/assets/28002703/56efcf70-e8c3-477c-8a4d-a82c97b429c2)

**Comment by Kudo** [comment]
could you try to run it locally first? for example, `https_proxy='https://localhost:1' DEBUG='*' eas build --branch master --message 'testing' --non-interactive`
the `https://localhost:1` is a non-existed proxy server and this is my output

```
  config reading core plugin /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/package.json +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/oclif.manifest.json +0ms
  config:eas-cli using manifest from /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/oclif.manifest.json +0ms
  config reading user plugins pjson /Users/kudo/.local/share/eas-cli/package.json +0ms
  config loadJSON /Users/kudo/.local/share/eas-cli/package.json +0ms
  config loading plugins [
  '@oclif/plugin-autocomplete',
  '@expo/plugin-help',
  '@expo/plugin-warn-if-update-available'
] +1ms
  config reading core plugin /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/package.json +0ms
  config reading core plugin /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-help +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-help/package.json +0ms
  config reading core plugin /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/package.json +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-help/oclif.manifest.json +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  config loadJSON /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config:@expo/plugin-help using manifest from /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-help/oclif.manifest.json +0ms
  config:@oclif/plugin-autocomplete using manifest from /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  config:@expo/plugin-warn-if-update-available using manifest from /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config config done +3ms
  config start init hook +0ms
  eas:@expo/plugin-warn-if-update-available:hooks:init start (require) /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/lib/hooks/init/check-update.js +0ms
  eas:@expo/plugin-warn-if-update-available:hooks:init done +1ms
  config init hook done +9ms
  config runCommand build [ '--branch', 'master', '--message', 'testing', '--non-interactive' ] +0ms
  https-proxy-agent:agent creating new HttpsProxyAgent instance: Url { protocol: 'https:', slashes: true, auth: null, host: 'localhost:1', port: '1', hostname: 'localhost', hash: null, search: null, query: null, pathname: '/', path: '/', href: 'https://localhost:1/' } +0ms
  https-proxy-agent:agent creating new HttpsProxyAgent instance: Url { protocol: 'https:', slashes: true, auth: null, host: 'localhost:1', port: '1', hostname: 'localhost', hash: null, search: null, query: null, pathname: '/', path: '/', href: 'https://localhost:1/' } +0ms
  config:eas-cli (require) /Users/kudo/.volta/tools/image/packages/eas-cli/lib/node_modules/eas-cli/build/commands/build/index.js +396ms
  config start prerun hook +376ms
  config prerun hook done +0ms
  eas:build init version: @oclif/core@1.23.2 argv: [ '--branch', 'master', '--message', 'testing', '--non-interactive' ] +0ms
  agent-base Resolving socket for 'https:' request: 'POST /graphql' +0ms
  https-proxy-agent:agent Creating `tls.Socket`: { protocol: 'https:', slashes: true, auth: null, host: 'localhost', port: 1, hostname: 'localhost', hash: null, search: null, query: null, href: 'https://localhost:1/', ALPNProtocols: [ 'http 1.1' ] } +220ms
  https-proxy-agent:parse-proxy-response onerror Error: connect ECONNREFUSED ::1:1     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '::1', port: 1 } +0ms
```

**Comment by miki07** [comment]
Thanks for you quick reply. I did try locally and from what I remember we had similar logs. I'll post it tomorrow.

**Comment by miki07** [comment]
@Kudo ive realised that ive posted the wrong command. It's eas update we were trying not eas build. But everything else stays the same. Nothing is different in relation to the issue as even when you try with the eas build with those wrong flags its still the same error. During some meeting we were trying few things and by mistake left the build instead of update. So sorry about that

**Comment by Kudo** [comment]
in this case, please try `https_proxy='https://localhost:1' DEBUG='*' eas update...` and check the if there's any log for `https-proxy-agent`.
