### ISSUE TITLE
[docs] troubleshoot setting up starter expo app with new native module

### ISSUE THREAD

**Issue by chancesmith** [expo/expo#23950]
### Summary

Having trouble with setting up a new module with a new expo app. Simulator shows an error of "Unable to resolve module ./.expo/.virtual-metro-entry"

## steps to recreate
1. create a mono repo (yarn workspace) with directories of `packages/` and `apps/`
2. add new package to `packages/` following the [standalone-expo-modules guide](https://docs.expo.dev/modules/use-standalone-expo-module-in-your-project/) by running `npx create-expo-module packages/expo-settings --no-example`.
3. follow the guide from here...
3. create a new expo app in `apps/` with `npx create-expo-app -t expo-template-blank-typescript`
4. then [add autolinking to package.json](https://docs.expo.dev/modules/use-standalone-expo-module-in-your-project/#2-set-up-workspace)
5. [run build on package](https://docs.expo.dev/modules/use-standalone-expo-module-in-your-project/#3-run-the-module)
6. [run prebuild on expo app](https://docs.expo.dev/modules/use-standalone-expo-module-in-your-project/#3-run-the-module)
7. `npx expo run:ios`

The result we get from expo is:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module ./.expo/.virtual-metro-entry from /Users/USER_NAME/wip/expo-mono-repo/frontend/apps/mobile-test-player/.: <br><br>None of these files exist:<br> &nbsp;* .expo/.virtual-metro-entry(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)<br> &nbsp;* .expo/.virtual-metro-entry/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (/Users/USER_NAME/wip/expo-mono-repo/frontend/apps/mobile-test-player/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (/Users/USER_NAME/wip/expo-mono-repo/frontend/apps/mobile-test-player/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)<br> &nbsp; &nbsp;at /Users/USER_NAME/wip/expo-mono-repo/frontend/apps/mobile-test-player/node_modules/metro/src/lib/transformHelpers.js:169:21<br> &nbsp; &nbsp;at Server._resolveRelativePath (/Users/USER_NAME/wip/expo-mono-repo/frontend/apps/mobile-test-player/node_modules/metro/src/Server.js:1045:12)<br> &nbsp; &nbsp;at async Server.requestProcessor [as _processBundleRequest] (/Users/USER_NAME/wip/expo-mono-repo/frontend/apps/mobile-test-player/node_modules/metro/src/Server.js:449:37)<br> &nbsp; &nbsp;at async Server._processRequest (/Users/USER_NAME/wip/expo-mono-repo/frontend/apps/mobile-test-player/node_modules/metro/src/Server.js:383:7)</pre>
</body>
</html>


RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

### Link to the related docs page

https://docs.expo.dev/modules/use-standalone-expo-module-in-your-project/

**Comment by chancesmith** [comment]
The issue was I didn't configure the new expo app to be mono-repo ready:
https://docs.expo.dev/guides/monorepos/

Go see the guide above, but here are the steps to solve this:
1. [add metro.config.js](https://docs.expo.dev/guides/monorepos/)
2. [update entrypoint in package.json](https://docs.expo.dev/guides/monorepos/) in expo app
