### ISSUE TITLE
`metro@0.76.7` does not tell you what module import failed

### ISSUE THREAD

**Issue by awilson9** [expo/expo#23971]
### Minimal reproducible example

https://github.com/awilson9/shady-pines-radio-mobile/pull/2

### Summary

Exact repro is on this branch https://github.com/awilson9/shady-pines-radio-mobile/pull/2

`realModuleName` is not a part of the error message on `"metro": "^0.76.7"`

Repro steps: 

1. check out linked branch
2. Run `pnpm install`
3. Run `pnpm web`
4. Observe error:
```
  error: Error: Module does not exist in the Haste module map or in these directories:
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/lib/module/views/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/lib/module/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/lib/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules
  /Users/aaronwilson/code/node_modules
  /Users/aaronwilson/node_modules
  /Users/node_modules
  /node_modules

    at resolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro-resolver/src/resolve.js:147:9)
    at doResolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:181:24)
    at /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:217:48
    at resolveRequest (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@expo/cli/build/src/start/server/metro/withMetroResolvers.js:30:44)
    at Object.resolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/node_modules/metro-resolver/src/resolve.js:47:12)
    at ModuleResolver.resolveDependency (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
  Web Bundling failed 5161ms
  error: Error: Module does not exist in the Haste module map or in these directories:
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/lib/commonjs/views/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/lib/commonjs/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/lib/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/drawer/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@react-navigation/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/node_modules
  /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules
  /Users/aaronwilson/code/node_modules
  /Users/aaronwilson/node_modules
  /Users/node_modules
  /node_modules

    at resolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro-resolver/src/resolve.js:147:9)
    at doResolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:181:24)
    at /Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js:217:48
    at resolveRequest (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/@expo/cli/build/src/start/server/metro/withMetroResolvers.js:30:44)
    at Object.resolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/node_modules/metro-resolver/src/resolve.js:47:12)
    at ModuleResolver.resolveDependency (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/aaronwilson/code/shady-pines-radio-mobile/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
  ```
5. using VSCode debug terminal, set breakpoint in `node_modules/metro-resolver/src/resolve.js:147` at code point `throw new _FailedToResolveNameError.default(nodeModulesPaths, extraPaths);`
6.  Observe breakpoint executor `VARIABLES.moduleName` is equal to `react-native-reanimated`
7. Resume execution
8. Observe error message has no mention of missing dependency
9. Run `pnpm install react-native-reanimated`
10. Run `pnpm web`
11. Observe no error

Expected results: module import error includes the module that was not installed
Actual results: no module name is included in error

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.7 => 49.0.7 
      metro: ^0.76.7 => 0.76.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    Expo Workflow: managed
```

**Comment by bentburton** [comment]
Facing this issue also

**Comment by bentburton** [comment]
I was able to get a better error message after running "yarn upgrade"
Before:
<similar to yours>

After:
The package at "node_modules/mime-types/index.js" attempted to import the Node standard library module "path".
It failed because the native React runtime does not include the Node standard library.
