### ISSUE TITLE
`NullPointerException`s when calling `Updates.reloadAsync` with SDK49 in production builds

### ISSUE THREAD

**Issue by jludwiggreenaction** [expo/expo#24159]
EDIT: Please see linked comment for repro steps. The cause seems to be from calling `reloadAsync` from `expo-updates`.

### Minimal reproducible example

https://github.com/patidarsarvesh/ExpoNullPointerIssue

### The problem
We are noticing our app crashing on android with `NullPointerException` occasionally in production. It is affecting <1% of users, but it's still consistently happening 1-2 times a day.

Judging from our logs, all crashes seem to be caused by `NullPointerException` with expo packages. We have seen them so far occur in `expo-notifications` and `expo-location`. Here are the stack traces we have:
#### expo-location
```
java.lang.NullPointerException: java.lang.NullPointerException
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt)
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt:24)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke(Promise.kt:22)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke(Promise.kt:22)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$1.resolve(Promise.kt:29)
    at expo.modules.adapters.react.PromiseWrapper.resolve(PromiseWrapper.java:27)
    at expo.modules.location.LocationHelpers$1.onLocationChanged(LocationHelpers.java:157)
    at expo.modules.location.LocationModule$1.onLocationResult(LocationModule.java:557)
    at com.google.android.gms.internal.location.zzaw.notifyListener(com.google.android.gms:play-services-location@@20.0.0:2)
    at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.1.0:2)
    at com.google.android.gms.common.api.internal.zacb.run
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
```

#### expo-notifications
```
java.lang.NullPointerException: java.lang.NullPointerException
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt)
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt:24)
    at expo.modules.kotlin.jni.PromiseImpl.reject(PromiseImpl.kt:87)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$1.reject(Promise.kt:41)
    at expo.modules.adapters.react.PromiseWrapper.reject(PromiseWrapper.java:36)
    at expo.modules.notifications.notifications.presentation.ExpoNotificationPresentationModule$4.onReceiveResult(ExpoNotificationPresentationModule.java:98)
    at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:59)
    at android.os.ResultReceiver.send(ResultReceiver.java:93)
    at expo.modules.notifications.service.NotificationsService.handleIntent(NotificationsService.kt:650)
    at expo.modules.notifications.service.NotificationsService$onReceive$1.invoke(NotificationsService.kt:588)
    at expo.modules.notifications.service.NotificationsService$onReceive$1.invoke(NotificationsService.kt:586)
    at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```
```
java.lang.NullPointerException: java.lang.NullPointerException
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt)
    at expo.modules.kotlin.jni.JavaCallback.invoke(JavaCallback.kt:24)
    at expo.modules.kotlin.jni.PromiseImpl.reject(PromiseImpl.kt:87)
    at expo.modules.kotlin.PromiseKt$toBridgePromise$1.reject(Promise.kt:41)
    at expo.modules.adapters.react.PromiseWrapper.reject(PromiseWrapper.java:36)
    at expo.modules.notifications.tokens.PushTokenModule$1.onComplete(PushTokenModule.java:72)
    at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8855)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### other details
- In production, sentry breadcrumbs suggest the expo-notifications crashes happen on app launch (when we setup the notification handler) and when we fetch the expo push token.
- Logs also suggest that the expo-locations crash happens while we fetch location data from the device
- Crashes so far seen on google and samsung devices, and across many different OS versions (10, 11, 13)
- These crashes somewhat resemble #23382 and #17426, but nothing really matches up with what we're seeing here

### repro
~~We are having problems consistently reproducing the problem, but [here](https://github.com/patidarsarvesh/ExpoNullPointerIssue) is a repo with what we think are the minimum requirements to trigger the crash.~~

~~We have tried everything we can think of to try to reproduce it consistently, such as accepting/rejecting permissions, fetching location data frequently, triggering the push notification handler, fetching the push token frequently, and testing from cold start and on entering foreground.~~
see https://github.com/expo/expo/issues/24159#issuecomment-1701761218

~~If you have any tips on debugging native crashes like this we would be happy to apply them and followup. Both in the reproduction repo and in our production app we don't write any native code ourselves. We have thought about downgrading to expo 48 to see if that fixes the problem but we didn't want to go through all that effort yet without knowing the root cause.~~

### Environment

- We use eas-build to build our app for ios & android, but the following is one of our local dev machines

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.asdf/installs/nodejs/16.19.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.19.0/bin/yarn
      npm: 8.19.3 - ~/git_repos/<project_name>/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7
      expo: ^49.0.6 => 49.0.6
      react: 18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by jludwiggreenaction** [comment]
I did not see #24154, that seems like it could be related to our notifications crashes.

**Comment by leymytel** [comment]
I am experiencing the same issue. Here's some of the stack traces:

```
Exception java.lang.NullPointerException: java.lang.NullPointerException
  at expo.modules.kotlin.jni.JavaCallback.invoke
  at expo.modules.kotlin.jni.JavaCallback.invoke (JavaCallback.kt:24)
  at expo.modules.kotlin.jni.PromiseImpl.reject (PromiseImpl.kt:87)
  at expo.modules.kotlin.Promise$DefaultImpls.reject (Promise.kt:15)
  at expo.modules.kotlin.jni.PromiseImpl.reject (PromiseImpl.kt:26)
  at expo.modules.kotlin.functions.AsyncFunction$attachToJSObject$2$functionBody$1.invoke (AsyncFunction.kt:74)
  at expo.modules.kotlin.functions.AsyncFunction$attachToJSObject$2$functionBody$1.invoke (AsyncFunction.kt:66)
  at expo.modules.kotlin.functions.AsyncFunction$attachToJSObject$2$3.invokeSuspend (AsyncFunction.kt:104)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.os.HandlerThread.run (HandlerThread.java:67)
```

Expo updates:

```
Exception java.lang.NullPointerException: java.lang.NullPointerException
  at expo.modules.kotlin.jni.JavaCallback.invoke
  at expo.modules.kotlin.jni.JavaCallback.invoke (JavaCallback.kt:24)
  at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke (Promise.kt:22)
  at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke (Promise.kt:22)
  at expo.modules.kotlin.PromiseKt$toBridgePromise$1.resolve (Promise.kt:29)
  at expo.modules.adapters.react.PromiseWrapper.resolve (PromiseWrapper.java:27)
  at expo.modules.updates.UpdatesModule$checkForUpdateAsync$1$1.onSuccess (UpdatesModule.kt:188)
  at expo.modules.updates.loader.FileDownloader.parseRemoteUpdateResponse$expo_updates_release (FileDownloader.kt:116)
  at expo.modules.updates.loader.FileDownloader$downloadRemoteUpdate$1.onResponse (FileDownloader.kt:548)
  at expo.modules.updates.loader.FileDownloader$downloadData$1.onResponse (FileDownloader.kt:622)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:519)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)
```

Expo Location

```
Exception java.lang.NullPointerException: java.lang.NullPointerException
  at expo.modules.kotlin.jni.JavaCallback.invoke
  at expo.modules.kotlin.jni.JavaCallback.invoke (JavaCallback.kt:24)
  at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke (Promise.kt:22)
  at expo.modules.kotlin.PromiseKt$toBridgePromise$resolveMethod$1.invoke (Promise.kt:22)
  at expo.modules.kotlin.PromiseKt$toBridgePromise$1.resolve (Promise.kt:29)
  at expo.modules.adapters.react.PromiseWrapper.resolve (PromiseWrapper.java:27)
  at expo.modules.location.LocationHelpers$1.onLocationChanged (LocationHelpers.java:157)
  at expo.modules.location.LocationModule$1.onLocationResult (LocationModule.java:557)
  at com.google.android.gms.internal.location.zzaw.notifyListener (com.google.android.gms:play-services-location@@20.0.0:2)
  at com.google.android.gms.common.api.internal.ListenerHolder.zaa (com.google.android.gms:play-services-base@@18.1.0:2)
  at com.google.android.gms.common.api.internal.zacb.run
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.os.HandlerThread.run (HandlerThread.java:67)
```

**Comment by jludwiggreenaction** [comment]
@leymytel Do you use `expo-updates` or ever call `reloadAsync()`? One suspicion I had was that updating the app bundle could be crashing the app if one of the native modules is doing something while the restart occurs.

**Comment by leymytel** [comment]
Hi @jludwiggreenaction! We use reloadAsync and reanimated. Do you use reanimated? It's a known issue. 
One way to reproduce it is to use the "Reload" button from the dev menu. It used to crash for me when I had something rendered from reanimated.

**Comment by jludwiggreenaction** [comment]
I have updated my reproducible example link. I am able to see the app consistently crashing on both IOS and android. Steps are simply:
- run the app in non-dev mode
- send the app to background
- send the app to foreground
- witness crash

**Comment by SohelIslamImran** [comment]
I'm facing the same issue on Android at first app startup...

<img width="741" alt="image" src="https://github.com/expo/expo/assets/76745339/3f073faa-f1e6-4d6a-a933-bf74759c1850">
<img width="461" alt="image" src="https://github.com/expo/expo/assets/76745339/5d4f40d8-00c9-478c-b9bd-f00076030df4">

**Comment by douglowder** [comment]
I'll take a look.

**Comment by douglowder** [comment]
> I have updated my reproducible example link. I am able to see the app consistently crashing on both IOS and android. Steps are simply:
> run the app in non-dev mode
> send the app to background
> send the app to foreground
> witness crash

@jludwiggreenaction I tried the example repo you provided, set up updates with `eas init` and `eas update:configure`, and built and ran the app in release mode on both emulator and device. I don't see any crashes.

**Comment by SohelIslamImran** [comment]
In my case, calling `crashlytics().setAttributes({ ... });` with invalid data caused the error.. Removing that solved my issue
![image](https://github.com/expo/expo/assets/76745339/fff52940-8956-4a41-ba79-4eca739c30d7)
This only accepts `string`.

But it should throw meaningful error messages

**Comment by sperrys** [comment]
This oddly tracks with something we've been seeing since upgrading to 49. A bunch of NPEs randomly showing up and crashing users. It's been in expo-contacts, but a similiar stack trace.

**Comment by jludwiggreenaction** [comment]
I want to reiterate that although we only see logs of this occurring on android with `NullPointException`s in sentry, I was able to crash IOS as with the same steps, but sentry is unable to log anything.

**Comment by jludwiggreenaction** [comment]
Is it possible to include [037566e](https://github.com/expo/expo/commit/037566ee6439d3b86571dec5e5efd641d476131b) with the v49 sdk? It's been merged to main for a month but we're still dealing with this on v49.

**Comment by DAVIS-PYTH** [comment]
@jludwiggreenaction I am experiencing this issue in production and the crash rate has significantly risen. I believe calling Updates.reloadAsync is the cause, The App crashes whenever we push out an update. How have you been able to manage this issue so far?

**Comment by jludwiggreenaction** [comment]
> @jludwiggreenaction I am experiencing this issue in production and the crash rate has significantly risen. I believe calling Updates.reloadAsync is the cause, The App crashes whenever we push out an update. How have you been able to manage this issue so far?

We don't have a solution yet. Most we could do is try to call `refreshAsync` less often.

@lukmccall I apologize for the ping on a closed issue, but do you know if there's a chance this fix can be backported to sdk 49?

**Comment by leymytel** [comment]
I ran into a similar issue and found a workaround that may help you. Before calling `reloadAsync`, try the following steps:
1. Unmount the entire React tree
2. Stop any background services or tasks (e.g., location tracking)

We are still getting some exceptions but not that often.

**Comment by rafavalerio** [comment]
Any updates on this?

I just migrated to SDK49, and all works well locally with dev builds, but as soon as I create a build for our UAT environment (prod like), it just crashes on open. Seems related to `expo-updates` and `react-native-reanimated`

Sentry does not catch anything, and the crash log is not exactly helpful.

**Comment by jludwiggreenaction** [comment]
@rafavalerio The fix is included in SDK 50, but after requesting it for months I don't see this fix ever being backported to SDK 49 unfortunately.

**Comment by rafavalerio** [comment]
@jludwiggreenaction Very unfortunate! Network debugging would be very helpful, so I guess will have to wait until SDK50 drops! Thanks for the reply!
