### ISSUE TITLE
Camera java.lang.IllegalArgumentException: Invalid image data size

### ISSUE THREAD

**Issue by superyarik** [expo/expo#2422]
expo SDK 30

randomly get exception when scan qr codes, in logcat find

```
10-15 09:44:10.482 9832-11191/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #8
    Process: host.exp.exponent, PID: 9832
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: Invalid image data size.
        at com.google.android.gms.f.b$a.a(Unknown Source:22)
        at abi30_0_0.expo.modules.barcodescanner.utils.FrameFactory.buildFrame(FrameFactory.java:13)
        at abi30_0_0.expo.modules.barcodescanner.scanners.GMVBarCodeScanner.scan(GMVBarCodeScanner.java:36)
        at abi30_0_0.expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:36)
        at abi30_0_0.expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:6)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

is it relased to https://github.com/react-native-community/react-native-camera/issues/1255 ?

**Comment by sjchmiela** [comment]
Hey @superyarik! Does it crash the application or just fail silently?

**Comment by superyarik** [comment]
yep, sometimes it's asking to send debug info to google, sometimes just crush like home button press.

**Comment by wellmonge** [comment]
> expo SDK 30
> 
> randomly get exception when scan qr codes, in logcat find
> 
> 10-15 09:44:10.482 9832-11191/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #8
> Process: host.exp.exponent, PID: 9832
> java.lang.RuntimeException: An error occurred while executing doInBackground()
> at android.os.AsyncTask$3.done(AsyncTask.java:353)
> at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
> at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
> at java.util.concurrent.FutureTask.run(FutureTask.java:271)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
> at java.lang.Thread.run(Thread.java:764)
> Caused by: java.lang.IllegalArgumentException: Invalid image data size.
> at com.google.android.gms.f.b$a.a(Unknown Source:22)
> at abi30_0_0.expo.modules.barcodescanner.utils.FrameFactory.buildFrame(FrameFactory.java:13)
> at abi30_0_0.expo.modules.barcodescanner.scanners.GMVBarCodeScanner.scan(GMVBarCodeScanner.java:36)
> at abi30_0_0.expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:36)
> at abi30_0_0.expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:6)
> at android.os.AsyncTask$2.call(AsyncTask.java:333)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
> at java.lang.Thread.run(Thread.java:764) 
> 
> is it relased to [react-native-community/react-native-camera#1255](https://github.com/react-native-community/react-native-camera/issues/1255) ?
Could you reproduce your enviroment?

**Comment by superyarik** [comment]
we will make snack in a few days

also logs from ios device
`HW kbd: Failed to set (null) as keyboard focus
TCP Conn 0x280f0e700 Failed : error 0:61 [61]
[com.apple.WebKi:848] SyscallError: setpriority(PRIO_DARWIN_ROLE, 848, 3): Operation not supported

Can't get most elevated app state from dictionary {
    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "ru.hubex.engineer";
    SBApplicationStateKey = 0;
    SBApplicationStateProcessIDKey = 845;
    SBApplicationStateRunningReasonsKey =     (
                {
            SBApplicationStateRunningReasonAssertionIdentifierKey = Resume;
            SBApplicationStateRunningReasonAssertionReasonKey = 10000;
        },
                {
            SBApplicationStateRunningReasonAssertionIdentifierKey = "Shared Background Assertion 0 for ru.hubex.engineer";
            SBApplicationStateRunningReasonAssertionReasonKey = 4;
        }
    );
}`

in both errors there is about background task...
