### ISSUE TITLE
TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found.

### ISSUE THREAD

**Issue by evertuv** [expo/expo#24468]
### Summary

My application is correct in the expo go development environment, but when I build and open the application it closes and I receive the following log in abs logcat, would anyone have any idea how to solve it?

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

```
{
  "name": "projectname",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.3.1",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@tanstack/react-query": "^4.35.3",
    "axios": "^1.5.0",
    "expo": "~49.0.10",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-circular-progress-indicator": "^4.4.2",
    "react-native-dotenv": "^3.4.9",
    "react-native-paper": "^5.10.4",
    "react-native-reanimated": "~3.3.0",
    "react-native-recaptcha-that-works": "^2.0.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "zod": "^3.22.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~49.0.10 => 49.0.10
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: managed
```

### Reproducible demo

```
index.js
import 'react-native-gesture-handler';
import { AppRegistry } from 'react-native';
import { atsoftwaresolutions as appName } from './app.json'
import App from './App';

AppRegistry.registerComponent(appName, () => App);

app.tsx
import React from 'react'
import { AppRoutes } from './src/routes/routes';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { AuthContextProvider } from './src/context/AuthContext';

export default function App() {
  const queryClient = new QueryClient()

  return (
    <QueryClientProvider client={queryClient}>
      <AuthContextProvider>
        <AppRoutes />
      </AuthContextProvider>
    </QueryClientProvider>
  )
}
```

### Stacktrace (if a crash is involved)

````
FATAL EXCEPTION: mqt_native_modules
Process: com.projectname.projectname, PID: 10651
com.facebook.react.common.JavascriptException: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes, stack:
invariant@1:63052
getEnforcing@1:82422
anonymous@1:1203011
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:1198796
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:1198573
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:1195593
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:1195143
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:1194528
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:1191420
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:1190999
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:683278
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:682824
loadModuleImplementation@1:45432
guardedLoadModule@1:44987
metroRequire@1:44615
anonymous@1:51812
loadModuleImplementation@1:45432
guardedLoadModule@1:44944
metroRequire@1:44615
global@1:44171

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
```

**Comment by adamblvck** [comment]
Having the same issue

**Comment by evertuv** [comment]
@adamblvck 

import "react-native-gesture-handler";
import { GestureHandlerRootView } from "react-native-gesture-handler";

<GestureHandlerRootView style={{ flex: 1 }}>
  <AppRoutes />
</GestureHandlerRootView>

This solved it for me, but maybe it's something in your package that is conflicting and breaking the application
