### ISSUE TITLE
FetchError when pushing notification on expo

### ISSUE THREAD

**Issue by lamipaul** [expo/expo#2454]
I am trying to send push notifications using the [expo-server-sdk-node](https://github.com/expo/expo-server-sdk-node) package from a firebase cloud function. 
the server returns a `fetchError : getaddrinfo EAI_AGAIN exp.host:443` 

The rest of the function executes with no error.
The expo token and message format seem correct (see actual behavior).

### Environment
Firebase cloud function, trying to send push notifications to react native expo app using expo-server-sdk 

### Steps to Reproduce

1. Deploy function on firebase server
2. Trigger function by writing a new message in the DB
3. the function fetches the user's tokens from the firebase realtime db
4. the function builds the message to be sent
5. the function calls `expo.sendPushNotificationsAsync(chunk)`

### Expected Behavior
The pushed message is sent to the expo server and redirected to the android expo app through google cloud messaging.

### Actual Behavior

The message is not received on the phone.
The message object sent is : 
```
[ { to: 'ExponentPushToken[wpZZfVOYDjb8Xq_jmNOXGI]',
    sound: 'default',
    body: 'jkObject wrote : Hello World!',
    title: 'New Message on PiPle' } ]
```
 
The ticketChunk gets this error : 
```
{ FetchError: request to https://exp.host/--/api/v2/push/send failed, reason: getaddrinfo EAI_AGAIN exp.host:443
    at ClientRequest.<anonymous> (/srv/node_modules/node-fetch/lib/index.js:1345:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'request to https://exp.host/--/api/v2/push/send failed, reason: getaddrinfo EAI_AGAIN exp.host:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }

```

### Reproducible Demo
Here is the firebase function executing on server

```

const {Expo} = require('expo-server-sdk');

exports.sendNotification = functions.database.ref('AugustTests/groupList/{grpId}/MOIList/{moiId}/messageList/{msgId}/').onWrite( 
  async (change, context) => { 
    if(change.after.exists()){ 
      const text = change.after.val().text; 
      const authorId = change.after.val().user; 
    
      // Get the list of device notification tokens. 
      const groupRef = change.after.ref.parent.parent.parent.parent;
      const userListRef = groupRef.parent.parent
			const getParticipantsPromise = groupRef.child('participantList').once('value'); 
 
      const participants = await Promise.all([getParticipantsPromise]); 

 
 			var getUsersPromise = [];
 			for(let key in participants[0].val()){
 				if(key!==authorId){
 					getUsersPromise.push(admin.database().ref('AugustTests/userList/'+key).once('value'));
 				}
 			}
 			const getAuthorPromise = admin.database().ref('AugustTests/userList/'+authorId).once('value');

      const users = await Promise.all(getUsersPromise); 
 
 			var expoTokens=[];
      for(let uid in users){
      	if(users[uid].val()['tokens']){
      		for(let code of Object.keys(users[uid].val()['tokens'])){

	      		 expoTokens.push(String('ExponentPushToken[').concat(code,']'));
  				}
     		}
      }

      const author = await Promise.all([getAuthorPromise]); 

      const pseudo = author[0].val()['pseudo']; 

      //Push expo tokens
      if(expoTokens.length>0){
  			let expo = new Expo();

  			let messages = [];
  			for (let pushToken of expoTokens) {
  			  if (!Expo.isExpoPushToken(pushToken)) {
  			    console.error('Push token '+pushToken+' is not a valid Expo push token');
  			  }
  			  messages.push({
  			    to: pushToken,
  			    sound: 'default',
  			    body: pseudo+' wrote : '+text,
  			    title: 'New Message on PiPle',
  			  })
  			}


  			let chunks = expo.chunkPushNotifications(messages);
  			let tickets = [];
  			(async () => {
  			  for (let chunk of chunks) {
  			    try {
  			      let ticketChunk = await expo.sendPushNotificationsAsync(chunk);
  			      console.log(ticketChunk);
  			      tickets.push(...ticketChunk); 
  			    } catch (error) {
  			      console.error(error);
  			    }
  			  }
  			})();
      }

    } 
    return null; 
  });
```

**Comment by lamipaul** [comment]
turns out this is due to the fact that firebase doesn't allow outbound request when on free plan
