### ISSUE TITLE
Not able to run npx expo start --tunnel

### ISSUE THREAD

**Issue by mikoprus** [expo/expo#24627]
### Summary

`npx expo start --tunnel` 

results in:

Starting project at /project_location
Starting Metro Bundler
CommandError: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
      npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.8 => 0.19.8 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

`npx expo start --tunnel`

**Comment by nalinbhardwaj** [comment]
+1; I reproduced this

**Comment by AmeliaIsStillCoding** [comment]
+1

**Comment by kaushik1094** [comment]
+1

Could reproduce this on SDK 48.0.0

Node Version: 16.17.0 but same issue Node18 as well.

**Comment by x41lakazam** [comment]
+1 
Could reproduce

**Comment by tabletenniser** [comment]
+1, also hit this on Mac with sdk 48.0.0. Tried node version 18.14.0 and 18.16.0 with no luck. Things work fine without the `--tunnel` flag, but I kinda need that flag in order to bypass https://stackoverflow.com/questions/76396683/expo-app-not-running-on-dev-buildunexpected-end-of-stream-expo

Is there anyway we can get a stacktrace or more debugging info on `npx expo start --tunnel` command to debug this? Has anyone managed to find a workaround / solution to this?

**Comment by bgowers** [comment]
+1

**Comment by tabletenniser** [comment]
The work around I ended up using for this is:
* Run `npx expo` without the --tunnel flag: `npx expo start --dev-client --port 80`
* Install ngrok separate and run `ngrok http 80 --log stdout`
* When expo app opens, enter the ngrok URL from step #2 above manually in the emulator

It's a bit troublesome but it works at least...

**Comment by bgowers** [comment]
> The work around I ended up using for this is:
> 
> * Run `npx expo` without the --tunnel flag: `npx expo start --dev-client --port 80`
> * Install ngrok separate and run `ngrok http 80 --log stdout`
> * When expo app opens, enter the ngrok URL from step 2 above manually in the emulator
> 
> It's a bit troublesome but it works at least...

With this I'm able to open the app and I can see that expo dev server bundles the necessary index files. But I don't think it is properly connected because I can't get any logs from my interactions **and** whenever I do anything to change state in the app (that would require the expo dev server), I see a log from ngrok with the message `msg="join connections"`.

This makes me think that the app on my phone isn't actually connected to expo dev server, but simply sending requests to the proxied URL. This becomes apparent when I list the available devices from expo cli (`shift+i`) - I cannot see my iPhone listed as an available device.

**Comment by bgowers** [comment]
I'm still getting this issue. I managed to proxy the dev client using ngrok as @tabletenniser mentioned, but I also have an API running locally that the app needs to connect to. Using the internal IP of my mac (along with the correct port) doesn't work, but I can proxy the API through ngrok to get my app working locally on my physical device.

The issue is that the free ngrok subscription rate limits the proxy URLs. Since there are quite a lot of requests going through to the proxied expo dev server **and** my proxied locally running API, I quickly run out of requests, making my app unusable.

I'm wondering if there's a way that I can somehow enable my iPhone to use internal IPs on the same network so that I don't have to do any proxying...

**Comment by bgowers** [comment]
I think I know why I can't use my Mac's internal IP - I'm working on a organisation owned Mac that has restrictive firewall settings. This is not allowing my iPhone to connect 😞

**Comment by scott-gulliver** [comment]
I had this issue today, and not quite sure what the root cause is, but as a workaround, installing `@expo/ngrok` as a local dependancy rather than global seems to get past the issue for now (ie. `npm i @expo/ngrok`).

**Comment by codejudas** [comment]
Also running into this issue, @tabletenniser 's solution did not work for me unfortunately it gives another variation of the cannot connect error when i try to put the ngrok url into dev client app.

**Comment by rami-nk** [comment]
Since yesterday out of nowhere I get this error when running normal `npx expo start`: 
```
CommandError: Unexpected response when fetching version info from Expo servers: Unauthorized
```

These are my dependencies:
```json
  "dependencies": {
    "@clerk/clerk-expo": "^1.2.0",
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/native": "^6.0.2",
    "@reduxjs/toolkit": "^2.2.5",
    "expo": "~51.0.11",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.7",
    "expo-image": "~1.12.12",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.15",
    "expo-secure-store": "~13.0.1",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.6",
    "expo-updates": "~0.25.16",
    "expo-web-browser": "~13.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.2",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-web": "~0.19.10",
    "react-redux": "^9.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@expo/ngrok": "^4.1.3",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.2.45",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.1",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
```

I'm also always running expo in `tunnel` mode. This doesn't work either right now. It gives me the following error:

```
CommandError: [Network] Unauthorized
Check the Ngrok status page for outages: https://status.ngrok.com/
CommandError: [Network] Unauthorized
Check the Ngrok status page for outages: https://status.ngrok.com/
    at assertNgrok (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:197:15)
    at AsyncNgrok.connectToNgrokInternalAsync (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:206:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AsyncNgrok._connectToNgrokAsync (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:122:21)
    at AsyncNgrok.startAsync (project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:92:22)
    at MetroBundlerDevServer._startTunnelAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:248:5)
    at MetroBundlerDevServer.postStartAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:227:7)
    at MetroBundlerDevServer.startAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:163:5)
    at DevServerManager.startAsync (/project-path/node_modules/@expo/cli/src/start/server/DevServerManager.ts:176:7)
    at startAsync (/project-path/node_modules/@expo/cli/src/start/startAsync.ts:105:3)
```

I also tried running ngrok locally, substituting the authtoken by my own. This just gave me different types of errors for which I also did not find any other solution. It is working on another project I have, but on this one it just doesn't want to. 
I tried to delete every cache possible, installing and uninstalling everything. 
If you need more information just tell me.

Ah one more information. Updating expo to the newest canary version [52.0.0-canary-20240627-1402f4b](https://www.npmjs.com/package/expo/v/52.0.0-canary-20240627-1402f4b) fixed the `npx expo start`, but the ngrok issue remains.

Would appreciate it if someone can help me with that.

**Comment by rami-nk** [comment]
> Since yesterday out of nowhere I get this error when running normal `npx expo start`:
> 
> ```
> CommandError: Unexpected response when fetching version info from Expo servers: Unauthorized
> ```
> 
> These are my dependencies:
> 
> ```json
>   "dependencies": {
>     "@clerk/clerk-expo": "^1.2.0",
>     "@expo/vector-icons": "^14.0.0",
>     "@react-navigation/native": "^6.0.2",
>     "@reduxjs/toolkit": "^2.2.5",
>     "expo": "~51.0.11",
>     "expo-constants": "~16.0.2",
>     "expo-font": "~12.0.7",
>     "expo-image": "~1.12.12",
>     "expo-linking": "~6.3.1",
>     "expo-router": "~3.5.15",
>     "expo-secure-store": "~13.0.1",
>     "expo-splash-screen": "~0.27.5",
>     "expo-status-bar": "~1.12.1",
>     "expo-system-ui": "~3.0.6",
>     "expo-updates": "~0.25.16",
>     "expo-web-browser": "~13.0.3",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-native": "0.74.2",
>     "react-native-gesture-handler": "~2.16.1",
>     "react-native-reanimated": "~3.10.1",
>     "react-native-safe-area-context": "4.10.1",
>     "react-native-screens": "3.31.1",
>     "react-native-svg": "15.2.0",
>     "react-native-web": "~0.19.10",
>     "react-redux": "^9.1.2"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.20.0",
>     "@expo/ngrok": "^4.1.3",
>     "@types/jest": "^29.5.12",
>     "@types/react": "~18.2.45",
>     "@types/react-test-renderer": "^18.0.7",
>     "jest": "^29.2.1",
>     "jest-expo": "~51.0.1",
>     "react-test-renderer": "18.2.0",
>     "typescript": "~5.3.3"
>   },
> ```
> 
> I'm also always running expo in `tunnel` mode. This doesn't work either right now. It gives me the following error:
> 
> ```
> CommandError: [Network] Unauthorized
> Check the Ngrok status page for outages: https://status.ngrok.com/
> CommandError: [Network] Unauthorized
> Check the Ngrok status page for outages: https://status.ngrok.com/
>     at assertNgrok (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:197:15)
>     at AsyncNgrok.connectToNgrokInternalAsync (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:206:9)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at AsyncNgrok._connectToNgrokAsync (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:122:21)
>     at AsyncNgrok.startAsync (project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:92:22)
>     at MetroBundlerDevServer._startTunnelAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:248:5)
>     at MetroBundlerDevServer.postStartAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:227:7)
>     at MetroBundlerDevServer.startAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:163:5)
>     at DevServerManager.startAsync (/project-path/node_modules/@expo/cli/src/start/server/DevServerManager.ts:176:7)
>     at startAsync (/project-path/node_modules/@expo/cli/src/start/startAsync.ts:105:3)
> ```
> 
> I also tried running ngrok locally, substituting the authtoken by my own. This just gave me different types of errors for which I also did not find any other solution. It is working on another project I have, but on this one it just doesn't want to. I tried to delete every cache possible, installing and uninstalling everything. If you need more information just tell me.
> 
> Ah one more information. Updating expo to the newest canary version [52.0.0-canary-20240627-1402f4b](https://www.npmjs.com/package/expo/v/52.0.0-canary-20240627-1402f4b) fixed the `npx expo start`, but the ngrok issue remains.
> 
> Would appreciate it if someone can help me with that.

Apparently this line in AsyncNgrok.js is causing the error:
```js
            const hostname = await this._getProjectHostnameAsync();
```

**Comment by rami-nk** [comment]
> > Since yesterday out of nowhere I get this error when running normal `npx expo start`:
> > ```
> > CommandError: Unexpected response when fetching version info from Expo servers: Unauthorized
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These are my dependencies:
> > ```json
> >   "dependencies": {
> >     "@clerk/clerk-expo": "^1.2.0",
> >     "@expo/vector-icons": "^14.0.0",
> >     "@react-navigation/native": "^6.0.2",
> >     "@reduxjs/toolkit": "^2.2.5",
> >     "expo": "~51.0.11",
> >     "expo-constants": "~16.0.2",
> >     "expo-font": "~12.0.7",
> >     "expo-image": "~1.12.12",
> >     "expo-linking": "~6.3.1",
> >     "expo-router": "~3.5.15",
> >     "expo-secure-store": "~13.0.1",
> >     "expo-splash-screen": "~0.27.5",
> >     "expo-status-bar": "~1.12.1",
> >     "expo-system-ui": "~3.0.6",
> >     "expo-updates": "~0.25.16",
> >     "expo-web-browser": "~13.0.3",
> >     "react": "18.2.0",
> >     "react-dom": "18.2.0",
> >     "react-native": "0.74.2",
> >     "react-native-gesture-handler": "~2.16.1",
> >     "react-native-reanimated": "~3.10.1",
> >     "react-native-safe-area-context": "4.10.1",
> >     "react-native-screens": "3.31.1",
> >     "react-native-svg": "15.2.0",
> >     "react-native-web": "~0.19.10",
> >     "react-redux": "^9.1.2"
> >   },
> >   "devDependencies": {
> >     "@babel/core": "^7.20.0",
> >     "@expo/ngrok": "^4.1.3",
> >     "@types/jest": "^29.5.12",
> >     "@types/react": "~18.2.45",
> >     "@types/react-test-renderer": "^18.0.7",
> >     "jest": "^29.2.1",
> >     "jest-expo": "~51.0.1",
> >     "react-test-renderer": "18.2.0",
> >     "typescript": "~5.3.3"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm also always running expo in `tunnel` mode. This doesn't work either right now. It gives me the following error:
> > ```
> > CommandError: [Network] Unauthorized
> > Check the Ngrok status page for outages: https://status.ngrok.com/
> > CommandError: [Network] Unauthorized
> > Check the Ngrok status page for outages: https://status.ngrok.com/
> >     at assertNgrok (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:197:15)
> >     at AsyncNgrok.connectToNgrokInternalAsync (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:206:9)
> >     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at AsyncNgrok._connectToNgrokAsync (/project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:122:21)
> >     at AsyncNgrok.startAsync (project-path/node_modules/@expo/cli/src/start/server/AsyncNgrok.ts:92:22)
> >     at MetroBundlerDevServer._startTunnelAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:248:5)
> >     at MetroBundlerDevServer.postStartAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:227:7)
> >     at MetroBundlerDevServer.startAsync (/project-path/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:163:5)
> >     at DevServerManager.startAsync (/project-path/node_modules/@expo/cli/src/start/server/DevServerManager.ts:176:7)
> >     at startAsync (/project-path/node_modules/@expo/cli/src/start/startAsync.ts:105:3)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also tried running ngrok locally, substituting the authtoken by my own. This just gave me different types of errors for which I also did not find any other solution. It is working on another project I have, but on this one it just doesn't want to. I tried to delete every cache possible, installing and uninstalling everything. If you need more information just tell me.
> > Ah one more information. Updating expo to the newest canary version [52.0.0-canary-20240627-1402f4b](https://www.npmjs.com/package/expo/v/52.0.0-canary-20240627-1402f4b) fixed the `npx expo start`, but the ngrok issue remains.
> > Would appreciate it if someone can help me with that.
> 
> Apparently this line in AsyncNgrok.js is causing the error:
> 
> ```js
>             const hostname = await this._getProjectHostnameAsync();
> ```

I have hacked fixed it by hardcoding the hostname here and it did work lol

**Comment by AhmedCoolProjects** [comment]
> * ngrok http 80 --log stdout

Well if I wanted to use that link in expo go, we need kinda a prefix "expo://" something similar, any idea please?

**Comment by mtch99** [comment]
> I had this issue today, and not quite sure what the root cause is, but as a workaround, installing `@expo/ngrok` as a local dependancy rather than global seems to get past the issue for now (ie. `npm i @expo/ngrok`).

This worked for me

**Comment by isiyok-siemens** [comment]
For me none of the above comments worked but this worked:
1. npm uninstall -g @expo/ngrok
2. npm install -g @expo/ngrok@4.1.0

So seems like the version of the ngrok is important, before it was 4.1.3 installed

**Comment by isiyok** [comment]
For me none of the above comments worked but this worked:

1. npm uninstall -g @expo/ngrok
2. npm install -g @expo/ngrok@4.1.0

**Comment by DavidJFigueroa** [comment]
Unfortunately none of the above solutions worked for me im still getting:
CommandError: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null

**Comment by DavidJFigueroa** [comment]
> > For me none of the above comments worked but this worked:
> > 
> > 1. npm uninstall -g @expo/ngrok
> > 2. npm install -g @expo/ngrok@4.1.0
> 
> This works!

Unfortunately not for me.

**Comment by DavidJFigueroa** [comment]
> > For me none of the above comments worked but this worked:
> > 
> > 1. npm uninstall -g @expo/ngrok
> > 2. npm install -g @expo/ngrok@4.1.0
> 
> This works!

Still the same error also with @expo/ngrok@4.1.0
<img width="886" alt="Screenshot 2024-11-26 at 6 28 50 PM" src="https://github.com/user-attachments/assets/cb85ef43-f3d1-4f1e-b5ba-c2ca568d418c">
