### ISSUE TITLE
Exception occurred while executing exported method watchPositionImplAsync on module ExpoLocation

### ISSUE THREAD

**Issue by m-regragui** [expo/expo#24774]
Hi, I catch an error with expo-location only on production on android (work well in dev). I tried with Location.watchPositionAsync() and Location.getLastKnownPositionAsync() :

```
const [location, setLocation] = useState(null);

useEffect(() => {
    (async () => {
      let { status } = await Location.requestForegroundPermissionsAsync();
      if (status !== "granted") {
        return;
      }
      try {
        await Location.watchPositionAsync(
          { accuracy: Location.Accuracy.High },
          (loc) => {
            setLocation(loc);
          }
        );
      } catch (error) {
        alert(error);
      }
    })();
  }, []);
```

Error: Encountered an exception while calling native method: Exception occurred while executing exported method watchPositionImplAsync on module ExpoLocation: Found interface com.google.android.gms.lo cation.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.locati on.FusedLocation ProviderClient' appears in /data/app/

I use SDK 49 with expo-location 16.1.0 and managed workflow with eas build

_Originally posted by @m-regragui in https://github.com/expo/expo/issues/10756#issuecomment-1746555020_

**Comment by forki** [comment]
I have something similiar but directly in Expo app:

Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExpoNotificationPermissionsModule: String resource ID #0xffffffff

**Comment by lluisandreu** [comment]
Same issue here with version ^16.3.0

[Error: Encountered an exception while calling native method: Exception occurred while executing exported method watchPositionImplAsync on module ExpoLocation: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~3v9DmJnHtC12IHYDflLujA==/com.tokentrotter.app-EzsxN5xHAaWl9kY0ns_eBQ==/base.apk!classes6.dex)]

**Comment by lluisandreu** [comment]
I think expo-location should update "play-services-location" to 21.0.1

com.google.android.gms:play-services-location:21.0.1

If that is an issue for those using react-native-maps, they can update this package to v2.0.0-beta.14 which works with PSL 21.0.1.

**Comment by CostasCF** [comment]
Still having the same issue, any solution?

**Comment by Thotsuya** [comment]
I'm having a similar issue

`[Error: Encountered an exception while calling native method: Exception occurred while executing exported method getCurrentPositionAsync on module ExpoLocation: Found interface com.google.android.gms.location.FusedLocation
ProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~3vyWg7s9RwJ99lUbw2dcmg==/com.thotsuya.medlaapp-xjcjrh20AevFazVYU2oXvg==/base.apk!classes6.dex)]`

with Expo Location version: 

`"expo-location": "~15.1.1",`

**Comment by CostasCF** [comment]
Apparently going inside native-modules folder -> expo-location -> android -> build.gradle and changing: 

`  api 'com.google.android.gms:play-services-location:x.x.x' `to   `api 'com.google.android.gms:play-services-location:21.0.1'`
  
  fixes the issue! 

So yes, expo team needs to patch this and update this dependency.

**Comment by Thotsuya** [comment]
> Apparently going inside native-modules folder -> expo-location -> android -> build.gradle and changing:
> 
> ` api 'com.google.android.gms:play-services-location:x.x.x'`to `api 'com.google.android.gms:play-services-location:21.0.1'`
> 
> fixes the issue!
> 
> So yes, expo team needs to patch this and update this dependency.


I've just did that, rebuild my project using EAS Build but still getting the error.

**Comment by mehdi78800** [comment]
> > Apparently going inside native-modules folder -> expo-location -> android -> build.gradle and changing:
> > ` api 'com.google.android.gms:play-services-location:x.x.x'`to `api 'com.google.android.gms:play-services-location:21.0.1'`
> > fixes the issue!
> > So yes, expo team needs to patch this and update this dependency.
> 
> I've just did that, rebuild my project using EAS Build but still getting the error.

me too

**Comment by Thotsuya** [comment]
> > > Apparently going inside native-modules folder -> expo-location -> android -> build.gradle and changing:
> > > ` api 'com.google.android.gms:play-services-location:x.x.x'`to `api 'com.google.android.gms:play-services-location:21.0.1'`
> > > fixes the issue!
> > > So yes, expo team needs to patch this and update this dependency.
> > 
> > 
> > I've just did that, rebuild my project using EAS Build but still getting the error.
> 
> me too

Updating to Expo SDK 49 Fixed the issue for me.

**Comment by CostasCF** [comment]
@Thotsuya @mehdi78800 

I am using expo location v16.3.0 and Expo SDK 49 and my fix works. You shouldn't reinstall node modules with what I suggested as it overwrites the fix. 

It's only a temporary fix and it will only work on the local dev environment. 

I still think expo team needs to update  

`api 'com.google.android.gms:play-services-location:x.x.x' `to api `'com.google.android.gms:play-services-location:21.0.1'` in expo-location package and it should work fine then for production.

**Comment by mehdi78800** [comment]
> @Thotsuya @mehdi78800
> 
> I am using expo location v16.3.0 and Expo SDK 49 and my fix works. You shouldn't reinstall node modules with what I suggested as it overwrites the fix.
> 
> It's only a temporary fix and it will only work in the local dev environment.
> 
> I still think expo team needs to update
> 
> `api 'com.google.android.gms:play-services-location:x.x.x' `to api `'com.google.android.gms:play-services-location:21.0.1'` in expo-location package and it should work fine then for production.

I have not the issue in local dev environment, only in production, I also tried to downgrade expo-location but that not resolve the issue. I'm on expo location v16.1.0 and Expo SDK 49 and i also already tried to run a prebuild to create the android folder then change api 'com.google.android.gms:play-services-location:x.x.x' to api 'com.google.android.gms:play-services-location:21.0.1' but not working neither..

**Comment by robrechtme** [comment]
As far as I understand, this issue arises from a version mismatch of `com.google.android.gms:play-services-location` between `expo-location` and `react-native-maps`. See #23501 which essentially introduces the bug. To fix this, make sure you use the same version of `com.google.android.gms:play-services-location` for both `expo-location` and `react-native-maps`. 

If you're using `expo-location@16.3.0` and `react-native-maps@1.8.1` you can do so by bumping the one from `expo-location` as @CostasCF suggests. If you're using [patch-package](https://www.npmjs.com/package/patch-package), you can use this patch:

```patch
diff --git a/node_modules/expo-location/android/build.gradle b/node_modules/expo-location/android/build.gradle
index 3610030..01cd9f7 100644
--- a/node_modules/expo-location/android/build.gradle
+++ b/node_modules/expo-location/android/build.gradle
@@ -85,7 +85,7 @@ android {
 dependencies {
   implementation project(':expo-modules-core')
 
-  api 'com.google.android.gms:play-services-location:20.0.0'
+  api 'com.google.android.gms:play-services-location:21.0.1'
 
   api('io.nlopez.smartlocation:library:3.3.3') {
     transitive = false
```

**Comment by lucasgrass** [comment]
+1, "expo": "~48.0.9", "expo-location": "^16.3.0",

**Comment by lluisandreu** [comment]
My solution was to fix the react-native-maps package to: 
"react-native-maps": "2.0.0-beta.14",

And then use the patch above or mine to change the play service location dependency (using patch-package)

```
diff --git a/node_modules/expo-location/android/build.gradle b/node_modules/expo-location/android/build.gradle
index 3610030..01cd9f7 100644
--- a/node_modules/expo-location/android/build.gradle
+++ b/node_modules/expo-location/android/build.gradle
@@ -85,7 +85,7 @@ android {
 dependencies {
   implementation project(':expo-modules-core')
 
-  api 'com.google.android.gms:play-services-location:20.0.0'
+  api 'com.google.android.gms:play-services-location:21.0.1'
 
   api('io.nlopez.smartlocation:library:3.3.3') {
     transitive = false
```

**Comment by superyarik** [comment]
> I've just did that, rebuild my project using EAS Build but still getting the error.

If you made changes to build.gradle locally, the Expo servers are not aware of your local modifications.

looks like PR is on the go https://github.com/expo/expo/pull/25028

**Comment by emuswailit** [comment]
Still stuck on the same too. Any help out there?

**Comment by CostasCF** [comment]
looks like the PR is merged, so now we just wait for the new expo-location version, right?

**Comment by superyarik** [comment]
Also, I wonder if it will be possible to use this fix in SDK48.

**Comment by CostasCF** [comment]
I ended up using [patch-package](https://www.npmjs.com/package/patch-package) for production as well. (Thanks @robrechtme for the suggestion!). It's a good temporary fix till the new version of expo-location arrives.

**Comment by larbizard** [comment]
> I ended up using [patch-package](https://www.npmjs.com/package/patch-package) for production as well. (Thanks @robrechtme for the suggestion!). It's a good temporary fix till the new version of expo-location arrives.

Hi @CostasCF, I am new at using patch-package. Is there a way to use the remote changes from https://github.com/expo/expo/tree/main/packages/expo-location/ or do we have to make the changes locally.

I am not able to build locally I wanted to use the remote changes and trigger the build on eas build.

Thank you for your help.

**Comment by CostasCF** [comment]
@larbizard I think you can just make the changes locally inside node_modules folder, then you type: 

npx patch-package expo-location

(Make sure to add the script in the package.json - follow the readme of patch-package) 

Then, a folder called patches is created containing the changes you did locally.

So, then you can just type: 
eas build -p android --profile production
 
And it builds in the remote expo server.

**Comment by larbizard** [comment]
@CostasCF Thank you !
It worked perfectly.
I just changed the following in the build.gradle
`api 'com.google.android.gms:play-services-location:20.0.0'`
to 
`api 'com.google.android.gms:play-services-location:21.0.1'`
And applied the patch and builded using `eas build -p android --profile production`

Hopefully the merge will be released soon !

**Comment by mehdi78800** [comment]
> @larbizard I think there is no way to get the changes remotely. However, it's easy to do it locally. Make the needed changes inside node_modules folder, then you type:
> 
> npx patch-package expo-location
> 
> (Make sure to add the script in the package.json - follow the readme of patch-package)
> 
> Then, a folder called patches is created containing the changes you did locally.
> 
> So, then you can just type: eas build -p android --profile production
> 
> And it builds in the remote expo server.

Thanks a lot for your detailed explanations, i did it and it finally works in production as well 👍

**Comment by superyarik** [comment]
> It worked perfectly.
> I just changed the following in the build.gradle
> `api 'com.google.android.gms:play-services-location:20.0.0'`
> to
> `api 'com.google.android.gms:play-services-location:21.0.1'`
> And applied the patch and builded using `eas build -p android --profile production`

Can you specify the changes you made in build.gradle using the script for patch-package?

**Comment by larbizard** [comment]
> > It worked perfectly.
> > I just changed the following in the build.gradle
> > `api 'com.google.android.gms:play-services-location:20.0.0'`
> > to
> > `api 'com.google.android.gms:play-services-location:21.0.1'`
> > And applied the patch and builded using `eas build -p android --profile production`
> 
> Can you specify the changes you made in build.gradle using the script for patch-package?
Hi @superyarik ,

1. I installed patch-package using: 
 
`npx patch-package expo-location`

2.  I then added the patch-package to the scripts section in package.json

```
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "postinstall": "patch-package"
  },
```

3. I made sure that all my modules are installed: 

`npm install` or `npx expo install`

4. I modified `node_modules/expo-location/android/build.gradle`  by updating line 108 :

reaplacing `api 'com.google.android.gms:play-services-location:20.0.0'`

with

with `api 'com.google.android.gms:play-services-location:21.0.1'`

5. I then executed the `patch-package` script using:

`npx patch-package expo-location`

This produced a file in a sub folder `patches/expo-location+16.4.0.patch` with contains the delta of our patch

```
diff --git a/node_modules/expo-location/android/build.gradle b/node_modules/expo-location/android/build.gradle
index e16df0a..09341fc 100644
--- a/node_modules/expo-location/android/build.gradle
+++ b/node_modules/expo-location/android/build.gradle
@@ -105,7 +105,7 @@ dependencies {
     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${getKotlinVersion()}"
   }
 
-  api 'com.google.android.gms:play-services-location:20.0.0'
+  api 'com.google.android.gms:play-services-location:21.0.1'
 
   api('io.nlopez.smartlocation:library:3.3.3') {
     transitive = false
```

6. I finally commited by code to my branch and started the remote build on eas using:

`eas build -p android --profile production`

**Comment by farfanRogerBrandon** [comment]
hi @larbizard . is it necesary to make this?  "postinstall": "patch-package", When I make npx install that bring me a lot of errors

**Comment by Jahanzeb009** [comment]
> Apparently going inside native-modules folder -> expo-location -> android -> build.gradle and changing:
> 
> ` api 'com.google.android.gms:play-services-location:x.x.x'`to `api 'com.google.android.gms:play-services-location:21.0.1'`
> 
> fixes the issue!
> 
> So yes, expo team needs to patch this and update this dependency.

This solved my problem, I use the patch package :D

**Comment by samuelastech** [comment]
> hi @larbizard . is it necesary to make this? "postinstall": "patch-package", When I make npx install that bring me a lot of errors EDIT: Yes, it was very necessary. Also MAKE SURE to change the react native maps too. It works

@farfanRogerBrandon which version of react-native-maps are you using?

**Comment by farfanRogerBrandon** [comment]
> > hi @larbizard . is it necesary to make this? "postinstall": "patch-package", When I make npx install that bring me a lot of errors EDIT: Yes, it was very necessary. Also MAKE SURE to change the react native maps too. It works
> 
> @Jahanzeb009 @farfanRogerBrandon which version of react-native-maps are you using?

Hi, the versions is 1.7.1  . You have to change the version like this, in both, expo location and maps: +  implementation "com.google.android.gms:play-services-location:21.0.1"

**Comment by samuelastech** [comment]
Finally it's working! Thank you @farfanRogerBrandon <3

**Comment by Jahanzeb009** [comment]
> > hi @larbizard . is it necesary to make this? "postinstall": "patch-package", When I make npx install that bring me a lot of errors EDIT: Yes, it was very necessary. Also MAKE SURE to change the react native maps too. It works
> 
> @Jahanzeb009 @farfanRogerBrandon which version of react-native-maps are you using?

1.3.2 with expo sdk 48

**Comment by HarsHopp** [comment]
Thank you very much @CostasCF & @larbizard. Answers of you both worked perfectly for me in android apk after looking for solution for long time, really thanks.

**Comment by HarsHopp** [comment]
I was having doubt that do we need to do anything like this for iOS app when using `react-native-maps` & `expo-location`?

**Comment by emirdeliz** [comment]
+1

**Comment by HidayetCanOzcan** [comment]
I was having the same problem. When I made the update described above in the expo-location package, my problem was solved. When I realized that I was getting the same error when showing the user's location, I made the same correction and updated the dependencies of the react-native-maps package and it was solved. I hope it will be useful to you too.

**Comment by YassineOujaa77** [comment]
Downgrading to expo-location v16.1.0 worked for me

**Comment by akorajac** [comment]
issue still not fixed 👎

**Comment by christopherboisvert** [comment]
> Apparently going inside native-modules folder -> expo-location -> android -> build.gradle and changing:
> 
> ` api 'com.google.android.gms:play-services-location:x.x.x'`to `api 'com.google.android.gms:play-services-location:21.0.1'`
> 
> fixes the issue!
> 
> So yes, expo team needs to patch this and update this dependency.

This was the fix for me.

**Comment by superyarik** [comment]
For those who are using SDK48, here's how it works for me: for building on Android, I updated expo-location to version 16.5.1, as well as react-native-maps to 1.8.4. It builds and works fine. However, for building on iOS, I need to downgrade expo-location to version 15.1.1 - otherwise, the iOS build fails. It may seem a bit hacky, but it works for SDK48. It's recommended to upgrade to SDK49.

**Comment by Eliost** [comment]
SDK 49 : 
I get this error, even when modifying expo-location with patch-package: "com.google.android.gms:play-services-location:21.0.1"
Nothing changes, I still get this error :
"Erreur get position:, [Error: Encountered an exception while calling native method: Exception occurred while executing exported method reverseGeocodeAsync on module ExpoLocation: host.exp.exponent: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts]"

 -> overnight, incomprehensible

**Comment by christopherboisvert** [comment]
Hi everyone ! I have updated the version of expo-location to the latest ~16.5.2 and it fixed it for me.

**Comment by Eliost** [comment]
I tried everything mentioned above and nothing worked for me. Always the same error that suddenly appears.

`Exception occurred while executing exported method reverseGeocodeAsync on module ExpoLocation: host.exp.exponent: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`

I haven't been able to fix the problem yet.

**Comment by christopherboisvert** [comment]
> I tried everything mentioned above and nothing worked for me. Always the same error that suddenly appears.
> 
> `Exception occurred while executing exported method reverseGeocodeAsync on module ExpoLocation: host.exp.exponent: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`
> 
> I haven't been able to fix the problem yet.

Have you tried upgrading to a newer version of expo ? That was one of the changes I made.

**Comment by 2kneo** [comment]
> Я попробовал все, что описано выше, и у меня ничего не получилось. Всегда одна и та же ошибка, которая внезапно появляется.
> 
> `Exception occurred while executing exported method reverseGeocodeAsync on module ExpoLocation: host.exp.exponent: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`
> 
> Мне пока не удалось решить проблему.

Same problem, I changed versions from "react-native-maps": "^1.10.2" to "react-native-maps": "^2.0.0-beta.14" and "expo-location": "16.0 .0" to "expo-location": "16.1.0", "expo-location": "16.5.3", and "expo": "~49.0.15" to "expo": "50.0.6". I don't understand what the combination needs to be for this to work.

**Comment by 2kneo** [comment]
> > Я попробовал все, что описано выше, и у меня ничего не получилось. Всегда одна и та же ошибка, которая внезапно появляется.
> > `Exception occurred while executing exported method reverseGeocodeAsync on module ExpoLocation: host.exp.exponent: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`
> > Мне пока не удалось решить проблему.
> 
> Вы пробовали обновиться до более новой версии expo? Это было одно из изменений, которые я сделал.

I tried a bunch of things and these versions worked for me 
"expo": "~49.0.15",
"expo-location": "16.0.0",
"react-native-maps": "1.8.4",

`"dependencies": {
    "@react-native-async-storage/async-storage": "^1.18.2",
    "@react-native-community/geolocation": "^3.1.0",
    "@react-native-masked-view/masked-view": "0.2.9",
    "@react-native-picker/picker": "2.4.10",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/material-top-tabs": "^6.6.5",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.20",
    "@shopify/flash-list": "^1.4.3",
    "axios": "^1.6.2",
    "expo": "~49.0.15",
    "expo-battery": "^7.7.2",
    "expo-camera": "~13.4.4",
    "expo-dev-client": "~2.4.12",
    "expo-device": "^5.9.3",
    "expo-document-picker": "^11.10.1",
    "expo-image-picker": "^14.5.0",
    "expo-local-authentication": "~13.4.1",
    "expo-localization": "^14.5.0",
    "expo-location": "16.0.0",
    "expo-media-library": "^15.9.1",
    "expo-notifications": "~0.20.1",
    "expo-permissions": "^14.4.0",
    "expo-secure-store": "^12.8.1",
    "expo-sensors": "~12.3.0",
    "expo-sharing": "^11.10.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "i18next": "^23.7.11",
    "intl": "^1.2.5",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-hook-form": "^7.48.2",
    "react-i18next": "^14.0.0",
    "react-native": "0.72.6",
    "react-native-btr": "^2.2.0",
    "react-native-flash-message": "^0.4.2",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-leaflet-view": "^0.1.2",
    "react-native-maps": "1.8.4",
    "react-native-pager-view": "^6.2.3",
    "react-native-paper": "^5.11.3",
    "react-native-reanimated": "~3.3.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "13.9.0",
    "react-native-svg-uri": "^1.2.3",
    "react-native-tab-view": "^3.5.2",
    "react-native-webview": "^13.6.3",
    "uuid": "^9.0.1"
  },`

**Comment by quanSadie** [comment]
So I fixed it by using the same version for

>  _react-native-maps_

 and _

> expo-location

_

**Comment by Arsalan-kh** [comment]
Hey! I encountered the same error. Here's how I fixed it. 🛠️ I went into the native module and updated the version of Google Play services from 20.0.0 to 21.0.1. Check out the code below:
dependencies {
  implementation project(':expo-modules-core')

  api 'com.google.android.gms:play-services-location:21.0.1'

  api('io.nlopez.smartlocation:library:3.3.3') {
    transitive = false
  }
}

Also, I'm using Expo SDK 49, "react-native-maps": "^1.14.0", and "expo-location": "~16.1.0". 🚀

**Comment by Arsalan-kh** [comment]
These are the combination you needed to fixed this issue 
Expo SDK 49, "react-native-maps": "^1.14.0", and "expo-location": "~16.1.0". 🚀

**Comment by ivanvpan** [comment]
@Arsalan-kh So you had to eject the project?

**Comment by WaheedRumaneh** [comment]
this solution worked for me, 
expo: ~49.0.20
expo-location: ~16.1.0
app status: ejected


in `MainApplication.java` add this code:

`import android.content.BroadcastReceiver;
 import android.content.Intent;
 import android.content.IntentFilter;
 import android.content.Context;
 import android.os.Build;
 import org.jetbrains.annotations.Nullable;`
 
 `@Override
     public Intent registerReceiver(@Nullable BroadcastReceiver receiver, IntentFilter filter) {
         if (Build.VERSION.SDK_INT >= 34 && getApplicationInfo().targetSdkVersion >= 34) {
             return super.registerReceiver(receiver, filter, Context.RECEIVER_EXPORTED);
         } else {
             return super.registerReceiver(receiver, filter);
         }
     }`
     
     
     
then in `android/app/build.gradle` add this code:
`implementation 'org.jetbrains:annotations:16.0.2'`

clean the build file and try again.

**Comment by roggyboy** [comment]
Hi. 
Maybe my problem is related to this  issue? 
On latest expo 51 and expo-location 17.0.1 we are getting this nullpointer on android. 
try catch around the expo location logic does not catch this. The stacktrace is from sentry reports. 
Anybody else experienced this or have any suggestions for fix? 

`java.lang.NullPointerException: java.lang.NullPointerException
    at expo.modules.kotlin.jni.JavaScriptModuleObject.emitEvent(JavaScriptModuleObject.kt)
    at expo.modules.kotlin.events.KModuleEventEmitterWrapper.emitNative(KModuleEventEmitterWrapper.kt:48)
    at expo.modules.kotlin.events.KModuleEventEmitterWrapper.emit(KModuleEventEmitterWrapper.kt:28)
    at expo.modules.kotlin.modules.Module.sendEvent(Module.kt:31)
    at expo.modules.location.LocationModule.sendLocationResponse$expo_location_release(LocationModule.kt:572)
    at expo.modules.location.LocationHelpers$Companion$requestContinuousUpdates$1.onLocationChanged(LocationHelpers.kt:97)
    at expo.modules.location.LocationModule$requestLocationUpdates$locationCallback$1.onLocationResult(LocationModule.kt:433)
    at com.google.android.gms.internal.location.zzct.notifyListener(com.google.android.gms:play-services-location@@21.0.1:2)
    at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.2.0:2)
    at com.google.android.gms.common.api.internal.zacb.run
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8839)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)`

The implementation looks like this:

`await Location.watchPositionAsync(locationOptions, newLocation => {

              if (
                newLocation &&
                newLocation.coords &&
                JSON.stringify(newLocation.coords) !==
                  JSON.stringify(location.currentLocation?.coords)
              ) {
                const updatedLocationState = {
                  ...location,
                  currentLocation: newLocation,
                };
                setLocation(updatedLocationState);
              }
            }),`

**Comment by NiccoloCase** [comment]
> Hi. Maybe my problem is related to this issue? On latest expo 51 and expo-location 17.0.1 we are getting this nullpointer on android. try catch around the expo location logic does not catch this. The stacktrace is from sentry reports. Anybody else experienced this or have any suggestions for fix?
> 
> `java.lang.NullPointerException: java.lang.NullPointerException at expo.modules.kotlin.jni.JavaScriptModuleObject.emitEvent(JavaScriptModuleObject.kt) at expo.modules.kotlin.events.KModuleEventEmitterWrapper.emitNative(KModuleEventEmitterWrapper.kt:48) at expo.modules.kotlin.events.KModuleEventEmitterWrapper.emit(KModuleEventEmitterWrapper.kt:28) at expo.modules.kotlin.modules.Module.sendEvent(Module.kt:31) at expo.modules.location.LocationModule.sendLocationResponse$expo_location_release(LocationModule.kt:572) at expo.modules.location.LocationHelpers$Companion$requestContinuousUpdates$1.onLocationChanged(LocationHelpers.kt:97) at expo.modules.location.LocationModule$requestLocationUpdates$locationCallback$1.onLocationResult(LocationModule.kt:433) at com.google.android.gms.internal.location.zzct.notifyListener(com.google.android.gms:play-services-location@@21.0.1:2) at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.2.0:2) at com.google.android.gms.common.api.internal.zacb.run at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:257) at android.os.Looper.loop(Looper.java:368) at android.app.ActivityThread.main(ActivityThread.java:8839) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)`
> 
> The implementation looks like this:
> 
> `await Location.watchPositionAsync(locationOptions, newLocation => {
> 
> ```
>           if (
>             newLocation &&
>             newLocation.coords &&
>             JSON.stringify(newLocation.coords) !==
>               JSON.stringify(location.currentLocation?.coords)
>           ) {
>             const updatedLocationState = {
>               ...location,
>               currentLocation: newLocation,
>             };
>             setLocation(updatedLocationState);
>           }
>         }),`
> ```

same issue

**Comment by ds-ms2soft** [comment]
I'm also experiencing the same issue with `Location.watchPositionAsync`. It works most of the time, but crashes randomly.

```
"expo": "~51.0.38",
"expo-location": "~17.0.1",
```

```
java.lang.NullPointerException: java.lang.NullPointerException
  expo.modules.kotlin.jni.JavaScriptModuleObject.emitEvent(Native Method)
  expo.modules.kotlin.events.KModuleEventEmitterWrapper.emitNative(KModuleEventEmitterWrapper.kt:48)
  expo.modules.kotlin.events.KModuleEventEmitterWrapper.emit(KModuleEventEmitterWrapper.kt:28)
  expo.modules.kotlin.modules.Module.sendEvent(Module.kt:31)
  expo.modules.location.LocationModule.sendLocationResponse$expo_location_debug(LocationModule.kt:572)
  expo.modules.location.LocationHelpers$Companion$requestContinuousUpdates$1.onLocationChanged(LocationHelpers.kt:97)
  expo.modules.location.LocationModule$requestLocationUpdates$locationCallback$1.onLocationResult(LocationModule.kt:433)
  com.google.android.gms.internal.location.zzct.notifyListener(com.google.android.gms:play-services-location@@21.0.1:2)
  com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.2.0:2)
  com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
  android.os.Handler.handleCallback(Handler.java:942)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:201)
  android.os.Looper.loop(Looper.java:288)
  android.app.ActivityThread.main(ActivityThread.java:7918)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by micaiah-effiong** [comment]
I am also experiencing the same issue with `Location.watchPositionAsync`. 
I have observed that the crashes happen during reloads when the app watches for position updates.

I tried to stop location update with `useEffect` as a cleanup function which didn't work, but it worked with `useLayoutEffect`
```tsx
useLayoutEffect(() => {
    return () => {
      // stopBackgroundUpdate();
      stopForegroundUpdate();
    };
}, []);
```

**Comment by ryskin** [comment]
Same problem (

**Comment by FoRavel** [comment]
Instead of using patch-package:

In android/build.gradle you can add this piece of code:

```
configurations.all {
            resolutionStrategy {
                force 'com.google.android.gms:play-services-location:21.0.1'
            }
       }
```

Inside 

allprojects { ... } brackets.

Effect: Force the usage of 21.0.1 version for all package (like expo-location).
