### ISSUE TITLE
[docs] npx create-expo-module expo-settings

### ISSUE THREAD

**Issue by Kaique292** [expo/expo#24835]
### Summary

Node version: 18.8
Windows 11

npx create-expo-module my-module 

I'm observing error as follows: 

Error: npm install exited with non-zero code: 1
    at ChildProcess.completionListener (C:\ProgramData\nvm\v18.17.0\node_modules\create-expo-module\node_modules@expo\spawn-async\build\spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:629:26)
   .......
    ...
    at spawnAsync (C:\ProgramData\nvm\v18.17.0\node_modules\create-expo-module\node_modules@expo\spawn-async\build\spawnAsync.js:7:23)
    at installDependencies (C:\ProgramData\nvm\v18.17.0\node_modules\create-expo-module\build\packageManager.js:9:37)
    at C:\ProgramData\nvm\v18.17.0\node_modules\create-expo-module\build\create-expo-module.js:86:60
    at newStep (C:\ProgramData\nvm\v18.17.0\node_modules\create-expo-module\build\utils.js:21:22)
    at Command.main (C:\ProgramData\nvm\v18.17.0\node_modules\create-expo-module\build\create-expo-module.js:85:35) {
  pid: 27716,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null
}

so I did manual installation of dependencies and happen to find the following:

set -eo pipefail
        ^^^^^^^^

SyntaxError: Unexpected identifier
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

### Link to the related docs page

https://docs.expo.dev/modules/native-module-tutorial/#example-app-2

**Comment by JJosephttg** [comment]
Same problem, using yarn for my package manager inside of workspaces and am windows 11
