### ISSUE TITLE
Audio files are not loading in Expo AV on Android

### ISSUE THREAD

**Issue by jarcoder** [expo/expo#24875]
### Minimal reproducible example

Audio.Sound.createAsync({ uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' });

### Summary

Using the method Audio.Sound.createAsync of ExpoAV package I tried to open a local file using the "require" method, a local file at the URL 'file:///...' and a file from a web server with different versions of Expo 49.0.x and ExpoAV 12.x.x-13.x.x and on three smartphones: OnePlus 8 (Android 13), OnePlus 8T (Android 13), Samsung Galaxy S20 (Android 11). All attempts have failed with this error:

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Cannot convert 'null' to a Kotlin type.
Error: Cannot convert 'null' to a Kotlin type.
    at construct (native)
    at apply (native)
    at _construct (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:4470:28)
    at Wrapper (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:4428:25)
    at construct (native)
    at _createSuperInternal (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:124818:322)
    at call (native)
    at CodedError (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:124831:26)
    at promiseFn (native)
    at tryCallTwo (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at loadForSound (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:132387:47)
    at tryCallTwo (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:132371:31)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:6070:26)
    at _next (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:6089:29)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/554c6x4t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:39573:26)
    at _callTimer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:39452:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:39497:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:39703:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:3677:46)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:3451:45)
    at __guard (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:3650:15)
    at flushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.jarcoder.testaudio&modulesOnly=false&runModule=true:3450:21)
```

Simple code for reproduce (App.tsx):

```

import { StatusBar } from 'expo-status-bar';
import { Text, View } from 'react-native';
import { Audio } from 'expo-av';
import { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    Audio.Sound.createAsync(
      { uri: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
      { shouldPlay: false },
      () => {},
      true,
    );
  }, []);
  return (
    <View style={{ flex: 1 }}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

```

package.json:

```
{
  "name": "test_audio",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.13",
    "expo-av": "^13.7.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

The new architecture is enabled. JS engine is Hermes.

The problem is relevant only on Android. Everything works fine on iOS devices.

### Environment

Expo info:
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.2 - /usr/local/bin/npm
      Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.3.10
```

**Comment by jarcoder** [comment]
> Hi there! It looks like your issue requires a minimal reproducible example, but it is invalid or absent. Please prepare such an example and share it in a new issue.
> 
> **The best way to get attention to your issue is to provide a clean and easy way for a developer to reproduce the issue on their own machine.** Please do not provide your entire project, or a project with more code than is necessary to reproduce the issue.
> 
> A side benefit of going through the process of narrowing down the minimal amount of code needed to reproduce the issue is that you may get lucky and discover that the bug is due to a mistake in your application code that you can quickly fix on your own.
> 
> ### Resources
> * ["How to create a Minimal, Reproducible Example"](https://stackoverflow.com/help/minimal-reproducible-example)
> * ["How to narrow down the source of an error"](https://expo.fyi/manual-debugging)
> 
> ### Common concerns
> #### "I've only been able to reproduce it in private, proprietary code"
> You may not have spent enough time narrowing down the root cause of the issue. Try out the techniques discussed in this [manual debugging guide](https://expo.fyi/manual-debugging) to learn how to isolate the problem from the rest of your codebase.
> 
> #### "I didn't have time to create one"
> That's understandable, it can take some time to prepare. We ask that you hold off on filing an issue until you are able to fully complete the required fields in the issue template.
> 
> #### "You can reproduce it by yourself by creating a project and following these steps"
> This is useful knowledge, but it's still valuable to have the resulting project that is produced from running the steps, where you have verified you can reproduce the issue.

WTF?)

**Comment by DimitrisTzimikas** [comment]
@jarcoder we had the same issue and we downgrade to expo-av: ^13.4.1, this needs to be re-opened.

**Comment by mihailapuste** [comment]
Can we re-open this issue? I am experiencing the same thing on expo 49 with expo-av 13.8. IOS works fine

**Comment by mihailapuste** [comment]
Upgrading to expo 50 alpha 6 worked for me. Using react native 72.7

**Comment by evelant** [comment]
Looks like the last working version of expo-av was around 13.4.1. Any later versions fail to load sounds with `Cannot convert 'null' to a Kotlin type.`

**Comment by Josias1997** [comment]
Any updates on this

**Comment by mubashiralisiddiqui** [comment]
why this issue is closed I am facing the same error
