### ISSUE TITLE
(Android Only) SDK 49 Splash Screen does not dismiss after sending a expo-update

### ISSUE THREAD

**Issue by scottgrunerud** [expo/expo#24972]
### Minimal reproducible example

https://github.com/scottgrunerud/expo-49-updates-methods-not-resolving

### Summary

We recently upgraded to Expo 49 and noticed that on Android, the splash screen will freeze and not dismiss when users download a pending expo update. The only fix is to close the app and open it again and then it will work normally until the next update. We also recently got flooded with a bunch of errors in sentry that read:
```
Call to function 'ExpoSplashScreen.hideAsync' has been rejected.
→ Caused by: The current activity is no longer available
```

In the attached MVP you will see that we `await` the `onFetchUpdateAsync` function this for some reason causes the splash screen to freeze. If we remove the `await` on the `onFetchUpdateAsync` we then have a race condition where the code will execute hide the splash screen -> fetch the update -> reload-> show the splash screen-> then immediately hide the splash screen.

We aren't really sure where to go from here, in reality, the expected behaviour to us would be that the splash screen is only hidden after the update is applied.

## Example 1 (await onFetchUpdateAsync)
1. App launches 
2. Shows splash screen
3. Freezes

[promise-does-not-resolve.webm](https://github.com/expo/expo/assets/95248534/d69aca86-869a-430d-b6d5-3a7daf58e6af)

## Example (no **await** onFetchUpdateAsync - race condition)
1. App launches 
2. Shows splash screen
3. Hide splash screen
4. Reloads 
5. Shows splash screen
6. Hides splash screen

[splash-screen-race-condition.webm](https://github.com/expo/expo/assets/95248534/b87cf840-360f-4fbe-9c5a-34e56f18e379)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/scottgrunerud/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 33
        Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-29 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed

**Comment by douglowder** [comment]
Inspecting your app, it looks like it has the default configuration where the native code checks for updates automatically on launch. Since your app code is also attempting to check for updates and potentially downloading and restarting the app, this could lead to a race condition. We would recommend that your `app.json` "updates" section look like this:

```json
{
  "updates": {
    "checkAutomatically": "ON_ERROR_RECOVERY",
    "url": "https://expo.dev/<etc>"
  }
}
```

See https://docs.expo.dev/versions/latest/sdk/updates/#updatescheckautomaticallyvalue

**Comment by douglowder** [comment]
In SDK 50, we will have a newer Updates JS API that will make it easier to know when a new update is available or downloaded. https://expo.dev/changelog/2023/08-08-use-updates-api

**Comment by hichemfantar** [comment]
Had a similar problem with asset loading. Try removing the use callback on layout root view

**Comment by ahocevar3tav** [comment]
I'm getting the same problem but when I try to restart the app, the difference in logcat is this:

```
2023-10-25 13:36:43.001  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  Callback failure for call to http://192.168.210.222:8081/...
2023-10-25 13:36:43.004  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  java.net.ProtocolException: Expected leading [0-9a-fA-F] character but was 0xd
2023-10-25 13:36:43.005  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:185)
2023-10-25 13:36:43.009  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:42)
2023-10-25 13:36:43.013  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:16)
2023-10-25 13:36:43.016  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at okio.x.read(RealBufferedSource.kt:6)
2023-10-25 13:36:43.017  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at abi49_0_0.com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:187)
2023-10-25 13:36:43.019  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at abi49_0_0.com.facebook.react.devsupport.BundleDownloader.processMultipartResponse(BundleDownloader.java:26)
2023-10-25 13:36:43.024  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at abi49_0_0.com.facebook.react.devsupport.BundleDownloader.access$100(BundleDownloader.java:1)
2023-10-25 13:36:43.027  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at abi49_0_0.com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:76)
2023-10-25 13:36:43.032  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:61)
2023-10-25 13:36:43.037  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023-10-25 13:36:43.039  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023-10-25 13:36:43.041  4487-6666  okhttp.OkHttpClient     host.exp.exponent                    I  	at java.lang.Thread.run(Thread.java:1012)
2023-10-25 13:36:43.119  4487-4496  st.exp.exponent         host.exp.exponent                    I  Background young concurrent copying GC freed 36306(2478KB) AllocSpace objects, 4(208KB) LOS objects, 2% free, 74MB/76MB, paused 4.178ms,435us total 765.760ms
2023-10-25 13:36:43.133  4487-4498  System                  host.exp.exponent                    W  A resource failed to call close. 
```

**Comment by dhruvpvx** [comment]
bun issue https://github.com/oven-sh/bun/issues/6445

**Comment by scottgrunerud** [comment]
> Inspecting your app, it looks like it has the default configuration where the native code checks for updates automatically on launch. Since your app code is also attempting to check for updates and potentially downloading and restarting the app, this could lead to a race condition. If you want to manage downloading and launching updates yourself on startup using the JS API, we would recommend that your `app.json` "updates" section look like this:
> 
> ```json
> {
>   "updates": {
>     "checkAutomatically": "ON_ERROR_RECOVERY",
>     "url": "https://expo.dev/<etc>"
>   }
> }
> ```
> 
> See https://docs.expo.dev/versions/latest/sdk/updates/#updatescheckautomaticallyvalue
> 
> After making the above change, you will need to run `npx expo prebuild` to update the Android manifest with the new value.

Hey Doug thanks for the quick reply, so sorry for the late one from my end we've had an internal hackathon at work so it's been a busy week! Regarding the `ON_ERROR_RECOVERY` option I can confirm this flag is already present in our production codebase and we do run expo prebuild as part of the build process. However, I did add these config options to the demo and noticed something strange, after applying the changes and running `eas build --profile production --local` in the AndroidManifest.xml the `ON_ERROR_RECOVERY` value gets automatically switched to `NEVER`? 

After making the request changes I tried again and both failure cases were still present.
