### ISSUE TITLE
renderRouter testing causes TypeError: Cannot set properties of undefined (setting 'value')

### ISSUE THREAD

**Issue by RobertUpchurch** [expo/expo#25087]
### Minimal reproducible example

https://github.com/RobertUpchurch/expo-router-failed-jest

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have followed the docs at https://docs.expo.dev/router/reference/testing/ in an attempt to get Jest working with expo router and receive the following error every time i use renderRouter.

```
       TypeError: Cannot set properties of undefined (setting 'value')

       6 |   const MockComponent = jest.fn(() => <View />);
       7 |
    >  8 |   renderRouter(
         |               ^
       9 |     {
      10 |       index: MockComponent,
      11 |       "folder/a": MockComponent,

      at renderRouter (node_modules/expo-router/src/testing-library/index.tsx:63:22)
      at Object.<anonymous> (__tests__/expo-router.test.tsx:8:15)
```

I have provided an example repo where i cloned the example tab project from [quick start](https://docs.expo.dev/routing/installation/#quick-start) and then tried my best to follow those docs exactly. This seems to also have been reported a while back in discord with no responses.

https://discord.com/channels/695411232856997968/1156942316582469692/1156942316582469692

To see every single change i made to the example repo you can see this PR on the reproducible example. https://github.com/RobertUpchurch/expo-router-failed-jest/pull/1/files

### Environment

  ```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: managed
```

**Comment by RobertUpchurch** [comment]
closing as its a duplicate of #24786 

Sorry
