### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by pavlea** [expo/expo#25121]
### Command

```
/Users/pavle/.rvm/rubies/ruby-3.2.1/bin/pod install --repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.14.2
        Ruby : ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin22]
    RubyGems : 3.4.6
        Host : macOS 13.2.1 (22D68)
       Xcode : 14.3.1 (14E300c)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /Users/pavle/.rvm/rubies/ruby-3.2.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'StakeMateAlpha' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/pavle/.cocoapods/repos/trunk/Specs/1/1/7/SDWebImage/5.18.2/SDWebImage.podspec.json'.

unexpected token at ''
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification.rb:752:in `from_string'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification.rb:726:in `from_file'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source.rb:188:in `specification'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:362:in `map'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `each'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:422:in `analyze'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:162:in `install!'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/Users/pavle/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/Users/pavle/.rvm/rubies/ruby-3.2.1/bin/pod:25:in `load'
/Users/pavle/.rvm/rubies/ruby-3.2.1/bin/pod:25:in `<main>'
/Users/pavle/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
/Users/pavle/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
```

### What platform(s) does this occur on?

iOS

### SDK Version

49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.14.2 - /Users/pavle/.rvm/rubies/ruby-3.2.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild

### Minimal reproducible example

yarn install
npx expo run:ios

**Comment by brentvatne** [comment]
> JSON::ParserError - Failed to parse JSON at file: '/Users/pavle/.cocoapods/repos/trunk/Specs/1/1/7/SDWebImage/5.18.2/SDWebImage.podspec.json'.

it looks like you may have a corrupt spec cache. https://github.com/CocoaPods/CocoaPods/issues/9814#issuecomment-746812453

**Comment by pavlea** [comment]
> > JSON::ParserError - Failed to parse JSON at file: '/Users/pavle/.cocoapods/repos/trunk/Specs/1/1/7/SDWebImage/5.18.2/SDWebImage.podspec.json'.
> 
> it looks like you may have a corrupt spec cache. [CocoaPods/CocoaPods#9814 (comment)](https://github.com/CocoaPods/CocoaPods/issues/9814#issuecomment-746812453)

thanks, but didn't worked...

**Comment by brentvatne** [comment]
@pavlea - the best place to discuss this further is in the cocoapods repository, we don't control the source of that error message in this repo
