### ISSUE TITLE
jest-expo Results in 'empty-project-emplate' Message

### ISSUE THREAD

**Issue by reggie3** [expo/expo#2515]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

```
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.10.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/reggie3-50636d47-8986-4957-993a-6249b0b64e52.tar.gz
```

Android

### Steps to Reproduce

(Write your steps here:)

1. Install jest npm package
2. Follow steps to install  jest-expo in jest-expo ReadMe file
2. Start project application using expo start 
3. Attempt to run test using  npm test as directected in jest-expo ReadMe file

### Expected Behavior
Expected test to run

(Write what you thought would happen.)

### Actual Behavior
Received the following message:
```
empty-project-template@ test C:\Users\regin\Dropbox\Project 1\mobile
> jest
```

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by KeevanDance** [comment]
I am getting this error with `node_modules/.bin/jest`, but when switching to `"test": "node ./node_modules/jest/bin/jest.js --watchAll"` I am now getting this error:

```javascript
λ npm test

> empty-project-template@ test A:\Documents\Programming\price-earnings-ratio-calulator
> node ./node_modules/jest/bin/jest.js

internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'A:\Documents\Programming\price-earnings-ratio-calulator\node_modules\jest\bin\jest.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by tiagodprovenzano** [comment]
Same problem here

**Comment by davidgithub1980** [comment]
Hi, I have exactly the same problem (Windows 10, **EXPO v31**). _npm test_ just outputs **_> jest_** followed by nothing -> as though no tests are run. How can we remedy? The jest-expo docs look like it is super-easy to run the _Example-test.js_ but it does not work.

**Comment by tiagodprovenzano** [comment]
@davidgithub1980 I couldn't make jest-expo work. I ended up using plain jest instead. It runs with slower performance but I had no problems until now.

**Comment by davidgithub1980** [comment]
Ended up using plain jest as well.

**Comment by osamaq** [comment]
I had the same issue using jest-expo following the tutorial at [jest-expo](https://github.com/expo/expo/tree/master/packages/jest-expo).

Changing the "test" script from `node_modules/.bin/jest` to `node ./node_modules/jest/bin/jest.js` fixed it.

**Comment by Norfeldt** [comment]
This worked for me

>package.json

```
  "scripts": {
    ...
    "test": "node ./node_modules/.bin/jest --watchAll"
  },
  ...
  "devDependencies": {
      ...
    "jest-expo": "^32.0.0"
  },
```
