### ISSUE TITLE
Unable to launch JS debugger when metro-config is installed

### ISSUE THREAD

**Issue by Justin-Singh125125** [expo/expo#25243]
### Summary

I installed `metro-config` at version `0.79.1` in a freshly created Expo app using the command `npx create-expo-app my-app`. I didn't make any customizations to the metro.config.js file; I simply installed the package into the project. However, after the installation, I encountered the following error code when trying to launch the JavaScript debugger:

`FetchError: invalid json response body at http://192.168.1.204:8081/json/list reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at http://192.168.1.204:8081/json/list reason: Unexpected token < in JSON at position 0
    at /Users/justinsingh/Work/fix-devtools/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.queryAllInspectorAppsAsync (/Users/justinsingh/Work/fix-devtools/node_modules/@expo/dev-server/build/JsInspector.js:53:30)
    at async DevServerManagerActions.openJsInspectorAsync (/Users/justinsingh/Work/fix-devtools/node_modules/@expo/cli/build/src/start/interface/interactiveActions.js:94:22)
    at async KeyPressHandler.handleKeypress (/Users/justinsingh/Work/fix-devtools/node_modules/@expo/cli/build/src/start/interface/KeyPressHandler.js:43:17)`

### What platform(s) does this occur on?

Android, iOS

### SDK Version

49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.2
    Expo Workflow: managed

### Minimal reproducible example

// package.json

{
  "name": "fix-devtools",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "metro-config": "^0.79.1"
  },
  "private": true
}

// App.js

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by Justin-Singh125125** [comment]
I fixed this issue by removing two packages, `metro-config` and `@expo/metro-config`, from my project. Expo already includes these dependencies, so when I installed "metro-config" separately, it triggered the error mentioned earlier. If you're still encountering the error even after uninstalling these packages, make sure to delete your "package-lock.json" file and clear your "node_modules" directory.
