### ISSUE TITLE
PKCS#12 MAC could not be verified. Invalid password? When running expo build:ios

### ISSUE THREAD

**Issue by virus2016** [expo/expo#2564]
Hi there,

I delete my certificates around 2 times as my CI server wasn't accepting them. I successfully completed that however, I have tried to create a third time and I get the error below.

Hopefully you can help me.

### Environment

```
[03:00:28] Generating diagnostics report...
[03:00:28] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS 10.14
  Node: 8.12.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  expo: ^29.0.1 => 29.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/healthyapp-2e1af163-00c6-43ff-819e-21f286695b56.tar.gz
```

### Steps to Reproduce

```npx exp build:ios -c
We've built a brand new CLI for Expo!
Expo CLI is a drop in replacement for exp.
Install: npm install -g expo-cli
Use: expo --help
Read more: https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c
[02:51:00] Checking if current build exists...

[02:51:00] No currently active or previous builds for this project.
[02:51:01] Removed existing credentials from expo servers
? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? ****i@medayo.co.uk
? Password? [hidden]
[02:51:15] Validating Credentials...
[02:51:18] Only 1 team associated with your account, using Team ID: *******
? Will you provide your own Distribution Certificate? Let Expo handle the process
? Will you provide your own Push Certificate? Let Expo handle the process
[02:51:23] Error while gathering & validating credentials
[02:51:23] PKCS#12 MAC could not be verified. Invalid password?
[02:51:23] Error: PKCS#12 MAC could not be verified. Invalid password?
    at Object.p12.pkcs12FromAsn1 (/Users/macbuild1/Documents/mobileapp/node_modules/node-forge/lib/pkcs12.js:475:13)
    at _getCertData (/xdl@51.3.1/src/detach/IosCodeSigning.js:50:28)
    at Object.findP12CertSerialNumber (/xdl@51.3.1/src/detach/IosCodeSigning.js:35:20)
    at /xdl@51.3.1/src/Credentials.js:138:26
    at Array.map (<anonymous>)
    at Object.<anonymous> (/xdl@51.3.1/src/Credentials.js:135:16)
    at Generator.next (<anonymous>)
    at step (/Users/macbuild1/Documents/mobileapp/node_modules/xdl/build/Credentials.js:206:191)
    at /Users/macbuild1/Documents/mobileapp/node_modules/xdl/build/Credentials.js:206:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Expected Behavior

Create iOS certs for distribution.  

### Actual Behavior

Does not create any certificates.

**Comment by virus2016** [comment]
Just tried it on another Macbook and a Ubuntu clean docker image. Looks like the same issue: 

```
? Will you provide your own Distribution Certificate? Let Expo handle the process
? Will you provide your own Push Certificate? Let Expo handle the process
[03:38:14] Error while gathering & validating credentials
[03:38:14] Error: PKCS#12 MAC could not be verified. Invalid password?
[03:38:14] PKCS#12 MAC could not be verified. Invalid password?
[03:38:14] Error: PKCS#12 MAC could not be verified. Invalid password?
    at Object.p12.pkcs12FromAsn1 (/home/mobileapp/node_modules/node-forge/lib/pkcs12.js:475:13)
    at _getCertData (/xdl@51.4.5/src/detach/IosCodeSigning.js:50:28)
    at Object.findP12CertSerialNumber (/xdl@51.4.5/src/detach/IosCodeSigning.js:35:20)
    at /xdl@51.4.5/src/Credentials.js:138:26
    at Array.map (<anonymous>)
    at Object.<anonymous> (/xdl@51.4.5/src/Credentials.js:135:16)
    at Generator.next (<anonymous>)
    at step (/home/mobileapp/node_modules/xdl/build/Credentials.js:206:191)
    at /home/mobileapp/node_modules/xdl/build/Credentials.js:206:361
    at <anonymous>
```

**Comment by virus2016** [comment]
Workaround is to manually create distribution certificate.

**Comment by jakubste** [comment]
Hi,
1/ You're using `exp` which is deprecated (which you could read at the very beginning of logs you pasted). Please update to newest version of `expo-cli`
2/ If the issue persists with `expo-cli` please open a ticket at https://github.com/expo/expo-cli repository
3/ You can try also changing your apple password, if you have, in any way, odd one.
For now, I'm closing this issue, especially because it's in the wrong repository :)

**Comment by virus2016** [comment]
@jakubste tried with expo-cli, same issue.
