### ISSUE TITLE
`npx pod-install` suppresses console errors from `pod-install`

### ISSUE THREAD

**Issue by navignaw** [expo/expo#26102]
### Summary

Edit: after some additional debugging, it looks like `npx pod-install` is suppressing helpful stdout/stderr messages from `pod install`, even without verbose mode. Rather than forwarding `verbose` mode, I think it would be beneficial to just pipe all of the output from `pod install` to the output of `npx pod-install`.

Original issue below:

---

When debugging issues with `pod install`, it is often helpful to add the `--verbose` flag so that it will print out a full stack trace. However, it doesn't seem like `npx pod-install` supports passing this flag.

This is especially handy because `pod install` can fail for thousands of unrelated reasons (examples: [bad Ruby version](https://github.com/expo/expo/issues/20707), [extra console output](https://stackoverflow.com/a/74065592), [extra console.debug in app.config.ts](https://forums.expo.dev/t/eas-build-failing-with-expo-router-v2-and-expo-sdk-49/72962/5)), yet searching through these error messages without verbose mode is a nightmare because they all have the same error message.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2023.10.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Reproducible demo or steps to reproduce from a blank project

Construct a failing `app.config.ts` file, for example one that looks like this:
```ts
throw new Error('oh no!')
export default ({ config }) => config
```

Run `npx pod-install --verbose` and see this output:

```
❯ npx pod-install
Scanning for pods...
1.12.1
> pod install

[!] Invalid `Podfile` file: Couldn't parse JSON coming from `expo-modules-autolinking` command:
unexpected token at ''.

 #  from /REPO_PATH/ios/Podfile:45
 #  -------------------------------------------
 #  target 'ZiplineDevelopment' do
 >    use_expo_modules!
 #    config = use_native_modules!
 #  -------------------------------------------
```

Now run `pod install --verbose` and see this output, with an expected stack trace:

```
❯ pod install --verbose
  $ /usr/local/bin/node -p require.resolve(     "@react-native-community/cli-platform-ios/native_modules.rb",     {paths: [process.argv[1]]},   )
  REPO_PATH/node_modules/react-native/scripts
  REPO_PATH/node_modules/@react-native-community/cli-platform-ios/native_modules.rb
  REPO_PATH/app.config.ts:5
throw new Error('oh no!')
      ^

Error: Error reading Expo config at REPO_PATH/app.config.ts:

test
    at Object.<anonymous> (REPO_PATH/app.config.ts:5:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at requireFromString (REPO_PATH/node_modules/require-from-string/index.js:28:4)
    at evalConfig (REPO_PATH/node_modules/@expo/config/build/evalConfig.js:61:47)
    at readConfigFile (REPO_PATH/node_modules/@expo/config/build/getConfig.js:45:41)
    at getDynamicConfig (REPO_PATH/node_modules/@expo/config/build/getConfig.js:54:18)
    at getConfig (REPO_PATH/node_modules/@expo/config/build/Config.js:259:43)
    at getBuildPropertiesAsync (REPO_PATH/node_modules/expo-modules-autolinking/build/autolinking/extraDependencies.js:15:58)
    at resolveExtraDependenciesAsync (REPO_PATH/node_modules/expo-modules-autolinking/build/autolinking/extraDependencies.js:24:30)
    at /REPO_PATH/node_modules/expo-modules-autolinking/build/index.js:63:95 {
  isConfigError: true
}

[!] Invalid `Podfile` file: Couldn't parse JSON coming from `expo-modules-autolinking` command:
unexpected token at ''.

 #  from /REPO_PATH/ios/Podfile:45
 #  -------------------------------------------
 #  target 'ZiplineDevelopment' do
 >    use_expo_modules!
 #    config = use_native_modules!
 #  -------------------------------------------
```

**Comment by navignaw** [comment]
Started a draft in #27828, would appreciate some help in testing/validation!

**Comment by navignaw** [comment]
As mentioned above I have a draft PR to fix this. Would appreciate if someone could take a look!
