### ISSUE TITLE
expo-modules-core android Build error

### ISSUE THREAD

**Issue by HuseyinOzler** [expo/expo#26389]
Android Build Error

### Summary

huseyinozler@Huseyins-MacBook-Prolcn env % npx expo run:android         
› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/huseyinozler/Desktop/nest/env/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 356

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > Failed to notify project evaluation listener.
      > No enum constant org.jetbrains.kotlin.gradle.plugin.PropertiesProvider.JvmTargetValidationMode.WARNİNG
      > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 3s
5 actionable tasks: 5 up-to-date
Error: /Users/huseyinozler/Desktop/nest/env/android/gradlew exited with non-zero code: 1
Error: /Users/huseyinozler/Desktop/nest/env/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/huseyinozler/Desktop/nest/env/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (/Users/huseyinozler/Desktop/nest/env/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/Users/huseyinozler/Desktop/nest/env/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/Users/huseyinozler/Desktop/nest/env/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/Users/huseyinozler/Desktop/nest/env/node_modules/@expo/cli/b
![Ekran Resmi 2024-01-13 01 38 27](https://github.com/expo/expo/assets/43011441/e25a05de-2136-41d8-8914-6c5f7be16d5b)
uild/src/run/android/runAndroidAsync.js:36:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
huseyinozler@Huseyins-MacBook-Prolcn env % 

I downloaded the project and bought a prebuild directly, then when I want to build as Android, I get this error.

**Comment by HuseyinOzler** [comment]
classpath( "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0")

I added it and it worked

**Comment by Kudo** [comment]
hi there! it doesn't look correct when `kotlin-gradle-plugin` to cause the problem from `autolinking_implementation.gradle`.  could you share the repro with us for further troubleshooting?

**Comment by clydee-geng** [comment]
classpath( "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0")
Adding this sentence doesn't work either
