### ISSUE TITLE
Production Release Crash on Startup since 

### ISSUE THREAD

**Issue by Chrissi2812** [expo/expo#26494]
### Summary

Newly build apps with react-native-reanimated crash on launch on Android (iOS not tested so far)
I have created 2 Builds of exactly the same App on two different Dates:
- 21.12.2023: App just works fine 
[Link to Build](https://expo.dev/accounts/pixel-kraft/projects/commulino-dbh/builds/086f5ea2-62f1-4730-ac84-a226c63d3a2c)
[gradlelog_working.txt](https://github.com/expo/expo/files/13976963/gradlelog_working.txt)

- 18.01.2023: App crashes after splash screen 
[Link to Build](https://expo.dev/accounts/pixel-kraft/projects/commulino-dbh/builds/32f692a0-a34d-4be8-8b5d-7769268857c8) 
[gradlelog_broken.txt](https://github.com/expo/expo/files/13976967/gradlelog_broken.txt)

The only difference seems to be in the gradle output of both runs. 

I include both crashlogs for the minimal repo and for my app:
- [min_repro_crash.log](https://github.com/expo/expo/files/13977058/min_repro_crash.log)
- [production_app_crash.log](https://github.com/expo/expo/files/13977060/production_app_crash.log)

### SDK Version

49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22631
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7
      babel-preset-expo: ^9.5.0 => 9.5.2
      expo: ^49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/Chrissi2812/expo-issue-repro/tree/crash/reanimated-minimal

**Comment by ngondat97** [comment]
same issue

**Comment by alucardeht** [comment]
Same here, debugging using logcat and seems some problem with RNSVG in my case

**Comment by alucardeht** [comment]
I tried to find the problem and I didn't find it, I tried to solve it several times but with no solution, it ended up that updating to SDK 50 solved it and it started working normally again, but it caused a headache to update

**Comment by Kudo** [comment]
hi there! i tried to run [your app](https://expo.dev/accounts/pixel-kraft/projects/commulino-dbh/builds/32f692a0-a34d-4be8-8b5d-7769268857c8) and seen the crash log. it looks different to the minimal repro crash.
```
           UpdatesUtils  E  Failed to parse date string on first try: 2024-01-11T15:53:42.691Z
                         E  java.text.ParseException: Unparseable date: "2024-01-11T15:53:42.691Z"
                         E      at java.text.DateFormat.parse(DateFormat.java:389)
                         E      at expo.modules.updates.UpdatesUtils.parseDateString(UpdatesUtils.kt:282)
                         E      at expo.modules.updates.manifest.NewUpdateManifest$Companion.fromNewManifest(NewUpdateManifest.kt:102)
                         E      at expo.modules.updates.manifest.ManifestFactory.getManifest(ManifestFactory.kt:23)
                         E      at expo.modules.updates.loader.FileDownloader$Companion.checkCodeSigningAndCreateManifest(FileDownloader.kt:692)
                         E      at expo.modules.updates.loader.FileDownloader$Companion.access$checkCodeSigningAndCreateManifest(FileDownloader.kt:627)
                         E      at expo.modules.updates.loader.FileDownloader.parseManifest(FileDownloader.kt:494)
                         E      at expo.modules.updates.loader.FileDownloader.parseMultipartRemoteUpdateResponse(FileDownloader.kt:330)
                         E      at expo.modules.updates.loader.FileDownloader.parseRemoteUpdateResponse$expo_updates_release(FileDownloader.kt:149)
                         E      at expo.modules.updates.loader.FileDownloader$downloadRemoteUpdate$1.onResponse(FileDownloader.kt:548)
                         E      at expo.modules.updates.loader.FileDownloader$downloadData$1.onResponse(FileDownloader.kt:622)
                         E      at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                         E      at java.lang.Thread.run(Thread.java:1012)
```

we had a relevant fix from https://github.com/expo/expo/pull/24951 and published `expo-updates@0.18.17` previously. could you try to upgrade the expo-updates package to the latest sdk 49 version `expo-updates@0.18.19` and see whether it works for you?

**Comment by Chrissi2812** [comment]
I finally got the App working again. 
I have updated theses dependencies:
```
expo-file-system         15.4.4 -> 15.4.5
expo-screen-orientation   6.0.5 -> 6.0.6
expo-updates            0.18.16 -> 0.18.19
react-native-ui-lib      6.31.0 -> 7.15.0
sentry-expo               7.0.1 -> 7.1.1
```

I had to update react-native-ui-lib because of this error https://github.com/wix/react-native-ui-lib/issues/2875. That Issue also affects Expo SDK 50.

But I don't understand why my build with the exact same dependencies was working on 21th December and then no longer worked in January.
Was something changed on the EAS Servers? Where can we see a changelog for them?
Does the EAS server respect the package-lock.json? 
Or how is it possible that two identical build result in different output on different dates?
It was really difficult to find the cause of this issue because of this...

**Comment by Kudo** [comment]
since it's expo-updates related, could it because you published eas updates in between?

**Comment by Chrissi2812** [comment]
I only used the App I mentioned as an example because it was the last one that I built that worked. And to proof my point that it's not related to changes made in my code. But something else must have changed. See Below.. 

I tried to publish a similar App this year and the problems started. No expo-updates were involved at that time. It was a new App. 
https://expo.dev/accounts/pixel-kraft/projects/commulino-petrieichen/builds/1928d7c3-d323-4fd7-9dfd-51857593467f

----------

### More findings with apktool


I expected that If i push exactly the same code to the EAS Servers that exactly the same result would come out. 
But this is not the case it seems. (The index.android.bundle is exactly the same but some via apktool i found some differences in the MainApplication.smali)

| Build | Date | Working? |
|--------|--------|:--------:|
| 5904 | Dec.2023 | ✅ |
| 5905 | Jan.2024 | ❌ | 

```
Files 5904/assets/app.config and 5905/assets/app.config differ
Files 5904/assets/app.manifest and 5905/assets/app.manifest differ
Files 5904/assets/dexopt/baseline.prof and 5905/assets/dexopt/baseline.prof differ
Files 5904/assets/dexopt/baseline.profm and 5905/assets/dexopt/baseline.profm differ
Files 5904/original/AndroidManifest.xml and 5905/original/AndroidManifest.xml differ
Files 5904/original/META-INF/BNDLTOOL.RSA and 5905/original/META-INF/BNDLTOOL.RSA differ
Files 5904/original/META-INF/BNDLTOOL.SF and 5905/original/META-INF/BNDLTOOL.SF differ
Files 5904/original/META-INF/MANIFEST.MF and 5905/original/META-INF/MANIFEST.MF differ
Files 5904/smali_classes2/com/example/test/BuildConfig.smali and 5905/smali_classes2/com/example/test/BuildConfig.smali differ
Files 5904/smali_classes2/com/example/test/MainApplication.smali and 5905/smali_classes2/com/example/test/MainApplication.smali differ
```

```patch
--- 5904/smali_classes2/com/example/test/MainApplication.smali  2024-01-23 14:53:15.435084700 +0100
+++ 5905/smali_classes2/com/example/test/MainApplication.smali  2024-01-23 14:55:25.271807300 +0100
@@ -45,10 +45,10 @@
 .method public onConfigurationChanged(Landroid/content/res/Configuration;)V
     .locals 0

-    .line 77
+    .line 79
     invoke-super {p0, p1}, Landroid/app/Application;->onConfigurationChanged(Landroid/content/res/Configuration;)V

-    .line 78
+    .line 80
     invoke-static {p0, p1}, Lexpo/modules/ApplicationLifecycleDispatcher;->onConfigurationChanged(Landroid/app/Application;Landroid/content/res/Configuration;)V

     return-void
@@ -65,18 +65,7 @@
     .line 63
     invoke-static {p0, v0}, Lcom/facebook/soloader/SoLoader;->init(Landroid/content/Context;Z)V

-    .line 71
-    invoke-virtual {p0}, Lcom/example/test/MainApplication;->getReactNativeHost()Lcom/facebook/react/ReactNativeHost;
-
-    move-result-object v0
-
-    invoke-virtual {v0}, Lcom/facebook/react/ReactNativeHost;->getReactInstanceManager()Lcom/facebook/react/ReactInstanceManager;
-
-    move-result-object v0
-
-    invoke-static {p0, v0}, Lcom/example/test/ReactNativeFlipper;->initializeFlipper(Landroid/content/Context;Lcom/facebook/react/ReactInstanceManager;)V
-
-    .line 72
+    .line 74
     invoke-static {p0}, Lexpo/modules/ApplicationLifecycleDispatcher;->onApplicationCreate(Landroid/app/Application;)V

     return-void
```

**Comment by Kudo** [comment]
that is a great investigation 👏  the relevant change is also from me at https://github.com/expo/expo/pull/26120. it's strange that changing the bridge initialization flow would cause the `Failed to parse date string on first try: 2024-01-11T15:53:42.691Z` issue, but originally it does not happen to you.

fwiw, eas build will respect your **package-lock.json**. this case is slightly different. it's from template changes. when running `npx expo prebuild` on eas build, it will pull the latest `expo-template-bare-minimum` from npm.

**Comment by Chrissi2812** [comment]
Yes I had multiple error messages that happened.  And I tried to pinpoint it down. But I think the related error for me was caused by react-native-ui-lib. Because even after updating expo-updates and all other expo packages to the latest. 
The app would still crash with this error:

```
-23 11:13:59.768  1471  1586 D ScreenCurtainController: onForegroundActivitiesChanged: com.example.test
01-23 11:13:59.899  1471  1883 D MdnieScenarioControlService:  packageName : com.example.test    className : com.example.test.MainActivity
--------- beginning of crash
01-23 11:13:59.939  1411  1477 E AndroidRuntime: FATAL EXCEPTION: expo-updates-error-recovery
01-23 11:13:59.939  1411  1477 E AndroidRuntime: Process: com.example.test, PID: 1411
01-23 11:13:59.939  1411  1477 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.getDecorView()' on a null object reference
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.wix.reactnativeuilib.keyboardinput.ReactScreenMonitor.registerWindowLayoutListener(ReactScreenMonitor.java:65)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.wix.reactnativeuilib.keyboardinput.ReactScreenMonitor.onHostResume(ReactScreenMonitor.java:51)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:308)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:778)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:813)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.-$$Nest$mmoveReactContextToCurrentLifecycleState(Unknown Source:0)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$6.run(ReactInstanceManager.java:1202)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
01-23 11:13:59.939  1411  1477 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
01-23 11:13:59.942  1471  3777 W ActivityTaskManager:   Force finishing activity com.example.test/.MainActivity
01-23 11:13:59.943  1471  1545 W ActivityManager: crash : com.example.test,10013
```

Thanks for clarifying how `eas build` handles that. Would be great to be able to pin `expo-template-bare-minimum` in `eas.json` at least for testing purposes.

**Comment by Kudo** [comment]
> Would be great to be able to pin expo-template-bare-minimum in eas.json at least for testing purposes.

not a normal usage but you can [customize the prebuildCommand in eas.json](https://docs.expo.dev/eas/json/#prebuildcommand). the `npx expo prebuild --template /path/to/template.tgz` is something you can try. on the latest sdk 50, you can even use a github url like `npx expo --template https://github.com/expo/expo/tree/30072b9637f0d2b964fe7f47f99f0e369336913a/templates/expo-template-bare-minimum`.
hope this information helps!

**Comment by Kudo** [comment]
since the root cause was revolved by #24951 already, i'm closing issue. let me know if you still have other questions. thank you!

**Comment by glundgrenm** [comment]
As an info if someone is having this issue, i can confirm it was caused by react-native-ui-lib, just removed if from project and the android build didn't crashed.
