### ISSUE TITLE
[SDK 50] firebase/compat Error

### ISSUE THREAD

**Issue by Chrissi2812** [expo/expo#26522]
### Minimal reproducible example

https://github.com/Chrissi2812/expo-issue-repro/tree/error/sdk50-firebase

### Summary

Using `firebase/firestore` in compat mode does trigger an error.

```
 ERROR  [2024-01-19T14:07:50.126Z]  @firebase/firestore: Firestore (10.7.2): INTERNAL UNHANDLED ERROR:  TypeError: Cannot read property 'includes' of undefined
    at isSafari (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:137899:53)
    at __PRIVATE_getDefaultRelativeIndexReadCostPerDocument (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:158452:35)    
    at __PRIVATE_QueryEngine (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:158453:8)
    at createLocalStore (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:163947:83)
    at ?anon_0_ (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:163927:256)
    at next (native)
    at asyncGeneratorStep (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:7269:26)
    at _next (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:7288:29)
    at tryCallOne (/home/expo/workingdir/build/react-native-lab/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6q1z5s36/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/home/expo/workingdir/build/react-native-lab/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6q1z5s36/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:46872:26)
    at _callTimer (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:46751:17)
    at _callReactNativeMicrotasksPass (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:46796:17)
    at callReactNativeMicrotasks (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:47002:44)
    at __callReactNativeMicrotasks (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:9343:48)
    at anonymous (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:9116:45)
    at __guard (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:9315:15)
    at flushedQueue (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:9115:21)
    at callFunctionReturnFlushedQueue (http://192.168.188.178:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app:9100:33)
 ERROR  [2024-01-19T14:08:27.261Z]  @firebase/firestore: Firestore (10.7.2): FIRESTORE (10.7.2) INTERNAL ASSERTION FAILED: Unexpected state
 ERROR  Error: FIRESTORE (10.7.2) INTERNAL ASSERTION FAILED: Unexpected state, js engine: hermes
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.12.1 - ~\AppData\Roaming\npm\npm.CMD
    npmPackages:
      expo: ^50.0.1 => 50.0.1
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: managed

**Comment by brentvatne** [comment]
this looks like a bug in firestore. please create an issue on the firebase repository

**Comment by monsieurnebo** [comment]
Same issue over here.

**Comment by goxr3plus** [comment]
Oh gosh i had this bug today too ....

**Comment by Eliyasulimani** [comment]
Just having it

**Comment by CodeOfDutySE** [comment]
literally just having this problem right now

**Comment by parallex12** [comment]
anyone solved it yet, i am stuck with dozens of projects due to this issue, none of my project works after update for firestore.

**Comment by monsieurnebo** [comment]
The workaround has been shared a few post [upper](https://github.com/expo/expo/issues/26522#issuecomment-1902547646).

**Comment by mamadouD29** [comment]
did anybody find the solution ?

**Comment by SevostyanovAleksandr** [comment]
Здесь та же проблема.

Это регрессия firebase-js-sdk версии 10.7.2.

В настоящее время ведется работа над исправлением, но откат до версии 10.7.1 тем временем сделает свое дело.

Связано с https://github.com/firebase/firebase-js-sdk/issues/7962

Но мне не помогло

**Comment by mamadouD29** [comment]
@SevostyanovAleksandr I rolled back to 10.7.1
here is what I actually did to fix it when I rolled back.

1. Stopped my expo project
2. In my package.json  I removed the "firebase": "^10.7.2" line
3. I deleted the package-lock.json and node_modules
3. I install firebase 10.7.1 : npm install firebase@10.7.1 , it will install all your node_modules and package-lock.json
4. I started my project and all work pretty good like nothing happened

Give a try and let me know

**Comment by GiauLee** [comment]
> @SevostyanovAleksandr I rolled back to 10.7.1 here is what I actually did to fix it when I rolled back.
> 
> 1. Stopped my expo project
> 2. In my package.json  I removed the "firebase": "^10.7.2" line
> 3. I deleted the package-lock.json and node_modules
> 4. I install firebase 10.7.1 : npm install firebase@10.7.1 , it will install all your node_modules and package-lock.json
> 5. I started my project and all work pretty good like nothing happened
> 
> Give a try and let me know



-- Thank you very much, I fixed it!!! --

**Comment by parallex12** [comment]
SOLVED.
rm -rf node_modules
rm -rf package-lock.json
npm install 
npm install expo@latest
npm install --check 
npm install firebase@10.7.1

tried this in several project and it worked.
