### ISSUE TITLE
PluginError: Package "expo-font" does not contain a valid config plugin.

### ISSUE THREAD

**Issue by szmarczak** [expo/expo#26551]
### Minimal reproducible example

https://snack.expo.dev/@szmarczak/crabby-red-marshmallows

### Summary

Minimal reproducible example is just a link to default snack project so this issue doesn't get closed automatically.

---

```
> npm run start -- --android

> the-trolley-app@1.0.0 start
> expo start --android

Starting project at C:\Users\szmar\Desktop\the-trolley-app
PluginError: Package "expo-font" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token 'export'
C:\Users\szmar\Desktop\the-trolley-app\node_modules\expo-font\build\index.js:1
export * from './Font';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1175:20)
    at Module._compile (node:internal/modules/cjs/loader:1219:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at requirePluginFile (C:\Users\szmar\Desktop\the-trolley-app\node_modules\@expo\config-plugins\build\utils\plugin-resolver.js:214:12)
    at resolveConfigPluginFunctionWithInfo (C:\Users\szmar\Desktop\the-trolley-app\node_modules\@expo\config-plugins\build\utils\plugin-resolver.js:155:14)
```

### Environment

```
> npx expo-env-info
Need to install the following packages:
  expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.9 => 0.72.9 
    Expo Workflow: bare
```

```js
"expo": "49.0.8",
"expo-font": "11.4.0",
```

**Comment by rhh4x0r** [comment]
Getting the same error here.

**Comment by rhh4x0r** [comment]
I updated expo-font to the latest version (npm didn't default add the latest) and that fixed that error for me.

**Comment by mzaien** [comment]
> (npm d

What version exactlly?

**Comment by nunathanw** [comment]
Which version did you download? npx expo install expo-font@latest still causes an error for me

**Comment by c2tarun** [comment]
> I updated expo-font to the latest version (npm didn't default add the latest) and that fixed that error for me.

@rhh4x0r would really appreciate if you can please share the version which fixed this for you? I am also running into same issue.

**Comment by hind-sagar-biswas** [comment]
I am also having the similar issue,

```cli
$> npx expo start
Starting project at F:\WebNProg\React\PeriodicTableQuiz
PluginError: Package "expo-font" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token 'export'
F:\WebNProg\React\PeriodicTableQuiz\node_modules\expo-font\build\index.js:1
export * from './Font';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at requirePluginFile (F:\WebNProg\React\PeriodicTableQuiz\node_modules\@expo\config-plugins\build\utils\plugin-resolver.js:214:12)
    at resolveConfigPluginFunctionWithInfo (F:\WebNProg\React\PeriodicTableQuiz\node_modules\@expo\config-plugins\build\utils\plugin-resolver.js:155:14)
```

**Comment by rhh4x0r** [comment]
"expo": "50.0.2"
  "expo-font": "~11.10.2",

**Comment by wodin** [comment]
1. Run `npx expo install --fix` to ensure you are using a version of `expo-font` compatible with your version of the Expo SDK.

2. You can only use the `expo-font` config plugin from Expo SDK 50. It won't work in Expo SDK 49

**Comment by Kudo** [comment]
hi there! it looks like `"expo": "49.0.8"` with `"expo-font": "11.4.0"` is a correct setup for sdk 49, but it's strange make sense for me that `expo-font@11.4.0` doesn't have any config-plugins. would be great if you could provide a minimal repro for further troubleshooting.

**Comment by squidis** [comment]
Hi, I was getting this error along with this one involving wrap-ansi #26459 when trying to upgrade to the latest expo. I tried ditching yarn v1 and using npm and both errors disappeared. Hope that helps!

**Comment by helloiambguedes** [comment]
I'm on expo `~49.0.18` and also having the same issue.

**Comment by trooms** [comment]
Getting similar that won't even let me run expo-doctor:
```
/node_modules/expo-font/build/index.js:1
export * from './Font';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1290:20)
    at Module._compile (node:internal/modules/cjs/loader:1342:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at requirePluginFile (.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:17:438899)
    at resolveConfigPluginFunctionWithInfo (.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:17:437772) {
  name: 'PluginError',
  isPluginError: true,
  code: 'INVALID_PLUGIN_IMPORT',
  cause: undefined
}

Node.js v21.6.1
```
Using Expo 49.0.0 and expo-font 11.4.0.

Had "expo-font": "~11.10.2" before in my package.json, but was getting 
```
fontFamily "Inter" is not a system font and has not been loaded through Font.loadAsync.
```

So tried npx expo install expo-font@latest as recommended above (which resulted in the first error above)

**Comment by MusabMahmoodh** [comment]
I used 
`    
   "expo": "^49.0.0",
    ....,
    "expo-font": "~11.4.0",
    `
    
![image](https://github.com/expo/expo/assets/43021789/92d8e096-caf8-4081-8c12-92e3d6acfec7)
Problem solved for me
