### ISSUE TITLE
[regression] Expo Go 2.30.8 (SDK50) Android Crash When Running SDK49 project

### ISSUE THREAD

**Issue by rogalski** [expo/expo#26561]
### Minimal reproducible example

WIP

### Summary

Expo Go: 2.30.8, Android
Prev version: unknown, but before SDK50 release.

The crash happens when `react-native-image-viewing` fullscreen view is open - I am working on MCVE. Nevertheless, since it's clear regression (as I am opening project update pushed to Expo before App Store update of Expo Go) IMHO it's still beneficial to report it as it is.

From sources - `Animated.Image` is used under the hood: https://github.com/jobtoday/react-native-image-viewing/blob/master/src/components/ImageItem/ImageItem.android.tsx

```
FATAL EXCEPTION: FrescoDecodeExecutor-6
Process: host.exp.exponent, PID: 22883
java.lang.IncompatibleClassChangeError: Found interface com.facebook.imagepipeline.image.CloseableImage, but class was expected (declaration of 'com.facebook.imagepipeline.image.CloseableImage' appears in base.apk!classes2.dex)
	at abi49_0_0.com.facebook.react.modules.image.ImageLoaderModule$2.onNewResultImpl(SourceFile:30)
	at com.facebook.datasource.BaseDataSubscriber.onNewResult(SourceFile:5)
	at com.facebook.datasource.AbstractDataSource$1.run(SourceFile:29)
	at com.facebook.common.executors.CallerThreadExecutor.execute(SourceFile:1)
	at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(SourceFile:18)
	at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(SourceFile:35)
	at com.facebook.datasource.AbstractDataSource.setResult(SourceFile:3)
	at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onNewResultImpl(SourceFile:14)
	at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(SourceFile:2)
	at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(SourceFile:1)
	at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$createConsumer$1.onNewResultImpl(SourceFile:7)
	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:14)
	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(SourceFile:134)
	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(SourceFile:4)
	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(SourceFile:1)
	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:14)
	at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(SourceFile:25)
	at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(SourceFile:1)
	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:14)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleResult(SourceFile:22)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(SourceFile:248)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder._init_$lambda$2(SourceFile:120)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.a(SourceFile:1)
	at com.facebook.imagepipeline.producers.a.run(SourceFile:1)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(SourceFile:31)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(SourceFile:1)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(SourceFile:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(SourceFile:16)
	at com.facebook.imagepipeline.core.PriorityThreadFactory.a(SourceFile:1)
	at com.facebook.imagepipeline.core.a.run(SourceFile:1)
	at java.lang.Thread.run(Thread.java:1012)
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7
      expo: ^49.0.7 => 49.0.18
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: bare

**Comment by rogalski** [comment]
Question to the maintainers - what is the recommended approach to downgrade Expo Go?
Is there any server where old APKs can be downloaded?

This will help immensely with verifying MCVE.

**Comment by alanjhughes** [comment]
Hi - this library is not maintained or supported by expo. I suggest opening an issue on their repo.

**Comment by brentvatne** [comment]
@rogalski - you can install an old version of expo go by staring an sdk 49 project and launching it - https://docs.expo.dev/get-started/expo-go/#how-can-i-install-an-older-version

cc @amandeepmittal - perhaps we should list old versions of expo go somewhere? maybe on https://expo.dev/tools

**Comment by wodin** [comment]
> maybe on https://expo.dev/tools

Or /client?

**Comment by brentvatne** [comment]
this should be resolved in the latest version of expo go

**Comment by rogalski** [comment]
Thank you @brentvatne
