### ISSUE TITLE
Expo Go 2.30.8 crashes when using `Image.getSize()` from react-native

### ISSUE THREAD

**Issue by RBrNx** [expo/expo#26617]
### Minimal reproducible example

https://snack.expo.dev/uUNkLxofgJ2oUOYg0Zld8

### Summary

I've been developing an app using Expo SDK49 for a few months now, everything has been working smoothly - until this evening when my Expo Go updated to v2.30.8 which includes support for SDK50. I'm still running SDK49 but now when I make any call to Image.getSize() from the react-native package, Expo Go crashes instantly are there are no error logs.

[This snack](https://snack.expo.dev/uUNkLxofgJ2oUOYg0Zld8) will crash when using 2.30.8 on Android, but installing version 2.29.8 of Expo Go by using the `-a` flag to start the bundler works fine.

Using adb logcat -e "host.exp.exponent" I was able to retrieve the logs below 
```
01-22 18:34:42.489 30663  4665 E AndroidRuntime: FATAL EXCEPTION: FrescoDecodeExecutor-4
01-22 18:34:42.489 30663  4665 E AndroidRuntime: Process: host.exp.exponent, PID: 30663
01-22 18:34:42.489 30663  4665 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Found interface com.facebook.imagepipeline.image.CloseableImage, but class was expected (declaration of 'com.facebook.imagepipeline.image.CloseableImage' appears in /data/app/~~MDV6EtjjFVkE4oVrDUZwWA==/host.exp.exponent-3wXcgDw7YyvNT2zuo-lo8w==/base.apk!classes2.dex)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at abi49_0_0.com.facebook.react.modules.image.ImageLoaderModule$1.onNewResultImpl(SourceFile:30)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.datasource.BaseDataSubscriber.onNewResult(SourceFile:5)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.datasource.AbstractDataSource$1.run(SourceFile:29)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.common.executors.CallerThreadExecutor.execute(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(SourceFile:18)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(SourceFile:35)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.datasource.AbstractDataSource.setResult(SourceFile:3)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onNewResultImpl(SourceFile:14)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(SourceFile:2)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$createConsumer$1.onNewResultImpl(SourceFile:7)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:14)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(SourceFile:134)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(SourceFile:4)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:14)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(SourceFile:25)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:14)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleResult(SourceFile:22)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(SourceFile:248)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder._init_$lambda$2(SourceFile:120)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.a(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.a.run(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.JobScheduler.doJob(SourceFile:31)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.JobScheduler.access$000(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.producers.JobScheduler$1.run(SourceFile:3)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(SourceFile:16)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.core.PriorityThreadFactory.a(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at com.facebook.imagepipeline.core.a.run(SourceFile:1)
01-22 18:34:42.489 30663  4665 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
01-22 18:34:42.563  2755  4674 W ActivityManager: crash : host.exp.exponent,10530
```

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.16 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    Expo Workflow: managed
 ```

**Comment by Kudo** [comment]
hi there! this is duplicated as #26561 and will be resolved by #26624. i'm closing this one, let's track the problem on #26561. thanks for shaing the problem.
