### ISSUE TITLE
Attempt to invoke interface method 'void fd.b.b(android.content.Context, fd.b$a, java.lang.Runnable, md.f)' on a null object reference

### ISSUE THREAD

**Issue by Invictus-Munish** [expo/expo#26627]
### Minimal reproducible example

[code.txt](https://github.com/expo/expo/files/14024133/code.txt)

### Summary

Fatal Exception: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void fd.b.b(android.content.Context, fd.b$a, java.lang.Runnable, md.f)' on a null object reference
       at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

I am facing this crash while using expo-location along with expo-task-manager when app is kept in background. After sometime the app crashes with above logs

### Environment

"expo": "^49.0.21",
"expo-background-fetch": "^11.3.0",
"expo-camera": "^13.4.4",
"expo-face-detector": "^12.2.0",
"expo-gl": "^13.0.1",
"expo-location": "^16.1.0",
"expo-modules-core": "^1.5.12",
"expo-task-manager": "^11.3.0",
"react": "^18.2.0",
"react-native": "^0.72.6",

**Comment by Invictus-Munish** [comment]
[com.invictus.jra_issue_3f5696e927859c43261bf2131dad5cce_crash_session_65AFABA301AA000133BE7DB2DAE15D92_DNE_0_v2_stacktrace.txt](https://github.com/expo/expo/files/14024219/com.invictus.jra_issue_3f5696e927859c43261bf2131dad5cce_crash_session_65AFABA301AA000133BE7DB2DAE15D92_DNE_0_v2_stacktrace.txt)
