### ISSUE TITLE
[SDK 50] Expo tracking transparency crashing on web

### ISSUE THREAD

**Issue by JPStrydom** [expo/expo#26841]
### Minimal reproducible example

Add `import { requestTrackingPermissionsAsync } from 'expo-tracking-transparency';` to an Expo 50 web project

### Summary

After upgrading to Expo 50, our web servers stopped working - both dev and production (bundled).

When attempting to start our dev web server with `expo start --web` we get the following error:
```
Failed to compile.
   7 |   const cryptoObject =
Module not found: Can't resolve 'crypto'
   8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
>  9 |       ? require('crypto')
     |        ^
  10 |       : crypto;
  11 |
  12 |   if (!cryptoObject?.randomUUID) {
```

After setting the following in our `webpack.config.js` file (which feels like a band aid solution):
```
config.resolve.fallback = { crypto: false };
```

We're able to get the server running. We then get the following error:
```
Uncaught Error: Cannot find native module 'ExpoTrackingTransparency'
    at r (requireNativeModule.web.ts:2:9)
    at 96419 (ExpoTrackingTransparency.ts:4:16)
    at n (bootstrap:19:32)
    at 26898 (main.9f22d3ea.js:1:16081)
    at n (bootstrap:19:32)
    at 15530 (AppEntry.js:5:1)
    at n (bootstrap:19:32)
    at startup:4:74
    at n.O (chunk loaded:23:12)
    at startup:5:43
```

This seems to be caused by expo-tracking-transparency. As soon as we remove the import (_adding this to any web project with Expo 50 and expo-tracking-transparency will reproduce the error)_:
```
import { requestTrackingPermissionsAsync } from 'expo-tracking-transparency';
```

From our codebase, then the server works and our site renders correctly.

_NOTE: We're also happy to migrate to Metro for web, but we've been unable to find guides on how to migrate our `HtmlWebpackPlugin` and we're using React Navigation and not Expo Router (which is apparently a requirement for using Metro on web)._

Here's are our project dependencies:
```
"dependencies": {
    "@babel/core": "^7.23.7",
    "@expo/config-plugins": "~7.8.0",
    "@expo/react-native-action-sheet": "^4.0.1",
    "@expo/webpack-config": "^19.0.1",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.11",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/netinfo": "11.1.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@testing-library/react-native": "^12.4.3",
    "axios": "^1.6.7",
    "axios-retry": "^4.0.0",
    "core-js-pure": "^3.35.1",
    "date-fns": "^3.3.1",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-check-file": "^2.6.2",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.1.0",
    "eslint-plugin-sort-exports": "^0.9.1",
    "expo": "~50.0.4",
    "expo-application": "~5.8.3",
    "expo-asset": "~9.0.2",
    "expo-auth-session": "~5.4.0",
    "expo-av": "~13.10.4",
    "expo-barcode-generator": "^1.0.5",
    "expo-build-properties": "~0.11.0",
    "expo-clipboard": "~5.0.1",
    "expo-constants": "~15.4.5",
    "expo-crypto": "~12.8.0",
    "expo-device": "~5.9.3",
    "expo-font": "~11.10.2",
    "expo-image": "~1.10.5",
    "expo-image-picker": "~14.7.1",
    "expo-linking": "~6.2.2",
    "expo-local-authentication": "~13.8.0",
    "expo-localization": "~14.8.3",
    "expo-location": "~16.5.2",
    "expo-notifications": "~0.27.6",
    "expo-random": "~13.6.0",
    "expo-secure-store": "~12.8.1",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-tracking-transparency": "~3.3.0",
    "expo-video-thumbnails": "~7.9.0",
    "expo-web-browser": "~12.8.2",
    "html-webpack-plugin": "^5.6.0",
    "husky": "^9.0.7",
    "intl": "^1.2.5",
    "jest": "^29.7.0",
    "jwt-decode": "^4.0.0",
    "lint-staged": "^15.2.0",
    "lodash": "^4.17.21",
    "mockdate": "^3.0.5",
    "moxios": "^0.4.0",
    "newrelic-react-native-agent": "^1.3.5",
    "node-forge": "^1.3.1",
    "phone": "^3.1.42",
    "prettier": "^3.2.4",
    "prettier-2": "npm:prettier@^2.8.8",
    "prop-types": "^15.8.1",
    "qs": "^6.11.2",
    "react": "18.2.0",
    "react-content-loader": "^6.2.1",
    "react-dom": "18.2.0",
    "react-error-boundary": "^4.0.12",
    "react-hook-form": "^7.49.3",
    "react-native": "0.73.2",
    "react-native-dotenv": "^3.4.9",
    "react-native-maps": "1.8.0",
    "react-native-pager-view": "6.2.3",
    "react-native-paper": "^5.12.3",
    "react-native-paper-dates": "^0.21.7",
    "react-native-paper-tabs": "^0.10.3",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-style-prop-type": "^1.0.3",
    "react-native-svg": "14.1.0",
    "react-native-vector-icons": "^10.0.3",
    "react-native-web": "~0.19.10",
    "react-native-web-maps": "^0.3.0",
    "react-native-webview": "13.6.4",
    "react-test-renderer": "18.2.0",
    "rimraf": "^5.0.5",
    "semver": "^7.5.4",
    "serve": "^14.2.1",
    "south-african-id-parser": "^2.0.0",
    "yargs": "^17.7.2"
  }
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    npmPackages:
      @expo/webpack-config: ^19.0.1 => 19.0.1
      expo: ~50.0.4 => 50.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.10 => 0.19.10
    Expo Workflow: managed

**Comment by JPStrydom** [comment]
The reproduction is way to simple to warrent an entire repo. All you need to do is run an Expo 50 web project and include the following line of code in the project:
```
import { requestTrackingPermissionsAsync } from 'expo-tracking-transparency';
```
Using expo-tracking-transparency ~3.3.0
