### ISSUE TITLE
[SDK 50] Expo tracking transparency crashing on web

### ISSUE THREAD

**Issue by JPStrydom** [expo/expo#26879]
### Minimal reproducible example

See attached ZIP file ([expo-upgrade-playground.zip](https://github.com/expo/expo/files/14138698/expo-upgrade-playground.zip))

### Summary

After upgrading to Expo 50, our web servers stopped working - both dev and production (bundled).

When attempting to start our dev web server with `expo start --web` we get the following error:
```
Failed to compile.
   7 |   const cryptoObject =
Module not found: Can't resolve 'crypto'
   8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
>  9 |       ? require('crypto')
     |        ^
  10 |       : crypto;
  11 |
  12 |   if (!cryptoObject?.randomUUID) {
```

After setting the following in our `webpack.config.js` file (which feels like a band aid solution):
```
config.resolve.fallback = { crypto: false };
```

We're able to get the server running. We then get the following error:
```
Uncaught Error: Cannot find native module 'ExpoTrackingTransparency'
    at r (requireNativeModule.web.ts:2:9)
    at 96419 (ExpoTrackingTransparency.ts:4:16)
    at n (bootstrap:19:32)
    at 26898 (main.9f22d3ea.js:1:16081)
    at n (bootstrap:19:32)
    at 15530 (AppEntry.js:5:1)
    at n (bootstrap:19:32)
    at startup:4:74
    at n.O (chunk loaded:23:12)
    at startup:5:43
```

This seems to be caused by expo-tracking-transparency. If we remove the following line from our codebase, the site renders correctly:
```
import { requestTrackingPermissionsAsync } from 'expo-tracking-transparency';
```

#### Issue Reproduction

Here's a ZIP file containing a small project that reproduces the issue:
[expo-upgrade-playground.zip](https://github.com/expo/expo/files/14138698/expo-upgrade-playground.zip)

To reproduce this issue, simply install the dependencies with:
```shell
npm i
```
And then start the web server with:
```shell
npm run web
```

You should then see the above mentioned runtime error.

_NOTE: We're also happy to migrate to Metro for web, but we've been unable to find guides on how to migrate our `HtmlWebpackPlugin` and we're using React Navigation and not Expo Router (which is apparently a requirement for using Metro on web)._

Here's are our project dependencies:
```
"dependencies": {
    "@babel/core": "^7.23.7",
    "@expo/config-plugins": "~7.8.0",
    "@expo/react-native-action-sheet": "^4.0.1",
    "@expo/webpack-config": "^19.0.1",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.11",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/netinfo": "11.1.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@testing-library/react-native": "^12.4.3",
    "axios": "^1.6.7",
    "axios-retry": "^4.0.0",
    "core-js-pure": "^3.35.1",
    "date-fns": "^3.3.1",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-check-file": "^2.6.2",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.1.0",
    "eslint-plugin-sort-exports": "^0.9.1",
    "expo": "~50.0.4",
    "expo-application": "~5.8.3",
    "expo-asset": "~9.0.2",
    "expo-auth-session": "~5.4.0",
    "expo-av": "~13.10.4",
    "expo-barcode-generator": "^1.0.5",
    "expo-build-properties": "~0.11.0",
    "expo-clipboard": "~5.0.1",
    "expo-constants": "~15.4.5",
    "expo-crypto": "~12.8.0",
    "expo-device": "~5.9.3",
    "expo-font": "~11.10.2",
    "expo-image": "~1.10.5",
    "expo-image-picker": "~14.7.1",
    "expo-linking": "~6.2.2",
    "expo-local-authentication": "~13.8.0",
    "expo-localization": "~14.8.3",
    "expo-location": "~16.5.2",
    "expo-notifications": "~0.27.6",
    "expo-random": "~13.6.0",
    "expo-secure-store": "~12.8.1",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-tracking-transparency": "~3.3.0",
    "expo-video-thumbnails": "~7.9.0",
    "expo-web-browser": "~12.8.2",
    "html-webpack-plugin": "^5.6.0",
    "husky": "^9.0.7",
    "intl": "^1.2.5",
    "jest": "^29.7.0",
    "jwt-decode": "^4.0.0",
    "lint-staged": "^15.2.0",
    "lodash": "^4.17.21",
    "mockdate": "^3.0.5",
    "moxios": "^0.4.0",
    "newrelic-react-native-agent": "^1.3.5",
    "node-forge": "^1.3.1",
    "phone": "^3.1.42",
    "prettier": "^3.2.4",
    "prettier-2": "npm:prettier@^2.8.8",
    "prop-types": "^15.8.1",
    "qs": "^6.11.2",
    "react": "18.2.0",
    "react-content-loader": "^6.2.1",
    "react-dom": "18.2.0",
    "react-error-boundary": "^4.0.12",
    "react-hook-form": "^7.49.3",
    "react-native": "0.73.2",
    "react-native-dotenv": "^3.4.9",
    "react-native-maps": "1.8.0",
    "react-native-pager-view": "6.2.3",
    "react-native-paper": "^5.12.3",
    "react-native-paper-dates": "^0.21.7",
    "react-native-paper-tabs": "^0.10.3",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-style-prop-type": "^1.0.3",
    "react-native-svg": "14.1.0",
    "react-native-vector-icons": "^10.0.3",
    "react-native-web": "~0.19.10",
    "react-native-web-maps": "^0.3.0",
    "react-native-webview": "13.6.4",
    "react-test-renderer": "18.2.0",
    "rimraf": "^5.0.5",
    "semver": "^7.5.4",
    "serve": "^14.2.1",
    "south-african-id-parser": "^2.0.0",
    "yargs": "^17.7.2"
  }
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    npmPackages:
      @expo/webpack-config: ^19.0.1 => 19.0.1
      expo: ~50.0.4 => 50.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.10 => 0.19.10
    Expo Workflow: managed

**Comment by joaolfern** [comment]
I'm also facing this. I have come up with this code to avoid crashing on web:

```import { ReactNode, Suspense, lazy } from 'react'
import { Platform } from 'react-native'

const TrackingProvider = lazy(() => import('src/components/TrackingProvider'))

export function PlatformTrackingWrapper({ children }: { children: ReactNode }) {
  if (Platform.OS === 'web') return children

  return (
    <>
      {children}
      <Suspense>
        <TrackingProvider />
      </Suspense>
    </>
  )
}
`

Given that the package appears to have no utility on the web, I believe this code suffices

**Comment by serfgy** [comment]
seeing the same errors with similar environment, managed workflow

we are also using react navigation and happy to migrate to metro, need guidance on migration without using expo-router

**Comment by HugDoggyDogg** [comment]
I encounter the same error after upgrading to SDK50, not using expo-router yet either.

**Comment by ArnieGA** [comment]
Same here. Using react-navigation instead of expo-router as well.

I'm not using the `TrackingProvider` though, as the others seem to be. It is a very simple and minimal project made of 2 screens. Here's what the terminal screams at me with:
```
ERROR in ./node_modules/expo-modules-core/build/uuid/uuid.web.js:9:8
Module not found: Can't resolve 'crypto'
   7 |   const cryptoObject =
   8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
>  9 |       ? require('crypto')
     |        ^
  10 |       : crypto;
  11 |
  12 |   if (!cryptoObject?.randomUUID) {

ERROR in ./node_modules/expo-router/build/onboard/Tutorial.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: <private-project-path>\node_modules\expo-router\build\onboard\Tutorial.js: Expected `fromDir` to be of type `string`, got `undefined`
    at resolveFrom (<private-project-path>\node_modules\resolve-from\index.js:8:9)
    at module.exports (<private-project-path>\node_modules\resolve-from\index.js:46:47)
    at getExpoRouterAppRoot (<private-project-path>\node_modules\babel-preset-expo\build\expo-router-plugin.js:14:52)
    at PluginPass.call (<private-project-path>\node_modules\babel-preset-expo\build\expo-router-plugin.js:72:66)
    at call (<private-project-path>\node_modules\@babel\traverse\src\visitors.ts:293:14)
    at NodePath._call (<private-project-path>\node_modules\@babel\traverse\src\path\context.ts:35:20)
    at NodePath.call (<private-project-path>\node_modules\@babel\traverse\src\path\context.ts:20:17)
    at NodePath.visit (<private-project-path>\node_modules\@babel\traverse\src\path\context.ts:94:31)
    at TraversalContext.visitQueue (<private-project-path>\node_modules\@babel\traverse\src\context.ts:147:16)
    at TraversalContext.visitSingle (<private-project-path>\node_modules\@babel\traverse\src\context.ts:108:19)
    at TraversalContext.visit (<private-project-path>\node_modules\@babel\traverse\src\context.ts:179:19)
    at traverseNode (<private-project-path>\node_modules\@babel\traverse\src\traverse-node.ts:40:17)
    at NodePath.visit (<private-project-path>\node_modules\@babel\traverse\src\path\context.ts:101:33)
    at TraversalContext.visitQueue (<private-project-path>\node_modules\@babel\traverse\src\context.ts:147:16)
    at TraversalContext.visitSingle (<private-project-path>\node_modules\@babel\traverse\src\context.ts:108:19)
    at TraversalContext.visit (<private-project-path>\node_modules\@babel\traverse\src\context.ts:179:19)
    at traverseNode (<private-project-path>\node_modules\@babel\traverse\src\traverse-node.ts:40:17)
    at NodePath.visit (<private-project-path>\node_modules\@babel\traverse\src\path\context.ts:101:33)
    at TraversalContext.visitQueue (<private-project-path>\node_modules\@babel\traverse\src\context.ts:147:16)
    at TraversalContext.visitMultiple (<private-project-path>\node_modules\@babel\traverse\src\context.ts:98:17)
    at TraversalContext.visit (<private-project-path>\node_modules\@babel\traverse\src\context.ts:177:19)
    at traverseNode (<private-project-path>\node_modules\@babel\traverse\src\traverse-node.ts:40:17)
    at NodePath.visit (<private-project-path>\node_modules\@babel\traverse\src\path\context.ts:101:33)
    at TraversalContext.visitQueue (<private-project-path>\node_modules\@babel\traverse\src\context.ts:147:16)
    at TraversalContext.visitMultiple (<private-project-path>\node_modules\@babel\traverse\src\context.ts:98:17)
    at TraversalContext.visit (<private-project-path>\node_modules\@babel\traverse\src\context.ts:177:19)
    at traverseNode (<private-project-path>\node_modules\@babel\traverse\src\traverse-node.ts:40:17)
    at NodePath.visit (<private-project-path>\node_modules\@babel\traverse\src\path\context.ts:101:33)
    at TraversalContext.visitQueue (<private-project-path>\node_modules\@babel\traverse\src\context.ts:147:16)
    at TraversalContext.visitSingle (<private-project-path>\node_modules\@babel\traverse\src\context.ts:108:19)
    at TraversalContext.visit (<private-project-path>\node_modules\@babel\traverse\src\context.ts:179:19)
    at traverseNode (<private-project-path>\node_modules\@babel\traverse\src\traverse-node.ts:40:17)
    at traverse (<private-project-path>\node_modules\@babel\traverse\src\index.ts:82:15)
    at transformFile (<private-project-path>\node_modules\@babel\core\src\transformation\index.ts:124:15)
    at transformFile.next (<anonymous>)
    at run (<private-project-path>\node_modules\@babel\core\src\transformation\index.ts:48:12)
    at run.next (<anonymous>)
    at transform (<private-project-path>\node_modules\@babel\core\src\transform.ts:29:20)
    at transform.next (<anonymous>)
    at step (<private-project-path>\node_modules\gensync\index.js:261:32)
    at <private-project-path>\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (<private-project-path>\node_modules\gensync\index.js:223:11)
```

And here's my `package.json`:
```
{
  "name": "<not-important>",
  "version": "1.0.0",
  "main": "./src/index.tsx",
  "scripts": {
    "start": "expo start",
    "start:c": "expo start -c",
    "android": "expo start -c --android",
    "ios": "expo start -c --ios",
    "web": "expo start -c --web"
  },
  "dependencies": {
    "@expo/webpack-config": "^19.0.1",
    "@gorhom/bottom-sheet": "^4.6.1",
    "@react-navigation/native": "^6.1.14",
    "@react-navigation/native-stack": "^6.9.22",
    "@reduxjs/toolkit": "^2.2.1",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.8",
    "axios": "^1.6.7",
    "expo": "~50.0.8",
    "expo-clipboard": "^5.0.1",
    "expo-crypto": "^12.8.1",
    "expo-router": "~3.4.8",
    "expo-status-bar": "~1.11.1",
    "formik": "^2.4.5",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.73.4",
    "react-native-dotenv": "^3.4.11",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "^3.29.0",
    "react-native-web": "^0.19.10",
    "react-redux": "^9.1.0",
    "text-encoding": "^0.7.0",
    "yup": "^1.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@types/lodash": "^4.14.202",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

**Comment by keith-kurak** [comment]
Hi! Thanks for the reproduction. I was able to see the issue on my end, with the `Cannot find native module 'ExpoTrackingTransparency'` error occurring for both Metro and Webpack (`crypto` error only happens on webpack), which was not the case in SDK 49.

 The net result is the same as @joaolfern's workaround, but just wanted to throw one more out there in the meantime while we look at this: wrapping the tracking transparency usage in a hook in a separate file, and using a platform-specific file extension to no-op this for web.
 
 App.js:
 ```
 import { useTrackingTransparency } from './useTrackingTransparency';

export default () => {
  useTrackingTransparency();

  return (
    //... etc.
  );
}
 ```

useTrackingTransparency.js:
```
import { useEffect } from 'react';
import { requestTrackingPermissionsAsync } from 'expo-tracking-transparency';

export const useTrackingTransparency = () => {
  useEffect(() => {
    const loadTrackingPermissionsAsync = async () => {
      const { status } = await requestTrackingPermissionsAsync();
      console.log(`Loaded expo-tracking-transparency status as ${status}`)
    }

    loadTrackingPermissionsAsync()
  }, []);
}
```

useTrackingTransparency.web.js:
```
export const useTrackingTransparency = () => {}
```

**Comment by ArnieGA** [comment]
@keith-kurak Thanks, but what about the rest of us getting the same error just by running the project in Web mode? In our case we're not even using `ExpoTrackingTransparency` anywhere.

**Comment by ricohumme** [comment]
I took @keith-kurak approach and made it slightly different:

```
// useTrackingTransparency.ts
import { requestTrackingPermissionsAsync, useTrackingPermissions } from "expo-tracking-transparency";

export const useTrackingTransparency = () => {
  const [status, requestPermission] = useTrackingPermissions();

  if (status?.canAskAgain && !status?.granted) {
    requestPermission();
  }

  return {
    status,
    requestTrackingPermissionsAsync,
  };
};
```

```
// useTrackingTransparency.web.ts
export const useTrackingTransparency = () => {
  return {
    status: { granted: false },
    requestTrackingPermissionsAsync: () => {
      return new Promise((resolve) => resolve({ granted: false }));
    },
  };
};
```

```
// App.js
const { status, requestTrackingPermissionsAsync } = useTrackingTransparency();
...
```

**Comment by serfgy** [comment]
is react navigation going to be supported with expo's metro bundler or do we have to use expo router going forward? this will require a compulsory refactor to our code

**Comment by sean-m-oleary** [comment]
> > is react navigation going to be supported with expo's metro bundler or do we have to use expo router going forward? this will require a compulsory refactor for web compatible native code
> 
> I would also really like to know if we can still use React Navigation with Metro. It's my understanding that Expo Router uses React Navigation under the hood, so it'll be quite sad if we need to refactor our systems to use Expo Router when the underlying functionality is the same.
> 
> Like [@serfgy](https://github.com/serfgy) mentioned, migrating away from React Navigation to Expo Router is quite a big change, especially on apps with lots of existing pages and navigation logic. Expo Router also forces a folder structure and file naming convention on developers, which might be difficult to switch to.
> 
> I really hope Expo will still support using React Navigation as a navigation framework.

I second this. If we're forced to switch just to keep on the latest Expo then this is a massive headache.

**Comment by josiext** [comment]
Any news on this?

**Comment by josiext** [comment]
Well I fixed it using this custom hook to calling the function:

```
export const useTrackingPermission = () => {
  useEffect(() => {
    (() => {
      setTimeout(async () => {
        if (Platform.OS !== "ios") return;

        // Async import to avoid errors in web
        const { requestTrackingPermissionsAsync } = await import(
          "expo-tracking-transparency"
        );
        await requestTrackingPermissionsAsync();
      }, 500);
    })();
  }, []);
};

```

**Comment by chrfalch** [comment]
Closing since SDK-50 is no longer supported - please retest and create a new issue if this still persists.
