### ISSUE TITLE
[SKD 50] jest-expo is not mocking all native modules

### ISSUE THREAD

**Issue by rodneyrehm** [expo/expo#26893]
### Minimal reproducible example

none

### Summary

After upgrading to Expo 50.0.5 (with jest-expo 50.0.1) various of our jest suites fail. It appears certain modules have not yet been added to https://github.com/expo/expo/blob/main/packages/jest-expo/src/preset/expoModules.js. From the looks of it, this also is the case for #26877

### jest-expo

Applying the following patch

```diff
diff --git a/node_modules/jest-expo/src/preset/expoModules.js b/node_modules/jest-expo/src/preset/expoModules.js
index 039dc93..014df20 100644
--- a/node_modules/jest-expo/src/preset/expoModules.js
+++ b/node_modules/jest-expo/src/preset/expoModules.js
@@ -408,6 +408,9 @@ module.exports = {
           { name: 'stopRecording', argumentsCount: 1, key: 'stopRecording' },
           { name: 'takePicture', argumentsCount: 2, key: 'takePicture' },
         ],
+        ExpoCameraNext: [
+          // MISSING
+        ],
         ExponentConstants: [
           { name: 'getWebViewUserAgentAsync', argumentsCount: 0, key: 'getWebViewUserAgentAsync' },
         ],
@@ -492,6 +495,12 @@ module.exports = {
           { name: 'getNotificationCategoriesAsync', argumentsCount: 0, key: 1 },
           { name: 'setNotificationCategoryAsync', argumentsCount: 3, key: 2 },
         ],
+        ExpoNotificationChannelGroupManager: [
+          // MISSING
+        ],
+        ExpoNotificationChannelManager: [
+          // MISSING
+        ],
         ExpoNotificationPermissionsModule: [
           { name: 'getPermissionsAsync', argumentsCount: 0, key: 0 },
           { name: 'requestPermissionsAsync', argumentsCount: 1, key: 1 },
@@ -717,6 +726,9 @@ module.exports = {
           VideoStabilization: { type: 'object' },
           WhiteBalance: { type: 'object' },
         },
+        ExpoCameraNext: {
+          // MISSING
+        },
         ExponentConstants: {
           appOwnership: { type: 'string' },
           debugMode: { type: 'boolean', mock: false },
@@ -828,6 +840,9 @@ module.exports = {
             'zoom',
           ],
         },
+        ExpoCameraNext: {
+          // MISSING
+        },
         ExponentGLView: { propsNames: ['enableExperimentalWorkletSupport', 'msaaSamples'] },
         ExpoVideoView: { propsNames: ['resizeMode', 'source', 'status', 'useNativeControls'] },
       },
@@ -903,6 +918,9 @@ module.exports = {
     getConstants: { type: 'function' },
     removeListeners: { type: 'function', functionType: 'async' },
   },
+  RNCDatePicker: {
+    // MISSING
+  },
   RNCMaskedViewManager: {},
   RNCNetInfo: {
     addListener: { type: 'function', functionType: 'async' },
@@ -919,6 +937,9 @@ module.exports = {
   RNCSafeAreaView: {},
   RNCSegmentedControlManager: {},
   RNCSliderManager: {},
+  RNCTimePicker: {
+    // MISSING
+  },
   RNCViewPager: {
     getConstants: { type: 'function' },
     setPage: { type: 'function', functionType: 'async' },
```

prevents the following errors

```
Cannot find native module 'ExpoNotificationChannelManager'

at Object.requireNativeModule (node_modules/expo-modules-core/src/requireNativeModule.ts:43:11)
at requireNativeModule (node_modules/jest-expo/src/preset/setup.js:222:34)
at Object.<anonymous> (node_modules/expo-notifications/src/NotificationChannelManager.native.ts:5:35)
```

```
Cannot find native module 'ExpoNotificationChannelGroupManager'

at Object.requireNativeModule (node_modules/expo-modules-core/src/requireNativeModule.ts:43:11)
at requireNativeModule (node_modules/jest-expo/src/preset/setup.js:222:34)
at Object.<anonymous> (node_modules/expo-notifications/src/NotificationChannelGroupManager.native.ts:5:35)
```

```
Cannot find native module 'ExpoCameraNext'

at Object.requireNativeModule (node_modules/expo-modules-core/src/requireNativeModule.ts:43:11)
at requireNativeModule (node_modules/jest-expo/src/preset/setup.js:222:34)
at Object.<anonymous> (node_modules/expo-camera/src/next/ExpoCameraManager.ts:3:35)
```

```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCDatePicker' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","DeviceInfo","ImageLoader","KeyboardObserver","RNCSafeAreaContext","StatusBarManager","StatusBarManager","I18nManager"],"TurboModules":[],"NotFound":["SoundManager","FrameRateLogger","Appearance","RNCDatePicker"]}

at invariant (node_modules/invariant/invariant.js:40:15)
at Object.getEnforcing (node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:87:12)
at Object.getEnforcing (node_modules/@react-native-community/datetimepicker/src/specs/NativeModuleDatePicker.js:15:37)
```

```
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCTimePicker' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","DeviceInfo","RNCSafeAreaContext","ImageLoader","KeyboardObserver","StatusBarManager","StatusBarManager","I18nManager","RNCDatePicker"],"TurboModules":[],"NotFound":["SoundManager","FrameRateLogger","Appearance","RNCTimePicker"]}

at invariant (node_modules/invariant/invariant.js:40:15)
at Object.getEnforcing (node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:87:12)
at Object.getEnforcing (node_modules/@react-native-community/datetimepicker/src/specs/NativeModuleTimePicker.js:16:37)
```

### react-native-webview

Adding the following to `jest.setup.js`

```js
jest.mock('react-native-webview', () => {
  const rn = jest.requireActual('react-native')
  return rn.View
})
```

prevents the following error:

```
/…/node_modules/react-native-webview/lib/RNCWebViewNativeComponent.js: Could not find component config for native component

  > 10 | import WebView from 'react-native-webview'
       | ^

at throwIfConfigNotfound (node_modules/@react-native/codegen/lib/parsers/error-utils.js:285:11)
at findComponentConfig (node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:896:3)
at buildComponentSchema (node_modules/@react-native/codegen/lib/parsers/flow/components/index.js:24:32)
…
at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:726:19)
at Object.require (node_modules/react-native-webview/lib/WebView.ios.js:62:1)
at Object.require (node_modules/react-native-webview/index.js:1:1)
```

### expo-splash-screen

Adding the following to `jest.setup.js`

```js
jest.mock('expo-splash-screen', () => ({
  hideAsync: jest.fn().mockResolvedValue(null),
  preventAutoHideAsync: jest.fn().mockResolvedValue(null),
}))
```

prevents the following error:

```
TypeError: Cannot read properties of undefined (reading 'catch')

at Object.hideAsync (node_modules/expo-splash-screen/src/index.native.ts:56:34)
at hideAsync (App.tsx:162:20)
at commitHookEffectListMount (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12999:26)
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /opt/homebrew/bin/node
      npm: 10.2.3 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 28, 31, 33, 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^10.0.0 => 10.0.1
      expo: ~50.0.5 => 50.0.5
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.8
    Expo Workflow: bare
```

**Comment by anhphamminh** [comment]
```
error: ../../node_modules/expo-router/_ctx.ios.js: ../../node_modules/expo-router/_ctx.ios.js:Invalid call at line <unknown>: undefined
First argument of `require.context` should be a string denoting the directory to require.
```

got this error when upgrade expo to 50, plz help me!!

**Comment by rodneyrehm** [comment]
> I think most of these issues should be fixed by releasing new bundled mocks for SDK50 – PR is open.

yes, #26931 looks like a good step forward! thanks <3

However, it seems the generator you executed there did not come across
* `ExpoNotificationChannelGroupManager` from `expo-notifications`
* `ExpoNotificationChannelManager` from `expo-notifications`
* `RNCDatePicker` from `@react-native-community/datetimepicker`
* `RNCTimePicker` from `@react-native-community/datetimepicker`

The `RNCWebViewNativeComponent` issue remains as well.

**Comment by aleqsio** [comment]
yeah, I saw that – investigating why the mock-generator broke for those or if those even are native modules that are still included is a bit of a larger task...

**Comment by kotadd** [comment]
Hi @aleqsio and @rodneyrehm,

I hope you're doing well. I've encountered the same issue as reported here and had to halt upgrading to Expo 50 due to the error like below:

```
Cannot find native module 'ExpoCrypto'
```

Is there any progress on resolving this? Also, is temporarily mocking the affected modules the recommended workaround for now? Any guidance or updates would be greatly appreciated!

Thank you for your efforts!

**Comment by aleqsio** [comment]
@kotadd This package should be automocked by `jest-expo` reading `packages/expo-crypto/mocks/ExpoCrypto.ts` – seems like a different issue.

**Comment by aleqsio** [comment]
@rodneyrehm Were you able to fix the jest tests or migrate to sdk51 successfully?

**Comment by rodneyrehm** [comment]
@aleqsio I haven't upgraded to SDK51 _yet_. jest is running fine with SDK50 (jest-expo v50.0.4) as long as I apply the following via patch-package:

```diff
diff --git a/node_modules/jest-expo/src/preset/expoModules.js b/node_modules/jest-expo/src/preset/expoModules.js
index aba8800..2ffb759 100644
--- a/node_modules/jest-expo/src/preset/expoModules.js
+++ b/node_modules/jest-expo/src/preset/expoModules.js
@@ -442,6 +442,9 @@ module.exports = {
           { name: 'getCurrentInput', argumentsCount: 0, key: 21 },
           { name: 'startAudioRecording', argumentsCount: 0, key: 22 },
         ],
+        ExpoCameraNext: [
+          // MISSING
+        ],
         ExponentConstants: [
           { name: 'getWebViewUserAgentAsync', argumentsCount: 0, key: 'getWebViewUserAgentAsync' },
         ],
@@ -548,6 +551,12 @@ module.exports = {
           { name: 'getNotificationCategoriesAsync', argumentsCount: 0, key: 1 },
           { name: 'setNotificationCategoryAsync', argumentsCount: 3, key: 2 },
         ],
+        ExpoNotificationChannelGroupManager: [
+          // MISSING
+        ],
+        ExpoNotificationChannelManager: [
+          // MISSING
+        ],
         ExpoNotificationPermissionsModule: [
           { name: 'getPermissionsAsync', argumentsCount: 0, key: 0 },
           { name: 'requestPermissionsAsync', argumentsCount: 1, key: 1 },
@@ -960,6 +969,9 @@ module.exports = {
     getConstants: { type: 'function' },
     getRandomBase64: { type: 'function', functionType: 'sync' },
   },
+  RNCDatePicker: {
+    // MISSING
+  },
   RNCMaskedViewManager: {},
   RNCNetInfo: {
     addListener: { type: 'function', functionType: 'async' },
@@ -977,6 +989,9 @@ module.exports = {
   RNCSafeAreaView: {},
   RNCSegmentedControlManager: {},
   RNCSliderManager: {},
+  RNCTimePicker: {
+    // MISSING
+  },
   RNCViewPager: {
     getConstants: { type: 'function' },
     setPage: { type: 'function', functionType: 'async' },
```
