### ISSUE TITLE
Expo 50.0.6: `npx expo start`: Invalid URL

### ISSUE THREAD

**Issue by acarlstein** [expo/expo#27076]
### Summary

It fails to start after updating Expo to 50.0.6 and all the related packages to their latest versions (using `ncu -u`).

### SDK Version

50.0.6

### Environment

```
% npx expo-env-info  
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    Expo Workflow: managed
  ```

### Minimal reproducible example

**Failure:**
```
xyz@ ~/Projects/AwesomeProject/Code/awesome-project % npx expo start       
Starting project at /Users/xyz/Projects/AwesomeProject/Code/awesome-project
(node:46548) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
TypeError: Invalid URL
TypeError: Invalid URL
    at new URL (node:internal/url:787:36)
    at Object.createCorsMiddleware (/Users/xyz/Projects/AwesomeProject/Code/awesome-project/node_modules/@expo/cli/src/start/server/middleware/CorsMiddleware.ts:18:27)
    at Object.instantiateMetroAsync (/Users/xyz/Projects/AwesomeProject/Code/awesome-project/node_modules/@expo/cli/src/start/server/metro/instantiateMetro.ts:166:30)
    at MetroBundlerDevServer.startImplementationAsync (/Users/xyz/Projects/AwesomeProject/Code/awesome-project/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:412:58)
    at MetroBundlerDevServer.startAsync (/Users/xyz/Projects/AwesomeProject/Code/awesome-project/node_modules/@expo/cli/src/start/server/BundlerDevServer.ts:159:18)
    at DevServerManager.startAsync (/Users/xyz/Projects/AwesomeProject/Code/awesome-project/node_modules/@expo/cli/src/start/server/DevServerManager.ts:176:7)
    at startAsync (/Users/xyz/Projects/AwesomeProject/Code/awesome-project/node_modules/@expo/cli/src/start/startAsync.ts:93:3)
```

**package.json:**
```
{
  "name": "AwesomeProject",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "lint": "eslint .",
    "test": "jest"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "expo": "^50.0.6",
    "expo-barcode-scanner": "~12.9.2",
    "expo-camera": "~14.0.4",
    "expo-constants": "~15.4.5",
    "expo-device": "~5.9.3",
    "expo-linking": "~6.2.2",
    "expo-location": "~16.5.3",
    "expo-router": "^3.4.7",
    "expo-splash-screen": "^0.26.4",
    "expo-status-bar": "~1.11.1",
    "patch-package": "^8.0.0",
    "punycode": "^2.3.1",
    "react": "18.2.0",
    "react-native": "^0.73.4",
    "react-native-maps": "1.10.2",
    "react-native-modal": "^13.0.1",
    "react-native-qrcode-svg": "^6.3.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.9.0",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.23.9",
    "@react-native/metro-config": "0.73.5",
    "metro": "^0.80.5"
  },
  "resolutions": {
    "react-refresh": "~0.14.0"
  },
  "engines": {
    "node": ">=18"
  },
  "private": true
}
```

**Observations:**

* The folder, inside `node_modules`, `@expo/cli/src` is missing.

**Comment by brentvatne** [comment]
@acarlstein - i'd love to investigate this but not sure where to start without a minimal reproducible example! please share
