### ISSUE TITLE
`getCurrentPositionAsync` from `expo-location` breaks in WearOS

### ISSUE THREAD

**Issue by FacuM** [expo/expo#27098]
### Minimal reproducible example

https://github.com/FacuM/AbsolutelyEpicLocationCrashExample

### Summary

On **WearOS**, tested on a **Samsung Galaxy Watch5 Pro** running **Android 13**, the method `getCurrentPositionAsync` from `expo-location` breaks with the error code **ERR_LOCATION_SETTINGS_UNSATISFIED**.

This assumption of an access denial is false because, previously, the logs clearly indicate that permissions were successfully granted. For an example, check the log below:

```
Android Bundled 31ms (node_modules/expo/AppEntry.js)
 DEBUG  requestForegroundPermissionsAsync: granted
 ERROR  detectOriginStation: [Error: Location request failed due to unsatisfied device settings]
```

Looking up the output of `logcat` wthin **Android Studio** I can tell that the reason for the crash is that **WearOS's GMS framework** doesn't seem to implement the native method call that `getCurrentPositionAsync` is looking for.

```
2024-02-15 01:18:38.397   755-1030  AsyncOperation          com.google.android.gms               W  operation=CheckLocationSettings, opStatusCode=10 [CONTEXT service_id=6 ]
                                                                                                    OperationException[Status{statusCode=Not implemented on this platform., resolution=null}]
                                                                                                    	at bcsn.a(:com.google.android.gms@233612092@23.36.12 (240804-562690244):7)
                                                                                                    	at yyf.c(:com.google.android.gms@233612092@23.36.12 (240804-562690244):1)
                                                                                                    	at yyl.run(:com.google.android.gms@233612092@23.36.12 (240804-562690244):144)
                                                                                                    	at bgzr.run(:com.google.android.gms@233612092@23.36.12 (240804-562690244):13)
                                                                                                    	at nfg.c(:com.google.android.gms@233612092@23.36.12 (240804-562690244):50)
                                                                                                    	at nfg.run(:com.google.android.gms@233612092@23.36.12 (240804-562690244):76)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at nkd.run(:com.google.android.gms@233612092@23.36.12 (240804-562690244):8)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-02-15 01:18:38.401  5954-6985  ReactNativeJS           host.exp.exponent                    E  'detectOriginStation:', { [Error: Location request failed due to unsatisfied device settings] code: 'ERR_LOCATION_SETTINGS_UNSATISFIED' }
```

For testing purposes, it's relevant to note that identical behavior can be observed from an emulated **WearOS** smartwatch.

### Environment

```
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.6 Pop!_OS 22.04 LTS
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      npm: 10.2.4 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 30, 31, 33, 34
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
        System Images: android-33 | Wear OS 4 Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by coffeeblack** [comment]
This is happening for me, too, on an Expo-managed project. It happens on Android 9 and also on the simlator for Pixel 3 and 6.

**Comment by FacuM** [comment]
> @FacuM We were able to get up and running again by downgrading to Expo SDK 49 and running `npx expo-doctor`.

Thanks for the hint, Scott! However, it doesn't seem to work for me. Changing the target version of Expo seems to break my dependencies for some reason, as you can see in the log below:

```
Error: While trying to resolve module `make-plural` from file `[redacted]/node_modules/i18n-js/dist/require/Pluralization.js`, the package `[redacted]/node_modules/make-plural/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`[redacted]/node_modules/make-plural/plurals.mjs`. Indeed, none of these files exist:

  * [redacted]/node_modules/make-plural/plurals.mjs(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
  * [redacted]/node_modules/make-plural/plurals.mjs/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
    at DependencyGraph.resolveDependency ([redacted]/node_modules/metro/src/node-haste/DependencyGraph.js:289:17)
    at Object.resolve ([redacted]/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies ([redacted]/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule ([redacted]/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency ([redacted]/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 3)
    at async Graph._processModule ([redacted]/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency ([redacted]/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 1)
```

I've reverted the change and it's running properly now.

**Comment by FacuM** [comment]
@coffeeblack 

As far as I can tell, what's breaking is the logic related to this [LocationModule.kt#478](https://github.com/expo/expo/blob/main/packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.kt#L478) where it tries to call for the unimplemented method `checkLocationSettings()`.

The _failure listener_ leads to a cancelation of any pending operations on error, my appreciation is that, considering that the underlying API eventually works if you use another method call that doesn't check for the availability of location settings such as `getLastKnownLocation()`, I think that just assuming that we should try to run the rest of code regardless of the return value of `checkLocationSettings()` would be a good idea.

If you have an environment already set-up to work on the SDK itself, please give it a try!

My proposal is that the following code block:

```
      } else { // Location settings are not satisfied. However, we have no way to fix the settings so we won't show the dialog.
        executePendingRequests(Activity.RESULT_CANCELED)
      }
```

Should look like this instead:

```
      } else { // Location settings are not satisfied. However, we have no way to fix the settings so we won't show the dialog.
        executePendingRequests(Activity.RESULT_OK)
      }
```

I haven't been able to properly set-up a development environment as the documentation isn't clear enough about what's the link between `bare-expo` and the packages, or at least I'm not being able to figure it out.
