### ISSUE TITLE
[SDK50] Unable to build with `npx expo run:android --device` 

### ISSUE THREAD

**Issue by leons1767** [expo/expo#27100]
### Summary

Building with `eas build --profile development --platform android` is fine.

Unable to build with `npx expo run:android --device`.

Error output from command as follow.

```
> Task :app:checkDebugAarMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform hermes-android-0.73.4-debug.aar (com.facebook.react:hermes-android:0.73.4) to match attributes {artifactType=android-aar-metadata, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\xxx\.gradle\caches\modules-2\files-2.1\com.facebook.react\hermes-android\0.73.4\d619d768b80e1491148283de8b4cd4481e2c814d\hermes-android-0.73.4-debug.aar.
         > Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 14s
19 actionable tasks: 12 executed, 7 up-to-date
Error: D:\ReactNative\sdk50LocalBuild\android\gradlew.bat exited with non-zero code: 1
Error: D:\ReactNative\sdk50LocalBuild\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (D:\ReactNative\sdk50LocalBuild\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (D:\ReactNative\sdk50LocalBuild\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (D:\ReactNative\sdk50LocalBuild\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (D:\ReactNative\sdk50LocalBuild\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (D:\ReactNative\sdk50LocalBuild\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (D:\ReactNative\sdk50LocalBuild\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22631
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20230416.213759.0 - D:\ReactNative\watchman-v2023.04.17.00-windows\bin\watchman.EXE
    npmPackages:
      expo: ~50.0.6 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: bare

### Minimal reproducible example

```
npx create-expo-app sdk50LocalBuild
cd sdk50LocalBuild
npx expo run:android --device
```

**Comment by leons1767** [comment]
I found the issue, SDK50 doesn't work well with openJDK 21. It seems to work with JDK17 only. I replaced it with microsoft-openjdk17, and all is well again.

`choco install -y microsoft-openjdk17`

**Comment by leons1767** [comment]
I found the issue, SDK50 doesn't work well with openJDK 21. It seems to work with JDK17 only. I replaced it with microsoft-openjdk17, and all is well again.

`choco install -y microsoft-openjdk17`
