### ISSUE TITLE
[SDK50 expo-updates 0.24.10] Unable to build with npx expo run:android --device

### ISSUE THREAD

**Issue by leons1767** [expo/expo#27104]
### Summary

The build issue is with eas-updates 0.24.10

Building with eas build --profile development --platform android is fine.

Unable to build with npx expo run:android --device. The build is successful again once eas-updates is removed.

Error output from command as follow.

```
> Task :expo-updates:kaptGenerateStubsDebugKotlin FAILED
e: java.lang.IllegalAccessError: superclass access check failed: class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x7a866d6b) cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x7a866d6b
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.contextForStubGeneration(Kapt3Extension.kt:297)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:176)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:106)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:125)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)


> Task :react-native-device-info:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-updates:kaptGenerateStubsDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 44s
611 actionable tasks: 110 executed, 487 from cache, 14 up-to-date
Error: D:\ReactNative\DoHelpMg\android\gradlew.bat exited with non-zero code: 1
Error: D:\ReactNative\DoHelpMg\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (D:\ReactNative\DoHelpMg\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (D:\ReactNative\DoHelpMg\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (D:\ReactNative\DoHelpMg\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (D:\ReactNative\DoHelpMg\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (D:\ReactNative\DoHelpMg\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (D:\ReactNative\DoHelpMg\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: Windows 10 10.0.22631
Binaries:
Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
Watchman: 20230416.213759.0 - D:\ReactNative\watchman-v2023.04.17.00-windows\bin\watchman.EXE
npmPackages:
expo: ~50.0.6 => 50.0.6
react: 18.2.0 => 18.2.0
react-native: 0.73.4 => 0.73.4
Expo Workflow: bare

### Minimal reproducible example

```
npx create-expo-app sdk50LocalBuild
cd sdk50LocalBuild
npx expo install expo-updates
npx expo run:android --device
```

**Comment by brentvatne** [comment]
hi there!

make sure you have installed and properly configured the correct jdk version on your machine: https://docs.expo.dev/guides/local-app-development/#android

**Comment by brentvatne** [comment]
@leons1767 - the error that you shared above would be unrelated to the nodejs version, but i'm glad you were able to resolve it!

**Comment by rafavalerio** [comment]
I am getting a similar error, but I am using EAS to build.

This is my GH action setup:

```YML
jobs:
  buildAndSubmit:
    name: Submit to app store
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 📦 Install dependencies
        run: yarn install
      - name: Fetch Google Services JSON key
        run: |
          mkdir .temp
          touch .temp/service-account-key.json
          echo "$SERVICE_ACCOUNT_KEY" > .temp/service-account-key.json
      - name: Build & Submit on EAS (${{ contains(github.base_ref, 'production') && 'Production' || 'UAT' }})
        run: eas build --platform all --profile ${{ contains(github.base_ref, 'production') && 'production' || 'uat' }} --non-interactive --auto-submit
```

Not sure what else I could try since I am using EAS to build? iOS builds fine.

**Comment by leons1767** [comment]
> I am getting a similar error, but I am using EAS to build.
> 
> This is my GH action setup:
> 
> ```yaml
> jobs:
>   buildAndSubmit:
>     name: Submit to app store
>     permissions:
>       contents: read
>     runs-on: ubuntu-latest
>     steps:
>       - uses: actions/checkout@v3
>       - uses: actions/setup-node@v3
>         with:
>           node-version: 18.x
>           cache: yarn
>       - name: 🏗 Setup Expo and EAS
>         uses: expo/expo-github-action@v8
>         with:
>           expo-version: latest
>           eas-version: latest
>           token: ${{ secrets.EXPO_TOKEN }}
>       - name: 📦 Install dependencies
>         run: yarn install
>       - name: Fetch Google Services JSON key
>         run: |
>           mkdir .temp
>           touch .temp/service-account-key.json
>           echo "$SERVICE_ACCOUNT_KEY" > .temp/service-account-key.json
>       - name: Build & Submit on EAS (${{ contains(github.base_ref, 'production') && 'Production' || 'UAT' }})
>         run: eas build --platform all --profile ${{ contains(github.base_ref, 'production') && 'production' || 'uat' }} --non-interactive --auto-submit
> ```
> 
> Not sure what else I could try since I am using EAS to build? iOS builds fine.

I don't have the same problem with EAS for Android. Maybe try building from terminal instead of GH, to eliminate any GH issue. BTW, there is a minor update for expo-updates@0.24.11, you may want to update it to see if it fixes the problem.

**Comment by toni1703** [comment]
Hello, i have an issue on 2 projects and all behave the same. If i have expo-updates grater then (> 0.24.8) the android build will crash at build process. if the expo-updates is 0.24.8 the build will be successful, but it will crash on real device. if after build process with expo-updates 0.24.8 i do an OTA with eas, then all is good.
