### ISSUE TITLE
I cannot build locally for android

### ISSUE THREAD

**Issue by naticio** [expo/expo#27236]
### Summary

as the eas queue for android takes forever, then I tried to build locally and it doesn't work. It used to work before now it's spitting errors left and right, why?

nat-serrano@Nats-MacBook-Pro-2 MaxineAI % eas build --platform android --local
★ eas-cli@7.3.0 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

Loaded "env" configuration for the "production" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/varia/
Specified value for "android.package" in app.json is ignored because an android directory was detected in the project.
EAS Build will use the value found in the native code.
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials 2pxoqSrDra (default)
ANDROID_NDK_HOME environment variable was not specified, continuing build without NDK
[SETUP_WORKINGDIR] Preparing workingdir /var/folders/9_/xqn4bxx955z6npf3wh5n74nw0000gn/T/eas-build-local-nodejs/603410e3-38a1-4b6f-b7b8-8a0c1c493fd9
[START_BUILD] Starting build
  "job": {
    "type": "generic",
    "platform": "android",
    "projectRootDirectory": ".",
    "projectArchive": {
      "type": "PATH",
      "path": "/var/folders/9_/xqn4bxx955z6npf3wh5n74nw0000gn/T/eas-cli-nodejs/6b30e3a6-91f1-4216-8c2a-ad395e96c0d5.tar.gz"
    },
    "builderEnvironment": {},
    "cache": {
      "disabled": false,
      "paths": [],
      "clear": false
    },
    "updates": {},
    "username": "naticio",
    "experimental": {},
    "mode": "build",
    "triggeredBy": "EAS_CLI"
  }
[READ_PACKAGE_JSON] Using package.json:
[READ_PACKAGE_JSON] {
  "name": "maxineai",
  "version": "1.0.1",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/webpack-config": "~19.0.1",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@types/react": "~18.2.45",
    "expo": "~50.0.6",
    "expo-asset": "~9.0.2",
    "expo-av": "^13.10.5",
    "expo-dev-client": "~3.3.8",
    "expo-file-system": "~16.0.6",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.4",
    "react-native-purchases": "^7.21.0",
    "react-native-quick-base64": "^2.0.8",
    "react-native-web": "~0.19.6",
    "typescript": "^5.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react-native": "^0.73.0"
  },
  "private": true
}
[INSTALL_DEPENDENCIES] Running "yarn install" in /var/folders/9_/xqn4bxx955z6npf3wh5n74nw0000gn/T/eas-build-local-nodejs/603410e3-38a1-4b6f-b7b8-8a0y
x[INSTALL_DEPENDENCIES] yarn install v1.22.21
[INSTALL_DEPENDENCIES] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mi.
[INSTALL_DEPENDENCIES] [1/4] Resolving packages...
[INSTALL_DEPENDENCIES] [2/4] Fetching packages...
[INSTALL_DEPENDENCIES] [3/4] Linking dependencies...
[INSTALL_DEPENDENCIES] warning "expo > @expo/metro-config@0.17.4" has unmet peer dependency "@react-native/babel-preset@*".
[INSTALL_DEPENDENCIES] warning "react-native > @react-native/codegen@0.73.3" has unmet peer dependency "@babel/preset-env@^7.1.6".
[INSTALL_DEPENDENCIES] warning Workspaces can only be enabled in private projects.
[INSTALL_DEPENDENCIES] [4/4] Building fresh packages...
[INSTALL_DEPENDENCIES] Done in 5.28s.
The NODE_ENV environment variable is required but was not specified. Ensure the project is bundled with Expo CLI or NODE_ENV is set.
Proceeding without mode-specific .env
env: load .env
env: export EXPO_PUBLIC_11LABS_API_KEY EXPO_PUBLIC_SD_URL EXPO_PUBLIC_LLM_URL EXPO_PUBLIC_RC_ANDROID_KEY EXPO_PUBLIC_RC_IOS_KEY
[READ_APP_CONFIG] Using app configuration:
[READ_APP_CONFIG] {
  "name": "MaxineAI",
  "slug": "MaxineAI",
  "version": "1.0.1",
  "orientation": "portrait",
  "icon": "./assets/icon.png",
  "userInterfaceStyle": "light",
  "splash": {
    "image": "./assets/splash.png",
    "resizeMode": "contain",
    "backgroundColor": "#ffffff"
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "ios": {
    "supportsTablet": true,
    "bundleIdentifier": "APTRT.Maxi-IOS"
  },
  "android": {
    "versionCode": 2,
    "adaptiveIcon": {
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#ffffff"
    },
    "package": "com.APTRT.Maxine"
  },
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "extra": {
    "eas": {
      "projectId": "8959a3aa-c7f1-4960-9c48-9063b9d38f92"
    }
  },
  "sdkVersion": "50.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ]
}
[RUN_EXPO_DOCTOR] Running "expo doctor"
[RUN_EXPO_DOCTOR] Running 11 checks on your project...
[RUN_EXPO_DOCTOR] ✔ Check Expo config for common issues
[RUN_EXPO_DOCTOR] ✔ Check package.json for common issues
[RUN_EXPO_DOCTOR] ✖ Check dependencies for packages that should not be installed directly
[RUN_EXPO_DOCTOR] ✖ Check for common project setup issues
[RUN_EXPO_DOCTOR] ✔ Check npm/ yarn versions
[RUN_EXPO_DOCTOR] ✔ Check for issues with metro config
[RUN_EXPO_DOCTOR] ✔ Check Expo config (app.json/ app.config.js) schema
[RUN_EXPO_DOCTOR] ✔ Check that native modules do not use incompatible support packages
[RUN_EXPO_DOCTOR] ✔ Check for legacy global CLI installed locally
[RUN_EXPO_DOCTOR] ✖ Check that packages match versions required by installed Expo SDK
[RUN_EXPO_DOCTOR] ✔ Check that native modules use compatible support package versions for installed Expo SDK
[RUN_EXPO_DOCTOR] Detailed check results:
[RUN_EXPO_DOCTOR] Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
[RUN_EXPO_DOCTOR] The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native".
[RUN_EXPO_DOCTOR] This project has multiple package manager lock files (yarn.lock, package-lock.json). This may cause EAS build to restore dependenc.
[RUN_EXPO_DOCTOR] The following packages should be updated for best compatibility with the installed expo version:
[RUN_EXPO_DOCTOR]   @react-native-async-storage/async-storage@1.22.0 - expected version: 1.21.0
[RUN_EXPO_DOCTOR]   expo@50.0.6 - expected version: ~50.0.7
[RUN_EXPO_DOCTOR] Your project may not work correctly until you install the correct versions of the packages.
[RUN_EXPO_DOCTOR] Found outdated dependencies
[RUN_EXPO_DOCTOR] One or more checks failed, indicating possible issues with the project.
[RUN_EXPO_DOCTOR] Command "expo doctor" failed.
Error: npx -y expo-doctor exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at runExpoDoctor (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/build-tools/dist/common/setup.js:98:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/build-tools/dist/common/setup.js:71:36
    at async BuildContext.runBuildPhase (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/build-tools/dist/context.js:98:28)
    at async setupAsync (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/build-tools/dist/common/setup.js:69:9)
    at async buildAsync (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/build-tools/dist/builders/android.js:38:5)
    at async runBuilderWithHooksAsync (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.androidBuilder (/Users/nat-serrano/.npm/_npx/994d822063d9f19d/node_modules/@expo/build-tools/dist/builders/android.js:24:16)
[PREBUILD] Skipped running "expo prebuild" because the "android" directory already exists. Learn more about the build process: https://docs.expo.dev/
[PREPARE_CREDENTIALS] Writing secrets to the project's directory
[PREPARE_CREDENTIALS] Injecting signing config into build.gradle
[RUN_GRADLEW] Running 'gradlew :app:bundleRelease' in /var/folders/9_/xqn4bxx955z6npf3wh5n74nw0000gn/T/eas-build-local-nodejs/603410e3-38a1-4b6f-b7bd
[RUN_GRADLEW] > Task :expo-dev-launcher-gradle-plugin:pluginDescriptors
[RUN_GRADLEW] > Task :expo-dev-launcher-gradle-plugin:processResources
[RUN_GRADLEW] > Task :gradle-plugin:pluginDescriptors
[RUN_GRADLEW] > Task :gradle-plugin:processResources
[RUN_GRADLEW] > Task :expo-dev-launcher-gradle-plugin:compileKotlin
[RUN_GRADLEW] > Task :expo-dev-launcher-gradle-plugin:compileJava NO-SOURCE
[RUN_GRADLEW] > Task :expo-dev-launcher-gradle-plugin:classes
[RUN_GRADLEW] > Task :expo-dev-launcher-gradle-plugin:jar
[RUN_GRADLEW] > Task :expo-dev-launcher-gradle-plugin:inspectClassesForKotlinIC
[RUN_GRADLEW] > Task :gradle-plugin:compileKotlin
[RUN_GRADLEW] > Task :gradle-plugin:compileJava NO-SOURCE
[RUN_GRADLEW] > Task :gradle-plugin:classes
[RUN_GRADLEW] > Task :gradle-plugin:jar
[RUN_GRADLEW] > Task :gradle-plugin:inspectClassesForKotlinIC
[RUN_GRADLEW] > Configure project :app
[RUN_GRADLEW] ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@3.6.6)
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Script '/private/var/folders/9_/xqn4bxx955z6npf3wh5n74nw0000gn/T/eas-build-local-nodejs/603410e3-38a1-4b6f-b7b8-8a0c1c493fd9/build/nod7
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating project ':expo'.
[RUN_GRADLEW] > A problem occurred configuring project ':expo-av'.
[RUN_GRADLEW]    > SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in y.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Script '/private/var/folders/9_/xqn4bxx955z6npf3wh5n74nw0000gn/T/eas-build-local-nodejs/603410e3-38a1-4b6f-b7b8-8a0c1c493fd9/build/nod5
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred configuring project ':expo'.
[RUN_GRADLEW] > Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareCo.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] BUILD FAILED in 13s
[RUN_GRADLEW] 10 actionable tasks: 10 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "name": "maxineai",
  "version": "1.0.1",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/webpack-config": "~19.0.1",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@types/react": "~18.2.45",
    "expo": "~50.0.6",
    "expo-asset": "~9.0.2",
    "expo-av": "^13.10.5",
    "expo-dev-client": "~3.3.8",
    "expo-file-system": "~16.0.6",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.4",
    "react-native-purchases": "^7.21.0",
    "react-native-quick-base64": "^2.0.8",
    "react-native-web": "~0.19.6",
    "typescript": "^5.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react-native": "^0.73.0"
  },
  "private": true
}

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1 
      expo: ~50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Reproducible demo

eas build --platform android --local

**Comment by naticio** [comment]
I uninstalled this and  worked
@types/react-native
