### ISSUE TITLE
[expo-media-library] Out Of Memory after calling getAssetsAsync

### ISSUE THREAD

**Issue by swizes** [expo/expo#27308]
### Minimal reproducible example

https://github.com/swizes/media-lib-oom

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

We have one user, who has Galaxy S23 Android 14 phone. When we try to list the albums with thumbnails, user faces with OOM crash.

We are using the 1st asset of the album as thumbnail source. We fetch the uri by fetching 1 asset via getAssetsAsync.

We run a for loop for the albums we have 

```
for (const album of albumsWithAtLeastOneAsset) {
            const albumData = {
                id: album.id,
                title: album.title,
                count: album.assetCount,
                image: await getAlbumThumbnail(album, mediaType),
            };
            result.push(albumData);
        }
```
and call `getAlbumThumbnail` method for each album

```
export const getAlbumThumbnail = async (
    album: Album,
    mediaType: AssetsOptions['mediaType'],
) => {
    try {
        const albumAssets = await getAssetsAsync({
            first: 1,
            album: album.id,
            mediaType,
            sortBy: SortBy.creationTime,
        });

        return albumAssets?.assets[0]?.uri || '';
    } catch (error) {
        throw error;
    }
};
```

### Crashlytics Stack Trace:
It appears to be happening in `expo.modules.medialibrary.assets.AssetUtilsKt.putAssetsInfo (AssetUtils.kt:114)`

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 163840016 byte allocation with 25165824 free bytes and 154MB until OOM, target footprint 131684768, growth limit 268435456
       at java.io.BufferedInputStream.fill(BufferedInputStream.java:225)
       at java.io.BufferedInputStream.skip(BufferedInputStream.java:373)
       at java.io.FilterInputStream.skip(FilterInputStream.java:150)
       at androidx.exifinterface.media.ExifInterface$ByteOrderedDataInputStream.skipFully(ExifInterface.java:7874)
       at androidx.exifinterface.media.ExifInterface.parseTiffHeaders(ExifInterface.java:6796)
       at androidx.exifinterface.media.ExifInterface.getRawAttributes(ExifInterface.java:5711)
       at androidx.exifinterface.media.ExifInterface.loadAttributes(ExifInterface.java:4601)
       at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5294)
       at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3955)
       at expo.modules.medialibrary.assets.AssetUtilsKt.putAssetsInfo(AssetUtils.kt:114)
       at expo.modules.medialibrary.assets.GetAssets.execute(GetAssets.kt:36)
       at expo.modules.medialibrary.MediaLibraryModule$definition$lambda-47$lambda-31$lambda-30$$inlined$withModuleScope$1.invokeSuspend(MediaLibraryModule.kt:487)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

[oom-stacktrace.txt](https://github.com/expo/expo/files/14414780/oom-stacktrace.txt)

![image](https://github.com/expo/expo/assets/8876645/99ba6b7f-87f0-4d5b-acf9-f5f0833c961b)

The issue does not occur on every user and we can't reproduce it.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.1 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/........./bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 29, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.71.11 => 0.71.13 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by matrak-jason** [comment]
I am setting this too after switching to ImagePicker from a the old 'expo-image-picker-multiple'.

I'm not sure this should be closed.

It's only happening on Android 14 too.
