### ISSUE TITLE
[docs] Expo-Notifications

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#27328]
### Summary

states to install expo-notifications:

```
{
  "expo": {
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./local/assets/notification-icon.png",
          "color": "#ffffff",
          "sounds": [
            "./local/assets/notification-sound.wav",
            "./local/assets/notification-sound-other.wav"
          ]
        }
      ]
    ]
  }
}
```

When doing so:

```
Starting project at /Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev
PluginError: Plugin is an unexpected type: object
PluginError: Plugin is an unexpected type: object
    at withStaticPlugin (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:132:11)
    at /Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:18)
    at withConfigPlugins (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/config/build/plugins/withConfigPlugins.js:36:47)
    at fillAndReturnConfig (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/config/build/Config.js:218:78)
    at getConfig (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/config/build/Config.js:274:10)
    at startAsync (/Users/nilsbaumgartner/Documents/GitHub/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/cli/build/src/start/startAsync.js:94
```

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/notifications/

### Anything else?

Also shown by the IDE.

**Comment by NilsBaumgartner1994** [comment]
Any new updates on this how to use the expo plugins section?

**Comment by krazykriskomar** [comment]
This happened to me and what had happened is my linter somehow put parens () around one of the array items in the plugin array. Dunno how/why. Look for ([ "some plugin" ])
