### ISSUE TITLE
After Expo 50 & RN 73 upgrade iOS build fails at Install Pods step: Unable to find a specification for ExpoModulesCore

### ISSUE THREAD

**Issue by x-tba** [expo/expo#27411]
### Minimal reproducible example

https://github.com/x-tba/expo-upgrade-issue

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I’m in the process of upgrading my Expo Managed React native app from React-native "0.72.10" to "0.73.4" and Expo “49.0.7” to “50.0.8”. I was able to successfully run the app using Expo Go and also build the Android internal distribution build using EAS. 
When trying to build the iOS build locally and also using EAS I’m getting the below error.

[!] Unable to find a specification for `ExpoModulesCore` depended upon by `ExpoLocalAuthentication`

Below is the error log,

```
[INSTALL_PODS] Using Expo modules
[INSTALL_PODS] [Expo] Enabling modular headers for pod ExpoModulesCore
[INSTALL_PODS] Auto-linking React Native modules for target `expoupgradeissue`: Expo, RNCAsyncStorage, RNFlashList, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNVectorIcons, react-native-get-random-values, react-native-netinfo, react-native-pager-view, react-native-safe-area-context, react-native-slider, and react-native-webview
[INSTALL_PODS] Framework build type is static library
[INSTALL_PODS] [Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[INSTALL_PODS] [Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
[INSTALL_PODS] Analyzing dependencies
[INSTALL_PODS] Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[INSTALL_PODS] [Codegen] Found FBReactNativeSpec
[INSTALL_PODS] Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[INSTALL_PODS] [Codegen] Found rncore
[INSTALL_PODS] Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
[INSTALL_PODS] Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[INSTALL_PODS] Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[INSTALL_PODS] [Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.4/react-native-artifacts-0.73.4-hermes-ios-debug.tar.gz
[INSTALL_PODS] % Total    % Received
[INSTALL_PODS] % Xferd  Average Speed   Time    Time     Time  Current
[INSTALL_PODS]                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-
[INSTALL_PODS] -     0
[INSTALL_PODS] 0     0    0
[INSTALL_PODS] 0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[INSTALL_PODS] 2 16.2M    2  359k    0
[INSTALL_PODS] 0   247k      0  0:01:07  0:00:01  0:01:06  247k
[INSTALL_PODS] 47 16.2M   47 7927k    0     0  3231k      0  0:
[INSTALL_PODS] 00:05  0:00:02  0:00:03 3231k
[INSTALL_PODS] 100 16.2M  100 16.2M
[INSTALL_PODS] 0     0  5259k      0  0:00:03  0:00:03 --:--:-- 5260k
[INSTALL_PODS] % Total    % Rece
[INSTALL_PODS] ived % Xferd  Average Speed   Time    Time     Time  Current
[INSTALL_PODS]                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0
[INSTALL_PODS] 0      0 --:--:-- --:--:-- --:--:--     0
[INSTALL_PODS] 0     0    0     0    0
[INSTALL_PODS] 0      0      0 --:--:-- --:--:-- --:--:--     0
[INSTALL_PODS] 1 12.3M    1  1
[INSTALL_PODS] 43k    0     0   114k      0  0:01:50  0:00:01  0:01:49  114k
[INSTALL_PODS] 41 12.3M   41 5295k    0     0  2324k      0
[INSTALL_PODS] 0:00:05  0:00:02  0:00:03 2324k
[INSTALL_PODS] 100 12.3M  100 12.3M    0     0
[INSTALL_PODS] 4831k      0  0:00:02  0:00:02 --:--:-- 4831k
[INSTALL_PODS] [!] Unable to find a specification for `ExpoModulesCore` depended upon by `ExpoLocalAuthentication`
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.
[INSTALL_PODS] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `90A3B477F7E8421A97640A21` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
[INSTALL_PODS] 
Error: pod install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at installPods (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/build-tools/dist/ios/pod.js:11:38)
    at /Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/build-tools/dist/builders/ios.js:69:41
    at BuildContext.runBuildPhase (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/build-tools/dist/context.js:98:34)
    at buildAsync (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/build-tools/dist/builders/ios.js:68:19)
    at async runBuilderWithHooksAsync (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.iosBuilder (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/@expo/build-tools/dist/builders/ios.js:28:16)
    at async buildIosAsync (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/eas-cli-local-build-plugin/dist/ios.js:66:12)
    at async buildAsync (/Users/thanushka/.npm/_npx/1a85490733db6fa1/node_modules/eas-cli-local-build-plugin/dist/build.js:56:29)

Build failed
Unknown error. See logs of the Install pods build phase for more information.
```

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/opt/node@20/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/opt/node@20/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.1, 34.0.0
        System Images: android-33 | Google Play Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: managed
`

### Expo Doctor Diagnostics

```
npx expo-doctor 
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by x-tba** [comment]
Issue seems to be with expo-web-browser as it's a peer dependency of expo-auth-session which uses "expo-web-browser": "~12.8.0"
The issue was resolved after downgrading to "expo-web-browser": "~12.8.0" from "expo-web-browser": "~12.8.2" and deleting package-lock.json
