### ISSUE TITLE
expo update with termux 

### ISSUE THREAD

**Issue by 1-AlenToma** [expo/expo#27624]
### Summary

so I have build an app on my mobile using termux acode ide. 

now using eas build on the expo works just fine but wanted to implement expo update too.

When I run `eas update` using termux I get the following error
```
eas update
✔ No branches found. Provide a branch name: … main
✔ Provide an update message: … better design
[expo-cli] Starting Metro Bundler
[expo-cli]
[expo-cli] Failed to generate Hermes bytecode for: /data/data/com.termux/files/home/Novelo/node_modules/expo/AppEntry.js
[expo-cli] iOS Bundling failed 191006ms (node_modules/expo/AppEntry.js)
[expo-cli]
[expo-cli]
[expo-cli] Error: Unsupported host platform for Hermes compiler: android
[expo-cli] Error: Unsupported host platform for Hermes compiler: android
[expo-cli]     at getHermesCommandPlatform (/data/data/com.termux/files/home/Novelo/node_modules/@expo/metro-config/src/serializer/exportHermes.ts:46:13)
[expo-cli]     at importHermesCommandFromProject (/data/data/com.termux/files/home/Novelo/node_modules/@expo/metro-config/src/serializer/exportHermes.ts:12:30)
[expo-cli]     at directlyBuildHermesBundleAsync (/data/data/com.termux/files/home/Novelo/node_modules/@expo/metro-config/src/serializer/exportHermes.ts:94:27)
✖ Export failed
/data/data/com.termux/files/home/Novelo/node_modules/expo/bin/cli exited with non-zero code: 1
    Error: update command failed.
```

I am able to run `npx expo start` and using expo go able to debugg it just find, so what is the issue above?

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: android
    Binaries:
      Node: 20.2.0 - /data/data/com.termux/files/usr/bin/node
      Yarn: 1.22.21 - /data/data/com.termux/files/usr/bin/yarn
      npm: 9.6.6 - /data/data/com.termux/files/usr/bin/npm
    npmPackages:
      expo: ^50.0.4 => 50.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    npmGlobalPackages:
      eas-cli: 7.5.0
      expo-cli: 6.3.10
    Expo Workflow: bare

```

### Minimal reproducible example

```
here is the app, just run expo update on mobile using termux
```

[Novelo](https://github.com/1-AlenToma/Novelo)

**Comment by 1-AlenToma** [comment]
you cannot test this on stack, it is an issue when using the cli with termux on mobile, please have someone co.firm this
