### ISSUE TITLE
SDK 50.0.13 - Deprecated Gradle features were used

### ISSUE THREAD

**Issue by jppradoleal** [expo/expo#27718]
### Minimal reproducible example

https://github.com/jppradoleal/bp-react-native-paper-redux-firebase

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When I try to run the app from the native sources (npx expo prebuild --clean && npx expo run:android) it throws lots of warning and it fails, here's the complete crash log.

```
› Building app...
Configuration on demand is an incubating feature.

> Configure project :app
 ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@3.6.8)

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 32.7.2
:react-native-firebase_app:play.play-services-auth using default value: 20.7.0
:react-native-firebase_app package.json found at /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 19.0.1 (19,0,1 - 19000001)
:react-native-firebase_app:android.compileSdk using custom value: 34
:react-native-firebase_app:android.targetSdk using custom value: 34
:react-native-firebase_app:android.minSdk using custom value: 23
:react-native-firebase_app:reactNativeAndroidDir /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/react-native/android

> Configure project :react-native-firebase_auth
:react-native-firebase_auth package.json found at /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_app package.json found at /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_auth:firebase.bom using default value: 32.7.2
:react-native-firebase_auth package.json found at /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@react-native-firebase/auth/package.json
:react-native-firebase_auth:version set from package.json: 19.0.1 (19,0,1 - 19000001)
:react-native-firebase_auth:android.compileSdk using custom value: 34
:react-native-firebase_auth:android.targetSdk using custom value: 34
:react-native-firebase_auth:android.minSdk using custom value: 23
:react-native-firebase_auth:reactNativeAndroidDir /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/react-native/android

> Configure project :expo

Using expo modules
  - expo-constants (15.4.5)
  - expo-dev-client (3.3.10)
  - expo-dev-launcher (3.6.8)
  - expo-dev-menu (4.5.7)
  - expo-file-system (16.0.8)
  - expo-font (11.10.3)
  - expo-json-utils (0.12.3)
  - expo-keep-awake (12.8.2)
  - expo-manifests (0.13.2)
  - expo-modules-core (1.11.12)
  - expo-modules-core$android-annotation (1.11.12)
  - expo-modules-core$android-annotation-processor (1.11.12)
  - expo-splash-screen (0.26.4)


> Task :react-native-firebase_app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase_app:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-firebase_app:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /home/jpprado/Android/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /home/jpprado/.sdkman/candidates/java/21-open/bin/jlink with arguments {--module-path /home/jpprado/.gradle/caches/transforms-3/89aeb64341c8ed90285a353acc7ef035/transformed/output/temp/jmod --add-modules java.base --output /home/jpprado/.gradle/caches/transforms-3/89aeb64341c8ed90285a353acc7ef035/transformed/output/jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 18s
260 actionable tasks: 48 executed, 202 from cache, 10 up-to-date
Error: /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/android/gradlew exited with non-zero code: 1
Error: /home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at Object.spawnAsync [as default] (/home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/home/jpprado/Documents/ws-self/bp-react-native-paper-redux-firebase/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24)
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.19.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 33.0.1, 33.0.2, 34.0.0
        System Images: android-30 | AOSP ATD Intel x86 Atom, android-30 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ^50.0.13 => 50.0.13
      react: 18.2.0 => 18.2.0
      react-native: 0.73.5 => 0.73.5
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check native tooling versions
✔ Check npm/ yarn versions
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.

One or more checks failed, indicating possible issues with the project.

**Comment by alanjhughes** [comment]
Hi @jppradoleal - You are using Java 21 which is not supported by AGP. You need to use Java 17.

**Comment by alanjhughes** [comment]
@wp-coin adding an emoji to a comment isn't useful. Provide some  details in a new issue and a reproduction. If the error is the exact same, then you are not using Java 17.
