### ISSUE TITLE
Running web version, getting an error: Metro error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by elyran** [expo/expo#27720]
### Summary

Hi,

After a clean install, getting that error.
```
$ node -v
v20.11.1
$ pnpm -v
8.15.4
```

Used the instructions at https://docs.expo.dev/get-started/installation/ .
```
user1@user1-pc:~/tmp$ pnpm dlx create-expo-app --template
user1@user1-pc:~/tmp$ cd expo-test-app-3
user1@user1-pc:~/tmp/expo-test-app-3$ pnpm run web
```

This is the output:
```
› Metro waiting on exp://10.0.2.11:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:8081

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Web Bundling failed 24384ms (node_modules/.pnpm/expo-router@3.4.8_expo-constants@15.4.5_expo-linking@6.2.2_expo-modules-autolinking@1.10.3_ex_lnqiyb25mqt2osf3juqdgfrjma/node_modules/expo-router/entry.js)
Unable to resolve "@babel/runtime/helpers/interopRequireDefault" from "app/+not-found.tsx"
λ node_modules/.pnpm/expo-router@3.4.8_expo-constants@15.4.5_expo-linking@6.2.2_expo-modules-autolinking@1.10.3_ex_lnqiyb25mqt2osf3juqdgfrjma/node_modules/ex
po-router/node/render.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 94.6% (815/838)Error: ENOENT: no such file or directory, open '/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/@expo+server@0.3.1/node_modules/@expo/server/src/index.ts'
    at Object.readFileSync (node:fs:453:20)
    at getCodeFrame (/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/metro@0.80.6/node_modules/metro/src/Server.js:868:18)
    at Server._symbolicate (/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/metro@0.80.6/node_modules/metro/src/Server.js:945:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Server._processRequest (/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/metro@0.80.6/node_modules/metro/src/Server.js:394:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/@expo+server@0.3.1/node_modules/@expo/server/src/index.ts'
}
Error: ENOENT: no such file or directory, open '/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/@expo+server@0.3.1/node_modules/@expo/server/src/vendor/http.ts'
    at Object.readFileSync (node:fs:453:20)
    at getCodeFrame (/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/metro@0.80.6/node_modules/metro/src/Server.js:868:18)
    at Server._symbolicate (/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/metro@0.80.6/node_modules/metro/src/Server.js:945:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Server._processRequest (/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/metro@0.80.6/node_modules/metro/src/Server.js:394:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user1/tmp/expo-test-app-3/node_modules/.pnpm/@expo+server@0.3.1/node_modules/@expo/server/src/vendor/http.ts'
λ node_modules/.pnpm/expo-router@3.4.8_expo-constants@15.4.5_expo-linking@6.2.2_expo-modules-autolinking@1.10.3_ex_lnqiyb25mqt2osf3juqdgfrjma/node_modules/ex
po-router/node/render.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 97.2% (831/843)
Metro error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /home/user1/tmp/expo-test-app-3/app/+not-found.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  node_modules
> 1 | import { Link, Stack } from 'expo-router';
    | ^
  2 | import { StyleSheet } from 'react-native';
  3 |
  4 | import { Text, View } from '@/components/Themed';


Call Stack
  MetroBundlerDevServer.getStaticResourcesAsync (node_modules/.pnpm/@expo+cli@0.17.8_@react-native+babel-preset@0.73.21_expo-modules-autolinking@1.10.3/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:294:13)
  processTicksAndRejections (node:internal/process/task_queues)
  MetroBundlerDevServer.getStaticPageAsync (node_modules/.pnpm/@expo+cli@0.17.8_@react-native+babel-preset@0.73.21_expo-modules-autolinking@1.10.3/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:351:52)
  getHtml (node_modules/.pnpm/@expo+cli@0.17.8_@react-native+babel-preset@0.73.21_expo-modules-autolinking@1.10.3/node_modules/@expo/cli/src/start/server/metro/createServerRouteMiddleware.ts:78:31)
  handler (node_modules/.pnpm/@expo+server@0.3.1/node_modules/@expo/server/src/index.ts:149:26)
λ Bundling failed 24755ms (node_modules/.pnpm/expo-router@3.4.8_expo-constants@15.4.5_expo-linking@6.2.2_expo-modules-autolinking@1.10.3_ex_lnqiyb25mqt2osf3juqdgfrjma/node_modules/expo-router/node/render.js)
Unable to resolve "@babel/runtime/helpers/interopRequireDefault" from "app/(tabs)/index.tsx"
Web Bundled 5459ms (node_modules/.pnpm/expo-router@3.4.8_expo-constants@15.4.5_expo-linking@6.2.2_expo-modules-autolinking@1.10.3_ex_lnqiyb25mqt2osf3juqdgfrjma/node_modules/expo-router/_error.js)
```

Secondly, tried to manually `pnpm add ...` (more than once) but getting an error on the browser, something about a network error.

What am I missing? Followed the instructions 1:1.

### Environment

```
user1@user1-pc:~/tmp/expo-test-app-3$ pnpm dlx expo-env-info
Packages: +2
++
Progress: resolved 2, reused 1, downloaded 1, added 2, done

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 20.11.1 - ~/.local/share/pnpm/node
      Yarn: 1.22.21 - ~/.local/share/pnpm/yarn
      npm: 10.2.4 - ~/.local/share/pnpm/npm
    npmPackages:
      expo: ~50.0.13 => 50.0.13 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

```

### Minimal reproducible example

Just execute these:
```
user1@user1-pc:~/tmp$ pnpm dlx create-expo-app --template
user1@user1-pc:~/tmp$ cd expo-test-app-3
user1@user1-pc:~/tmp/expo-test-app-3$ pnpm run web

```

**Comment by Kudo** [comment]
hi there! for pnpm, could you try to add `node-linker=hoisted` to **.npmrc.** as mentioned [here](https://docs.expo.dev/guides/monorepos/#can-i-use-another-monorepo-tool-instead-of-yarn-workspaces)? i am afraid that we are not fully support pnpm isolated mode at the moment.

**Comment by byCedric** [comment]
This issue specifically comes from Metro: https://github.com/facebook/metro/issues/1047#issuecomment-1657200840

**Comment by elyran** [comment]
@Kudo tried, did not work.

I had to install two additional packages just for the **Android** app to work (gave up on web, for now).

**Comment by elyran** [comment]
I am wondering - is Expo production ready?
Compiling issues, runtime issues, integration issues (had to point the emulator to the right IP, because the automatically provided one was wrong)...
Apologize if that's implies underestimation of your hard work. Definitely not intended :heart: 
Because I didn't do anything special, just followed the instructions.
Currently it seems Expo does not work out of the box. That's something I wouldn't expect from a mature framework such as Expo.

Any clue?

**Comment by Kudo** [comment]
i would say we don't fully support pnpm right now. to save your time struggling issue. please try yarn or npm instead. use `npx create-expo-app@latest` to create your app.

for the other problems, i can totally understand your pain point for setup all of these. i'd happy to help if you could describe all the other problems in details.

**Comment by elyran** [comment]
no problem, i can avoid pnpm here. what bothers me is that the TS template doesn't work out of the box.
the "standard" JS template does work, however. but, even that JS template, Metro launches the Android emulator using the wrong IP so currently i manually point it.

does everything works out of the box for you? i wonder if it's a local issue with my env.

**Comment by elyran** [comment]
hi, i'll try:

> hi there!
> 
> would be if you could elaborate the details for each problems.
> 
> > ts template
> 
> * what's the "doesn't work"? any error messages?
as wrote, many compilation / bundling errors. i have to manually install packages, as mentioned earlier.
> * how did you initiate the project?
also, as said: `npx create-expo-app --template`
then choosing TS navigation.
> 
> > android emulator ip
> 
> * what's the wrong ip and what's the correct ip?
wrong: exp://10.0.2.11:8081
right: exp://10.0.2.2:8081 (this IP is the emulator's gateway, as seen from within the emulator).
> * are there any special network environment, e.g. WSL?
network behind a Fortinet, could the source to that problem.

anyway it seems to work now.
not sure what it was, but it was a consistent problem (web and Android).
for now i'm closing it, as i can provide no more info (it works).
thanks anyway
