### ISSUE TITLE
Update dotenv-expand to fix critical error in SDK50

### ISSUE THREAD

**Issue by daniel-xyz** [expo/expo#27755]
### Summary

Me and another discord user experienced issues when we updated to SDK 50 or started a new project with SDK 50. npx commands like `npx expo start` or `npx expo install --fix` throw `JavaScript heap out of memory` errors. After manually increasing the heap size the following error appears:

```
RangeError: Maximum call stack size exceeded
    at RegExpStringIterator.next (<anonymous>)
    at Function.from (<anonymous>)
    at _searchLast (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:5:25)
    at _interpolate (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:12:40)
    at _interpolate (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/Volumes/git/myapp/node_modules/dotenv-expand/lib/main.js:38:12)
 ```

We could find a workaround by overriding a dependency in the package.json:

```
  "overrides": {
    "@expo/env": {
      "dotenv-expand": "11.0.6"
    }
  },
```

It might be related to [this issue ](https://github.com/motdotla/dotenv-expand/issues/98) but since it happens to a newly created SDK 50 project without any .env variables it's hard to say - maybe expo sets some default variables internally. Anyway, it seems to be fixed with a simple version bump.

### SDK Version

50

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      npm: 10.5.0 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.13 => 50.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
    Expo Workflow: managed

### Minimal reproducible example

1. Create new app: `npx create-expo-app --template`
2. Select "Blank" project in the CLI
3. Run `npx expo start`

**Comment by byCedric** [comment]
We just merged the fix (upgrading `dotenv-expand`), still need to backport it to SDK 50 though so bear with us 😄 

At least this is fixed now for SDK 51+.
