### ISSUE TITLE
Expo 50 and expo-router doesn't work in monorepo

### ISSUE THREAD

**Issue by mtzfactory** [expo/expo#28108]
### Minimal reproducible example

https://github.com/mtzfactory/expo-sdk-50-with-router-monorepo

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

I faced a problem upgrading an existing expo app from sdk 49 to sdk 50 in a monorepo setup, the reported error stated it wasn't able to import the modules declared in the yarn workspaces...

I created a new application from scratch and moved it to a monorepo configuration following [this expo guide](https://docs.expo.dev/guides/monorepos/) and faced the very same problem.

Am I missing something?

The error differs from web and native:

When I try to execute in native I get this:

```
Metro has encountered an error: While trying to resolve module `@monorepo/cool-package` from file `/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/src/app/index.tsx`, the package `/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@monorepo/cool-package/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@monorepo/cool-package/index.js`. Indeed, none of these files exist:

  * /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@monorepo/cool-package/index.js(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css)
  * /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@monorepo/cool-package/index.js/index(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css): /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/node-haste/DependencyGraph.js (243:17)

  241 |         }
  242 |         if (error instanceof InvalidPackageError) {
> 243 |           throw new PackageResolutionError({
      |                 ^
  244 |             packageError: error,
  245 |             originModulePath: from,
  246 |             targetModuleName: to,

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

When I try to execute in web I get this:

```
{
  "originModulePath": "/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/.",
  "targetModuleName": "./node_modules/expo-router/entry",
  "message": "Unable to resolve module ./node_modules/expo-router/entry from /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/.: \n\nNone of these files exist:\n  * node_modules/expo-router/entry(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n  * node_modules/expo-router/entry/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)",
  "cause": {
    "candidates": {
      "file": {
        "type": "sourceFile",
        "filePathPrefix": "node_modules/expo-router/entry",
        "candidateExts": [
          "",
          ".web.ts",
          ".ts",
          ".web.tsx",
          ".tsx",
          ".web.mjs",
          ".mjs",
          ".web.js",
          ".js",
          ".web.jsx",
          ".jsx",
          ".web.json",
          ".json",
          ".web.cjs",
          ".cjs",
          ".web.scss",
          ".scss",
          ".web.sass",
          ".sass",
          ".web.css",
          ".css"
        ]
      },
      "dir": {
        "type": "sourceFile",
        "filePathPrefix": "node_modules/expo-router/entry/index",
        "candidateExts": [
          "",
          ".web.ts",
          ".ts",
          ".web.tsx",
          ".tsx",
          ".web.mjs",
          ".mjs",
          ".web.js",
          ".js",
          ".web.jsx",
          ".jsx",
          ".web.json",
          ".json",
          ".web.cjs",
          ".cjs",
          ".web.scss",
          ".scss",
          ".web.sass",
          ".sass",
          ".web.css",
          ".css"
        ]
      }
    },
    "name": "Error",
    "message": "The module could not be resolved because none of these files exist:\n\n  * /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/node_modules/expo-router/entry(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n  * /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/node_modules/expo-router/entry/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)",
    "stack": "Error: The module could not be resolved because none of these files exist:\n\n  * /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/node_modules/expo-router/entry(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n  * /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/node_modules/expo-router/entry/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n    at upstreamResolveRequest (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro-resolver/src/resolve.js:44:13)\n    at resolveRequest (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:94:20)\n    at upstreamResolveRequest (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro-resolver/src/resolve.js:32:12)\n    at firstResolver (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:94:20)\n    at firstResolver (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:108:16)\n    at resolveRequest (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:137:16)\n    at Object.resolve (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro-resolver/src/resolve.js:32:12)\n    at ModuleResolver.resolveDependency (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:73:31)\n    at DependencyGraph.resolveDependency (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)\n    at /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/lib/transformHelpers.js:156:21"
  },
  "errors": [
    {
      "description": "Unable to resolve module ./node_modules/expo-router/entry from /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/.: \n\nNone of these files exist:\n  * node_modules/expo-router/entry(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n  * node_modules/expo-router/entry/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)"
    }
  ],
  "name": "Error",
  "stack": "Error: Unable to resolve module ./node_modules/expo-router/entry from /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/.: \n\nNone of these files exist:\n  * node_modules/expo-router/entry(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n  * node_modules/expo-router/entry/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n    at ModuleResolver.resolveDependency (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)\n    at DependencyGraph.resolveDependency (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)\n    at /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/lib/transformHelpers.js:156:21\n    at Server._resolveRelativePath (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/Server.js:1023:12)\n    at Server.requestProcessor [as _processBundleRequest] (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/Server.js:423:33)\n    at Server._processRequest (/Users/rmartinez/development/personal/temp/react-native/expo-monorepo/node_modules/metro/src/Server.js:360:7)"
}
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.1 - ~/.nvm/versions/node/v18.20.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.1/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/rmartinez/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by mtzfactory** [comment]
I've checked that the workspaces are linked in `node_modules`:

```
❯ pwd
/Users/rmartinez/development/personal/temp/react-native/expo-monorepo
❯ ls node_modules/@monorepo
total 0
63667765 0 drwxr-xr-x    4 rmartinez  staff    128 Apr  8 14:04 .
63667474 0 drwxr-xr-x  718 rmartinez  staff  22976 Apr  8 14:04 ..
63715730 0 lrwxr-xr-x    1 rmartinez  staff     15 Apr  8 14:04 app -> ../../apps/expo
63715729 0 lrwxr-xr-x    1 rmartinez  staff     27 Apr  8 14:04 cool-package -> ../../packages/cool-package
❯ ls node_modules/@monorepo/cool-package/
total 24
63622857 0 drwxr-xr-x  5 rmartinez  staff  160 Apr  8 14:13 .
63622137 0 drwxr-xr-x  3 rmartinez  staff   96 Apr  8 13:47 ..
63623037 8 -rw-r--r--  1 rmartinez  staff   34 Apr  8 13:48 index.ts
63622939 8 -rw-r--r--  1 rmartinez  staff  158 Apr  8 14:14 package.json
63623203 8 -rw-r--r--  1 rmartinez  staff   86 Apr  8 13:48 yarn.lock
```

**Comment by byCedric** [comment]
Hi @mtzfactory! Thanks for the repro, this isn't an issue with the CLI but more how Metro resolves packages. As the error pointed out, it can't find **packages/@cool-package/index.js**. That's because:

- The **packages/@cool-package/package.json** `main` entry, points towards `index.js` ([here](https://github.com/mtzfactory/expo-sdk-50-with-router-monorepo/blob/ecd6fbb8428e0406d4dababc19a39ebe13baf651/packages/cool-package/package.json#L4))
- But only **packages/@cool-package/index.ts** (with `.ts`) exists.

You can either update the **package.json** `main` to point to `index.ts`, or rename the `index.ts -> index.js`.

Hope this helps!

**Comment by mtzfactory** [comment]
@byCedric thank you very much for your quick response!
But that solved o nly the iOS problem, the web problem remains... with the very same error:

```
"targetModuleName": "./node_modules/expo-router/entry",
  "message": "Unable to resolve module ./node_modules/expo-router/entry from /Users/rmartinez/development/personal/temp/react-native/expo-monorepo/apps/expo/.: \n\nNone of these files exist:\n  * node_modules/expo-router/entry(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)\n  * node_modules/expo-router/entry/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)",
```

As I said "_I faced a problem **upgrading an existing expo app from sdk 49 to sdk 50** in a monorepo setup, the reported error stated it wasn't able to import the modules declared in the yarn workspaces..._"

**Comment by mtzfactory** [comment]
Just to add some more info, I started the metro server cleaning the cache with `yarn workspace @monorepo/app start -c`

**Comment by stewartiee** [comment]
I see the same error when taking a new Expo project, and then trying to apply the Expo Router install instructions whilst using a monorepo with Bun.

**Comment by mtzfactory** [comment]
@stewartiee thanks! That solved the problem in the demo repo I shared... I'll try it now in the real project!
