### ISSUE TITLE
Cannot build when including react-native-skia with SDK 51 beta

### ISSUE THREAD

**Issue by contactsimonwilson** [expo/expo#28494]
### Minimal reproducible example

https://github.com/contactsimonwilson/expo-51-beta-prebuild

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Local builds fail when including react-native-skia on sdk51. It seems to be an issue with more than just skia in one of my projects; the provided example reproduces the issue in a minimal way.

I confirmed that downgrading to SDK 50 (and installing the recommended dependency versions) does not have the same issue.

```
> Task :shopify_react-native-skia:generateCodegenSchemaFromJavaScript FAILED
C:\Repos\my-app\node_modules\@react-native\codegen\lib\cli\combine\combine-js-to-schema-cli.js:62
  .parseSync();
   ^

TypeError: yargs.option(...).option(...).parseSync is not a function
    at Object.<anonymous> (C:\Repos\my-app\node_modules\@react-native\codegen\lib\cli\combine\combine-js-to-schema-cli.js:62:4)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.9.0

FAILURE: Build failed with an exception.
```

To reproduce with linked repo:
`npm i`
`npx expo rebuild --clean`
`npm run android`

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD

### Expo Doctor Diagnostics

C:\Repos\my-app [master +0 ~3 -0 | +0 ~1 -0 !]> npx expo-doctor@latest
Need to install the following packages:
expo-doctor@1.5.2
Ok to proceed? (y) y
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
C:\Repos\my-app [master +0 ~3 -0 | +0 ~1 -0 !]>

**Comment by gorbypark** [comment]
Is this possibly dev env setup (or Windows) related?
SDK 51.0.0-preview.7 blank project
```bash
npx expo install @shopify/react-native-skia
npx expo prebuild --clean
yarn ios
yarn android
```
both android and ios build for me using the above steps.  On macOS/Xcode 15.3 and openjdk 17.0.10

**Comment by contactsimonwilson** [comment]
I get the same error with EAS build on the project I initially ran into this error with

**Comment by contactsimonwilson** [comment]
@gorbypark can confirm the build passes that step on mac but not on Windows or within the EAS build service

```
Running 'gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-8.6-all.zip
10%
20%
30%.
40%.
50%.
60%.
70%.
80%
90%
100%
Welcome to Gradle 8.6!
Here are the highlights of this release:
 - Configurable encryption key for configuration cache
 - Build init improvements
 - Build authoring improvements
For more details see https://docs.gradle.org/8.6/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.6/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Task :gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Configure project :app
Warning: Errors during XML parse:
Warning: Additionally, the fallback loader failed to parse the XML.
Checking the license for package NDK (Side by side) 26.1.10909125 in /home/expo/Android/Sdk/licenses
License for package NDK (Side by side) 26.1.10909125 accepted.
Preparing "Install NDK (Side by side) 26.1.10909125 v.26.1.10909125".
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" ready.
Installing NDK (Side by side) 26.1.10909125 in /home/expo/Android/Sdk/ndk/26.1.10909125
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" complete.
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" finished.
> Configure project :expo
Using expo modules
  - [32mexpo-asset[0m (10.0.3)
  - [32mexpo-constants[0m (16.0.1)
  - [32mexpo-file-system[0m (17.0.1)
  - [32mexpo-font[0m (12.0.4)
  - [32mexpo-image[0m (1.12.4)
  - [32mexpo-keep-awake[0m (13.0.1)
  - [32mexpo-linear-gradient[0m (13.0.1)
- [32mexpo-modules-core[0m (1.12.3)
  - [32mexpo-splash-screen[0m (0.27.2)
> Configure project :shopify_react-native-skia
react-native-skia: node_modules/ found at: /home/expo/workingdir/build/node_modules
react-native-skia: RN Version: 74 / 0.74.0
react-native-skia: isSourceBuild: false
react-native-skia: PrebuiltDir: /home/expo/workingdir/build/node_modules/@shopify/react-native-skia/android/build/react-native-0*/jni
react-native-skia: buildType: release
react-native-skia: buildDir: /home/expo/workingdir/build/node_modules/@shopify/react-native-skia/android/build
react-native-skia: node_modules: /home/expo/workingdir/build/node_modules
react-native-skia: Enable Prefab: true
react-native-skia: aar state post 70, do nothing
Checking the license for package Android SDK Build-Tools 34 in /home/expo/Android/Sdk/licenses
License for package Android SDK Build-Tools 34 accepted.
Preparing "Install Android SDK Build-Tools 34 v.34.0.0".
"Install Android SDK Build-Tools 34 v.34.0.0" ready.
Installing Android SDK Build-Tools 34 in /home/expo/Android/Sdk/build-tools/34.0.0
"Install Android SDK Build-Tools 34 v.34.0.0" complete.
"Install Android SDK Build-Tools 34 v.34.0.0" finished.
Checking the license for package Android SDK Platform 34 in /home/expo/Android/Sdk/licenses
License for package Android SDK Platform 34 accepted.
Preparing "Install Android SDK Platform 34 (revision 3)".
"Install Android SDK Platform 34 (revision 3)" ready.
Installing Android SDK Platform 34 in /home/expo/Android/Sdk/platforms/android-34
"Install Android SDK Platform 34 (revision 3)" complete.
"Install Android SDK Platform 34 (revision 3)" finished.
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Task :expo-asset:preBuild
UP-TO-DATE
> Task :expo-asset:preReleaseBuild UP-TO-DATE
> Task :expo-asset:generateReleaseResValues
> Task :expo-asset:generateReleaseResources
> Task :expo-asset:packageReleaseResources
> Task :expo-file-system:preBuild UP-TO-DATE
> Task :expo-file-system:preReleaseBuild UP-TO-DATE
> Task :expo-file-system:generateReleaseResValues
> Task :expo-file-system:generateReleaseResources
> Task :expo-constants:createExpoConfig
> Task :expo-constants:preBuild
> Task :expo-constants:preReleaseBuild
> Task :expo-constants:generateReleaseResValues
> Task :expo-constants:generateReleaseResources
> Task :expo-constants:packageReleaseResources
> Task :expo-font:preBuild UP-TO-DATE
> Task :expo-font:preReleaseBuild UP-TO-DATE
> Task :expo-font:generateReleaseResValues
> Task :expo-font:generateReleaseResources
> Task :expo-file-system:packageReleaseResources
> Task :expo-image:preBuild UP-TO-DATE
> Task :expo-image:preReleaseBuild UP-TO-DATE
> Task :expo-font:packageReleaseResources
> Task :expo-keep-awake:preBuild UP-TO-DATE
> Task :expo-keep-awake:preReleaseBuild UP-TO-DATE
> Task :expo-image:generateReleaseResValues
> Task :expo-image:generateReleaseResources
> Task :expo-keep-awake:generateReleaseResValues
> Task :expo-keep-awake:generateReleaseResources
> Task :expo-image:packageReleaseResources
> Task :expo-linear-gradient:preBuild UP-TO-DATE
> Task :expo-linear-gradient:preReleaseBuild UP-TO-DATE
> Task :expo-keep-awake:packageReleaseResources
> Task :expo-modules-core:preBuild UP-TO-DATE
> Task :expo-modules-core:preReleaseBuild UP-TO-DATE
> Task :expo-linear-gradient:generateReleaseResValues
> Task :expo-linear-gradient:generateReleaseResources
> Task :expo-modules-core:generateReleaseResValues
> Task :expo-modules-core:generateReleaseResources
> Task :expo-linear-gradient:packageReleaseResources
> Task :expo-splash-screen:preBuild UP-TO-DATE
> Task :expo-modules-core:packageReleaseResources
> Task :expo-splash-screen:preReleaseBuild UP-TO-DATE
> Task :expo-splash-screen:generateReleaseResValues
> Task :expo-splash-screen:generateReleaseResources
> Task :expo-splash-screen:packageReleaseResources
> Task :expo:generateExpoModulesPackageListTask
> Task :expo:preBuild
> Task :expo:preReleaseBuild
> Task :expo:generateReleaseResValues
> Task :expo:generateReleaseResources
> Task :expo-asset:extractDeepLinksRelease
> Task :expo:packageReleaseResources
> Task :expo:extractDeepLinksRelease
> Task :shopify_react-native-skia:generateCodegenSchemaFromJavaScript FAILED
/home/expo/workingdir/build/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:62
  .parseSync();
   ^
TypeError: yargs.option(...).option(...).parseSync is not a function
    at Object.<anonymous> (/home/expo/workingdir/build/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:62:4)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47
Node.js v18.18.0
> Task :expo:processReleaseManifest
> Task :expo-asset:processReleaseManifest
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':shopify_react-native-skia:generateCodegenSchemaFromJavaScript'.
> Process 'command 'node'' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 3m 2s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
32 actionable tasks: 32 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

**Comment by johnf** [comment]
This is being caused by multikple versions of `yargs`

I fixed with yarn bu adding the following to package.json:
```
  "resolutions": {
    "yargs": "^17"
  },
```
