### ISSUE TITLE
Android Build Error related to expo-dev-launcher@4.0.13

### ISSUE THREAD

**Issue by kziemski** [expo/expo#28726]
### Summary

> Task :expo-dev-launcher:compileDebugKotlin FAILED
e: file:///home/ubuntu/repos/.../node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/loaders/DevLauncherAppLoaderFactory.kt:44:29 Unresolved reference: isValidUpdatesConfiguration

this is on expo-dev-launcher@4.0.13 
downgrade to: 
npx expo install expo-dev-launcher@4.0.12 
works temporairily but your not meant to install expo-dev-launcher driectly 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

Using expo modules
  - expo-application (5.9.1)
  - expo-asset (10.0.6)
  - expo-av (14.0.3)
  - expo-blur (13.0.2)
  - expo-constants (16.0.1)
  - expo-dev-client (4.0.12)
  - expo-dev-launcher (4.0.13)
  - expo-dev-menu (5.0.13)
  - expo-device (6.0.2)
  - expo-file-system (17.0.1)
  - expo-font (12.0.4)
  - expo-haptics (13.0.1)
  - expo-image-loader (4.7.0)
  - expo-image-picker (15.0.4)
  - expo-json-utils (0.13.1)
  - expo-keep-awake (13.0.1)
  - expo-linear-gradient (13.0.2)
  - expo-local-authentication (14.0.1)
  - expo-manifests (0.14.1)
  - expo-modules-core (1.12.10)
  - expo-notifications (0.28.1)
  - expo-screen-orientation (7.0.4)
  - expo-secure-store (13.0.1)
  - expo-splash-screen (0.27.4)
  - expo-system-ui (3.0.4)
  - expo-task-manager (11.8.1)
  - expo-web-browser (13.0.3)
  - unimodules-app-loader (4.6.0)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 4.1.1 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: bare

### Reproducible demo

don't have the time to produce something in the middle will fix this after hours.

### Stacktrace (if a crash is involved)

npx expo run:android 
....

Error: /home/ubuntu/repos/CLIENTS/FIDES/cmat/cmat-cmon-app/packages/site/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a exited with non-zero code: 1
Error: /home/ubuntu/repos/CLIENTS/FIDES/cmat/cmat-cmon-app/packages/site/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a exited with non-zero code: 1
    at ChildProcess.completionListener (/home/ubuntu/repos/CLIENTS/FIDES/cmat/cmat-cmon-app/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/home/ubuntu/repos/CLIENTS/FIDES/cmat/cmat-cmon-app/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/home/ubuntu/repos/CLIENTS/FIDES/cmat/cmat-cmon-app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/home/ubuntu/repos/CLIENTS/FIDES/cmat/cmat-cmon-app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/home/ubuntu/repos/CLIENTS/FIDES/cmat/cmat-cmon-app/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)

**Comment by kziemski** [comment]
Resolved by updating to expo-dev-client@4.0.13 which resolves expo-dev-launcher to v4.0.14 
 expo-dev-client@npm:4.0.13
│  └─ expo-dev-launcher@npm:4.0.14 (via npm:4.0.14)
