### ISSUE TITLE
[SDK 51][expo-web] @apollo-client fails during expo export with metro for web

### ISSUE THREAD

**Issue by marklawlor** [expo/expo#28785]
Regression in SDK51 where expo-web is unable to export projects that include dependencies that export `__DEV__` inside a module. 

@marklawlor @wollerman this happens with expo51, which didn't with expo50.
see the reproduction here: https://github.com/younes0/apollo-sdk51-bug-repro

running `npx expo export --clear --platform web` results in:
```
Web Bundling failed 11730ms node_modules/expo-router/entry.js (1197 modules)
error: node_modules/@apollo/client/utilities/globals/index.js: /projects/apollo-sdk51-bug-repro/node_modules/@apollo/client/utilities/globals/index.js: Property exported of ExportSpecifier expected node to be of a type ["Identifier","StringLiteral"] but instead got "BooleanLiteral"
λ Bundled 11807ms node_modules/expo-router/node/render.js (1093 modules)
Error: node_modules/@apollo/client/utilities/globals/index.js: /projects/apollo-sdk51-bug-repro/node_modules/@apollo/client/utilities/globals/index.js: Property exported of ExportSpecifier expected node to be of a type ["Identifier","StringLiteral"] but instead got "BooleanLiteral"
Error: node_modules/@apollo/client/utilities/globals/index.js: /projects/apollo-sdk51-bug-repro/node_modules/@apollo/client/utilities/globals/index.js: Property exported of ExportSpecifier expected node to be of a type ["Identifier","StringLiteral"] but instead got "BooleanLiteral"
    at MetroBundlerDevServer.getStaticResourcesAsync (/projects/apollo-sdk51-bug-repro/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:325:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at exportFromServerAsync (/projects/apollo-sdk51-bug-repro/node_modules/@expo/cli/src/export/exportStaticAsync.ts:196:66)
    at unstable_exportStaticAsync (/projects/apollo-sdk51-bug-repro/node_modules/@expo/cli/src/export/exportStaticAsync.ts:94:12)
    at exportAppAsync (/projects/apollo-sdk51-bug-repro/node_modules/@expo/cli/src/export/exportApp.ts:169:7)
    at exportAsync (/projects/apollo-sdk51-bug-repro/node_modules/@expo/cli/src/export/exportAsync.ts:18:3)
```

_Originally posted by @younes0 in https://github.com/expo/expo/issues/25965#issuecomment-2105505368_

**Comment by ericlyoung** [comment]
having to roll back to 50 because of this bug
