### ISSUE TITLE
npx expo lint gives a maximum call stack size exceeded

### ISSUE THREAD

**Issue by oamr-abdelaziz** [expo/expo#28799]
### Summary

I created a new expo project, and I'm trying to setup eslint as in documentation by trying
 npx expo lint
 but I receive RangeError: Maximum call stack size exceeded
 RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:54:5)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)
    at findFileInParents (D:\Multimedia\GenerateAIImage\node_modules\@expo\cli\build\src\utils\findUp.js:60:12)

### SDK Version

51.0.2

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.0.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-233.14808.21.2331.11709847
    npmPackages:
      expo: ~51.0.2 => 51.0.2
      expo-router: ~3.5.11 => 3.5.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/oamr-abdelaziz/Generate-AI-Image

type in terminal, npx expo lint

**Comment by oamr-abdelaziz** [comment]
I updated my expo to the latest now but the issue is still the same,
Is there something else I should do?
