### ISSUE TITLE
[SDK 51][expo-router] expo-router's Head element is not working anymore

### ISSUE THREAD

**Issue by sem4phor** [expo/expo#28949]
### Minimal reproducible example

-

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

Theres a regression which crashes the app when using the Head element from expo router on some route within an expo router application. We are using an nx monorepo but shouldn't matter.

Error msg:
```
index.esm.js:642 Uncaught TypeError: Cannot read properties of undefined (reading 'add')
    at HelmetDispatcher.init (index.esm.js:642:3)
    at HelmetDispatcher.render (index.esm.js:646:3)
    at finishClassComponent (react-dom.development.js:19755:9)
    at updateClassComponent (react-dom.development.js:19701:16)
    at beginWork (react-dom.development.js:21614:10)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4166:9)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4216:16)
    at invokeGuardedCallback (react-dom.development.js:4279:1)
    at beginWork$1 (react-dom.development.js:27453:29)
    at performUnitOfWork (react-dom.development.js:26559:10)
```

### Environment

```
System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/valentinrapp/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.1 => 0.18.4 
      babel-preset-expo: ~11.0.0 => 11.0.6 
      expo: ~51.0.8 => 51.0.8 
      expo-router: ~3.5.14 => 3.5.14 
      metro: ^0.80.9 => 0.80.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: 0.19.11 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 9.0.6
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.8.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~7.0.0
Found invalid:
  @expo/prebuild-config@6.7.3
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

**Comment by ps-artem** [comment]
@sem4phor Just add this to your top `_layout` file

```
import Head from 'expo-router/head'
import { Slot } from 'expo-router'
export default () => (
    <Head.Provider>
      <Slot />
    </Head.Provider>
)
```
