### ISSUE TITLE
@expo/fingerprint  return error - Cannot get Expo config from an Expo project

### ISSUE THREAD

**Issue by eladgoeuro** [expo/expo#29089]
### Summary

Hi, 

Am getting the folloiwng error when I a trying to compare the finger prints:

`npx @expo/fingerprint@latest ./fingerprint.json
`

```
Cannot get Expo config from an Expo project - node /Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/fingerprint/build/sourcer/ExpoConfigLoader.js /Users/elad/blindchat/blind-chat-app/fingerprint.json /var/folders/z_/zjwpt3811zj2bdqnw34jcfl00000gn/T/.fingerprintignore exited with non-zero code: 1:  Error: node /Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/fingerprint/build/sourcer/ExpoConfigLoader.js /Users/elad/blindchat/blind-chat-app/fingerprint.json /var/folders/z_/zjwpt3811zj2bdqnw34jcfl00000gn/T/.fingerprintignore exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
    ...
    at spawnAsync (/Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at getExpoConfigSourcesAsync (/Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/fingerprint/build/sourcer/Expo.js:26:60)
    at async Promise.all (index 2)
    at async getHashSourcesAsync (/Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/fingerprint/build/sourcer/Sourcer.js:15:21)
    at async Object.createFingerprintAsync (/Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/fingerprint/build/Fingerprint.js:14:21)
    at async /Users/elad/.npm/_npx/6e6f49cf5232e11b/node_modules/@expo/fingerprint/bin/cli.js:44:27
```

I am using app.js and app.config.js

export default ({ config: _config }) => {
 ...
}

### SDK Version

50

### Environment

xpo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.07.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^10.0.0 => 10.0.2
      expo: ^50.0.0 => 50.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

### Minimal reproducible example

1. npx @expo/fingerprint@latest . > /fingerprint.json
2. npx @expo/fingerprint@latest  ./fingerprint.json

**Comment by Charles-Johnson** [comment]
@eladgoeuro, have you tried running `npx @expo/fingerprint@latest . ./fingerprint.json`?

**Comment by GollyJer** [comment]
Did anyone figure this out? Having the same issue.
`Failed to read the app config from the project using "npx expo config" command: npx expo config --json --type introspect exited with non-zero code: 1.`

**Comment by elyobo** [comment]
Also seeing it, using `app.config.ts`.

`bunx @expo/fingerprint fingerprint:generate` works without errors while calling `createFingerprintAsync` outputs an error; both do give the same hash and looking into how the CLI works it's actually generating the error as well, it's just suppressing it via the `withConsoleDisabledAsync` utility function it calls.

Unsure whether I can trust the hash or not, given that it seems to be failing to read the config file for some reason.

**Edit:**

Looking further and invoking the command that it's trying to do, which is output in the error message - `node /Users/me/src/app/node_modules/@expo/fingerprint/build/ExpoConfigLoader.js /Users/me/src/app` in my case - I can see the problem, my `react-native-maps` dependency has JSX inside a `.js` file which cannot be parsed; it's not a problem with `@expo/fingerprint`

```
node /Users/me/src/app/node_modules/@expo/fingerprint/build/ExpoConfigLoader.js /Users/me/src/app
The NODE_ENV environment variable is required but was not specified. Ensure the project is bundled with Expo CLI or NODE_ENV is set. Using only .env.local and .env
Uncaught Error /Users/me/src/app/node_modules/react-native-maps/lib/MapView.js:347
        return (<decorateMapComponent_1.ProviderContext.Provider value={this.props.provider}>
                ^

SyntaxError: Unexpected token '<'
    at wrapSafe (node:internal/modules/cjs/loader:1692:18)
    at Module._compile (node:internal/modules/cjs/loader:1735:20)
    at Object..js (node:internal/modules/cjs/loader:1893:10)
    at Module.load (node:internal/modules/cjs/loader:1481:32)
    at Module._load (node:internal/modules/cjs/loader:1300:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.require (node:internal/modules/cjs/loader:1504:12)
    at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (/Users/me/src/app/node_modules/react-native-maps/lib/index.js:33:32) {
  name: 'PluginError',
  isPluginError: true,
  code: 'INVALID_PLUGIN_IMPORT',
  cause: undefined
}
```

**Edit #2:**

And in this case that was fixable by upgrading to a more recent `react-native-maps` version.
