### ISSUE TITLE
[Task-manager][BackgroundFetch]PluginError: Plugin is an unexpected type: object

### ISSUE THREAD

**Issue by aymanMFD** [expo/expo#29086]
### Minimal reproducible example

https://github.com/aymanMFD/Monitoring-System.git

### Did you reproduce this issue in a development build?

Yes

### Summary

When trying task-manager and backgroundFetch, the console gives  me this error `PluginError: Plugin is an unexpected type: object`.

Outside of react component
```js
TaskManager.defineTask(BACKGROUND_FETCH_TASK, async () => {
  const now = Date.now();
  sendNotif("Background?");
  console.log(`Got background fetch call at date: ${new Date(now).toISOString()}`);

  // Be sure to return the successful result type!
  return BackgroundFetch.BackgroundFetchResult.NewData;
});

async function registerBackgroundFetchAsync() {
    return BackgroundFetch.registerTaskAsync(BACKGROUND_FETCH_TASK, {
      minimumInterval: 60 * 1, // 15 minutes
      stopOnTerminate: false, // android only,
      startOnBoot: true, // android only
    });
  }
```
In my react component
```js
    useEffect(() => {
        registerBackgroundFetchAsync();
        TaskManager.isTaskRegisteredAsync().then(res => {console.log(`Task registered: ${res}`)});
    }, [])
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

### Expo Doctor Diagnostics

There was a lot to text but couldn't paste it due to work limit                                                                                                                         

PluginError: Plugin is an unexpected type: object
    at withStaticPlugin (C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:53:425334)
    at C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:53:422676
    at Array.reduce (<anonymous>)
    at withPlugins (C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:53:422621)
    at withConfigPlugins (C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:53:481353)
    at fillAndReturnConfig (C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:53:465809)
    at getConfig (C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:53:466626)
    at actionAsync (C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:100143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (C:\Users\mumfdu358\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:101815) {
  isPluginError: true,
  code: 'INVALID_PLUGIN_TYPE',
  cause: undefined
}

Node.js v20.11.1

**Comment by aymanMFD** [comment]
Nvm it was a mistake I did in app.json file
