### ISSUE TITLE
Expo Router is not compatible with ESLint + Bun (`Error: Cannot find module 'ajv/dist/compile/codegen'`)

### ISSUE THREAD

**Issue by amanape** [expo/expo#29150]
### Minimal reproducible example

https://github.com/amanape/expo-router-eslint-bun-bug

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Given this combination of packages:
1. Installing ESLint with `bunx/npx expo lint`
2. Installing Expo Router by following [the official reference](https://docs.expo.dev/router/installation/)

And attempting to start the development environment **with Bun** (`bun start`), the error is thrown in the console. Here is the full error:
```sh
> bun start
$ expo start
Starting project at /Users/.../error
Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /Users/.../error/node_modules/ajv-keywords/dist/definitions/typeof.js
- /Users/.../error/node_modules/ajv-keywords/dist/keywords/typeof.js
- /Users/.../error/node_modules/ajv-keywords/dist/keywords/index.js
- /Users/.../error/node_modules/ajv-keywords/dist/index.js
- /Users/.../error/node_modules/schema-utils/dist/validate.js
- /Users/.../error/node_modules/schema-utils/dist/index.js
- /Users/.../error/node_modules/expo-router/plugin/build/index.js
- /Users/.../error/node_modules/expo-router/app.plugin.js
- /Users/.../error/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /Users/.../error/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /Users/.../error/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /Users/.../error/node_modules/@expo/config-plugins/build/index.js
- /Users/.../error/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /Users/.../error/node_modules/@expo/config/build/Config.js
- /Users/.../error/node_modules/@expo/config/build/index.js
- /Users/.../error/node_modules/@expo/cli/build/src/utils/analytics/getDevClientProperties.js
- /Users/.../error/node_modules/@expo/cli/build/src/start/resolveOptions.js
- /Users/.../error/node_modules/@expo/cli/build/src/start/index.js
- /Users/.../error/node_modules/@expo/cli/build/bin/cli
- /Users/.../error/node_modules/expo/bin/cli
Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /Users/.../error/node_modules/ajv-keywords/dist/definitions/typeof.js
- /Users/.../error/node_modules/ajv-keywords/dist/keywords/typeof.js
- /Users/.../error/node_modules/ajv-keywords/dist/keywords/index.js
- /Users/.../error/node_modules/ajv-keywords/dist/index.js
- /Users/.../error/node_modules/schema-utils/dist/validate.js
- /Users/.../error/node_modules/schema-utils/dist/index.js
- /Users/.../error/node_modules/expo-router/plugin/build/index.js
- /Users/.../error/node_modules/expo-router/app.plugin.js
- /Users/.../error/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /Users/.../error/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /Users/.../error/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /Users/.../error/node_modules/@expo/config-plugins/build/index.js
- /Users/.../error/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /Users/.../error/node_modules/@expo/config/build/Config.js
- /Users/.../error/node_modules/@expo/config/build/index.js
- /Users/.../error/node_modules/@expo/cli/build/src/utils/analytics/getDevClientProperties.js
- /Users/.../error/node_modules/@expo/cli/build/src/start/resolveOptions.js
- /Users/.../error/node_modules/@expo/cli/build/src/start/index.js
- /Users/.../error/node_modules/@expo/cli/build/bin/cli
- /Users/.../error/node_modules/expo/bin/cli
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/.../error/node_modules/ajv-keywords/dist/definitions/typeof.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
error: script "start" exited with code 1
```

Interestingly, attempting to run `npx/bunx expo-doctor` throws the same error:
```sh
> bunx expo-doctor
node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /Users/.../error/node_modules/ajv-keywords/dist/definitions/typeof.js
- /Users/.../error/node_modules/ajv-keywords/dist/keywords/typeof.js
- /Users/.../error/node_modules/ajv-keywords/dist/keywords/index.js
- /Users/.../error/node_modules/ajv-keywords/dist/index.js
- /Users/.../error/node_modules/schema-utils/dist/validate.js
- /Users/.../error/node_modules/schema-utils/dist/index.js
- /Users/.../error/node_modules/expo-router/plugin/build/index.js
- /Users/.../error/node_modules/expo-router/app.plugin.js
- /private/tmp/bunx-501-expo-doctor@latest/node_modules/expo-doctor/build/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/.../error/node_modules/ajv-keywords/dist/definitions/typeof.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/.../error/node_modules/ajv-keywords/dist/definitions/typeof.js',
    '/Users/.../error/node_modules/ajv-keywords/dist/keywords/typeof.js',
    '/Users/.../error/node_modules/ajv-keywords/dist/keywords/index.js',
    '/Users/.../error/node_modules/ajv-keywords/dist/index.js',
    '/Users/.../error/node_modules/schema-utils/dist/validate.js',
    '/Users/.../error/node_modules/schema-utils/dist/index.js',
    '/Users/.../error/node_modules/expo-router/plugin/build/index.js',
    '/Users/.../error/node_modules/expo-router/app.plugin.js',
    '/private/tmp/bunx-501-expo-doctor@latest/node_modules/expo-doctor/build/index.js'
  ]
}

Node.js v20.11.0
```

Abandoning Bun and reinstalling dependencies with `npm` works fine.

### Environment

```sh
expo-env-info 1.2.0 environment info:
System:
  OS: macOS 14.5
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.11.0 - /usr/local/bin/node
  Yarn: 1.22.17 - /opt/homebrew/bin/yarn
  npm: 10.3.0 - /opt/homebrew/bin/npm
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode: 15.4/15F31d - /usr/bin/xcodebuild
npmPackages:
  expo: ~51.0.8 => 51.0.8 
  expo-router: ~3.5.14 => 3.5.14 
  react: 18.2.0 => 18.2.0 
  react-native: 0.74.1 => 0.74.1 
npmGlobalPackages:
  eas-cli: 9.0.8
  expo-cli: 6.3.10
Expo Workflow: managed
```

**Comment by marklawlor** [comment]
This is not a bug with Expo, but rather with how `bun` handles `peerDependancies`. In your repo there is a version clash, and the undesired version is being hoisted. 

The root cause of your problem is that `eslint-config-expo`->`@typescript-eslint/eslint-plugin` does not support `eslint@9`  (its still in beta) https://github.com/typescript-eslint/typescript-eslint/issues/8211

You can resolve your issue by downgrading your eslint or setting an explicit version on the top level `bun install ajv`

**Comment by amanape** [comment]
@marklawlor The reproducible repository I have shared only has an `eslint` version of `^8.57.0` and an `eslint-config-expo` of `^7.0.0`. Moreover, removing either Expo Router or ESLint results in the project working fine, but the two together prevent the project from working.

I have done nothing more but follow the official Expo documentation on setting up ESLint. Why does Expo use the beta version if it contains clashing versions of `eslint-config-expo` and `eslint`?

**Comment by marklawlor** [comment]
I understand your frustration, but unfortunately this is an issue with `bun` and not with Expo. 

```
// your deps if installed with yarn

error@1.0.0 /Users/mark/Github/amanape/expo-router-eslint-bun-bug
├─┬ eslint@8.57.0
│ ├─┬ @eslint/eslintrc@2.1.4
│ │ └── ajv@6.12.6
│ └── ajv@6.12.6
└─┬ expo-router@3.5.14
  └─┬ schema-utils@4.2.0
    ├─┬ ajv-formats@2.1.1
    │ └── ajv@8.14.0 deduped
    ├─┬ ajv-keywords@5.1.0
    │ └── ajv@8.14.0 deduped
    └── ajv@8.14.0

// your deps if installed with bun
error@1.0.0 /Users/mark/Github/amanape/expo-router-eslint-bun-bug
├─┬ eslint@8.57.0
│ ├─┬ @eslint/eslintrc@2.1.4
│ │ └── ajv@6.12.6 deduped
│ └── ajv@6.12.6
└─┬ expo-router@3.5.14
  └─┬ schema-utils@4.2.0
    ├─┬ ajv-formats@2.1.1
    │ └── ajv@8.14.0
    ├─┬ ajv-keywords@5.1.0
    │ └── ajv@6.12.6 deduped invalid: "^8.8.2" from node_modules/ajv-keywords
    └── ajv@8.14.0
```

Expo has specified the correct dependencies, as shown by it work with `npm`/`yarn`, but `bun` follows a different peerDependency logic to these package managers. I do not know the details on why it operates differently. If you wish to use `bun`, then occasionally you need to pin the version of a peerDependency.

Expo has reported this to `bun` here https://github.com/oven-sh/bun/issues/8406

It looks like my previous comment about `eslint@9` was incorrect, i apologise for that.

**Comment by amanape** [comment]
It is much clearer now. It looks like they expect it to be resolved by next week. Thanks a lot!
