### ISSUE TITLE
npx expo run:android results in javax.net.ssl.SSLException: Tag mismatch

### ISSUE THREAD

**Issue by rpasechnikov** [expo/expo#29419]
### Summary

Hi all,

Just wondering if I'm missing something obvious. I followed the following two pages:
1. https://docs.expo.dev/get-started/create-a-project/
2. https://docs.expo.dev/get-started/set-up-your-environment/?platform=android&device=simulated&mode=development-build&buildEnv=local

And after a bit of trial and error, I got it almost running, however it seems to fail when running `npx expo run:android`, even though the Android emulator starts up fine.

Not sure if this is an environment issue or a case of [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK).

### What platform(s) does this occur on?

Android

### SDK Version

51.0.9

### Environment

System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10300.40.2321.11668458
    npmPackages:
      expo: ~51.0.9 => 51.0.9
      expo-router: ~3.5.14 => 3.5.15
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

### Minimal reproducible example

1. Create a new folder
2. Run `npx create-expo-app@latest`
3. Run `npx expo install expo-dev-client`
4. Run `npx expo run:android`

**Expected**: Android emulator starts fine and the sample/demo app is visible
**Actual**: 

```
$ npx expo run:android

📝  Android package Learn more: https://expo.fyi/android-package

√ What would you like your Android package name to be? ... com.anonymous.EventLog

✔ Created native directory
✔ Updated package.json
✔ Finished prebuild
› Opening emulator Pixel_5
› Building app...
Downloading https://services.gradle.org/distributions/gradle-8.6-all.zip
....................10%.....................20%.....................30%.....................40%.....................50%.....................60%.........
Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch!
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:123)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1513)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1484)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:141)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3698)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3691)
        at org.gradle.wrapper.Install.forceFetch(SourceFile:2)
        at org.gradle.wrapper.Install$1.call(SourceFile:8)
        at org.gradle.wrapper.GradleWrapperMain.main(SourceFile:67)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
        at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1493)
        at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:447)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2500)
        at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1933)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:264)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        ... 12 more
Error: C:\dev\Test-Expo-2\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86_64,arm64-v8a exited with non-zero code: 1
Error: C:\dev\Test-Expo-2\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86_64,arm64-v8a exited with non-zero code: 1
    at ChildProcess.completionListener (C:\dev\Test-Expo-2\node_modules\@expo\spawn-async\build\spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at cp.emit (C:\dev\Test-Expo-2\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (C:\dev\Test-Expo-2\node_modules\@expo\spawn-async\build\spawnAsync.js:7:23)
    at spawnGradleAsync (C:\dev\Test-Expo-2\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:96:48)
    at assembleAsync (C:\dev\Test-Expo-2\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:74:18)
    at runAndroidAsync (C:\dev\Test-Expo-2\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:45:37)

```

**Comment by SuhitAgarwal** [comment]
I have a feeling that this is the same issue that I faced yesterday, so after `expo prebuild`, if you navigate to `android/gradle/wrapper/gradle-wrapper.properties`, you'll see the `distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip` remove the extra `\` from the link right after `https`.

Once you fix this, and execute `npx expo run:android` again, it should start working

**Comment by rpasechnikov** [comment]
That was it! Thank you! 

Do we know what results in to be there in the first place?

**Comment by SuhitAgarwal** [comment]
unsure although a quick search shows it here:
https://github.com/expo/expo/blob/ee1117786d78501442881f6241944ee15958e14e/apps/expo-go/android/gradle/wrapper/gradle-wrapper.properties#L3
