### ISSUE TITLE
Expo 31 new install - Jest encountered an unexpected token

### ISSUE THREAD

**Issue by ericjames** [expo/expo#2950]
### Environment

  Expo CLI 2.6.9 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.6.9

### Steps to Reproduce

Upgrading to 31 and running my unit tests, Jest complains about the Babel preset with `Requires Babel "^7.0.0-0", but was loaded with "6.26.3".` (https://forums.expo.io/t/upgrade-to-sdk-31-jest-test-fails-with-requires-babel-7-0-0-0-but-was-loaded-with-6-26-3/16909).

So I did a fresh install and noticed it was also broken, so let's start here and it will probably resolve whatever is affecting mine. 

`expo init`
`npm run test`

```
> node ./node_modules/jest/bin/jest.js --watchAll

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/Users/Eric/Github/expo/TestApp/node_modules/jest/bin/jest.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `node ./node_modules/jest/bin/jest.js --watchAll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Eric/.npm/_logs/2018-12-10T16_14_50_319Z-debug.log
```

Okay go into package.json and change scripts to `"test": "jest"`

`npm run test`

```
 FAIL  components/__tests__/StyledText-test.js
  ● Test suite failed to run

    /Users/Eric/Github/expo/TestApp/node_modules/react-native/jest/mockComponent.js: Unexpected token (20:23)

      Jest encountered an unexpected token
      This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
      By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
      Here's what you can do:
       • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
       • If you need a custom transformation specify a "transform" option in your config.
       • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
      You'll find more details and examples of these config options in the docs:
      https://jestjs.io/docs/en/configuration.html
      Details:
        18 | 
        19 |   const Component = class extends SuperClass {
      > 20 |     static displayName = 'Component';
           |                        ^
        21 | 
        22 |     render() {
        23 |       const name =

 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    /Users/Eric/Github/expo/TestApp/node_modules/react-native/jest/mockComponent.js: Unexpected token (20:23)

      Jest encountered an unexpected token
      This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
      By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
      Here's what you can do:
       • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
       • If you need a custom transformation specify a "transform" option in your config.
       • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
      You'll find more details and examples of these config options in the docs:
      https://jestjs.io/docs/en/configuration.html
      Details:
        18 | 
        19 |   const Component = class extends SuperClass {
      > 20 |     static displayName = 'Component';
           |                        ^
        21 | 
        22 |     render() {
        23 |       const name =

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.767s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Eric/.npm/_logs/2018-12-10T16_15_08_458Z-debug.log
ejprime-2:TestApp Eric$ 
```

**Comment by brentvatne** [comment]
I just ran `expo init`, chose the `tabs` project, installed the dependencies, `cd`'d into the directory and ran `yarn test` and it worked. I wonder if there might be a bug with your version of npm? You could try installing yarn and initializing a new project to see if that helps

**Comment by ericjames** [comment]
Hmmm 
```
npm ls babel-core
.../expo/TestApp
├─┬ jest-expo@31.0.0
│ ├── babel-core@7.0.0-bridge.0 
│ └─┬ jest@23.6.0
│   └─┬ jest-cli@23.6.0
│     ├─┬ jest-config@23.6.0
│     │ └── babel-core@6.26.3  deduped
│     └─┬ jest-runtime@23.6.0
│       └── babel-core@6.26.3  deduped
└─┬ react-native@0.57.1
  └─┬ fbjs-scripts@0.8.3
    └─┬ babel-core@6.26.3 
      └─┬ babel-register@6.26.0
        └── babel-core@6.26.3  deduped
```

**Comment by ericjames** [comment]
Oh this is a dupe of https://github.com/expo/expo/issues/2595
