### ISSUE TITLE
[expo-video] [Android] Video player causes the app to crash.

### ISSUE THREAD

**Issue by PrinceD96** [expo/expo#29739]
### Minimal reproducible example

https://github.com/PrinceD96/expo-video-repro

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I created a brand new expo-bare project and installed the expo-video package. I then copied and pasted the example from the expo-video docs and the app kept crashing for Android. It seems related to Picture In Picture (PIP)

```
Exception in native call
java.lang.IllegalStateException: setPictureInPictureParams: Current activity does not support picture-in-picture.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3065)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityClientController$Stub$Proxy.setPictureInPictureParams(IActivityClientController.java:1966)
	at android.app.ActivityClient.setPictureInPictureParams(ActivityClient.java:363)
	at android.app.Activity.setPictureInPictureParams(Activity.java:3009)
	at expo.modules.video.VideoView.applyRectHint(VideoView.kt:255)
	at expo.modules.video.VideoView.onLayout(VideoView.kt:275)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:254)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:225)
	at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:135)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:910)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1023)
	at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches(Unknown Source:0)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$1.doFrame(ReactChoreographer.java:89)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:878)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityClientController.ensureValidPictureInPictureActivityParams(ActivityClientController.java:957)
	at com.android.server.wm.ActivityClientController.setPictureInPictureParams(ActivityClientController.java:887)
	at android.app.IActivityClientController$Stub.onTransact(IActivityClientController.java:1000)
	at com.android.server.wm.ActivityClientController.onTransact(ActivityClientController.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1339)

D  Shutting down VM
E  FATAL EXCEPTION: main
Process: com.expobarelatest, PID: 23521
java.lang.IllegalStateException: setPictureInPictureParams: Current activity does not support picture-in-picture.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3065)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityClientController$Stub$Proxy.setPictureInPictureParams(IActivityClientController.java:1966)
	at android.app.ActivityClient.setPictureInPictureParams(ActivityClient.java:363)
	at android.app.Activity.setPictureInPictureParams(Activity.java:3009)
	at expo.modules.video.VideoView.applyRectHint(VideoView.kt:255)
	at expo.modules.video.VideoView.onLayout(VideoView.kt:275)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at expo.modules.video.VideoView.mLayoutRunnable$lambda$3(VideoView.kt:125)
	at expo.modules.video.VideoView.$r8$lambda$oOlWV_EIAOBus6c_5bDslSW12u4(Unknown Source:0)
	at expo.modules.video.VideoView$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```

### Environment

```  
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 3.6.4 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.6.5 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/username/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
expo-bare-latest|main⚡ ⇒ npx expo-doctor@latest 
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check native tooling versions
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by behenate** [comment]
@PrinceD96 Hi! Did you install the package using `npx expo install expo-video` and re-ran the prebuild command?  The config plugin should be automatically added to the `plugins` section in your `app.json`, but you still have to prebuild to apply it.
If for some reason it's not there try to add "expo-video" to the plugins array and run `npx expo prebuild -p android`. If it's there just re-run the prebuild command and it should start working :)

**Comment by PrinceD96** [comment]
@behenate thank you, that fixed the issue!

Question: would this also be the solution for an RN CLI project as well?

**Comment by vonovak** [comment]
Hi!
[Expo modules](https://docs.expo.dev/modules/overview/) and [Config plugins](https://docs.expo.dev/config-plugins/introduction/) are expo-specific tools. Config plugins are applied when you run `npx expo prebuild` - there is no alternative to this in the RN CLI.
 
You can install expo-video as well as any other package into a bare React Native app, see https://docs.expo.dev/versions/latest/sdk/video/#installation

Hope this helps,
Thank you!
