### ISSUE TITLE
run turtle setup:android throw ERROR: Error: connect ETIMEDOUT 216.58.221.238:443

### ISSUE THREAD

**Issue by Pines-Cheng** [expo/expo#2978]
### Environment
    System:
      OS: macOS High Sierra 10.13.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.8.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.5.0

### Steps to Reproduce
I get some error after run `turtle setup:android`, but the network is well.

```
➜  taro-demo git:(master) ✗ turtle setup:android
Dec 13 21:28:45 turtle[40012] INFO:  Downloading Android SDK
  buildPhase: "setting up environment"
Dec 13 21:30:01 turtle[40012] ERROR: Failed to setup environment for android builds
Dec 13 21:30:01 turtle[40012] ERROR: Error: connect ETIMEDOUT 216.58.221.238:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

### Expected Behavior
output the correct result.

**Comment by dsokal** [comment]
Please rerun the command and let me know if it works now.

**Comment by Pines-Cheng** [comment]
Still not work , the same error.

**Comment by dsokal** [comment]
@Pines-Cheng `turtle-cli` downloads Android SDK from here - https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
If you're not able to open this URL in your browser then there is definitely something wrong with your network.

**Comment by Pines-Cheng** [comment]
the problem is , I can download the file .
So ,Do you have some manual resolution ?
