### ISSUE TITLE
Expo issues with npm workspaces / monorepos

### ISSUE THREAD

**Issue by necolas** [expo/expo#30143]
### Minimal reproducible example

https://github.com/facebook/react-strict-dom

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

We're experiencing issues with Expo not working correctly in npm workspaces. Some of these issues can be worked around, although they mean Expo doesn't work out-of-the-box. Others appear to be issues relating to Expo development with npm not being tested.

* The Expo template [doesn't work in npm workspaces](https://github.com/facebook/react-strict-dom/blob/71b4bcdcdb3f7f0d9b6f21cc17918a3eb74f0f92/apps/examples/src/index.js#L10-L12)

* The SKD v51 doesn't build in npm workspaces (we're stuck on v50). Errors about missing dependency declarations in various Expo `package.json` files. Expo is making a bad assumption - that other packages containing these dependencies will be installed, that all packages are hoisted to the top level (yarn behavior), and therefore that dependencies don't need to be accurately declared.

* Metro requires [esoteric configuration](https://github.com/facebook/react-strict-dom/blob/71b4bcdcdb3f7f0d9b6f21cc17918a3eb74f0f92/apps/examples/metro.config.js) to work with modern npm packages and npm workspaces.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2024-06-28T02:56:23Z - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✖ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following scripts in package.json conflict with the contents of node_modules/.bin: flow, jest.

One or more checks failed, indicating possible issues with the project.

**Comment by byCedric** [comment]
Hi @necolas! I'd love to dig into these issues. Will try to answer your points that you mentioned in this PR:

> Metro requires [esoteric configuration](https://github.com/facebook/react-strict-dom/blob/71b4bcdcdb3f7f0d9b6f21cc17918a3eb74f0f92/apps/examples/metro.config.js) to work with modern npm packages and npm workspaces.

We've updated [our monorepo guide](https://docs.expo.dev/guides/monorepos/#modify-the-metro-config) a couple of months ago and tried to communicate that this configuration isn't required anymore. It should work out of the box, as `@expo/metro-config` now detects monorepo config:

<img width="1101" alt="image" src="https://github.com/expo/expo/assets/1203991/f9979b8f-88eb-40c8-b553-dcfaf7ce5961">

Since the react-strict-dom monorepo uses npm, you can drop the **apps/examples/metro.config.js** file. I just tested this and both `npx expo export` (for android, ios, web) and `npx expo start` (for ios) seems to work fine.

Also, in the past, we recommended disabling the hierarchical lookup due to issues within the `react-native` package itself. These have since been resolved, it's likely doing more harm than good. I would highly discourage disabling this.

> The SKD v51 doesn't build in npm workspaces (we're stuck on v50). Errors about missing dependency declarations in various Expo package.json files. Expo is making a bad assumption - that other packages containing these dependencies will be installed, that all packages are hoisted to the top level (yarn behavior), and therefore that dependencies don't need to be accurately declared.

I'm not exactly sure which libraries you are referring to. React Native has historically been "not-great" with adhering to Node module resolution. We try to follow this resolution as a way for all (externally) imported modules. If that doesn't work, or if the import is not following this, it's a bug and I'd love to fix it.

- If its about the `@react-native/asset-registry` we've discussed internally, React Native needs adjustments for us to be able to properly resolve these modules. No package manager satisfies peer dependencies by transitive dependencies, not even npm. If `react-native` manages the version of a specific package through it's own dependencies, it needs to be properly exposed for us to import it. E.g. something like `react-native/assetRegistry` could work, similarly to how we let users import `expo/config-plugins` and `expo/metro-config`, and still let `expo` control these versions. Unfortunately, the `@react-native/asset-registry` package seems to no default entrypoint (only nested import paths), which makes this approach harder than it should be.

- If its about the `expo/AppEntry`, see below.

> The Expo template [doesn't work in npm workspaces](https://github.com/facebook/react-strict-dom/blob/71b4bcdcdb3f7f0d9b6f21cc17918a3eb74f0f92/apps/examples/src/index.js#L10-L12)

I think you are referring to the `expo/AppEntry` from the blank template (not the default template) not working correctly in workspaces, right? If so, you are right, the hardcoded import of `../../App` may or may not work, depending on how the package manager sets up your `node_modules` folders. That's why we recommend to modify this, and [use your own entrypoint](https://docs.expo.dev/guides/monorepos/#change-default-entrypoint):

<img width="1128" alt="image" src="https://github.com/expo/expo/assets/1203991/2f149efd-96f7-4a61-9e66-dca0f8171486">

For Expo Router projects, like our default template, this is different. In this case, we are dynamically resolving the routes without hardcoded paths. Unfortunately, we don't have a great alternative for `expo/AppEntry` entrypoints yet, as it would require Metro changes or exposing the project root and using dynamic import paths.

If we can help upgrading to SDK 51 in the react-strict-dom repo, I'd love to help. Just let me know how we can help!

Hope this helps!

**Comment by byCedric** [comment]
To follow-up, I just upgraded my monorepo example to SDK 51, and it seems to work without issues: https://github.com/byCedric/expo-monorepo-example/pull/121.

**Comment by necolas** [comment]
> I just upgraded my monorepo example to SDK 51, and it seems to work without issues

Maybe because it's not using npm?

**Comment by byCedric** [comment]
@necolas It's not just pnpm; its also [bun](https://github.com/byCedric/expo-monorepo-example/pull/123), [npm](https://github.com/byCedric/expo-monorepo-example/pull/122), and [yarn](https://github.com/byCedric/expo-monorepo-example/pull/124).

**Comment by necolas** [comment]
I'm confused. I explained in detail why undeclared dependencies were causing Expo builds to failing in the npm workspace.

**Comment by byCedric** [comment]
I'm not sure exactly which package(s) you refer to:
> Expo is making a bad assumption - that other packages containing these dependencies will be installed

If it's the `@react-native/asset-registry`, there is currently no reliable way for us to load it using the exact version that `react-native` is using. Other than to first resolve react-native, then resolve `@react-native/asset-registry` from that path. However, it won't solve the bad assumptions, as we still "expect" it will be there.

I'd be happy to investigate or take a closer look at other cases if you can provide them 😄

**Comment by dani-mp** [comment]
hey, folks

I'm also having problems with a monorepo and npm, I followed the expo guide for monorepos and my interpretation was:

To use a custom metron config (this is the one I'm using):
```
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

// Find the project and workspace directories
const projectRoot = __dirname;
// This can be replaced with `find-yarn-workspace-root`
const monorepoRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

// 1. Watch all files within the monorepo
config.watchFolders = [monorepoRoot];
// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(monorepoRoot, 'node_modules'),
];

module.exports = config;
```

To use `EXPO_USE_METRO_WORKSPACE_ROOT`:
```
"start": "EXPO_USE_METRO_WORKSPACE_ROOT=1 npx expo start"
```

I'm also because I'm using expo router, I don't have a custom entry point:
```
"main": "expo-router/entry"
```

when I created the project some days ago, I think it was v51.0.15, and this configuration was working.

Today, I installed the latest `"expo": "~51.0.17"` and I started getting errors similar to what I think @necolas mentioned:

```
Error: Cannot find module 'metro/src/lib/TerminalReporter'
```

(and if I add metro to my dev dependencies, another error from a different dependency pops up)

**Comment by byCedric** [comment]
Hi @dani-mp! Do you have a repository that I can use to investigate this? I've tried replicating a test repo with the exact same config, but that seems to work fine.

- Basic monorepo setup: https://github.com/byCedric/test-expo-30143
- Using the custom metro config: https://github.com/byCedric/test-expo-30143/blob/custom-metro-config/apps/test-app/metro.config.js
- Using the custom `EXPO_USE_METRO_WORKSPACE_ROOT=1 npx expo start`: https://github.com/byCedric/test-expo-30143/blob/custom-workspace-root-start/apps/test-app/package.json#L6

**Comment by dani-mp** [comment]
@byCedric thanks for setting up the test repo, I'll take a look at it tomorrow with a fresh mind and compare it to mine, and will follow up. 🙏

**Comment by dani-mp** [comment]
@byCedric but just to be clear, do I need:
- the custom metro config?
- the `EXPO_USE_METRO_WORKSPACE_ROOT=1` env var?

**Comment by byCedric** [comment]
@dani-mp No worries, and:

> the custom metro config?

Not for a standard npm monorepo, Expo detects this and sets it up automatically. Only for pnpm this is required. But, the metro config you provided is correct so with or without, it should work.

> the `EXPO_USE_METRO_WORKSPACE_ROOT=1` env var?

This is something we are testing, but I would highly recommend turning it on. It skews the paths a bit better for monorepos, and avoids possible cache conflicts with "identical apps" running in the same monorepo.

**Comment by Kudo** [comment]
i tried to update sdk 51 in RSD repo and i didn't come across the problem. this is my [change](https://github.com/facebook/react-strict-dom/compare/main...Kudo:react-strict-dom:%40kudo/expo-sdk51?expand=1).

wondering if that could be npm version? my node is v20.14.0 and npm is v10.7.0

**Comment by byCedric** [comment]
Awesome, glad you got it sorted for your repo @dani-mp! I would personally consider the `node_modules` in your monorepo as unstable. It may change at any given time due to different package resolutions.

E.g. in my case, I tested why `react-native` would break when using multiple versions. To do that, I added `"peerDependencies": { "react-native": "^0.73.0" }` to **packages/test-pkg/package.json** (which is obviously incorrect, as I'm using `react-native@0.74.x` in **apps/test-app/package.json).

One thing that we did find, which touches on @necolas's point, is that somehow npm prioritizes hoisting with `peerDependencies` over normal `dependencies`. Meaning, my monorepo looked like:
```
- apps/test-app/package.json -> dependencies:react-native@0.74.2
- apps/test-app/node_modules -> react-native@0.74.2
- packages/test-pkg/package.json -> peerDependencies:react-native@^0.73.0
- node_modules -> react-native@0.73.8
```

Unfortunately, when any library is hoisted (`apps/test-app/node_modules → node_modules`) and tries to resolve `react-native`, it will always hit the wrong `react-native` version (`0.73.8`). This issue exists in `expo-*` packages, but also in many community libraries.

An alternative solution that I came up with, that still requires intensive testing, is modifying the **metro.config.js** and use a custom `resolveRequest`:

```js
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

module.exports = withForcedReactNativePath(getDefaultConfig(__dirname));

function withForcedReactNativePath(config) {
  // Resolve the project's react native path
  const reactNativePath = path.join(require.resolve('react-native/package.json'), '..');

  // Redirect any `react-native` or `react-native/*` resolutions to the correct path
  config.resolver.resolveRequest = (context, moduleName, platform) => {
    let redirectedModuleName = undefined;

    if (!redirectedModuleName && moduleName === 'react-native' || moduleName.startsWith('react-native/')) {
      redirectedModuleName = context.redirectModulePath(
        moduleName.replace('react-native', reactNativePath)
      );

      // Drop this if you don't want any logging
      console.log(
        '[REDIRECT]', 
        moduleName, 
        '->', 
        redirectedModuleName === false 
          ? '<empty module>' 
          : redirectedModuleName
      );
    }

    return context.resolveRequest(
      context, 
      redirectedModuleName !== undefined 
        ? redirectedModuleName 
        : moduleName, 
      platform
    );
  };

  return config;
}
```

This would force any `react-native`/`react-native/...` imports to the correct **apps/test-app** react native path.

**Comment by byCedric** [comment]
I just pulled up some stats on packages importing `react-native`, but do not specify its peer dependency.

- From all packages on https://reactnative.directory/ (roughly 1000)
- 27.5% import `react-native`, without specifying the peer dependency
  - `expo-*` packages account for 3.5% of that
- Most common peer dependency reference is `"react-native": "*"` (32.4%)
  - Followed by a few `"react-native": ">=0.XX.Y"` references (>2.2%)

**Comment by SimonVillage** [comment]
@byCedric using the `Basic monorepo setup` repo. Running `npm run start` work without issues, however `npx expo run:ios` / `npm run ios` fails:

```
/Users/simon/Downloads/test-expo-30143-main/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112
        throw new UnableToResolveError(
              ^
Error: Unable to resolve module ./node_modules/expo-router/entry from /Users/simon/Downloads/test-expo-30143-main/apps/test-app/.: 

None of these files exist:
  * node_modules/expo-router/entry(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css)
  * node_modules/expo-router/entry/index(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css)
    at ModuleResolver.resolveDependency (/Users/simon/Downloads/test-expo-30143-main/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (/Users/simon/Downloads/test-expo-30143-main/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/simon/Downloads/test-expo-30143-main/node_modules/metro/src/lib/transformHelpers.js:156:21
    at HmrServer._registerEntryPoint (/Users/simon/Downloads/test-expo-30143-main/node_modules/metro/src/HmrServer.js:49:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
```

**Comment by mosesfinlay** [comment]
I kept getting this error in my turbo monorepo and I solved it by switching package managers from npm to pnpm. Hopefully this helps anyone who might be experiencing the same thing!
`iOS Bundling failed 2721ms apps/mobile/node_modules/expo-router/entry.js (917 modules)
error: node_modules/expo-router/_ctx.ios.js: node_modules/expo-router/_ctx.ios.js:Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT
First argument of `require.context` should be a string denoting the directory to require.`

**Comment by FezVrasta** [comment]
After I update the metro.config.js with the one provided by [byCedric](https://github.com/byCedric) in https://github.com/expo/expo/issues/30143#issuecomment-2209170420 I get the following error:

```
TypeError: Cannot read property 'useId' of null
```

I'm starting from a fresh project bootstrapped with Gluestack. Any idea?

![CleanShot 2024-11-05 at 5  42 18@2x](https://github.com/user-attachments/assets/e19efca1-b2dc-48be-b1b6-632d61010499)

**Comment by kev0960** [comment]
Same issue as described on https://github.com/expo/expo/issues/30143#issuecomment-2457674039. 

It does not work on both Android and iOS, and regardless of patching the metro.config.js or not.

**Comment by Entropy-10** [comment]
I'm having the same `Cannot read property 'useId' of null` error as well with expo 52, bun, and turborepo. @byCedric would you have any insights on this?

**Comment by kev0960** [comment]
@Entropy-10 FYI, I was able to fix the problem by making React's version of the packages in the monorepo to be identical. It seems like when the different packges in the monorepo uses the different react version, it somehow collides each other.

**Comment by Entropy-10** [comment]
@kev0960 thanks for the suggestion! unfortunately I'm running nextjs 15 which uses react 19 so I can't use the same version of react. Though that did give me the idea to use overrides in my package.json which worked!

`apps/mobile/package.json`
```json
"overrides": {
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "@types/react": "18.3.12"
}
```

**Comment by fabricio-yoke** [comment]
To fix this I created a `.npmrc` file in the root folder with `shared-workspace-lockfile=false`. This way, each project has its own `pnpm-lock.yaml`

**Comment by ilterugur** [comment]
> [@kev0960](https://github.com/kev0960) thanks for the suggestion! unfortunately I'm running nextjs 15 which uses react 19 so I can't use the same version of react. Though that did give me the idea to use overrides in my package.json which worked!
> 
> `apps/mobile/package.json`
> 
> "overrides": {
>     "react": "18.3.1",
>     "react-dom": "18.3.1",
>     "@types/react": "18.3.12"
> }

Did it really work on your project? I'm trying to use react 19 on vite and react 18 on expo. Using overrides doesn't fix my case on my bun turborepo

**Comment by DavidHooper** [comment]
I had this issue and have been able to resolve it by deleting all node_modules and the package-lock.json of my npm workspaces and rerunning with `expo start --clear`.

Not ideal, but I could see multiple versions of react-native show up in the package-lock despite using overrides.

**Comment by SennaSanzo** [comment]
Hi everyone,

Since the issue title is pretty generic, I ask it there: Has someone succeeded to import shared package of a monorepo (turborepo) into Expo project by using "exports" functionnality of package.json ? Currently I'm obliged to specify a main entry point (index) and do some kind of barrel stuff so that Expo app can import my shared package correctly. Seems like exports from other packages are not available in Expo projects. In Next.js projects everything is ok...

See: [turborepo docs](https://turbo.build/repo/docs/crafting-your-repository/creating-an-internal-package#add-a-packagejson)

**Comment by austinm911** [comment]
@SennaSanzo  can you share more detail on how you worked around this? I dealing with the same issue of not being able to getting my `apps/native` (the expo app) to be able to import from other packages in a monorepo (turborepo) setup

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/473be0ca-441a-4950-beec-5caab1062bd2" />

**Comment by hexcowboy** [comment]
Using `sharedWorkspaceLockfile: false` in the root `pnpm-workspace.yaml` has really been the best solution for this. You can still share dependencies between projects by installing shared deps in the project workspace `pnpm i -w react`, and really the only downside is you don't get to use pnpm's dependency sharing (not a huge deal).

`sharedWorkspaceLockfile: false` just gives every package in your monorepo its own `pnpm-lock.yaml` and `node_modules` instead of sharing one at the root of the monorepo.

**Comment by SennaSanzo** [comment]
@austinm911 Oh i'm so sorry man. I missed your question. If this is still a problem for you one month later, instead of explaining what I did, I think Expo 53 and the new metro implementation are dealing exports much more smoothly than before. If this is a possibility for you git it a try... Using pnpm can also be a good angle to try since it handles a lot better the monorepos (so turborepo too) in my opinion.

**Comment by rafinskipg** [comment]
I have SPENT COUNTLESS HOURS trying to get expo to work with my yarn monorepo, last version. THERE IS NO WAY TO MAKE THIS WORK OR WHAT

**Comment by chris-garrett** [comment]
> I have SPENT COUNTLESS HOURS trying to get expo to work with my yarn monorepo, last version. THERE IS NO WAY TO MAKE THIS WORK OR WHAT

FWIW, this is one example that works for me:  https://github.com/tamagui/starter-free/tree/main/apps/expo

**Comment by lukaszblasz** [comment]
For me putting install-strategy = "nested" into .npmrc root file and also placing same .npmrc into my expo subpackage helped.

Not sure why but putting it only at root level does not hep.

**Comment by kitten** [comment]
Monorepo issues should be resolved in SDK 54. We don't have a repro in this issue, so for now I'll close it, since this is working as expected in all our testing. Any new issues are unrelated.

To address a few comments from this thread (in arbitrary order), as of SDK 54:
- `pnpm` is supported, isolated dependency installations are supported
- obsolete (pre SDK 52) config options in customised Metro configs are now flagged as such by `expo-doctor`, since they can cause issues and are obsolete since SDK 52 (docs are also up-to-date)
- `Cannot read property [...] of null` errors in React are due to duplicated versions of `react`. Aligning versions of react has and does always resolve this. If a monorepo requires two versions of React, `experiments.autolinkingModuleResolution: true` smooths this over and effectively fixes this
- `EXPO_USE_METRO_WORKSPACE_ROOT` has been obsolete since SDK 53 and the default

**Comment by stefan-schweiger** [comment]
@kitten I have a weird case after upgrading to expo 54 in a nx mono repo, that expo router is not able to resolve the `src/app` directory anymore. Only thing that helped was to manually add `root: __dirname + '/src/app'` in `app.config.js`. My best guess would be some complication due to the metro workspace root not being correctly figured out.

I have a repro on hand, but wanted to make sure that the `__dirname` isn't intended before I open a bug for it.

**Comment by wildseansy** [comment]
@stefan-schweiger - I have been noticing the same thing with nx + expo 54
