### ISSUE TITLE
`npx expo export` inaccurately reports "In iOS native project: Hermes is not enabled"

### ISSUE THREAD

**Issue by msbit** [expo/expo#30264]
### Summary

Starting with a react-native app, then adding the expo modules (as per https://docs.expo.dev/bare/installing-expo-modules/) leaves the app in a state where running `npx expo export` fails with:

```
Starting Metro Bundler
Error: JavaScript engine configuration is inconsistent between app.json and iOS native project.
In app.json: Hermes is enabled
In iOS native project: Hermes is not enabled
Please check the following files for inconsistencies:
  - /private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/app.json
  - /private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/ios/Podfile
  - /private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/ios/Podfile.properties.json
Learn more: https://expo.fyi/hermes-ios-config
Error: JavaScript engine configuration is inconsistent between app.json and iOS native project.
In app.json: Hermes is enabled
In iOS native project: Hermes is not enabled
Please check the following files for inconsistencies:
  - /private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/app.json
  - /private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/ios/Podfile
  - /private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/ios/Podfile.properties.json
Learn more: https://expo.fyi/hermes-ios-config
    at maybeThrowFromInconsistentEngineAsync (/private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/node_modules/@expo/cli/src/export/exportHermes.ts:77:11)
    at assertEngineMismatchAsync (/private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/node_modules/@expo/cli/src/export/exportHermes.ts:13:3)
    at /private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/node_modules/@expo/cli/src/export/exportApp.ts:133:13
    at async Promise.all (index 0)
    at exportAppAsync (/private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/node_modules/@expo/cli/src/export/exportApp.ts:127:7)
    at exportAsync (/private/var/folders/_g/kc3wz03n2mb32x9ty7m6sh9m0000gn/T/tmp.yepXp39zy7/foobar/node_modules/@expo/cli/src/export/exportAsync.ts:19:3)
```

I don't believe this (`In iOS native project: Hermes is not enabled`) to be correct, as the default value of `hermes_enabled` for iOS is based on the `USE_HERMES` environment variable (as per https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L66). This variable is unset and so the value of `hermes_enabled` is true.

From scratch:

```
#!/usr/bin/env bash

set -eux

name=${1}

pushd $(mktemp -d)
npx react-native init --install-pods false ${name} 
pushd ${name}
npx install-expo-modules --non-interactive
npx expo export
```

### What platform(s) does this occur on?

iOS

### SDK Version

51.0.0

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.2.26 - /opt/local/bin/bash
    Binaries:
      Node: 18.20.2 - /opt/local/bin/node
      Yarn: 3.6.4 - ~/bin/yarn
      npm: 9.9.3 - /opt/local/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/tom/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    Expo Workflow: bare
```

### Minimal reproducible example

https://github.com/msbit/swh1YJSlQZqdE7U7lxO1m

**Comment by msbit** [comment]
@byCedric any motion on this one?

**Comment by knowbody** [comment]
this is something I've been running into for a few weeks now.

the hacky solution is to add this line to the Podfile, just before running the export script

```
:hermes_enabled => true
```

This cannot be committed though, as it breaks the iOS build process.

I'd love this to be fixed, happy to help in any way I can.

**Comment by scarlac** [comment]
Comment to fend off the zombie comment bot. This is still an issue.
The workaround is to modify app.json so tell it that you aren't using Hermes:
```json
{
  "name": "MyApp",
  "displayName": "MyDisplayName",
  "expo": {
    "jsEngine": "jsc",
    // ...
```
Then it'll detect it correctly. However, there are other subsequent issues that may arise, such as:
`Your source map refers to generated column 35 on line 20, but the source only contains 34 column(s) on that line.
  Check that you are using the correct source map`
which can be temporarily circumvented by adding `--no-border-checks` when running `npx source-map-exporer`. However, it does seem like the export feature isn't working as intended. Possibly a Metro bug. react-native-bundle-visualizer has the same kind of issues.

**Comment by frid-pnpt** [comment]
For now, I'm using [scarlac](https://github.com/scarlac)'s workaround. (Thank you!)
Is there any solution to solve this problem correctly?
