### ISSUE TITLE
Expo Web can’t use an ESM package with import.meta.

### ISSUE THREAD

**Issue by MJRT** [expo/expo#30323]
### Minimal reproducible example

https://github.com/MJRT/import-meta-url-error-on-web

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

```
AppEntry.bundle:87829 
Uncaught Syntax Error: Cannot use 'import.meta' outside a module
```
The error appeared after used [PGlite](https://github.com/electric-sql/pglite/) package, that can [reproduce easily](https://github.com/MJRT/import-meta-url-error-on-web).

It is worth mentioning that `@babel/plugin-syntax-import-meta` is not working, even though use `expo start --clear`.

I tried some way on google and chatgpt, but they are all not working:
1. add `"type": "module",` to `package.json`, but get error: 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/jinhao/repositories/examples/expo/metro.config.js from /home/jinhao/repositories/examples/expo/node_modules/metro-config/node_modules/import-fresh/index.js not supported.
metro.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename metro.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/jinhao/repositories/examples/expo/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```
2. use babel plugins  `transform-dirname-filename` and `babel-plugin-transform-import-meta` that with  `expo start --clear`, but get error:
```
__filename is not defined
```
3. Other attempts...

Lots of web packages are using `import.meta` with ESM, I'm a beginner in this field, does anyone know how to solve it?

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/.local/share/pnpm/node
      npm: 10.8.1 - /home/linuxbrew/.linuxbrew/bin/npm
      Watchman: 2024.05.06.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-233.14808.21.2331.11842104
    npmPackages:
      expo: ~51.0.9 => 51.0.18
      react: ^18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by jasonlewicki** [comment]
same problem

**Comment by jancbeck** [comment]
I have the same problem when trying to use @payloadcms (which uses import.meta internally) inside an api route

**Comment by jancbeck** [comment]
After spending a weekend on this I found a solution for my situation:

### 1. Install [Expo canary](https://docs.expo.dev/versions/latest/#canary-releases) 
`npm install expo@canary`

I did not run `npx expo install --fix` to upgrade the other expo packages because that cause new issues.
The latest Expo canary supports dynamic imports in server packages and when you run it will warn about the dependencies that have them which is helpful for the next step.

### 2. Use babel plugins

- [`babel-plugin-transform-import-meta`](https://www.npmjs.com/package/babel-plugin-transform-import-meta) replaces all occurrences of `import.meta.url` with `require('url').pathToFileURL(__filename).toString()`
- [`@reactioncommerce/babel-remove-es-create-require`](https://www.npmjs.com/package/@reactioncommerce/babel-remove-es-create-require)  removes all lines where you're calling `createRequire`

```
// babel.config.js
/** @type {import("@babel/core").ConfigFunction} */
module.exports = (api) => {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    overrides: [
      {
        test: [/@payloadcms/, /payload/, /prettier/],
        plugins: [
          "babel-plugin-transform-import-meta",
          "module:@reactioncommerce/babel-remove-es-create-require",
        ],
      },
    ],
  };
};
```

`@payloadcms`, `payload` and `prettier` were the dependencies that caused bundling and runtime errors because of dynamic imports and inserting `createRequire`. `@payloadcms` includes `drizzle` for the postgresql adapter which caused a lot of the issues. 

## Related settings

One dependency included `prettier` as a production dependency but that isn't used as far as I can tell. It didn't end up being necessary but you could configure metro to resolve it as an empty module like this:

```
// metro.config.js
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (platform === "web" && moduleName === "prettier") {
    return {
      type: "empty",
    };
  }

  // Ensure you call the default resolver.
  return context.resolveRequest(context, moduleName, platform);
};
```

There are also these unstable / experimental settings - not sure how they relate to the issue:

```
config.transformer.getTransformOptions = async () => ({
  transform: {
    experimentalImportSupport: true,
  },
});
config.resolver.unstable_enablePackageExports = true;
```

I'm using a [mono-repo template](https://github.com/t3-oss/create-t3-turbo/) so I also needed to manually load `.env` from the workspace root because Expo doesn't use `find-up` like Next to discover these.

```
const findWorkspaceRoot = require("find-yarn-workspace-root");
const workspaceRoot = findWorkspaceRoot(__dirname);

// Load the environment variables from the workspace root .env file
require("@expo/env").load(workspaceRoot, { force: true });
```

There are also several recent PRs related to RSC by @EvanBacon that make me hopeful that this workaround won't be necessary for long:
- https://github.com/expo/expo/pull/30334
- https://github.com/expo/expo/pull/30005
- https://github.com/expo/expo/pull/27638
- https://github.com/expo/expo/pull/30763
- https://github.com/expo/expo/pull/30348
- https://github.com/expo/expo/pull/30347

**Comment by EvanBacon** [comment]
Expo web doesn't support browser ESM at the moment. This is because React Native doesn't have support and we try to keep the bundling targets as similar as possible to reduce the chance of something breaking between targets. 

Not opposed to adding native ESM support though, it's just not the highest priority at the moment.

**Comment by jancbeck** [comment]
I come from Next.js and before this have never touched RN, Expo or bundlers before but saw your talk at React Conf. My hope was that I could just drop-in the same route handler that I use in Next for Expo API routes. So from my perspective, it should definitely be a higher priority to smooth the transition between both. 
Love the work you are doing btw!

**Comment by jmurphy4** [comment]
+1 for getting ESM support. Tried following Jan's steps for pglite but no dice

**Comment by jancbeck** [comment]
Haven't tested it myself yet but node 23 could resolve this
https://nodejs.org/en/blog/release/v23.0.0#requireesm-is-now-enabled-by-default
https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/

**Comment by akpor-kofi** [comment]
Any update on this please. because i'm trying to use wa-sqlite (SQLite WASM) on the web and that package makes use of import.meta

**Comment by AntonOfTheWoods** [comment]
@EvanBacon , I haven't even started with native yet but from the looks of the linked issues, esm is now reasonably well supported by the upstream stuff. Does that mean expo could now support esm?

I'm mainly interested because there are some expo-sqlite features I would like to port to pglite... But if there are known gotchas that might be a fool's errand.

**Comment by devinrhode2** [comment]
@brockklein Looking at this thread, I wonder if the issue could have been resolved by the linked PR. Could be worth updating the original "Minimal reproducible example" linked at the very top to use latest version of expo.

**Comment by brockklein** [comment]
@devinrhode2 interesting, it looks like that linked PR is running Expo `51.0.31` and my [repro and solution](https://github.com/brockklein/expo-pglite) was on `52.0.33` so I'm pretty sure it would have already included those changes to Expo.

**Comment by giaset** [comment]
In SDK 53 you should be able to add `unstable_transformImportMeta: true` to your `babel.config.js`

```
presets: [
      [
        'babel-preset-expo',
        {
          unstable_transformImportMeta: true
        }
      ]
    ]
```

**Comment by 1mehdifaraji** [comment]
This issue is ESM-related and basically has 3 main factors:

Expo SDK 52 enforces Hermes and the New Architecture by default, which lacks native ESM support.

Zustand 5.0.3 uses ESM conditionals that Hermes cannot resolve.

Downgrading or Metro configuration are current workarounds until Hermes gains ESM support.

However I solved it by modifying the metro config file

```javascript
// Prioritize CommonJS modules over ESM, bypassing `import.meta` checks
module.exports = {
  resolver: {
    unstable_conditionNames: ['browser', 'require', 'react-native'],
  },
};
```
package.json
```json
"@rn-primitives/avatar": "^1.1.0",
"@rn-primitives/checkbox": "^1.1.0",
"@rn-primitives/dropdown-menu": "^1.1.0",
"@rn-primitives/hooks": "^1.1.0",
"@rn-primitives/portal": "^1.1.0",
"@rn-primitives/radio-group": "^1.1.0",
"@rn-primitives/slot": "^1.1.0",
"@rn-primitives/types": "^1.1.0",
"zustand": "5.0.3",
"expo": "52.0.7"
```

**Comment by adamteale** [comment]
@1mehdifaraji thank you, adding `unstable_conditionNames: ['browser', 'require', 'react-native'],` got things working again for me!

**Comment by stephane-segning** [comment]
Those like me applying this and having issues:
```javascript
module.exports = {
  resolver: {
     unstable_conditionNames: ['browser', 'require', 'react-native'],
  },
};
```

then update it like this:
```javascript
const {getDefaultConfig} = require('expo/metro-config'); // <-- this line will help get the default config
const _ = require('lodash');

const config = getDefaultConfig(__dirname); // <-- this will help create the default config

// ...
config.resolver.unstable_conditionNames = _.uniq(config.resolver.unstable_conditionNames.concat('browser', 'require', 'react-native')); // <-- and here we can override what we want
// ...

module.exports = config;
```

**Comment by kitten** [comment]
As said above, the necessary switch to support `import.meta` is `unstable_transformImportMeta` on the Expo babel preset, `babel-preset-expo`, until we enable this by default in a stable release. It's also worth checking which package causes this and trace it down (e.g. with Expo Atlas), to see if it has a non-ESM version that you can resolve instead.

**Comment by jancbeck** [comment]
I currently have `babel-plugin-transform-import-meta` in my `babel.config.js`: https://github.com/jancbeck/expo-payload/blob/31f03fe480188fd0295832365eadfe67055bd971/babel.config.js#L29-L39

When I replace it with `unstable_transformImportMeta` I get this runtime error:

> Metro error: Cannot read properties of undefined (reading 'url')
> 
>   TypeError: Cannot read properties of undefined (reading 'url')
>     at factory (/Users/jb/workspace/oss/expo-payload/node_modules/[payload/dist/utilities/dependencies/dependencyChecker.js:5:44](https://github.com/payloadcms/payload/blob/39143c9d12ac81de25e677517b58406ae81d317f/packages/payload/src/utilities/dependencies/dependencyChecker.ts#L7))
>     at loadModuleImplementation (/Users/jb/workspace/oss/expo-payload/node_modules/@expo/cli/build/metro-require/require.js:241:36)
>     at guardedLoadModule (/Users/jb/workspace/oss/expo-payload/node_modules/@expo/cli/build/metro-require/require.js:157:16)
>     at require (/Users/jb/workspace/oss/expo-payload/node_modules/@expo/cli/build/metro-require/require.js:68:75)
>     at factory (/Users/jb/workspace/oss/expo-payload/node_modules/payload/dist/checkPayloadDependencies.js:1:1)
>     at loadModuleImplementation (/Users/jb/workspace/oss/expo-payload/node_modules/@expo/cli/build/metro-require/require.js:241:36)
>     at guardedLoadModule (/Users/jb/workspace/oss/expo-payload/node_modules/@expo/cli/build/metro-require/require.js:157:16)
>     at require (/Users/jb/workspace/oss/expo-payload/node_modules/@expo/cli/build/metro-require/require.js:68:75)
>     at factory (/Users/jb/workspace/oss/expo-payload/node_modules/payload/dist/index.js:34:1)
>     at loadModuleImplementation (/Users/jb/workspace/oss/expo-payload/node_modules/@expo/cli/build/metro-require/require.js:241:36)
> POST http://localhost:8081/api/auth/sign-in/social

So at least in my case `unstable_transformImportMeta` doesn't do the same as the plugin.

**Comment by jancbeck** [comment]
Not stale

**Comment by a-eid** [comment]
any updates on this .. cc @Kudo

**Comment by federicogomez-stowlog** [comment]
not stale

**Comment by csheppard** [comment]
+1 this works for me:

**babel.config.js**
```ts
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [
      [
        "babel-preset-expo",
        {
          web: {
            unstable_transformImportMeta: true,
          },
        },
      ],
    ],
  }
}
```

**Comment by kitten** [comment]
`unstable_transformImportMeta` will become the default in SDK 56 which will (eventually) resolve this issue then: #44239

Until then, enabling `unstable_transformImportMeta` for `babel-preset-expo`, as shown [above](https://github.com/expo/expo/issues/30323#issuecomment-3880279411), is a way to change the default.
