### ISSUE TITLE
install-expo-modules crashes if babel.config.json is used instead of babel.config.js

### ISSUE THREAD

**Issue by wojtekmaj** [expo/expo#30355]
### Summary

I tried to use install-expo-modules to migrate from plain RN to Expo, and I was immediately met with this error:

```
✔ We recommend installing the Expo CLI integration for the best experience. Not using it may result in some features not working as expected. Learn more: https://docs.expo.dev/bare/using-expo-cli/
Install the Expo CLI integration? … yes
› Updating your project...
Uncaught Error Error: [ios.dangerous]: withIosDangerousBaseMod: ENOENT: no such file or directory, open '…/app-native/babel.config.js'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:745010
    at async action (/private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:560958)
    at async interceptingMod (/private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:559653)
    at async interceptingMod (/private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:559653)
    at async interceptingMod (/private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:559653)
    at async action (/private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:533863)
    at async interceptingMod (/private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:559653)
    at async evalModsAsync (/private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-0b5771f5/dlx-72014/node_modules/install-expo-modules/build/index.js:34:541579) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '…/app-native/babel.config.js'
}
```

### What platform(s) does this occur on?

iOS

### SDK Version

n/a

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.4.1 - /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-8c7ce9a9/node
      Yarn: 4.3.1 - /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-8c7ce9a9/yarn
      npm: 10.8.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      react: 18.2.0 => 18.2.0 
      react-native: ^0.74.1 => 0.74.1 
    Expo Workflow: bare

### Minimal reproducible example

n/a

**Comment by marcinsuski** [comment]
I have exactly the same issue, but with .babelrc.json so I second the request for broader support.
