### ISSUE TITLE
Expo API Router Deployment fails with ESM 

### ISSUE THREAD

**Issue by ProchaLu** [expo/expo#30423]
### Minimal reproducible example

https://github.com/ProchaLu/expo-api-router-deployment

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

While the [Expo API Router documentation](https://docs.expo.dev/router/reference/api-routes/#esm-not-supported) states that ESM (ECMAScript Modules) is not supported, all other ESM-based TypeScript configurations in my project have been working seamlessly. I would like to maintain consistency by using ESM throughout the entire project.

### Error

When attempting to deploy the Expo API Router on Vercel, I encounter the following error message:

```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///var/task/api/index.js:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at c (/opt/rust/nodejs.js:8:13647)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 121.06 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///var/task/api/index.js:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at c (/opt/rust/nodejs.js:8:13647)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 212.79 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
```

This error happens because the file /var/task/api/index.js is being treated as an ES module due to the "type": "module" declaration in /var/task/package.json. However, Expo API Router does not support ESM, causing the deployment to fail.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - /opt/homebrew/opt/node@20/bin/node
      npm: 10.7.0 - /opt/homebrew/opt/node@20/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.20 => 51.0.20 
      expo-router: ^3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.3.1 => 18.3.1 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ^0.19.12 => 0.19.12 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by ProchaLu** [comment]
## Workaround

To deploy to Vercel while using ESM, I had to modify the `package.json` to switch from `"type": "module"` to `"type": "commonjs"`. This can be achieved inside the `vercel.json` file by specifying a custom `buildCommand`. 

Here’s the solution:

```json
"buildCommand": "expo export -p web && sed -i 's/\"type\": \"module\"/\"type\": \"commonjs\"/' package.json",
```

**Comment by ProchaLu** [comment]
@jancbeck, thx for the follow-up! I didn't open an issue for that

**Comment by jancbeck** [comment]
@ProchaLu would be great if you could. This saved me quite a lot of time. In any case thanks!

**Comment by karlhorky** [comment]
> > I ended up using your patch for expo-server headers. Did you open an issue for that already?
> 
> @jancbeck, thx for the follow-up! I didn't open an issue for that

No need to open an issue, it's already reported and fixed:

- https://github.com/expo/expo/issues/29431
- https://github.com/expo/expo/pull/29616

Just hasn't been published yet.

If you want to use this fixed version without waiting, just change to the canary version that has been published:

- https://github.com/expo/expo/pull/29616#issuecomment-2230772231

cc @kitten @EvanBacon

**Comment by karlhorky** [comment]
not stale

**Comment by karlhorky** [comment]
Not stale

**Comment by kitten** [comment]
We do publish `@expo/server` with hybrid outputs now, so assuming most of this is resolved. Please keep in mind that the instructions we've written in the docs don't assume `type: "module"` which is generally not expected to be used in this context or in this manner. Adjustments will need to be made if you want to rewrite the docs' given examples in `mjs` and/or with `package.json:type: "module"`
