### ISSUE TITLE
[CXX1210] node_modules/expo-modules-core/android/CMakeLists.txt debug|armeabi-v7a : No compatible library found

### ISSUE THREAD

**Issue by FahimMontasir** [expo/expo#30808]
### Summary

it shows when I use `npx expo run:android`. 

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

- expo sdk 51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.8 Kali GNU/Linux Rolling 2024.2
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
      npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
      Watchman: 2024.07.08.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    npmPackages:
      expo: ~51.0.24 => 51.0.24 
      expo-router: ~3.5.20 => 3.5.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: bare

### Reproducible demo

> Task :expo-modules-core:configureCMakeDebug[armeabi-v7a] FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeDebug[armeabi-v7a]'.
> [CXX1210] /home/fahim/Code/bc-app-startar/business-club/node_modules/expo-modules-core/android/CMakeLists.txt debug|armeabi-v7a : No compatible library found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 13s
449 actionable tasks: 25 executed, 424 up-to-date
Error: /home/fahim/Code/bc-app-startar/business-club/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8082 -PreactNativeArchitectures=armeabi-v7a exited with non-zero code: 1
Error: /home/fahim/Code/bc-app-startar/business-club/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8082 -PreactNativeArchitectures=armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (/home/fahim/Code/bc-app-startar/business-club/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/home/fahim/Code/bc-app-startar/business-club/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/home/fahim/Code/bc-app-startar/business-club/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/home/fahim/Code/bc-app-startar/business-club/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/home/fahim/Code/bc-app-startar/business-club/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)

**Comment by FahimMontasir** [comment]
still I have the issue

**Comment by ganeshkasture95** [comment]
i am also facing the same issue
