### ISSUE TITLE
AdMobInterstitial not working on Android api 28 (Android 9) - AbstractMethodError 

### ISSUE THREAD

**Issue by onka13** [expo/expo#3087]
### Environment
Android version: 9
Device: Emulator, Android SDK x86_64
Expo Client: 2.9.2
Expo sdk: v31.0.0

### Steps to Reproduce
Implement basic code below;

AdMobInterstitial.setAdUnitID("ca-app-pub-3940256099942544/8691691433")
AdMobInterstitial.setTestDeviceID("EMULATOR")
AdMobInterstitial.requestAdAsync().then(() => {
    AdMobInterstitial.showAdAsync()
})

### Actual Behavior

Throws an error and app is closing.

```
java.lang.AbstractMethodError: abstract method "boolean android.content.Context.canLoadUnsafeResources()"
       at android.content.ContextWrapper.canLoadUnsafeResources(ContextWrapper.java:946)
       at android.content.ContextWrapper.canLoadUnsafeResources(ContextWrapper.java:946)
       at android.widget.TextView.readTextAppearance(TextView.java:3561)
       at android.widget.TextView.<init>(TextView.java:924)
       at android.widget.TextView.<init>(TextView.java:869)
       at android.widget.TextView.<init>(TextView.java:865)
       at android.widget.TextView.<init>(TextView.java:861)
       at com.google.android.gms.ads.internal.webview.t.D(:com.google.android.gms.dynamite_adsdynamite@13280056@13.2.80 (040800-211705629):123)
       at com.google.android.gms.ads.nonagon.render.af.run(Unknown Source:2)
       at com.google.android.gms.ads.internal.util.future.ad.execute(:com.google.android.gms.dynamite_adsdynamite@13280056@13.2.80 (040800-211705629):4)
       at com.google.android.gms.ads.internal.util.future.z.run(Unknown Source:2)
       at com.google.android.gms.ads.internal.util.future.y.a(:com.google.android.gms.dynamite_adsdynamite@13280056@13.2.80 (040800-211705629):22)
       at com.google.android.gms.ads.internal.util.future.ag.b(:com.google.android.gms.dynamite_adsdynamite@13280056@13.2.80 (040800-211705629):64)
       at com.google.android.gms.ads.nonagon.ad.webview.k.a(Unknown Source:3)
       at com.google.android.gms.ads.internal.webview.j.o(:com.google.android.gms.dynamite_adsdynamite@13280056@13.2.80 (040800-211705629):19)
       at com.google.android.gms.ads.internal.webview.j.onPageFinished(:com.google.android.gms.dynamite_adsdynamite@13280056@13.2.80 (040800-211705629):201)
       at com.android.webview.chromium.Ap.onPageFinished(WebViewContentsClientAdapter.java:221)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:70)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Reproducible Demo

[https://snack.expo.io/rykz97UW4](
https://snack.expo.io/rykz97UW4)

**Comment by esamelson** [comment]
Thanks for letting us know about this @onka13 ! We'll look into it as soon as we can. In the meantime, does it work if you upgrade to a newer SDK version?

**Comment by mczernek** [comment]
@onka13 Thanks for submitting an issue!
Are you still observing this issue on the newest expo (32) and client (2.10.6)? 
I am executing your snack and cannot reproduce your issue.

**Comment by girishjjain** [comment]
I tried it with Expo SDK 32 and for me the Android app crashes on simulator, for physical device app goes into background. Verified the same behavior using this snack as well - https://snack.expo.io/@thetc/admob-example

Raised it on Expo forums as well: https://forums.expo.io/t/android-admob-interstitial-crashes-in-simulator-and-closes-on-device/21583

**Comment by mczernek** [comment]
Thanks for your reply!

Are you seeing an Ad after opening Interstitial?

I am observing that there is no actual crash in Android, but application is not restored after exiting interstitial ad. That is not the case on iOS. Is that what you observe? I will take a look at that inconsistency.

**Comment by girishjjain** [comment]
Thanks for looking into the issue.

#### Android
You're correct, on the Android device I do see Ad and then application is not restored after exiting interstitial ad. The crash happens on Android simulator.

#### iOS
You're correct, no issues on iOS.
