### ISSUE TITLE
Issue when trying to run in Android Tablet

### ISSUE THREAD

**Issue by leiteszeke** [expo/expo#30877]
### Minimal reproducible example

https://github.com/leiteszeke/a11y-playground

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Hello team

I have had a problem in the past days in one project that mainly runs on the Web, but when I moved to iOS / Android I found that in both platforms for mobile phone simulators/emulators, the app behaves as expected, the same when trying in iPad, however, when I try to run the app in an Android tab emulator, I received the following error. I tested this running expo run:android with prebuild, also in development build.

I created an empty project to verify if it was an issue with my project and possible dependencies, but even in a clean project, the issue remains

Let me know if more information is needed.
I attached a link to my clean project where I can reproduce the issue

```
Error: adb: failed to install /Users/leiteszeke/.expo/android-apk-cache/Exponent-2.31.2.apk: Failure [INSTALL_FAILED_INVALID_APK: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

Error: /Users/leiteszeke/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -d --user 0 /Users/leiteszeke/.expo/android-apk-cache/Exponent-2.31.2.apk exited with non-zero code: 1
    at ChildProcess.completionListener (/private/var/apps/discover/a11y-playground/node_modules/@expo/spawn-async/src/spawnAsync.ts:67:13)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:338:12)
    ...
    at spawnAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/spawn-async/src/spawnAsync.ts:28:21)
    at ADBServer.runAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/cli/src/start/platforms/android/ADBServer.ts:85:59)
    at Object.installAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/cli/src/start/platforms/android/adb.ts:217:10)
    at AndroidDeviceManager.installAppAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/cli/src/start/platforms/android/AndroidDeviceManager.ts:85:5)
    at ExpoGoInstaller.ensureAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/cli/src/start/platforms/ExpoGoInstaller.ts:140:9)
    at AndroidPlatformManager.openProjectInExpoGoAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/cli/src/start/platforms/PlatformManager.ts:119:27)
    at async Promise.allSettled (index 0)
    at openPlatformsAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/cli/src/start/server/openPlatforms.ts:10:19)
    at startAsync (/private/var/apps/discover/a11y-playground/node_modules/@expo/cli/src/start/startAsync.ts:125:3)
```

Thanks :)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
      Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/leiteszeke/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.25 => 51.0.25 
      expo-router: ~3.5.21 => 3.5.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by uzairrj** [comment]
The same thing is happening to me. Did you find any solution?

**Comment by leiteszeke** [comment]
> The same thing is happening to me. Did you find any solution?

Not yet, I spent some time before opening this issue and was not able to find a solution. I have not rechecked yet. It is not a high priority in my project at the moment.

**Comment by crisfeitosa** [comment]
The same thing is happening to me.

**Comment by uzairrj** [comment]
Ok, I know the fix; I was accidentally running the app on Beta API, i.e., API 35 (Android 15). Running the app on the API 33 (Android 13) fixed the issue and it is running fine on the tablets now.

**Comment by eyedroot** [comment]
> Ok, I know the fix; I was accidentally running the app on Beta API, i.e., API 35 (Android 15). Running the app on the API 33 (Android 13) fixed the issue and it is running fine on the tablets now.

Thanks!

**Comment by leo-caicedo** [comment]
> Ok, I know the fix; I was accidentally running the app on Beta API, i.e., API 35 (Android 15). Running the app on the API 33 (Android 13) fixed the issue and it is running fine on the tablets now.
Yes, this worked for me

**Comment by leo-caicedo** [comment]
> Ok, I know the fix; I was accidentally running the app on Beta API, i.e., API 35 (Android 15). Running the app on the API 33 (Android 13) fixed the issue and it is running fine on the tablets now.

Yes, this worked for me
