### ISSUE TITLE
exp init → Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by cem2ran** [expo/expo#309]
Filling this incase someone else bumps into it and is looking for an answer.

I believe the following is the status so far: https://github.com/react-community/create-react-native-app/issues/135#issuecomment-309518292 @brentvatne? (some solutions are mentioned towards the bottom of the discussion, e.g. https://github.com/react-community/create-react-native-app/issues/135#issuecomment-311453597)

**Env:**
- Mac OS: 10.12.5
- Exp v42.1.0
- Yarn v0.21.3
- Node v7.6.0

**Description**:
Getting the following error/warning whenever I run an exp command. Did a `yarn cache clean` followed by `yarn global add exp` to see if this changed anything. It didn't. Although it throws the below error, everything seems to be working.
```
❯ exp init reasonable-react-native-project
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cem2ran/.config/yarn/global/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cem2ran/.config/yarn/global/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cem2ran/.config/yarn/global/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
? Project type. Options are: "blank", "tabs" 
```

**Comment by dikaiosune** [comment]
cc @jesseruder -- I believe we had a fix planned for this, correct?

**Comment by satya164** [comment]
So I'm not the only one seeing this error.

**Comment by ickma** [comment]
Change your Python version to 2.7.x, and globally reinstall exp, and try again!

**Comment by brentvatne** [comment]
We removed the dependency on dtrace now :) If you install the latest version of exp you won't have this problem.
