### ISSUE TITLE
NoSuchMethodException: com.facebook.react.views.view.g.setLayoutDirectionOverride

### ISSUE THREAD

**Issue by anudit** [expo/expo#31146]
### Minimal reproducible example

This will be hard as I haven't been able to narrow down which component is causing the crash yet, the screen has a lot of components.

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

App crashes on RN `0.75.2` and expo `51`, this is when the app transitions from a loading state to when the components show up, Most of the features work this crash is only on one of the tab screens (will narrow down on which component but looks like `View` ? idk)

Logcat
```
2024-08-23 19:04:04.933  6178-6269  TrafficStats            com.cupoc.omnid                      D  tagSocket(197) with statsTag=0xffffffff, statsUid=-1
2024-08-23 19:04:04.971  6178-6178  RNSentry                com.cupoc.omnid                      D  Fragment is not a ScreenStackFragment, won't listen for the first draw.
2024-08-23 19:04:04.991  6178-6178  Compatibil...geReporter com.cupoc.omnid                      D  Compat change id reported: 303326708; UID 10518; state: DISABLED
2024-08-23 19:04:04.998  6178-6178  AutofillManager         com.cupoc.omnid                      D  view not autofillable - not passing ime action check
2024-08-23 19:04:05.080  6178-6178  WindowOnBackDispatcher  com.cupoc.omnid                      W  OnBackInvokedCallback is not enabled for the application.
                                                                                                    Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2024-08-23 19:04:05.145  1724-11138 ConnectivityService     system_server                        D  requestNetwork for uid/pid:10518/6178 activeRequest: null callbackRequest: 54062 [NetworkRequest [ REQUEST id=54063, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
2024-08-23 19:04:05.154  1724-2456  WifiNetworkFactory      system_server                        D  got request NetworkRequest [ REQUEST id=54063, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ]
2024-08-23 19:04:05.154  1724-2456  UntrustedW...orkFactory system_server                        D  got request NetworkRequest [ REQUEST id=54063, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ]
2024-08-23 19:04:05.157  1724-2456  OemPaidWif...orkFactory system_server                        D  got request NetworkRequest [ REQUEST id=54063, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ]
2024-08-23 19:04:05.158  1724-2456  MultiInter...orkFactory system_server                        D  got request NetworkRequest [ REQUEST id=54063, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ]
2024-08-23 19:04:05.198  6178-6178  AndroidRuntime          com.cupoc.omnid                      D  Shutting down VM
2024-08-23 19:04:05.199  6178-6178  AndroidRuntime          com.cupoc.omnid                      E  FATAL EXCEPTION: main
                                                                                                    Process: com.cupoc.omnid, PID: 6178
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:590)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
                                                                                                    Caused by: java.lang.NoSuchMethodException: com.facebook.react.views.view.g.setLayoutDirectionOverride [int]
                                                                                                    	at java.lang.Class.getMethod(Class.java:2937)
                                                                                                    	at java.lang.Class.getMethod(Class.java:2449)
                                                                                                    	at w7.f.onDraw(SourceFile:63)
                                                                                                    	at android.view.View.draw(View.java:24627)
                                                                                                    	at w7.f.draw(SourceFile:74)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                                                                                    	at android.view.View.draw(View.java:24357)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23484)
                                                                                                    	at android.view.View.draw(View.java:24357)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23484)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
2024-08-23 19:04:05.199  6178-6178  AndroidRuntime          com.cupoc.omnid                      E  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23449)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
2024-08-23 19:04:05.199  6178-6178  AndroidRuntime          com.cupoc.omnid                      E  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5313)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4975)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4093)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:945)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592)
                                                                                                    	... 3 more
2024-08-23 19:04:05.226  1724-11138 ActivityTaskManager     system_server                        W    Force finishing activity com.cupoc.omnid/.MainActivity
2024-08-23 19:04:05.228  6178-6259  TrafficStats            com.cupoc.omnid                      D  tagSocket(185) with statsTag=0xffffffff, statsUid=-1
2024-08-23 19:04:05.233  6178-6178  Process                 com.cupoc.omnid                      I  Sending signal. PID: 6178 SIG: 9
2024-08-23 19:04:05.326  1724-11138 ActivityManager         system_server                        I  Process com.cupoc.omnid (pid 6178) has died: fg  TOP 
2024-08-23 19:04:05.327  1724-12036 WindowManager           system_server                        I  WIN DEATH: Window{6c07b3a u0 com.cupoc.omnid/com.cupoc.omnid.MainActivity}
2024-08-23 19:04:05.327  1724-12036 InputManager-JNI        system_server                        W  Input channel object '6c07b3a com.cupoc.omnid/com.cupoc.omnid.MainActivity (client)' was disposed without first being removed with the input manager!
2024-08-23 19:04:05.328  1724-12036 WindowManager           system_server                        V  Loading animations: layout params pkg=com.cupoc.omnid resId=0x1030308
2024-08-23 19:04:05.328  1724-2464  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=54057, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ] (release request)
2024-08-23 19:04:05.328  1724-26177 ImeTracker              system_server                        I  com.cupoc.omnid:f84612a0: onRequestHide at ORIGIN_SERVER reason HIDE_REMOVE_CLIENT fromUser false
2024-08-23 19:04:05.328  1724-26177 ImeTracker              system_server                        I  com.cupoc.omnid:f84612a0: onCancelled at PHASE_SERVER_SHOULD_HIDE
2024-08-23 19:04:05.328  1724-2464  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=54059, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ] (release request)
2024-08-23 19:04:05.328  1724-2464  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=54063, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ] (release request)
2024-08-23 19:04:05.329  1724-2464  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=54061, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ] (release request)
2024-08-23 19:04:05.329  1724-2464  ConnectivityService     system_server                        D  releasing NetworkRequest [ REQUEST id=54055, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10518 RequestorUid: 10518 RequestorPkg: com.cupoc.omnid UnderlyingNetworks: Null] ] (release request)
2024-08-23 19:04:05.347  1724-1771  WindowManager           system_server                        W  Failed to deliver inset control state change to w=Window{6c07b3a u0 com.cupoc.omnid/com.cupoc.omnid.MainActivity EXITING}
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:485)
                                                                                                    	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3775)
                                                                                                    	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:376)
                                                                                                    	at com.android.server.wm.InsetsStateController.$r8$lambda$MnP7XA1MDcyrUwoj0hcoT5hTO8E(InsetsStateController.java:0)
                                                                                                    	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:314)
                                                                                                    	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:207)
                                                                                                    	at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:99)
                                                                                                    	at com.android.server.wm.WindowAnimator.$r8$lambda$AS_wbK9i-bc6ocCFop7s9PnXP80(WindowAnimator.java:0)
                                                                                                    	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(R8$$SyntheticClass:0)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:941)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:46)
2024-08-23 19:04:05.376  1724-1766  WindowManager           system_server                        V      info={id=15335 t=CLOSE f=0x10 trk=0 r=[0@Point(0, 0)] c=[
                                                                                                            {WCT{RemoteToken{7fc124a Task{3e69cc6 #1 type=undefined}}} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0x83ded21 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},
                                                                                                            {WCT{RemoteToken{ba3c5e7 Task{9055d91 #10739 type=standard A=10518:com.cupoc.omnid}}} m=CLOSE f=NONE leash=Surface(name=Task=10739)/@0xda7cd01 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},
                                                                                                            {null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{556849c token=android.os.Binder@112c0f})/@0x6ba2bec sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}
                                                                                                        ]}
2024-08-23 19:04:05.397  1724-1771  WindowManager           system_server                        W  Failed to deliver inset control state change to w=Window{6c07b3a u0 com.cupoc.omnid/com.cupoc.omnid.MainActivity EXITING}
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:485)
                                                                                                    	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3775)
                                                                                                    	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:376)
                                                                                                    	at com.android.server.wm.InsetsStateController.$r8$lambda$MnP7XA1MDcyrUwoj0hcoT5hTO8E(InsetsStateController.java:0)
                                                                                                    	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:314)
                                                                                                    	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:207)
                                                                                                    	at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:99)
                                                                                                    	at com.android.server.wm.WindowAnimator.$r8$lambda$AS_wbK9i-bc6ocCFop7s9PnXP80(WindowAnimator.java:0)
                                                                                                    	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(R8$$SyntheticClass:0)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:941)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:46)
2024-08-23 19:04:05.728  1724-1770  ActivityTaskManager     system_server                        W  Activity top resumed state loss timeout for ActivityRecord{2d48515 u0 com.cupoc.omnid/.MainActivity t10739 f} isExiting}
2024-08-23 19:04:05.816  1724-11579 WindowManager           system_server                        W  Exception thrown during dispatchAppVisibility Window{6c07b3a u0 com.cupoc.omnid/com.cupoc.omnid.MainActivity EXITING}
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:552)
                                                                                                    	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3217)
                                                                                                    	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1293)
                                                                                                    	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:403)
                                                                                                    	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7100)
                                                                                                    	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5820)
                                                                                                    	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5762)
                                                                                                    	at com.android.server.wm.Transition.finishTransition(Transition.java:1257)
                                                                                                    	at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:925)
                                                                                                    	at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:489)
                                                                                                    	at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:278)
                                                                                                    	at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:199)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1505)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1444)


### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2024.06.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 34
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0, 35.0.0
        System Images: android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.31 => 51.0.31
      expo-router: 3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.75.2 => 0.75.2
    npmGlobalPackages:
      eas-cli: 10.2.3
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

"expo": "^51.0.31",
"react-native": "0.75.2",

**Comment by anudit** [comment]
@alanjhughes

**Comment by alanjhughes** [comment]
@anudit already working on this 👍

**Comment by anudit** [comment]
@alanjhughes This is now fixed with the latest `expo-image` release, thanks!!

**Comment by alanjhughes** [comment]
@anudit great! Thanks for confirming 👍
