### ISSUE TITLE
[expo-av] IllegalStateException: Player is accessed on the wrong thread

### ISSUE THREAD

**Issue by jchao-pepper** [expo/expo#31225]
### Minimal reproducible example

https://github.com/jchao-pepper/expo-av-crash

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

On Android, the `Video` component from `expo-av` crashes the app with an `IllegalStateException` when it's unmounted immediately after `Updates.reloadAsync` is called. Previously raised on Discord here https://discord.com/channels/695411232856997968/920032594232500225/1278075701437923441

```
08-28 09:54:27.355  7627  7657 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
08-28 09:54:27.355  7627  7657 E AndroidRuntime: Process: com.test.expoavcrash, PID: 7627
08-28 09:54:27.355  7627  7657 E AndroidRuntime: java.lang.IllegalStateException: Player is accessed on the wrong thread.
08-28 09:54:27.355  7627  7657 E AndroidRuntime: Current thread: 'mqt_native_modules'
08-28 09:54:27.355  7627  7657 E AndroidRuntime: Expected thread: 'main'
08-28 09:54:27.355  7627  7657 E AndroidRuntime: See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2597)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:950)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1031)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at expo.modules.av.player.SimpleExoPlayerData.release(SimpleExoPlayerData.java:122)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at expo.modules.av.video.VideoView.unloadPlayerAndMediaController(VideoView.java:93)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at expo.modules.av.AVManager.onHostDestroy(AVManager.java:260)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at expo.modules.adapters.react.services.UIManagerModuleWrapper$3.onHostDestroy(UIManagerModuleWrapper.java:166)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at expo.modules.adapters.react.services.UIManagerModuleWrapper.onDestroy(UIManagerModuleWrapper.java:178)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at expo.modules.core.ModuleRegistry.onDestroy(ModuleRegistry.java:120)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at expo.modules.adapters.react.NativeModulesProxy.invalidate(NativeModulesProxy.java:170)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:109)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:86)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.lambda$destroy$2(CatalystInstanceImpl.java:352)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.$r8$lambda$M6ldpf8zIRREkmuc2xVoSJs-7ps(Unknown Source:0)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$$ExternalSyntheticLambda0.run(Unknown Source:2)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
08-28 09:54:27.355  7627  7657 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

The crash can be reproduced using the example repository when using the `release` variant -

```bash
npx expo run:android --variant release
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.10.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2024.07.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.31
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 10.0.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by wardjk87** [comment]
This happens for me also when testing on an eas dev build running on android physical device. If music is playing, and I reload the project, then I get the same exception. "Player is accessed on the wrong thread. Current thread 'mqt_native_modules'...". I tried wrapping all the uses of Expo-av in try/ catches, but they do not catch the error. This didn't happen on previous versions of Expo before v51. I'm using 14.0.6 of expo-av.

**Comment by work7z** [comment]
same error on my end

    "expo": "^51.0.28",
    "expo-av": "~14.0.7",

**Comment by brentvatne** [comment]
we're working on rewriting expo-av's Video component in expo-video: https://docs.expo.dev/versions/latest/sdk/video/

can you try reproduce your issue there?

**Comment by work7z** [comment]
> we're working on rewriting expo-av's Video component in expo-video: https://docs.expo.dev/versions/latest/sdk/video/
> 
> can you try reproduce your issue there?

thanks for your prompt replying.  

`expo-video` is working fine on my local, my previous error was caused by expo-av. I noticed it's going to be replaced by expo-video, guess there's some issue but it's ok since I just wanna fix this error

**Comment by mateuszbasiak** [comment]
Same error for me. Seeing it happening a lot also in production according to Sentry. Is there any chance for a fix in `expo-av`? Ideally, we'd like to avoid migrating to `expo-video` right now as we are using `Expo Go` for development.

**Comment by mateuszbasiak** [comment]
Was able to connect logcat and reproduce the issue on production build. 
```
Unhandled SoftException com.facebook.react.bridge.ReactNoCrashSoftException: Cannot get UIManager because the context doesn't contain an active CatalystInstance.
at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:76)
at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46) 
at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag(UIManagerHelper.java:40)
at expo.modules.adapters.react.services.UIManagerModuleWrapper.resolveView(UIManagerModuleWrapper.java:108)
at expo.modules.av.ViewUtils.tryRunWithVideoViewOnUiThread(ViewUtils.kt:21)
at expo.modules.av.ViewUtils.tryRunWithVideoView$lambda$0(ViewUtils.kt:44)
at expo.modules.av.ViewUtils.$r8$lambda$vSffXDAXp56z8j5DvDykgPT5VTU(Unknown Source:0)
at expo.modules.av.ViewUtils$$ExternalSyntheticLambda1.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8377)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```
Right before the the error.

**Comment by mateuszbasiak** [comment]
I was able to fix it for myself with following patch:

```
diff --git a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
index 672871d..4bf5385 100644
--- a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
+++ b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
@@ -12,6 +12,8 @@ import android.view.Surface;
 import androidx.annotation.NonNull;
 import androidx.annotation.Nullable;
 
+import com.facebook.react.bridge.UiThreadUtil;
+
 import com.google.android.exoplayer2.C;
 import com.google.android.exoplayer2.MediaItem;
 import com.google.android.exoplayer2.PlaybackException;
@@ -118,7 +120,12 @@ class SimpleExoPlayerData extends PlayerData
   public synchronized void release() {
     super.release();
     stopUpdatingProgressIfNecessary();
-    if (mSimpleExoPlayer != null) {
+    if (!UiThreadUtil.isOnUiThread() && mSimpleExoPlayer != null) {
+      UiThreadUtil.runOnUiThread(() -> {
+        mSimpleExoPlayer.release();
+        mSimpleExoPlayer = null;
+      });
+    } else if (mSimpleExoPlayer != null) {
       mSimpleExoPlayer.release();
       mSimpleExoPlayer = null;
     }
```

**Comment by work7z** [comment]
seems no updates

**Comment by seba9999** [comment]
up !

**Comment by VSKut** [comment]
up!

**Comment by VSKut** [comment]
> I was able to fix it for myself with following patch:
> 
> ```
> diff --git a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
> index 672871d..4bf5385 100644
> --- a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
> +++ b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
> @@ -12,6 +12,8 @@ import android.view.Surface;
>  import androidx.annotation.NonNull;
>  import androidx.annotation.Nullable;
>  
> +import com.facebook.react.bridge.UiThreadUtil;
> +
>  import com.google.android.exoplayer2.C;
>  import com.google.android.exoplayer2.MediaItem;
>  import com.google.android.exoplayer2.PlaybackException;
> @@ -118,7 +120,12 @@ class SimpleExoPlayerData extends PlayerData
>    public synchronized void release() {
>      super.release();
>      stopUpdatingProgressIfNecessary();
> -    if (mSimpleExoPlayer != null) {
> +    if (!UiThreadUtil.isOnUiThread() && mSimpleExoPlayer != null) {
> +      UiThreadUtil.runOnUiThread(() -> {
> +        mSimpleExoPlayer.release();
> +        mSimpleExoPlayer = null;
> +      });
> +    } else if (mSimpleExoPlayer != null) {
>        mSimpleExoPlayer.release();
>        mSimpleExoPlayer = null;
>      }
> ```

Solved the problem for me

**Comment by VSKut** [comment]
> I was able to fix it for myself with following patch:
> 
> ```
> diff --git a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
> index 672871d..4bf5385 100644
> --- a/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
> +++ b/node_modules/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java
> @@ -12,6 +12,8 @@ import android.view.Surface;
>  import androidx.annotation.NonNull;
>  import androidx.annotation.Nullable;
>  
> +import com.facebook.react.bridge.UiThreadUtil;
> +
>  import com.google.android.exoplayer2.C;
>  import com.google.android.exoplayer2.MediaItem;
>  import com.google.android.exoplayer2.PlaybackException;
> @@ -118,7 +120,12 @@ class SimpleExoPlayerData extends PlayerData
>    public synchronized void release() {
>      super.release();
>      stopUpdatingProgressIfNecessary();
> -    if (mSimpleExoPlayer != null) {
> +    if (!UiThreadUtil.isOnUiThread() && mSimpleExoPlayer != null) {
> +      UiThreadUtil.runOnUiThread(() -> {
> +        mSimpleExoPlayer.release();
> +        mSimpleExoPlayer = null;
> +      });
> +    } else if (mSimpleExoPlayer != null) {
>        mSimpleExoPlayer.release();
>        mSimpleExoPlayer = null;
>      }
> ```

This solved my problem.

**Comment by duogenesis** [comment]
Judging by this comment which was introduced in #16075 in March 2022, this issue's been known about and unresolved for over two years! 🙀

https://github.com/expo/expo/blob/cd39671d70ad59277af77f156920002a148ca4a3/packages/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java#L129-L135

**Comment by umrashrf** [comment]
In the meantime, is there an alternate safe way to play audio?

**Comment by voxlz** [comment]
I've encountered this too. Anyone tried the new expo-audio? Does that work?

**Comment by badhrin** [comment]
same error here....any fix in sight ? The new expo-video had other major issues, so dropped it for now. Is there any other reliable library to use to play video ?

**Comment by Ludevsoftware** [comment]
I receive this bug when launch an expo update. Any solution?

**Comment by singlecolor** [comment]
> Judging by this comment which was introduced in [#16075](https://github.com/expo/expo/pull/16075) in March 2022, this issue's been known about and unresolved for over two years! 🙀
> 
> [expo/packages/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java](https://github.com/expo/expo/blob/cd39671d70ad59277af77f156920002a148ca4a3/packages/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java#L129-L135)
> 
> Lines 129 to 135 in [cd39671](/expo/expo/commit/cd39671d70ad59277af77f156920002a148ca4a3)
> 
>  @Override 
>  protected double getCurrentPositionSeconds() { 
>    // TODO: Find a way to fix "IllegalStateException: SimpleExoPlayer is accessed on the wrong thread." 
>    // this is called synchronously on JS thread while SimpleExoPlayer is accessed on main thread. 
>    return -1.0; 
>    // return (double)mSimpleExoPlayer.getCurrentPosition() / 1000.0; 
>  }

I noticed this PR was merged but the owner mentioned it may not work with later versions. Was it resolved and has since stopped working for the latest versions of Expo? We experience this issue in Expo 51 on some Androids, but only inconsistently. 

Considering switching to expo-audio but there is not much documentation there yet last time I looked.

**Comment by Charnnarong** [comment]
I ran into this when I called `Audio.Sound.createAsync` inside a component used in FlatList's `renderItem`. While `renderItem` runs on the JS thread, creating sound objects hits native modules and can overload the UI thread, especially when FlatList renders items rapidly.

I fixed it by moving sound object creation and audio logic out of FlatList items and into the parent component. This solved the issue without patching the library.

**Comment by guihendias** [comment]
Still happening with expo 52

**Comment by lasfito** [comment]
getting the same error on expo 53

**Comment by conghai** [comment]
Same error for:
- expo: ~53.0.9 
- expo-audio: ~0.4.5

=> `This error only occurs on certain Android devices, not all.`
- Galaxy A7 (2018) (android 10)
- A79 5G (android 15)
- Galaxy A33 5G (android 14)
- Pixel 3a (android 12)
- Galaxy S24+ (android 15)
- Redmi Note 13 (android 15)
...

```
Fatal Exception: java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'mqt_v_js'
Expected thread: 'main'
See https://developer.android.com/guide/topics/media/issues/player-accessed-on-wrong-thread
       at androidx.media3.exoplayer.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2896)
       at androidx.media3.exoplayer.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:830)
       at androidx.media3.common.BasePlayer.pause(BasePlayer.java:119)
       at expo.modules.audio.AudioModule.audioFocusChangeListener$lambda$3(AudioModule.kt:66)
       at expo.modules.audio.AudioModule.$r8$lambda$aEI5geKxf9YtJMZhtvtrr4Tlii8()
       at expo.modules.audio.AudioModule$$ExternalSyntheticLambda0.onAudioFocusChange(D8$$SyntheticClass)
       at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2667)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.startNewBackgroundThread$lambda$1(MessageQueueThreadImpl.kt:175)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.$r8$lambda$ldnZnqelhYFctGaUKkOKYj5rxo4()
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by SergiOnGit** [comment]
The same here, this new audio module was meant to be better, right? Then why is it worse? Please fix this.

**Comment by evelant** [comment]
Just updated to expo53 and enabled the new architecture and now I see this crash a ton in Sentry from expo-audio.

**Comment by evelant** [comment]
Here's a patch for `expo-audio` you can use with patch-package that fixes the thread-safety crash

```patch
diff --git a/node_modules/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt b/node_modules/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt
index 13a3c24..f08f449 100644
--- a/node_modules/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt
+++ b/node_modules/expo-audio/android/src/main/java/expo/modules/audio/AudioModule.kt
@@ -63,7 +63,9 @@ class AudioModule : Module() {
       AudioManager.AUDIOFOCUS_LOSS_TRANSIENT -> {
         focusAcquired = false
         players.values.forEach {
-          it.player.pause()
+          runOnMain {
+            it.player.pause()
+          }
         }
       }
 
@@ -71,7 +73,9 @@ class AudioModule : Module() {
         focusAcquired = false
         if (interruptionMode == InterruptionMode.DUCK_OTHERS) {
           players.values.forEach {
-            it.player.volume /= 2f
+            runOnMain {
+               it.player.volume /= 2f
+            }
           }
         }
       }
@@ -79,7 +83,9 @@ class AudioModule : Module() {
       AudioManager.AUDIOFOCUS_GAIN -> {
         focusAcquired = true
         players.values.forEach {
-          it.setVolume(it.previousVolume)
+          runOnMain {
+            it.setVolume(it.previousVolume)
+          }
         }
       }
     }

```

**Comment by evelant** [comment]
Oh it looks like this already had a fix merged here: https://github.com/expo/expo/issues/36948

**Comment by SergiOnGit** [comment]
> Oh it looks like this already had a fix merged here: [#36948](https://github.com/expo/expo/issues/36948)

But is it fixed?

**Comment by vonovak** [comment]
Hello and thanks for reporting,
`expo-av` is depreacted, so I'll close this.
Thank you 🙂
