### ISSUE TITLE
Receiving the following error on running iOS Maestro tests on Expo Server: Error: Request for viewHierarchy failed, because of unknown reason, body: {"code":"internal","errorMessage":"Unable to perform work on main run loop, process main thread busy for 30.0s"} 29 ❌ Error: BlockingCoroutine is cancelling

### ISSUE THREAD

**Issue by smehr123** [expo/expo#31242]
### Minimal reproducible example

https://github.com/smehr123/Expo-iOS-error

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When we run my maestro tests locally on iOS Mobile Dev app, it works beautifully but when we run them on Expo server, they all fail with the following exception. Any help would be greatly appreciated.

**Please Note:** Android Maestro tests works fine on Expo server

**Device Used on Expo Server to run Maestro tests:**  iPhone 15, iOS 17.5

**Other Environment Details:**
Maestro Version: 1.37.9
OS Version: 14.5
OS Name: Mac OS X
Xcode Version: 15.4

**Expected Results:** Test should run smoothly on Expo server as they do locally

**Actual Results:** 

Failing with error -

Error: Request for viewHierarchy failed, because of unknown reason, body: {"code":"internal","errorMessage":"Unable to perform work on main run loop, process main thread busy for 30.0s"}
29
❌ Error: BlockingCoroutine is cancelling
30
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@1c6682dc
31
Caused by: UnknownFailure(errorResponse=Request for viewHierarchy failed, code: 500, body: {"code":"internal","errorMessage":"Unable to perform work on main run loop, process main thread busy for 30.0s"})
32
at xcuitest.XCTestDriverClient.handleExceptions(XCTestDriverClient.kt:310)
33
at xcuitest.XCTestDriverClient.processResponse(XCTestDriverClient.kt:258)
34
at xcuitest.XCTestDriverClient.executeJsonRequest(XCTestDriverClient.kt:240)
35
at xcuitest.XCTestDriverClient.viewHierarchy(XCTestDriverClient.kt:72)
36
at ios.xctest.XCTestIOSDevice$viewHierarchy$1.invoke(XCTestIOSDevice.kt:40)
37
at ios.xctest.XCTestIOSDevice$viewHierarchy$1.invoke(XCTestIOSDevice.kt:38)
38
at ios.xctest.XCTestIOSDevice.execute(XCTestIOSDevice.kt:227)
39
at ios.xctest.XCTestIOSDevice.viewHierarchy(XCTestIOSDevice.kt:38)
40
at ios.LocalIOSDevice.viewHierarchy(LocalIOSDevice.kt:47)
41
at maestro.drivers.IOSDriver.viewHierarchy(IOSDriver.kt:152)
42
at maestro.drivers.IOSDriver.access$viewHierarchy(IOSDriver.kt:41)
43
at maestro.drivers.IOSDriver$contentDescriptor$1.invoke(IOSDriver.kt:147)
44
at maestro.drivers.IOSDriver$contentDescriptor$1.invoke(IOSDriver.kt:147)
45
at maestro.drivers.IOSDriver.runDeviceCall(IOSDriver.kt:499)
46
at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:147)
47
at maestro.ViewHierarchy$Companion.from-8JJjmZI(ViewHierarchy.kt:29)
48
at maestro.utils.ScreenshotUtils$Companion.viewHierarchy-c1iYVAs(ScreenshotUtils.kt:99)
49
at maestro.utils.ScreenshotUtils$Companion.waitForAppToSettle-OpTFbEc(ScreenshotUtils.kt:58)
50
at maestro.drivers.IOSDriver.waitForAppToSettle-5RpGHs4(IOSDriver.kt:429)
51
at maestro.Maestro.waitForAppToSettle-5RpGHs4(Maestro.kt:474)
52
at maestro.Maestro.waitForAppToSettle-5RpGHs4$default(Maestro.kt:469)
53
at maestro.Maestro.screenshotBasedTap-hbl3e4M(Maestro.kt:314)
54
at maestro.Maestro.performTap-hbl3e4M(Maestro.kt:283)
55
at maestro.Maestro.tap-BUbHBYE(Maestro.kt:195)
56
at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:777)
57
at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:240)
58
at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:605)
59
at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:646)
60
at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:514)
61
at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:270)
62
at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:201)
63
at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:111)
64
at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:75)
65
at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:185)
66
at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:54)
67
at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:51)
68
at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:145)
69
at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:51)
70
at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:291)
71
at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:249)
72
at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:107)
73
at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
74
at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:249)
75
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
76
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
77
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
78
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
79
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
80
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
81
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
82
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
      npm: 10.4.0 - ~/.nvm/versions/node/v20.5.0/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/snehamehrotra/.rvm/gems/ruby-3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 30, 31, 32, 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.1 => 0.18.11 
      expo: ~51.0.28 => 51.0.28 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 7.8.3
    Expo Workflow: bare

### Expo Doctor Diagnostics

The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.28 - expected version: ~51.0.31
  expo-av@14.0.6 - expected version: ~14.0.7
  expo-camera@15.0.14 - expected version: ~15.0.15
  expo-dev-client@4.0.23 - expected version: ~4.0.25
  expo-notifications@0.28.15 - expected version: ~0.28.16
  expo-updates@0.25.22 - expected version: ~0.25.24
  jest-expo@51.0.3 - expected version: ~51.0.4
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

**Comment by smehr123** [comment]
Hi, is this error fixed here?
https://github.com/mobile-dev-inc/maestro/pull/2036
