### ISSUE TITLE
expo-mail-composer Intent Resolver Crash on Android 15

### ISSUE THREAD

**Issue by mchisolm** [expo/expo#31454]
### Minimal reproducible example

https://snack.expo.dev/NEgBuVFTBdXY3D_NerME-

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

When attempting to compose a share on Android 15 (currently in beta), I get an application crash with the following stack trace:
```
Key android.intent.extra.TEXT expected ArrayList<java.lang.CharSequence> but value was of a different type.  The default value <null> was returned.
Attempt to cast generated internal exception:
java.lang.ClassCastException: Cannot cast java.lang.String to java.util.ArrayList
	at java.lang.Class.cast(Class.java:4193)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:405)
	at android.os.BaseBundle.getValue(BaseBundle.java:382)
	at android.os.BaseBundle.getArrayList(BaseBundle.java:1527)
	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1570)
	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1325)
	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:9663)
	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:12844)
	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:12805)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2000)
	at android.app.Activity.startActivityForResult(Activity.java:5882)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5839)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:1)
	at expo.modules.mailcomposer.MailComposerModule$definition$lambda$7$$inlined$AsyncFunctionWithPromise$2.invoke(SourceFile:34)
	at expo.modules.mailcomposer.MailComposerModule$definition$lambda$7$$inlined$AsyncFunctionWithPromise$2.invoke(SourceFile:36)
	at expo.modules.kotlin.functions.AsyncFunctionWithPromiseComponent.callUserImplementation$expo_modules_core_release(SourceFile:2)
	at expo.modules.kotlin.functions.AsyncFunction$attachToJSObject$2$functionBody$1.invoke(SourceFile:2)
	at expo.modules.kotlin.functions.AsyncFunction$attachToJSObject$2$functionBody$1.invoke(SourceFile:1)
	at expo.modules.kotlin.functions.AsyncFunction$dispatchOnQueue$1.invokeSuspend(SourceFile:13)
	at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:12)
	at py.x0.run(SourceFile:129)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

### Environment

```
ram Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.28 => 51.0.32
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK     

Didn't find any issues with the project!
```

**Comment by khusmann** [comment]
@mchisolm I just upgraded to Android 15 ("stable" version released in Dec) and am getting this crash in expo even though the google issue tracker lists it as fixed... Did you ever get this working or find a workaround?

**Comment by SultanBadri** [comment]
Same here 🙁

**Comment by SultanBadri** [comment]
I just found [Linking](https://reactnative.dev/docs/linking?syntax=android&language=typescript), which is working well for sending emails.

**Comment by khusmann** [comment]
@SultanBadri Nice! Thanks for the tip, exactly what I needed. Even works with setting subject / body of messages: https://stackoverflow.com/questions/4782068/can-i-set-subject-content-of-email-using-mailto

**Comment by OlivierHartmann** [comment]
Hello,
End of June and still have this problem, especially now that my fun updated to android 15.
The google issue tracker is not moving on neither.

Must be something wrong in that lib as it's working good with this one to send the log files : https://github.com/BeTomorrow/react-native-file-logger/blob/f7207f4c8b1416c1da19a2d21b3b287b123a5637/android/src/main/java/com/betomorrow/rnfilelogger/FileLoggerModule.java#L186
I couldn't figure out the problem just by comparing the two source codes.

I can't use the mailto straight with Linking as it seems limited to 256 chars, no ?

Do you have any idea ?

Thank you,

**Comment by OlivierHartmann** [comment]
Hello,
I can add that I switched to use the https://github.com/tschoffelen/react-native-email-link that is working perfectly fine, with intents behind and not simple mailto link, and with my big messages.
So it really looks like there is a real bug in this expo lib.
Thank you,
