### ISSUE TITLE
Package is not running at http://192.168.1.103.80

### ISSUE THREAD

**Issue by suyash8991** [expo/expo#3147]
00:00
fs.js:1384
    throw error;
    ^

Error: watch /home/ssk/first/node_modules/asn1 ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at NodeWatcher.watchdir (/home/ssk/first/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/home/ssk/first/node_modules/sane/src/common.js:116:12)
    at emitTwo (events.js:126:13)
    at Walker.emit (events.js:214:7)
    at /home/ssk/first/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/ssk/first/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:135:15)

I cannot understand what is wrong with code.
The same code was running when i first ran it .
The second time i ran this error came.

**Comment by suyash8991** [comment]
I solved this by referring this solution
https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve/32600959#32600959
ran this command to avoid ENOSPC .
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
