### ISSUE TITLE
Expo app won't start the development server

### ISSUE THREAD

**Issue by Revaycolizer** [expo/expo#31481]
### Minimal reproducible example

https://github.com/Revaycolizer/app-delicery

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

Tried to initialize my app which i have been developing for two years but sadly i am not able to run it and i am getting this error 

FetchError: request to https://api.expo.dev/v2/sdks/51.0.0/native-modules failed, reason: 
FetchError: request to https://api.expo.dev/v2/sdks/51.0.0/native-modules failed, reason: 
    at ClientRequest.<anonymous> (/home/revaycolizer/projects/app-delivery/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:520:28)
    at emitErrorEvent (node:_http_client:103:11)
    at TLSSocket.socketErrorListener (node:_http_client:506:5)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.8 Linux Mint 21.3 (Virginia)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v22.6.0/bin/npm
    npmPackages:
      expo: ~51.0.28 => 51.0.29 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.3
      expo-cli: 6.3.12
    Expo Workflow: managed

### Expo Doctor Diagnostics

Detailed check results:

(node:39061) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
FetchError: request to https://api.expo.dev/v2/sdks/51.0.0/native-modules failed, reason: 
FetchError: request to https://api.expo.dev/v2/sdks/51.0.0/native-modules failed, reason: 
    at ClientRequest.<anonymous> (/home/revaycolizer/projects/app-delivery/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:520:28)
    at emitErrorEvent (node:_http_client:103:11)
    at TLSSocket.socketErrorListener (node:_http_client:506:5)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by sherkhan688** [comment]
i am also facing this type of problem

**Comment by habdams** [comment]
If you run into this issue: running `rm -rf .expo` will fix it.
Reference: https://docs.expo.dev/workflow/common-development-errors/

**Comment by marjorg** [comment]
We are experiencing the same issue in iOS Development Clients on Expo 52, seems not to be happening in 51.

The error also causes ` ERROR  TypeError: Cannot read property 'decode' of undefined, js engine: hermes
` originating from the `whatwg-url-without-unicode` package.

![image](https://github.com/user-attachments/assets/4acc9aa1-f084-4a3a-98b2-61d8adc0c8bc)

```
  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
      npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.19.4 => 0.19.4
      expo: 52.0.7 => 52.0.7
      expo-router: 4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
    npmGlobalPackages:
      eas-cli: 13.3.0
    Expo Workflow: managed
```


`pnpm why whatwg-url-without-unicode -r`

```
dependencies:
@dev-plugins/apollo-client 0.0.6
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
@dev-plugins/async-storage 0.0.3
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
@dev-plugins/react-navigation 0.0.6
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
@react-native-community/datetimepicker 8.2.0
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
@sentry/react-native 6.1.0
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
expo 52.0.7
└── whatwg-url-without-unicode 8.0.0-3
expo-application 6.0.1
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
expo-asset 11.0.1
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
expo-av 15.0.1
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
expo-clipboard 7.0.0
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3

devDependencies:
jest-expo 52.0.2
└─┬ expo 52.0.7 peer
  └── whatwg-url-without-unicode 8.0.0-3
```

**Comment by marjorg** [comment]
After some more debugging I got Expo 52 working with the previously posted setup by removing the `EXPO_USE_FAST_RESOLVER` flag we were using.

**Comment by nguyenvanphituoc** [comment]
this same issues for starter projects in firebase studio, just remove `EXPO_USE_FAST_RESOLVER` in env configuration in file .nix

**Comment by pfcodes** [comment]
For me this issue happens when using `useAuthRequest`'s `promptAsync`
