### ISSUE TITLE
PluginError when using plugins with parameters

### ISSUE THREAD

**Issue by teisen** [expo/expo#31601]
### Minimal reproducible example

https://github.com/teisen/expolocationtest/blob/main/app.json

### What platform(s) does this occur on?

Android, iOS, Web

### Where did you reproduce the issue?

in a development build

### Summary

Hello. I am still new to Expo, but i was trying to add location to my app and run into the below problem. I am not able to add plugins that need a configuration in the app.json.
Besides the issue with the location plugin  also noticed that adding firebase plugiuns that need configuration cauised the same problem, so i assume the problem is not specific to the location plugin. 

Steps to reproduce: 
Created new, empty expo app with: npx install-expo-modules@latest

Install expo-location: npx expo install expo-location

Configuration in app.json/app.config.js:
    "plugins": [
      "expo-router",
      "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow $(PRODUCT_NAME) to use your location."
        }
    ],

Error:
C:\expolocationtest>npx expo start
Starting project at C:\expolocationtest
PluginError: Plugin is an unexpected type: object
PluginError: Plugin is an unexpected type: object
    at withStaticPlugin (C:\expolocationtest\node_modules\@expo\config-plugins\build\plugins\withStaticPlugin.js:130:11)
    at C:\expolocationtest\node_modules\@expo\config-plugins\build\plugins\withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (C:\expolocationtest\node_modules\@expo\config-plugins\build\plugins\withPlugins.js:30:18)
    at withConfigPlugins (C:\expolocationtest\node_modules\@expo\config\build\plugins\withConfigPlugins.js:35:47)
    at fillAndReturnConfig (C:\expolocationtest\node_modules\@expo\config\build\Config.js:229:78)
    at getConfig (C:\expolocationtest\node_modules\@expo\config\build\Config.js:286:10)
    at startAsync (C:\expolocationtest\node_modules\@expo\cli\build\src\start\startAsync.js:131:70)
    at expoStart (C:\expolocationtest\node_modules\@expo\cli\build\src\start\index.js:138:12)

Thanks!

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.19072.14.2412.12360217
    npmPackages:
      expo: ~51.0.28 => 51.0.32
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
PluginError: Plugin is an unexpected type: object
    at withStaticPlugin (C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:425597)
    at C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:422939
    at Array.reduce (<anonymous>)
    at withPlugins (C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:422884)
    at withConfigPlugins (C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:464021)
    at fillAndReturnConfig (C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:448476)
    at getConfig (C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:449293)
    at actionAsync (C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:567154)
    at async run (C:\Users\teise\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js:59:568832) {
  isPluginError: true,
  code: 'INVALID_PLUGIN_TYPE',
  cause: undefined
}

Node.js v20.17.0
```

**Comment by vonovak** [comment]
Hello and thanks for asking,
Please look carefully at https://docs.expo.dev/versions/latest/sdk/location/#example-appjson-with-config-plugin

you need to wrap the plugin in `[ ... ]` in order for the parameters to be passed correctly.
Thank you 🙂
