### ISSUE TITLE
[expo-location] checkLocationSettings in resolveUserSettingsForRequest failing

### ISSUE THREAD

**Issue by mlecoq** [expo/expo#31793]
### Minimal reproducible example

todo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

This issue https://github.com/expo/expo/issues/24729 has been closed and relative one https://issuetracker.google.com/issues/303285489 also whereas it still occurs few times in production 

users who encounter this issue are on android 12, I don't have more details for the moment

Here is the stack trace I have (from firebase)
```
Fatal Exception: java.lang.ClassCastException: com.google.android.gms.common.api.ApiException cannot be cast to com.google.android.gms.common.api.ResolvableApiException
       at expo.modules.location.LocationModule.lambda$resolveUserSettingsForRequest$16$expo-modules-location-LocationModule(LocationModule.java:668)
       at expo.modules.location.LocationModule$$ExternalSyntheticLambda12.onFailure(:4)
       at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

I open a new issue because last one may think it is resolved 

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.1 - ~/.local/state/fnm_multishells/28530_1727795184220/bin/node
      Yarn: 1.22.22 - ~/.local/state/fnm_multishells/28530_1727795184220/bin/yarn
      npm: 9.8.1 - ~/.local/state/fnm_multishells/28530_1727795184220/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.6 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.5.1
    Expo Workflow: bare
```
```


### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for issues with metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/metro-config@~0.18.11
Found invalid:
  @expo/metro-config@0.18.8
  (for more info, run: npm why @expo/metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

The following packages should be updated for best compatibility with the installed expo version:
  @expo/vector-icons@14.0.2 - expected version: ^14.0.3
  expo@51.0.18 - expected version: ~51.0.35
  expo-build-properties@0.12.3 - expected version: ~0.12.5
  expo-font@12.0.7 - expected version: ~12.0.10
  expo-splash-screen@0.27.5 - expected version: ~0.27.6
  expo-updates@0.25.18 - expected version: ~0.25.25
  react-native-safe-area-context@4.10.1 - expected version: 4.10.5
  expo-dev-client@4.0.19 - expected version: ~4.0.27
  jest-expo@51.0.3 - expected version: ~51.0.4
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```
```

**Comment by BrandonYuen** [comment]
We also have this error (fatal crash) occurring for a few select users. Seems like it's related to Samsung devices but not sure. I am unable to reproduce this with our own devices.
![Screenshot 2024-11-01 at 12 22 58](https://github.com/user-attachments/assets/74153798-2395-4fe8-bc01-b2a3c8b70b65)

**Comment by aleksnied** [comment]
This is happening to us too, it seems to be exclusive to users in South America for us, European/US users are not seeing this issue in our user base. Not exclusive to Samsung devices, seeing it on Motorolas too.

**Comment by aleksnied** [comment]
<img width="478" alt="Image" src="https://github.com/user-attachments/assets/8bc46f9e-1971-43c2-be43-86e5e57d9208" />

Hi, any update on this? We keep getting this issue on latest Android. We also checked that play services version was updated to latest.

**Comment by aleksnied** [comment]
Looks like the expo code is expecting to get a ResolvableApiException and failing on the cast that is not caught by the catch:

```
        try {
          val resolvable = e as ResolvableApiException
          mUIManager.registerActivityEventListener(this@LocationModule)
          resolvable.startResolutionForResult(appContext.throwingActivity, CHECK_SETTINGS_REQUEST_CODE)
        } catch (e: SendIntentException) {
          // Ignore the error.
          executePendingRequests(Activity.RESULT_CANCELED)
        }
```

I've just ordered a moto g13 to try and reproduce this. Hopefully it's not carrier specific. I will attempt to patch this crash by doing:

```
        try {
          val resolvable = e as? ResolvableApiException
          if (resolvable != null) {
            mUIManager.registerActivityEventListener(this@LocationModule)
            resolvable.startResolutionForResult(appContext.throwingActivity, CHECK_SETTINGS_REQUEST_CODE)
          } else {
            executePendingRequests(Activity.RESULT_CANCELED)
          }
        } catch (e: SendIntentException) {
          // Ignore the error.
          executePendingRequests(Activity.RESULT_CANCELED)
        }
```

**Comment by aleksnied** [comment]
Hi, I can confirm that above patch has prevented the crash. This crash was being caused by restricted IT set ups on phones. Some unexpected class of error must be being raised when expo-location is blocked from accessing location. The patch above has prevented the crash but location does not get resolved (which for us is acceptable as that part is because of customer's company's IT set up)

**Comment by mlecoq** [comment]
@aleksnied  The error is currently misleading so I think that you should propose a PR for this, thanks for your analysis
