### ISSUE TITLE
Expo-sensors not working on the web platform (any device)

### ISSUE THREAD

**Issue by mwojcik0** [expo/expo#31888]
### Minimal reproducible example

https://github.com/mwojcik0/expo-sensors-example

### What platform(s) does this occur on?

Android, iOS, Web

### Where did you reproduce the issue?

in a development build, in Expo Go, on web

### Summary

Hi, so the problem is when I create a new expo project, which doesn't have any additional npm packages other than the base ones and expo-sensors, the example of an Accelerometer implementation doesn't work on any of my devices on web. I have to mention that all of them feature sensors such as gyroscope and accelerometer, even my laptop, I used Accelerometer.isAvailableAsync() to check, and It always returns true, so that's not where the issue is. Also, If I launch the dev app in a mobile version the sensors are supported on the plugged in device.

App crashes and there are console logs like:

> C:\Users\PC-3\Docume…\DeviceSensor.js:14 Uncaught TypeError: this._nativeModule.addListener is not a function
    at AccelerometerSensor.addListener (C:\Users\PC-3\Docume…viceSensor.js:14:35)
    at AccelerometerSensor.addListener (C:\Users\PC-3\Docume…elerometer.js:30:22)
    at _subscribe (C:\Users\PC-3\Docume…ample\App.tsx:18:35)
    at C:\Users\PC-3\Docume…xample\App.tsx:27:5
    at commitHookEffectListMount (C:\Users\PC-3\Docume…lopment.js:23150:26)
    at commitPassiveMountOnFiber (C:\Users\PC-3\Docume…lopment.js:24931:11)
    at commitPassiveMountEffects_complete (C:\Users\PC-3\Docume…elopment.js:24891:9)
    at commitPassiveMountEffects_begin (C:\Users\PC-3\Docume…elopment.js:24878:7)
    at commitPassiveMountEffects (C:\Users\PC-3\Docume…elopment.js:24866:3)
    at flushPassiveEffectsImpl (C:\Users\PC-3\Docume…elopment.js:27039:3)

> C:\Users\PC-3\Docume…evelopment.js:18687 The above error occurred in the <App> component: at App (http://localhost:8082/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&de…=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:49903:39)
    at withDevTools(App)
    at AppContainer (http://localhost:8082/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&de…t=false&lazy=true&transform.engine=hermes&transform.routerRoot=app:29820:7)

> Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
C:\Users\PC-3\Docume…\DeviceSensor.js:14 Uncaught TypeError: this._nativeModule.addListener is not a function
    at AccelerometerSensor.addListener (C:\Users\PC-3\Docume…viceSensor.js:14:35)
    at AccelerometerSensor.addListener (C:\Users\PC-3\Docume…elerometer.js:30:22)
    at _subscribe (C:\Users\PC-3\Docume…ample\App.tsx:18:35)
    at C:\Users\PC-3\Docume…xample\App.tsx:27:5
    at commitHookEffectListMount (C:\Users\PC-3\Docume…lopment.js:23150:26)
    at commitPassiveMountOnFiber (C:\Users\PC-3\Docume…lopment.js:24931:11)
    at commitPassiveMountEffects_complete (C:\Users\PC-3\Docume…elopment.js:24891:9)
    at commitPassiveMountEffects_begin (C:\Users\PC-3\Docume…elopment.js:24878:7)
    at commitPassiveMountEffects (C:\Users\PC-3\Docume…elopment.js:24866:3)
    at flushPassiveEffectsImpl (C:\Users\PC-3\Docume…elopment.js:27039:3)

If you have any advice please let me know, I've searched through the internet for fixes and any of the solutions were helpful.

### Environment

```text
PS C:\Users\PC-3\Documents\GitHub\expo-sensors-example> npx expo-env-info                                                                                  

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^51.0.36 => 51.0.36 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: ^0.74.5 => 0.74.5 
      react-native-web: ^0.19.12 => 0.19.12 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
PS C:\Users\PC-3\Desktop\todo-expo> npx expo-doctor

✔️ Check Expo config for common issues
✔️ Check package.json for common issues
✔️ Check native tooling versions
✔️ Check if the project meets version requirements for submission to app stores
✔️ Check dependencies for packages that should not be installed directly
✔️ Check for common project setup issues
✔️ Check for app config fields that may not be synced in a non-CNG project
✔️ Check npm/ yarn versions
✔️ Check for issues with metro config
✔️ Check Expo config (app.json/ app.config.js) schema
✔️ Check that native modules do not use incompatible support packages
✔️ Check for legacy global CLI installed locally
✔️ Check that packages match versions required by installed Expo SDK
✔️ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by mwojcik0** [comment]
Could I recieve any help in regards to that issue?

**Comment by edkimmel** [comment]
This broke as of Expo 51.

The mock native module for web never implemented addListener
https://github.com/expo/expo/blob/main/packages/expo-sensors/src/ExponentAccelerometer.web.ts

In Expo 50, DeviceSensor added the listener to a local EventEmitter
https://github.com/expo/expo/blob/sdk-50/packages/expo-sensors/src/DeviceSensor.ts#L35

In Expo 51, it tried to add the listener directly to the native module, which again does not implement it on web
https://github.com/expo/expo/blob/sdk-51/packages/expo-sensors/src/DeviceSensor.ts#L30
