### ISSUE TITLE
Android ClassNotFoundException

### ISSUE THREAD

**Issue by Geor23** [expo/expo#319]
Any idea why this might happen? 
Got about 30 crash reports for this, only on Android. 

Full report: 

--
```
Non-fatal Exception: java.lang.ClassNotFoundException: abi17_0_0.com.facebook.soloader.SoLoader
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:400)
       at java.lang.Class.forName(Class.java:326)
       at host.exp.exponent.RNObject.loadVersion(RNObject.java:60)
       at host.exp.exponent.experience.ExperienceActivity.soloaderInit(ExperienceActivity.java:168)
       at host.exp.exponent.experience.ExperienceActivity.onResume(ExperienceActivity.java:156)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
       at android.app.Activity.performResume(Activity.java:7019)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by java.lang.ClassNotFoundException: Didn't find class "abi17_0_0.com.facebook.soloader.SoLoader" on path: DexPathList[[zip file "/data/app/**/base.apk"],nativeLibraryDirectories=[/data/app/**/lib/arm, /data/app/**/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:400)
       at java.lang.Class.forName(Class.java:326)
       at host.exp.exponent.RNObject.loadVersion(RNObject.java:60)
       at host.exp.exponent.experience.ExperienceActivity.soloaderInit(ExperienceActivity.java:168)
       at host.exp.exponent.experience.ExperienceActivity.onResume(ExperienceActivity.java:156)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
       at android.app.Activity.performResume(Activity.java:7019)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

#0. Crashed: main: 0 0 0x0000000000000000
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:400)
       at java.lang.Class.forName(Class.java:326)
       at host.exp.exponent.RNObject.loadVersion(RNObject.java:60)
       at host.exp.exponent.experience.ExperienceActivity.soloaderInit(ExperienceActivity.java:168)
       at host.exp.exponent.experience.ExperienceActivity.onResume(ExperienceActivity.java:156)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
       at android.app.Activity.performResume(Activity.java:7019)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by ide** [comment]
This is very strange since it's from when React Native first loads. Do you see any other patterns, such as whether this is happening on a certain manufacturer's phone or specific version of Android?

**Comment by jesseruder** [comment]
Can you send the entire crash report? As it says at the top, this is a non-fatal exception, so there is something else happening

**Comment by Geor23** [comment]
@ide Don't think there's a pattern in devices, it appeared on all Android phones/tablets we tested on. However, it does seem to happen when zooming in and out of the maps
@jesseruder that's literally all I get from Crashlytics

**Comment by dikaiosune** [comment]
Hi! If this was happening when interacting with maps then I think we'll instead track the need to update the maps library we ship -- hopefully that'll clear up this exception. If you have a concrete reproduction we can try, please post back and I'll happily reopen. Thanks!

**Comment by anjalsan** [comment]
I Got the same issue on android fabric console, I used the app only some minutes in one device. it happened 30 times. it's not crash, the app is working properly. not distracting user experience . it's a non fatals. my error report

`Non-fatal Exception: java.lang.ClassNotFoundException: abi23_0_0.com.facebook.soloader.SoLoader
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:400)
       at java.lang.Class.forName(Class.java:326)
       at host.exp.exponent.RNObject.loadVersion(RNObject.java:60)
       at host.exp.exponent.experience.ExperienceActivity.soloaderInit(ExperienceActivity.java:184)
       at host.exp.exponent.experience.ExperienceActivity.loadExperience(ExperienceActivity.java:306)
       at host.exp.exponent.experience.ExperienceActivity.loadExperience(ExperienceActivity.java:256)
       at host.exp.exponent.experience.ExperienceActivity.onCreate(ExperienceActivity.java:157)
       at host.exp.exponent.experience.ShellAppActivity.onCreate(ShellAppActivity.java:20)
       at android.app.Activity.performCreate(Activity.java:6847)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by java.lang.ClassNotFoundException: Didn't find class "abi23_0_0.com.facebook.soloader.SoLoader" on path: DexPathList[[zip file "/data/app/com.poletalks.socialwall-1/base.apk"],nativeLibraryDirectories=[/data/app/com.poletalks.socialwall-1/lib/arm, /data/app/com.poletalks.socialwall-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:400)
       at java.lang.Class.forName(Class.java:326)
       at host.exp.exponent.RNObject.loadVersion(RNObject.java:60)
       at host.exp.exponent.experience.ExperienceActivity.soloaderInit(ExperienceActivity.java:184)
       at host.exp.exponent.experience.ExperienceActivity.loadExperience(ExperienceActivity.java:306)
       at host.exp.exponent.experience.ExperienceActivity.loadExperience(ExperienceActivity.java:256)
       at host.exp.exponent.experience.ExperienceActivity.onCreate(ExperienceActivity.java:157)
       at host.exp.exponent.experience.ShellAppActivity.onCreate(ShellAppActivity.java:20)
       at android.app.Activity.performCreate(Activity.java:6847)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by lucasboleli** [comment]
Same here:

07-28 17:42:08.968 13720 13720 E i       : java.lang.ClassNotFoundException: abi28_0_0.com.facebook.soloader.SoLoader
07-28 17:42:08.969 13720 13720 E i       : Runtime exception in RNObject when calling method init: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Method[] java.lang.Class.getMethods()' on a null object reference
07-28 17:42:08.972  1435  1521 I ActivityManager: Displayed com.tecprime.queixocaido/host.exp.exponent.experience.ShellAppActivity: +260ms
07-28 17:42:08.961   528   528 W Binder:477_1: type=1400 audit(0.0:4598): avc: denied { search } for name="479" dev="proc" ino=17446 scontext=u:r:surfaceflinger:s0 tcontext=u:r:mm-pp-daemon:s0 tclass=dir permissive=0
07-28 17:42:08.986 13720 13720 W a       : Could not find listener for key: readyForBundle
07-28 17:42:08.988 13720 13720 E d       : java.lang.RuntimeException: A TaskDescription's primary color should be opaque
07-28 17:42:08.981   530   530 W Binder:477_2: type=1400 audit(0.0:4599): avc: denied { search } for name="479" dev="proc" ino=17446 scontext=u:r:surfaceflinger:s0 tcontext=u:r:mm-pp-daemon:s0 tclass=dir permissive=0
07-28 17:42:08.992 13720 13720 D ReactNative: ReactInstanceManager.ctor()
07-28 17:42:09.003 13720 13720 D ReactNative: ReactInstanceManager.createReactContextInBackground()
07-28 17:42:09.003 13720 13720 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
07-28 17:42:09.003 13720 13720 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
07-28 17:42:09.003 13720 13720 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
07-28 17:42:09.003 13720 13720 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
07-28 17:42:09.005 13720 15886 D ReactNative: ReactInstanceManager.createReactContext()
07-28 17:42:09.008  1435  4729 V RestrictedPackageService: filterBroadcastReceiver for com.google.android.gms.gcm.ACTION_SCHEDULE
07-28 17:42:09.001  6828  6828 W Binder:477_5: type=1400 audit(0.0:4600): avc: denied { search } for name="479" dev="proc" ino=17446 scontext=u:r:surfaceflinger:s0 tcontext=u:r:mm-pp-daemon:s0 tclass=dir permissive=0
07-28 17:42:09.022 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTGroupViewManager
07-28 17:42:09.023 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTGroupShadowNode
07-28 17:42:09.024 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTShapeViewManager
07-28 17:42:09.025 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTShapeShadowNode
07-28 17:42:09.027 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTTextViewManager
07-28 17:42:09.028 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTTextShadowNode
07-28 17:42:09.029 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.checkbox.ReactCheckBoxManager
07-28 17:42:09.030  1435  4098 V RestrictedPackageService: filterBroadcastReceiver for com.google.android.gms.gcm.ACTION_SCHEDULE
07-28 17:42:09.037 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.uimanager.LayoutShadowNode
07-28 17:42:09.043 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.picker.ReactDialogPickerManager
07-28 17:42:09.044 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.drawer.ReactDrawerLayoutManager
07-28 17:42:09.045 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.picker.ReactDropdownPickerManager
07-28 17:42:09.046 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
07-28 17:42:09.049 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
07-28 17:42:09.050 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.progressbar.ReactProgressBarViewManager
07-28 17:42:09.051 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.progressbar.ProgressBarShadowNode
07-28 17:42:09.052 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.scroll.ReactScrollViewManager
07-28 17:42:09.055 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.slider.ReactSliderManager
07-28 17:42:09.056 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
07-28 17:42:09.057 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.switchview.ReactSwitchManager
07-28 17:42:09.058 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
07-28 17:42:09.059 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.toolbar.ReactToolbarManager
07-28 17:42:09.061 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.webview.ReactWebViewManager
07-28 17:42:09.063 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
07-28 17:42:09.065 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTSurfaceViewManager
07-28 17:42:09.065 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.art.ARTSurfaceViewShadowNode
07-28 17:42:09.066 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
07-28 17:42:09.066 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
07-28 17:42:09.067 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.image.ReactImageManager
07-28 17:42:09.070 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.modal.ReactModalHostManager
07-28 17:42:09.071 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.modal.ModalHostShadowNode
07-28 17:42:09.072 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.ReactRawTextManager
07-28 17:42:09.072 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.ReactRawTextShadowNode
07-28 17:42:09.073 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.textinput.ReactTextInputManager
07-28 17:42:09.079 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.textinput.ReactTextInputShadowNode
07-28 17:42:09.083 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.ReactTextViewManager
07-28 17:42:09.086 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.ReactTextShadowNode
07-28 17:42:09.087 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.view.ReactViewManager
07-28 17:42:09.108 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.viewpager.ReactViewPagerManager
07-28 17:42:09.109 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.ReactVirtualTextViewManager
07-28 17:42:09.110  1435  4099 V RestrictedPackageService: filterBroadcastReceiver for com.google.android.gms.gcm.ACTION_SCHEDULE
07-28 17:42:09.110 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.com.facebook.react.views.text.ReactVirtualTextShadowNode
07-28 17:42:09.111 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.admob.RNAdMobBannerViewManager
07-28 17:42:09.112 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.admob.RNPublisherBannerViewManager
07-28 17:42:09.113 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.LinearGradientManager
07-28 17:42:09.115 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.av.video.VideoViewManager
07-28 17:42:09.116 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.camera.CameraViewManager
07-28 17:42:09.119 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.gl.GLViewManager
07-28 17:42:09.119 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.fbads.NativeAdViewManager
07-28 17:42:09.120 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.barcodescanner.BarCodeScannerViewManager
07-28 17:42:09.121 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.fbads.BannerViewManager
07-28 17:42:09.122 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.RenderableViewManager
07-28 17:42:09.123 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.GroupShadowNode
07-28 17:42:09.127 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.PathShadowNode
07-28 17:42:09.128 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.CircleShadowNode
07-28 17:42:09.129 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.EllipseShadowNode
07-28 17:42:09.131 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.LineShadowNode
07-28 17:42:09.132 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.RectShadowNode
07-28 17:42:09.134 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.TextShadowNode
07-28 17:42:09.134  1435  1960 V RestrictedPackageService: filterBroadcastReceiver for com.google.android.gms.gcm.ACTION_SCHEDULE
07-28 17:42:09.136 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.TSpanShadowNode
07-28 17:42:09.137 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.TextPathShadowNode
07-28 17:42:09.138 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.ImageShadowNode
07-28 17:42:09.140 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.ClipPathShadowNode
07-28 17:42:09.141 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.DefsShadowNode
07-28 17:42:09.142 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.UseShadowNode
07-28 17:42:09.143 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.SymbolShadowNode
07-28 17:42:09.146 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.LinearGradientShadowNode
07-28 17:42:09.148 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.RadialGradientShadowNode
07-28 17:42:09.151 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.SvgViewManager
07-28 17:42:09.151 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.svg.SvgViewShadowNode
07-28 17:42:09.153 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapCalloutManager
07-28 17:42:09.154 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager
07-28 17:42:09.157 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapPolylineManager
07-28 17:42:09.159 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapPolygonManager
07-28 17:42:09.161 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapCircleManager
07-28 17:42:09.163 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapManager
07-28 17:42:09.168 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapLiteManager
07-28 17:42:09.169 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapUrlTileManager
07-28 17:42:09.170 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapLocalTileManager
07-28 17:42:09.171 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.maps.AirMapOverlayManager
07-28 17:42:09.172 13720 15886 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi28_0_0.host.exp.exponent.modules.api.components.lottie.LottieAnimationViewManager
07-28 17:42:09.174  1435  1521 I WindowManager: Destroying surface Surface(name=Starting com.tecprime.queixocaido) called by com.android.server.wm.WindowStateAnimator.destroySurface:2047 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2091 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704
