### ISSUE TITLE
Local eas build fails with error: "Cannot find module '@expo/config-plugins'"

### ISSUE THREAD

**Issue by paule89123** [expo/expo#31985]
### Minimal reproducible example

https://github.com/paule89123/eas-build-issue

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When I run `npx eas build --profile development --platform ios --local`, I get this error:

```
Error: Cannot find module '@expo/config-plugins'
Require stack:

/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/config/build/plugins/withConfigPlugins.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/config/build/Config.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/config/build/index.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/utils/appConfig.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/context.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/builders/android.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/builders/index.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/index.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/eas-cli-local-build-plugin/dist/build.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/eas-cli-local-build-plugin/dist/main.js
/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/eas-cli-local-build-plugin/bin/run
at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
at Module._load (node:internal/modules/cjs/loader:981:27)
at Module.require (node:internal/modules/cjs/loader:1231:19)
at require (node:internal/modules/helpers:177:18)
at _configPlugins (/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/config/build/plugins/withConfigPlugins.js:8:16)
at withConfigPlugins (/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/config/build/plugins/withConfigPlugins.js:35:18)
at fillAndReturnConfig (/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/config/build/Config.js:229:78)
at getConfig (/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/config/build/Config.js:286:10)
at readAppConfig (/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/utils/appConfig.js:35:39)
at get appConfig [as appConfig] (/Users/paule/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/context.js:93:61)
Build failed
Unknown error. See logs of the Read app config build phase for more information.
npx exited with non-zero code: 1
```
I'm having this issue with all my projects, including brand new ones created today with create-expo-app@latest.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 10.8.3 - ~/.nvm/versions/node/v18.20.4/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.37 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.5.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by paule89123** [comment]
I managed to fix it by running `npx clear-npx-cache`.
