### ISSUE TITLE
npx create-expo-module <projName> throws up error

### ISSUE THREAD

**Issue by nagubadianil** [expo/expo#32138]
### Summary

 Downloaded module template from npm
✔ Created the module from template files
✖ Installing module dependencies
Error: npm install exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Dev\ReactNative\expo-settings\node_modules\@expo\spawn-async\build\spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at cp.emit (C:\Dev\ReactNative\expo-settings\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (C:\Dev\ReactNative\expo-settings\node_modules\@expo\spawn-async\build\spawnAsync.js:7:23)
    at installDependencies (C:\Dev\ReactNative\expo-settings\node_modules\create-expo-module\build\packageManager.js:9:37)
    at C:\Dev\ReactNative\expo-settings\node_modules\create-expo-module\build\create-expo-module.js:86:60
    at newStep (C:\Dev\ReactNative\expo-settings\node_modules\create-expo-module\build\utils.js:21:22)
    at Command.main (C:\Dev\ReactNative\expo-settings\node_modules\create-expo-module\build\create-expo-module.js:85:35) {
  pid: 23508,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null
}

### SDK Version

51

### Environment

```text
C:\Dev\ReactNative>npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20240728.093121.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        Android NDK: 27.1.12297006
    IDEs:
      Android Studio: AI-242.23339.11.2421.12483815
```

### Minimal reproducible example

Just the command: npx create-expo-module expo-settings 
C:\Dev\ReactNative>npm ls -g --depth=0
C:\Users\nagub\AppData\Roaming\npm
+-- eas-cli@12.5.3
+-- expo-cli@6.3.12
+-- npm@10.9.0
+-- react-native-cli@2.0.1
`-- yarn@1.22.22

**Comment by PierreCapo** [comment]
Same issue for me on a MacOS computer.

**Comment by nagubadianil** [comment]
Hey Pierre,

You can make a module within an expo bare project.  Use the npx
***@***.*** --local to create a local module in the project
and then use it.
See the steps the below:

The Steps 2 and 3, below are from here:
https://docs.expo.dev/modules/third-party-library/

   1.

   npx create-expo-app —template


   -

   chosen bare template (last one)


   2.

   Followed steps from here :
   https://docs.expo.dev/modules/get-started/#add-a-new-module-to-an-existing-application



   1.

   Step 1: Create the local Expo module

npx ***@***.*** --local

   -

   named the module expo-settings and module name ExpoSettings


   2.

   Used the below command in the app created in step 1:

npx expo prebuild --clean

   3.

   Then followed Step 2: Use the local module
   4.

   Then followed Step 3: Edit the module
   5.

   Tested it
