### ISSUE TITLE
Expo server crashes often.

### ISSUE THREAD

**Issue by EltonZhong** [expo/expo#3227]
ECONNRESET

![image](https://user-images.githubusercontent.com/20570738/51232472-cbbb7580-19a1-11e9-83f2-390c8adb4fb9.png)
![image](https://user-images.githubusercontent.com/20570738/51232480-d7a73780-19a1-11e9-80c1-78c9fe77310d.png)
I served the app with the command: `expo start`
But it keeps crashing again and again. And I can not get any information from the message.

**Comment by tcdavis** [comment]
Stack traces that start with ABIXX and ABIYY are very often bad state being cached by the bundler.
Try deleting everything in node_modules and reinstalling, calling `watchman watch-del-all`, and running with `expo start --clear`

**Comment by EltonZhong** [comment]
> Stack traces that start with ABIXX and ABIYY are very often bad state being cached by the bundler.
> Try deleting everything in node_modules and reinstalling, calling `watchman watch-del-all`, and running with `expo start --clear`

OK I'll try, thanks

**Comment by EltonZhong** [comment]
> > Stack traces that start with ABIXX and ABIYY are very often bad state being cached by the bundler.
> > Try deleting everything in node_modules and reinstalling, calling `watchman watch-del-all`, and running with `expo start --clear`
> 
> OK I'll try, thanks

Not  working, expo still crash sometimes, given the only message:
![image](https://user-images.githubusercontent.com/20570738/51301122-0a683300-1a69-11e9-9f05-31b7f809706b.png)

**Comment by cklinx** [comment]
Same here.

**Comment by brentvatne** [comment]
what operating system are you folks using? please notice that there is an issue template that you need to follow in order for us to understand the context surrounding your issue. i attached it here again for you to fill it out. we can't help until you do it.

```
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!



### Environment

<!-- In your terminal run `expo diagnostics` and paste the output here. -->

<!-- Please also let us know about your app's target (iOS, Android, Client, Standalone, ExpoKit) -->

### Steps to Reproduce

<!--
  How would you describe your issue to someone who doesn’t know you or your project?
  Try to write a sequence of steps that anybody can repeat to see the issue.
  Be specific! If the bug cannot be reproduced, your issue may be closed.
-->

(Write your steps here:)

1.
2.
3.

### Expected Behavior

<!--
  How did you expect your project to behave?
  It’s fine if you’re not sure your understanding is correct.
  Just write down what you thought would happen.
-->

(Write what you thought would happen.)

### Actual Behavior

<!--
  Did something go wrong?
  Is something broken, or not behaving as you expected?
  Describe this section in detail, and attach screenshots if possible.
  Don't just say "it doesn't work"!
-->

(Write what happened. Add screenshots!)

### Reproducible Demo

<!--
  Please share a project that reproduces the issue.
  There are two ways to do it:

    * Create a new app using https://snack.expo.io/ and try to reproduce the issue in it.
      This is useful if you roughly know where the problem is, or can’t share the real code.

    * Or, copy your app and remove things until you’re left with the minimal reproducible demo.
      This is useful for finding the root cause. You may then optionally create a Snack.

  This is a good guide to creating bug demos: https://stackoverflow.com/help/mcve
  Once you’re done, copy and paste the link to the Snack or a public GitHub repository below:
-->

(Paste the link to an example project and exact instructions to reproduce the issue.)

<!--
  What happens if you skip this step?

  Someone will read your bug report, and maybe will be able to help you,
  but it’s unlikely that it will get much attention from the team. Eventually,
  the issue will likely get closed in favor of issues that have reproducible demos.

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->
```

**Comment by EltonZhong** [comment]
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      npm: 6.5.0-next.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
    npmPackages:
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.14



### Steps to Reproduce

1. In my server, run expo start
2. Open the app in ios simulators, ios real device, Android devices, with development mode.
3.  Accidentally, the error occurs, and devices cannot load js bundle from expo server.

### Expected Behavior

The expo server should serve js bundle stably

### Actual Behavior

 expo crashes sometimes, given the only message:
![image](https://user-images.githubusercontent.com/20570738/51301122-0a683300-1a69-11e9-9f05-31b7f809706b.png)

When I restart it, everything goes well then, and it still crashes after some time.
Haven't got a clue.


### Reproducible Demo
If you really need a demo project, please leave comments.

Thank you.

**Comment by pwfcurry** [comment]
I've had this issue before, consistently -- I think it might have been something to do with watchman. I restarted my laptop and it went away...

**Comment by EltonZhong** [comment]
> I've had this issue before, consistently -- I think it might have been something to do with watchman. I restarted my laptop and it went away...

While, even if I change to prod mode, it still crashes,

Actually what I'm doing is to make expo server serve my app stable, for continuous integration use. It's a shame that if expo-server is only for development use :(

**Comment by EltonZhong** [comment]
Hi, @brentvatne, I got something new!
![image](https://user-images.githubusercontent.com/20570738/51955010-3d54f280-247d-11e9-8571-8dd3c87e8c96.png)
I modified node_modules/react-native/local-cli/cli.js, 
added code below:
![image](https://user-images.githubusercontent.com/20570738/51955092-8442e800-247d-11e9-9ec5-8f6c30abd1d2.png)
and it gives the message above, will it help?

**Comment by EltonZhong** [comment]
```
[17:44:54] We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN.
[11:14:02] We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN.
[14:44:21] We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN.
[17:05:07] Tue, 29 Jan 2019 09:05:07 GMT uncaughtException: read ECONNRESET
[17:05:07] Error: read ECONNRESET
[17:05:07]     at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/xdl/build/logs/PackagerLogsStream.js:436
    if (chunk.msg.match(/Looking for JS files in/)) {
                  ^

TypeError: chunk.msg.match is not a function
    at PackagerLogsStream._formatMsg (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/xdl/build/logs/PackagerLogsStream.js:436:19)
    at Object.write (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/xdl/build/logs/PackagerLogsStream.js:177:24)
    at Logger._emit (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/@expo/bunyan/lib/bunyan.js:928:22)
    at Logger.info (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/@expo/bunyan/lib/bunyan.js:1053:24)
    at Object.logInfo (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/xdl/build/project/ProjectUtils.js:337:27)
    at _logPackagerOutput (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2275:45)
    at Stream.<anonymous> (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:1359:9)
    at Stream.emit (events.js:188:13)
    at drain (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/root/.nvm/versions/node/v11.6.0/lib/node_modules/expo-cli/node_modules/through/index.js:45:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start --clear`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-29T09_05_08_196Z-debug.log
There is a new version of expo-cli available (2.7.0).
You are currently using expo-cli 2.6.14
Run `npm install -g expo-cli` to get the latest version
```

**Comment by TrentonAdams** [comment]
I erroneously posted this on react-native, but I'm posting it here now...

## Environment
```
$ react-native info

  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 18.2 (Sonya)
      CPU: (4) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
      Memory: 889.13 MB / 15.66 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 11.8.0 - ~/.nvm/versions/node/v11.8.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v11.8.0/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v11.8.0/bin/npm
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
```
## Description
This consistently happens when the phone is locked or you close the app on the phone.  On my machine this takes 3 minutes on the nose.  So, I'm guessing there's a 300ms timeout on the socket.  The problem is, it never recovers when I start the phone app back up again, which causes lost productivity because I have to restart expo, and then wait about a minute for the javascript build.  I have a very small project, I can't imagine how painful this would be with larger projects.
```
[21:39:36] events.js:173
[21:39:36]       throw er; // Unhandled 'error' event
[21:39:36]       ^
[21:39:36] 
[21:39:36] Error: read ECONNRESET
[21:39:36]     at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
[21:39:36] Emitted 'error' event at:
[21:39:36]     at emitErrorNT (internal/streams/destroy.js:82:8)
[21:39:36]     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
[21:39:36]     at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

## Reproducible Demo
This happens with any application, no real need for a demo; it's an expo issue for not being able to recover from a connection reset.

**Comment by TrentonAdams** [comment]
Oh, one more thing.  This will only occur if you actually start the app using the expo app and trigger a javascript build on the expo server.  After that I'm guessing it keeps a connection open between the server and the app on the phone to monitor for changes, and that is where the issue lies.

**Comment by Alexdeng09** [comment]
The error disappears once I switch expo to production mode

**Comment by iranmarcius** [comment]
Same here. But production mode didn't solve it.

**Comment by nonoyek** [comment]
need help, facing same problem here too.........

**Comment by UchihaVeha** [comment]
I have the same problem, server crash every 5-20 min, this really annoying restarting server every 5-20 min

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
Maybe the problem because I use the socket.io and websocket in my project? After migrating to expo-cli my websockets connection stop working in development mode

**Comment by cklinx** [comment]
Same here, i am using android emulator on win 10/ ubuntu. Any help?

**Comment by styrken** [comment]
Started to happen after switching to a new laptop 😒 Happens very often.

**Comment by ricardovf** [comment]
Same here. I deleted the .expo folder and upgraded expo CLI to 2.11.8 but the problem insistis.
OSX Mojave (10.14.2).
Expo (clI) 2.11.8
expo@32.0.6
node v10.15.2
Typescript

**Comment by JorgeMoralesLopez** [comment]
Same problem
ubuntu 16.04
expo sdk 32
node v10.15.1
expo cli 2.6.14

**Comment by ricardovf** [comment]
> Same here. I deleted the .expo folder and upgraded expo CLI to 2.11.8 but the problem insistis.
> OSX Mojave (10.14.2).
> Expo (clI) 2.11.8
> expo@32.0.6
> node v10.15.2
> Typescript

I changed to node v8.9.4 and the problem is gone.

**Comment by Deceptio** [comment]
Same here:
expo: "^32.0.0"
react": "16.5.0"
react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz
node v10.11.0

**Comment by liudmyla-schastlyvets** [comment]
The same problem:
 Expo CLI 2.14.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.1 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.16.0 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.14.0

**Comment by AleksandrDorofeev** [comment]
Same problem...

Expo CLI 2.14.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @types/expo: ^32.0.3 => 32.0.10 
      @types/react-navigation: ^3.0.3 => 3.0.6 
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.3.0 => 3.6.1 
    npmGlobalPackages:
      expo-cli: 2.14.0
