### ISSUE TITLE
expo-module build fails when using pnpm and corepack (`packageManager` field in packge.json)

### ISSUE THREAD

**Issue by TimoGlastra** [expo/expo#32382]
### Summary
As title suggests, `expo-module build` fails when using pnpm and corepack (packageManager field in packge.json). It will use `yarn exec` and `corepack` doesn't allow using `yarn` when you have specified to use `pnpm`. 

To reproduce:
- `pnpm create expo-app --template default`
- `corepack use pnpm@9.4.0`
- `pnpm add --save-dev expo-module-scripts`
- `pnpm expo-module build`

It seems to be because of this file: https://github.com/expo/expo/blob/25e4fbd072112bb53c3b456221ce1a86ae110009/packages/expo-module-scripts/bin/npx

```
if [[ ! "$npm_config_user_agent" =~ yarn ]] && [ -x "$(command -v yarn)" ]; then
  yarn exec -- npx "$@"
else
  npx "$@"
fi
```

The value of `$npm_config_user_agent` is evaluated in my environment to:
```
pnpm/9.4.0 npm/? node/v20.11.1 darwin arm64
```

But it still uses the `yarn exec` statement, which then results in an error being thrown by corepack. Removing the if/else statement and just leave the else code fixes the issue. But I'm not so sure on how to fix it, as it seems to use the `yarn exec` code only if `yarn` is NOT found in the `$npm_config_user_agent` (because of the `!`). So before making a PR I wanted to understand why `yarn` exec is used if `yarn` is not in `$npm_config_user_agent`.

```
❯ pnpm expo-module build
Usage Error: This project is configured to use pnpm

$ yarn ...
```

### SDK Version

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 16.0/16A242 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.38
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.13
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/TimoGlastra/expo-pnpm-corepack-repro

Run:
- `corepack enable` (if not enabled yet)
- `corepack use` 
- `pnpm install`
- `pnpm expo-module build`

**Comment by nickrugge** [comment]
it seems expo/eas really likes yarn

**Comment by larcho** [comment]
Same boat, I just ended up creating a new project outside my monorepo.

**Comment by monim67** [comment]
I can't even create the expo module using `npx create-expo-module expo-settings` command not npm install fails always. Is it that broken?

**Comment by thomasrebam** [comment]
Same issue here, trying to build an app using `expo-module build` fails when using the `bun run` command.

I am not sure either to understand why the `[[ ! "$npm_config_user_agent" =~ yarn ]]` check was introduced in the first place (introduced in [this commit](https://github.com/expo/expo/commit/6d2045be9152a9fcc0890a7776863cb8e1d3ae86#diff-f7b17de0e7ff56edbeaef64c83a5a8049bd7964200dde88286a7d4a77d7230c9R4))

**Comment by sultanmyrza** [comment]
> I can't even create the expo module using `npx create-expo-module expo-settings` command not npm install fails always. Is it that broken?

Same here. I enable corepack `corepack enable yarn` and `EXPO_BETA=1 yarn create expo-module`
```
➤ YN0000: · Yarn 4.6.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + create-expo-module@npm:0.8.9, @babel/code-frame@npm:7.10.4, @babel/helper-validator-identifier@npm:7.25.9, @babel/highlight@npm:7.25.9, @expo/bunyan@npm:4.0.1, @expo/config-plugins@npm:9.0.14, @expo/config-types@npm:52.0.3, and 231 more.
➤ YN0000: └ Completed in 1s 716ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 238 packages were added to the project (+ 17.41 MiB).
➤ YN0000: └ Completed in 0s 659ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 2s 457ms

? What is the name of the npm package? › my-module(node:9988) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ What is the name of the npm package? … my-module
✔ What is the native module name? … MyModule
✔ How would you describe the module? … My new module
✔ What is the Android package name? … expo.modules.mymodule
✔ What is the name of the package author? … sultanmyrza
✔ What is the email address of the author? … sultanmyrza@gmail.com
✔ What is the URL to the author's GitHub profile? … https://github.com/sultanmyrza
✔ What is the URL for the repository? … https://github.com/sultanmyrza/my-module

⠋ Downloading module template from npm
Couldn't download the versioned template from npm, falling back to the latest version.
✔ Downloaded module template from npm
✔ Created the module from template files
✖ Installing module dependencies
Error: yarn install exited with non-zero code: 1

Error stack:
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@4.6.0+sha512.5383cc12567a95f1d668fbe762dfe0075c595b4bfff433be478dbbe24e05251a8e8c3eb992a986667c1d53b6c3a9c85b8398c35a960587fbd9fa3a0915406728.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager


    at installDependencies (/private/var/folders/7p/h2rzh7_n3qv9flwkm6gmp1l80000gn/T/xfs-1d50fd83/dlx-9982/.yarn/cache/create-expo-module-npm-0.8.9-555e1d2f2d-99fd27097d.zip/node_modules/create-expo-module/build/packageManager.js:15:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /private/var/folders/7p/h2rzh7_n3qv9flwkm6gmp1l80000gn/T/xfs-1d50fd83/dlx-9982/.yarn/cache/create-expo-module-npm-0.8.9-555e1d2f2d-99fd27097d.zip/node_modules/create-expo-module/build/create-expo-module.js:86:13
    at async newStep (/private/var/folders/7p/h2rzh7_n3qv9flwkm6gmp1l80000gn/T/xfs-1d50fd83/dlx-9982/.yarn/cache/create-expo-module-npm-0.8.9-555e1d2f2d-99fd27097d.zip/node_modules/create-expo-module/build/utils/ora.js:19:16)
    at async Command.main (/private/var/folders/7p/h2rzh7_n3qv9flwkm6gmp1l80000gn/T/xfs-1d50fd83/dlx-9982/.yarn/cache/create-expo-module-npm-0.8.9-555e1d2f2d-99fd27097d.zip/node_modules/create-expo-module/build/create-expo-module.js:85:9)
    
    ```

**Comment by kslbdev** [comment]
any workaround?

**Comment by tom-sherman** [comment]
I was able to resolve this by ensuring corepack didn't choose yarn berry (aka v4). I used `npx create-expo-module` to spin up the templated repo, and then edited `package.json` to include `"packageManager": "yarn@1.22.22"`. Remove any existing lockfiles and node_modules, then run `yarn` to install dependencies.

**Comment by sawa-ko** [comment]
I can't even create a module using the command that appears in the documentation, which is: npx create-expo-module expo-native-configuration

```
sawa@DESKTOP-20HVJVH:~/react-native/expo-modules$ npx create-expo-module expo-native-configuration
✔ What is the name of the npm package? … expo-native-configuration
✔ What is the native module name? … ExpoNativeConfiguration
✔ How would you describe the module? … My new module
✔ What is the Android package name? … expo.modules.nativeconfiguration
✔ What is the name of the package author? … sawa-ko
✔ What is the email address of the author? …
✔ What is the URL to the author's GitHub profile? … https://github.com/sawa-ko
✔ What is the URL for the repository? … https://github.com/sawa-ko/expo-native-configuration

✔ Downloaded module template from npm
✔ Created the module from template files
✖ Installing module dependencies
Error: npm install exited with non-zero code: 1

Error stack:
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated sudo-prompt@9.1.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm warn deprecated @xmldom/xmldom@0.7.13: this version is no longer supported, please update to at least 0.8.*
npm warn deprecated sudo-prompt@8.2.5: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
Tried to guess the docs homepage for expo-native-configuration; add it under the "homepage" entry in package.json
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@4.6.0+sha512.5383cc12567a95f1d668fbe762dfe0075c595b4bfff433be478dbbe24e05251a8e8c3eb992a986667c1d53b6c3a9c85b8398c35a960587fbd9fa3a0915406728.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager

npm error code 1
npm error path /home/sawa/react-native/expo-modules/expo-native-configuration
npm error command failed
npm error command sh -c expo-module prepare
npm error A complete log of this run can be found in: /home/sawa/.npm/_logs/2025-02-21T17_18_38_260Z-debug-0.log

    at installDependencies (/home/sawa/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/packageManager.js:15:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /home/sawa/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:86:13
    at async newStep (/home/sawa/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/utils/ora.js:19:16)
    at async Command.main (/home/sawa/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:85:9)
```

**Comment by lundn** [comment]
We've been looking into the T3 Turbo starter repo with Expo, bu are facing the same issues with pnpm and Expo Modules. Would be great to get some eyes on this!

**Comment by thomasrebam** [comment]
For me a solution was to remove the checks from the expo-module-scripts/bin/npx file : I changed the content of the file from `if [[ ! "$npm_config_user_agent" =~ yarn ]] && [ -x "$(command -v yarn)" ]; then
  yarn exec -- npx "$@"
else
  npx "$@"
fi`
to simply
`npx "$@"`
I launch the command with bun and it has been working fine so far

**Comment by neolivz** [comment]
The best solution (workaround) for me is to uninstall yarn and reinstall it when I need it.

**Comment by eric-edouard** [comment]
Same problem here, this [workaround](https://github.com/expo/expo/issues/31459#issuecomment-2351376833) worked for me !

**Comment by AndrewSouthpaw** [comment]
Still an issue

**Comment by oluwatobiiloba** [comment]
Still experiencing this

**Comment by thomasrebam** [comment]
This seems fixed by https://github.com/expo/expo/pull/37976, which has been deployed in `expo-module-scripts` 4.1.10

I can't see how all this wrapping is useful though, so I opened a PR to remove the npx wrapping behavior

**Comment by kitten** [comment]
Obsolete due to #36296
