### ISSUE TITLE
iOS `xcodebuild` Builds fail to resolve entrypoint when directory is in `/private/tmp` with custom entrypoint

### ISSUE THREAD

**Issue by iameli** [expo/expo#32477]
### Summary

Hi! iOS `xcodebuild` builds fail when the following conditions are met:

1. You're on a Mac.
2. The project is cloned into a subdirectory of `/tmp` (which is actually `/private/tmp` on modern macOS). This happened to me on a CI system.
3. The entrypoint is a local file. `"main": "expo-router/entry"` works fine, `"main": "./app/entrypoint.tsx"` breaks things.

The end result is the following:
```
Error: Unable to resolve module /tmp/expo-bug-example/app/entrypoint.tsx from /private/tmp/expo-bug-example/.:

None of these files exist:
  * ../../../tmp/expo-bug-example/app/entrypoint.tsx(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css)
  * ../../../tmp/expo-bug-example/app/entrypoint.tsx
Error: Unable to resolve module /tmp/expo-bug-example/app/entrypoint.tsx from /private/tmp/expo-bug-example/.:

None of these files exist:
  * ../../../tmp/expo-bug-example/app/entrypoint.tsx(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css)
  * ../../../tmp/expo-bug-example/app/entrypoint.tsx
    at ModuleResolver.resolveDependency (/private/tmp/expo-bug-example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (/private/tmp/expo-bug-example/node_modules/metro/src/node-haste/DependencyGraph.js:232:43)
    at /private/tmp/expo-bug-example/node_modules/metro/src/lib/transformHelpers.js:156:21
    at Server._resolveRelativePath (/private/tmp/expo-bug-example/node_modules/metro/src/Server.js:1104:12)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at MetroBundlerDevServer.resolveRelativePathAsync (/private/tmp/expo-bug-example/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:1208:12)
    at MetroBundlerDevServer.metroLoadModuleContents (/private/tmp/expo-bug-example/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:430:35)
    at MetroBundlerDevServer.legacySinglePageExportBundleAsync (/private/tmp/expo-bug-example/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:553:20)
    at exportEmbedBundleAndAssetsAsync (/private/tmp/expo-bug-example/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:116:21)
    at exportEmbedAsync (/private/tmp/expo-bug-example/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:68:30)
```

### What platform(s) does this occur on?

iOS

### SDK Version

0.18.30 (also confirmed on 0.18.25)

### Environment

```text
▶ npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 22.9.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.3 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.38
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.13
    Expo Workflow: bare
```

### Minimal reproducible example

Do the following things on a Mac:

```
cd /tmp
git clone https://github.com/iameli-streams/expo-bug-example.git
npm install
npx expo prebuild
```
Open the project in XCode and add a signing certificate.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5a727097-3f2b-4e2f-bdce-c0731a807e4d">
```
./run.sh
```

This will run most of a build and then crash.

**Comment by corrosive4354** [comment]
Since the /private/tmp directory may cause path resolution problems, it is recommended to clone your project to another directory (such as the user's home directory) to see if this solves the problem. You can try the following steps:

cd ~
git clone https://github.com/iameli-streams/expo-bug-example.git
cd expo-bug-example
npm install
npx expo prebuild

**Comment by iameli-streams** [comment]
> Since the /private/tmp directory may cause path resolution problems, it is recommended to clone your project to another directory (such as the user's home directory) to see if this solves the problem. You can try the following steps:
> 
> cd ~ git clone https://github.com/iameli-streams/expo-bug-example.git cd expo-bug-example npm install npx expo prebuild

Yep, that 100% works - in my case I just added this to the start of my GitLab CI builds:

```
    - cd ..
    - mv aquareum /Users/admin/aquareum
    - cd /Users/admin/aquareum
```
And then everything works great. Just figured I'd file the bug.

**Comment by iameli** [comment]
Yeah no this is still a problem and I have a repro case and everything.
