### ISSUE TITLE
Expo 52 update error on web - Cannot find module 'inline-style-prefixer/lib/plugins/backgroundClip'

### ISSUE THREAD

**Issue by yjb94** [expo/expo#32491]
### Minimal reproducible example

`npx create-expo-app@latest --template default@beta` and run `npm run web`

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

`npx create-expo-app@latest --template default@beta`
and run
`npm run web``

you will see the error

### Environment

```text

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v22.6.0/bin/npm
      Watchman: 2024.09.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.13 => 52.0.0-preview.13 
      expo-router: ~4.0.0-preview.8 => 4.0.0-preview.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.5.3
    Expo Workflow: managed

```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK
```

**Comment by sharray2918** [comment]
I have the exact same issue

**Comment by lxm7** [comment]
Also having this issue with a brand new Expo boilerplates + Tamagui app. I've tried Expo, Tamagui's and [`npx rn-new@latest` ](https://rn.new/) installs / recommended documentation. I've also tried downgrading Expo to v51, expo router to 3.5 and any associated expo-* packages via npx expo install <pkg> with the same error when trying to run in web:

```
Web node_modules/expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1087/1093)TypeError: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/xxx/Dev/\x00node:inline-style-prefixer/lib/plugins/backgroundClip'
    at Object.readFileSync (node:fs:446:42)
    at getCodeFrame (/Users/xxx/Dev/sessions/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/xxx/Dev/sessions/node_modules/metro/src/Server.js:1026:22)
    at Server._processRequest (/Users/xxx/Dev/sessions/node_modules/metro/src/Server.js:419:7) {
  code: 'ERR_INVALID_ARG_VALUE'
}

Metro error: Cannot find module 'inline-style-prefixer/lib/plugins/backgroundClip'
```

Also tried various metro configs to allow, mjs, cjs. Any suggestions? Its a shame as it looks to be an excellent universal library. Will have to use Nativewind now

**Comment by bastischulz** [comment]
Same. Did anyone find a solution?

**Comment by jasper-infinityquest** [comment]
Same issue. Does anybody know how to fix it?
