### ISSUE TITLE
[SDK 52] development build failed on android (Execution failed for task ':app:processDebugResources')

### ISSUE THREAD

**Issue by Kavosh-m** [expo/expo#32558]
### Minimal reproducible example

https://github.com/Kavosh-m/test-expo-sdk52

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I initialize a new expo project (on Windows 10). then run a development build and got the following error:

`
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     com.testexposdk52.app-mergeDebugResources-2:/values/values.xml:5704: error: resource drawable/splashscreen (aka com.testexposdk52:drawable/splashscreen) not found.
     com.testexposdk52.app-mergeDebugResources-2:/values/values.xml:5704: error: resource drawable/splashscreen (aka com.testexposdk52:drawable/splashscreen) not found.
     error: failed linking references.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 37s
202 actionable tasks: 8 executed, 194 up-to-date
Error: path\to\project\root\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: path\to\project\root\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (path\to\project\root\node_modules\@expo\spawn-async\src\spawnAsync.ts:67:13)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.cp.emit (path\to\project\root\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at spawnAsync (path\to\project\root\node_modules\@expo\spawn-async\src\spawnAsync.ts:28:21)
    at spawnGradleAsync (path\to\project\root\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:134:28)
    at assembleAsync (path\to\project\root\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:83:16)
    at runAndroidAsync (path\to\project\root\node_modules\@expo\cli\src\run\android\runAndroidAsync.ts:48:24)

`

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 30, 31, 32, 33, 34, 35
        Build Tools: 30.0.3, 32.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-242.23339.11.2421.12483815
    npmPackages:
      expo: ~52.0.0-preview.16 => 52.0.0-preview.18
      expo-router: ~4.0.0-preview.11 => 4.0.0-preview.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✖ Check Expo config (app.json/ app.config.js) schema
Unexpected error while running 'Check Expo config (app.json/ app.config.js) schema' check:
TypeError: fetch failed
Error: getaddrinfo EAI_AGAIN exp.host
This check requires a connection to the Expo API. Please check your network connection.
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for issues with Metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✖ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by alanjhughes** [comment]
Hi @Kavosh-m, I've pulled your repro but I'm not seeing the error. The app runs as normal

![Screenshot_1730626117](https://github.com/user-attachments/assets/5cc67bd4-9294-44ec-8bd8-5c1e04ec7e13)

**Comment by Kavosh-m** [comment]
> Hi @Kavosh-m, I've pulled your repro but I'm not seeing the error. The app runs as normal
> 
> ![Screenshot_1730626117](https://github.com/user-attachments/assets/5cc67bd4-9294-44ec-8bd8-5c1e04ec7e13)
> 

thanks for your feedback. do you run it on Windows?

**Comment by ChronoByteCosmonaut** [comment]
Had the same error!

**Comment by AmdjedSanero** [comment]
me too the same error ??

**Comment by brunocentanaro** [comment]
I'm having the same error

**Comment by brunocentanaro** [comment]
seems to be fixed in ```^52.0.0-preview.20``` (i also upgraded splash with ```npx expo install --fix```)

**Comment by Kavosh-m** [comment]
> seems to be fixed in `^52.0.0-preview.20` (i also upgraded splash with `npx expo install --fix`)

still have issue on windows. I update expo version to `"~52.0.0-preview.21"` and got following error:

> ninja: build stopped: .
> 
>   C++ build system [build] failed while executing:
>       @echo off
>       "C:\\Users\\username\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
>         -C ^
>         "D:\\something\\Personal\\ReactNative\\TestProjects\\test-expo-sdk52\\node_modules\\react-native-reanimated\\android\\.cxx\\Debug\\1f59275c\\arm64-v8a" ^
>         reanimated ^
>         worklets
>     from D:\something\Personal\ReactNative\TestProjects\test-expo-sdk52\node_modules\react-native-reanimated\android
>   ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/D_/something/Personal/ReactNative/TestProjects/test-expo-sdk52/node_modules/react-native-reanimated): No such file or directory

here is my `package.json` :

```json
{
  "name": "test-expo-sdk52",
  "license": "0BSD",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint",
    "postinstall": "patch-package"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/bottom-tabs": "7.0.0-rc.36",
    "@react-navigation/native": "7.0.0-rc.21",
    "expo": "~52.0.0-preview.21",
    "expo-audio": "~0.2.3",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.2",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.2",
    "expo-router": "~4.0.0-preview.11",
    "expo-splash-screen": "~0.29.3",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.2",
    "expo-web-browser": "~14.0.0",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.1",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "4.0.0-beta.16",
    "react-native-web": "~0.19.13"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.0-preview.3",
    "patch-package": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },
  "private": true
}

```

**Comment by brunocentanaro** [comment]
That error seems different to the one on the issue though. I would try deleting the ```node_modules``` and ```android``` folders, reinstalling and running the prebuild again to see if that fixes it

**Comment by Mihai-github** [comment]
Hello, I'm getting the same error when trying to build the app (not using Expo Go). The script I'm running is the following 
`rm -rf ./android && expo run:android --device`

IMPORTANT: I'm getting the error on a fresh version of Expo just created yesterday

**Comment by dipen-apptrait** [comment]
I am having same issue.     "expo": "~52.0.11", Any solution?

**Comment by lagoasoft-yagosantos** [comment]
same here "expo": "~52.0.18"

**Comment by sarveshhh-m** [comment]
> same here "expo": "~52.0.18"

+1

**Comment by AnjanaDhakal** [comment]
i have the build error but after adding firebase googleService.json.

**Comment by wjd3** [comment]
+1 with `"expo": "~52.0.19"` on Mac OS 15.1.1

**Comment by andrewchester1** [comment]
same

**Comment by Poojaauma** [comment]
```Task :expo-updates-interface:bundleLibRuntimeToDirRelease
> Task :app:checkReleaseDuplicateClasses FAILED
> Task :app:dexBuilderRelease
> Task :react-native-reanimated:buildCMakeRelWithDebInfo[x86_64]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class android.support.v4.app.INotificationSideChannel found in modules core-1.13.1.aar -> core-1.13.1-runtime (androidx.core:core:1.13.1) and support-compat-26.1.0.aar -> support-compat-26.1.0-runtime (com.android.support:support-compat:26.1.0)
     Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules core-1.13.1.aar -> core-1.13.1-runtime (androidx.core:core:1.13.1) and support-compat-26.1.0.aar -> support-compat-26.1.0-runtime (com.android.support:support-compat:26.1.0)
     Duplicate class android.support.v4.app.INotificationSideChannel$Stub$Proxy found in modules core-1.13.1.aar -> core-1.13.1-runtime (androidx.core:core:1.13.1) and support-compat-26.1.0.aar -> support-compat-26.1.0-runtime (com.android.support:support-compat:26.1.0)
     Duplicate class android.support.v4.media.MediaBrowserCompat found in modules media-1.7.0.aar -> media-1.7.0-runtime (androidx.media:media:1.7.0) and support-media-compat-26.1.0.aar -> support-media-compat-26.1.0-runtime (com.android.support:support-media-compat:26.1.0)```


Has anyone faced the above issue when we run `eas build --platform android --profile production` . We are using expo sdk 52 and react-native "0.76.5"?

**Comment by AnjanaDhakal** [comment]
@Poojaauma  count me i am facing the same error since last week . i am using   "react-native": "0.76.3". For me build failed after adding firebase module

**Comment by Poojaauma** [comment]
@AnjanaDhakal ,

Without firebase module, is the build working fine?

**Comment by AnjanaDhakal** [comment]
@Poojaauma  yes  before installin firebase app and module development build works fine

**Comment by Poojaauma** [comment]
Can you please share your package.json file? @AnjanaDhakal

**Comment by AnjanaDhakal** [comment]
@Poojaauma , here is the json file.


{
  "name": "rider_app",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native-firebase/app": "^21.6.1",
    "@react-native-firebase/messaging": "^21.6.1",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "expo": "~52.0.17",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.11",
    "expo-secure-store": "~14.0.0",
    "expo-splash-screen": "~0.29.15",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.5",
    "expo-web-browser": "~14.0.1",
    "frappe-js-sdk": "^1.7.0",
    "nativewind": "^4.1.23",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.3",
    "react-native-alert-notification": "^0.4.2",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5",
    "tailwindcss": "^3.4.16"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },
  "private": true
}

**Comment by benpigchu** [comment]
I believe this has some connection with https://github.com/ninja-build/ninja/issues/1900#issuecomment-1817532728

**Comment by shutoo** [comment]
Same here expo 52.0.23

I was able to solve the problem in the following way.

### 1. Add these two files

expo-plugins/withGradleProperties.js

```javascript
const { withGradleProperties } = require('@expo/config-plugins')

module.exports = function withGradlePropertiesModification(config) {
  return withGradleProperties(config, config => {
    const properties = config.modResults

    // Enable AndroidX
    if (!properties.find(p => p.key === 'android.useAndroidX')) {
      properties.push({ type: 'property', key: 'android.useAndroidX', value: 'true' })
    }

    // Enable Jetifier
    if (!properties.find(p => p.key === 'android.enableJetifier')) {
      properties.push({ type: 'property', key: 'android.enableJetifier', value: 'true' })
    }

    return config
  })
}
```

expo-plugins/withAndroidManifest.js

```javascript
const { withAndroidManifest } = require('@expo/config-plugins')

module.exports = function withAndroidManifestModification(config) {
  return withAndroidManifest(config, config => {
    config.modResults.manifest.application[0]['$']['tools:replace'] = 'android:appComponentFactory'
    config.modResults.manifest.application[0]['$']['android:appComponentFactory'] =
      'androidx.core.app.CoreComponentFactory'

    return config
  })
}
```

### 2. Update app.json with these plugins

```
{
  "expo": {
    ...
    "plugins": [
      ...
      "./expo-plugins/withAndroidManifest",
      "./expo-plugins/withGradleProperties"
    ]
  }
}
```

I'm not sure which library caused the error yet.

**Comment by vikasmis** [comment]
1. Get Latest Android studio 
2. Clean the project in Android studio. 
3. sudo rm -rf ~/.gradle/caches
4. cd android
./gradlew assembleDebug
5. restart laptop

**Comment by jpaas** [comment]
afaik this issue was never solved. I had to create an expo plugin to enable jetifier in the gradle properties.

**Comment by mantrobuski** [comment]
I'm still experiencing this issue.

**Comment by muhammedaksam** [comment]
~52.0.46

**Comment by AyoCodess** [comment]
same error

**Comment by itsmbaqer** [comment]
Same error message

**Comment by Z3NTL3** [comment]
same

**Comment by ygnoh** [comment]
You can fix it by running `expo install expo-secure-store`.

**Comment by Z3NTL3** [comment]
I wanna tell that I'm managing a college project and we choose for Expo, however we do not use EAS or the cloud services, because we do not wanna participate in fee's while we just align with the framework, on Expo router and Expo managed libraries side ofc.

So we do local app compilation, and I found that the caches are sorta buggy. It does not detect making changes when the dependencies change. Therefore it fails the build if you try it with newly installed dependencies (or link not sure), well the solution for me is, destroying the cache and ``android`` | ``ios`` folders. Which solves the build artifact on the next run.

I am also using Nitro Modules. But I don't always have to purge ``android`` folder, only when I introduce some new dependencies
