### ISSUE TITLE
Expo export -p web fails to transpile async code

### ISSUE THREAD

**Issue by Manodiestra** [expo/expo#32599]
### Summary

When building an expo with `npx expo export -p web` and serving with `npx serve dist` the app can be served, but fails to render.

The browser console gives the error:

```
entry-f7a9e494bd11e33378f96a0b17c50c35.js:111 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Promise%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ou (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:56778)
    at e (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:61777)
    at Do (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:73372)
    at Bi (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:120039)
    at Us (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:111214)
    at Os (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:111142)
    at Ds (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:111005)
    at xs (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:107423)
    at Ss (entry-f7a9e494bd11e33378f96a0b17c50c35.js:111:106390)
    at k (entry-f7a9e494bd11e33378f96a0b17c50c35.js:123:1376)
```

This only happens if the code contains an `async` function. Removing any `async` functions resolves the error and it is served as expected.

This error occurs if the export has app.json configured for web `static` or `single` output.

Expected behavior is that the app is served and renders correctly.

### What platform(s) does this occur on?

Web

### SDK Version

51.0.28

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.3 (Virginia)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
      npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
      Watchman: 2023.12.04.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google Play Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom, android-35 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~51.0.28 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ^0.19.13 => 0.19.13 
    Expo Workflow: managed
```

### Minimal reproducible example

Starting with the basic app generated from `npx create-expo-app AppName` and `npm run reset-project` all you need to do is add `async` to any function declaration and then  `npx expo export -p web` and serving with `npx serve dist`.

**Comment by samtsai** [comment]
The issues for me have gone away in one of the latest expo sdk and/or expo package updates.

**Comment by Manodiestra** [comment]
Yes, this issue seems to be resolved with SDK 52.
