### ISSUE TITLE
Expo51 - iOS - Expo EAS Build failed - PhaseScriptExecution [Hermes] Replace hermes for the right configuration 

### ISSUE THREAD

**Issue by CastelukeDevs** [expo/expo#32590]
### Minimal reproducible example

https://github.com/CastelukeDevs/monst-moneystory

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

I Tried to build my project with eas build.
android build is ok. but iOS has some issues with Hermes in run fastlane phase.
note: While debugging this, I tried to build it in my local machine using --local flag.
It build without error.

specific error from fastlane:
````
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/expo/Library/Developer/Xcode/DerivedData/MoneyStorydevelopment-ewmnbthazvkqocaoywdseidfxfru/Build/Intermediates.noindex/ArchiveIntermediates/MoneyStorydevelopment/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/hermes-engine.build/Script-46EB2E00029E40.sh (in target 'hermes-engine' from project 'Pods')
▸ 	Archiving workspace MoneyStorydevelopment with scheme MoneyStorydevelopment
▸ (2 failures)
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/expo/Library/Developer/Xcode/DerivedData/MoneyStorydevelopment-ewmnbthazvkqocaoywdseidfxfru/Build/Intermediates.noindex/ArchiveIntermediates/MoneyStorydevelopment/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/hermes-engine.build/Script-46EB2E00029E40.sh (in target 'hermes-engine' from project 'Pods')
	Archiving workspace MoneyStorydevelopment with scheme MoneyStorydevelopment
(2 failures)

Exit status: 65
````

I have been trying so hard to resolve the issues but most is finding somthing like removing **ios/.xcode.env.local** or modify **ios/.xcode.env**.  but this file is generated while expo prebuild in build phase isnt it?
and the build error only happen in expo build, and fine in my local.

I tried to download the logs from expo and find the error. then this is the result:
````
Node found at: /Users/expo/.nvm/versions/node/v18.18.0/bin/node
Preparing the final location
node:internal/fs/utils:350
    throw err;
    ^

Error: EPERM: operation not permitted, scandir 'hermes-engine'
    at readdirSync (node:fs:1527:3)
    at _rmdirSync (node:internal/fs/rimraf:250:29)
    at rimrafSync (node:internal/fs/rimraf:200:14)
    at Object.rmSync (node:fs:1278:10)
    at replaceHermesConfiguration (/Users/expo/workingdir/build/node_modules/react-native/sdks/hermes-engine/utils/replace_hermes_version.js:60:6)
    at main (/Users/expo/workingdir/build/node_modules/react-native/sdks/hermes-engine/utils/replace_hermes_version.js:79:3)
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/react-native/sdks/hermes-engine/utils/replace_hermes_version.js:106:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  errno: -1,
  syscall: 'scandir',
  code: 'EPERM',
  path: 'hermes-engine'
}

Node.js v18.18.0
Command PhaseScriptExecution failed with a nonzero exit code


````

If there is any info or something constructive please reply and help me. If there is something details missing I will edit and add later. 

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/opt/ruby@3.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.38 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.6.2
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment]
hey there! it looks like your minimal repro is not quite minimal - it includes a lot of unrelated code. please try to narrow it down further.

once you've reproduced it in a minimal example, try out following this guide: https://docs.expo.dev/build-reference/troubleshooting/

**Comment by CastelukeDevs** [comment]
It is using new expo project and I only added my package list and eas config there which shouldnt be too much.
The problem stem in the project unable to be **build** in expo. working on local build.
The expo project in repro is 99% from expo. I only including my necessary package which while in build behave the same way with my original project.

**Comment by d4rky-pl** [comment]
We had similar issue, turned out our `cocoapods` version was specified in `eas.json` and it was quite old (1.14.3). Switching to latest (1.16.2) solved the issue for us. @CastelukeDevs you may want to check if that solves the problem for you, [it's in "ios" section of eas.json](https://docs.expo.dev/eas/json/#cocoapods)
