### ISSUE TITLE
Image resizing failure with SDK 52 and Android images

### ISSUE THREAD

**Issue by joshmohrer** [expo/expo#32625]
### Minimal reproducible example

NA

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

In trying to prebuild with expo 52, I get this error. It originally showed an error like this for android.adaptiveIcon.backgroundImage, so I removed those from app.json and it just went to the next image. Something is wonky with app.json android image processing.

✖ Prebuild failed
Error: [android.dangerous]: withAndroidDangerousBaseMod: It was not possible to generate splash screen './assets/icon.png'. Expected positive integer for width but received 93.60000000000001 of type number
Error: [android.dangerous]: withAndroidDangerousBaseMod: It was not possible to generate splash screen './assets/icon.png'. Expected positive integer for width but received 93.60000000000001 of type number
    at resizeAsync (/Users/joshuamohrer/Coding/waveapp/node_modules/@expo/image-utils/build/Image.js:105:15)
    at async generateImageAsync (/Users/joshuamohrer/Coding/waveapp/node_modules/@expo/image-utils/build/Image.js:214:18)
    at async generateIconAsync (/Users/joshuamohrer/Coding/waveapp/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:350:7)
    at async /Users/joshuamohrer/Coding/waveapp/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:273:21
    at async Promise.all (index 3)
    at async generateMultiLayerImageAsync (/Users/joshuamohrer/Coding/waveapp/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:269:3)
    at async setIconAsync (/Users/joshuamohrer/Coding/waveapp/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:156:3)
    at async /Users/joshuamohrer/Coding/waveapp/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:102:5
    at async action (/Users/joshuamohrer/Coding/waveapp/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/build/plugins/withMod.js:199:23)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.3/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v18.20.3/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0-preview.19 => 52.0.0-preview.19 
      expo-router: ~4.0.0-preview.12 => 4.0.0-preview.12 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ^0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.6.2
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
joshuamohrer@Joshuas-MacBook-Pro-2 waveapp % npx expo-doctor@latest                  
» android: expo-share-intent: your Expo SDK version does not match requirements! v2.5.2 needs ^51, found 52.0.0. Please refer to the compatibility table. https://github.com/achorein/expo-share-intent/#versioning
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check native tooling versions
✖ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~9.0.0
Found invalid:
  @expo/config-plugins@8.0.10
  @expo/config-plugins@8.0.10
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: @intercom/intercom-react-native, expo-quick-actions, react-native-adapty, react-native-fs, react-native-phone-input, react-native-quick-base64, react-native-restart, react-native-select-contact, react-native-siri-shortcut
Unmaintained: react-native-fs, react-native-phone-input
No metadata available: @adapty/react-native-ui, @config-plugins/react-native-siri-shortcut, @expo/config-plugins, @microsoft/microsoft-graph-client, @twotalltotems/react-native-otp-input, axios, base-64, date-fns, expo-checkbox, ffmpeg-kit-react-native, libphonenumber-js, lodash, marked, p-retry, path, phone, react-native-otp-textinput, react-native-pdf-thumbnail, react-native-skadnetwork, react-native-social-buttons, react-native-sound-player, rxjs, use-debounce
Advice: 
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by brentvatne** [comment]
@joshmohrer - can you please share a minimal reproducible example?

**Comment by brentvatne** [comment]
i can repro this if i install sharp-cli: 

```
npm i -g sharp-cli@^2.1.0

npx expo prebuild -p android --clean
! Git branch has uncommited file changes
› It's recommended to commit all changes before proceeding in case you want to revert generated changes.

✔ Continue with uncommited changes? … yes

✔ Cleared android code
✔ Created native directory
✔ Updated package.json | no changes
✖ Prebuild failed
Error: [android.dangerous]: withAndroidDangerousBaseMod: Expected integer for left but received 2.5 of type number
Error: [android.dangerous]: withAndroidDangerousBaseMod: Expected integer for left but received 2.5 of type number
    at Object.invalidParameterError (/Users/brent/.nvm/versions/node/v20.15.1/lib/node_modules/sharp-cli/node_modules/sharp/lib/is.js:124:10)
    at /Users/brent/.nvm/versions/node/v20.15.1/lib/node_modules/sharp-cli/node_modules/sharp/lib/composite.js:150:18
    at Array.map (<anonymous>)
    at Sharp.composite (/Users/brent/.nvm/versions/node/v20.15.1/lib/node_modules/sharp-cli/node_modules/sharp/lib/composite.js:117:35)
    at compositeImagesAsync (/Users/brent/code/test-sajorahasan/node_modules/@expo/image-utils/build/Image.js:240:10)
    at async /Users/brent/code/test-sajorahasan/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:273:21
    at async Promise.all (index 0)
    at async generateMultiLayerImageAsync (/Users/brent/code/test-sajorahasan/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:269:3)
    at async setIconAsync (/Users/brent/code/test-sajorahasan/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:156:3)
    at async /Users/brent/code/test-sajorahasan/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:102:5
```

**Comment by sajorahasan** [comment]
Hi @brentvatne thank you for looking into this.
I have tried using `EXPO_IMAGE_UTILS_NO_SHARP npx expo prebuild` but got this error `zsh: command not found: EXPO_IMAGE_UTILS_NO_SHARP`

Anyway the error has been resolved with latest expo beta version `52.0.0-preview.22` npx prebuild commands run successfully without any error.
I had initially faced this error with version `52.0.0-preview.18`
https://github.com/expo/expo/pull/32649

**Comment by brentvatne** [comment]
that would be `EXPO_IMAGE_UTILS_NO_SHARP=1 npx expo prebuild` - that's how you set an env var

if you can share a minimal repro where we can re-create this issue it would be very helpful. https://stackoverflow.com/help/minimal-reproducible-example

**Comment by sajorahasan** [comment]
Hi @brentvatne thanks for all the help but I am not able to reproduce this with the latest beta expo template anymore.

**Comment by meftunca** [comment]
I found an issue related to this problem in the jimp js library as the source of the problem. Maybe the problem could be the creation of the “.DS_store” file as mentioned here.

https://github.com/jimp-dev/jimp/issues/643

**Comment by meftunca** [comment]
I have a similar problem with jimp
```
✔ Continue with uncommited changes? … yes

✔ Cleared android code
Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "description", "iosAppName", "displayName", "enrollVersion"
Learn more: https://expo.fyi/root-expo-object
✔ Created native directory
› Using current versions instead of recommended expo@~52.0.0-preview.22.
✔ Updated package.json | no changes
✖ Prebuild failed
Error: [android.dangerous]: withAndroidDangerousBaseMod: Could not find MIME for Buffer <null>
Error: [android.dangerous]: withAndroidDangerousBaseMod: Could not find MIME for Buffer <null>
    at Jimp.parseBitmap (/Users/***technologies/Desktop/***/***-mobile/node_modules/jimp-compact/dist/jimp.js:1:125518)
    at Jimp.parseBitmap (/Users/***technologies/Desktop/***/***-mobile/node_modules/jimp-compact/dist/jimp.js:1:8514)
    at new Jimp (/Users/***technologies/Desktop/***/***-mobile/node_modules/jimp-compact/dist/jimp.js:1:7847)
    at _construct (/Users/***technologies/Desktop/***/***-mobile/node_modules/jimp-compact/dist/jimp.js:1:18894)
    at /Users/***technologies/Desktop/***/***-mobile/node_modules/jimp-compact/dist/jimp.js:1:14079
    at new Promise (<anonymous>)
    at B.read (/Users/***technologies/Desktop/***/***-mobile/node_modules/jimp-compact/dist/jimp.js:1:14037)
    at Object.getJimpImageAsync (/Users/***technologies/Desktop/***/***-mobile/node_modules/@expo/image-utils/build/jimp.js:136:45)
    at compositeImagesAsync (/Users/***technologies/Desktop/***/***-mobile/node_modules/@expo/image-utils/build/Image.js:238:87)
    at runNextTicks (node:internal/process/task_queues:65:5)
```

**Comment by meftunca** [comment]
I found the solution to the problem, at least in my own project, and it really worked as expected. 
Steps
1. remove the .expo folder in the root directory of the project
2. Run `npx expo prebuild -p android --clean`

**Comment by meftunca** [comment]
Hi @rotoxl , this(`ios: icon: No icon is defined in the Expo config.`)
Can you update the app.config.js file related to the section and try again?

**Comment by rotoxl** [comment]
Hey @meftunca, 
Yeah, unfortunately no differences 

```
╭─rotoxl@ICEO--MacBook-Pro--emolina ~/dev/beone-mobile-2  ‹bump/test-newarch-sdk52beta*›
╰─➤  npx expo prebuild --clean
env: load .env.local
env: export EXPO_PUBLIC_DEFAULT_ENV EXPO_PUBLIC_API_PLACEHOLDER EXPO_PUBLIC_API_URL EXPO_PUBLIC_WS_URL EXPO_PUBLIC_ADMIN_API_URL EXPO_PUBLIC_WEB_CLIENT_ID EXPO_PUBLIC_ALLOW_ENV_CHANGE EXPO_PUBLIC_TMX_ORG_ID EXPO_PUBLIC_TMX_FP_SERVER EXPO_PUBLIC_ENABLE_PROFILING
! Git branch has uncommited file changes
› It's recommended to commit all changes before proceeding in case you want to revert generated changes.

✔ Continue with uncommited changes? … yes

✔ Cleared android, ios code
✔ Created native directories
› Using current versions instead of recommended expo@~52.0.0-preview.23.
✔ Updated package.json | no changes
✖ Prebuild failed
TypeError: [android.dangerous]: withAndroidDangerousBaseMod: (0 , _imageUtils(...).generateImageBackgroundAsync) is not a function
TypeError: [android.dangerous]: withAndroidDangerousBaseMod: (0 , _imageUtils(...).generateImageBackgroundAsync) is not a function
    at generateIconAsync (/Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:360:75)
    at async /Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:273:21
    at async Promise.all (index 0)
    at async generateMultiLayerImageAsync (/Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:269:3)
    at async setIconAsync (/Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:156:3)
    at async /Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:102:5
    at async action (/Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/config-plugins/build/plugins/withMod.js:199:23)
    at async interceptingMod (/Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async action (/Users/rotoxl/dev/beone-mobile-2/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:60:21)
```

**Comment by matt-42** [comment]
Thanks @samtsai  this worked for me. In my case it was the expo-assets package (latest version) that was pulling the old @expo/image-utils version

**Comment by flexbox** [comment]
I jut made a reproductible example using [expo.new](https://expo.new).

https://github.com/flexbox/expo-52-app-icon-badge

Build works with

```json
    "app-icon-badge": "^0.1.2",
    "expo": "~52.0.27",
```

![Image](https://github.com/user-attachments/assets/57b26c26-df03-4847-8630-1fb0b8fa1e90)

Now I need to make the build working again on my project due to this error
```
 [ios.dangerous]: withIosDangerousBaseMod: Unrecognised filter type - 255
```
I will give an update on this.

**Comment by emmyduruc** [comment]
i am having same issue but when I comment out      // "icon": "./assets/images/icon.png", then it runs for me

**Comment by flexbox** [comment]
@joshmohrer If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

And for other people who are landing here and want to rely on a simple solution (_no image generation with a third part library_).
1. follow the setup https://github.com/betomoedano/with-environments/tree/main
2. add dynamic image for env https://github.com/betomoedano/with-environments/blob/main/app.config.ts

**Comment by laponovsemen** [comment]
> I found the solution to the problem, at least in my own project, and it really worked as expected. Steps
> 
> 1. remove the .expo folder in the root directory of the project
> 2. Run `npx expo prebuild -p android --clean`



This helped me
