### ISSUE TITLE
ExpoKit - Android Crash onload - java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by owenhope** [expo/expo#3278]
Hi.

`java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so`

I keep getting this error whenever I try and open my standalone app on device after uploading to Play Store the app works fine when testing through Android Studio on device.

```
01-21 17:00:29.333 19998 20102 E AndroidRuntime: FATAL EXCEPTION: Thread-9
01-21 17:00:29.333 19998 20102 E AndroidRuntime: Process: com.xxx.xxx, PID: 19998
01-21 17:00:29.333 19998 20102 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:703)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:564)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:500)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:914)
01-21 17:00:29.333 19998 20102 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

```

Running Expo 32, ExpoKit 32.0.5

**Comment by owenhope** [comment]
I solved by delete ios/android and re-ejecting.

**Comment by markygab** [comment]
I've also just got this error. After 3 days in dependency Gradle hell trying to upgrade to ExpoKit 32 to remove the READ_SMS permission, now what?
