### ISSUE TITLE
expo-video 2.0.0 [RUN_GRADLEW] Execution failed for task ':expo-video:compileDebugKotlin'. - 1.2.7 builds

### ISSUE THREAD

**Issue by sanchaz** [expo/expo#32993]
### Minimal reproducible example

.

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

[RUN_GRADLEW] Execution failed for task ':expo-video:compileDebugKotlin'.
[RUN_GRADLEW] > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
[RUN_GRADLEW]    > Compilation error. See log for more details
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 1m 37s
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
[RUN_GRADLEW] 727 actionable tasks: 726 executed, 1 up-to-date
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      npm: 10.9.0 - ~/.nvm/versions/node/v20.18.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12483815
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.39 => 51.0.39 
      expo-router: ~3.5.24 => 3.5.24 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 13.2.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by CavalcanteLeo** [comment]
same error, cannot compile android anymore

```
bun android
$ expo run:android
env: load .env.development.local
env: export APP_VARIANT EXPO_PUBLIC_BD EXPO_APPLE_TEAM_ID EXPO_PUBLIC_FIREBASE_API_KEY EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN EXPO_PUBLIC_FIREBASE_PROJECT_ID EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID EXPO_PUBLIC_FIREBASE_APP_ID EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID EXPO_PUBLIC_TYPESENSE_HOST EXPO_PUBLIC_TYPESENSE_API_KEY EXPO_PUBLIC_TYPESENSE_EVENTS_COLLECTION EXPO_PUBLIC_TYPESENSE_LIVE_UPDATES_COLLECTION EXPO_PUBLIC_TYPESENSE_EVENT_TEMPLATES_COLLECTION EXPO_PUBLIC_TYPESENSE_EVENT_BRANDS_COLLECTION EXPO_PUBLIC_TYPESENSE_PERFORMERS_COLLECTION EXPO_PUBLIC_TYPESENSE_PROMOTERS_COLLECTION EXPO_PUBLIC_TYPESENSE_VENUES_COLLECTION SENTRY_DSN SENTRY_PROJECT SENTRY_AUTH_TOKEN EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY EXPO_PUBLIC_STRIPE_DEGEN_PRICE_ID
› Building app...
Configuration on demand is an incubating feature.

> Configure project :app
 ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@4.0.29)
 ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.25.27)
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.

> Configure project :shopify_react-native-skia
react-native-skia: node_modules/ found at: /Users/leonardocavalcante/Projects/bondi-lines/app/node_modules
react-native-skia: RN Version: 74 / 0.74.5
react-native-skia: isSourceBuild: false
react-native-skia: PrebuiltDir: /Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/@shopify/react-native-skia/android/build/react-native-0*/jni
react-native-skia: buildType: debug
react-native-skia: buildDir: /Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/@shopify/react-native-skia/android/build
react-native-skia: node_modules: /Users/leonardocavalcante/Projects/bondi-lines/app/node_modules
react-native-skia: Enable Prefab: true
react-native-skia: aar state post 70, do nothing

> Configure project :expo

Using expo modules
  - expo-application (5.9.1)
  - expo-asset (10.0.10)
  - expo-av (14.0.7)
  - expo-blur (13.0.2)
  - expo-camera (15.0.16)
  - expo-constants (16.0.2)
  - expo-crypto (13.0.2)
  - expo-dev-client (4.0.29)
  - expo-dev-launcher (4.0.29)
  - expo-dev-menu (5.0.23)
  - expo-device (6.0.2)
  - expo-eas-client (0.12.0)
  - expo-file-system (17.0.1)
  - expo-font (12.0.10)
  - expo-haptics (13.0.1)
  - expo-image (1.13.0)
  - expo-image-loader (4.7.0)
  - expo-image-picker (15.0.7)
  - expo-json-utils (0.13.1)
  - expo-keep-awake (13.0.2)
  - expo-linear-gradient (13.0.2)
  - expo-localization (15.0.3)
  - expo-location (17.0.1)
  - expo-mail-composer (13.0.1)
  - expo-manifests (0.14.3)
  - expo-media-library (16.0.5)
  - expo-modules-core (1.12.26)
  - expo-secure-store (13.0.2)
  - expo-sharing (12.0.1)
  - expo-splash-screen (0.27.7)
  - expo-store-review (7.0.2)
  - expo-structured-headers (3.8.0)
  - expo-system-ui (3.0.7)
  - expo-tracking-transparency (4.0.2)
  - expo-updates (0.25.27)
  - expo-video (2.0.3)
  - expo-web-browser (13.0.3)
  - react-native-image-colors (2.4.0)


> Configure project :react-native-quick-md5
react-native-quick-md5: node_modules/ found at: /Users/leonardocavalcante/Projects/bondi-lines/app/node_modules

> Configure project :react-native-reanimated
Android gradle plugin: 8.2.1
Gradle: 8.8

> Configure project :react-native-video
Kotlin version is correct: 1.9.23
useExoplayerIMA: false
useExoplayerSmoothStreaming: true
useExoplayerDash: true
useExoplayerHls: true
useExoplayerRtsp: false
buildFromSource: false

> Configure project :react-native-vision-camera
[VisionCamera] Thank you for using VisionCamera ❤️
[VisionCamera] If you enjoy using VisionCamera, please consider sponsoring this project: https://github.com/sponsors/mrousavy
[VisionCamera] node_modules found at /Users/leonardocavalcante/Projects/bondi-lines/app/node_modules
[VisionCamera] VisionCamera_enableFrameProcessors is set to true!
[VisionCamera] react-native-worklets-core not found, Frame Processors are disabled!
[VisionCamera] VisionCamera_enableCodeScanner is set to false!

> Task :app:processDebugMainManifest
/Users/leonardocavalcante/Projects/bondi-lines/app/android/app/src/debug/AndroidManifest.xml:6:5-162 Warning:
        application@android:usesCleartextTraffic was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
/Users/leonardocavalcante/Projects/bondi-lines/app/android/app/src/debug/AndroidManifest.xml Warning:
        provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present

> Task :expo-video:compileDebugKotlin
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:40:72 Unresolved reference: throwingActivity
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:108:45 Unresolved reference: throwingActivity
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:340:7 No value passed for parameter 'name'
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:340:12 No type arguments expected for inline fun Class(name: String, body: ClassComponentBuilder<Unit>.() -> Unit = ...): Unit
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:341:40 Unresolved reference: width
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:342:41 Unresolved reference: height
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:343:48 Unresolved reference: requestedTime
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoModule.kt:344:45 Unresolved reference: actualTime
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoThumbnail.kt:15:3 'nativeRefType' overrides nothing
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoThumbnail.kt:17:3 'getAdditionalMemoryPressure' overrides nothing
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoView.kt:48:44 Unresolved reference: throwingActivity
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoView.kt:206:32 Variable expected
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoView.kt:216:30 Variable expected
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/drawing/OutlineProvider.kt:55:30 Unresolved reference: instance
e: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-video/android/src/main/java/expo/modules/video/player/VideoPlayer.kt:337:7 Unresolved reference: emit

> Task :expo-video:compileDebugKotlin FAILED

> Task :expo-updates:compileDebugKotlin
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/DisabledUpdatesController.kt:63:20 This class shouldn't be used in Kotlin. Use kotlin.Any instead.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/DisabledUpdatesController.kt:164:14 This class shouldn't be used in Kotlin. Use kotlin.Any instead.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt:5:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt:79:39 This class shouldn't be used in Kotlin. Use kotlin.Any instead.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt:114:20 This class shouldn't be used in Kotlin. Use kotlin.Any instead.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt:232:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt:232:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt:258:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt:258:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesConfiguration.kt:189:13 'get(String!): Any?' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt:4:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt:183:138 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt:290:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt:290:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesModule.kt:4:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesModule.kt:151:46 'toString(): String' is deprecated. Prefer to use specific field getters
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesModule.kt:240:7 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesModule.kt:240:17 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesModule.kt:246:7 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesModule.kt:246:17 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/Converters.kt:56:30 Type mismatch: inferred type is ByteArray? but ByteArray was expected
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/Converters.kt:98:21 Parameter 'value' is never used
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/Converters.kt:103:21 Parameter 'hashType' is never used
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/DatabaseHolder.kt:24:20 This class shouldn't be used in Kotlin. Use kotlin.Any instead.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/DatabaseHolder.kt:36:14 This class shouldn't be used in Kotlin. Use kotlin.Any instead.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/DatabaseIntegrityCheck.kt:38:39 Type mismatch: inferred type is String? but String was expected
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/Reaper.kt:50:41 Type mismatch: inferred type is String? but String was expected
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/Reaper.kt:68:41 Type mismatch: inferred type is String? but String was expected
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:107:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:122:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:144:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:162:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:181:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:189:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:197:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/db/UpdatesDatabase.kt:208:28 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/launcher/NoDatabaseLauncher.kt:4:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/launcher/NoDatabaseLauncher.kt:61:7 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/launcher/NoDatabaseLauncher.kt:61:17 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/FileDownloader.kt:210:27 'constructor MultipartStream(InputStream!, ByteArray!)' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/Loader.kt:242:13 Type mismatch: inferred type is String? but String was expected
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/Loader.kt:285:7 'when' is exhaustive so 'else' is redundant here
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/Loader.kt:306:65 Type mismatch: inferred type is String? but String was expected
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/LoaderTask.kt:4:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/LoaderTask.kt:350:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/LoaderTask.kt:350:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/LoaderTask.kt:403:105 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/LoaderTask.kt:479:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/loader/LoaderTask.kt:479:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/manifest/EmbeddedUpdate.kt:30:89 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/manifest/ExpoUpdatesUpdate.kt:35:92 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/CheckForUpdateProcedure.kt:4:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/CheckForUpdateProcedure.kt:33:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/CheckForUpdateProcedure.kt:33:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/CheckForUpdateProcedure.kt:131:108 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/CheckForUpdateProcedure.kt:164:108 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/FetchUpdateProcedure.kt:4:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/FetchUpdateProcedure.kt:34:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/FetchUpdateProcedure.kt:34:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/RelaunchProcedure.kt:5:19 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/RelaunchProcedure.kt:11:34 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/RelaunchProcedure.kt:91:5 'AsyncTask<Params : Any!, Progress : Any!, Result : Any!>' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/RelaunchProcedure.kt:91:15 'execute(Runnable!): Unit' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/RelaunchProcedure.kt:118:9 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/RestartReactAppExtensions.kt:6:34 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/RestartReactAppExtensions.kt:15:7 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/StartupProcedure.kt:163:36 'getCurrentState(): UpdatesStateValue' is deprecated. Avoid needing to access current state to know how to transition to next state
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/StartupProcedure.kt:197:34 'getCurrentState(): UpdatesStateValue' is deprecated. Avoid needing to access current state to know how to transition to next state
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/procedures/StateMachineSerialExecutorQueue.kt:43:35 'getCurrentState(): UpdatesStateValue' is deprecated. Avoid needing to access current state to know how to transition to next state
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/main/java/expo/modules/updates/statemachine/UpdatesStateMachine.kt:27:20 This declaration overrides deprecated member but not marked as deprecated itself. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/react-native-74/main/expo/modules/updates/errorrecovery/ErrorRecovery.kt:11:34 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/react-native-74/main/expo/modules/updates/errorrecovery/ErrorRecovery.kt:103:9 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/react-native-74/main/expo/modules/updates/errorrecovery/ErrorRecovery.kt:110:50 Parameter 'devSupportManager' is never used
w: file:///Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/expo-updates/android/src/react-native-74/main/expo/modules/updates/errorrecovery/ErrorRecovery.kt:136:9 'ReactFeatureFlags' is deprecated. Deprecated in Java

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-video:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 32s
851 actionable tasks: 184 executed, 651 from cache, 16 up-to-date
Error: /Users/leonardocavalcante/Projects/bondi-lines/app/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a exited with non-zero code: 1
Error: /Users/leonardocavalcante/Projects/bondi-lines/app/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/Users/leonardocavalcante/Projects/bondi-lines/app/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)
error: script "android" exited with code 1
```

**Comment by beydogan** [comment]
@CavalcanteLeo have you figured this error out? Just added expo-video to the project, ios is fine but android build is failing. I cannot pin point the issue. No error in expo-doctor either.

**Comment by Th1nhNg0** [comment]
> [@CavalcanteLeo](https://github.com/CavalcanteLeo) have you figured this error out? Just added expo-video to the project, ios is fine but android build is failing. I cannot pin point the issue. No error in expo-doctor either.

I have the same issue

**Comment by beydogan** [comment]
Upgrading to Expo SDK 52 fixed for me.
