### ISSUE TITLE
TypeError: fetch failed when starting Expo project

### ISSUE THREAD

**Issue by EzequiasAzanes** [expo/expo#33051]
### Summary

Got an error: TypeError: fetch failed. 2 projects were working smoothly then suddenly it got this error. Created a new expo project to see if the error were gone as it is fresh installed project and no added dependencies or configuration but same error occurred. Been trying to resolve from November 14 - November 18, the error started on November 14th and before that it is working smoothly. Still, no solution after working around it and checking stackoverflow. More details about error logs on my git repo.

### What platform(s) does this occur on?

Android

### SDK Version

52.0.7

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.20.5 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/EzequiasAzanes/MinimalExample.git

**Comment by cheprasov-dev** [comment]
I have the same problem; I encountered it both on version 51 and version 52.

I'm running it via WSL, but the error also occurs on Windows.

![image](https://github.com/user-attachments/assets/2e5381ef-69eb-4953-963e-1da65a90d737)

**Comment by bagus-Arya** [comment]
> I have the same problem; I encountered it both on version 51 and version 52.
> 
> I'm running it via WSL, but the error also occurs on Windows.
> 
> ![image](https://private-user-images.githubusercontent.com/58470356/387692568-2e5381ef-69eb-4953-963e-1da65a90d737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjc4ODYsIm5iZiI6MTczMjA2NzU4NiwicGF0aCI6Ii81ODQ3MDM1Ni8zODc2OTI1NjgtMmU1MzgxZWYtNjllYi00OTUzLTk2M2UtMWRhNjVhOTBkNzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAxNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMDQyZjQxYmFlYTJmMzQyMmNiNDVhZDIyZDJlODk4MGQzMDE0ZmE5NDM3MjVhZTFmODNjOTNjZGU0ZGY3ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S13JXo-WL7uC2-eFKSdlhRtPDhh9vkOFVXCVLpVj-RA)

i think it's bug, when i  `sudo pacman -Syu` on Arch Linux  the error was gone

**Comment by EzequiasAzanes** [comment]
> I have the same problem; I encountered it both on version 51 and version 52.
> 
> I'm running it via WSL, but the error also occurs on Windows.
> 
> ![image](https://private-user-images.githubusercontent.com/58470356/387692568-2e5381ef-69eb-4953-963e-1da65a90d737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTA5ODEsIm5iZiI6MTczMjExMDY4MSwicGF0aCI6Ii81ODQ3MDM1Ni8zODc2OTI1NjgtMmU1MzgxZWYtNjllYi00OTUzLTk2M2UtMWRhNjVhOTBkNzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEzNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDE4YTYxNDBiNDA5NTgzMmVkMTQ1MzFkYjliODg2NTg2MWE4YjhiODkyMjllMTc2OWUyOTJjMzA1ZDk3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8zqaSfvOPEihpVns5sS8HrBM5ujL2_fcAiPAaa85JJ8)

I also have 51 was working smoothly then after a day it just throw an Error. I didn't update or add anything just run it.

**Comment by likeSo** [comment]
Same problem here..
When i launch my fresh-created expo sdk52 project, i got this:
```shell
> vv-party@1.0.0 start
> npx expo start

Starting project at D:\Code\Projects\vv-party
Starting Metro Bundler
(node:2512) [UNDICI-EHPA] Warning: EnvHttpProxyAgent is experimental, expect them to change at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: fetch failed
TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

My env:
```shell
expo-env-info@1.2.1
Ok to proceed? (y) y


  expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.26100
    Binaries:
      Node: 22.11.0 - D:\Applications\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.9.0 - D:\Applications\nodejs\npm.CMD


```

**Comment by bagus-Arya** [comment]
i add ip addr follow this ref https://stackoverflow.com/questions/77032040/fetcherror-request-to-https-api-expo-dev-v2-sdks-49-0-0-native-modules-failed

**Comment by EzequiasAzanes** [comment]
> i add ip addr follow this ref https://stackoverflow.com/questions/77032040/fetcherror-request-to-https-api-expo-dev-v2-sdks-49-0-0-native-modules-failed

I tried adding ip address. It didn't work.
Still, the same error persist on newly created expo project. Also, restarted router. 

```bash
C:\Users\azane>nslookup api.expo.dev
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    api.expo.dev
Addresses:  2606:4700::6812:468
          2606:4700::6812:568
          104.18.4.104
          104.18.5.104


C:\Users\azane>ping api.expo.dev

Pinging api.expo.dev [104.18.4.104] with 32 bytes of data:
Reply from 104.18.4.104: bytes=32 time=184ms TTL=54
Reply from 104.18.4.104: bytes=32 time=186ms TTL=54
Reply from 104.18.4.104: bytes=32 time=187ms TTL=54
Reply from 104.18.4.104: bytes=32 time=187ms TTL=54

Ping statistics for 104.18.4.104:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 184ms, Maximum = 187ms, Average = 186ms

PS C:\Users\azane> Resolve-DnsName api.expo.dev

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
api.expo.dev                                   A      59916 Answer     104.18.4.104
                                                      1
C:\Windows\System32\drivers\etc
host: 104.18.4.104 api.expo.dev
```

**Comment by pedrojluke** [comment]
I have the same issue you mention. The exacly one. None of the mentioned workarounds worked for me on Windows within vs Code

**Comment by luizcarlospedrosogomes** [comment]
removed .env variable HTTP_PROXY

**Comment by EzequiasAzanes** [comment]
> removed .env variable HTTP_PROXY

Newly created blank template no prebuilt .env file.

**Comment by pedrojluke** [comment]
I was able to solve it just moving back to previous expo version.

**Comment by Funiel298** [comment]
> I was able to solve it just moving back to previous expo version.

You used version 51.0.38 or first versions of 52?

**Comment by EzequiasAzanes** [comment]
Was able to run Expo project with version 51.0.28 but SDK 52 still same error. Got errors with sdk 51, 50, 49 earlier but I just switched to higher nodejs LTS version and it is now working.

**Comment by zxyty** [comment]
Add a .env prefile in the project root. and set a var: NODE_TLS_REJECT_UNAUTHORIZED=0
![image](https://github.com/user-attachments/assets/46d82907-4b3a-4500-9b1d-30c126975d79)

**Comment by fsmalaquias** [comment]
> Add a .env file in the project root. and set a var: NODE_TLS_REJECT_UNAUTHORIZED=0 ![image](https://private-user-images.githubusercontent.com/17245817/394760753-46d82907-4b3a-4500-9b1d-30c126975d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NTA3MjAsIm5iZiI6MTczMzk1MDQyMCwicGF0aCI6Ii8xNzI0NTgxNy8zOTQ3NjA3NTMtNDZkODI5MDctNGIzYS00NTAwLTliMWQtMzBjMTI2OTc1ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDIwNTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZGIwZWE2MGJmYWU2OTBiZTY5Mzk4OTQ1NzIwMzNkZjJiYzYwOWU2NmEyM2FkOWMwNDE4MWQ3Y2NiZjY1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aYaeq4_GYHSJIt3qxTlC0U40Gw1NeSu_LrUGIjhdP_A)

This worked for me!

Using VS Code for Mac! 

Thank you

**Comment by RodBr** [comment]
I have the same issue but that didn't work for me, same error

**Comment by EzequiasAzanes** [comment]
Retested Expo SDK 52, now it is working on my end. Didn't need to add .env file on my project with this variable.
```bash
NODE_TLS_REJECT_UNAUTHORIZED=0
```
```bash
node version: 22.11.0
npm version: 10.9.0
```

**Comment by Nemila** [comment]
I think the issue comes from the Network. I had the same issue but when I connect to a different WIFI connexion it works fine after a few retries.

**Comment by fsmalaquias** [comment]
It makes sense.
I was behind the company proxy.



*Flávio Malaquias*
*Coordenador de Desenvolvimento de Sistemas*
*Linkedin: https://www.linkedin.com/in/flavio-malaquias
<https://www.linkedin.com/in/flavio-malaquias>*
*Instagram: @fsmalaquias*


Em dom., 22 de dez. de 2024 às 12:23, Lamine Diamoutene <
***@***.***> escreveu:

**Comment by ianzone** [comment]
same here
```bash
expo install --check
TypeError: fetch failed
TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchWithCredentials (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/api/rest/client.js:91:30)
    at async cachedFetch (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/api/rest/cache/wrapFetchWithCache.js:33:30)
    at async getNativeModuleVersionsAsync (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/api/getNativeModuleVersions.js:17:22)
    at async getVersionedNativeModulesAsync (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/start/doctor/dependencies/bundledNativeModules.js:83:20)
    at async getCombinedKnownVersionsAsync (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/start/doctor/dependencies/getVersionedPackages.js:60:47)
    at async getVersionedDependenciesAsync (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/start/doctor/dependencies/validateDependenciesVersions.js:127:35)
    at async checkPackagesAsync (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/install/checkPackages.js:86:26)
    at async installAsync (/home/ian/templates/rn-template/node_modules/@expo/cli/build/src/install/installAsync.js:114:16)
error: "expo" exited with code 1
```

**Comment by Octagon-simon** [comment]
It's a network error, just switch wifi as suggested by @Nemila and it'll be fine.. I just did and mine was resolved 

you can also try out the other solutions like the env var and upgrading your nodejs version

![image](https://github.com/user-attachments/assets/610aa7f1-7b09-42f3-9a11-f83b0ac7fef8)

**Comment by hooooooouzx** [comment]
> It's a network error, switch wifi as suggested by [@Nemila](https://github.com/Nemila) and it'll be fine... I just did and mine was resolved
> 
> Turn your wifi off then try to run
> 
> ```
> npx expo start
> ```
> 
> if it works with your local address, stop the server then connect your wifi again and rerun the command
> 
> If it doesn't work, you can also try out the other solutions like the env var and upgrading your nodejs version
> 
> ![image](https://github.com/user-attachments/assets/610aa7f1-7b09-42f3-9a11-f83b0ac7fef8)

thanks bro, it works for me.

**Comment by kpothula** [comment]
> NODE_TLS_REJECT_UNAUTHORIZED=0

This worked for me.

**Comment by Caleb2330** [comment]
> > NODE_TLS_REJECT_UNAUTHORIZED=0
> 
> This worked for me.

What is your node version

**Comment by Caleb2330** [comment]
> Add a .env file in the project root. and set a var: NODE_TLS_REJECT_UNAUTHORIZED=0 ![image](https://github.com/user-attachments/assets/46d82907-4b3a-4500-9b1d-30c126975d79)

This worked for me!
node 22.14.0
npm 10.9.2

**Comment by onesamket** [comment]
same issue here

**Comment by TLovers** [comment]
我也有相同的问题，node v20.10.0

**Comment by Aashi1109** [comment]
for me my vpn software was running by simply exiting it worked on expo 52, also due to that vpn software my yarn command was not working too.

**Comment by hammadvu** [comment]
By switching the Wi-Fi connection always works for me.

**Comment by omenmn** [comment]
shouldnt expo uppload there .exe of on there server instead of `https://d1ahtucjixef4r.cloudfront.net/Exponent-2.33.19.apk` whatever this is.

for me i cannot access this server so it shows me the TypeError: fetch failed.

**Comment by omenmn** [comment]
if someone knows how to open a bug related to this issue. please do.

**Comment by a-man-called-q** [comment]
this still happening in 2025

**Comment by Nayan014** [comment]
If you're having trouble getting the dev tools to open, try this:

1. Run your project using:

   ```bash
   npx expo start
   ```

2. In the emulator, press `m` to open the menu.
3. From the menu, select **"Open DevTools"**.

This worked for me — hope it helps!

**Comment by firminkeambou** [comment]
I had the same problem, but at the end of the day, it was just a proxy server,  I switched my internet Connexion and Moved to a connexiont  that didn't required a proxy server, then everything came back to normal. 

it seems as if  "expo" requires you to be connected

**Comment by sainjay** [comment]
Faced the same issue in a corporate network. Switched to a different WiFi to make it work again.

**Comment by igorteixeiradev** [comment]
Use comand `pnpm expo start --offline` for run the project

**Comment by miktae07** [comment]
Use npx expo start --offline worked for me

**Comment by amos-babu** [comment]
> Use npm expo start --offline worked for me

You mean " npx expo start --offline "?

**Comment by miktae07** [comment]
Yes, @amos-babu

**Comment by kitten** [comment]
Expected behaviour that isn't logging properly. The error itself can be ignored and subsequent changes in later SDK versions should be falling back to continuing offline automatically.
cc @byCedric

**Comment by neghi14** [comment]
I just wanted to say turning of my wifi worked for me as well.

**Comment by AliSinaYOusofi** [comment]
Try re-running your project on a different network and it will work. If that did not work turn of your wifi and then run your project it will definitely work.

**Comment by lara1732** [comment]
I had the same error, but I didn't realize that I had a corporate VPN enabled. I disabled it and everything works normally now.

**Comment by chiro79** [comment]
I followed this comment, and it worked for me: https://github.com/expo/expo-cli/issues/2363#issuecomment-659162706

> Hi,
after executing the following commands i was able to resolve this issue.
npm config set strict-ssl false
and
SET NODE_TLS_REJECT_UNAUTHORIZED=0
thanks for the help.
