### ISSUE TITLE
[expo-image][android] useImage causes a native crash when uri is unresolvable

### ISSUE THREAD

**Issue by lovegaoshi** [expo/expo#33115]
### Minimal reproducible example

https://snack.expo.dev/@lovegaoshi/moody-orange-french-fries?platform=android

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

expo-image's useImage hook will cause a native crash on android, if the uri is unresolvable. the linked snack will immediately crash on android, fine on others.

I've googled this and the problem seems to be how one wraps try/catch around a kotlin coroutine, though i cant tell why it doesnt work. anyways, here's [my patch that works for my purposes](https://github.com/lovegaoshi/azusa-player-mobile/blob/dev/patches/expo-image%2B2.0.1.patch).

### Environment

```text
expo 52/snack
```

### Expo Doctor Diagnostics

```text
on snack
```

**Comment by nd-gorm** [comment]
I experience an issue, which might be related?

With latest version of expo (52.0.11) and expo-image (2.0.2) everything works fine in development builds for both ios and Android. However, certain screens crashes on Android 12 in production (works fine on iOS).

I receive the following stacktrace for the crash on Android 12.

`          Fatal Exception: java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
       at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
       at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
       at expo.modules.image.ImageLoadTask$load$2$deferred$1$1.invokeSuspend(ImageLoadTask.kt:30)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)`

**Comment by davidjbng** [comment]
We have seen crashes on all Android devices after upgrading to expo-image v2 with expo sdk 52.
Crashes were only happening in release builds, not in development.

Not sure if those issues are related, but we were using the `useImage` hook before migrating to `react-native` `Image` component to fix the issue.

I can try to create a reproducable example for our crashes if desired.

**Comment by lovegaoshi** [comment]
@lukmccall tysm for the fix, however it seems [the patch at 2.0.3](https://github.com/expo/expo/blob/d18e953971e06c8d7cbc0fb4f31d5883d01894b3/packages/expo-image/CHANGELOG.md?plain=1#L17) didnt resolve this issue. I have [renewed the linked snack to use expo-image 2.0.3](https://snack.expo.dev/@lovegaoshi/moody-orange-french-fries?platform=android) but it still causes a native crush on android.
