### ISSUE TITLE
[expo/fetch] no supporting formData

### ISSUE THREAD

**Issue by wcastand** [expo/expo#33134]
### Minimal reproducible example

https://github.com/wcastand/bug-fetch-form-data

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

Trying to use `expo/fetch` but it seems to not support FormData. getting `[Error: Unsupported FormDataPart implementation]`

docs says compliant to [WinterCG-compliant Fetch API](https://fetch.spec.wintercg.org/)
and from what i can see, it's suppose to support FormData.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.0/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
      Watchman: 2024.08.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.9 => 52.0.9
      expo-router: ~4.0.7 => 4.0.7
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by AntonioRoye** [comment]
You need to add the data property to params.

Change 

```
const params = {
        method: "POST",
        body,
      }
```

to 

```
const params = {
        method: "POST",
        data:body,
      }
```

**Comment by wcastand** [comment]
thanks i didn't know formData wasn't using `body` guessing most lib i used were doing that in the background. thanks will try in work app

**Comment by AntonioRoye** [comment]
@wcastand If you use the global fetch instead of expo/fetch it does use body. Your code works fine if you delete `import {fetch} from "expo/fetch";`

**Comment by wcastand** [comment]
yeah we will probably do that because it's to upload to aws and they don't seem to accept the `data`

**Comment by a-leblond** [comment]
Hi, I don't know if it's a React Native specific format but it's the only format I found that worked for me when trying to upload a file with fetch.

**Comment by a-leblond** [comment]
Unfortunately I couldn't make it work with expo-file-system.

```
await FileSystem.uploadAsync(presignedPost.url, file.uri, {
		fieldName: "file",
		httpMethod: "POST",
		headers: presignedPost.fields,
		uploadType: FileSystem.FileSystemUploadType.MULTIPART,
	})
```

We are using AWS S3 to upload and they keep denying access with this, I tried BINARY_CONTENT also as uploadType.
I can make it work only with fetch for now.

**Comment by Kudo** [comment]
could it be headers related? would be good if you can share corresponding code using fetch? (with multipart and headers)
fwiw, @aleqsio is proposing #33152 for file upload using fetch. that should also help for your case.

**Comment by Wolfleader101** [comment]
> could it be headers related? would be good if you can share corresponding code using fetch? (with multipart and headers) fwiw, @aleqsio is proposing #33152 for file upload using fetch. that should also help for your case.



It seems to be a bug with expo fetch for sure.

```ts
      const blob = new Blob([atob(file)], {
        type: "audio/m4a",
      });

      formData.append("audio", blob, "recording.m4a");

      const res = await fetch(
        "http://xxxxxx",
        {
          method: "POST",
          body: formData,
        }
      );
```

With `import { fetch } from "expo/fetch";` this wont work, but as soon as i comment it out, it works.

**Comment by Kudo** [comment]
@Wolfleader101 `expo/fetch` is not designed to be compatible with react-native's fetch. [the original repro](https://github.com/wcastand/bug-fetch-form-data/blob/979ac8832045db9498b36df6a804d2965afe46ed/app/index.tsx#L36) passing a file uri in FormData is kind of react-native customized feature, and i don't think we should support this feature.

```js
const photot = {
  uri: uriFromCameraRoll,
  type: 'image/jpeg',
  name: 'photo.jpg',
};
const formData = new FormData();
body.append('photo', photo);
```

however passing Blob in your example looks good and aligned with wintercg standard. i can try to add blob support to FormData.

**Comment by a-leblond** [comment]
> could it be headers related? would be good if you can share corresponding code using fetch? (with multipart and headers) fwiw, @aleqsio is proposing #33152 for file upload using fetch. that should also help for your case.

The code used with fetch is :
```
export const uploadFile = async ({
	presignedPost,
	file,
}: { presignedPost: any; file: { name: string; type: string; uri: string } }) => {
	const body = new FormData()
	for (const [field, value] of Object.entries(presignedPost.fields)) {
		body.append(field, value as string)
	}
	body.append("file", file as any)

	const params = {
		method: "POST",
		body,
	}

	return await fetch(presignedPost.url, params)
}
```
`presignedPost.fields` contains the headers for authentication with AWS S3 so I think it should have worked with `FileSystem.uploadAsync` but putting them in `headers` directly, but maybe I'm doing something wrong.

I can still try with https://github.com/expo/expo/pull/33152 as soon as we have it and let you know if it works.

**Comment by Kudo** [comment]
> Yep, form data with blob will be great. Happy to raise a PR for it if you haven't completed it already :)

@Wolfleader101 plan to add the support this week. welcome to send me a pr if my plan is too late for you.

**Comment by Wolfleader101** [comment]
> @Wolfleader101 plan to add the support this week. welcome to send me a pr if my plan is too late for you.

I just took a look, I believe #33152 will fix it :)

**Comment by Wolfleader101** [comment]
@Kudo I believe there is a bug with Blob (I'm not sure if your PR fixed it)

Blobs don't seem to support the new File System Next.

```ts
const file = new File(uri);
const blob = new Blob([file.bytes()], { type: 'audio/m4a' });
```

Gives `[Error: Creating blobs from 'ArrayBuffer' and 'ArrayBufferView' are not supported]`

Also worth noting u need to wrap in try-catch to see that error, otherwise it silently fails 🤔

**Comment by vanstinator** [comment]
I think the new support broke something, I'm seeing errors in unit tests now 

```
│     TypeError: Cannot read properties of undefined (reading 'push')
│ 
│       18 |
│       19 |   Object.entries(fields).forEach(([key, value]) => {
│     > 20 |     formData.append(key, value)
│          |              ^
│       21 |   })
│       22 |
│       23 |   if (Platform.OS === 'web') {
│ 
│       at _FormData.push [as append] (../../node_modules/expo/src/winter/FormData.ts:85:17)
│       at append (src/utils/prepareFileUpload.ts:20:14)
│           at Array.forEach (<anonymous>)
│       at forEach (src/utils/prepareFileUpload.ts:19:26)
│       at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
│       at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
│       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
│       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
│       at apply (src/utils/prepareFileUpload.ts:39:2)
│       at apply (src/utils/prepareFileUpload.ts:3:48)
│       at src/components/fosters/FosterThumbnailEdit.tsx:86:38
│       at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
│       at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
│       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
│       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
│       at apply (src/components/fosters/FosterThumbnailEdit.tsx:60:15)
│       at upload (src/components/fosters/FosterThumbnailEdit.tsx:51:7)
│       at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
│       at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
```

Currently on expo `52.0.18` trying to move to `52.0.23`

**Comment by Kudo** [comment]
@vanstinator would be helpful if you could share a repro project then we can further investigate.

**Comment by vanstinator** [comment]
@Kudo here you go!

https://github.com/vanstinator/expo-formdata-repro

**Comment by aleqsio** [comment]
@vanstinator 

This is how fetch with filesystem next should work:
```
const src = new File(testDirectory, 'file.txt');
const blob = src.blob();

const response = await fetch('https://httpbin.test.k6.io/anything', {
  method: 'POST',
  body: blob,
});
```

If this is not working for you we probably need to publish a new version, but it should be out.

**Comment by vanstinator** [comment]
I'm not having problems with fetch, My app is using `FormData` directly and I'm only seeing the exception i shared when running under jest, the code itself works fine when running in a build.

**Comment by aleqsio** [comment]
Oh, sorry @vanstinator, think I meant to tag @Wolfleader101 instead!

**Comment by a-leblond** [comment]
Update, it works now for me with this code !

```
import { File } from "expo-file-system/next"
import { fetch } from "expo/fetch"

export const uploadFile = async ({
	presignedPost,
	file,
}: { presignedPost: any; file: { name: string; type: string; uri: string } }) => {
	const src = new File(file.uri)
	const body = new FormData()
	for (const [field, value] of Object.entries(presignedPost.fields)) {
		body.append(field, value as string)
	}
	body.append("file", src.blob())

	const params = {
		method: "POST",
		body,
	}

	return await fetch(presignedPost.url, params)
}

```

**Comment by Wolfleader101** [comment]
> @vanstinator
> 
> This is how fetch with filesystem next should work:
> 
> ```
> const src = new File(testDirectory, 'file.txt');
> const blob = src.blob();
> 
> const response = await fetch('https://httpbin.test.k6.io/anything', {
>   method: 'POST',
>   body: blob,
> });
> ```
> 
> Note the `.blob()` which ensures you're not using RN's Blob interface, instead using a native one from FSNext. If this is not working for you we probably need to publish a new version, but it should be out.


`File` doesn't contain a method `.blob()`, so I'm not sure where you are getting that from.
![image](https://github.com/user-attachments/assets/2c5490ee-8bc0-44f7-a36c-bb5ed28c8233)

**Comment by otajor** [comment]
> I think the new support broke something, I'm seeing errors only in unit tests now. Still going over my config, but it's weird that it's _only_ during tests.
> 
> ```
> │     TypeError: Cannot read properties of undefined (reading 'push')
> │ 
> │       18 |
> │       19 |   Object.entries(fields).forEach(([key, value]) => {
> │     > 20 |     formData.append(key, value)
> │          |              ^
> │       21 |   })
> │       22 |
> │       23 |   if (Platform.OS === 'web') {
> │ 
> │       at _FormData.push [as append] (../../node_modules/expo/src/winter/FormData.ts:85:17)
> │       at append (src/utils/prepareFileUpload.ts:20:14)
> │           at Array.forEach (<anonymous>)
> │       at forEach (src/utils/prepareFileUpload.ts:19:26)
> │       at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
> │       at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
> │       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
> │       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
> │       at apply (src/utils/prepareFileUpload.ts:39:2)
> │       at apply (src/utils/prepareFileUpload.ts:3:48)
> │       at src/components/fosters/FosterThumbnailEdit.tsx:86:38
> │       at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
> │       at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
> │       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
> │       at ../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
> │       at apply (src/components/fosters/FosterThumbnailEdit.tsx:60:15)
> │       at upload (src/components/fosters/FosterThumbnailEdit.tsx:51:7)
> │       at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
> │       at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
> ```
> 
> Currently on expo `52.0.18` trying to move to `52.0.23`

I'm seeing the same error going from 52.0.7 to 52.0.25, it's only a problem for me in tests as well. I can't find very much on what  `expo/src/winter/FormData` is or why it's replacing the native fetch.

For now I've fixed it by putting this in my jest setup.ts:
```
class CustomFormData extends FormData {
    _parts: any[] = [];
  }
  global.FormData = CustomFormData;
```

**Comment by bastischulz** [comment]
Same problem on our side.

52.0.18 -> 52.0.19 is breaking our custom Formdata / Blob / File upload.

**Comment by davoam** [comment]
Update: in `expo` version `52.0.39` `FormData.get` works as expected.

**Comment by SleeplessByte** [comment]
Expo `52.0.46`. Before finding this thread, replacement of `fetch` by `expo/fetch` resulted in `Unsupported FormDataPart implementation` spawned in `convertFormData.ts`.

No further explanation is given here or in the docs. The comment above it in the code is:
```javascript
// React Native's FormData is not compatible with the web's FormData
```

The next line with a comment is:

```javascript
// @ts-expect-error: React Native's FormData is not 100% compatible with ours
```

It's possible this has been solved in later versions of either expo or dependencies, but I wanted to post this so people can find it when searching for it.

https://github.com/expo/expo/pull/33152 looks like it should address this exact issue, and that is merged.

For now, I switched back to regular `fetch` whenever uploading formdata.

**Comment by aleqsio** [comment]
@SleeplessByte Does this also happen on SDK53?

**Comment by SleeplessByte** [comment]
@aleqsio I unfortunately have not been able to test / establish that (hence me making no claims about this being present in the newest versions) and don't have the bandwidth to currently test it. The minimally reproducible code is a single fetch with manually created `FormData`.

**Comment by valotas** [comment]
@aleqsio I am on SDK53 and I have the issue

**Comment by fendyk** [comment]
A temp fix for this could be:



```js
import mime from "mime";

const doAFetch = () => {
  const uri = 'path/to/file'
  
  const fileType = mime.getType(uri);
  const fileName = uri.split("/").pop();
  const formData = new FormData();
  formData.append(
  	"file",
  	JSON.stringify({ // Stringify this
  		uri: uri,
  		name: fileName,
  		type: fileType,
  	}),
  );
  
  const res = await fetch('localhost:3000', {
  	headers: {
  		"Content-Type": "multipart/form-data",
  	},
  	method: "POST",
  	body: formData,
  });
}

```

**Comment by axdynx** [comment]
Same here

**Comment by grapevine2383** [comment]
This issue is resolved but solution from this issue overwritten as there is no more File.blob in SDK 54 and you can just pass an expo-file-system File object instead. Use the below to upload files: 

```typescript
import { File } from "expo-file-system/next"
import { fetch } from 'expo/fetch';

const formData = new FormData();
formData.append("file",new File(file.uri));
const res = await fetch('localhost:3000', {method: "POST",body: formData});
```

**Comment by a-leblond** [comment]
I can confirm, it works fine with `expo-fetch` and `expo-file-system` now, in SDK 54

**Comment by Thoobi** [comment]
hi, it seems like i didn't get what the working method is, i tried but kept getting network error from axios, @a-leblond  please can you help me put. i have to use formData to append with axios.

**Comment by taejinii** [comment]
@grapevine2383 it worked for me thx

**Comment by Jamim** [comment]
So what is the correct way to send FormData using Expo SDK 56? 🤔

**Comment by Jamim** [comment]
> This issue is resolved but solution from this issue overwritten as there is no more File.blob in SDK 54 and you can just pass an expo-file-system File object instead. Use the below to upload files:
> 
> ```js
> import { File } from "expo-file-system/next"
> import { fetch } from 'expo/fetch';
> 
> const formData = new FormData();
> formData.append("file",new File(file.uri));
> const res = await fetch('localhost:3000', {method: "POST",body: formData});
> ```

This works in the iOS Simulator, but causes `Property 'ReadabaleStream' doesn't exists` error on a real device using an app installed from TestFlight.

It turns out, you need some additional polyfill-magick in your `index.js`. Something like this:
```js
import 'react-native-url-polyfill/auto';
import { ReadableStream } from 'web-streams-polyfill';

if (!globalThis.ReadableStream) {
  globalThis.ReadableStream = ReadableStream;
}
```

**Comment by jaka-kralj** [comment]
@Jamim 
Have you managed to resolve the issue? I am just experiencing this today, after an upgrade to Expo SDK 56.

**Comment by Billzabob** [comment]
We are also experiencing this issue after our Expo 56 upgrade

**Comment by rklf** [comment]
I'm getting exact same issue after SDK 56 upgrade. How can we workaround that?

**Comment by mjimenez98** [comment]
To anyone affected by the SDK 56 upgrade, I resolved my issue by following the example in [Uploading files using expo/fetch](https://docs.expo.dev/versions/latest/sdk/filesystem/#uploading-files-using-expofetch).

I went from
```ts
formData.append("image", {
  uri: uri,
  type: "image/jpeg",
  name: "image.jpg",
} as any);
```
to
```ts
import { File } from "expo-file-system";

[...]

formData.append("image", new File(uri));
```
