### ISSUE TITLE
`pnpm create expo-module` fails

### ISSUE THREAD

**Issue by mnemitz** [expo/expo#33145]
### Summary

The CLI doesn't let me create an expo-module repo using PNPM

### What platform(s) does this occur on?

MacOS 15.0.1 (24A348)

### SDK Version

create-expo-module@latest

### Environment

```text
N/A (CLI bug)
```

### Minimal reproducible example

node version: 20.17.0
pnpm version: 9.14.2

Run command: `pnpm create expo-module@latest`                                                                                                       

Output:
```
✔ What is the name of the npm package? … my-module
✔ What is the native module name? … MyModule
✔ How would you describe the module? … My new module
✔ What is the Android package name? … expo.modules.mymodule
✔ What is the name of the package author? … Matt Nemitz
✔ What is the email address of the author? … mattn@foo.com
✔ What is the URL to the author's GitHub profile? … mnemitz
✔ What is the URL for the repository? … https://github.com/foo

✔ Downloaded module template from npm
✔ Created the module from template files
✖ Installing module dependencies
Error: pnpm install exited with non-zero code: 1

Error stack:
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@9.14.2+sha512.6e2baf77d06b9362294152c851c4f278ede37ab1eba3a55fda317a4a17b209f4dbb973fb250a77abc463a341fcb1f17f17cfa24091c4eb319cda0d9b84278387.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager

Tried to guess the docs homepage for my-module; add it under the "homepage" entry in package.json
/Users/mattn/.nvm/versions/node/v20.17.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22373
              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);
                    ^

UsageError: This project is configured to use pnpm because /Users/mattn/Projects/my-module/package.json has a "packageManager" field
    at Engine.findProjectSpec (/Users/mattn/.nvm/versions/node/v20.17.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22373:21)
    at async Engine.executePackageManagerRequest (/Users/mattn/.nvm/versions/node/v20.17.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22404:24)
    at async Object.runMain (/Users/mattn/.nvm/versions/node/v20.17.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
  clipanion: { type: 'usage' }
}

Node.js v20.17.0

    at installDependencies (/Users/mattn/Library/Caches/pnpm/dlx/nscvqqxncfckinsuv5avo2hkxq/1934f2d1fd9-d60e/node_modules/.pnpm/create-expo-module@0.8.6/node_modules/create-expo-module/build/packageManager.js:15:15)
    at async /Users/mattn/Library/Caches/pnpm/dlx/nscvqqxncfckinsuv5avo2hkxq/1934f2d1fd9-d60e/node_modules/.pnpm/create-expo-module@0.8.6/node_modules/create-expo-module/build/create-expo-module.js:86:13
    at async newStep (/Users/mattn/Library/Caches/pnpm/dlx/nscvqqxncfckinsuv5avo2hkxq/1934f2d1fd9-d60e/node_modules/.pnpm/create-expo-module@0.8.6/node_modules/create-expo-module/build/utils/ora.js:19:16)
    at async Command.main (/Users/mattn/Library/Caches/pnpm/dlx/nscvqqxncfckinsuv5avo2hkxq/1934f2d1fd9-d60e/node_modules/.pnpm/create-expo-module@0.8.6/node_modules/create-expo-module/build/create-expo-module.js:85:9)
```

**Comment by t1minator** [comment]
I have this error with node 18.18.0

**Comment by aleqsio** [comment]
I tried this using pnpm and node18 and it seems to work fine for me.

```
Work/Expo/helpers took 16.1s 
➜   pnpm create expo-module@latest
 WARN  1 deprecated subdependencies found: @xmldom/xmldom@0.7.13
.../194cc7ca4f0-17014                    | +238 ++++++++++++++++++++++++
.../194cc7ca4f0-17014                    | Progress: resolved 238, reused 0, downloaded 238, added 238, done
? What is the name of the npm package? › my-module(node:94239) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ What is the name of the npm package? … my-module
✔ What is the native module name? … MyModule
✔ How would you describe the module? … My new module
✔ What is the Android package name? … expo.modules.mymodule
✔ What is the name of the package author? … aleqsio
✔ What is the email address of the author? … mikucki@gmail.com
✔ What is the URL to the author's GitHub profile? … aleqsio
✔ What is the URL for the repository? … http://test.com

✔ Downloaded module template from npm
✔ Created the module from template files
✔ Installed module dependencies
✔ Compiled TypeScript files
✔ Initialized the example app
✔ Configured the example app
✔ Prebuilt the example app
✔ Installed dependencies in the example app
✔ Created an empty Git repository

✅ Successfully created Expo module

To start developing your module, navigate to the directory and open iOS and Android projects of the example app
> cd my-module
> pnpm run open:ios
> pnpm run open:android

Learn more on Expo Modules APIs: https://docs.expo.dev/modules
```

**Comment by dhatGuy** [comment]
Experiencing this issue too. I tried bun, yarn and pnpm, none worked. I ended up cloning the tutorial repo.
