### ISSUE TITLE
[SDK52] [expo-updates] android build failure: java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit

### ISSUE THREAD

**Issue by ThaisRobba** [expo/expo#33164]
### Minimal reproducible example

https://github.com/ThaisRobba/expo-update-test

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Fails to build on android with the following stack trace:

```
> Task :expo-updates:kspDebugKotlin FAILED
e: java.io.FileNotFoundException: /Users/thais/Downloads/expo-update-test/node_modules/expo-updates/android/build/generated/source/buildConfig/debug/expo/modules/updates/BuildConfig.java (Operation not permitted)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.loadFileBytes(FileUtil.java:204)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.local.CoreLocalVirtualFile.contentsToByteArray(CoreLocalVirtualFile.java:98)
        at org.jetbrains.kotlin.cli.jvm.index.SingleJavaFileRootsIndex$JavaSourceClassIdReader.<init>(SingleJavaFileRootsIndex.kt:58)
        at org.jetbrains.kotlin.cli.jvm.index.SingleJavaFileRootsIndex.getClassIdsForRootAt(SingleJavaFileRootsIndex.kt:48)
        at org.jetbrains.kotlin.cli.jvm.index.SingleJavaFileRootsIndex.findJavaSourceClasses(SingleJavaFileRootsIndex.kt:44)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.knownClassNamesInPackage(KotlinCliJavaFileManagerImpl.kt:277)
        at org.jetbrains.kotlin.resolve.jvm.KotlinJavaPsiFacade$CliFinder.knownClassNamesInPackage(KotlinJavaPsiFacade.java:545)
        at org.jetbrains.kotlin.resolve.jvm.KotlinJavaPsiFacade.knownClassNamesInPackage(KotlinJavaPsiFacade.java:249)
        at org.jetbrains.kotlin.load.java.JavaClassFinderImpl.knownClassNamesInPackage(JavaClassFinderImpl.kt:68)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope$knownClassNamesInPackage$1.invoke(LazyJavaPackageScope.kt:51)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope$knownClassNamesInPackage$1.invoke(LazyJavaPackageScope.kt:50)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope.findClassifier(LazyJavaPackageScope.kt:141)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope.getContributedClassifier(LazyJavaPackageScope.kt:136)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getContributedClassifier(JvmPackageScope.kt:55)
        at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:35)
        at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:91)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:88)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:681)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getBuiltInClassByName(KotlinBuiltIns.java:223)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getNumber(KotlinBuiltIns.java:293)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getNumberType(KotlinBuiltIns.java:524)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.<init>(ResolverImpl.kt:1144)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:221)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.local/state/fnm_multishells/30562_1732241172521/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.local/state/fnm_multishells/30562_1732241172521/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 31, 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0, 36.0.0
        System Images: android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.10 => 52.0.10 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
❯ npx expo-doctor@latest
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, userInterfaceStyle, splash, ios, android.


One or more checks failed, indicating possible issues with the project.
```

**Comment by brentvatne** [comment]
hi there! i am unable to reproduce this in the project that you shared, the following worked as expected:

```
npx expo run:android
npx expo run:android --variant release
```

try clearing your android build cache.

**Comment by ThaisRobba** [comment]
@brentvatne Aaah, my bad, you are absolutely correct. Clearing `~/.gradle` and invalidating everything in android studio fixed it, thanks ^^
