### ISSUE TITLE
eas build fails while expo run:ios/android works fine

### ISSUE THREAD

**Issue by IlirEdis** [expo/expo#33263]
### Minimal reproducible example

https://github.com/IlirEdis/issue-reproduce

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Running `npx expo run:ios` or `npx expo run:android` the app builds just fine but when deploying with `eas build` it fails with this error:

`npx expo export:embed --eager --platform android --dev false exited with non-zero code: 1`

Here's the whole log from the Bundle Javascript step:

``` bash
Starting Metro Bundler
Android Bundled 40811ms node_modules/expo-router/entry.js (3120 modules)
Exporting server
λ Bundling failed 14031ms node_modules/expo-router/build/static/getServerManifest.js (2826 modules)
Error: Unable to resolve module ../../Utilities/Platform from /home/expo/workingdir/build/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js: 
None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css|.web.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform
  24 |
  25 | const {findNodeHandle} = require('../../ReactNative/RendererProxy');
> 26 | const Platform = require('../../Utilities/Platform');
     |                           ^
  27 | const React = require('react');
  28 | type ComponentRef = React.ElementRef<HostComponent<mixed>>;
  29 |
Error: Unable to resolve module ../../Utilities/Platform from /home/expo/workingdir/build/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js: 
None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css|.web.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform
  24 |
  25 | const {findNodeHandle} = require('../../ReactNative/RendererProxy');
> 26 | const Platform = require('../../Utilities/Platform');
     |                           ^
  27 | const React = require('react');
  28 | type ComponentRef = React.ElementRef<HostComponent<mixed>>;
  29 |
    at ModuleResolver.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:235:43)
    at /home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:160:21
    at resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 4)
    at visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
npx expo export:embed --eager --platform android --dev false exited with non-zero code: 1

```

I tried deleting `node_modules` and i also added `/ios` and `/android` folders to `.gitignore` so eas can create fresh ones but nothing worked.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - /usr/local/bin/node
      npm: 10.9.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 30, 35
        Build Tools: 30.0.3, 34.0.0, 35.0.0
    IDEs:
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.7 => 52.0.11 
      expo-router: ~4.0.6 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.10 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.4.2
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check native tooling versions
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: orientation, scheme, icon, userInterfaceStyle, splash, ios, android, plugins. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: lucide-react-native
No metadata available: @google-cloud/vertexai, @hookform/resolvers, base64-arraybuffer, stripe, tailwindcss
Advice: 
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by agendartdelucca** [comment]
I am facing the same issue. I just updated my local eas cli and run: 

`npx expo export:embed --help `

Then on the output is shown that the eager option does exist: 
`--eager  Eagerly export the bundle with default options`

I have just upgraded to Expo SDK 52 and my app run smoothly on my local environment.

Is there any update on this issue?

**Comment by johannbuscail** [comment]
Any update ?

**Comment by Aakash074** [comment]
Facing same issue. Any update ?

**Comment by fabdrol** [comment]
I'm running into this as well

**Comment by brentvatne** [comment]
@IlirEdis - I had a look at the logs for the reproducible example that you shared, it seems that this is related to using [server exports with Metro](https://github.com/IlirEdis/issue-reproduce/blob/e8da4cc90a29e059e68a35caff8e727bf6e3ae47/app.json#L27-L31) and not having react-native-web installed. I've added an annotation on EAS Build with information on how to resolve (`npx expo install react-native-web`):

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/9f45fa72-1d7a-4f05-8ab8-5a4b7daf3320">

**Comment by IlirEdis** [comment]
@brentvatne , Thanks for the response!

I checked in my other project and i already have `react-native-web` installed. 
I updated all the packages with `npx expo install --fix`, i tried it and it failed again, until i set `"output": "static"`, then it finished building properly. 

Tbh, i forgot why i set output to server (maybe its the default setting) but does this need further investigation why it fails when it is set to server?

**Comment by u2gilles** [comment]
Same issue here.

**Comment by Ademola101** [comment]
What's is the solution to this?

**Comment by Ademola101** [comment]
> @brentvatne , Thanks for the response!
> 
> 
> 
> I checked in my other project and i already have `react-native-web` installed. 
> 
> I updated all the packages with `npx expo install --fix`, i tried it and it failed again, until i set `"output": "static"`, then it finished building properly. 
> 
> 
> 
> ~~Tbh, i forgot why i set output to server (maybe its the default setting)~~ I set it to `server` so i can use API routes. Does this need further investigation why it fails when it is set to server? 

Where did you set this output as static? Which file?

**Comment by IlirEdis** [comment]
@Ademola101 `app.json`

```JSON
"expo": {
   "web": {
         "output": "static",
       },
}
```

**Comment by Ademola101** [comment]
> @Ademola101 `app.json`
> 
> 
> 
> ```JSON
> 
> "expo": {
> 
>    "web": {
> 
>          "output": "static",
> 
>        },
> 
> }
> 
> ```

Thanks. In my case nativewind was the issue. I had to remove it.

**Comment by ahmedibra28** [comment]
> "web": {
> 
>          "output": "static",
> 
>        },

I have the same issue and I'm using Nativewind so how did you fix it or you removed it totally from the app?

**Comment by michaelAngelo1** [comment]
Hi, I have the same issue as well. In my case, the error is

![Image](https://github.com/user-attachments/assets/7ba43056-0b27-42f6-a0e3-708639fe577a)

I have set the web output to static on **app.json**. I have also tried updating the packages with **npx expo install --fix**, which seems to be the issue on the build details, but to no avail. 

This has been going on for months. I thought expo would fix this so I just tried rebuilding every other week, still the same issue came up.

Any detailed help would be so much appreciated. 🙏

**Comment by Ademola101** [comment]
> > "web": {
> > 
> >          "output": "static",
> > 
> >        },
> 
> I have the same issue and I'm using Nativewind so how did you fix it or you removed it totally from the app?

I removed it totally

**Comment by michaelAngelo1** [comment]
@Ademola101 


> > > "web": {
> > > ```
> > >      "output": "static",
> > > 
> > >    },
> > > ```
> > 
> > 
> > I have the same issue and I'm using Nativewind so how did you fix it or you removed it totally from the app?
> 
> I removed it totally

Hi @Ademola101 Apology if it is a dumb question: would removing Nativewind also remove all the styling applied in the app? I need the styling to remain applied. Thanks!

**Comment by zyncc** [comment]
![Image](https://github.com/user-attachments/assets/fa48d812-0bc3-45db-b247-d29132ffb39f)

i have the same issue. my build was literally working an hour ago and suddenly i got this issue

**Comment by techwithtwin** [comment]
Facing same issue with native wind

**Comment by DelfimCelestino** [comment]
"web": {
      "bundler": "metro",
      "output": "static",
    },

**Comment by DarioBanno** [comment]
> [@Ademola101](https://github.com/Ademola101) `app.json`
> 
> "expo": {
>    "web": {
>          "output": "static",
>        },
> }

Had the same issue with Stripe not building for iOS using Expo. This fixed it!! 👏👏👏

**Comment by Grealishgit** [comment]
but stripe wont work in static mode well

**Comment by Grealishgit** [comment]
> > [@Ademola101](https://github.com/Ademola101) `app.json`
> > "expo": {
> > "web": {
> > "output": "static",
> > },
> > }
> 
> Had the same issue with Stripe not building for iOS using Expo. This fixed it!! 👏👏👏

Is Your stripe working well though??

**Comment by zaini** [comment]
This is a bad fix that goes against the docs. When using Expo API Routes, you need output to be set to `server`.

```
  "web": {
    "output": "server"
  }
```

https://docs.expo.dev/router/reference/api-routes/#create-an-api-route

Any suggestions @brentvatne ?  I already have `"react-native-web": "^0.20.0"

```
yarn run v1.22.22
$ /Users/expo/workingdir/build/node_modules/.bin/expo export:embed --eager --platform ios --dev false
Starting Metro Bundler
iOS node_modules/expo-router/entry.js ▓▓▓▓▓▓▓░░░░░░░░░ 49.2% (490/713)
iOS node_modules/expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓░░░ 84.3% (1308/1425)
iOS node_modules/expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.9% (1595/1596)
iOS node_modules/expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.9% (1596/1596)
iOS node_modules/expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.9% (3306/3306)
iOS Bundled 15424ms node_modules/expo-router/entry.js (3306 modules)
Exporting server
λ node_modules/expo-router/build/static/getServerManifest.js ▓▓▓▓▓▓▓▓▓▓▓▓▓░░░ 84.9% (2501/2714)
| Dynamic import at line 108: require(s). This module may not work as intended when deployed to a runtime.
λ Bundling failed 4594ms node_modules/expo-router/build/static/getServerManifest.js (3021 modules)
Unable to resolve module ../Utilities/Platform from /Users/expo/workingdir/build/node_modules/react-native/Libraries/ReactNative/BridgelessUIManager.js: 

None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css|.web.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform
[0m [90m 16 |[39m [36mimport[39m {unstable_hasComponent} [36mfrom[39m [32m'../NativeComponent/NativeComponentRegistryUnstable'[39m[33m;[39m
 [90m 17 |[39m [36mimport[39m defineLazyObjectProperty [36mfrom[39m [32m'../Utilities/defineLazyObjectProperty'[39m[33m;[39m
[31m[1m>[22m[39m[90m 18 |[39m [36mimport[39m [33mPlatform[39m [36mfrom[39m [32m'../Utilities/Platform'[39m[33m;[39m
 [90m    |[39m                       [31m[1m^[22m[39m
 [90m 19 |[39m [36mimport[39m {getFabricUIManager} [36mfrom[39m [32m'./FabricUIManager'[39m[33m;[39m
 [90m 20 |[39m [36mimport[39m nullthrows [36mfrom[39m [32m'nullthrows'[39m[33m;[39m
 [90m 21 |[39m[0m
Error: Unable to resolve module ../Utilities/Platform from /Users/expo/workingdir/build/node_modules/react-native/Libraries/ReactNative/BridgelessUIManager.js: 

None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css|.web.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform
[0m [90m 16 |[39m [36mimport[39m {unstable_hasComponent} [36mfrom[39m [32m'../NativeComponent/NativeComponentRegistryUnstable'[39m[33m;[39m
 [90m 17 |[39m [36mimport[39m defineLazyObjectProperty [36mfrom[39m [32m'../Utilities/defineLazyObjectProperty'[39m[33m;[39m
[31m[1m>[22m[39m[90m 18 |[39m [36mimport[39m [33mPlatform[39m [36mfrom[39m [32m'../Utilities/Platform'[39m[33m;[39m
 [90m    |[39m                       [31m[1m^[22m[39m
 [90m 19 |[39m [36mimport[39m {getFabricUIManager} [36mfrom[39m [32m'./FabricUIManager'[39m[33m;[39m
 [90m 20 |[39m [36mimport[39m nullthrows [36mfrom[39m [32m'nullthrows'[39m[33m;[39m
 [90m 21 |[39m[0m
Error: Unable to resolve module ../Utilities/Platform from /Users/expo/workingdir/build/node_modules/react-native/Libraries/ReactNative/BridgelessUIManager.js: 

None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css|.web.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform
[0m [90m 16 |[39m [36mimport[39m {unstable_hasComponent} [36mfrom[39m [32m'../NativeComponent/NativeComponentRegistryUnstable'[39m[33m;[39m
 [90m 17 |[39m [36mimport[39m defineLazyObjectProperty [36mfrom[39m [32m'../Utilities/defineLazyObjectProperty'[39m[33m;[39m
[31m[1m>[22m[39m[90m 18 |[39m [36mimport[39m [33mPlatform[39m [36mfrom[39m [32m'../Utilities/Platform'[39m[33m;[39m
 [90m    |[39m                       [31m[1m^[22m[39m
 [90m 19 |[39m [36mimport[39m {getFabricUIManager} [36mfrom[39m [32m'./FabricUIManager'[39m[33m;[39m
 [90m 20 |[39m [36mimport[39m nullthrows [36mfrom[39m [32m'nullthrows'[39m[33m;[39m
 [90m 21 |[39m[0m
    at ModuleResolver.resolveDependency (/Users/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (/Users/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:239:43)
    at /Users/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:165:21
    at resolveDependencies (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at visit (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 2)
    at visit (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Lysander086** [comment]
> [@Ademola101](https://github.com/Ademola101) `app.json`
> 
> "expo": {
>    "web": {
>          "output": "static",
>        },
> }

HI , this doesn't fix my error.

log: 
```log
Web Bundling failed 1031ms index.ts (774 modules)
Unable to resolve "../Utilities/Platform" from "node_modules/react-native/Libraries/ReactNative/BridgelessUIManager.js"
```

# My solution
- to fix the above error, I used command 
```shell
npx expo install --fix

```

**Comment by lucasoliveirabr** [comment]
### Another possible solution:
In my case, none of the solutions above solved the issue. The problem was a missing dependency required in `app.json` as a plugin (expo-secure-store). Please do check this.

**Comment by willeswa** [comment]
When NODE_ENV is set to production, devDependencies are not installed. If your production build relies on a package that is mistakenly categorized as a devDependency, it won't be available during the build.
Ensure all necessary packages for your production build are listed as dependencies in your package.json, not devDependencies.
