### ISSUE TITLE
`jest-expo` missing native modules in SDK 52

### ISSUE THREAD

**Issue by elyobo** [expo/expo#33342]
### Minimal reproducible example

n/a

### Where did you reproduce the issue?

in a development build

### Summary

`jest-expo` is missing mocks that were available in earlier versions. This looks similar to https://github.com/expo/expo/issues/26893 which was for SDK 50 which was resolved in https://github.com/expo/expo/pull/26931 with @aleqsio noting that the mocks hadn't been regenerated; perhaps the same has happened again?

```
    Cannot find native module 'ExpoNotificationChannelManager'

      1 | import { getInitialURL } from 'expo-linking'
    > 2 | import { getLastNotificationResponseAsync } from 'expo-notifications'
        | ^
      3 | import { router } from 'expo-router'
      4 | import { useEffect, useState } from 'react'
      5 |

      at Object.requireNativeModule (node_modules/expo-modules-core/src/requireNativeModule.ts:17:11)
      at requireNativeModule (node_modules/jest-expo/src/preset/setup.js:249:71)
      at requireMockModule (node_modules/jest-expo/src/preset/setup.js:271:24)
      at Object.<anonymous> (node_modules/expo-notifications/src/NotificationChannelManager.native.ts:5:35)
      at Object.require (node_modules/expo-notifications/src/getNotificationChannelsAsync.android.ts:3:1)
      at Object.require (node_modules/expo-notifications/src/index.ts:21:1)
 ```

As per https://github.com/expo/expo/issues/26893, adding in the missing modules manually resolves things.

```diff
--- node_modules/jest-expo/src/preset/expoModules.js	2024-12-02 14:11:16
+++ patched.js	2024-12-02 14:11:12
@@ -425,6 +425,12 @@
           },
           { name: 'requestPermissionsAsync', argumentsCount: 1, key: 'requestPermissionsAsync' },
           { name: 'saveToLibraryAsync', argumentsCount: 1, key: 'saveToLibraryAsync' },
+        ],
+        ExpoNotificationChannelManager: [
+          // Missing
+        ],
+        ExpoNotificationChannelGroupManager: [
+          // Missing
         ],
         ExponentAccelerometer: [
           { name: 'isAvailableAsync', argumentsCount: 0, key: 'isAvailableAsync' },
```

I also note that the specific method I'm using here, `getLastNotificationResponseAsync`, is present in the file but under `ExpoNotificationsEmitter` instead...

```js
        ExpoNotificationsEmitter: [
          { name: 'getLastNotificationResponseAsync', argumentsCount: 0, key: 0 },
        ],
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.11 => 52.0.11
      expo-router: ~4.0.9 => 4.0.9
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: ^0.76.3 => 0.76.3
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 13.4.2
    Expo Workflow: managed
```
```


### Expo Doctor Diagnostics

```text
No repro provided and does not appear to be relevant in this case.
```

**Comment by elyobo** [comment]
bump

**Comment by elyobo** [comment]
@aleqsio  @brentvatne I'd be happy to open a PR like https://github.com/expo/expo/pull/26931 to bring the mocks up to date again but I'm not sure how to regenerate them, is that documented somewhere?

**Comment by brentvatne** [comment]
@aleqsio - can you help out @elyobo here?

**Comment by aleqsio** [comment]
Hi @elyobo – here are the docs for this:
https://docs.expo.dev/modules/mocking/#automatic-generation-of-mocks

Let me know if you need more help!

**Comment by elyobo** [comment]
Thanks; I had actually stumbled across that when looking into this but it sounds like it's targeted at module authors generating mocks for their own packages, which would presumably be provided with the package - these mocks are in `jest-expo`, which is not itself a native module and which has these mocks set up in `src/preset/expoModules.js`, not in `mocks` directory in which this tool says it'll create them.

I thought to pull down `expo/expo` and generate mocks on a package basis then try copying them over to the presets, but I'm unable to get anything running at all that way (bunch of different errors with the current `main` branch, can't even `npm i`, `npx expo-modules-test-core generate-ts-mocks` results in a not found error, globally installing fixes that but leads to more issues...) - is this the expected route?

**Comment by aleqsio** [comment]
Oh, in this case you're looking for this guide:
https://github.com/expo/expo/blob/main/guides/Generating%20Jest%20Mocks.md

The problem is this requires running expo-go which is pretty painful – on the SDK-52 branch for instance I'm running into issues right now.

**Comment by elyobo** [comment]
I was unable to follow the guide earlier, but will take a look again now that we're on 53,  maybe it's working again.

Note that this is mitigated by https://github.com/expo/expo/pull/36839, but the mocks are still missing at this point (and the patch above no longer applies at least in part because the file has moved).

**Comment by elyobo** [comment]
Apologies for not coming back on this sooner; the missing mocks seem to have been resolved in expo/jest-expo 53 and we were able to remove the patch described in the original issue description once we'd done that upgrade, closing.
