### ISSUE TITLE
CI=TRUE fails with TRUE is not a boolean.

### ISSUE THREAD

**Issue by fdstevex** [expo/expo#33486]
### Summary

Attempting to build an Expo app using Xcode Cloud, but the build fails with this error:

    GetEnv.NoBoolean: TRUE is not a boolean.

This is because Expo looks for a "CI" environment variable, but uses the `boolish` package to convert it into a boolean, and `boolish` does a case sensitive comparison.

To reproduce:

    CI=TRUE npx expo prebuild

"So set the environment variable correctly" you say.  That's a reasonable request.  Problem is, with Xcode Cloud, the CI variable is set by the environment before the build is run.  Attempting to override it in the UI is disallowed because it's a reserved name.  

Attempting to override it in a [custom build script](https://developer.apple.com/documentation/xcode/writing-custom-build-scripts) works for the initial `expo prebuild` but then later, during the actual Xcode compile during the "Bundle React Native code and images" phase, the error occurs again and I haven't been able to find a way to work around it there.

### What platform(s) does this occur on?

iOS

### SDK Version

52.0.11

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 3.6.1 - ~/.nvm/versions/node/v18.14.0/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
      Watchman: 2024.10.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.9 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: bare
```
```


### Minimal reproducible example

In an Expo project, do this:

        CI=TRUE npx expo prebuilt

You should see:

```
Error: GetEnv.NoBoolean: TRUE is not a boolean.
Error: GetEnv.NoBoolean: TRUE is not a boolean.
    at Object.boolish (/Users/stevex/src/cloudmd/kiimobile/node_modules/getenv/index.js:70:15)
    at /Users/stevex/src/cloudmd/kiimobile/node_modules/getenv/index.js:84:27
    at Env.CI (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/utils/env.ts:40:19)
    at isInteractive (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/utils/interactive.ts:5:15)
    at ora (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/utils/ora.ts:27:34)
    at logNewSection (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/utils/ora.ts:97:19)
    at cloneTemplateAndCopyToProjectAsync (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/prebuild/updateFromTemplate.ts:106:28)
    at updateFromTemplateAsync (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/prebuild/updateFromTemplate.ts:59:94)
    at prebuildAsync (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/prebuild/prebuildAsync.ts:91:34)
```

**Comment by fdstevex** [comment]
This is the problem:

```
  /** Is running in non-interactive CI mode */
  get CI() {
    return boolish('CI', false);
  }
```

From [cli/src/utils/env.ts](https://github.com/expo/expo/blob/b85c7db8c8c14bec6a209c25f720ac1baaa625b8/packages/%40expo/cli/src/utils/env.ts#L38).

It's not pretty but one fix would be to treat the CI variable differently from the rest and actually get it and lowercase it before converting it to a bool.

**Comment by cervere** [comment]
Hi, facing the same issue. Previously a different app was working with `CI="true" npx expo prebuild`. 

But I started a new app with latest react-native / expo setup, with the line above in ci_post_clone, but I still get the `GetEnv.NoBoolean: TRUE is not a boolean.` 

Thanks for any pointers!

**Comment by cervere** [comment]
Hi, was curious if there was any update on this? Thanks!

**Comment by brentvatne** [comment]
related: https://github.com/ctavan/node-getenv/pull/22

**Comment by nkat2112** [comment]
> related: [ctavan/node-getenv#22](https://github.com/ctavan/node-getenv/pull/22)
> 
> you can work around this by applying this patch to your node_modules with patch-package.

This approach is certainly the right way to go - thank you @brentvatne . And thanks to @fdstevex for pointing out this stack trace when building on the Xcode cloud. I ran into the same issue.

Unfortunately, the patch presently shown in the pull request that you reference, @brentvatne , will not - I believe - work as it is. I applied the same approach to this fix to the "boolish" method (as shown in @fdstevex 's error stack trace) and then it finally worked for me on the Xcode cloud. (As the PR, as it currently stands, only corrects such a case-sensitivity issue on the "bool" method.)

I added a comment to the open pull request to explain how I resolved this in my case:

https://github.com/ctavan/node-getenv/pull/22

Please let me know if I'm misunderstanding anything or if I made any errors. Thank you all!

**Comment by stephenlacy** [comment]
It seems that the latest/next version of expo will not have this issue as `node-getenv` has been removed: https://github.com/search?q=repo%3Aexpo%2Fexpo%20node-getenv&type=code

**Comment by BenjDrury** [comment]
I am experiencing the same issue on one of the latest version of @expo! Patching it with the solution @brentvatne mentioned for me is kind of a bad solution. Any other solutions flying around?

**Comment by stephenlacy** [comment]
@BenjDrury there are several moving components in expo, from the cli (global vs local) to metro, package-manager, etc. The  file requiring `node-getenv` seems to have been changed 2 years ago -- I'm assuming one of your dependencies may still be using the older expo package.
The patch should not be required with the latest release (I am the author of the pr/patch to node-getenv)
Can you list out your entire dependency tree and check to see which package is loading node-getenv? For example with pnpm: `pnpm list --depth 100`

**Comment by stephenlacy** [comment]
@brentvatne I can send a PR to either:
- Change `node-getenv` to a new published npm package with the patch
- Add the boolish function to utils/env.ts 
- Add a new @expo/ package called `getenv`

Let me know which you/expo would prefer

**Comment by brentvatne** [comment]
@byCedric - not sure if you have a preference here. i suspect we probably want to create a new `@expo/getenv` package so that we can be sure we reuse the same env logic in other package as well, such as in eas cli.

**Comment by imrankhanpersonalai** [comment]
I have the same issue on react native expo. I would love to see a proper fix for that instead of the patch.

**Comment by stephenlacy** [comment]
@brentvatne the PR with the fixes for getenv was merged https://github.com/ctavan/node-getenv/pull/22 and getenv was published to 2.0.0

I opened PRs for expo + expo/atlas:
- https://github.com/expo/expo/pull/36688
- https://github.com/expo/atlas/pull/82

**Comment by byCedric** [comment]
@stephenlacy your PRs have been applied to main and it's queued for release. Any version after `expo@53.0.9` should have this fix included.

**Comment by stephenlacy** [comment]
@byCedric Thanks for reviewing/merging!
