### ISSUE TITLE
Environment variables from .env is not always loaded when app.config.js is loaded

### ISSUE THREAD

**Issue by JoelYourstone** [expo/expo#33483]
### Summary

**Config from `app.config.js` is sometimes read before we have proper env variables, potentially causing issues**

The code that loads env variables from `.env` : https://github.com/expo/expo/blob/c13b3e2b34a81a578e4243a3cef6b175eb037a7f/packages/%40expo/cli/src/start/startAsync.ts#L72
is run **after** we've run `resolveOptionsAsync` : https://github.com/expo/expo/blob/c13b3e2b34a81a578e4243a3cef6b175eb037a7f/packages/%40expo/cli/src/start/index.ts#L86

And **if you are marked as a dev client**, the call to `resolveSchemeAsync` inside `resolveOptionsAsync` will ultimately read from the `app.config.js` file via this call stack:
```
at exports.default (C:\Projects\ExpoEnvRepro\app.config.js:4:11)
at resolveConfigExport (C:\Projects\ExpoEnvRepro\node_modules\@expo\config\build\evalConfig.js:152:14)
at evalConfig (C:\Projects\ExpoEnvRepro\node_modules\@expo\config\build\evalConfig.js:92:10)
at readConfigFile (C:\Projects\ExpoEnvRepro\node_modules\@expo\config\build\getConfig.js:45:41)
at getDynamicConfig (C:\Projects\ExpoEnvRepro\node_modules\@expo\config\build\getConfig.js:54:18)
at getConfig (C:\Projects\ExpoEnvRepro\node_modules\@expo\config\build\Config.js:280:43)
at getManagedDevClientSchemeAsync (C:\Projects\ExpoEnvRepro\node_modules\@expo\cli\build\src\utils\scheme.js:159:46)
at getOptionalDevClientSchemeAsync (C:\Projects\ExpoEnvRepro\node_modules\@expo\cli\build\src\utils\scheme.js:181:27)
at async resolveSchemeAsync (C:\Projects\ExpoEnvRepro\node_modules\@expo\cli\build\src\start\resolveOptions.js:90:32)
at async resolveOptionsAsync (C:\Projects\ExpoEnvRepro\node_modules\@expo\cli\build\src\start\resolveOptions.js:60:20
```

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 22.8.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~52.0.15 => 52.0.15
      expo-router: ~4.0.11 => 4.0.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/JoelYourstone/ExpoEnvRepro

# Easy steps to reproduce without above repo 👇 
1. `npx create-expo-app@latest ExpoEnvRepro`
2. `cd ExpoEnvRepro`
3. `npm install expo-dev-client`
4. Add the following `app.config.js` file:
```
export default ({ config }) => {
  if (!process.env.TEST_ENV) {
    throw new Error("TEST_ENV is not set");
  }
  return config;
};

```
5. Add the following `.env` file:
```
TEST_ENV=true
```
6. `npx expo start`

### Expected results
It starts without issues, since we have set TEST_ENV

### Actual results
Error("TEST_ENV is not set")

**Comment by chenweigh** [comment]
try add line to package.json, and npm run dev: 
```json
"scripts": {
    "dev": "APP_VARIANT=development npx expo start",
  }
```

**Comment by JoelYourstone** [comment]
> try add line to package.json, and npm run dev:
> 
> ```json
> "scripts": {
>     "dev": "APP_VARIANT=development npx expo start",
>   }
> ```

Good shout We have already a workaround in place (code that ensures env vars are loaded from the config file). But I still think this is a de-facto bug that might be good to know. To not fall into the same rabbit hole I fell into 😅
