### ISSUE TITLE
TypeError: commands[command] is not a function

### ISSUE THREAD

**Issue by 1cedsoda** [expo/expo#33650]
### Summary
I upgraded another project's SDK to 52 and got an error.
As a minimal working example, I created a fresh app with `create-expo-app` and the error shows again without configuration when I try to run on Expo Go on Android or iOS.

```
pnpm expo
Starting project at /Users/redacted/code/somefilder/my-app
Starting Metro Bundler
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █ ██▀▀█▀▄██ ▄▄▄▄▄ █
█ █   █ █  ▀█ ▀█ ██ █   █ █
█ █▄▄▄█ █▀  █▄▀▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█▄█▄█▄▄▄▄▄▄▄█
█▄ ▀▀▄▄▄▀▀█▄█▄▀▄ ███ ▀▄▄ ▄█
█ █▀▀▀█▄▄  ▄█▀██  ▀ █▄  ▀██
█ █▀▀▄ ▄  ▀▀▄▀█▄▀▄▀▄▀▀▄ ▀██
███▀  ▄▄▀█ ▄ ▄██ ▀ ▀ ▄ ▀███
█▄▄█▄██▄▄ ▄██▄▀▄▀ ▄▄▄ ▀ ▄▄█
█ ▄▄▄▄▄ █▀▄██▀█▀▀ █▄█ ▀▀▀▀█
█ █   █ █▄▀ ▄▀▄ █ ▄ ▄▄▀   █
█ █▄▄▄█ █▀▀  ▄ ▄▀█▀▄▀█▀▀ ██
█▄▄▄▄▄▄▄█▄█▄█▄▄████▄▄▄▄▄▄▄█

› Metro waiting on exp://172.20.10.4:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:8081

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› shift+m │ more tools
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on iOS...
› Opening exp://172.20.10.4:8081 on iPhone 15 Pro
› Press ? │ show all commands
Error: /Users/redacted/node_modules/expo-updates/build-cli/cli.js:46
commands[command]().then((exec) => exec(commandArgs));
                 ^

TypeError: commands[command] is not a function
    at Object.<anonymous> (/Users/redacted/node_modules/expo-updates/build-cli/cli.js:46:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/redacted/node_modules/expo-updates/bin/cli.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.18.2

› Opening on Android...
› Opening exp://172.20.10.4:8081 on Pixel_3a_API_34_extension_level_7_arm64-v8a
› Press ? │ show all commands
Error: /Users/redacted/node_modules/expo-updates/build-cli/cli.js:46
commands[command]().then((exec) => exec(commandArgs));
                 ^

TypeError: commands[command] is not a function
    at Object.<anonymous> (/Users/redacted/node_modules/expo-updates/build-cli/cli.js:46:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/redacted/node_modules/expo-updates/bin/cli.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.18.2
```

package.json
```json
{
  "name": "my-app",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "expo": "~52.0.18",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.3",
    "expo-router": "4.0.11",
    "expo-splash-screen": "~0.29.18",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.6",
    "expo-web-browser": "~14.0.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.5",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },
  "private": true
}
```

### SDK Version

52.0.18

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 30.0.3, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.18 => 52.0.18
      expo-router: 4.0.11 => 4.0.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 7.0.0
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Minimal reproducible example

1. `pnpx create-expo-app@latest`
2. cd <project>
3. `pnpm i`
4. `pnpm expo install --fix`
5. `pnpm expo` > i > a

**Comment by 1cedsoda** [comment]
I created an SDK 51 expo app with `pnpx create-expo-app MyApp --template default@sdk-51` and it works as expected on my devices. Something's off with SDK 52 or `create-expo-app`.

**Comment by byCedric** [comment]
hi @1cedsoda! Thanks for reporting this issue. Is it possible to create a repro with the state of the project (right after creating it through `pnpx create-expo-app@latest` and `pnpm i`)? I've tried to reproduce this issue, and it didn't result in any errors.

The weird thing here is that it seems to install `expo-updates` for you, which it shouldn't do automatically. This should only be there when installing `expo-updates` manually as a project dependency. So that's something I'd love to figure out.

**Comment by 1cedsoda** [comment]
@byCedric https://github.com/1cedsoda/expo-issue-33650

**Comment by 1cedsoda** [comment]
Solved the issue by uninstalling `expo-updates` from my global node_modules.

```bash
rm -rf ~/node_modules/expo-updates
```

The question is how did it get there? Does it get installed when upgrading an expo SDK? I recently upgraded a project from SDK 51 to 52.
