### ISSUE TITLE
Error when fingerprint reads from expo config file

### ISSUE THREAD

**Issue by JoelYourstone** [expo/expo#33798]
### Minimal reproducible example

https://github.com/JoelYourstone/ExpoFingerprintStdoutRepro

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app, on web

### Summary

The issue is that fingerprint console logs a stringified config and then reads that directly from `stdout`, which might make it include other things than just the stringified config, e.g. if you have a `app.config.js` and you have any `console.log` in it.

## How to reproduce easily
1. Create a new expo project, e.g. `npx create-expo-app@latest ExpoFingerprintStdoutRepro`
1. Rename app.json to app.config.js and default export the entire object.
1. Add a `console.log("Modify stdout");` in app.config.js
1. Run `npx @expo/fingerprint .` in root of the project

### Expected result
Default fingerprint output

### Actual result
```
Cannot get Expo config from an Expo project - Unexpected token 'M', "Modify std"... is not valid JSON:  SyntaxError: Unexpected token 'M', "Modify std"... is not valid JSON
    at JSON.parse (<anonymous>)
    at getExpoConfigSourcesAsync (C:\tempo\ExpoFingerprintStdoutRepro\node_modules\@expo\fingerprint\build\sourcer\Expo.js:34:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 2)
    at async getHashSourcesAsync (C:\tempo\ExpoFingerprintStdoutRepro\node_modules\@expo\fingerprint\build\sourcer\Sourcer.js:25:21)
    at async createFingerprintAsync (C:\tempo\ExpoFingerprintStdoutRepro\node_modules\@expo\fingerprint\build\Fingerprint.js:14:21)
    at async runLegacyCLIAsync (C:\tempo\ExpoFingerprintStdoutRepro\node_modules\@expo\fingerprint\cli\build\runLegacyCLIAsync.js:37:33)
```

It does spit out some JSON after that, but it's not the same JSON as if the error would not occur.

### Fun side fact
Expo doctor also included the console.log in its output :) See below 

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 22.8.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~52.0.20 => 52.0.21
      expo-router: ~4.0.14 => 4.0.14
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Modify stdout
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by JoelYourstone** [comment]
I'm not 100% sure if this counts as an SDK bug or a CLI bug. I filed it as a SDK bug for now.
