### ISSUE TITLE
React Native DevTools Fails to Open on Fresh Install: `TypeError: fetch failed`

### ISSUE THREAD

**Issue by aabuhijleh** [expo/expo#33833]
### Summary

I can't open React Native DevTools on a fresh install using the latest version. 

I'm getting the following error when pressing `j`:

```sh
Failed to open the React Native DevTools.
TypeError: fetch failed
```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

52.0.23

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.17.0 - ~/.local/share/nvm/v20.17.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - ~/.local/share/nvm/v20.17.0/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.23 => 52.0.23 
      expo-router: ~4.0.15 => 4.0.15 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: bare
```

### Minimal reproducible example

Here's a repo where I can reproduce this issue 100% of the time: https://github.com/aabuhijleh/fresh-start

```sh
# init app
$ npx create-expo-app@latest

# use development build (or don't; same issue)
$ npm install expo-dev-client

# install and run the app on android emulator (or physical device, or ios; same issue)
$ npm run android
```

Then after pressing `j`, the dev tools won't open and you get an error message instead.

### Screenshots and Videos

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/7323f361-bc90-41b9-9180-2d826359baf3" />

https://github.com/user-attachments/assets/f527738a-b376-40f1-bbfc-b7b64473bbc2

**Comment by aabuhijleh** [comment]
I did some debugging and the issue appears to be happening in `queryAllInspectorAppsAsync`

It seems that this `http://192.168.1.22:8081/json/list` is not reachable.

<img width="1862" alt="image" src="https://github.com/user-attachments/assets/73006e7a-31d0-45eb-9117-18d18113b81f" />

Here's the full error

```
TypeError: fetch failed
    at fetch (/Users/abed/Desktop/Playground/fresh-start/node_modules/undici/index.js:112:13)
    at queryAllInspectorAppsAsync (/Users/abed/Desktop/Playground/fresh-start/node_modules/@expo/cli/src/start/server/middleware/inspector/JsInspector.ts:91:16)
    at DevServerManagerActions.openJsInspectorAsync (/Users/abed/Desktop/Playground/fresh-start/node_modules/@expo/cli/src/start/interface/interactiveActions.ts:105:20)
    at ReadStream.KeyPressHandler.handleKeypress (/Users/abed/Desktop/Playground/fresh-start/node_modules/@expo/cli/src/start/interface/KeyPressHandler.ts:43:7) {
  [cause]: SocketError: other side closed
      at Socket.<anonymous> (node:internal/deps/undici/undici:6020:28)
      at Socket.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1696:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '192.168.1.22',
      localPort: 59140,
      remoteAddress: '192.168.1.22',
      remotePort: 8081,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 183,
      bytesRead: 0
    }
  }
}
```


So, I tried to use the `--localhost` argument.

And now `http://127.0.0.1:8081/json/list` is reachable and here's its output:

```json
[
  {
    "id": "8541df8fc08287923c0f0215f32705e2014f28ab-1",
    "title": "React Native Bridgeless [C++ connection]",
    "description": "com.aabuhijleh.freshstart",
    "type": "node",
    "devtoolsFrontendUrl": "devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=192.168.1.22%3A8081%2Finspector%2Fdebug%3Fdevice%3D8541df8fc08287923c0f0215f32705e2014f28ab%26page%3D1",
    "webSocketDebuggerUrl": "ws://192.168.1.22:8081/inspector/debug?device=8541df8fc08287923c0f0215f32705e2014f28ab&page=1",
    "deviceName": "sdk_gphone64_arm64 - 15 - API 35",
    "reactNative": {
      "logicalDeviceId": "8541df8fc08287923c0f0215f32705e2014f28ab",
      "capabilities": {
        "prefersFuseboxFrontend": true,
        "nativeSourceCodeFetching": false,
        "nativePageReloads": true
      }
    }
  },
  {
    "id": "8541df8fc08287923c0f0215f32705e2014f28ab-2",
    "title": "React Native Bridgeless [C++ connection]",
    "description": "com.aabuhijleh.freshstart",
    "type": "node",
    "devtoolsFrontendUrl": "devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=192.168.1.22%3A8081%2Finspector%2Fdebug%3Fdevice%3D8541df8fc08287923c0f0215f32705e2014f28ab%26page%3D2",
    "webSocketDebuggerUrl": "ws://192.168.1.22:8081/inspector/debug?device=8541df8fc08287923c0f0215f32705e2014f28ab&page=2",
    "deviceName": "sdk_gphone64_arm64 - 15 - API 35",
    "reactNative": {
      "logicalDeviceId": "8541df8fc08287923c0f0215f32705e2014f28ab",
      "capabilities": {
        "prefersFuseboxFrontend": true,
        "nativeSourceCodeFetching": false,
        "nativePageReloads": true
      }
    }
  },
  {
    "id": "8541df8fc08287923c0f0215f32705e2014f28ab-3",
    "title": "React Native Bridgeless [C++ connection]",
    "description": "com.aabuhijleh.freshstart",
    "type": "node",
    "devtoolsFrontendUrl": "devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=192.168.1.22%3A8081%2Finspector%2Fdebug%3Fdevice%3D8541df8fc08287923c0f0215f32705e2014f28ab%26page%3D3",
    "webSocketDebuggerUrl": "ws://192.168.1.22:8081/inspector/debug?device=8541df8fc08287923c0f0215f32705e2014f28ab&page=3",
    "deviceName": "sdk_gphone64_arm64 - 15 - API 35",
    "reactNative": {
      "logicalDeviceId": "8541df8fc08287923c0f0215f32705e2014f28ab",
      "capabilities": {
        "prefersFuseboxFrontend": true,
        "nativeSourceCodeFetching": false,
        "nativePageReloads": true
      }
    }
  },
  {
    "id": "8541df8fc08287923c0f0215f32705e2014f28ab-4",
    "title": "Reanimated UI runtime [C++ connection]",
    "description": "com.aabuhijleh.freshstart",
    "type": "node",
    "devtoolsFrontendUrl": "devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=192.168.1.22%3A8081%2Finspector%2Fdebug%3Fdevice%3D8541df8fc08287923c0f0215f32705e2014f28ab%26page%3D4",
    "webSocketDebuggerUrl": "ws://192.168.1.22:8081/inspector/debug?device=8541df8fc08287923c0f0215f32705e2014f28ab&page=4",
    "deviceName": "sdk_gphone64_arm64 - 15 - API 35",
    "reactNative": {
      "logicalDeviceId": "8541df8fc08287923c0f0215f32705e2014f28ab",
      "capabilities": {
        "prefersFuseboxFrontend": false,
        "nativeSourceCodeFetching": false,
        "nativePageReloads": false
      }
    }
  }
]
```

But now I'm getting a different error

```sh
Failed to open the React Native DevTools.
Error: socket hang up
  ```
  
And I think this is maybe because of the web socket URL returned from `http://127.0.0.1:8081/json/list` not being reachable `192.168.1.22`. I'm not sure. I hope this helps you find the issue.

**Comment by aabuhijleh** [comment]
It looks like the `--localhost` argument is not being handled well.

I was able to resolve this issue by making 2 changes

I added this code here to replace `192.168.x.x` with `localhost`

```js
// inside node_modules/@expo/cli/build/src/start/server/middleware/inspector/JsInspector.js
async function queryAllInspectorAppsAsync(metroServerOrigin) {
    const resp = await fetch(`${metroServerOrigin}/json/list`);
    const apps = transformApps(await resp.json());
    + // Replace IP
    + const ipRegex = /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/;
    + apps.forEach((app) => {
    +    app.devtoolsFrontendUrl = app.devtoolsFrontendUrl.replace(ipRegex, "localhost");
    +    app.webSocketDebuggerUrl = app.webSocketDebuggerUrl.replace(ipRegex, "localhost");
    + });
    const results = [];
```

I also replaced the `serverBaseUrl` here with `localhost`. It was being sent as  `192.168.x.x`

```js
// inside node_modules/@expo/cli/build/src/start/server/metro/debugging/createDebugMiddleware.js
function createDebugMiddleware(metroBundler) {
    // Load the React Native debugging tools from project
    // TODO: check if this works with isolated modules
    const { createDevMiddleware  } = require("@react-native/dev-middleware");
    const { middleware , websocketEndpoints  } = createDevMiddleware({
        projectRoot: metroBundler.projectRoot,
        serverBaseUrl: "http://localhost:8081", /*metroBundler.getUrlCreator().constructUrl({
            scheme: "http",
            hostType: "lan"
        }),*/
        logger: createLogger(_chalk().default.bold("Debug:")),
```

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/c0cc37f7-782d-42be-92a0-079c28978f35" />

**Comment by abed-daloopa** [comment]
@kfinley-rbi, it looks like this issue has been assigned to a contributor. Thought, I don't think a PR has been opened yet because this issue would have been referenced in the PR.

**Comment by leonhh** [comment]
I had the same issue and it was solved by rebooting macOS. In my case Expo was trying to open `192.168.1.15` while my Wi-Fi settings were telling me I was connected as `192.168.1.96`.

I believe `ifconfig` was showing both ip addresses for my primary network adapter (en0). I can't reproduce this issue after a reboot.

**Comment by thisroot** [comment]
@aabuhijleh i am still have trouble with run react native debugger, after making changes with you advice

![Image](https://github.com/user-attachments/assets/edf4b8ba-dbc1-442d-a58c-bfc3c10f325f)

**Comment by bitcrumb** [comment]
I have the exact same issue.

[These steps](https://github.com/expo/expo/issues/33833#issuecomment-2561912164) described by [aabuhijleh](https://github.com/aabuhijleh) seem to indeed do the trick.

**Comment by TheRealMikeD** [comment]
FWIW, I got the same error recently on an existing project.  Everything had been working correctly for months, and then I started getting this error when trying to open the RN Dev Tools.  What had changed was an update to the VPN app (NordVPN) on my dev machine.  Some newly updated functionality of the VPN app seems to be blocking this connection, probably assuming that it's malicious.

Now, if I pause the VPN for a moment, I can launch the Dev Tools as expected.  Once the Dev Tools are open and running, I can then re-enable the VPN and the Dev Tools continue to work.  I just need to pause the VPN any time I am opening the Dev Tools for the first time in a session.  It's a minor nuisance, but easy enough to work around it.

I'm sure this is not the scenario for everyone, but maybe it will help some of you.

**Comment by mikehuebner** [comment]
That worked for me as well!
