### ISSUE TITLE
Error: While trying to resolve module "react"

### ISSUE THREAD

**Issue by pranshuchittora** [expo/expo#33886]
### Summary

Context - I am trying to use Expo in an existing bare RN project. As part of migrating from codepush to Expo-Updates

This is my tsconfig with an explicit definition for react types. This is needed for vector-icons to work. Else I encounter 
'XXX' cannot be used as a JSX component.

```json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "commonjs",
    "types": ["react-native", "jest"],
    "lib": ["es2019"],
    "allowJs": true,
    "jsx": "react-native",
    "isolatedModules": true,
    "skipLibCheck": true,
    "baseUrl": "./",
    "paths": {
      "react": ["./node_modules/@types/react"] // Needed for react-native-vector-icons.
    }
  },
  "include": ["**/*", "../src/**/*"],
  "exclude": ["node_modules", "babel.config.js", "metro.config.js", "jest.config.js"]
}

```

Related issue for more context - https://github.com/facebook/metro/issues/1388

When I try to build an update locally, I get the below mentioned error.
But when I remove the react paths definition form the tsconfig, the build works but my TS checks breaks. 

```
eas update --channel staging --auto --platform android
[expo-cli] Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName"
[expo-cli] Learn more: https://expo.fyi/root-expo-object
[expo-cli] env: load .env.local
[expo-cli] env: export SENTRY_AUTH_TOKEN
[expo-cli] Starting Metro Bundler
[expo-cli] Android Bundling failed 2295ms index.js (1791 modules)
[expo-cli] Error: While trying to resolve module `react` from file `X/Y/Z/app/AppWithExpoUpdates.tsx`, the package `X/Y/Z/app/node_modules/@types/react/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`X/Y/Z/app/node_modules/@types/react/index`. Indeed, none of these files exist:
[expo-cli]
[expo-cli]   * X/Y/Z/app/node_modules/@types/react/index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs|.android.png|.native.png|.png)
[expo-cli]   * X/Y/Z/app/node_modules/@types/react/index/index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs|.android.png|.native.png|.png)
[expo-cli] Error: While trying to resolve module `react` from file `X/Y/Z/app/AppWithExpoUpdates.tsx`, the package `X/Y/Z/app/node_modules/@types/react/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`X/Y/Z/app/node_modules/@types/react/index`. Indeed, none of these files exist:
[expo-cli]
[expo-cli]   * X/Y/Z/app/node_modules/@types/react/index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs|.android.png|.native.png|.png)
[expo-cli]   * X/Y/Z/app/node_modules/@types/react/index/index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs|.android.png|.native.png|.png)
[expo-cli]     at DependencyGraph.resolveDependency (X/Y/Z/app/node_modules/metro/src/node-haste/DependencyGraph.js:247:17)
[expo-cli]     at X/Y/Z/app/node_modules/metro/src/lib/transformHelpers.js:156:21
[expo-cli]     at resolveDependencies (X/Y/Z/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
[expo-cli]     at visit (X/Y/Z/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
[expo-cli]     at async Promise.all (index 4)
[expo-cli]     at visit (X/Y/Z/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
[expo-cli]     at async Promise.all (index 5)
[expo-cli]     at visit (X/Y/Z/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
[expo-cli]     at async Promise.all (index 0)
[expo-cli]     at buildSubgraph (X/Y/Z/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:103:3)
✖ Export failed
X/Y/Z/app/node_modules/expo/bin/cli export --output-dir dist --dump-sourcemap --dump-assetmap --platform android exited with non-zero code: 1
    Error: update command failed.
```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

51

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
      Watchman: 2024.11.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 28, 31, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-28 | Google APIs ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a, android-35 | Google Play Intel x86_64 Atom, android-35 | Google Play Experimental 16k Page Size ARM 64 v8a, android-VanillaIceCream | Google APIs ARM 64 v8a
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: 51 => 51.0.39
      react: 18.3.1 => 18.3.1
      react-native: 0.75.4 => 0.75.4
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: bare
```

### Minimal reproducible example

No possible

**Comment by byCedric** [comment]
Hi @pranshuchittora! If I understand correctly, you want to "always include the React types" in the project, right? I'm not sure why this would be required for `react-native-vector-icons`, it's not documented in [their installation guide](https://github.com/oblador/react-native-vector-icons?tab=readme-ov-file#installation).

Either way, if you want to always include the React types, you'd need to configure it differently. [`paths`](https://www.typescriptlang.org/tsconfig/#paths) is used to rewrite import paths -- which causes the issue you are seeing. Whenever you import `react`, TypeScript will transform the import to `./node_modules/@types/react`, which is invalid as this package would only contain the TypeScript definitions, not the actual React code.

Instead, try using the [`types`](https://www.typescriptlang.org/tsconfig/#types) property. This will always import the types listed in this array (which should already include `@types/*` modules by default).

Hope this helps!

**Comment by pranshuchittora** [comment]
Hey, the TSConfig change was based on this 
https://github.com/oblador/react-native-vector-icons/issues/1446#issuecomment-1379905065
