### ISSUE TITLE
Non interactive login not working

### ISSUE THREAD

**Issue by atinder** [expo/expo#340]
exp login -u myUsername -p myPassword

throws

```
[exp] invalid_request
Error: invalid_request
    at _formatAuth0NodeError (/xdl/src/User.js:785:39)
    at /xdl/src/User.js:682:21
    at Generator.throw (<anonymous>)
    at step (/home/ubuntu/.nvm/versions/node/v7.10.0/lib/node_modules/exp/node_modules/xdl/build/User.js:188:191)
    at /home/ubuntu/.nvm/versions/node/v7.10.0/lib/node_modules/exp/node_modules/xdl/build/User.js:188:402

```
Interactive login works with the same username and password.

**Comment by dikaiosune** [comment]
@wilzh40 did your updates to login code get released yet? Or do you think they'll resolve this?

**Comment by wilzh40** [comment]
@dikaiosune I don't think my PR solves this problem. The error message `invalid_request` seems to be an auth0 error, not on the side of `exp.` 
I can't replicate this with the current version of `exp.`
@atinder Is it still failing?

**Comment by atinder** [comment]
its still there even after updating exp

**Comment by dikaiosune** [comment]
@atinder can you run this with the `EXPO_DEBUG` environment variable set to `1`?

**Comment by atinder** [comment]
Hey guys,
I tried with the debug flag and got this error
```
[exp] { error: 'invalid_user_password',
  error_description: 'Wrong email or password.' }
```

My password started with a special character. I did password reset and removed special character. And it works.

So the problem is parsing special characters in password field

**Comment by wilzh40** [comment]
The error seems to part of the Auth0 SDK. It seems that a special character makes the password not a string, but we have Flow typechecking that ensures that we pass a string to Auth0. Would you mind saying what special character you used?

**Comment by atinder** [comment]
I have used $
