### ISSUE TITLE
Invoking URL with scheme matching package name (reverse URL format) crashes app on Android

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#3432]
### Environment

```
  Expo CLI 2.8.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.4
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.8.0
```

Target: SDK 31, SDK 32, ExpoKit, Android
Devices: Galaxy S8 / Android 8.0; Google Pixel Emulator with Android 9.0
(also see what appears to be same issue on a standard Expo standalone app using SDK 31)

### Steps to Reproduce

1. Create an app with `expo init`, choose advanced workflow
2. Build the Android app (development mode is fine)
3. Attempt to invoke app with URL matching package name (e.g., reverse URL, like 'com.company.example://something')
*** you can invoke the app from completely outside of the app, or as part of a redirect back to the app after calling WebBrowser.openBrowserAsync() or WebBrowser.openAuthSessionAsync() and you will get the same result.

OR

1. Build a standard Expo standalone app for Android.
2. Attempt to invoke app with URL matching package name (e.g., reverse URL, like 'com.company.example://something')

### Expected Behavior

One of two things should happen when using the app-specific URL (depending on your perspective):
a. The app should open (and any registered Linking event listeners should do their thing), OR
b. Technically speaking (maybe?), nothing should happen because, by default , `expo init` sets up "exp<random number here>" for the incoming link scheme, and not the package name. I'm being pedantic ;-)- I'm perfectly happy with a) happening, and it's not unexpected because the `net.openid.appauth.RedirectUriReceiverActivity` activity is setup with the package name as a filter. It's just that, if all you're looking at is the scheme in app.json, the casual observer might not expect this url other scheme to work without being explicitly set there.

### Actual Behavior

The app crashes. A "<Your App Name> has stopped / Open app again" error dialog appears.

In logcat, the following error shows up:
```
2019-02-05 12:18:38.632 20222-20222/com.llamaluvr.testandroidlinkingcrash E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.llamaluvr.testandroidlinkingcrash, PID: 20222
    java.lang.RuntimeException: Unable to resume activity {com.llamaluvr.testandroidlinkingcrash/net.openid.appauth.AuthorizationManagementActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3788)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3036)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
        at android.app.Activity.startActivityForResult(Activity.java:4564)
        at android.app.Activity.startActivityForResult(Activity.java:4522)
        at android.app.Activity.startActivity(Activity.java:4883)
        at android.app.Activity.startActivity(Activity.java:4851)
        at net.openid.appauth.AuthorizationManagementActivity.onResume(AuthorizationManagementActivity.java:218)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7344)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3036) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

The crash happens/ same dialog appears on a standard Expo standalone app. I haven't confirmed if it has the same logcat error.

### Reproducible Demo

Here's an ExpoKit project on SDK 32 demonstrating the issue: https://github.com/llamaluvr/testandroidlinkingcrash

To run:
1) Restore yarn dependencies
2) `yarn start`
3) Run in Android Studio

You can trigger the error a few different ways.
a) Click a URL to invoke the app, like com.llamaluvr.testandroidlinkingcrash://oauthredirect.
b) The actual app is adapted from this example (https://github.com/expo/examples/blob/master/with-webbrowser-redirect/app/App.js), and includes buttons for opening a redirect page using both `openBrowserAsync()` and `openAuthSessionAsync()`. Each one has the same behavior (crash).

As a control, you can try the URL scheme registered in the MainActivity: exp756db71a4fa849eab0dde164561b89b7://whatever - it will work.

#### Other demo

This appears to happen on standard Expo standalone apps. In our app on the Play Store, Coach Messenger (https://play.google.com/store/apps/details?id=com.nudgecoach.nudgecoachmobile&hl=en_US), we haven't intentionally setup any linking to the app, but if you invoke a URL with our package name (e.g., com.nudgecoach.nudgecoachmobile://whatever), the app will crash. This app is built with SDK 31.

### Workarounds

I'm still figuring out if there's any collateral damage, but so far, it looks like removing the `data` element from the following in AndroidManifest.xml prevents the crash:
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.llamaluvr.testandroidlinkingcrash" android:path="oauthredirect"/>
      </intent-filter>
    </activity>
```

Then, if you add
```
<data android:scheme="com.llamaluvr.testandroidlinkingcrash"/>
```
as a filter in the MainActivity, the redirect using the package name URL works.

### Did this work before?

Yes, redirects using the package name worked without modifying anything in SDK 28 (I didn't try after that before now).

**Comment by EvanBacon** [comment]
This has been fixed in the new `expo-auth-session` API which uses `expo-web-browser` to handle redirects. Please migrate to using this instead https://docs.expo.io/versions/latest/sdk/auth-session/#useauthrequest
