### ISSUE TITLE
[UX][ApiV2] Unhandled exceptions causing API errors to stop runtime.

### ISSUE THREAD

**Issue by m4r3x** [expo/expo#3478]
### Environment
```
➜  ~ expo diagnostics

  Expo CLI 2.10.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v8.10.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.10.0
```

No app yet, init steps.

### Steps to Reproduce

```
➜  projects expo init XXX
? Choose a template: expo-template-blank
? Choose which workflow to use: advanced
✔ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration · 100% completed
? Yarn v1.12.3 found. Use Yarn to install dependencies? Yes
[07:58:02] Extracting project files...
[07:58:03] Customizing project...
[07:58:03] Unable to initialize git repo. `git` not installed.
[07:58:03] Installing ExpoKit...
[07:58:03] An Expo user account is required to proceed.
? How would you like to authenticate? Make a new Expo account

Thanks for signing up for Expo!
Just a few questions:

? E-mail: secret@secret.com
? Username: terribleusername
? Password: [hidden]
? Confirm Password: [hidden]
{ ApiV2Error: terribleusername already exists, please provide a different username.
    at /xdl@53.0.1/src/ApiV2.js:187:19
    at Generator.throw (<anonymous>)
    at step (/Users/cookie/.nvm/versions/node/v8.10.0/lib/node_modules/expo-cli/node_modules/xdl/build/ApiV2.js:42:191)
    at /Users/cookie/.nvm/versions/node/v8.10.0/lib/node_modules/expo-cli/node_modules/xdl/build/ApiV2.js:42:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'API_ERROR',
  _isApiError: true,
  serverStack: undefined,
  details: undefined }
[07:58:25] Error registering user: niv already exists, please provide a different username.
➜  projects expo init XXX
[07:58:30] The path "/Users/cookie/projects/XXX" already exists. Please choose a different parent directory or project name.
```

### Expected Behavior

CLI asks for retry.

### Actual Behavior

CLI exits because of unhandled error.

**Comment by AdamJNavarro** [comment]
Hey @m4r3x,

Thanks for this report. I transferred the issue to our expo/expo-cli repo here as it seems to be an issue with the devtool. https://github.com/expo/expo-cli/issues/379

Cheers,

Adam
