### ISSUE TITLE
get an error when execute turtle setup

### ISSUE THREAD

**Issue by vigossparker** [expo/expo#3519]
after install turtle-cli, get an bindings error when execute turtle setup.
I tried several versions of node but did not help.

here is the error:
/usr/local/lib/node_modules/turtle-cli/node_modules/bindings/bindings.js:124
  err = new Error(
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/build/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/build/Debug/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/build/Release/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/out/Debug/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/Debug/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/out/Release/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/Release/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/build/default/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/compiled/8.11.4/darwin/x64/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /usr/local/lib/node_modules/turtle-cli/node_modules/sharp/lib/binding/node-v57-darwin-x64/sharp.node
    at bindings (/usr/local/lib/node_modules/turtle-cli/node_modules/bindings/bindings.js:124:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/builders/utils/image.ts:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/builders/utils/ios/shellAppBuilder.ts:9:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/index.ts:7:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/commands/build/ios.ts:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/commands/build/index.ts:1:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/commands/index.ts:1:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:6:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/turtle-cli/bin/turtle.js:6:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

environment:
mac mojave 10.14.2
node (8.11.4, 10.10.0, 11.6.0) all tried

could someone help?

**Comment by AdamJNavarro** [comment]
Hey @vigossparker,

We try our best to keep Github issues reserved for bugs. Please create a post on our [forums](https://forums.expo.io/c/expo-cli) to seek help for setting up the turtle-cli!

Cheers,
Adam

**Comment by vigossparker** [comment]
> Hey @vigossparker,
> 
> We try our best to keep Github issues reserved for bugs. Please create a post on our [forums](https://forums.expo.io/c/expo-cli) to seek help for setting up the turtle-cli!
> 
> Cheers,
> Adam

ok thx
