### ISSUE TITLE
[expo-av] [Android] Exception occurred while executing exported method loadForSound on module ExponentAV: null

### ISSUE THREAD

**Issue by jamsch** [expo/expo#3645]
### Environment

Note: using a react-native project with unimodules & the `expo-av` library. Installed as shown below
```
import expo.modules.av.AVPackage;
...
private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(Arrays.<Package>asList(
     // Your other packages will be here 
     new ReactAdapterPackage(),
     new ConstantsPackage(),
     new PermissionsPackage(),
     new FileSystemPackage(),
     new AVPackage()
    ), Arrays.<SingletonModule>asList());
```

```
  Expo CLI 2.11.6 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      @storybook/react-native: 4.1.13 => 4.1.13 
      @types/react: 16.7.13 => 16.7.13 
      @types/react-native: 0.57.38 => 0.57.38 
      @types/react-navigation: 3.0.4 => 3.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0-rc.3 => 0.59.0-rc.3 
      react-navigation: 2.18.3 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.11.6
```

### Steps to Reproduce

1. Follow installation steps for `expo-av`
2. Call `const player = await Audio.Sound.createAsync({ uri }, { shouldPlay: true })` in your code base
3. Promise is rejected with the error: 

```
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err: java.lang.reflect.InvocationTargetException
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at expo.core.ExportedModule.invokeExportedMethod(ExportedModule.java:96)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at expo.adapters.react.NativeModulesProxy.callMethod(NativeModulesProxy.java:117)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.exoplayer2.upstream.DataSource$Factory expo.modules.av.player.datasource.DataSourceFactoryProvider.createFactory(android.content.Context, expo.core.ModuleRegistry, java.lang.String, java.util.Map)' on a null object reference
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at expo.modules.av.player.SimpleExoPlayerData.load(SimpleExoPlayerData.java:100)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at expo.modules.av.AVManager.loadForSound(AVManager.java:357)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err:     at expo.modules.av.AVModule.loadForSound(AVModule.java:43)
2019-03-04 17:36:54.393 12927-12967/com.testapp.app W/System.err: 	... 13 more
```

### Expected Behavior

Audio should correctly load

### Actual Behavior

`mAVModule.getModuleRegistry().getAllExportedModules().toArray()` in `expo/modules/av/player/SimpleExoPlayerData.java(load)` yields the following:

```
[
  expo.modules.av.video.VideoManager@f963221,
  expo.modules.constants.ConstantsModule@cbf9646,
  expo.modules.permissions.PermissionsModule@1e370dc,
  expo.modules.av.AVModule@d808007,
  expo.modules.filesystem.FileSystemModule@322d534
]
```

When calling `mAVModule.getModuleRegistry().getModule(DataSourceFactoryProvider.class)`, the DataSourceFactoryProvider isn't found.

**Comment by Szymon20000** [comment]
The issue shouldn't occur in the latest [expo-av](expo av npm). Could you tell what version of expo-av you have?

**Comment by jamsch** [comment]
@Szymon20000 Using expo-av@3.0.0. First time using this library was installing it earlier this day.

**Comment by Szymon20000** [comment]
Ok, now I see it's another bug. It should be fixed soon.

**Comment by sjchmiela** [comment]
Try downloading and using the following `expo-av` package as the dependency. We'll publish an official `3.0.1` update to NPM later today. 🙂 

[expo-av-3.0.1.tar.gz](https://github.com/expo/expo/files/2926120/expo-av-3.0.1.tar.gz)
