### ISSUE TITLE
[android] Uncaught Error: java.lang.String cannot be cast as java.lang.Boolean after bundle update

### ISSUE THREAD

**Issue by peterkuiper** [expo/expo#3770]
### Environment

```
  Expo CLI 2.10.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: 3.3.2 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.10.1
```

Update settings in `app.json`:

```
"updates": {
  "enabled": true,
  "checkAutomatically": "ON_ERROR_RECOVERY",
  "fallbackToCacheTimeout": 0
}
```

### Steps to Reproduce

This problem has been very difficult to troubleshoot. It only occurs on Android and only after a new bundle update has been pushed. It has been plaguing us since SDK v28.

We are using `Updates.checkForUpdateAsync()` to check for updates and use `Updates.fetchUpdateAsync()` to fetch new updates, if available. After the update has been downloaded, we show an alert with a button using `Updates.reloadFromCache()`.

I have been publishing under a different account (and monitoring network traffic with mitmproxy) with a custom build of the app in the hope that I would be able to spot something funky (corrupt bundle, empty manifest etc). I was unable to get this error condition. It just happens when it happens...

We also have Fabric and Sentry enabled, both of which do not give any information about this crash.

The real problem here is that there is some vital information missing from the error that Expo is returning. If at least there would be some way of getting more info then we at least would
know where to look.

I also posted to the forum (no replies yet): https://forums.expo.io/t/uncaught-error-java-lang-string-cannot-be-cast-to-java-lang-boolean-after-publish/20588. I also tried to join the Slack channel, but I didn't receive the invite for some reason.

If anyone could point me in the right direction to troubleshoot, that would be very much appreciated!

### Expected Behavior

Reloading the app after an update should work.

### Actual Behavior

![2LnxR](https://user-images.githubusercontent.com/6492184/54539198-f3c15800-4995-11e9-9b1b-2eb654180483.jpg)

The app needs to be completely reinstalled for it to work again.

### Reproducible Demo

Since this app has been ejected to Expokit it is not possible to create a reproducible demo.

**Comment by cruzach** [comment]
Hey @peterkuiper,

Sorry about this issue, but some more info on the error would be a huge help

I know you said the error doesn't occur reliably, just whenever it happens, but any chance you might be able to use `adb logcat` to capture some stack traces when the device throws an error?

Thanks!
Charlie

**Comment by peterkuiper** [comment]
@cruzach I sure will. Commands like these just the thing I am looking for trying to debug this issue. It is really frustrating to work on something like this, not being able to reproduce it. Hopefully, I can capture something useful. Thanks!

**Comment by peterkuiper** [comment]
I have yet to encounter the error, but I am still working on reproducing this issue.

**Comment by KendoJaaa** [comment]
I'm not sure it is the same problem I'm facing. 
but it happens only when I call "Updates.reloadFromCache()" after "Updates.fetchUpdateAsync()" instantly. 
and nothing happens from calling Updates.reloadFromCache(), the code just continue running to the next line.

but after a while (20 secs). Updates.reloadFromCache() is back to work correctly.

It also happened only on Android.

**Comment by KendoJaaa** [comment]
is there a workaround for this? 
should I use Updates.addListener(eventListener) instead? 
or setTimeout(). to wait abit @peterkuiper

**Comment by peterkuiper** [comment]
@KendoJaaa Not sure if this is the same error, could be.

@cruzach I have a stack trace from Fabric:

```
#0. Crashed: mqt_native_modules
       at com.facebook.react.bridge.ReadableNativeArray.getBoolean(ReadableNativeArray.java:104)
       at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:37)
       at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:33)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)

--

Non-fatal Exception: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
       at com.facebook.react.bridge.ReadableNativeArray.getBoolean(ReadableNativeArray.java:104)
       at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:37)
       at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:33)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)

#0. Crashed: mqt_native_modules
       at com.facebook.react.bridge.ReadableNativeArray.getBoolean(ReadableNativeArray.java:104)
       at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:37)
       at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:33)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

After an update we are seeing about ~130 of these events. Devices are HUAWEI and Samsung with Android 6, 7 and 8.

**Comment by peterkuiper** [comment]
I now have a device with said problem. Using `adb logcat`:

```
 5505 06-18 13:14:40.287 27979 28125 W System.err: org.json.JSONException: No value for bundledAssets
 5506 06-18 13:14:40.287 27979 28125 W System.err:  at org.json.JSONObject.get(JSONObject.java:392)
 5507 06-18 13:14:40.287 27979 28125 W System.err:  at org.json.JSONObject.getJSONArray(JSONObject.java:587)
 5508 06-18 13:14:40.287 27979 28125 W System.err:  at versioned.host.exp.exponent.modules.universal.ScopedFileSystemModule.getBundledAssets(ScopedFileSystemModule.java:41)
 5509 06-18 13:14:40.287 27979 28125 W System.err:  at versioned.host.exp.exponent.modules.universal.ScopedFileSystemModule.getConstants(ScopedFileSystemModule.java:28)
 5510 06-18 13:14:40.287 27979 28125 W System.err:  at expo.adapters.react.NativeModulesProxy.getConstants(NativeModulesProxy.java:74)
 5511 06-18 13:14:40.287 27979 28125 W System.err:  at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:138)
 5512 06-18 13:14:40.287 27979 28125 W System.err:  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 5513 06-18 13:14:40.287 27979 28125 W System.err:  at android.os.Handler.handleCallback(Handler.java:789)
 5514 06-18 13:14:40.287 27979 28125 W System.err:  at android.os.Handler.dispatchMessage(Handler.java:98)
 5515 06-18 13:14:40.287 27979 28125 W System.err:  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
 5516 06-18 13:14:40.287 27979 28125 W System.err:  at android.os.Looper.loop(Looper.java:164)
 5517 06-18 13:14:40.287 27979 28125 W System.err:  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
 5518 06-18 13:14:40.287 27979 28125 W System.err:  at java.lang.Thread.run(Thread.java:764)
```

And a lot of these:

```
6-18 13:17:02.651 27979 28352 W unknown:ReactNative: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
06-18 13:17:02.651 27979 28352 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {a17e6c4} sending message to a Handler on a dead thread
06-18 13:17:02.651 27979 28352 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {a17e6c4} sending message to a Handler on a dead thread
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.Handler.post(Handler.java:356)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:59)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:789)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at android.os.Looper.loop(Looper.java:164)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
06-18 13:17:02.651 27979 28352 W MessageQueue: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by cruzach** [comment]
@peterkuiper - I found a [different issue](https://github.com/zo0r/react-native-push-notification/issues/846) (separate repo) that is also using Expokit and seems to be seeing the same error messages. I'm thinking that the most likely culprit here is a missed step (or something similar) when [upgrading Expokit](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit). Can you confirm for me that your Android files have all the correct associated changes?

**Comment by peterkuiper** [comment]
@cruzach We have followed the upgrade guides closely. Maybe we missed something, but I would assume that this error would always occur and not just at random.

I have checked https://github.com/expo/expo/blob/7f7a23395b08a5479a28b113d4cb2ccd96e3d024/android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ScopedFileSystemModule.java#L41 but it seems to me that maybe SHELL_APP_EMBEDDED_MANIFEST_PATH is empty or malformed.

Is there any way to look at these files present on the device?

**Comment by cruzach** [comment]
Hmm that file should be created once you run `expo publish`, since this issue **only** crops up _after_ you send out an OTA update (by running `expo publish`), the file should be in the directory

**Comment by peterkuiper** [comment]
@cruzach 

```
    "android": {
      "package": "xxxx",
      "versionCode": xxxxx,
      "icon": "./assets/android_1024x1024.png",
      "playStoreUrl": "https://play.google.com/store/apps/details?id=xxxxx",
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json",
      "permissions": [
        "CAMERA",
        "MANAGE_DOCUMENTS",
        "READ_CONTACTS",
        "READ_EXTERNAL_STORAGE",
        "READ_INTERNAL_STORAGE",
        "READ_PHONE_STATE",
        "VIBRATE",
        "WRITE_EXTERNAL_STORAGE"
      ]
    },
```

**Comment by artemis-prime** [comment]
I'm getting this stack in Emulation (emulating Pixel 3 XL), as well as on a physical Android phone (Samsung J3)...  It started to happen without any change to my code that I can see.

**Comment by thiemo--bleeken** [comment]
Same for me. Not working in emulator and on android devices. iOS is not showing this error

**Comment by tsapeta** [comment]
SDK32 and ExpoKit are no longer supported so I'm closing this issue. I recommend migrating to bare workflow instead of using ExpoKit.
