### ISSUE TITLE
EXPO-GL flush crash in SDK 32

### ISSUE THREAD

**Issue by Uniphix** [expo/expo#3787]
When we use Expo GLView for some reason this is causing a crash.  This method works fine for iOS but not for android.

03-19 15:09:26.993  5996  6151 E AndroidRuntime: java.lang.NoSuchMethodError: no non-static method "Lexpo/modules/gl/b;.flush()V"
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at expo.modules.gl.cpp.EXGL.EXGLContextSetFlushMethod(Native Method)
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at expo.modules.gl.b$1.run(GLContext.java:93)
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:751)
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:154)
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
03-19 15:09:26.993  5996  6151 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:762)

**Comment by cruzach** [comment]
Hey @Uniphix,

Could you provide a method for us to reproduce this?

Best to just follow the template, that way we get all the info we need on the first go!

Thanks,
Charlie

**Comment by Uniphix** [comment]
### Environment

Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.4.1 
    npmGlobalPackages:
      expo-cli: 2.3.8

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/blender-8b050c4d-f829-4703-bf16-fdafb8ef63b4.tar.gz

Application Target: iOS, Android, ExpoKit (Ejected)

### Steps to Reproduce
We are using a third party library called gl-react, which works fine for iOS.  It is behind the scene using Expo GLView.  It will work on Android when it is **NOT** Production Mode.  But when it is it will not even allow the page to load, just crashes and provides only that error above

### Expected Behavior
To work just like iOS Production Mode and work fine either modes.

### Actual Behavior
Crash when we navigate to the page that uses GLView

**Comment by Uniphix** [comment]
Were you guys able to reproduce this issue?

**Comment by Uniphix** [comment]
I noticed that this error occurs when it is in production mode and deployed to PlayStore, but works fine when not in play store

**Comment by Uniphix** [comment]
I decided to use the Verbose mode and got this information right before the crash.  Not sure if it will help

`2019-03-21 17:32:42.697 304-304/? D/SurfaceFlinger:   Display[0] configurations (* current):
        * 0: 720x1280, xdpi=268.941010, ydpi=268.694000, refresh=16666667
      numHwLayers=4, flags=00000000
        type   |  handle  | hint | flag | tr | blnd |   format    |     source crop (l,t,r,b)      |          frame         | name 
    -----------+----------+------+------+----+------+-------------+--------------------------------+------------------------+------
           HWC | a9b8f5e0 | 0002 | 0000 | 00 | 0100 | RGBA_8888   |    0.0,    0.0,  719.0, 1280.0 |    0,    0,  719, 1280 | com.blender.socialdrip/host.exp.exponent.MainActivity
           HWC | a9bc94e0 | 0002 | 0000 | 00 | 0100 | RGBA_8888   |    0.0,    0.0,    1.0, 1280.0 |  719,    0,  720, 1280 | com.blender.socialdrip/com.yalantis.ucrop.UCropActivity
           HWC | a9b8e1a0 | 0002 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720.0,   48.0 |    0,    0,  720,   48 | StatusBar
     FB TARGET | adda2e60 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720.0, 1280.0 |    0,    0,  720, 1280 | HWC_FRAMEBUFFER_
2019-03-21 17:32:42.697 304-304/? D/SurfaceFlinger: TARGET
2019-03-21 17:32:42.702 304-326/? I/SurfaceFlinger: id=215 Removed com.blender.socialdrip/com.yalantis.ucrop.UCropActivity_dim (4/8)
2019-03-21 17:32:42.703 304-2320/? I/SurfaceFlinger: id=215 Removed com.blender.socialdrip/com.yalantis.ucrop.UCropActivity_dim (-2/8)
2019-03-21 17:32:42.704 304-304/? D/SurfaceFlinger:   Display[0] configurations (* current):
        * 0: 720x1280, xdpi=268.941010, ydpi=268.694000, refresh=16666667
      numHwLayers=3, flags=00000000
        type   |  handle  | hint | flag | tr | blnd |   format    |     source crop (l,t,r,b)      |          frame         | name 
    -----------+----------+------+------+----+------+-------------+--------------------------------+------------------------+------
           HWC | a9b8f5e0 | 0002 | 0000 | 00 | 0100 | RGBA_8888   |    0.0,    0.0,  720.0, 1280.0 |    0,    0,  720, 1280 | com.blender.socialdrip/host.exp.exponent.MainActivity
           HWC | a9b8e1a0 | 0002 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720.0,   48.0 |    0,    0,  720,   48 | StatusBar
     FB TARGET | adda2e60 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720.0, 1280.0 |    0,    0,  720, 1280 | HWC_FRAMEBUFFER_TARGET
2019-03-21 17:32:42.756 6011-6021/? I/art: Background partial concurrent mark sweep GC freed 4134(133KB) AllocSpace objects, 4(80KB) LOS objects, 9% free, 145MB/161MB, paused 16.212ms total 145.059ms
2019-03-21 17:32:42.935 6011-6118/? D/SoLoader: About to load: libexpo-gl.so
2019-03-21 17:32:42.941 6011-6118/? D/SoLoader: libexpo-gl.so not found on /data/data/com.blender.socialdrip/lib-main
2019-03-21 17:32:42.941 6011-6118/? D/SoLoader: libexpo-gl.so found on /data/app/com.blender.socialdrip-1/lib/arm
2019-03-21 17:32:42.941 6011-6118/? D/SoLoader: Not resolving dependencies for libexpo-gl.so
2019-03-21 17:32:43.036 6011-6118/? D/SoLoader: Loaded: libexpo-gl.so
2019-03-21 17:32:43.383 1638-1836/? D/NetworkController.MobileSignalController(0/-2): onSignalStrengthsChanged signalStrength=SignalStrength: 99 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 0x0 gsm|lte level=0
2019-03-21 17:32:43.384 1638-1836/? D/NetworkController.MobileSignalController(0/-2): getMobileIconGroup(): 0
2019-03-21 17:32:43.466 6011-6021/? I/art: Background sticky concurrent mark sweep GC freed 53429(2MB) AllocSpace objects, 3(60KB) LOS objects, 1% free, 158MB/161MB, paused 6.605ms total 57.524ms
2019-03-21 17:32:43.468 6011-6118/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.blender.socialdrip, PID: 6011
    java.lang.NoSuchMethodError: no non-static method "Lexpo/modules/gl/b;.flush()V"
        at expo.modules.gl.cpp.EXGL.EXGLContextSetFlushMethod(Native Method)
        at expo.modules.gl.b$1.run(GLContext.java:93)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:762)`

**Comment by DallAcqua** [comment]
Same error here, any progress?

**Comment by WonyJeong** [comment]
add line 
` -keep class expo.modules.** { *; }` in proguard-rules.pro
workd for me

**Comment by tsapeta** [comment]
If the above solution fixes the issue, I think we should add this thing to ProGuard rules to `expo-gl` package. This is easy to do and good-first-issue — does anybody here want to take care of it?
