### ISSUE TITLE
Android 7.0 - Fatal Exception

### ISSUE THREAD

**Issue by aarongfranco** [expo/expo#389]
I try to run my app on Expo and it crashes Expo.
Build Number:
`NPLS25.86-17-3-8`

Kernel:
`3.18.31-perf-gc-3f1117-00070-gbb3e543`

Expo XDE and Expo app are latest releases.

Error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: host.exp.exponent, PID: 518
       android.os.NetworkOnMainThreadException
           at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1317)
           at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
           at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
           at d.r.write(Okio.java:78)
           at d.b.write(AsyncTimeout.java:180)
           at d.x.d(RealBufferedSink.java:178)
           at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
           at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
           at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
           at abi18_0_0.com.facebook.react.devsupport.JSDebuggerWebSocketClient.closeQuietly(JSDebuggerWebSocketClient.java:144)
           at abi18_0_0.com.facebook.react.devsupport.WebsocketJavaScriptExecutor$3.run(WebsocketJavaScriptExecutor.java:146)
           at android.os.Handler.handleCallback(Handler.java:751)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:154)
           at android.app.ActivityThread.main(ActivityThread.java:6123)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by andreujuanc** [comment]
I just send a crash report as well. In my case app crashes when I tap on Scan QR code..
i'm running in a honeywell CT50 with android 6.0.1

**Comment by dikaiosune** [comment]
Hi! Sorry for the delay here. It's hard for us to act on reports that just have a stack trace without a description of what actions were taken or what app you were loading.

Going to give this a close for now, but if you're still seeing this on the current release, please reply back with a reproduction that we can try and some info about android version and device hardware and I'll reopen. Thanks!
