### ISSUE TITLE
google-services.json - Builds Failing on :app:processProdKernelReleaseGoogleServices

### ISSUE THREAD

**Issue by iChaosren** [expo/expo#3919]
### Environment
```
expo diagnostics

  Expo CLI 2.14.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617
```

I'm running the following command:
```
EXPO_ANDROID_KEYSTORE_PASSWORD=passwordhere EXPO_ANDROID_KEY_PASSWORD=passwordhere EXPO_DEBUG=true expo ba --release-channel auto-dev --no-publish --no-wait --keystore-path app.jks --keystore-alias private_alias
```

package.json:
```
"expo": "^32.0.6",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.1.tar.gz",
```

app.json:
```
"sdkVersion": "32.0.0",
"android": {
      "googleServicesFile": "./google-services.json",
      "versionCode": 20,
      "package": "com.company.app-example-name",
}
```

google-services.json (Downloaded straight from firebase):
```
{
  "project_info": {
    "project_number": "<private-project-number>",
    "firebase_url": "https://<private-project>.firebaseio.com",
    "project_id": "<private-project-id>",
    "storage_bucket": "<private-project>.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "<private>",
        "android_client_info": {
          "package_name": ""<private-verified-the-same-as-app.json>""
        }
      },
      "oauth_client": [
        {
          "client_id": "<private>.apps.googleusercontent.com",
          "client_type": 1,
          "android_info": {
            "package_name": "<private-verified-the-same-as-app.json>",
            "certificate_hash": "<private>"
          }
        }
      ],
      "api_key": [
        {
          "current_key": "<private>"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "<private>.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ]
  "configuration_version": "1"
}
```

### Steps to Reproduce
1. Init new project

2. Generate keystore with any alias

3. Follow these instructions to the letter: [https://docs.expo.io/versions/latest/guides/using-fcm/](https://docs.expo.io/versions/latest/guides/using-fcm/)

4. Execute command and watch logs:
```
EXPO_ANDROID_KEYSTORE_PASSWORD=passwordhere EXPO_ANDROID_KEY_PASSWORD=passwordhere EXPO_DEBUG=true expo ba --release-channel auto-dev --no-publish --no-wait --keystore-path app.jks --keystore-alias private_alias
```

### Expected Behavior
App builds successfully on expo server.

### Actual Behavior
App build fails with error:
```
> Task :app:processProdKernelReleaseGoogleServices FAILED
Parsing json file: /app/workingdir/android/sdk32/android-shell-app/app/google-services.json
12 actionable tasks: 12 executed
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processProdKernelReleaseGoogleServices'.
[stderr] > No matching client found for package name 'com.company.app-example-name'
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 26s
Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/app/node_modules/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by iChaosren** [comment]
Example build:
[https://expo.io/builds/30343509-74f7-4fb2-bb5c-280cb36c8136](https://expo.io/builds/30343509-74f7-4fb2-bb5c-280cb36c8136)

Don't know if this will help...

**Comment by iChaosren** [comment]
So apparently... And I did not know this...

The `--no-publish` was causing the issue, due to the google-services.json being out of date on the server and not in the project...

Ran a publish and now it's working just fine.
