### ISSUE TITLE
Ejected expo app APK always crashes on first open

### ISSUE THREAD

**Issue by WouterFlorijn** [expo/expo#3955]
I'm building an ejected Expokit app for Android. Whenever I install the SDK on my phone, it crashes after half a second of white screen. Then when I open it again, it runs. Note that I have published the app to the corresponding release channel already.

There are no errors to debug, because it's a production build. I can't replicate the situation on a debug build, since that just tries to connect to the bundler running on my laptop.

I think this is an issue with OTA, but other than that I'm in the dark.

**Comment by cruzach** [comment]
Hey @WouterFlorijn,

Could you try loading a production js bundle? That way you can use the native Android debugging tools (`adb`) and we can see the logs/stack trace and get a deeper understanding of what's going on

Thanks!
-Charlie

**Comment by WouterFlorijn** [comment]
Hi @cruzach 

Thanks for the tip! I tried replacing the `DEVELOPMENT_URL` in `DetachBuildConstants` with a published URL (https://exp.host/@dyme/dyme?release-channel=staging-2.7 in this case) and found that my issue seems to be the same as reported [here](https://forums.expo.io/t/expo-modules-firebase-messaging-exfirebaseinstanceidservice-fatals-on-first-run/17866).

Sadly, there are no answers. If you happen to know the cause, or know where else I should post this issue, I would be grateful.

The exception is:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dyme.dyme, PID: 5249
    java.lang.RuntimeException: Unable to instantiate service expo.modules.firebase.messaging.EXFirebaseInstanceIdService: java.lang.ClassNotFoundException: Didn't find class "expo.modules.firebase.messaging.EXFirebaseInstanceIdService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dyme.dyme-h_cWsmo_G6eBm3cXYNcpug==/base.apk"],nativeLibraryDirectories=[/data/app/com.dyme.dyme-h_cWsmo_G6eBm3cXYNcpug==/lib/arm, /data/app/com.dyme.dyme-h_cWsmo_G6eBm3cXYNcpug==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3654)
        at android.app.ActivityThread.access$1500(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "expo.modules.firebase.messaging.EXFirebaseInstanceIdService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dyme.dyme-h_cWsmo_G6eBm3cXYNcpug==/base.apk"],nativeLibraryDirectories=[/data/app/com.dyme.dyme-h_cWsmo_G6eBm3cXYNcpug==/lib/arm, /data/app/com.dyme.dyme-h_cWsmo_G6eBm3cXYNcpug==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3649)
        at android.app.ActivityThread.access$1500(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

I don't know much about Java, so it's hard for me to debug.

**Comment by WouterFlorijn** [comment]
Update: It works after removing the following from `AndroidManifest.xml`:

``` xml
<service android:name="expo.modules.firebase.messaging.EXFirebaseInstanceIdService">
    <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
</service>
```

I added this initially following [this guide](https://blog.expo.io/using-firebase-in-expo-e13844061832), but it appears the [boilerplate](https://github.com/EvanBacon/expo-native-firebase) is incorrect/outdated.

**Comment by hashmatmuqbil** [comment]
Hi, 
I got the same issue, created an app with the latest expo (33.0.0) and ejected with expoKit. (nothing changed in the app, I mean have't added additional packages) After a lot of work I succeed to build and install it with Android Studio on my phone and also on emulator but as soon I run the app it crashes so I can't run it at all. 
Any suggestions please ?

**Comment by cruzach** [comment]
Thanks for posting your fix @WouterFlorijn (that lib has been now been deprecated)

Hey @hashmatmuqbil, have you run `expo publish` before building? If you're still seeing that behavior, please open a separate issue and provide all the info we ask for in the bug report template. Thanks!
