### ISSUE TITLE
ERROR: Failed to setup environment for android builds

### ISSUE THREAD

**Issue by superyarik** [expo/expo#4021]
trying to [install turtle](https://docs.expo.io/versions/latest/distribution/turtle-cli/#install-turtle-cli) for build application with branch. ([blog post](https://blog.expo.io/changes-to-expo-branch-support-d002c4bc564e))
i can not install jdk 8, its unavailable from oracle servers, so latest installed.
also i install turtle-cli@0.5.15

run command
turtle setup:android --sdk-version 32.0.0

face this
Apr 17 13:08:57 turtle[8262] ERROR: Failed to setup environment for android builds
  err: Error: Process exited with non-zero code: 1
      at ChildProcess.child.on (/usr/local/lib/node_modules/turtle-cli/node_modules/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Socket.stream.socket.on (internal/child_process.js:346:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:557:12)
  platform: "ios"
  environment: null

how i can fix it?

**Comment by superyarik** [comment]
@cruzach 
$ echo $SHELL
/usr/local/bin/bash
$ echo $BASH_VERSION
5.0.3(1)-release
$ node -v
v8.11.3
