### ISSUE TITLE
Expo build:android error

### ISSUE THREAD

**Issue by jimyu2006** [expo/expo#4137]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

With virtual device open, then I run expo build:android generate issues as below:

C:\exec\react-native\test2>expo build:android
Checking if there is a build in progress...

Request failed with status code 400
Error: Request failed with status code 400
    at createError (C:\Dev\nvm\v10.15.1\node_modules\expo-cli\node_modules\xdl\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Dev\nvm\v10.15.1\node_modules\expo-cli\node_modules\xdl\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Dev\nvm\v10.15.1\node_modules\expo-cli\node_modules\xdl\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Same 400 issue when trying to click the "Run on android device/emulator" button in the expo browser window:
INFO12:44   Downloading latest version of Expo
ERROR 12:44  Couldn't start project on Android: Error running adb: Request failed with status code 400

Any ideas/help?

**Comment by cruzach** [comment]
Hi @jimyu2006,

Could you follow the issue template? Definitely need information like your environment, Expo CLI version, and everything else listed in the template.

Also- moving this to the Expo CLI repo

Thanks!
Charlie
