### ISSUE TITLE
[Camera] getSupportedRatiosAsync returns unsupported aspect ratio

### ISSUE THREAD

**Issue by EskelCz** [expo/expo#4174]
### Environment
```
  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^27.0.1 => 27.1.1 
      react: 16.3.1 => 16.3.1 
      react-native: ~0.55.2 => 0.55.4 
    npmGlobalPackages:
      expo-cli: 2.17.1
```
Target: Android, real device Xiaomi RedMi 6

### Steps to Reproduce

If you call getSupportedRatiosAsync(), you get a list of supported aspect ratios. Among them is '9:5'. However if you try to set this ratio to expo camera component, the app will crash.

### Expected Behavior

Either don`t show the ratio as supported, or handle the failure better.

### Actual Behavior
Crash
```
Java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.SortedSet.last()' on a null object reference
	at com.google.android.a.b.v(Camera1.java:560)
	at com.google.android.a.b$1.a(Camera1.java:114)
	at com.google.android.a.i.e(PreviewImpl.java:56)
	at com.google.android.a.n$1.onSurfaceTextureAvailable(TextureViewPreview.java:45)
	at android.view.TextureView.getHardwareLayer(TextureView.java:396)
	at android.view.TextureView.draw(TextureView.java:339)
	at android.view.View.updateDisplayListIfDirty(View.java:18254)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at android.view.View.draw(View.java:19345)
	at android.view.View.updateDisplayListIfDirty(View.java:18254)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at abi27_0_0.com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:210)
	at android.view.View.updateDisplayListIfDirty(View.java:18245)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at android.view.View.draw(View.java:19345)
	at android.view.View.updateDisplayListIfDirty(View.java:18254)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at android.view.View.updateDisplayListIfDirty(View.java:18245)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at android.view.View.updateDisplayListIfDirty(View.java:18245)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at android.view.View.updateDisplayListIfDirty(View.java:18245)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at android.view.View.draw(View.java:19345)
	at com.android.internal.policy.DecorView.draw(DecorView.java:792)
	at android.view.View.updateDisplayListIfDirty(View.java:18254)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:678)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:684)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:792)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3162)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2962)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2500)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1482)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7122)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:983)
	at android.view.Choreographer.doCallbacks(Choreographer.java:795)
	at android.view.Choreographer.doFrame(Choreographer.java:723)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:969)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
### Reproducible Demo

```
      <RNCamera ratio={'9:5'}/>
```

**Comment by cruzach** [comment]
Hi @EskelCz ,

Could you reproduce this with SDK 31 or above, and link the Snack?

Thanks!
Charlie

**Comment by EskelCz** [comment]
@cruzach Sure, it's as simple as I said, here: https://snack.expo.io/@eskel/camera-crash
When you open this in Xiaomi Redmi 6 (one of the cheapest smartphones), the app will crash.
It's cased by the aspect ratio. The problem is that this aspect ratio is returned as valid, from getSupportedRatiosAsync.

**Comment by ncoen97** [comment]
Hi, i think im having a similar issue. Im console logging the output of `cameraRef.getSupportedRatiosAsync()` in every render, and im getting:

- Array [ "2:1", "3:2", "3:4", "4:3", "5:3", "9:5", "9:11", "11:9", "16:9", ] in the first render
- Array [ "2:1", "3:2", "3:4", "4:3", "5:3", "9:11", "11:9", "16:9", ] in all the other renders

**Environment**
Expo CLI 3.24.2 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18

**Comment by chj-damon** [comment]
the github-actions bot is insane. this kind of issue is not resolved by the team and it keeps close it so other developers cannot track it down.

for me, this issue still happens now.

**Comment by lamualfa** [comment]
I'm facing the same problem. The other issues was closed by the bot without any solutions.
