### ISSUE TITLE
[expo-image-picker] FileUriExposedException: Failure delivering result ResultInfo{} to activity

### ISSUE THREAD

**Issue by retyui** [expo/expo#4205]
## 🐛 Bug Report

An aplication crashed with next error when using `launchCameraAsync()` fcuntion on Android!

```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testdemo, PID: 1614
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=13, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.testdemo/com.testdemo.MainActivity}: android.os.FileUriExposedException: file:///data/user/0/com.testdemo/cache/ImagePicker/9889d105-92cd-4880-b652-e83b82e66565.jpg exposed beyond app through ClipData.Item.getUri()
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4584)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: android.os.FileUriExposedException: file:///data/user/0/com.testdemo/cache/ImagePicker/9889d105-92cd-4880-b652-e83b82e66565.jpg exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
        at android.net.Uri.checkFileUriExposed(Uri.java:2371)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:966)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10902)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10887)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
        at android.app.Activity.startActivityForResult(Activity.java:4688)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4646)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at expo.modules.imagepicker.ImagePickerModule.startActivityOnResult(ImagePickerModule.java:754)
        at expo.modules.imagepicker.ImagePickerModule.launchCameraWithPermissionsGranted(ImagePickerModule.java:201)
        at expo.modules.imagepicker.ImagePickerModule.access$000(ImagePickerModule.java:60)
        at expo.modules.imagepicker.ImagePickerModule$1.onPermissionsResult(ImagePickerModule.java:156)
        at expo.modules.permissions.PermissionsService$1.onPermissionResult(PermissionsService.java:56)
        at org.unimodules.adapters.react.services.UIManagerModuleWrapper$5.onRequestPermissionsResult(UIManagerModuleWrapper.java:217)
        at com.reactnativenavigation.NavigationActivity.onRequestPermissionsResult(NavigationActivity.java:117)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7940)
        at android.app.Activity.dispatchActivityResult(Activity.java:7762)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4577)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6981) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
```

### Environment

```sh
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 19.1 (Tessa)
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 1.44 GB / 15.51 GB
      Shell: 2.7.1 - /usr/bin/fish
    Binaries:
      Node: 10.15.3 - /usr/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react-native: ^0.59.5 => 0.59.5 
    npmGlobalPackages:
      expo-image-picker: 4.0.0
      react-native-unimodules: 0.3.0
      react-native-navigation: 2.18.4
      create-react-native-web-app: 0.1.14
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      ...
```

### Steps to Reproduce

```
git clone https://github.com/retyui/expo-bag
cd expo-bag 
yarn start;
react-native run-android
```

Then press `Button` and provide  access permissions

### Expected Behavior

Will be opened a camera

### Actual Behavior

An aplication crashed always when call `launchCameraAsync`

### Reproducible Demo

https://github.com/retyui/expo-bag

**Comment by retyui** [comment]
https://github.com/expo/expo/issues/3702

**Comment by cruzach** [comment]
Hey @retyui,

You need to get Permissions for CAMERA and CAMERA_ROLL first.

Read through [the ImagePicker docs](https://docs.expo.io/versions/latest/sdk/imagepicker/#imagepickerlaunchcameraasyncoptions) for lots more info 😄 

-Charlie

**Comment by retyui** [comment]
@cruzach Please reopen issue!

I update demo: https://github.com/retyui/expo-bag/commit/df7cb21de0df920b8cea6f917366d0371a310adb

Nothing changed 

```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testdemo, PID: 7452
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=13, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.testdemo/com.testdemo.MainActivity}: android.os.FileUriExposedException: file:///data/user/0/com.testdemo/cache/ImagePicker/677ca68a-d3dc-4ee5-bc58-16c3a02d0ddb.jpg exposed beyond app through ClipData.Item.getUri()
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4584)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: android.os.FileUriExposedException: file:///data/user/0/com.testdemo/cache/ImagePicker/677ca68a-d3dc-4ee5-bc58-16c3a02d0ddb.jpg exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
        at android.net.Uri.checkFileUriExposed(Uri.java:2371)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:966)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10902)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10887)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
        at android.app.Activity.startActivityForResult(Activity.java:4688)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4646)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at expo.modules.imagepicker.ImagePickerModule.startActivityOnResult(ImagePickerModule.java:754)
        at expo.modules.imagepicker.ImagePickerModule.launchCameraWithPermissionsGranted(ImagePickerModule.java:201)
        at expo.modules.imagepicker.ImagePickerModule.access$000(ImagePickerModule.java:60)
        at expo.modules.imagepicker.ImagePickerModule$1.onPermissionsResult(ImagePickerModule.java:156)
        at expo.modules.permissions.PermissionsService$1.onPermissionResult(PermissionsService.java:56)
        at org.unimodules.adapters.react.services.UIManagerModuleWrapper$5.onRequestPermissionsResult(UIManagerModuleWrapper.java:217)
        at com.reactnativenavigation.NavigationActivity.onRequestPermissionsResult(NavigationActivity.java:117)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7940)
        at android.app.Activity.dispatchActivityResult(Activity.java:7762)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4577)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6981) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
```

**Comment by cruzach** [comment]
I believe this is a duplicate of #3706

**Comment by retyui** [comment]
I don't see the solution in that issue

**Comment by retyui** [comment]
@cruzach so...

**Comment by cruzach** [comment]
PR #3743 , which will be included in the next SDK or you can apply fixes manually as stated [here](https://github.com/expo/expo/issues/3706#issuecomment-472974427)

**Comment by AlbertVilaCalvo** [comment]
@cruzach FYI the PR #3734 doesn't fix the issue for me - see https://github.com/expo/expo/issues/3706#issuecomment-491611991
