### ISSUE TITLE
FileSystemModule.java did not reuse OkHttpClient causing memory leak when downloading 300+ files 

### ISSUE THREAD

**Issue by shcheuk** [expo/expo#4239]
## 🐛 Bug Report
okhttp suggested the correct way:
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html
That is to reuse the okhttpclient while expo create a new httpclient every time it call  FileSystem.downloadAsync function in https://github.com/expo/expo/blob/master/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java
getOkHttpClientBuilder() is called everytime downloadAsync is called and getOkHttpClientBuilder is creating a new instance of the client. This cause memory pile up sharply when downloading a number of files 10+. It eventually crash for out of memory (80 + files).

### Environment
 Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.15.4

     Enviroment: Android

### Steps to Reproduce
use FileSystem.downloadAsyc to download 300 - 1000+
for the repo demo, it crash at ~ the 330 th file download
### Expected Behavior
No crash same as SDK 28.0.0

### Actual Behavior
Crash,  expo console will output 404 file not find, while logcat will output the following:
`05-09 17:03:32.492: E/AndroidRuntime(7949): FATAL EXCEPTION: OkHttp Dispatcher
05-09 17:03:32.492: E/AndroidRuntime(7949): Process: host.exp.exponent, PID: 7949
05-09 17:03:32.492: E/AndroidRuntime(7949): java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.lang.Thread.nativeCreate(Native Method)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.lang.Thread.start(Thread.java:733)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1038)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1180)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.lang.Thread.run(Thread.java:764)
05-09 17:03:32.504: E/libc++abi(7949): terminating with uncaught exception of type std::bad_alloc: std::bad_alloc`

### Reproducible Demo

make this in app.js, start android simulator, expo start, a
```
import React from 'react';
import { StyleSheet, Text, View,Button } from 'react-native';
import {FileSystem} from 'expo'



export default class App extends React.Component {
	state ={count:0}
	downloadStart = async ()=>{
		
		const filenames = ['Tips2019_05_06-06_14_AWeqF.jpg','Tips2019_05_06-06_11_nXcoF.jpg','Tips2019_05_04-10_38_gG0FF.jpg','Tips2019_05_09-01_08_rD6ZF.jpg','Tips2019_05_09-01_00_G267F.jpg','Tips2019_05_09-07_49_4P3NF.jpg','Tips2019_05_09-07_46_JkAeF.jpg'];
		for (let op = 0; op < 10000; op++) {
				$name = filenames[op % 6];
				console.log('downloading ' ,(op % 6),$name,' count:',this.state.count,'/10000');
				var filepath = FileSystem.documentDirectory + $name;
				var url = 'https://files.swapcheck.net/swapcheckz/sites/default/files/imagecache/800x800/PortAndTravelPic/' + $name
				
				var response = await FileSystem.downloadAsync(url, filepath);
				if (response.status == 200) {
					this.setState({count:this.state.count+1})
				}
				await FileSystem.deleteAsync(filepath)
		}
	}
	render() { 
		return (
			<View style={{flex: 1,	backgroundColor: '#fff',alignItems: 'center',justifyContent: 'center',}}>
				<Text>FileDownloaded {this.state.count} /10000</Text>
				<Button title ='StartDownload' onPress={()=>{
					this.downloadStart()
				} } />
			</View>
		);
	}
}

```

**Comment by shcheuk** [comment]
May be this is the limitation of Async...if we use the same client, will it fall back to sync again....?

**Comment by shcheuk** [comment]
repo added
