### ISSUE TITLE
Clean expo init project - fail - Cannot find module 'babel-runtime/helpers/asyncToGenerator'

### ISSUE THREAD

**Issue by HazAT** [expo/expo#4301]
Getting an error with a clean `expo init` project, all the details can be found below:

Error:
`Cannot find module 'babel-runtime/helpers/asyncToGenerator'`

```
➜ node -v
v12.1.0
➜ yarn -v
1.13.0
➜ expo --version
2.18.3
```

```
➜ expo init AwesomeProject
? Choose a template: expo-template-blank
✔ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration/ · 100% completed
? Yarn v1.13.0 found. Use Yarn to install dependencies? Yes
Extracting project files...
Customizing project...
Initialized a git repository.
Installing dependencies...
yarn install v1.13.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "expo > expo-background-fetch@1.0.0" has unmet peer dependency "expo-task-manager-interface@~1.0.0".
warning "expo > expo-google-sign-in@2.0.0" has incorrect peer dependency "react-native@^0.55.4".
warning "expo > expo-location@2.0.1" has unmet peer dependency "expo-task-manager-interface@~1.0.0".
warning "expo > react-native-reanimated@1.0.0-alpha.11" has incorrect peer dependency "react@16.0.0-alpha.6".
warning "expo > react-native-reanimated@1.0.0-alpha.11" has incorrect peer dependency "react-native@^0.44.1".
warning "expo > expo-asset > url-loader@1.1.2" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 16.50s.

Your project is ready at /private/tmp/sadfhjhjkasd/AwesomeProject

To get started, you can type:

  cd AwesomeProject
  yarn start
```

```
➜ cd AwesomeProject
```

```
➜ EXPO_DEBUG=true yarn start
yarn run v1.13.0
$ expo start
Starting project at /private/tmp/sadfhjhjkasd/AwesomeProject
Cannot find module 'babel-runtime/helpers/asyncToGenerator'
Require stack:
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/commands/start.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
Require stack:
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/commands/start.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brentvatne** [comment]
@fson - do you have any idea what is happening here? I can't reproduce it locally

**Comment by sergeichestakov** [comment]
Hey @HazAT, I ran into a similar issue when I ejected from an Expo app (see the first half of this PR: https://github.com/expo/expo-cli/pull/567) and I was able to resolve it by adding the babel runtime package manually via `yarn add @babel/runtime`.

Your issue seems to be stemming from a different package (`babel-runtime`) but it might help to manually install that as a temporary workaround.

**Comment by ide** [comment]
It looks like the installation of Expo CLI did not go correctly. expo-cli depends on babel-runtime, so `@expo/dev-tools` should be able to find it as a peer dependency. I would search around the global node_modules folders to try to understand what is going on.

**Comment by HazAT** [comment]
So I tried again now with version `3.0.6` using `yarn`
Still same issue, now it even fails on `init`.

```
expo init expoproj2
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
Require stack:
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/commands/start.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/expo-cli@3.0.6/src/commands/start.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /expo-cli@3.0.6/src/exp.ts:354:29
    at Array.forEach (<anonymous>)
    at runAsync (/expo-cli@3.0.6/src/exp.ts:353:25)
    at /expo-cli@3.0.6/src/exp.ts:488:42
    at Object.run (/expo-cli@3.0.6/src/exp.ts:487:3)
    at Object.<anonymous> (/Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js:20:30)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js',
    '/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js',
    '/Users/haza/.config/yarn/global/node_modules/expo-cli/build/commands/start.js',
    '/Users/haza/.config/yarn/global/node_modules/expo-cli/build/exp.js',
    '/Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js'
  ]
}
Uncaught Error Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
Require stack:
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js
- /Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/commands/start.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/expo-cli@3.0.6/src/commands/start.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /expo-cli@3.0.6/src/exp.ts:354:29
    at Array.forEach (<anonymous>)
    at runAsync (/expo-cli@3.0.6/src/exp.ts:353:25)
    at /expo-cli@3.0.6/src/exp.ts:488:42
    at Object.run (/expo-cli@3.0.6/src/exp.ts:487:3)
    at Object.<anonymous> (/Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js:20:30)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js',
    '/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/index.js',
    '/Users/haza/.config/yarn/global/node_modules/expo-cli/build/commands/start.js',
    '/Users/haza/.config/yarn/global/node_modules/expo-cli/build/exp.js',
    '/Users/haza/.config/yarn/global/node_modules/expo-cli/bin/expo.js'
  ]
}
```

To folder `babel-runtime/helpers` exist but not the file with this naming.
```
➜ ls -al /Users/haza/.config/yarn/global/node_modules/babel-runtime/helpers
total 280
drwxr-xr-x  37 haza  staff  1184 Jul 30 13:11 .
drwxr-xr-x  11 haza  staff   352 Jul 30 13:16 ..
-rw-r--r--   1 haza  staff   738 Jul 30 13:08 async-to-generator.js
-rw-r--r--   1 haza  staff    87 Jul 30 13:08 bind.js
-rw-r--r--   1 haza  staff   211 Jul 30 13:08 class-call-check.js
-rw-r--r--   1 haza  staff   770 Jul 30 13:08 create-class.js
-rw-r--r--   1 haza  staff  1584 Jul 30 13:08 create-decorated-class.js
-rw-r--r--   1 haza  staff  1165 Jul 30 13:08 create-decorated-object.js
-rw-r--r--   1 haza  staff   299 Jul 30 13:08 default-props.js
-rw-r--r--   1 haza  staff   743 Jul 30 13:08 defaults.js
-rw-r--r--   1 haza  staff   510 Jul 30 13:08 define-decorated-property-descriptor.js
-rw-r--r--   1 haza  staff   403 Jul 30 13:08 define-property.js
-rw-r--r--   1 haza  staff   428 Jul 30 13:08 extends.js
-rw-r--r--   1 haza  staff  1015 Jul 30 13:08 get.js
-rw-r--r--   1 haza  staff    95 Jul 30 13:08 has-own.js
-rw-r--r--   1 haza  staff   780 Jul 30 13:08 inherits.js
-rw-r--r--   1 haza  staff   330 Jul 30 13:08 instanceof.js
-rw-r--r--   1 haza  staff   172 Jul 30 13:08 interop-export-wildcard.js
-rw-r--r--   1 haza  staff   148 Jul 30 13:08 interop-require-default.js
-rw-r--r--   1 haza  staff   366 Jul 30 13:08 interop-require-wildcard.js
-rw-r--r--   1 haza  staff   138 Jul 30 13:08 interop-require.js
-rw-r--r--   1 haza  staff   202 Jul 30 13:08 new-arrow-check.js
-rw-r--r--   1 haza  staff   155 Jul 30 13:08 object-destructuring-empty.js
-rw-r--r--   1 haza  staff   283 Jul 30 13:08 object-without-properties.js
-rw-r--r--   1 haza  staff   109 Jul 30 13:08 self-global.js
-rw-r--r--   1 haza  staff   665 Jul 30 13:08 set.js
-rw-r--r--   1 haza  staff    85 Jul 30 13:08 slice.js
-rw-r--r--   1 haza  staff   625 Jul 30 13:08 sliced-to-array-loose.js
-rw-r--r--   1 haza  staff  1008 Jul 30 13:08 sliced-to-array.js
-rw-r--r--   1 haza  staff   131 Jul 30 13:08 tagged-template-literal-loose.js
-rw-r--r--   1 haza  staff   392 Jul 30 13:08 tagged-template-literal.js
-rw-r--r--   1 haza  staff   216 Jul 30 13:08 temporal-assert-defined.js
-rw-r--r--   1 haza  staff    66 Jul 30 13:08 temporal-undefined.js
-rw-r--r--   1 haza  staff   212 Jul 30 13:08 to-array.js
-rw-r--r--   1 haza  staff   333 Jul 30 13:08 to-consumable-array.js
-rw-r--r--   1 haza  staff   220 Jul 30 13:08 typeof-react-element.js
-rw-r--r--   1 haza  staff   219 Jul 30 13:08 typeof.js
```

If I change the import in `/Users/haza/.config/yarn/global/node_modules/@expo/dev-tools/build/server/DevToolsServer.js` 
from: 
```
var _asyncToGenerator2 = require("babel-runtime/helpers/asyncToGenerator");
```
to:
```
var _asyncToGenerator2 = require("babel-runtime/helpers/async-to-generator");
```

This error disappears but the next one pops up.
So tbh I am not sure what's happening but I suppose something messes up in the expo-cli build process.

**Comment by HazAT** [comment]
So, I will close this issue.
I've cleaned everything, `yarn` `node` all global install packages and did a clean setup.
I suppose this happens because I use many different dev tools and at some point, expo was confused from where to fetch what package.

Anyway, thanks for everyone who spent time on this but I suppose this issue is not expo specific.
