### ISSUE TITLE
throw new Error('expo-cli supports Node versions 8.x.x, 10.x.x and newer.');

### ISSUE THREAD

**Issue by StudyTae** [expo/expo#4341]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

I was writing version 2.15.3. However, the update was posted and I'm update to 'expo-cli@2.18.5'.

But it causes an error.

```
.nvm/versions/node/v9.4.0/lib/node_modules/expo-cli/bin/expo.js:12
  throw new Error('expo-cli supports Node versions 8.x.x, 10.x.x and newer.');
  ^

Error: expo-cli supports Node versions 8.x.x, 10.x.x and newer.
    at Object.<anonymous> (/Users/.nvm/versions/node/v9.4.0/lib/node_modules/expo-cli/bin/expo.js:12:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

How can you solve this problem?

**Comment by StudyTae** [comment]
My node version is v9.4.0. It is higher than the v8 in error.

 But tell me to use more than v8.

> **This is a very wrong error,**

but I've increased the version of node to solve this problem.


**1. -$ node -v =>  v9.4.0**

**2. -$ nvm install v10.16.0 => Checksums matched!**

**3. -$ nvm use v10.16.0 => Now using node v10.16.0 (npm v6.9.0)**

**4. -$ node -v =>  v10.16.0**

**5. -$ expo init  exam =>   -bash: expo: command not found**

**6. -$ npm install -g expo-cli => + expo-cli@2.18.5**

**7. -$ expo init  exam => sucess**
