### ISSUE TITLE
getCurrentActivity() returns null in expo-payments-stripe using paymentRequestWithCardFormAsync()

### ISSUE THREAD

**Issue by nbgoodall** [expo/expo#4360]
## 🐛 Bug Report

That's the one! 

### Environment
```
Expo CLI 2.18.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.2.16 => 3.4.12
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.5.1
    npmGlobalPackages:
      expo-cli: 2.18.3
```

```
compileSdkVersion 28
buildToolsVersion '28.0.3'
minSdkVersion 21
targetSdkVersion 28
```

Using ExpoKit v32 on a Samsung Galaxy S7 (SM-G930F) running Android 8.0.0. Expo Payments is installed as per [the documentation](https://docs.expo.io/versions/latest/sdk/payments/).

### Steps to Reproduce

- Create new expo project
- Eject to ExpoKit SDK 32
- Install [Expo Payments](https://docs.expo.io/versions/latest/sdk/payments/) with a live Stripe publishable key
- After initialising with `Stripe.setOptionsAsync` in `componentWillMount`, call `Stripe. paymentRequestWithCardFormAsync()`
- Build app with `./gradlew assembleRelease`

### Expected Behavior

Calling `Stripe.paymentRequestWithCardFormAsync()` in production should open the card entry dialog (it works a-okay in development).

### Actual Behavior

It fails with this error:

```
06-01 17:08:46.437  2672  2772 W System.err: java.lang.reflect.InvocationTargetException
06-01 17:08:46.438  2672  2772 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-01 17:08:46.438  2672  2772 W System.err: 	at expo.a.c.invokeExportedMethod(ExportedModule.java:96)
06-01 17:08:46.438  2672  2772 W System.err: 	at expo.adapters.react.NativeModulesProxy.callMethod(NativeModulesProxy.java:117)
06-01 17:08:46.438  2672  2772 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-01 17:08:46.438  2672  2772 W System.err: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-01 17:08:46.438  2672  2772 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
06-01 17:08:46.438  2672  2772 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-01 17:08:46.438  2672  2772 W System.err: 	at android.os.Handler.handleCallback(Handler.java:789)
06-01 17:08:46.438  2672  2772 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-01 17:08:46.438  2672  2772 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
06-01 17:08:46.438  2672  2772 W System.err: 	at android.os.Looper.loop(Looper.java:164)
06-01 17:08:46.438  2672  2772 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
06-01 17:08:46.438  2672  2772 W System.err: 	at java.lang.Thread.run(Thread.java:764)
06-01 17:08:46.438  2672  2772 W System.err: Caused by: java.lang.NullPointerException: IllegalArgumentException
06-01 17:08:46.439  2672  2772 W System.err: 	at expo.modules.payments.stripe.util.ArgCheck.nonNull(ArgCheck.java:17)
06-01 17:08:46.439  2672  2772 W System.err: 	at expo.modules.payments.stripe.Errors.toErrorCode(Errors.java:33)
06-01 17:08:46.439  2672  2772 W System.err: 	at expo.modules.payments.stripe.StripeModule.paymentRequestWithCardForm(StripeModule.java:247)
06-01 17:08:46.439  2672  2772 W System.err: 	... 13 more
```

It appears that `getCurrentActivity()` returns `Null` in production from  [`StripeModule.java`](https://github.com/expo/expo/blob/master/packages/expo-payments-stripe/android/src/main/java/expo/modules/payments/stripe/StripeModule.java#L232); I don't know enough about Java/Android dev to tell you more.

### Reproducible Demo

If I'm not missing something obvious I'll try to update this with a demo next week. :pray:

**Comment by nbgoodall** [comment]
To anyone struggling with this – check your environment variables...
