### ISSUE TITLE
Expo SDK 33, bare-minimum template, Jest error on simple hook (useState)

### ISSUE THREAD

**Issue by dozouf** [expo/expo#4546]
### Environment
```
  Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
```
Also `react-native-cli 2.0.1`

### Steps to Reproduce

1. `expo init --template bare-minimum`
2. Fix babel config so jest tests run (in other words, rename `.babelrc` to `babel.config.js` and refactor accordingly)
3. Update `App.js` to:
```
import React, { useState } from "react";
import { Platform, StyleSheet, Text, View } from "react-native";

const instructions = Platform.select({
  ios: "Press Cmd+R to reload,\n" + "Cmd+D or shake for dev menu",
  android:
    "Double tap R on your keyboard to reload,\n" +
    "Shake or press menu button for dev menu"
});

export default function App() {
  const [value, setValue] = useState(false);
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>Welcome to React Native!</Text>
      <Text style={styles.instructions}>To get started, edit App.js</Text>
      <Text style={styles.instructions}>{instructions}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});
```
4. `yarn test`

(or)

1. `git clone https://github.com/dozouf/expo-sdk33-hooks-test`
2. `yarn`
3. `yarn test`

### Expected Behavior

Basic render test included in bare-minimum template passes.

### Actual Behavior

Test fails with:

```
yarn run v1.15.2
$ jest
 FAIL  __tests__/App.js (11.431s)
  × renders correctly (37ms)

  ● renders correctly

    Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

      10 |
      11 | export default function App() {
    > 12 |   const [value, setValue] = useState(false);
         |                             ^
      13 |   return (
      14 |     <View style={styles.container}>
      15 |       <Text style={styles.welcome}>Welcome to React Native!</Text>

      at invariant (node_modules/react/cjs/react.development.js:88:15)
      at resolveDispatcher (node_modules/react/cjs/react.development.js:1436:28)
      at useState (node_modules/react/cjs/react.development.js:1461:20)
      at App (App.js:12:29)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6889:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7389:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10149:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10181:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10267:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11135:7)

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8075
    The above error occurred in the <App> component:
        in App

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        15.033s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible Demo

[Expo SDK33 Hooks Test](https://github.com/dozouf/expo-sdk33-hooks-test)

**Comment by kgorol** [comment]
I am facing the same issue and asked the same question on [StackOverflow](https://stackoverflow.com/questions/57648015/simpliest-component-with-hooks-fails-jest-test-with-error-invariant-violation/57650920#57650920), but still no answer.

**Comment by kgorol** [comment]
Ok, upgrading `react-test-renderer` to version `16.8.3` fixed the issue for me.

**Comment by lukmccall** [comment]
> Ok, upgrading `react-test-renderer` to version `16.8.3` fixed the issue for me.

I think that is a solution. So, I'm closing this issue. Feel free to reopen it if this problem still occurs.
