### ISSUE TITLE
Cannot find module '@expo/image-utils'

### ISSUE THREAD

**Issue by vigneshraaj** [expo/expo#4702]
When I starts or restarts a local server for your app, its failing to start with following error.It was working fine until I updated expo-cli to 2.20.3 and expo-sdk to 33.0.7

Expecting it to provide URL of local server.

`$ expo start
Starting project at /Users/xyz/projects/proj-test/code
Expo DevTools is running at http://localhost:19002
Cannot find module '@expo/image-utils'
Error: Cannot find module '@expo/image-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/@expo/xdl@55.0.3/src/AssetUtils.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

`$ expo diagnostics

  Expo CLI 2.20.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: 33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
      react-navigation: 3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.3`

**Comment by ewein** [comment]
Yup I'm getting the same thing after updating my expo-cli.

**Comment by josantana** [comment]
Same thing, here.

**Comment by Fjorgejordan** [comment]
Same here

**Comment by chayancbnits** [comment]
I am facing the same issues.

**Comment by juyod** [comment]
Some thing...how to fix it?  I trired many version of expo-cli , but can't find the right version..

**Comment by andrewwippler** [comment]
Try version `33.0.6` as a work-around

**Comment by alex-melnyk** [comment]
Seems it's related to expo optimize:
```human$ EXPO_DEBUG=true expo optimize
Cannot find module '@expo/image-utils'
Error: Cannot find module '@expo/image-utils'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/@expo/xdl@55.0.3/src/AssetUtils.js:6:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)```

**Comment by INGJEISSON** [comment]
Tengo el mismo problema, recién comienzo a utilizar expo y me aparece éste error.
