### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Saneesh** [expo/expo#4711]
### Environment
```
Expo CLI 2.10.1 environment info:
   System:
     OS: macOS 10.14.5
     Shell: 3.2.57 - /bin/sh
   Binaries:
     Node: 12.4.0 - /usr/local/bin/node
     Yarn: 1.13.0 - /usr/local/bin/yarn
     npm: 6.9.0 - /usr/local/bin/npm
   IDEs:
     Android Studio: 3.2 AI-181.5540.7.32.5056338
     Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
   npmPackages:
     expo: ^33.0.0 => 33.0.7
     react: 16.8.3 => 16.8.3
     react-native: 0.59.8 => 0.59.8
     react-navigation: ^3.8.1 => 3.11.0
   npmGlobalPackages:
     expo-cli: 2.10.1
```

### Steps to Reproduce
`expo build:ios`

### Expected Behavior
It has to build successfully.

### Actual Behavior
```
[11:21:29] TypeError: Cannot read property 'forEach' of undefined
   at /xdl@53.0.1/src/Project.js:1032:26
   at Generator.next (<anonymous>)
   at step (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2236:191)
   at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2236:361
```

**Comment by Saneesh** [comment]
After updrading node, react-native, expo, expo-cli (sometimes `sudo  npm cache clean  --force` also needed to reflect the version upgrade)I have successfully build the app.

**Comment by RaduGrama** [comment]
> After updrading node, react-native, expo, expo-cli (sometimes `sudo npm cache clean --force` also needed to reflect the version upgrade)I have successfully build the app.

That doen't help one bit!
