### ISSUE TITLE
[expo-av] Bare React Native app Error: Unable to resolve module `nullthrows` 

### ISSUE THREAD

**Issue by Pines-Cheng** [expo/expo#4715]
### Environment
 
Bare React Native app

```
  Expo CLI 2.5.0 environment info:
    System:
      OS: macOS High Sierra 10.13.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.8.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
    npmGlobalPackages:
      expo-cli: 2.5.0
```

target: iOS

Bare React Native app

### Steps to Reproduce

Bare React Native app use `expo-av` , version 5.0.2 , throw error :

```shell
error: bundling failed: Error: Unable to resolve module `nullthrows` from `/Users/chengshuai/Work/taro/packages/taro-rn/node_modules/expo-av/build/Video.js`: Module `nullthrows` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/chengshuai/Work/taro/packages/taro-rn/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:1460)
    at ResolutionRequest.resolveDependency (/Users/chengshuai/Work/taro/packages/taro-rn/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/chengshuai/Work/taro/packages/taro-rn/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/chengshuai/Work/taro/packages/taro-rn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)

```

### Expected Behavior

use this package normal.

### Actual Behavior

![image](https://user-images.githubusercontent.com/9441951/60100650-c18d7680-978c-11e9-9305-62a024ae3685.png)

**Comment by ide** [comment]
Seems like we might just need to add this dependency to package.json. Should be simple if that’s the case.

**Comment by Pines-Cheng** [comment]
It‘s become normal after I add `nullthrows` dependency manual.
