### ISSUE TITLE
XDE 2.19.3 doesn't work on Linux

### ISSUE THREAD

**Issue by frol** [expo/expo#480]
*This issue was originally reported on XDE repo (https://github.com/expo/xde/issues/129).* /cc @brentvatne

XDE 2.19.3 "crashes" on start up:

```
Uncaught Error: Cannot find module 'core-js/library/fn/object/assign'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/tmp/.mount_WHk6KN/usr/bin/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_WHk6KN/usr/bin/resources/app/node_modules/babel-runtime/core-js/object/assign.js:1:186)
    at Object.<anonymous> (/tmp/.mount_WHk6KN/usr/bin/resources/app/node_modules/babel-runtime/core-js/object/assign.js:2:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

XDE 2.19.2 works just fine.

My system info:

* Arch Linux x64 (kernel version 4.12.3)
* XDE 2.19.3 AppImage downloaded from the official source

**Comment by frol** [comment]
XDE re-download fixed the issue.
