### ISSUE TITLE
Expo doesn´t start after Upgrade to SDK 33

### ISSUE THREAD

**Issue by michaelbenker** [expo/expo#4852]
Hello,

I have the trouble after my Upgrade to SDK 33 from 31.
Before the upgrade everything worked fine.

## 🐛 Bug Report

`Starting project at /Users/michaelbenker/Dropbox (Sistecs)/softwareentwicklung/Apps/sisManager
Expo DevTools is running at http://localhost:19002
Invalid Version: [object Object]
TypeError: Invalid Version: [object Object]
    at new SemVer (/Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:291:11)
    at compare (/Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:578:39)
    at lt (/Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:612:10)
    at cmp (/Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:653:21)
    at Comparator.intersects (/Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:745:5)
    at /Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:855:33
    at Array.every (<anonymous>)
    at /Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:854:33
    at Array.some (<anonymous>)
    at /Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:853:24
    at Array.every (<anonymous>)
    at /Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:852:28
    at Array.some (<anonymous>)
    at Range.intersects (/Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:851:19)
    at Function.intersects (/Users/michaelbenker/.config/yarn/global/node_modules/expo-cli/node_modules/semver/semver.js:1307:13)
    at _callee3$ (/expo-cli@2.21.2/src/commands/start.js:130:17)
    at tryCatch (/Users/michaelbenker/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/michaelbenker/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/michaelbenker/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/michaelbenker/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/michaelbenker/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
`

### Environment

`Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.npm-global/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.9.3 => 2.18.3 
`
Can someone help me?
Thanx Michael

**Comment by michaelbenker** [comment]
I found the reason:
In my package.json I had
`"dependencies": {
    "@expo/vector-icons": "*",`
I changed it to 
`"dependencies": {
    "@expo/vector-icons": "^10.0.1",`
Now it starts...
