### ISSUE TITLE
Can't build standalone app after upgrade to sdk 33

### ISSUE THREAD

**Issue by dawidczech355a** [expo/expo#4880]
Hi, after upgrade to Expo SDK 33, travis CI can't build standalone apps for android and iOS, always crash on this line: 
- $ travis_wait 60 ./ci/build-android.sh

and given logs: 

Failed to setup environment for android builds
  err: Error: yarn exited with non-zero code: 1
      at ChildProcess.completionListener (/home/travis/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:317:30)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:915:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
      ...
      at spawnAsync (/home/travis/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@55.0.7/src/detach/ExponentTools.js:126:21)
      at _installNodeModules (/home/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/android/index.ts:91:23)
      at <anonymous>
  platform: "android"

similar for the iOS:

wrong version of fastlane installed
  err: Error: Your fastlane on version 2.98.0. Please upgrade it to at least 2.99.0.
      at versionCheckFn (/Users/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/ios.ts:32:15)
      at <anonymous>
  platform: "ios"
  buildPhase: "setting up environment"

Failed to setup environment for ios builds
  err: Error: Tools required to perform standalone app build are missing. Please install them.
      at Object.ensureToolsAreInstalled (/Users/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/utils/toolsDetector.ts:44:11)
      at <anonymous>
  platform: "ios"

![Zrzut ekranu z 2019-07-09 14-35-23](https://user-images.githubusercontent.com/44273301/60888386-f7376280-a256-11e9-96a5-63fa0fc7e33a.png)

Every build finish with this errors

**Comment by AdamJNavarro** [comment]
Hey @dawidczech355a,

Can you try updating your Node and Xcode versions in your Travis environment? Both should be 10.x.

Cheers,
Adam

**Comment by dawidczech355a** [comment]
Thanks @AdamJNavarro from your response.
Upgrade Node and Xcode version in travis environment fix problem with iOS, Android still can't build well,

**Comment by AdamJNavarro** [comment]
Glad to hear we got iOS sorted out! Are you still encountering the same issue you mentioned above for android? Also, are you installing the latest version of `expo-cli` in your env or are you locking to a certain version?

**Comment by dawidczech355a** [comment]
Thank You for your involvement.
Yes, for android everything is the same . Android build exactly with same problem. I have installed latest version of expo-cli.
iOS version after upload on TestFlight display this issue, we did not change appKey from app.json. I don’t know what else could be the reason. I will be grateful for any tip.
![25B3899C-FD71-472E-9885-57F584ABC6ED](https://user-images.githubusercontent.com/44273301/60991228-6c379480-a34a-11e9-9cd4-9736ec694f3e.png)

**Comment by AdamJNavarro** [comment]
Can you try running `expo start --no-dev --minify` locally and see if you encounter any errors on iOS?

**Comment by dawidczech355a** [comment]
When I use this command line locally, everything is ok, any error doesn’t exists.

**Comment by dsokal** [comment]
Hello @dawidczech355a,

could you please send the full log output? The error you posted, which is:
```
Failed to setup environment for android builds
err: Error: yarn exited with non-zero code: 1
```
is a generic one so we can't really help you without looking at the previous logs.
