### ISSUE TITLE
`expo start` fails w/ expo-web

### ISSUE THREAD

**Issue by n-sviridenko** [expo/expo#4967]
### Environment

```
  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
```

### Steps to Reproduce

1. Add `web` to `app.json`
2. Install `react-dom` and `react-native-web` (w/o specifying version so that it will take the latest compatible)
3. Run `expo start`

### Expected Behavior

It runs w/o errors.

### Actual Behavior

After adding `web` to `app.json` on SDK 33, I'm having the following error after calling `expo start`:

```
(node:73688) UnhandledPromiseRejectionWarning: Error: Cannot find module './transformation/file/file'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<edited by me>/node_modules/metro/node_modules/@babel/core/lib/index.js:147:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

(node:73688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:73688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproducible Demo

-

**Comment by cruzach** [comment]
Hey @n-sviridenko -

I just tried to reproduce this on the tabs `expo init` template project, and was able to run on web just fine. `Expo CLI v2.21.2`

Could you provide steps to reproduce the error on our end? Without that, it's pretty tough to find the root cause
