### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by sylvainfraissenet** [expo/expo#5014]
Hi, 
I'm trying to build my app with following command : expo build:android and i receive the following message : 
Unable to find an existing Expo CLI instance for this directory, starting a new one...
Starting Metro Bundler on port 19001.
Tunnel URL not found, falled back to LAN URL.
Tunnel ready.
Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Building JavaScript bundle [====================================================================================================] 100%Finished building JavaScript bundle in 5801ms.
Analyzing assets
Building JavaScript bundle [====================================================================================================] 100%Finished building JavaScript bundle in 3485ms.
Finished building JavaScript bundle in 3298ms.
Finished building JavaScript bundle in 3102ms.
Uploading assets
No assets changed, skipped.
Processing asset bundle patterns:
- V:\DEV\xxxxx\xxx\xxxx\**\*
Uploading JavaScript bundles
Published
Your URL is

https://exp.host/@xxxx/xxxx

Checking if this build already exists...

Request failed with status code 404
Set EXPO_DEBUG=true in your env to view the stack trace.

Any idea ?
Many thanks 
Sylvain

**Comment by Bartewicz** [comment]
Same at me with this error:
`Checking if this build already exists...

Request failed with status code 404
Error: Request failed with status code 404
    at createError (C:\Users\BRITENET\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\xdl\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\BRITENET\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\xdl\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\BRITENET\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\xdl\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by cruzach** [comment]
Can one of you/both of you share your `app.json`?
