### ISSUE TITLE
 images, icons and maps are not displayed in app when creating release app bundle after updating ExpoKit SDK 32 to SDK 33

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#5068]
Environment

Expo CLI 3.0.2 environment info:
System:
OS: macOS 10.14.5
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - /usr/local/bin/node
Yarn: 1.12.3 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.4 AI-183.6156.11.34.5692245
Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
npmPackages:
expo: ^33.0.0 => 33.0.7
react: 16.8.3 => 16.8.3
react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
react-navigation: ^3.2.1 => 3.2.1
npmGlobalPackages:
expo-cli: 3.0.2

ExpoKit Android

Steps to Reproduce

Upgrade ExpoKit SDK from 32 to 33
Create release app bundle 
Install release app bundle ---> images, icons and maps are not displayed in app anymore 

Expected Behavior

User can see images, icons and maps in the app

Actual Behavior
 images, icons and maps are not displayed in app anymore

**Comment by cruzach** [comment]
Is there anything present in the device logs that might be able to shed some light on the issue? Not sure why maps would be tied up with this, as both images and icons are assets. Are you using [Mapview](https://docs.expo.io/versions/latest/sdk/map-view/) for your maps?

**Comment by Luckygirlllll** [comment]
@cruzach The problem with map is pretty clear, expo removed maps from expo, and now in Android it requires to use react-native-maps, which requires code refactoring. 

However, problem with images and icons are not clear at all.

**Comment by Luckygirlllll** [comment]
And, by the way, after the code refactoring map is not working in ExpoKit: 

https://stackoverflow.com/questions/57221772/app-is-having-trouble-with-google-play-services-please-try-again-in-expokit-pro

**Comment by Luckygirlllll** [comment]
It’s release app bundle, how can I get device logs, from release app bundle?

**Comment by cruzach** [comment]
I think [this page of the docs](https://docs.expo.io/versions/latest/workflow/logging/#optional-manually-access-device-logs) should help you out

**Comment by Luckygirlllll** [comment]
Here what I see, when I run adb logcat:

```
2019-07-28 17:13:20.093 5457-5457/? E/CatchNotificationsService: Invalid notification data
2019-07-28 17:13:21.776 3200-3762/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(26)
2019-07-28 17:13:21.788 4082-4082/? E/KeyguardUpdateMonitor: handleStartedWakingUp start 1
2019-07-28 17:13:21.788 4082-4082/? E/KeyguardFingerPrint: updateFingerprintListeningState#mFingerprintRunningState=0 shouldListenForFingerprint=false
2019-07-28 17:13:21.796 3200-3200/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(26)
2019-07-28 17:13:21.803 4082-4082/? E/KeyguardUpdateMonitor: handleStartedWakingUp end
2019-07-28 17:13:21.803 4408-4679/? E/ImsAdaptorImpl: setSSACInfo : ImsAdaptorImpl.
2019-07-28 17:13:21.804 3200-3200/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(26)
2019-07-28 17:13:21.892 14169-14169/? E/SPPClientService: [[PushClientService]] reqType : 0
2019-07-28 17:13:21.936 14169-14169/? E/SPPClientService: [[PushClientService]] F:false, D:false, E:false, T:false, S:true, R:false
2019-07-28 17:13:22.059 23218-23218/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-07-28 17:13:22.059 23218-23218/? E/libpersona: scanKnoxPersonas
2019-07-28 17:13:22.059 23218-23218/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
2019-07-28 17:13:22.151 4055-4196/? E/bt_btif: btif_dm_upstreams_evt: ev: BTA_DM_ENER_INFO_READ
2019-07-28 17:13:22.175 4055-4559/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler, msg: MESSAGE_SCAN_START, appName: com.google.uid.shared, scannerId: 6, reportDelayMillis=0
2019-07-28 17:13:22.186 4055-4557/? E/BtGatt.ScanManager: default value of curScanSetting 0 is choosen
2019-07-28 17:13:22.201 4055-4559/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler, msg: MESSAGE_SCAN_STOP, appName: android.uid.bcmgr, scannerId: 5, reportDelayMillis=0
2019-07-28 17:13:22.208 3667-3781/? E/memtrack: Couldn't load memtrack module
2019-07-28 17:13:22.253 4055-4559/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler, msg: MESSAGE_SCAN_START, appName: com.google.uid.shared, scannerId: 5, reportDelayMillis=0
2019-07-28 17:13:22.295 4055-4559/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler, msg: MESSAGE_SCAN_START, appName: android.uid.bcmgr, scannerId: 7, reportDelayMillis=0
2019-07-28 17:13:22.851 3200-3200/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(26)
2019-07-28 17:13:22.885 23263-23263/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-07-28 17:13:22.886 23263-23263/? E/libpersona: scanKnoxPersonas
2019-07-28 17:13:22.886 23263-23263/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
2019-07-28 17:13:23.078 23263-23263/? E/ACRA: Initializing ANR detector for process: com.facebook.appmanager
2019-07-28 17:13:23.225 4082-4082/? E/KeyguardFingerPrint: updateFingerprintListeningState#mFingerprintRunningState=0 shouldListenForFingerprint=false
2019-07-28 17:13:23.306 4082-4082/? E/KeyguardFingerPrint: updateFingerprintListeningState#mFingerprintRunningState=0 shouldListenForFingerprint=false
2019-07-28 17:13:23.311 3667-3667/? E/MotionRecognitionService:   mReceiver.onReceive : ACTION_USER_PRESENT  :: UNLOCK SCREEN
2019-07-28 17:13:23.340 22405-22405/? E/MtpService: In MTPAPP onReceive:android.intent.action.USER_PRESENT
2019-07-28 17:13:23.340 22405-22405/? E/MtpService: Inside ACTION_USER_PRESENT:android.intent.action.USER_PRESENT
2019-07-28 17:13:23.494 23309-23309/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-07-28 17:13:23.495 23309-23309/? E/libpersona: scanKnoxPersonas
2019-07-28 17:13:23.495 23309-23309/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory

2019-07-28 16:59:30.531 8365-8365/? E/NotificationData: getIconBitmap() ClassCastException
    java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
        at com.samsung.android.widgetapp.briefing.data.NotificationData.findPackageIcon(NotificationData.java:128)
        at com.samsung.android.widgetapp.briefing.data.NotificationData.getIcon(NotificationData.java:79)
        at com.samsung.android.widgetapp.briefing.CatchNotificationsView.inflateTextViews(CatchNotificationsView.java:230)
        at com.samsung.android.widgetapp.briefing.CatchNotificationsView.makeNotificationsPanelView(CatchNotificationsView.java:179)
        at com.samsung.android.widgetapp.briefing.CatchNotificationsView.makePanel(CatchNotificationsView.java:162)
        at com.samsung.android.widgetapp.briefing.CatchNotificationsView.onReceiveContentInfo(CatchNotificationsView.java:345)
        at com.samsung.android.app.cocktailbarservice.ui.panel.SepRemoteLoadablePanel.setData(SepRemoteLoadablePanel.java:22)
        at com.samsung.android.app.cocktailbarservice.ui.panel.AbstractRemotePanelView.composeView(AbstractRemotePanelView.java:190)
        at com.samsung.android.app.cocktailbarservice.ui.panel.AbstractCocktailPanelView.updateCocktail(AbstractCocktailPanelView.java:161)
        at com.samsung.android.app.cocktailbarservice.manager.CocktailBarPanelManager.updateContainedPanel(CocktailBarPanelManager.java:277)
        at com.samsung.android.app.cocktailbarservice.manager.CocktailBarPanelManager.updatePanelItem(CocktailBarPanelManager.java:186)
        at com.samsung.android.app.cocktailbarservice.controller.CocktailBarUiController.handleUpdateCocktail(CocktailBarUiController.java:1003)
        at com.samsung.android.app.cocktailbarservice.controller.CocktailBarUiController.access$1200(CocktailBarUiController.java:79)
        at com.samsung.android.app.cocktailbarservice.controller.CocktailBarUiController$InnerHandler.dispatchMessage(CocktailBarUiController.java:986)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2019-07-28 16:59:30.531 8365-8365/? E/NotificationData: Bitmap data null or empty for com.google.android.apps.playconsole
 
2019-07-28 17:13:30.220 3667-3781/? E/memtrack: Couldn't load memtrack module
```

**Comment by Luckygirlllll** [comment]
Other users facing the same issue as well: https://forums.expo.io/t/the-image-is-not-visible-in-expokit/24022

**Comment by amitava82** [comment]
Not sure if this is related, after updating to SDK34, I'm seeing white square, asian characters instead of icons.

**Comment by cruzach** [comment]
@amitava82 we technically haven't released SDK 34 yet (we will be, this week). You'll need to look out for our blog post on that release, and follow the necessary upgrade instructions

**Comment by amitava82** [comment]
Okay, it worked after I cleared all caches (npm, expo, metro etc) and rebuilt.

**Comment by sweebee** [comment]
I facing the same issue with the square question marks. I followed the upgrade instructions.

**Comment by cruzach** [comment]
@sweebee have you tried the solution above? 
> Okay, it worked after I cleared all caches (npm, expo, metro etc) and rebuilt.

**Comment by sweebee** [comment]
how do i clear the metro cache?

On android the icons work fine though, on iOS they dont.

**Comment by amitava82** [comment]
I followed this `https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352`

**Comment by sweebee** [comment]
thx, cleared everything. Do I need to upload a new build to the appstore? because publishing doesn't work, icons still not showing.

**Comment by Luckygirlllll** [comment]
@sweebee Did you find any other solution regarding icons? I also have question marks in IOS instead of vector icons, I have cleared everything, but it didn't help.

**Comment by sweebee** [comment]
@Luckygirlllll yes, it was a bug in expo font. Fixed in v 6.0.1.

**Comment by Luckygirlllll** [comment]
@sweebee I have  "@expo/vector-icons": "^10.0.1". you are using  v 6.0.1?

**Comment by sweebee** [comment]
expo vector-icons is a different package.

my versions:
```
expo: 34.0.3
@expo/vector-icons: 10.0.3
expo-font: 6.0.1
```

If you install expo ```34.0.3``` it should work because it installs the latest versions for icons/font.

**Comment by Luckygirlllll** [comment]
@sweebee Do you use expo or expoKit project?

**Comment by sweebee** [comment]
both, I have 1 app with expoKit and the rest just managed expo.

**Comment by Luckygirlllll** [comment]
@sweebee Updating expo-font solved this issue!

**Comment by MHauray** [comment]
Hello,

I managed to correct my image display problem by removing this line from the app.json file. If it can help others :)

Expo SDK 34

"assetBundlePatterns": [
       "** / *"
     ]

Regards,

**Comment by cruzach** [comment]
Closing since it looks like updating `expo-font` solves this issue 👍

**Comment by mi-mazouz** [comment]
not working from sdk 33 to sdk 34, I updated expo-font...

**Comment by felipegouveiae** [comment]
@mi-mazouz were you able to fix that issue? I have found the same problem here.

**Comment by crypteriumguy** [comment]
Experiencing the same issue  
Trying decreasing/updating expo-font, icons and etc. dependencies doesn't help solving the problem
