### ISSUE TITLE
HeadlessTasks not working on Android devices, Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by prav33n** [expo/expo#5070]
I am using firebase to push real time config update to my app, receiving real time updates work when the app is in foreground. When the app is in the background i am having 2 errors. 
We use a detached EXPO application. 
Expo SDK version : 33

1. I am getting a App crash with the following error 

``` 
java.lang.RuntimeException: Unable to start service io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService@9e4124f with Intent { cmp=com.qliro.qliro.dev/io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService (has extras) }: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at com.facebook.react.HeadlessJsTaskService.getReactNativeHost(HeadlessJsTaskService.java:171)
        at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
        at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:52)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

if i implement the `public class MainApplication extends ExpoApplication implements AppLoaderPackagesProviderInterface<ReactPackage>,ReactApplication `  ReactApplication I get the issue 2 

```2019-07-25 12:10:27.656 7355-7355/com.qliro.qliro.dev W/unknown:ReactNative: Packager connection already open, nooping.
2019-07-25 12:10:27.796 7355-7537/com.qliro.qliro.dev W/ReactNativeJS: The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
2019-07-25 12:10:27.869 7355-7537/com.qliro.qliro.dev W/ReactNativeJS: No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
2019-07-25 12:10:27.890 7355-7537/com.qliro.qliro.dev E/ReactNativeJS: The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.
2019-07-25 12:10:27.898 7355-7537/com.qliro.qliro.dev E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling startHeadlessTask)```

Android Manifest : 
```
`        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
        <service
            android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService"/>`
```

JS File 
// Current main application
AppRegistry.registerComponent('App Name', () => App);
// New task registration
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);


I tried creating a native headless service and still had the same error.  Is there a way to get HeadlessTasks working with expo kit detached  ? 

Thank you for your help.

**Comment by cruzach** [comment]
Hey @prav33n - could you go back and follow the issue template? It asks for all the information we need to help you out 😄 

Also- when you're sharing a block of code or logs, it's always better to format with   ```    before and after, instead of just one tick

**Comment by prav33n** [comment]
Thank you, i will update it with the issue template. 
I worked around it for now with native code, would be nice to understand why its not working our setup.

**Comment by niv-breez** [comment]
Hi, Can you share how did you worked around it ? I have the same issue.

**Comment by prav33n** [comment]
Hi, 
I went with the  native code,  i created a background service for Android and handled it in the service. 
For IOS  I havent done anything yet.

**Comment by niv-breez** [comment]
Can you share the code and how to integrate it ?

**Comment by prav33n** [comment]
Let me find the code , i stashed the solution since its not completely done.

**Comment by prav33n** [comment]
The solutions is specific to my case,  i want to handle firebase remote messages when the app is closed. I am not sure what your case, in my case the service listens to remote config intent, hope this helps 

`AndroidManifest.xml
        <service
          android:name=".RemoteMessageService"
          android:exported="false">
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
       </service>


RemoteMessageService.java

package host.exp.exponent;
import android.util.Log;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
import com.google.firebase.remoteconfig.FirebaseRemoteConfig;

import java.util.concurrent.Executor;

public class RemoteMessageService extends FirebaseMessagingService {

    private static final String TAG = "FirebaseMessageService";

    /**
     * Called when message is received.
     *
     * @param remoteMessage Object representing the message received from Firebase Cloud Messaging.
     */
    // [START receive_message]
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        FirebaseRemoteConfig  mFirebaseRemoteConfig = FirebaseRemoteConfig.getInstance();
        mFirebaseRemoteConfig.fetch(0).addOnCompleteListener((OnCompleteListener<Void>) task -> {
            if (task.isSuccessful()) {
                // After config data is successfully fetched, it must be activated before newly fetched
                // values are returned.
                mFirebaseRemoteConfig.getInstance().activate();
            } else {
                Log.d(TAG, "Fetch Failed");
            }
        });
    }
}
`

**Comment by niv-breez** [comment]
Thank you for sharing the code!
