### ISSUE TITLE
HeadlessTasks not working on Android devices, Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by prav33n** [expo/expo#5087]
## 🐛 Bug Report
I am using firebase to push real time config update to my app, receiving real time updates work when the app is in foreground. When the app is in the background i am having 2 errors. 
We use a detached EXPO application. 
Expo SDK version : 33

### Environment

Expo CLI 3.0.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 3.4.12 => 3.4.12 
      expo: 33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: 3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.0.

### Steps to Reproduce
I am using the following code to trigger a headless task in Android 
```JS File 
// Current main application
AppRegistry.registerComponent('App Name', () => App);
// New task registration
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessage);
const bgMessage = (message) => {
    // handle your message
    console.log("RemoteMessage", message);
    return Promise.resolve();
} ```

### Expected Behavior
The app should log out the message when we trigger a remote config updated from firebase console. 

### Actual Behavior
The app crashes with 2 errors based on these 2 steps 
1. I am getting a App crash with the following error 

`java.lang.RuntimeException: Unable to start service io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService@9e4124f with Intent { cmp=com.qliro.qliro.dev/io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService (has extras) }: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at com.facebook.react.HeadlessJsTaskService.getReactNativeHost(HeadlessJsTaskService.java:171)
        at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
        at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:52)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

if i implement the 
```public class MainApplication extends ExpoApplication implements AppLoaderPackagesProviderInterface<ReactPackage>,ReactApplication``` 
 I get the issue 2 

`2019-07-25 12:10:27.656 7355-7355/com.qliro.qliro.dev W/unknown:ReactNative: Packager connection already open, nooping.
2019-07-25 12:10:27.796 7355-7537/com.qliro.qliro.dev W/ReactNativeJS: The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
2019-07-25 12:10:27.869 7355-7537/com.qliro.qliro.dev W/ReactNativeJS: No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
2019-07-25 12:10:27.890 7355-7537/com.qliro.qliro.dev E/ReactNativeJS: The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.
2019-07-25 12:10:27.898 7355-7537/com.qliro.qliro.dev E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling startHeadlessTask)`

### Reproducible Demo
Unfortunately i cant share the app here. since i need to authenticate app for firebase services. I worked around using native code for now.

**Comment by tsapeta** [comment]
We no longer support ExpoKit and I encourage you to use bare workflow instead if you're still experiencing this issue. Closing this report, but feel free to open a new one if this still happens in bare workflow 🙂
