### ISSUE TITLE
[expo-camera & expo-face-detector] App crashing after building.

### ISSUE THREAD

**Issue by michaelszerman-Ripio** [expo/expo#5113]
### Environment

Native Project ( started with: `react-native init` )
```
"react": "16.8.3",
"react-native": "0.59.8",
"react-native-unimodules": "^0.5.0",
"expo-camera": "^6.0.0",
"expo-face-detector": "^6.0.0",
```

### Steps to Reproduce

1. Create a new project: `react-native init expoCamera --version react-native@0.59.8`

2. Install React Native Unimodules following the steps in the repo:
[https://github.com/unimodules/react-native-unimodules/](https://github.com/unimodules/react-native-unimodules/)

3. Install expo-camera following the steps in the repo:
[https://github.com/expo/expo/tree/master/packages/expo-camera](https://github.com/expo/expo/tree/master/packages/expo-camera)

4. Render `<Camera>` from `'expo-camera'` with the prop `onFacesDetected`

5. Try to run the application in Android: `react-native run-android`

### Expected Behavior

Be able to detect faces using `<Camera onFacesDetected={}>`

### Actual Behavior

The App crashes after is built.

### Reproducible Demo

https://github.com/michaelszerman-Ripio/expoCameraTest

**Comment by cruzach** [comment]
Hey @michaelszerman-Ripio - does the same happen on a bare project start via `expo-cli` where unimodules come preinstalled?

Also, if you could grab the [device logs](https://docs.expo.io/versions/latest/workflow/logging/#view-logs-from-android-device-or-emulator) from the crash, that would help!

**Comment by michaelszerman-Ripio** [comment]
Hello @cruzach! Yes, it also crashes on a project start via `expo-cli`.

Log with errors: [https://docs.google.com/document/d/1LUbTrj8i2I3rBIl_YmfbDEPU0FJiLJWz7Fpo9RtO7p8/edit?usp=sharing](https://docs.google.com/document/d/1LUbTrj8i2I3rBIl_YmfbDEPU0FJiLJWz7Fpo9RtO7p8/edit?usp=sharing)

**Comment by Slals** [comment]
I had this issue, in my case I had those logs :

```
08-06 21:32:26.701  2935  2935 E AndroidRuntime: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.myapp. Make sure to call FirebaseApp.initializeApp(Context) first.
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@17.0.0:234)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at com.google.firebase.ml.vision.FirebaseVision.getInstance(Unknown Source:1)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at expo.modules.facedetector.ExpoFaceDetector.createFaceDetector(ExpoFaceDetector.java:235)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at expo.modules.facedetector.ExpoFaceDetector.detectFaces(ExpoFaceDetector.java:94)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at expo.modules.camera.tasks.FaceDetectorTask.execute(FaceDetectorTask.java:40)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at expo.modules.camera.ExpoCameraView$1.onFramePreview(ExpoCameraView.java:142)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at com.google.android.cameraview.CameraView$CallbackBridge.onFramePreview(CameraView.java:604)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at com.google.android.cameraview.Camera1.onPreviewFrame(Camera1.java:766)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1203)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
08-06 21:32:26.701  2935  2935 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

To fix this you have to setup Firebase for your app.

```
// android/build.gradle
...
dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.0'
}
...
```
// android/app/build.gradle
...
// Bottom of the file
apply plugin: 'com.google.gms.google-services'
```

```
// MainApplication.java
```

```

**Comment by JClackett** [comment]
Confirmed: adding the firebase config fixes the crash, make sure to add a google-services.json to /app!

**Comment by chirag773** [comment]
> Confirmed: adding the firebase config fixes the crash, make sure to add a google-services.json to /app!

where should we have to add this? in which file and where can you please write in detail?

**Comment by chirag773** [comment]
> ##  Bug Report
> ### Environment
> Native Project ( started with: `react-native init` )
> 
> ```
> "react": "16.8.3",
> "react-native": "0.59.8",
> "react-native-unimodules": "^0.5.0",
> "expo-camera": "^6.0.0",
> "expo-face-detector": "^6.0.0",
> ```
> 
> ### Steps to Reproduce
> 1. Create a new project: `react-native init expoCamera --version react-native@0.59.8`
> 2. Install React Native Unimodules following the steps in the repo:
>    https://github.com/unimodules/react-native-unimodules/
> 3. Install expo-camera following the steps in the repo:
>    https://github.com/expo/expo/tree/master/packages/expo-camera
> 4. Render `<Camera>` from `'expo-camera'` with the prop `onFacesDetected`
> 5. Try to run the application in Android: `react-native run-android`
> 
> ### Expected Behavior
> Be able to detect faces using `<Camera onFacesDetected={}>`
> 
> ### Actual Behavior
> The App crashes after is built.
> 
> ### Reproducible Demo
> https://github.com/michaelszerman-Ripio/expoCameraTest

hey, how did you solved this issue? please tell us

**Comment by JClackett** [comment]
> > Confirmed: adding the firebase config fixes the crash, make sure to add a google-services.json to /app!
> 
> 
> 
> where should we have to add this? in which file and where can you please write in detail?

android/app directory

**Comment by chirag773** [comment]
> > > Confirmed: adding the firebase config fixes the crash, make sure to add a google-services.json to /app!
> > 
> > 
> > where should we have to add this? in which file and where can you please write in detail?
> 
> android/app directory

i have done that and now it is showing me below error
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.facedectorapp'

**Comment by JClackett** [comment]
> > > > Confirmed: adding the firebase config fixes the crash, make sure to add a google-services.json to /app!
> 
> > > 
> 
> > > 
> 
> > > where should we have to add this? in which file and where can you please write in detail?
> 
> > 
> 
> > android/app directory
> 
> 
> 
> i have done that and now it is showing me below error
> 
> * What went wrong:
> 
> Execution failed for task ':app:processDebugGoogleServices'.
> 
> No matching client found for package name 'com.facedectorapp'
> 
> 
> 
> 

Sounds like you've named the Android package different to what you put in the firebase config,

**Comment by davincikart** [comment]
But I have a different error code. It works well with some devices but not on all other devices.  

onFacesDetected in expo-camera crashes the android.

Error log:
```

Fatal Exception: java.lang.IllegalArgumentException: Invalid image data size.
       at com.google.android.gms.vision.Frame$Builder.setImageData(com.google.android.gms:play-services-vision-common@@19.0.0:13)
       at com.google.firebase.ml.vision.common.FirebaseVisionImage.zza(com.google.firebase:firebase-ml-vision@@24.0.1:152)
       at com.google.android.gms.internal.firebase_ml.zzri.zza(com.google.firebase:firebase-ml-vision@@24.0.1:11)
       at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.detectInImage(com.google.firebase:firebase-ml-vision@@24.0.1:25)
       at expo.modules.facedetector.ExpoFaceDetector.detectFaces(ExpoFaceDetector.kt:111)
       at expo.modules.camera.tasks.FaceDetectorTask.execute(FaceDetectorTask.kt:17)
       at expo.modules.camera.ExpoCameraView$1.onFramePreview(ExpoCameraView.kt:324)
       at com.google.android.cameraview.CameraView$CallbackBridge.onFramePreview(CameraView.java:604)
       at com.google.android.cameraview.Camera1.onPreviewFrame(Camera1.java:766)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1298)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
```


Package.json

  ```
  "expo": "~44.0.2",
    "expo-av": "~10.2.0",
    "expo-camera": "~12.1.2",
    "expo-dev-client": "~0.8.5",
    "expo-device": "~4.1.0",
    "expo-face-detector": "~11.1.3",
    "expo-file-system": "~13.1.4",
    "expo-gl": "~11.1.1",
    "expo-gl-cpp": "~11.1.0",
    "expo-image-manipulator": "~10.2.0",
    "expo-local-authentication": "~12.1.0",
    "expo-localization": "~12.0.0",
    "expo-location": "~14.0.1",
```

**Comment by danyalutsevich** [comment]
is there a way to fix it without doing expo eject

**Comment by hfllr** [comment]
did you guys find any fix yet @danyalutsevich @davincikart ? I'm in managed workflow as well, have an app in production and it happens for some devices, really frustrating!

**Comment by danyalutsevich** [comment]
@hfllr I still have this problem

**Comment by SaifullahIlyas** [comment]
> But I have a different error code. It works well with some devices but not on all other devices.
> 
> onFacesDetected in expo-camera crashes the android.
> 
> Error log:
> 
> ```
> 
> Fatal Exception: java.lang.IllegalArgumentException: Invalid image data size.
>        at com.google.android.gms.vision.Frame$Builder.setImageData(com.google.android.gms:play-services-vision-common@@19.0.0:13)
>        at com.google.firebase.ml.vision.common.FirebaseVisionImage.zza(com.google.firebase:firebase-ml-vision@@24.0.1:152)
>        at com.google.android.gms.internal.firebase_ml.zzri.zza(com.google.firebase:firebase-ml-vision@@24.0.1:11)
>        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.detectInImage(com.google.firebase:firebase-ml-vision@@24.0.1:25)
>        at expo.modules.facedetector.ExpoFaceDetector.detectFaces(ExpoFaceDetector.kt:111)
>        at expo.modules.camera.tasks.FaceDetectorTask.execute(FaceDetectorTask.kt:17)
>        at expo.modules.camera.ExpoCameraView$1.onFramePreview(ExpoCameraView.kt:324)
>        at com.google.android.cameraview.CameraView$CallbackBridge.onFramePreview(CameraView.java:604)
>        at com.google.android.cameraview.Camera1.onPreviewFrame(Camera1.java:766)
>        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1298)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:201)
>        at android.app.ActivityThread.main(ActivityThread.java:6810)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
> ```
> 
> Package.json
> 
> ```
> "expo": "~44.0.2",
>   "expo-av": "~10.2.0",
>   "expo-camera": "~12.1.2",
>   "expo-dev-client": "~0.8.5",
>   "expo-device": "~4.1.0",
>   "expo-face-detector": "~11.1.3",
>   "expo-file-system": "~13.1.4",
>   "expo-gl": "~11.1.1",
>   "expo-gl-cpp": "~11.1.0",
>   "expo-image-manipulator": "~10.2.0",
>   "expo-local-authentication": "~12.1.0",
>   "expo-localization": "~12.0.0",
>   "expo-location": "~14.0.1",
> ```

Any solution for this?

**Comment by danyalutsevich** [comment]
still cant fix it (

**Comment by matheusPcruz18** [comment]
Set the face-detector settings inside the onCameraReady prop with useState just helped me.
Source: https://stackoverflow.com/a/73713334/21635555

**Comment by JoyceQuerubino** [comment]
In my case, the error was FATAL EXCEPTION, so the error was not directly printed to me, the application just closed itself.

But in PlayStore i recived the error: `at com.google.mlkit.vision.common.InputImage.fromByteArray(com.google.mlkit:vision-common@@17.1.0:2).`

And after a while of investigation I managed to solve the error by adding the 'ratio' value, I don't know why, but it fixed the problem.

```
  <CameraContent
            ratio={'1:1'}
            type={CameraType.front}
            isConfigScreen={isConfigScreen}
            onFacesDetected={handleFacesDetected}
            faceDetectorSettings={{
              mode: FaceDetector.FaceDetectorMode.fast,
              detectLandmarks: FaceDetector.FaceDetectorLandmarks.all,
              runClassifications: FaceDetector.FaceDetectorClassifications.all,
              minDetectionInterval: 800,
              tracking: true,
            }}
 />
```
