### ISSUE TITLE
`pod install` failed on detached CRNA app

### ISSUE THREAD

**Issue by PaperMonster** [expo/expo#515]
I detached an app created with CRNA following instructions on [this document](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md). Then I run `npm install` on the project, followed by `pod install` in ios folder. However, there was an error:
````
[!] Error installing ExpoKit
[!] Failed to download 'ExpoKit'.
````

Full verbose:
````
$ pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-shobshop-backoffice-mobile`: (``)

Fetching external sources
-> Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/1.18.2`
 > Git download
 > Git download
     $ /usr/bin/git clone http://github.com/expo/expo.git
     /var/folders/pp/z0thq9tj63d5b1rslj97w69r0000gn/T/d20170818-27965-17ma8qn --template= --single-branch
     --depth 1 --branch ios/1.18.2
     Cloning into '/var/folders/pp/z0thq9tj63d5b1rslj97w69r0000gn/T/d20170818-27965-17ma8qn'...
     fatal: unable to access 'http://github.com/expo/expo.git/': Recv failure: Connection reset by peer

[!] Error installing ExpoKit
[!] Failed to download 'ExpoKit'.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:119:in `rescue in block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:114:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:686:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:662:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:661:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:661:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:660:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
````

The Podfile generated from detachment process:
````
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'shobshop-backoffice-mobile' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/1.18.2",
    :subspecs => [
      "Core",
      "CPP"
    ]

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "BatchedBridge"
    ]
  pod 'Yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
````

Did I miss something during the native code generation? My CocoaPods version is 1.3.1 and create-react-native-app version is 1.0.0

**Comment by ide** [comment]
Are you able to access http://github.com from the command line? It looks like your download got interrupted.

**Comment by PaperMonster** [comment]
@ide I think you're right. I've just tried again at home and now all pods are installed successfully. Might be connection problem at my office. Thanks!

**Comment by JulianKingman** [comment]
I had this error message: 
```bash
     git-lfs smudge 'ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks/GoogleInterchangeUtilities.framework/GoogleInterchangeUtilities': git-lfs: command not found
     error: external filter 'git-lfs smudge %f' failed 127
     error: external filter 'git-lfs smudge %f' failed
     fatal: ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks/GoogleInterchangeUtilities.framework/GoogleInterchangeUtilities: smudge filter lfs failed
     warning: Clone succeeded, but checkout failed.
     You can inspect what was checked out with 'git status'
     and retry the checkout with 'git checkout -f HEAD'
```

A quick `brew install git-lfs` allowed me to install it.

**Comment by djungowski** [comment]
I was having the same issue, although I already had git-lfs installed. But: It seems the git-lfs version was outdated, so `brew upgrade git-lfs` did the trick
