### ISSUE TITLE
[Detached] OkHttp error when starting detached project on Android after adding third-party library

### ISSUE THREAD

**Issue by daominhsangvn** [expo/expo#523]
I used SDK 20 and detached the app. Then i install Realm into project, the app get stucked at loading screen for iOS and crashed for android. There are no errors at xCode but Android

iOS:
![ec78b7fa18edaa7a17d1bd8496396bce82d894c0cddb4aa9df pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/8254183/29512265-f500e858-868b-11e7-82cb-321f07a47759.png)

Android:
```
08-22 11:03:07.558 13816-14195/com.nois.realm E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                Process: com.nois.realm, PID: 13816
                                                                java.lang.NullPointerException: Attempt to invoke interface method 'void host.exp.exponent.experience.DevBundleDownloadProgressListener.onProgress(java.lang.String, java.lang.Integer, java.lang.Integer)' on a null object reference
                                                                    at versioned.host.exp.exponent.ExponentDevBundleDownloadListener.onProgress(ExponentDevBundleDownloadListener.java:27)
                                                                    at com.facebook.react.devsupport.DevSupportManagerImpl$22.onProgress(DevSupportManagerImpl.java:819)
                                                                    at com.facebook.react.devsupport.BundleDownloader$1$1.execute(BundleDownloader.java:122)
                                                                    at com.facebook.react.devsupport.MultipartStreamReader.emitChunk(MultipartStreamReader.java:69)
                                                                    at com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:116)
                                                                    at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:91)
                                                                    at expolib_v1.okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                    at expolib_v1.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:818)
```
When i remove Realm, the app run fine.

**Comment by jesseruder** [comment]
Have you tried on a raw React Native app? Seems likely to be a bug with Realm.

**Comment by daominhsangvn** [comment]
@jesseruder No i have not. I doubt it will work in vanilla RN.

**Comment by dikaiosune** [comment]
Hi! Unfortunately without a minimal ExpoKit-specific repro of this problem (confirming that it isn't happening in vanilla RN), it's really hard for us to help with this. Please reply back if you can confirm it's specific to using ExpoKit and I'll reopen. Thanks!

**Comment by daominhsangvn** [comment]
@dikaiosune Yes, I'm using ExpoKit

**Comment by MichaelPote** [comment]
I'm having this exact problem. App is detached and I added some external dependencies.

```
09-01 11:08:01.758 14615-14817/com.bravedigital.accentureinnovation E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                                      Process: com.bravedigital.accentureinnovation, PID: 14615
                                                                                      java.lang.NullPointerException: Attempt to invoke interface method 'void host.exp.exponent.experience.DevBundleDownloadProgressListener.onProgress(java.lang.String, java.lang.Integer, java.lang.Integer)' on a null object reference
                                                                                          at versioned.host.exp.exponent.ExponentDevBundleDownloadListener.onProgress(ExponentDevBundleDownloadListener.java:27)
                                                                                          at com.facebook.react.devsupport.DevSupportManagerImpl$22.onProgress(DevSupportManagerImpl.java:819)
                                                                                          at com.facebook.react.devsupport.BundleDownloader$1$1.execute(BundleDownloader.java:122)
                                                                                          at com.facebook.react.devsupport.MultipartStreamReader.emitChunk(MultipartStreamReader.java:69)
                                                                                          at com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:116)
                                                                                          at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:91)
                                                                                          at expolib_v1.okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                          at expolib_v1.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                          at java.lang.Thread.run(Thread.java:818)
```

**Comment by dikaiosune** [comment]
@jesseruder do you think the recent OkHttp changes could have broken this for ExpoKit?

**Comment by MichaelPote** [comment]
Just to fill you in on what happened, each time I started up the app there would be about a 50% chance of it crashing. After restarting multiple times, I could eventually get it to load successfully and then the app would work perfectly after that point. 

We then removed Expo from our project and went back to pure react native and we didnt see that error again. Sorry I cant give any more specific details than that.

**Comment by dekelev** [comment]
I'm getting the same error on Android after upgrading from ExpoKit v16.0.0 to v20.0.0 and now my app is crashing on boot.

I'm using ExpoKit for _react-native-udp_ & _react-native-tcp_ native modules.

**Comment by daominhsangvn** [comment]
@dikaiosune when i use the `react-native-fetch-blob` i have to change all the `okhttp3` to use `expokit_lib.okhttp3` to make it work or it throw incompatible error. It could related to the realm

**Comment by ianlenehan** [comment]
FWIW @dikaiosune I am not using realm, and I am getting this same error with RN v20. I haven't tried updating to v21 yet. It crashes multiple times but the odd time I can get in. I am also developing with Expo Kit. I've no issues with iOS.

**Comment by mschipperheyn** [comment]
Some insights from the geo location guys about this issue: https://github.com/transistorsoft/react-native-background-geolocation/issues/567
