### ISSUE TITLE
[Expo 34] Caught unexpected exception when writing to SecureStore in Android SDK 21 and 22

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#5236]
My app is ejected from Expo 34 and I get this error when I use SecureStore in Android SDK 21 and 22

```
Caught unexpected exception when writing to SecureStore
    java.lang.IllegalStateException: Can't generate certificate
        at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:136)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:499)
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:452)
        at expo.modules.securestore.SecureStoreModule.getKeyEntry(SecureStoreModule.java:314)
        at expo.modules.securestore.SecureStoreModule.setItemImpl(SecureStoreModule.java:112)
        at expo.modules.securestore.SecureStoreModule.setValueWithKeyAsync(SecureStoreModule.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at org.unimodules.core.ExportedModule.invokeExportedMethod(ExportedModule.java:97)
        at org.unimodules.adapters.react.NativeModulesProxy.callMethod(NativeModulesProxy.java:117)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:135)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsupportedOperationException: private exponent cannot be extracted
        at com.android.org.conscrypt.OpenSSLRSAPrivateKey.getPrivateExponent(OpenSSLRSAPrivateKey.java:161)
        at org.spongycastle.jcajce.provider.asymmetric.rsa.RSAUtil.generatePrivateKeyParameter(RSAUtil.java:63)
        at org.spongycastle.jcajce.provider.asymmetric.rsa.DigestSignatureSpi.engineInitSign(DigestSignatureSpi.java:95)
        at java.security.Signature$SignatureImpl.engineInitSign(Signature.java:679)
        at java.security.Signature.initSign(Signature.java:330)
        at com.android.org.bouncycastle.x509.X509Util.calculateSignature(X509Util.java:243)
        at com.android.org.bouncycastle.x509.X509V3CertificateGenerator.generate(X509V3CertificateGenerator.java:434)
        at com.android.org.bouncycastle.x509.X509V3CertificateGenerator.generate(X509V3CertificateGenerator.java:412)
        at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:133)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276) 
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:499) 
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:452) 
        at expo.modules.securestore.SecureStoreModule.getKeyEntry(SecureStoreModule.java:314) 
        at expo.modules.securestore.SecureStoreModule.setItemImpl(SecureStoreModule.java:112) 
        at expo.modules.securestore.SecureStoreModule.setValueWithKeyAsync(SecureStoreModule.java:74) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at org.unimodules.core.ExportedModule.invokeExportedMethod(ExportedModule.java:97) 
        at org.unimodules.adapters.react.NativeModulesProxy.callMethod(NativeModulesProxy.java:117) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:135) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by cruzach** [comment]
Hey @changLiuUNSW - `expo-secure-store` isn't compatible with Android 5 devices and older. (I just made a change to the docs about this yesterday, they just haven't been deployed yet. you can see the note [here](https://github.com/expo/expo/blob/master/docs/pages/versions/v34.0.0/sdk/securestore.md), though)

Sorry about this, there's a little more info in [this forum post](https://forums.expo.io/t/issues-with-spongycastle-dependency/19019) if you're curious
