### ISSUE TITLE
Unable to publish because of 500 server error

### ISSUE THREAD

**Issue by borgogelli** [expo/expo#5247]
## 🐛 Bug Report

Suddently I was unable to publish because of 500 server error. I didn't update any tools or dependencies and the status at https://status.expo.io is all green.

```
Success. You are now logged in as borgo.
$ expo publish --non-interactive --release-channel ${RELEASE_CHANNEL} --quiet
[15:54:11] Unable to find an existing Expo CLI instance for this directory, starting a new one...
[15:54:20] Tunnel ready.
[15:54:20] Publishing to channel 'default'...
[15:54:22] Request failed with status code 500
[15:54:22] Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Is there any limts to the number of versions we can publish in a day ?

### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
    npmGlobalPackages:
      expo-cli: 3.0.9

**Comment by cruzach** [comment]
Hi! 

I was just able to publish, same version of `expo-cli`, so this is probably something environment or project-specific.

Are you able to publish a brand new `expo init` project?

**Comment by borgogelli** [comment]
I have found the cause:
```
{
  "expo": {
        "name": "AdzQuick",
        "slug": "adzquick-react-app",
        "description": "Sell everything",
        "owner": "AdzQuick.com",
.....
```
I have tried to remove the _description_ key and the _owner_ key from app.json file and now the "expo publish" command works as expected

```
{
  "expo": {
        "name": "AdzQuick",
        "slug": "adzquick-react-app",
.....
```
