### ISSUE TITLE
[jest-expo] TypeError: Cannot read property 'current' of undefined , ^34.0.0

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [expo/expo#5268]
I just installed a fresh version of React Native using Expo.

> npm install -g expo-cli
> expo init AwesomeProject
> cd AwesomeProject
> npm test
>

but tests fail.

<img width="866" alt="Schermata 2019-08-09 alle 15 59 31" src="https://user-images.githubusercontent.com/4108673/62784449-d1ec7d00-babe-11e9-971e-95e3894655fb.png">

I checked that versions mismatching

Versions installed are:
- jest-expo@34.0.0
- jest@24.8.0
- react-test-renderer@16.9.0
- react@16.8.3

react and react-test-renderer minor version are different, so I thought that the problem was that.

I tryed to follow the guide here:

https://docs.expo.io/versions/latest/guides/testing-with-jest/

but using `npm i react-test-renderer --save-dev` always installed ^16.9 version of react-test-renderer.

So I tryed to force install ^16.8 react-test-renderer version:

> npm i react-test-renderer@16.8 --save-dev

that solved the problem, but I think that there is a problem in version packages dependencies

**Comment by franzmoro** [comment]
also needed `react-dom@16.8.3` in my case

**Comment by ide** [comment]
Hm that is unfortunate that react-test-renderer is not semver-compatible with react or react-dom. We may need to pin the versions to fix this moving forward.

**Comment by FabrizioCaldarelli** [comment]
It seems that react-test-renderer follow semver, using same minor of react and react-dom.

Instead, it seems that jest-expo is using a different versione of react-test-renderer.

**Comment by bikashsahucbnits** [comment]
I guess It might occurs due to the expo-cli version.
I got this error after after upgrading expo-cli to 3.0.9

As a workaround you can downgrade the version to 3.0.8 and try..

**Comment by TrentonAdams** [comment]
React 16.8.6 does not solve my problem.  **FYI**, the infinity symbol replaces '$' in my terminal prompt. 
```
∞ expo init jestTest
There is a new version of expo-cli available (3.0.9).
You are currently using expo-cli 2.7.1
Run `npm install -g expo-cli` to get the latest version
? Choose a template: expo-template-tabs
? Choose which workflow to use: managed
✔ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration · 100% completed
? Yarn v1.16.0 found. Use Yarn to install dependencies? Yes
[22:54:49] Extracting project files...
[22:54:50] Customizing project...
[22:54:50] Installing dependencies...
yarn install v1.16.0
info No lockfile found.
[1/4] Resolving packages...
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning react-native-web > deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
warning jest-expo > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @react-navigation/web@1.0.0-alpha.9" has unmet peer dependency "@react-navigation/core@^3.0.0-alpha.13".
warning "react-native > metro-react-native-babel-transformer@0.51.0" has unmet peer dependency "@babel/core@*".
warning "react-native > @react-native-community/cli > metro-react-native-babel-transformer@0.51.1" has unmet peer dependency "@babel/core@*".
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "jest-expo > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "jest-expo > babel-jest > babel-preset-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 56.04s.

Your project is ready at /home/trenta/Documents/development/node/jestTest
To get started, you can type:

  cd jestTest
  yarn start

22:55:46 [trenta@trent-pc:~/Documents/development/node] master(+20/-11,3) 1m12s ± 
∞ cd jestTest/
22:56:11 [trenta@trent-pc:~/Documents/development/node/jestTest] master(+20/-11,3) ± 
∞ cd yar^C
22:56:13 [trenta@trent-pc:~/Documents/development/node/jestTest] master(+20/-11,3) 130 ± 
∞ jest
 FAIL  components/__tests__/StyledText-test.js
  ● renders correctly

    TypeError: Cannot read property 'current' of undefined

       5 | 
       6 | it(`renders correctly`, () => {
    >  7 |   const tree = renderer.create(<MonoText>Snapshot test!</MonoText>).toJSON();
         |                         ^
       8 | 
       9 |   expect(tree).toMatchSnapshot();
      10 | });

      at warnIfNotScopedWithMatchingAct (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14034:59)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15129:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15824:5)
      at Object.create (components/__tests__/StyledText-test.js:7:25)

 FAIL  __tests__/App-test.js
  ● App › renders the loading screen

    TypeError: Cannot read property 'current' of undefined

      19 | 
      20 |   it(`renders the loading screen`, () => {
    > 21 |     const tree = renderer.create(<App />).toJSON();
         |                           ^
      22 |     expect(tree).toMatchSnapshot();
      23 |   });
      24 | 

      at warnIfNotScopedWithMatchingAct (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14034:59)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15129:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15824:5)
      at Object.create (__tests__/App-test.js:21:27)

  ● App › renders the root without loading screen

    TypeError: Cannot read property 'current' of undefined

      24 | 
      25 |   it(`renders the root without loading screen`, () => {
    > 26 |     const tree = renderer.create(<App skipLoadingScreen />).toJSON();
         |                           ^
      27 |     expect(tree).toMatchSnapshot();
      28 |   });
      29 | });

      at warnIfNotScopedWithMatchingAct (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14034:59)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15129:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15824:5)
      at Object.create (__tests__/App-test.js:26:27)

Test Suites: 2 failed, 2 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        5.614s
Ran all test suites.
```

And the package.json...
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "~3.0.3",
    "@expo/vector-icons": "^10.0.3",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "expo": "^34.0.1",
    "expo-asset": "^6.0.0",
    "expo-constants": "6.0.0",
    "expo-font": "~6.0.0",
    "expo-web-browser": "6.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0",
    "jest-expo": "^34.0.0"
  },
  "private": true
}
22:59:12 [trenta@trent-pc:~/Documents/development/nod
```

**Comment by TrentonAdams** [comment]
Apparently expo installed react-dom 16.8.6 instead of matching it with react 16.8.3.  I also removed the '^' as per a previous suggestion, but to no avail.

**Comment by FabrizioCaldarelli** [comment]
> And the package.json...
> 
> ```
>   "devDependencies": {
>     "babel-preset-expo": "^6.0.0",
>     "jest-expo": "^34.0.0"
>   },
>   "private": true
> }
> 22:59:12 [trenta@trent-pc:~/Documents/development/nod
> ```

Add in packages.json react-test-renderer v.16.8:

```
npm i react-test-renderer@16.8 --save-dev
```

**Comment by TrentonAdams** [comment]
@FabrizioCaldarelli nice, that worked.  So, expo should be updated to do this automatically on a new project?  And make the versions the same too?

**Comment by ide** [comment]
We've pinned the version of react-test-renderer that jest-expo uses to be `~16.8.3`, which lines up with the required version of React (`16.8.3` exactly). We didn't expect this semver-breaking change in react-test-renderer and the issue should be fixed in jest-expo 34.0.1 (patch release).

**Comment by TrentonAdams** [comment]
@ide I can't confirm your statement about deleting the lock file and reinstalling dependencies, as the project is now gone.  But, I did confirm that the following worked for a new project...

```bash
yarn global upgrade expo
expo init jestTest
yarn test
```

**Comment by Nodirbek3d** [comment]
Having the same issue, I tried to set versions of dependencies to suggested ones, but no luck
here is my package.json
```
  "devDependencies": {
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.57.65",
    "babel-preset-expo": "^6.0.0",
    "jest-expo": "^34.0.0",
    "react-test-renderer": "^16.8.6"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
    ]
  },
```

**Comment by FabrizioCaldarelli** [comment]
@Nodirbeck3d remove react-test-renderer from packages.json and try with

npm i react-test-renderer@16.8 --save-dev

**Comment by Nodirbek3d** [comment]
> @Nodirbeck3d remove react-test-renderer from packages.json and try with
> 
> npm i react-test-renderer@16.8 --save-dev

When I do that, it installs 16.8.6

**Comment by ide** [comment]
16.8.6 is fine. It’s 16.9.x that broke things.

**Comment by Nodirbek3d** [comment]
but with 16.8.6 I am getting error...

**Comment by maq0n** [comment]
@Nodirbek3d  react-dom & react-test-renderer should to be exact versions (--save-exact) (without ^)

**Comment by ashton** [comment]
Same error here, using exact version `16.8.5` in all tree dependencies

**Comment by BenjaminWatts** [comment]
I'm having the same issue still - does anyone just have a working package.json they could share that works?

**Comment by bikashsahucbnits** [comment]
@BenjaminWatts Try with Below Dependencies in your package.json
"react": "16.8.6",
"react-dom": "16.8.6",
"react-test-renderer": "16.8.6",

**Comment by mi-mazouz** [comment]
how did you solved it? nothing working for me

**Comment by bikashsahucbnits** [comment]
@mi-mazouz try with https://github.com/expo/expo/issues/5268#issuecomment-520706978
Which version of expo you are using, they have solved it in their latest release.

**Comment by ebisLab** [comment]
As silly as this sounds, changing version numbers worked... i had to match them precisely .. without the ^
