### ISSUE TITLE
Importing "expo" in Jest when automocked throws importing-removed-modules error with SDK 34

### ISSUE THREAD

**Issue by FrickenHamster** [expo/expo#5633]
### Environment

` Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.2 => 16.9.2 
      @types/react-native: ^0.57.65 => 0.57.65 
      @types/react-navigation: ^3.0.4 => 3.0.8 
      expo: ^34.0.4 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.0.10`
target android and ios, but this is happening in jest

### Steps to Reproduce

Have test that imported a module such as { Notifications } from 'expo' in Expo 33. 
Upgrade to Expo 34

### Expected Behavior
It should still pass the test

### Actual Behavior

You get a pretty tricky to diagnose error since the error is thrown in a timeout. From what I can tell, it seems like Jest is trying to parse all the modules to mock, but doing so imports all the modules in expo which triggers the removed modules. I'm not sure about this.

Here is the stack trace

`
Trace: reee
        at Object.trace [as AdMobBanner] (/Users/alexyan/Code/mobile/node_modules/expo/build/removed.js:8:18)
        at Object.AdMobBanner (/Users/alexyan/Code/mobile/node_modules/expo/build/ExpoLazy.js:57:21)
        at _getSlots.forEach.slot (/Users/alexyan/Code/mobile/node_modules/jest-mock/build/index.js:788:56)
        at Array.forEach (<anonymous>)
        at ModuleMockerClass.getMetadata (/Users/alexyan/Code/mobile/node_modules/jest-mock/build/index.js:779:33)
        at Runtime._generateMock (/Users/alexyan/Code/mobile/node_modules/jest-runtime/build/index.js:923:47)
        at Runtime.requireMock (/Users/alexyan/Code/mobile/node_modules/jest-runtime/build/index.js:543:39)
        at Runtime.requireModuleOrMock (/Users/alexyan/Code/mobile/node_modules/jest-runtime/build/index.js:597:21)
        at Object.<anonymous> (/Users/alexyan/Code/mobile/.../testfile:7:1)
        at Runtime._execModule (/Users/alexyan/Code/mobile/node_modules/jest-runtime/build/index.js:868:68)
`

**Comment by FrickenHamster** [comment]
Hey @ide , Thanks for the response!
I took a closer look as per your suggestion and it does seem we are specifically mocking expo. `jest.mock('expo')`

However we are also testing the Notifications mock a few times. It does seem that mocking expo is what is triggering this error. Is there a way around it while allowing it to work with tests? or should we maybe disable it until the exports are removed?

Thanks!

**Comment by ide** [comment]
I'd try providing a manual mock, which might sidestep Jest's automocking enough for you to avoid this issue:

```
jest.mock('expo', () => ({
  Notifications: { whatever you want here },
  etc...
}));

**Comment by FrickenHamster** [comment]
Thanks for the help! I got it working for my purposes.
