### ISSUE TITLE
MediaLibrary.getAlbumAsync crashing on Android 10 (API Level 29)

### ISSUE THREAD

**Issue by blake-simpson** [expo/expo#5637]
### Environment

Android 10 (Pixel XL emulator with API level 29).
Also seen on production devices via the Play Store.

### Steps to Reproduce

Call `MediaLibrary.getAlbumAsync()`

### Expected Behavior

The album is returned

### Actual Behavior

The app crashes. Example error output:

```
09-13 13:31:07.621  6771  6816 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT bucket_id, bucket_display_name, COUNT(*) FROM files WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' , '12f9-100d' ))) AND ((media_type != 0 AND bucket_display_name=?) /*)) ORDER BY */ GROUP BY bucket_id ORDER BY bucket_display_name
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at android.content.ContentResolver.query(ContentResolver.java:944)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at android.content.ContentResolver.query(ContentResolver.java:880)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at android.content.ContentResolver.query(ContentResolver.java:836)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at expo.modules.medialibrary.MediaLibraryUtils.queryAlbum(MediaLibraryUtils.java:279)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at expo.modules.medialibrary.GetAlbum.doInBackground(GetAlbum.java:28)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at expo.modules.medialibrary.GetAlbum.doInBackground(GetAlbum.java:11)
09-13 13:31:07.621  6771  6816 E AndroidRuntime:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
```

### Reproducible Demo

Snack: https://snack.expo.io/@brsim/smiling-almond

Running this snack in the Expo app with the following emulator causes the app to crash:

```
  Name: Pixel_XL_API_29
  Device: pixel_xl (Google)
    Path: /Users/blake/.android/avd/Pixel_XL_API_29.avd
  Target: Google APIs (Google Inc.)
    Based on: Android API 29 Tag/ABI: google_apis/x86
  Skin: pixel_xl
  Sdcard: 100M
```

**Comment by indigoviolet** [comment]
any workarounds here? I see this as well :(

**Comment by jim-at-jibba** [comment]
I am still seeing this issue. App crashes when calling `MediaLibrary.getAlbumAsync`.

**Comment by lukmccall** [comment]
Hi @jim-at-jibba, this fix will be available in the next SDK version.

**Comment by impactcolor** [comment]
Any fix on this? I'm having htis problem.
