### ISSUE TITLE
The app just throws this issue while its idle

### ISSUE THREAD

**Issue by GodwinEbikwo** [expo/expo#5732]
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by byCedric** [comment]
Related: https://github.com/expo/expo-cli/issues/519
