### ISSUE TITLE
[AV][Android] looped video causes crash w/ "java.lang.Integer cannot be cast to java.lang.Double"

### ISSUE THREAD

**Issue by simse07** [expo/expo#5832]
## 🐛 Bug Report
Playing a video in a loop with a status listener attached causes `java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double` in PlayerData.java:205 + PlayerData.java:212

Stack Traces:
```
Attempt to cast generated internal exception:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at android.os.BaseBundle.getDouble(BaseBundle.java:1101)
	at android.os.BaseBundle.getDouble(BaseBundle.java:1083)
	at abi35_0_0.expo.modules.av.player.PlayerData.setStatusWithListener(PlayerData.java:205)
	at abi35_0_0.expo.modules.av.player.PlayerData.setStatus(PlayerData.java:265)
	at abi35_0_0.expo.modules.av.player.SimpleExoPlayerData.load(SimpleExoPlayerData.java:102)
	at abi35_0_0.expo.modules.av.video.VideoView.setSource(VideoView.java:350)
	at abi35_0_0.expo.modules.av.video.VideoViewManager.setSource(VideoViewManager.java:104)
	at java.lang.reflect.Method.invoke(Native Method)
	at abi35_0_0.org.unimodules.core.ViewManager.updateProp(ViewManager.java:81)
	at abi35_0_0.org.unimodules.adapters.react.views.ViewManagerAdapterUtils.setProxiedProperties(ViewManagerAdapterUtils.java:52)
	at abi35_0_0.org.unimodules.adapters.react.views.SimpleViewManagerAdapter.setProxiedProperties(SimpleViewManagerAdapter.java:49)
	at java.lang.reflect.Method.invoke(Native Method)
	at abi35_0_0.com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
	at abi35_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
	at abi35_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
	at abi35_0_0.com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
	at abi35_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:141)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
	at abi35_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at abi35_0_0.com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
	at abi35_0_0.com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```
```
Attempt to cast generated internal exception:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at android.os.BaseBundle.getDouble(BaseBundle.java:1101)
	at android.os.BaseBundle.getDouble(BaseBundle.java:1083)
	at abi35_0_0.expo.modules.av.player.PlayerData.setStatusWithListener(PlayerData.java:212)
	at abi35_0_0.expo.modules.av.player.PlayerData.setStatus(PlayerData.java:265)
	at abi35_0_0.expo.modules.av.player.SimpleExoPlayerData.load(SimpleExoPlayerData.java:102)
	at abi35_0_0.expo.modules.av.video.VideoView.setSource(VideoView.java:350)
	at abi35_0_0.expo.modules.av.video.VideoViewManager.setSource(VideoViewManager.java:104)
	at java.lang.reflect.Method.invoke(Native Method)
	at abi35_0_0.org.unimodules.core.ViewManager.updateProp(ViewManager.java:81)
	at abi35_0_0.org.unimodules.adapters.react.views.ViewManagerAdapterUtils.setProxiedProperties(ViewManagerAdapterUtils.java:52)
	at abi35_0_0.org.unimodules.adapters.react.views.SimpleViewManagerAdapter.setProxiedProperties(SimpleViewManagerAdapter.java:49)
	at java.lang.reflect.Method.invoke(Native Method)
	at abi35_0_0.com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
	at abi35_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
	at abi35_0_0.com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
	at abi35_0_0.com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
	at abi35_0_0.com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:141)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
	at abi35_0_0.com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
	at abi35_0_0.com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at abi35_0_0.com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
	at abi35_0_0.com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```
### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: Linux 4.4 Linux Mint 18.3 (Sylvia)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.9.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
    npmPackages:
      @types/expo: ^27.0.17 => 27.0.17 
      @types/react: ^16.8.3 => 16.9.4 
      @types/react-native: ^0.48.10 => 0.48.10 
      @types/react-navigation: ^2.0.16 => 2.13.10 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ~4.0.6 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.0.10

Running expo app on an Android Tablet via expo start + run app on Android

### Steps to Reproduce

Add a video player and play it in a loop

### Expected Behavior

Video should be playing all the time without pause.

### Actual Behavior

Video stops and causes app crash.

### Reproducible Demo

```
import * as React from 'react';
import { View } from 'react-native';
import Constants from 'expo-constants';
import { Video } from 'expo-av'

export default class App extends React.Component {
  render() {
    const playbackStatusUpdate = (status) => {
      if (status.error) {
        console.warn(status.error)
        return
      }
    }
    return (
      <View>
        <Video
          isLooping={true}
          onPlaybackStatusUpdate={playbackStatusUpdate}
          shouldPlay={true}
          source={{
            uri: '' // add uri to video
          }}
        />
      </View>
    );
  }
}
```

**Comment by cruzach** [comment]
Are you only seeing the crash on tablets? I tried testing this via [this snack](https://snack.expo.io/@charliecruzan/rude-bacon) and didn't see any crashes. How many times does the video need to loop before a crash usually happens?

**Comment by simse07** [comment]
Thank you for the fast response. The snack works for me too. I'm working on a reproducible demo.
The crash happens after 5-10 loops, but the biggest problem is that the video stops playing every time.

I'm wondering why you don't check the type of STATUS_PROGRESS_UPDATE_INTERVAL_MILLIS_KEY_PATH and STATUS_POSITION_MILLIS_KEY_PATH since there are setters which integer values like https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/versioned-abis/expoview-abi34_0_0/src/main/java/abi34_0_0/expo/modules/av/player/SimpleExoPlayerData.java#L190

**Comment by tsapeta** [comment]
We were unable to reproduce this and there was no activity for a pretty long period of time, so I'm closing it. Let us know once you find a reproducible example! 🙂
