### ISSUE TITLE
Expo Location. startLocationUpdatesAsync and TaskManager.defineTask, task crash and unregistering

### ISSUE THREAD

**Issue by sorinbogdan95** [expo/expo#6017]
### Environment

Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.2.3
    "expo-task-manager": "~7.0.0",
    "expo-location": "~7.0.0",
    "expo-permissions": "~7.0.0",
    "expo-constants": "~7.0.0"

Standalone app, Android.

### Steps to Reproduce

Just use the example provided in expo docs regarding background location task. Or the one I provided.
Enable the location task, check it has been enabled. Quit app. When the first location change is reported and task is run, it quits and the task is unregistered, and doesn't get triggered anymore.

### Expected Behavior

Background location is reported when app is minimised or quit.

### Actual Behavior

When app is quitted and the first location change is reported and task is run, the task is unregistered, and doesn't get triggered anymore. Also some errors are generated.

### Reproducible Demo

https://snack.expo.io/@sorinbogdan/ecba97

Errors from Logcat: 
`D/Zygote: Forked child process 26327
10-17 17:20:07.514 1255-1287/? I/ActivityManager: Start proc 26327:com.myapp.location/u0a247 for broadcast {com.myapp.location/expo.modules.taskManager.TaskBroadcastReceiver}
D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
10-17 17:20:07.524 26327-26327/? E/myapp.locatio: Not starting debugger since process cannot load the jdwp agent.
I/myapp.locatio: The ClassLoaderContext is a special shared library.
W/myapp.locatio: Unsupported class loader
V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/myapp.locatio: ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/com.myapp.location-z9T0Jp5Hh5WgiKmDZCgpeA==/base.apk*4174445279:/data/app/com.myapp.location-z9T0Jp5Hh5WgiKmDZCgpeA==/base.apk!classes2.dex*3392624095]{PCL[/system/framework/org.apache.http.legacy.jar*1038351580]})
10-17 17:20:07.749 26327-26353/? W/myapp.locatio: Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000055/dl-AdsFdrDynamite.integ_20461000000.apk
    NOTE: This wastes RAM and hurts startup performance.
    Found duplicated class when checking oat files: 'Landroid/support/annotation/Keep;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000055/dl-AdsFdrDynamite.integ_20461000000.apk and /data/app/com.myapp.location-z9T0Jp5Hh5WgiKmDZCgpeA==/base.apk
10-17 17:20:07.837 26327-26327/? D/SoLoader: init start

 adb shell setprop debug.firebase.analytics.app com.myapp.location
10-17 17:20:07.944 26327-26378/? E/Fabric: Fabric could not be initialized, API key missing from AndroidManifest.xml. Add the following tag to your Application element 
    	<meta-data android:name="io.fabric.ApiKey" android:value="YOUR_API_KEY"/>
D/b: Loaded exp.host status page.
Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.myapp.location/settings
E/Answers: Failed to retrieve settings

I/TaskService: Registered task with name 'background-location-task' for app with ID '@synkedup/location'.
I/TaskService: Handling intent with task name 'background-location-task' and appId '@synkedup/location'.
I/TaskService: Handling job with task name 'background-location-task' for app with ID '@synkedup/location'.
E/Expo: Cannot initialize app loader. host.exp.exponent.e.a.<init> [class android.content.Context]
E/TaskService: Cannot execute background task because application loader can't be found.
I/TaskService: Unregistering task 'background-location-task' for app '@synkedup/location'.
I/myapp.locatio: Waiting for a blocking GC ProfileSaver
I/myapp.locatio: WaitForGcToComplete blocked ProfileSaver on ClassLinker for 6.886ms
...28 minutes later... I/ActivityManager: Killing 26327:com.myapp.location/u0a247 (adj 985): empty #17
`
(cc @tsapeta )

**Comment by hladf** [comment]
The same is happening here. Sometimes works in debug mode with **android 9 emulator** or a **real device via usb**, but **`never`** work fine when build apk, install and open the app.

**Comment by jeromecornet** [comment]
This also happens with a BackgroundFetch, and points to a deeper problem with TaskManager rather than being BackgroundFetch or BackgroundLocation specific https://github.com/expo/expo/issues/6290

**Comment by fmontaigne** [comment]
Also having some issues with our app (we only use background location updates). Looks like it's working on dev environment but we have some crashes on standalone app. Will attach some details when we have a good reproducible demo

**Comment by jeromecornet** [comment]
https://github.com/expo/expo/issues/6290 has a demo project (based on BackgroundFetch) as well  https://github.com/jeromecornet/expo-android-backgroundfetch

**Comment by superyarik** [comment]
i hope my [comment](https://github.com/expo/expo/issues/6290#issuecomment-554881030) with error log will not be forgotten

**Comment by jeromecornet** [comment]
Thanks @superyarik. 
Does the crash happen _after_ the task gets unregistered or before ? 

I had a few minutes to take a look at the source code, and it would make sense to me if it was after, because of a race condition between LocationTaskConsumer#didUnregister() https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/versioned-abis/expoview-abi35_0_0/src/main/java/abi35_0_0/expo/modules/location/taskConsumers/LocationTaskConsumer.java#L79-L82 and the onComplete() listener https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/versioned-abis/expoview-abi35_0_0/src/main/java/abi35_0_0/expo/modules/location/taskConsumers/LocationTaskConsumer.java#L117-L124
which ends up calling maybeReportDeferredLocations() which calls shouldReportDeferredLocations() which in turn calls getOptions() on a null mTask: https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/versioned-abis/expoview-abi35_0_0/src/main/java/abi35_0_0/expo/modules/location/taskConsumers/LocationTaskConsumer.java#L305-L316

@tsapeta maybe the fix for the crash in https://github.com/expo/expo/issues/6290#issuecomment-554881030 is simply to add a guard early in in shouldReportDeferredLocations() https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/versioned-abis/expoview-abi35_0_0/src/main/java/abi35_0_0/expo/modules/location/taskConsumers/LocationTaskConsumer.java#L305-L313 to return if the task has already been unregistered ? 

But that said it would not fix the underlying issue (in TaskManager) which is that the task gets unregistered in the first place due to a loader error (```Cannot execute background task because application loader can't be found.```)

**Comment by xinlangzi** [comment]
@jeromecornet 

Have you figured out Expo Background Location work both well in android and ios? Not sure whether some demo code work well now on latest version of Expo SDK.

**Comment by jeromecornet** [comment]
It's still broken for me in SDK36

**Comment by ribeiroevandro** [comment]
@jeromecornet I also have the same problem, on the physical device, returns the error of the image, even after setting in app.json
![Screen Shot 2019-12-31 at 03 40 27](https://user-images.githubusercontent.com/943553/71612634-6c3d8200-2b80-11ea-892f-df3969e2b757.png)

**Comment by jeromecornet** [comment]
@ribeiroevandro this sound unrelated and a more likely a configuration problem in app.json rather than the loader problem discussed here.

**Comment by ribeiroevandro** [comment]
@jeromecornet I found the problem, in fact the Expo client for the physical appliance does not support localization. Sorry if I commented in the wrong place.

**Comment by jeromecornet** [comment]
np @ribeiroevandro ... BTW I've updated the sample code to reproduce the issue with the latest SDK 36 at https://github.com/jeromecornet/expo-android-backgroundfetch

**Comment by skjortan23** [comment]
Any updates on this? I am having the same problems. 
I there any workaround?

**Comment by superyarik** [comment]
@skjortan23 we build app version(.apk) without background tracking and send it to people who sad about crashing

**Comment by superyarik** [comment]
some phones facing this issue through time, some phones crash every launch.

**Comment by superyarik** [comment]
here is logs

`07-03 12:47:54.258 1649-1649/? I/TaskService: Registered task with name 'hubex-location' for app with ID '@hubex_developers/hubex-engineer'.
07-03 12:47:54.273 1649-1649/? I/TaskService: Handling job with task name 'hubex-location' for app with ID '@hubex_developers/hubex-engineer'.
07-03 12:47:54.276 1649-1649/? E/Expo: Cannot initialize app loader. host.exp.exponent.taskManager.ExpoHeadlessAppLoader
07-03 12:47:54.276 1649-1649/? W/System.err: java.lang.ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader
07-03 12:47:54.277 1649-1649/? W/System.err:     at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at l.d.a.b.a(AppLoaderProvider.java:2)
        at l.d.a.b.b(AppLoaderProvider.java:2)
        at expo.modules.taskManager.TaskService.getAppLoader(TaskService.java:2)
        at expo.modules.taskManager.TaskService.executeTask(TaskService.java:17)
        at expo.modules.taskManager.Task.execute(Task.java:2)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.executeTaskWithLocationBundles(LocationTaskConsumer.java:4)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob(LocationTaskConsumer.java:10)
        at expo.modules.taskManager.TaskService.handleJob(TaskService.java:7)
        at expo.modules.taskManager.TaskJobService.onStartJob(TaskJobService.java:3)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
07-03 12:47:54.278 1649-1649/? W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "host.exp.exponent.taskManager.ExpoHeadlessAppLoader" on path: DexPathList[[zip file "/data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/base.apk", zip file "/data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.arm64_v8a.apk", zip file "/data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.en.apk", zip file "/data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.ru.apk", zip file "/data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/lib/arm64, /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/base.apk!/lib/arm64-v8a, /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.en.apk!/lib/arm64-v8a, /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.ru.apk!/lib/arm64-v8a, /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 20 more
07-03 12:47:54.279 1649-1649/? W/System.err: 	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.arm64_v8a.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5943)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
    		... 6 more
07-03 12:47:54.280 1649-1649/? W/System.err: 	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.en.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5943)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
    		... 6 more
07-03 12:47:54.281 1649-1649/? W/System.err: 	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.ru.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5943)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
    		... 6 more
07-03 12:47:54.283 1649-1649/? W/System.err: 	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/ru.hubex.engineer-_0Ukvc5sVPdAIh8jXeksyw==/split_config.xxhdpi.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
07-03 12:47:54.284 1649-1649/? W/System.err:     at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5943)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
    		... 6 more
07-03 12:47:54.285 1649-1649/? E/JobServiceEngine: Error while executing job: 0
07-03 12:47:54.286 1649-1649/? D/AndroidRuntime: Shutting down VM
07-03 12:47:54.286 1649-1649/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.hubex.engineer, PID: 1649
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void l.d.a.c.a(android.content.Context, l.d.a.c$b, java.lang.Runnable, l.d.b.l.e)' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void l.d.a.c.a(android.content.Context, l.d.a.c$b, java.lang.Runnable, l.d.b.l.e)' on a null object reference
        at expo.modules.taskManager.TaskService.executeTask(TaskService.java:17)
        at expo.modules.taskManager.Task.execute(Task.java:2)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.executeTaskWithLocationBundles(LocationTaskConsumer.java:4)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob(LocationTaskConsumer.java:10)
        at expo.modules.taskManager.TaskService.handleJob(TaskService.java:7)
        at expo.modules.taskManager.TaskJobService.onStartJob(TaskJobService.java:3)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
07-03 12:47:54.298 4965-14441/? D/Debug: !@DumpState : SHIP
    !@DumpState : debug level:0x4f4c
07-03 12:47:54.299 4965-14441/? D/Debug: !@Dumpstate : Finally, system will skip dumpstate
07-03 12:47:54.299 4965-14441/? W/ActivityManager: crash : ru.hubex.engineer,0
07-03 12:47:54.306 4965-5049/? I/ActivityManager: Showing crash dialog for package ru.hubex.engineer u0
`

**Comment by syedhaider03** [comment]
Did someone find the problem? 
I am using it in bare react native app on android with unimodules installed and experience the same issue, when the app is launched from killed state it works fine but when we try to use it in already running app it always gives the error and then crashes the app after some time and you will need to kill the app and start it again to start working.
![Screenshot_1594578786](https://user-images.githubusercontent.com/43629380/87288249-8afbd880-c514-11ea-8a46-6d15e222c579.png)

**Comment by hnabbasi** [comment]
@tsapeta @sjchmiela 

The problem seems to when retrieving stored coordinates. But the bundle extras are being used without checking to see if it is even there,
this is the error:
```
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.PersistableBundle.unparcel()' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8034)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.PersistableBundle.unparcel()' on a null object reference
        at android.os.BaseBundle.putAll(BaseBundle.java:542)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob(LocationTaskConsumer.java:142)
        at expo.modules.taskManager.TaskService.handleJob(TaskService.java:331)
        at expo.modules.taskManager.TaskJobService.onStartJob(TaskJobService.java:13)
        at android.app.job.JobService$1.onStartJob(JobService.java:62)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8034) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
```
and the problem seems to be here,
https://github.com/expo/expo/blob/8baac603e92f5e63eb046d6898c968f8e4d2118e/packages/expo-location/android/src/main/java/expo/modules/location/taskConsumers/LocationTaskConsumer.java#L142

**Comment by ashishsober** [comment]
Is some find the solution for this ? or any workaround to fix this problem. Please, anyone, take the in charge to fix this issue

**Comment by superyarik** [comment]
one year anniversary bug?

**Comment by Zanchee** [comment]
Please move any future discussion of this issue to #9288 so that we can have it all in one place.
