### ISSUE TITLE
null in array in app.json causes crash on Android

### ISSUE THREAD

**Issue by ccuilla** [expo/expo#602]
We added an array in our `app.json` file for some configuration information (specifically under `extra`):

```
        "myarray": [
          null,
          30,
          10
        ]
```

This causes a crash on Android (but not iOS):

```09-06 10:32:38.107  3255  3255 E AndroidRuntime: java.lang.IllegalArgumentException: Unexpected type in an array: class org.json.JSONObject$1
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.exponent.utils.JSONBundleConverter.setJSONArray(JSONBundleConverter.java:150)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.exponent.utils.JSONBundleConverter.JSONToBundle(JSONBundleConverter.java:42)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.exponent.utils.JSONBundleConverter.JSONToBundle(JSONBundleConverter.java:36)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.exponent.utils.JSONBundleConverter.JSONToBundle(JSONBundleConverter.java:36)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.exponent.utils.JSONBundleConverter.JSONToBundle(JSONBundleConverter.java:36)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.exponent.experience.ReactNativeActivity.startReactInstance(ReactNativeActivity.java:441)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.expoview.ExponentActivity$3.onSuccess(ExponentActivity.java:215)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at host.exp.expoview.Exponent$3$1.run(Exponent.java:587)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-06 10:32:38.107  3255  3255 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I believe the JSON spec would allow null as a value in an array:

http://www.json.org/
https://tools.ietf.org/html/rfc7159

We're able to work around by using `-1` vs. `null`.

**Comment by dikaiosune** [comment]
Hi! I created a new project, and used this for its `app.json`:

```json
{
  "expo": {
    "sdkVersion": "21.0.0"
  },
  "extra": {
    "myarray": [
      null,
      30,
      10
    ]
  }
}
```

And was able to load my project OK. Can you provide some more details about the crash you saw? What device, Android version, etc? What was the full structure of app.json (it looks like this was nested pretty deeply)?
