### ISSUE TITLE
Test failed using jest-expo-enzyme

### ISSUE THREAD

**Issue by rodelrebucas** [expo/expo#6126]
Environment:
node 8
expo sdk 35

```
● Test suite failed to run

    .../node_modules/jest-expo-enzyme/src/setupEnzyme.native.js:4
    import 'react-native';
           ^^^^^^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.877s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Does anyone using this library yet and give a working sample config?

**Comment by cruzach** [comment]
Hi! there's an example in the [this library's readme](https://github.com/expo/expo/tree/master/packages/jest-expo-enzyme)

Your import should look like:
```
import { View, StyleSheet, Platform } from 'react-native';
```
rather than just `import 'react-native';`
