### ISSUE TITLE
expo sdk 20 - detached app wont start because of okHttp lib error

### ISSUE THREAD

**Issue by smolleyes** [expo/expo#623]
hi

expo sdk 20 / app detached

everything works fine with debug builds but release builds my app crash at boot...

logcat error :

```
09-09 17:42:46.880  8491  8516 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
09-09 17:42:46.880  8491  8516 E AndroidRuntime: Process: fr.batexpert.mobibat, PID: 8491
09-09 17:42:46.880  8491  8516 E AndroidRuntime: java.lang.RuntimeException: Could not load app.
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at host.exp.exponent.kernel.ExpoViewKernel.handleError(ExpoViewK
ernel.java:76)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at host.exp.expoview.ExponentActivity$1.onError(ExponentActivity
.java:100)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at host.exp.exponent.ExponentManifest$3.handleResponse(ExponentM
anifest.java:226)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at host.exp.exponent.ExponentManifest$3.onResponse(ExponentManif
est.java:247)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at host.exp.exponent.network.ExponentHttpClient$2$1.onResponse(E
xponentHttpClient.java:98)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at expolib_v1.okhttp3.RealCall$AsyncCall.execute(RealCall.java:1
35)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at expolib_v1.okhttp3.internal.NamedRunnable.run(NamedRunnable.j
ava:32)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolE
xecutor.java:1133)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPool
Executor.java:607)
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
09-09 17:42:46.880  8491  8516 E AndroidRuntime: Caused by: Could not load app.
09-09 17:42:46.880  8491  8516 E AndroidRuntime:        ... 8 more
```

an idear ? (urgent)

thanks

**Comment by smolleyes** [comment]
hello

exact same thing with expo sdk 19, i have a nice app but can t release it, everything works in debug 
 WOOO :/ 

please help !!!

thanks :)

**Comment by smolleyes** [comment]
NO problem with Vanill RN ! app boot

**Comment by jesseruder** [comment]
Hello. Are you sure you published your app before trying to load the release build? See https://docs.expo.io/versions/latest/guides/advanced-expokit-topics.html#configuring-the-js-url

**Comment by terribleben** [comment]
Closing for now because we haven't heard back - let me know if you're still blocked and we can reopen.

**Comment by fcaride** [comment]
Im having this exact problem in sdk 21 :(
It works on Debug variant but when i change it to release it wont launch the application.
Here is my output:

04-04 13:25:20.462 27835-27875/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.nxt.zero, PID: 27835
    java.lang.RuntimeException: Could not load app.
        at host.exp.exponent.kernel.ExpoViewKernel.handleError(ExpoViewKernel.java:76)
        at host.exp.expoview.ExponentActivity$2.onError(ExponentActivity.java:115)
        at host.exp.exponent.ExponentManifest$3.handleResponse(ExponentManifest.java:237)
        at host.exp.exponent.ExponentManifest$3.onResponse(ExponentManifest.java:258)
        at host.exp.exponent.network.ExponentHttpClient$2$1.onResponse(ExponentHttpClient.java:100)
        at expolib_v1.okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at expolib_v1.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: Could not load app.
        at host.exp.exponent.ExponentManifest$3.handleResponse(ExponentManifest.java:237) 
        at host.exp.exponent.ExponentManifest$3.onResponse(ExponentManifest.java:258) 
        at host.exp.exponent.network.ExponentHttpClient$2$1.onResponse(ExponentHttpClient.java:100) 
        at expolib_v1.okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) 
        at expolib_v1.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)
