### ISSUE TITLE
Loading VideoThumbnails sometimes crashes app on Android

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#6508]
## 🐛 Bug Report

Not sure if this is related to (#5711 by @lukmccall)?
### Environment

Bug occurs on Android. Tested on Nexus 6 API 28
```

  Expo CLI 3.4.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.9.9
      @types/react-native: ^0.57.60 => 0.57.65
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: 3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 3.4.0
```
### Steps to Reproduce

```'
import * as VideoThumbnails from 'expo-video-thumbnails';

const TestView: React.FC<InputProps> = props => {
  async function generateThumbnail(imageUrl: string) {
      try {
        const result = await VideoThumbnails.getThumbnailAsync(imageUrl, { time: 0 });
      } catch (e) {
        console.error(e);
      }
  }
 
 generateThumbnail("https://vengaclimb.s3.amazonaws.com/gyms%2Fcjqfhjyh822bp0831lcarhik9%2Froutes%2Fpictures%2Fck2mbriwt8em70875gvnk0m0j%2F1576100041157_1280x720.mp4");
}
```

### Expected Behavior

Expect app not to crash.

### Actual Behavior

App crashes with no errors in console or Sentry. This is the error I see in Android Studio:

```
2019-12-12 11:40:09.032 1749-20030/? E/NuCachedSource2: source returned error -1010, 0 retries left
2019-12-12 11:40:09.079 1749-1749/? E/StagefrightMetadataRetriever: extractor doesn't publish metadata, failed to initialize?
2019-12-12 11:40:09.079 1749-1749/? E/MetadataRetrieverClient: failed to capture a video frame
2019-12-12 11:40:09.079 19640-19720/host.exp.exponent E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
2019-12-12 11:40:09.130 19640-19640/host.exp.exponent E/AndroidRuntime: FATAL EXCEPTION: main
    Process: host.exp.exponent, PID: 19640
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at abi35_0_0.expo.modules.videothumbnails.VideoThumbnailsModule$1.onPostExecute(VideoThumbnailsModule.java:4)
        at abi35_0_0.expo.modules.videothumbnails.VideoThumbnailsModule$1.onPostExecute(VideoThumbnailsModule.java:1)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Reproducible Demo

https://snack.expo.io/@vjsingh/expo-video-thumbnail-android-bug

**Comment by cruzach** [comment]
Hm your repro didn't crash for me, but looks like [this one](https://snack.expo.io/@charliecruzan/expo-video-thumbnail-android-bug) from our docs does

thanks for reporting this, and for creating such a clear issue ticket 😄 it really helps!

**Comment by vjsingh** [comment]
@cruzach - No problem - glad to hear you managed to repro! That's the goal of this whole thing anyway. It was sporadic for me but seemed to happen when I opened a tab with a video thumbnail, navigated away, and then navigated back to it, the app would crash.

If I understand correctly, a fix for this will not make it in before, at the earliest, the next release of Expo? Or is there a possibility of somehow patching in to an existing release?

Our plan is to replace video thumbnails with a colored background and text on Android, so we have a fix but just curious on potential timeline. Thanks again for all your work on an excellent library.

**Comment by cruzach** [comment]
For standalone apps, which I'm guessing is higher importance for you since that would be production apps, we might be able to fix it. Although I can't give you a timeline unfortunately :(

**Comment by vjsingh** [comment]
@cruzach Gotcha, no worries I understand that you can't give an actual timeline. Yes, this is for a production app. Thanks for the info!

**Comment by Jesus-Blumer** [comment]
Any updates about this issue?

**Comment by lukmccall** [comment]
@vjsingh, I've looked into your problem and tried to fix it. Unfortunately, I ended up getting this exception: `java.lang.RuntimeException: setDataSource failed: status = 0x80000000`. 
It means that your file is corrupted - Android can't generate thumbnail from it. 
Sadly, I don't know why Android can handle your file.

However, I'll add better error handling. So this won't crash anymore.

**Comment by vjsingh** [comment]
Thanks @lukmccall !
