### ISSUE TITLE
ExpoKit SDK36: android debug build crashing because of Crashlytics

### ISSUE THREAD

**Issue by rodneyrehm** [expo/expo#6565]
### Environment

```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.7 - /usr/local/bin/zsh
    Binaries:
      Node: 12.9.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.7 => 32.0.13
      @types/react: ^16.8.23 => 16.9.16
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.1
```

Building ExpoKit (SDK36) for Android.

### Steps to Reproduce

* do not have anything about Crashlytics configured
* eject from managed workflow to ExpoKit
* build debug version in Android Studio and deploy to phone

### Expected Behavior

App starts normally.

### Actual Behavior

App crashes immediately (even before splash Screen) with the following logged to Android Studio log:

```
--------- beginning of crash
2019-12-17 13:34:22.103 18116-18116/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.application.bundle.id, PID: 18116
    java.lang.RuntimeException: Unable to get provider com.crashlytics.android.CrashlyticsInitProvider: io.fabric.sdk.android.services.concurrency.UnmetDependencyException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app’s build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at android.app.ActivityThread.installProvider(ActivityThread.java:7110)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6594)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6498)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: io.fabric.sdk.android.services.concurrency.UnmetDependencyException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app’s build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:243)
        at com.crashlytics.android.core.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:211)
        at io.fabric.sdk.android.InitializationTask.onPreExecute(InitializationTask.java:44)
        at io.fabric.sdk.android.services.concurrency.AsyncTask.executeOnExecutor(AsyncTask.java:611)
        at io.fabric.sdk.android.services.concurrency.PriorityAsyncTask.executeOnExecutor(PriorityAsyncTask.java:43)
        at io.fabric.sdk.android.Kit.initialize(Kit.java:69)
        at io.fabric.sdk.android.Fabric.initializeKits(Fabric.java:466)
        at io.fabric.sdk.android.Fabric.init(Fabric.java:410)
        at io.fabric.sdk.android.Fabric.setFabric(Fabric.java:368)
        at io.fabric.sdk.android.Fabric.with(Fabric.java:339)
        at com.crashlytics.android.CrashlyticsInitProvider.onCreate(CrashlyticsInitProvider.java:35)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7107)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6594) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6498) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

### Workaround

We've commented out https://github.com/expo/expo/blob/e4da7d0cfc26125cd50e016036db055700d6e3ee/android/app/build.gradle#L66 and the app started normally.

**Comment by tommyzat** [comment]
I'm having the same issue

**Comment by Bashin** [comment]
Same issue with my managed android SDK 36 build. App starting up twice and in that process dropping all information when started with a deep link.
Propably related: #6586

**Comment by tsapeta** [comment]
I'm closing this issue as we no longer support ExpoKit and Crashlytics is now deprecated as well.
