### ISSUE TITLE
expo and jest can't produce --coverage

### ISSUE THREAD

**Issue by kopax** [expo/expo#6612]
I am in a react-native (expo SDK36) application , I have configured jest using the explanation from expo documentation https://docs.expo.io/versions/v36.0.0/guides/testing-with-jest/.

This is how my jest configuration look like:

```json
{
  "dependencies": {
    "jest-expo": "^36.0.1",
    "jest-sonar-reporter": "^2.0.0"
  },
  "jest": {
    "testURL": "http://localhost",
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 0,
        "branches": 0,
        "functions": 0,
        "lines": 0
      }
    },
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/build/",
      "/server",
      "/server/node_modules/",
      "/public",
      "/coverage",
      "/stylguide",
      "package.json",
      "package-lock.json"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest.setup.js"
    ],
    "testResultsProcessor": "jest-sonar-reporter"
  },
  "jestSonar": {
    "reportPath": "reports",
    "reportFile": "test-report.xml",
    "indent": 2
  }
}

```

It produces the following error when I run `NODE_ENV=test jest --coverage`:

```
 PASS  src/tests/index.test.js
  <App />
    ✓ has 1 child (85ms)

TypeError: mappedCoverage.addStatement is not a function
    at /home/dka/workspace/test-native/node_modules/istanbul-lib-source-maps/lib/transformer.js:30:32
    at Array.forEach (<anonymous>)
    at SourceMapTransformer.processFile (/home/dka/workspace/test-native/node_modules/istanbul-lib-source-maps/lib/transformer.js:22:38)
    at /home/dka/workspace/test-native/node_modules/istanbul-lib-source-maps/lib/transformer.js:120:34
    at Array.forEach (<anonymous>)
    at SourceMapTransformer.transform (/home/dka/workspace/test-native/node_modules/istanbul-lib-source-maps/lib/transformer.js:109:29)
    at MapStore.transformCoverage (/home/dka/workspace/test-native/node_modules/istanbul-lib-source-maps/lib/map-store.js:173:14)
    at /home/dka/workspace/test-native/node_modules/@jest/reporters/build/coverage_reporter.js:225:59
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/dka/workspace/test-native/node_modules/@jest/reporters/build/coverage_reporter.js:124:24)
```

Some googling din't show me how to solve `TypeError: mappedCoverage.addStatement is not a function`.

Is anyone able to help me or give a little clue ?

Thanks and best!

**Comment by kopax** [comment]
## Reproduction

```
git clone https://github.com/kopax/expo-native.git
cd expo-native
npm i
```

Run coverage:

```
npm run test
```

Test will pass, I expect them to pass

Build web:

```
npm run web
npm test
```

Test will fail, I expect them to pass.

This must be due to jest ignoring the current configuration when `--coverage true` switch is on.

Any idea how I can fix the coverage ?
