### ISSUE TITLE
Jest  SyntaxError: Unexpected token 'export' at ScriptTransformer._transformAndBuildScript

### ISSUE THREAD

**Issue by kopax** [expo/expo#6638]
I am building an expo react-native app with expo SDK 36.

Jest was configured and the **last pipeline on `dev` was able to run test,

However, if I clone now, even if I have a `package-lock.json`, I have the failing test:

```bash
 FAIL  src/tests/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/dka/workspace/test-native-copy/node_modules/unimodules-permissions-interface/build/PermissionsInterface.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export var PermissionStatus;
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/expo-location/src/Location.ts:2:1)
```

This is how the test look like:

```jsx
import React from 'react';
import renderer from 'react-test-renderer';

import App from '..';

describe('<App />', () => {
  it('has 1 child', () => {
    const tree = renderer.create(<App />).toJSON();
    expect(tree.children.length).toBe(1);
  });
});
```

This is my `jestConfig`:

```json
{
  "jest": {
    "testURL": "http://localhost",
    "preset": "jest-expo",
    "testPathIgnorePatterns": [
      "/test.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 0,
        "branches": 0,
        "functions": 0,
        "lines": 0
      }
    },
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/web",
      "/web-build/",
      "/public",
      "/coverage",
      "/stylguide",
      "webpack.config.js",
      "package.json",
      "package-lock.json"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest.setup.js"
    ]
  }
}
```

This is my root file structure:

```
.
├── App.js
├── app.json
├── assets
├── babel.config.js
├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── coverage
├── deploy_dev.json
├── deploy_preprod.json
├── deploy_prod.json
├── deploy_staging.json
├── docker-compose.yml
├── Dockerfile
├── docs
├── LICENSE.md
├── node_modules
├── package.json
├── package-lock.json
├── public
├── README.md
├── release-docker.sh
├── reports
├── server
├── sonar-project.properties
├── src
├── styleguide
├── styleguide.config.js
├── web
└── web-build

11 directories, 19 files
```

This is my `jest` and `expo` version:

```json
{
    "react": "~16.12.0",
    "react-dom": "^16.12.0",
    "react-native-web": "^0.11.7",
    "expo": "~36.0.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "expo-cli": "^3.11.3",
    "jest-expo": "^36.0.1"
}
```

How can I fix the test in jest?

**Comment by kopax** [comment]
I have found that this error go away if I remove that line:

```jsx
import { AppLoading, SplashScreen } from 'expo';
```

**Comment by kopax** [comment]
Fixed by replacing in jest configuration `transformIgnorePatterns`:

```diff
- "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
+ "node_modules/(?!(jest-)?react-native|unimodules-permissions-interface|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
```

Shouldn't this be a default settings?

**Comment by cruzach** [comment]
Looks like there's a PR open to update that config -> https://github.com/expo/expo/pull/6602 which will account for all `unimodules-*` cases 👍
