### ISSUE TITLE
[SDK36] npm run eject break on the blank expo project break npm run android 

### ISSUE THREAD

**Issue by kopax** [expo/expo#6666]
## `npm run eject` break my project

I have tried to eject a blank application tu see what it was, and after running `npm run eject` command and choosing `bare` react native project, I am not able to start again

After running the eject command, it invited me to unlink the following so I did:

```bash
$ react-native unlink react-native-gesture-handler && react-native unlink react-native-reanimated && react-native unlink react-native-screens
```

That's somehow a big problem I need to fix since I wanted to start using expo on SDK36 and I see all those unexplained things (at the moment), though I could correct most of them with knowledge, this is out of my current knowledge scope.

## Expect

I expect to be able to run `npm run android` and still be able to run my project running on android.

## Result

`npm run android` fail with:

```
dka@dka:[~/workspace/github.com/kopax/expo/bug-reports (with-jest-ejected)]: npm run android

> @ android /home/dka/workspace/github.com/kopax/expo/bug-reports
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1313 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Configure project :app

Installing unimodules:
 unimodules-core@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/@unimodules/core
 unimodules-react-native-adapter@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/@unimodules/react-native-adapter
 expo-app-loader-provider@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-app-loader-provider
 expo-constants@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-constants
 expo-error-recovery@1.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-error-recovery
 expo-file-system@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-file-system
 expo-font@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-font
 expo-keep-awake@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-keep-awake
 expo-linear-gradient@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-linear-gradient
 expo-location@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-location
 expo-permissions@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-permissions
 expo-sqlite@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-sqlite
 expo-web-browser@8.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/expo-web-browser
 unimodules-barcode-scanner-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-barcode-scanner-interface
 unimodules-camera-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-camera-interface
 unimodules-constants-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-constants-interface
 unimodules-face-detector-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-face-detector-interface
 unimodules-file-system-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-file-system-interface
 unimodules-font-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-font-interface
 unimodules-image-loader-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-image-loader-interface
 unimodules-permissions-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-permissions-interface
 unimodules-sensors-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-sensors-interface
 unimodules-task-manager-interface@5.0.0 from /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/unimodules-task-manager-interface

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo-error-recovery', ':expo-permissions'

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings
269 actionable tasks: 1 executed, 268 up-to-date
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainActivity.java:6: error: package com.swmansion.gesturehandler.react does not exist
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
                                         ^
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainApplication.java:40: error: cannot find symbol
          new ReanimatedPackage(),
              ^
  symbol: class ReanimatedPackage
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainApplication.java:41: error: cannot find symbol
          new RNGestureHandlerPackage(),
              ^
  symbol: class RNGestureHandlerPackage
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainApplication.java:42: error: cannot find symbol
          new RNScreensPackage(),
              ^
  symbol: class RNScreensPackage
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainActivity.java:24: error: cannot find symbol
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
                           ^
  symbol: class RNGestureHandlerEnabledRootView
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainActivity.java:6: error: package com.swmansion.gesturehandler.react does not exist
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
                                         ^
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainApplication.java:40: error: cannot find symbol
          new ReanimatedPackage(),
              ^
  symbol: class ReanimatedPackage
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainApplication.java:41: error: cannot find symbol
          new RNGestureHandlerPackage(),
              ^
  symbol: class RNGestureHandlerPackage
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainApplication.java:42: error: cannot find symbol
          new RNScreensPackage(),
              ^
  symbol: class RNScreensPackage
/home/dka/workspace/github.com/kopax/expo/bug-reports/android/app/src/main/java/com/bugreports/MainActivity.java:24: error: cannot find symbol
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
                           ^
  symbol: class RNGestureHandlerEnabledRootView
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at checkExecSyncError (child_process.js:610:11)
    at execFileSync (child_process.js:628:15)
    at runOnAllDevices (/home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/home/dka/workspace/github.com/kopax/expo/bug-reports/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:164:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ android: `react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dka/.npm/_logs/2020-01-03T15_33_24_053Z-debug.log
```

## Reproduction

[GH project](https://github.com/kopax/expo-bug-reports/tree/with-jest-ejected) branch `with-jest-ejected`

```bash
git clone https://github.com/kopax/expo-bug-reports.git
cd expo-bug-reports
git checkout with-jest-ejected
npm i
npm test
npm run android
```

[Travis log](https://www.travis-ci.org/kopax/expo-bug-reports/jobs/632331366) => but they fail for some other reason, while they used to work before running `npm run eject`

##  `expo diagnostics`

```bash
  Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 5.3 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v13.5.0/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.11.3
```

Thank you in advance for opinion and best!

**Comment by kopax** [comment]
Wow guys, looking at the issues id, it sounds pretty bad.

**Comment by cruzach** [comment]
I'm not sure why those unlink warnings are showing up, but I don't think you should unlink.

I just tested ejecting a blank `expo init` SDK 36 tabs template app to bare, and running `yarn android` works (after fiddling a little bit since [AppLoading](https://docs.expo.io/versions/latest/sdk/app-loading/) isn't available in bare yet)

**Comment by kopax** [comment]
I can have another try, I've created the project in order to reproduce bugs quickly not to get my issues closed too quickly. 

> after fiddling a little bit since [AppLoading](https://docs.expo.io/versions/latest/sdk/app-loading/) isn't available in bare yet

Could you please be more specific on that part? It is not working straight (as described in the expo doc)? What have you changed?

**Comment by cruzach** [comment]
@kopax your issues are being closed because they are not bugs with the Expo SDK, but general questions regarding Expo, react-native, or 3rd party libraries (for answers, our [docs](https://docs.expo.io/versions/latest/) are very helpful, and if you can't find it there then feel free to ask on our [forums](https://forums.expo.io/))

If you want to try out the bare workflow, I suggest following [this walkthrough](https://docs.expo.io/versions/v36.0.0/bare/exploring-bare-workflow/). AppLoading isn't available for the bare workflow yet, so you can't use that module outside of the managed workflow - [see here for more info](https://docs.expo.io/versions/v36.0.0/introduction/managed-vs-bare/)

**Comment by kopax** [comment]
Thanks for the walkthrough link, I didn't went through it's my bad, I try to get through the most of it, I will multiply my checks to the docs before asking here. I was pointing at that issue https://github.com/expo/expo/issues/6660, unless you wanted on purpose to support a reduced API of the from the underlying libs, which I doubted at the first place, it should be treated as an issue or at minimum an improvement, not as a support request.

**Comment by cruzach** [comment]
Closing this issue in favor of https://github.com/expo/expo-cli/issues/1398 since it is more direct, is in the `expo-cli` repo, and follows the bug report template

as for 6660, we can continue the conversation there
