### ISSUE TITLE
[sdk36][android] app random crash from StyleSheet null

### ISSUE THREAD

**Issue by giautm** [expo/expo#6704]
### Environment
```
  Expo CLI 3.11.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.7479.19.35.5763348
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.0 => 16.9.11 
      @types/react-native: ^0.60.15 => 0.60.27 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.6 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.2
```
App's target: Android, Standalone

### Expected Behavior

Run without crash

### Actual Behavior

App crash on startup with random style error, please view bellow logcat:

**First crash**
```
01-08 10:57:07.561 24651 24790 D i       : WARNING: getPackageName called on ScopedContext
01-08 10:57:07.598 24651 24790 I chatty  : uid=10197(xxxxxxxxxxxxxxxxx) logThread identical 3 lines
01-08 10:57:07.602 24651 24790 D i       : WARNING: getPackageName called on ScopedContext
01-08 10:57:07.629 24651 24701 D b       : Loaded exp.host status page.
01-08 10:57:07.635 24651 24733 W unknown:ReactNative: StatusBarModule: Ignored status bar change, current activity is null.
01-08 10:57:07.638 24651 24733 I chatty  : uid=10197(xxxxxxxxxxxxxxxxx) mqt_native_modu identical 2 lines
01-08 10:57:07.638 24651 24733 W unknown:ReactNative: StatusBarModule: Ignored status bar change, current activity is null.
01-08 10:57:07.660 24651 24794 I WebViewFactory: Loading com.google.android.webview version 78.0.3904.108 (code 390410838)
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 0
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 1
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 2
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 3
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 4
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 5
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 6
01-08 10:57:07.693 24758 24758 E sound_trigger_platform: platform_stdev_init: Unable to open the mixer card 7
01-08 10:57:07.699  3511  3570 I ServiceManager: Waiting for service 'media.audio_policy' on '/dev/binder'...
01-08 10:57:07.736 24651 24794 I cr_LibraryLoader: Time to load native libraries: 2 ms
01-08 10:57:07.750 24651 24794 I chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
01-08 10:57:07.750 24651 24794 I cr_LibraryLoader: Expected native library version number "78.0.3904.108", actual native library version number "78.0.3904.108"
01-08 10:57:07.771   617 24802 E ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: Error while updating prop alignItems
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setAlignItems argument 1 has type java.lang.String, got java.lang.Integer
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:3)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:214)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
01-08 10:57:07.912 24651 24733 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:919)
01-08 10:57:07.928 24651 24651 D AndroidRuntime: Shutting down VM
01-08 10:57:07.929 24651 24651 E AndroidRuntime: FATAL EXCEPTION: main
01-08 10:57:07.929 24651 24651 E AndroidRuntime: Process: xxxxxxxxxxxxxxxxx, PID: 24651
01-08 10:57:07.929 24651 24651 E AndroidRuntime: java.lang.RuntimeException: Expo encountered a fatal error: Error while updating property 'alignItems' in shadow node of type: RCTView
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-08 10:57:07.929 24651 24651 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: Error while updating prop paddingHorizontal
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setPaddings argument 1 has type int, got null
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:7)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:214)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
01-08 10:57:07.967 24651 24733 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:919)
```

**Second crash:**
```
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: Error while updating prop paddingVertical
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setPaddings argument 1 has type int, got null
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:7)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:214)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
01-08 11:04:44.075 27800 27888 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:919)
01-08 11:04:44.083 27800 27800 D AndroidRuntime: Shutting down VM
01-08 11:04:44.083 27800 27800 E AndroidRuntime: FATAL EXCEPTION: main
01-08 11:04:44.083 27800 27800 E AndroidRuntime: Process: xxxxxxxxxxxxxxxxx, PID: 27800
01-08 11:04:44.083 27800 27800 E AndroidRuntime: java.lang.RuntimeException: Expo encountered a fatal error: Error while updating property 'paddingVertical' in shadow node of type: AndroidTextInput
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-08 11:04:44.083 27800 27800 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

```
01-08 11:57:02.646 10045 10045 W unknown:WrappingUtils: Don't know how to round that drawable: com.facebook.drawee.drawable.RoundedColorDrawable@fec640
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: Error while updating prop fontFamily
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: java.lang.IllegalArgumentException: method com.facebook.react.views.text.ReactBaseTextShadowNode.setFontFamily argument 1 has type java.lang.String, got com.facebook.react.bridge.DynamicFromObject
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:3)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:214)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
01-08 11:57:02.934 10045 10133 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:919)
01-08 11:57:02.945 10045 10045 D AndroidRuntime: Shutting down VM
01-08 11:57:02.945 10045 10045 E AndroidRuntime: FATAL EXCEPTION: main
01-08 11:57:02.945 10045 10045 E AndroidRuntime: Process: xxxxxxxxxxxxxxxxx, PID: 10045
01-08 11:57:02.945 10045 10045 E AndroidRuntime: java.lang.RuntimeException: Expo encountered a fatal error: Error while updating property 'fontFamily' in shadow node of type: RCTText
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-08 11:57:02.945 10045 10045 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

My app still working normaly before I upgraded to SDKv36 then build new APK. I can confirm no-where in my app/third party modules set that properties to null value. :'(

*Update another crash*
```
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: Error while updating prop overflow
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: java.lang.reflect.InvocationTargetException
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:3)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:214)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:919)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: Caused by: com.facebook.react.bridge.JSApplicationIllegalArgumentException: invalid value for overflow: Tiếp tục
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	at com.facebook.react.uimanager.LayoutShadowNode.setOverflow(LayoutShadowNode.java:5)
01-08 11:21:03.469  3916  4017 E unknown:ViewManager: 	... 17 more
01-08 11:21:03.475  3916  3916 D AndroidRuntime: Shutting down VM
01-08 11:21:03.476  3916  3916 E AndroidRuntime: FATAL EXCEPTION: main
01-08 11:21:03.476  3916  3916 E AndroidRuntime: Process: xxxxxxx, PID: 3916
01-08 11:21:03.476  3916  3916 E AndroidRuntime: java.lang.RuntimeException: Expo encountered a fatal error: Error while updating property 'overflow' in shadow node of type: RCTView
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-08 11:21:03.476  3916  3916 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
`Tiếp tục` is children of `Button` on first screen, can't be `overflow` property.
<img width="745" alt="Screen Shot 2020-01-08 at 11 27 31" src="https://user-images.githubusercontent.com/12751435/71950466-ee294d00-3209-11ea-94fd-34f12dcb6c22.png">

**Comment by esamelson** [comment]
Hey there @giautm - sorry you're running into this, it sounds frustrating 😞 unfortunately there's not much we can do to help with just these crash logs. If you're able to come up with a full, working example (ideally a [snack](https://snack.expo.io) or small GH repo) that reliably reproduces this error, feel free to open a new issue, fill out the template fully and we'll do our best to help you out there! [This guide](https://stackoverflow.com/help/minimal-reproducible-example) may help with that. I'm going to go ahead and close this issue.
