### ISSUE TITLE
[AppAuth] can't change response_type, if provided in additionalParameters app crashes

### ISSUE THREAD

**Issue by jurisjansons** [expo/expo#6710]
## 🐛 Bug Report

AppAuth makes all requests with `response_type="code"` and I neet to change it to `id_token`, if I provide `response_type` in config under `additionalParameters` then app crashes, tested only on Android, for now.

### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548

### Steps to Reproduce

Take example from expo.io documentation page about AppAuth and add: `additonalParameters: { response_type: "id_token" }`  and try to authenticate. `id_token` can be replaced with any other value.

### Expected Behavior

To create request to issuer with `response_type` parameter provided in additionalParameters

### Actual Behavior

App crashes

### Reproducible Demo

You can see the same behavior in this [snack](https://snack.expo.io/@aihen/app-auth-crash).

**Comment by esamelson** [comment]
Thanks for reporting this @jurisjansons - I've reproduced this, the stack trace is
```
01-08 12:23:47.503  7753  7753 E AndroidRuntime: FATAL EXCEPTION: main
01-08 12:23:47.503  7753  7753 E AndroidRuntime: Process: host.exp.exponent, PID: 7753
01-08 12:23:47.503  7753  7753 E AndroidRuntime: java.lang.IllegalArgumentException: Parameter response_type is directly supported via the authorization request builder, use the builder method instead
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at net.openid.appauth.p.a(Preconditions.java:6)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at net.openid.appauth.a.a(AdditionalParamsProcessor.java:11)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at net.openid.appauth.e$b.a(AuthorizationRequest.java:14)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at abi36_0_0.expo.modules.appauth.AppAuthModule.authWithConfiguration(AppAuthModule.java:13)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at abi36_0_0.expo.modules.appauth.AppAuthModule.access$200(AppAuthModule.java:1)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at abi36_0_0.expo.modules.appauth.AppAuthModule$2.onFetchConfigurationCompleted(AppAuthModule.java:4)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at net.openid.appauth.h$a.a(AuthorizationServiceConfiguration.java:20)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at net.openid.appauth.h$a.onPostExecute(AuthorizationServiceConfiguration.java:1)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:755)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at android.os.AsyncTask.access$900(AsyncTask.java:192)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-08 12:23:47.503  7753  7753 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
