### ISSUE TITLE
Standalone APK Crashes on start - Random reason why - With expo-template-tabs template.

### ISSUE THREAD

**Issue by mrdj07** [expo/expo#6746]
## 🐛 Bug Report

Initially I am developping a new application, that I started building from the expo template. Everything's been going well, excep when I started building the app as an APK. When running the app on my device, a Samsung Tab A 2019 Tablet running Android 9, it crashes on startup 9 times out of 10. Eventually the app boot goes through and the app can be used and no other problems occur.  Looking at the logcat, every crash generates a different, but similar error. Some kind of error trying to update a particuliar property (the problematic property changes every error). Logs example below.

I couldn't for the life of me figure out what the hell is wrong with the code base or versions that could cause it to crash like this. So I started fresh with a new expo-template-tabs template, and build that template and ran it on my device. Same problem !

### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832

Using Expo SDK 36.0.0.

Targetting Android 9, developping on Samsung Tab A Tablet

### Steps to Reproduce

- Ran Expo init with expo-template-tabs template.
- Ran expo build:android -t apk
- Download APK
- Run APK to device with Android Studio

### Expected Behavior

App should open and not crash.

### Actual Behavior

App crashed 9/10 times.

### Reproducible Demo

I just reproduced it with the expo-template-tabs template.

--------------------------------------

Now looking at the logs through adb logcat, here's what's coming out:

`
2020-01-12 16:34:09.577 23131-23220/? E/unknown:ViewManager: Error while updating prop paddingVertical
    java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setPaddings argument 1 has type int, got null
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:7)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:764)
2020-01-12 16:34:09.588 23131-23131/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.prmi.guidetest, PID: 23131
    java.lang.RuntimeException: Expo encountered a fatal error: Error while updating property 'paddingVertical' in shadow node of type: RCTView
        at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7100)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2020-01-12 16:34:09.601 23131-23220/? E/unknown:ViewManager: Error while updating prop position
    java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setPosition argument 1 has type java.lang.String, got java.lang.Float
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:3)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:764)
2020-01-12 16:34:09.616 23131-23220/? E/unknown:ViewManager: Error while updating prop height
    java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setHeight argument 1 has type com.facebook.react.bridge.Dynamic, got java.lang.String
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:3)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:764)
2020-01-12 16:34:09.650 23131-23220/? E/unknown:ViewManager: Error while updating prop height
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:3)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.Dynamic.isNull()' on a null object reference
        at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:1)
        at com.facebook.react.uimanager.LayoutShadowNode.setHeight(LayoutShadowNode.java:2)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:3) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:2) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:14) 
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:1) 
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:11) 
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:5) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
        at android.os.Looper.loop(Looper.java:214) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8) 
        at java.lang.Thread.run(Thread.java:764) 
2020-01-12 16:34:10.007 23062-23247/? E/FasUtils: pkg=null userId=0 has no information
`

**Comment by wen-kai** [comment]
Looks like a reliable repro for https://github.com/expo/expo/issues/6523

**Comment by mrdj07** [comment]
I believe so yes. I'll try turning it off and see if it fixes it.

**Comment by cruzach** [comment]
@mrdj07 I tested the `expo-tabs-template` standalone, both on android 9 and 10, in the hopes that it would be a repro for the other mentioned issue, but saw no crashes (tried opening/closing ~10 times each device)

**Comment by mrdj07** [comment]
Make sure you have a dark theme enabled.

**Comment by cruzach** [comment]
I have it enabled on the device. Did you set `"userInterfaceStyle"` in app.json? I didn't think so since it's a blank project

**Comment by mrdj07** [comment]
Try with this APK, https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40mr_dj07/Trying-0ab02018ec004f1d9e5ea49d6534f85f-signed.apk

This the expo-tabs-template I built. From Android Studio, I was able to make it crash on my device.

**Comment by cruzach** [comment]
No crash (also that doesn't look like the tabs-template to me, not sure if that's the apk you meant to send)

**Comment by mrdj07** [comment]
You are right ! Here is the right APK: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40mr_dj07/prmi_new-c1849b1cd222440ca5b9147453a71014-signed.apk

I just tried it on my Pixel 3, that has Dark Theme activated and it crashes. Please also note that it CAN open.

**Comment by cruzach** [comment]
there we go, that crashed (took about 8 opens to get a crash, so not near your 9/10 crash rate, not sure why)

Now, this is just a plain, blank `expo init` tabs-template project, you added the `android.package` field in app.json, then built with `expo build:android`?

**Comment by mrdj07** [comment]
Yes exactly.

**Comment by lukmccall** [comment]
I'm closing this issue, cause it's a duplication. Please, check the original thread.
