### ISSUE TITLE
SDK36 Android standalone app crashes

### ISSUE THREAD

**Issue by ru88s** [expo/expo#6878]
## 🐛 Bug Report
https://github.com/expo/expo/pull/6825
The same applies when night mode is ON.
My workflow is create-react-native-app.
Flashes and crashes when launching the app.

```
java.lang.RuntimeException: Expo encountered a fatal error: TypeError: null is not an object (evaluating 'y.NativeAppearance.initialPreferences')
at host.exp.exponent.experience.a$2.run(BaseExperienceActivity.java:197)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```
### Environment

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.7.0 - ~/.nodebrew/current/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.13.6 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7
```

```
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "axios": "^0.19.0",
    "ex-react-native-i18n": "0.0.6",
    "expo": "^36.0.0",
    "expo-ads-admob": "~8.0.0",
    "expo-analytics": "^1.0.11",
    "expo-analytics-amplitude": "~8.0.0",
    "expo-blur": "~8.0.0",
    "expo-codemod": "1.0.6",
    "expo-constants": "~8.0.0",
    "expo-file-system": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-keep-awake": "~8.0.0",
    "expo-linear-gradient": "~8.0.0",
    "expo-localization": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-speech": "~8.0.0",
    "expo-store-review": "~2.0.0",
    "expo-web-browser": "~8.0.0",
    "firebase": "^6.1.1",
    "linkify-it": "^2.2.0",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-app-intro-slider": "^1.0.1",
    "react-native-appearance": "~0.3.1",
    "react-native-dialog": "^5.6.0",
    "react-native-easy-toast": "^1.2.0",
    "react-native-elements": "1.2.3",
    "react-native-expo-image-cache": "^4.0.8",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-local-mongodb": "^2.2.9",
    "react-native-reanimated": "~1.4.0",
    "react-native-sortable-list": "0.0.22",
    "react-native-storage": "^1.0.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "7.4.3",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.3",
    "react-navigation-tabs": "^2.5.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "sentry-expo": "~2.0.0",
    "turtle-cli": "^0.13.8"
  },
```

**Comment by lukmccall** [comment]
Thank for creating a separate issue.

I need more information from you:
- Could you also provide me with your `app.json`?
- Have you cleared yarn/npm cache?

**Comment by ru88s** [comment]
My app.json:
Important parts are hidden.
```
{
  "expo": {
    "name": "xxxxxxxxxxx",
    "description": "xxxxxxxxxxx",
    "slug": "xxxxxxxxxxx",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "2.0.0",
    "orientation": "portrait",
    "extra": {
      "backgroundColor": "#ffffff",
      "ga": "UA-xxxxxxxxxxx-1",
      "amplitudeApiKey": "xxxxxxxxxxx",
      "firebase": {
        "apiKey": "xxxxxxxxxxx",
        "authDomain": "xxxxxxxxxxx.firebaseapp.com",
        "databaseURL": "https://xxxxxxxxxxx.firebaseio.com",
        "projectId": "xxxxxxxxxxx",
        "storageBucket": "xxxxxxxxxxx.appspot.com",
        "messagingSenderId": "xxxxxxxxxxx",
        "appId": "1:xxxxxxxxxxx:web:xxxxxxxxxxx"
      }
    },
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "/*"
    ],
    "ios": {
      "buildNumber": "1",
      "supportsTablet": true,
      "bundleIdentifier": "jp.co.xxxxxxxxxxx.xxxxxxxxxxx",
      "infoPlist": {
        "CFBundleDevelopmentRegion": "ja_JP",
        "NSCameraUsageDescription": "xxxxxxxxxxx",
        "NSPhotoLibraryUsageDescription": "xxxxxxxxxxx",
        "NSPhotoLibraryAddUsageDescription": "xxxxxxxxxxx"
      },
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-xxxxxxxxxxx~xxxxxxxxxxx"
      },
      "userInterfaceStyle": "automatic"
    },
    "android": {
      "versionCode": 39,
      "package": "jp.co.xxxxxxxxxxx.xxxxxxxxxxx",
      "splash": {
        "mdpi": "assets/images/mdpi/splash.png",
        "hdpi": "assets/images/hdpi/splash.png",
        "xhdpi": "assets/images/xhdpi/splash.png",
        "xxhdpi": "assets/images/xxhdpi/splash.png",
        "xxxhdpi": "assets/images/xxxhdpi/splash.png"
      },
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-xxxxxxxxxxx~xxxxxxxxxxx"
      }
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "xxxxxxxxxxx",
            "project": "xxxxxxxxxxx",
            "authToken": "xxxxxxxxxxx"
          }
        }
      ]
    }
  }
}
```

`rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c`

Installed with this.

**Comment by lukmccall** [comment]
Sorry, I'm a little bit confused right now. 
I'm not sure what `Installed with this.` means. Does the app crash in expo-client? Or maybe you build it using `expo build:android`?

**Comment by ru88s** [comment]
I'm sorry you have troubled me.

> Does the app crash in expo-client?
Yes, it's OK on Expo.

> expo build: android?
Yes, I do.

I am updating expo to 36.0.2 and testing it.
Direct installation and startup was successful.
However, it always crashes when downloading from the store.
I'll give it a try.

**Comment by lukmccall** [comment]
So to sum everything up, you built your app again after the fix was released. Next, you uploaded your app to play store (using [expo upload:android](https://docs.expo.io/versions/latest/distribution/uploading-apps/#21-if-you-choose-to-upload-your) or manually through the play store page). And only build from the play store doesn't work.
Are you sure that the version in the store is the newest one (Google need to accept the new version of your application - it can take some time)?

**Comment by ru88s** [comment]
Yes, that's right.

And, as a result of changing expo to `"expo": "^ 36.0.2"`  it started successfully. 
It is a solution.I have no idea why.

Sorry for confusing.
And thank you very much.
