### ISSUE TITLE
xCode Build Failed: Use of Const in Strict Mode

### ISSUE THREAD

**Issue by usegravity** [expo/expo#6951]
### Environment

 Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      npm: 6.12.1 - ~/.nvm/versions/node/v12.4.0/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.1.0 => 4.1.0 
    npmGlobalPackages:
      expo-cli: 3.11.7

Target: iOS

### Steps to Reproduce

Ejected Expo project (which runs fine as managed) and followed the documentation (pod update & pod install) then open the .xcworkspace file.

### Expected Behavior

Build and run iOS application.

### Actual Behavior

Build fails with the following error message:

/Users/Kyle/.nvm/versions/node/v12.4.0/lib/node_modules/expo-cli/node_modules/chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Kyle/.nvm/versions/node/v12.4.0/lib/node_modules/expo-cli/bin/expo.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by cruzach** [comment]
Is this ejected to expokit, or to bare? What command did you run that resulted in this error? Does it happen on a blank ejected `expo init` project?
