### ISSUE TITLE
jest `npm run test` error

### ISSUE THREAD

**Issue by bryanboyko** [expo/expo#7021]
I've followed the latest documentation here

https://docs.expo.io/versions/latest/guides/testing-with-jest/ 

And added the following code to my package.json

```"jest": {
  "preset": "jest-expo",
  "transformIgnorePatterns": [
    "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base)"
  ]
}```

Then after npm installing and running `npm run test`, I get the following error.

> @ test /Users/bryanboyko/XCode/Project9A/redpoint_client
> jest

 FAIL  ./App.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/bryanboyko/XCode/Project9A/redpoint_client/node_modules/@sentry/react-native/dist/js/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { Severity, Status } from "@sentry/types";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/sentry-expo/index.js:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.117s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bryanboyko/.npm/_logs/2020-02-11T23_25_05_761Z-debug.log

**Comment by bryanboyko** [comment]
Looks to be the same sentry issue that showed up here:

https://github.com/expo/expo/issues/6638

Although the fix is no longer working?

**Comment by bryanboyko** [comment]
Resolved by adding `@sentry/.*` to `transformIgnorePatters`, although then ran into the following issue

``` FAIL  ./App.test.js
  ● Test suite failed to run

    ReferenceError: FormData is not defined

      at Object.<anonymous> (node_modules/react-native-aws3-cognito/lib/Request.js:148:20)
      at Object.<anonymous> (node_modules/react-native-aws3-cognito/lib/RNS3.js:16:16)```

**Comment by cruzach** [comment]
the provided `transformIgnorePatters` is a starting point, but will change based  on what libraries you add to your project. Closing since you opened a new ticket for `FormData is not defined`
