### ISSUE TITLE
jest `npm run test` failing due to `react-native-aws3-cognito`

### ISSUE THREAD

**Issue by bryanboyko** [expo/expo#7022]
Follow Expo documentation to setup jest found here

https://docs.expo.io/versions/latest/guides/testing-with-jest/

Execute `npm run test` and note the following error

```
> jest

 FAIL  ./App.test.js
  ● Test suite failed to run

    ReferenceError: FormData is not defined

      at Object.<anonymous> (node_modules/react-native-aws3-cognito/lib/Request.js:148:20)
      at Object.<anonymous> (node_modules/react-native-aws3-cognito/lib/RNS3.js:16:16)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.619s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Updating `transformIgnorePatterns` to include `react-native-aws3-cognito` didn't seem to help. See following

```  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|@sentry/.*|sentry-expo|native-base|react-native-aws3-cognito/.*)"
    ]
  },```

**Comment by cruzach** [comment]
Looks like this is a bug with the original library, not with Expo. See [this issue](https://github.com/benjreinhart/react-native-aws3/issues/77). Unfortunately, it doesn't look like that library is maintained any more 🙁
