### ISSUE TITLE
App pending install of new JS bundle crashes if opened while offline

### ISSUE THREAD

**Issue by theneva** [expo/expo#7194]
### Environment

The app was built using `yarn expo publish` in this environment:

```
Expo CLI 3.13.1 environment info:
  System:
    OS: macOS 10.14.6
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /var/folders/gj/0mygpdfn6598xh34njlyrqzc0000gn/T/yarn--1582721700309-0.5850597968929274/node
    Yarn: 1.22.0 - /var/folders/gj/0mygpdfn6598xh34njlyrqzc0000gn/T/yarn--1582721700309-0.5850597968929274/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    expo: ^36.0.1 => 36.0.2 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
  npmGlobalPackages:
    expo-cli: 2.21.2 
```

The app is shipped to & installed via Play Store, running on a Google Pixel 3a (build number QQ1A.200205.0002) running Android version 10 with security patches from 2020-02-05.

### Steps to Reproduce

After a new (JS) update is shipped:

1. Open the app (which detects the new bundle on startup)
2. Close/stop the app (swipe it away from Recents, for example)
3. Disconnect from the internet (I turned on flight mode)
4. Open the app

### Expected Behavior

The app should detect that it is offline and show the "you're offline" screen we've implemented to present this to the user. This normally works – it only fails when the app knows that there is a new bundle.

### Actual Behavior

The app crashes immediately with an error from the Java layer:

```
2020-02-26 12:44:21.592 25771-25771/? E/no.folio.app: Not starting debugger since process cannot load the jdwp agent.
2020-02-26 12:44:21.822 25771-25801/? E/Fabric: Settings request failed.
2020-02-26 12:44:22.031 25771-25771/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: no.folio.app, PID: 25771
    java.lang.RuntimeException: Expo encountered a fatal error: Could not load request from https://expo.io:443/@folio/folio-native-app: the request timed out
        at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
        at android.app.Activity.runOnUiThread(Activity.java:6923)
        at host.exp.exponent.experience.a.k(BaseExperienceActivity.java:2)
        at host.exp.exponent.experience.a.b(BaseExperienceActivity.java:3)
        at host.exp.exponent.p.j.a(Kernel.java:141)
        at host.exp.exponent.p.j.b(Kernel.java:6)
        at host.exp.exponent.experience.ExperienceActivity$b.b(ExperienceActivity.java:2)
        at host.exp.exponent.c.b(AppLoader.java:26)
        at host.exp.exponent.c.d(AppLoader.java:2)
        at host.exp.exponent.c.a(AppLoader.java:1)
        at host.exp.exponent.c$a.run(AppLoader.java:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

This might be related to https://github.com/expo/expo/issues/5609, but the environments are different enough that I decided to create a new issue.

### Reproducible Demo

I believe this happens with any app. It crashes in the Java layer during startup as a result of shipping an update, so it's kind of hard to set up a minimal repro. Please see "Steps to Reproduce".

**Comment by cruzach** [comment]
What do you have set as the `updates` config in your app.json?

**Comment by theneva** [comment]
This is the whole block:

```json
"updates": { "fallbackToCacheTimeout": 0 },
```

Again, the app works fine while offline when there's no update available. :smile:

Am I missing anything obvious?

**Comment by cruzach** [comment]
No it doesn't look like it, but I just tried reproducing this with a blank project and the same `updates` settings, following your steps, and didn't see any crash 🤔

**Comment by theneva** [comment]
Weird... I can reproduce it consistently with our app. I'll try to put a repro project together when I get the chance

**Comment by cruzach** [comment]
Closing for inactivity, will reopen if we can get a reproducible demo 👍
