### ISSUE TITLE
Using .jsx extension breaks Jest

### ISSUE THREAD

**Issue by aikewoody** [expo/expo#7262]
### Environment
```
Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.1
```

### Steps to Reproduce
Setup a clean Expo project:
```
expo init --template blank;
cd expo-template-blank;
# Following the installation instructions from: https://docs.expo.io/versions/latest/guides/testing-with-jest/
npm i jest-expo --save-dev;
npm i react-test-renderer --save-dev;
```

Implement a simple test (Currency.test.jsx):
```
import React from 'react';
import renderer from 'react-test-renderer';

import Currency from './Currency';

describe('<Currency />', () => {
  it('has 1 child', () => {
    const tree = renderer.create(<Currency />).toJSON();
    expect(tree.children.length).toBe(1);
  });
});
```

With the simple component (Currency.jsx):
```
import React from 'react';
import { Text } from 'react-native';

export default function Currency({ children, ...props }) {
  return (
    <Text {...props}>
      $ {children}
    </Text>
  );
}
```

### Expected Behavior
The test should complete successfully.

### Actual Behavior
The test fails and gives the following output:
```
> @ test /Users/aike/react-native/verzekering-app
> jest

 FAIL  ./Currency.test.jsx
  ● Test suite failed to run

    /Users/aike/react-native/verzekering-app/Currency.test.jsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/node_modules/@jest/transform/build/ScriptTransformer.js:537:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.872s
Ran all test suites.
```

By changing the file extension from Currency.test from .jsx to .js the problem moves to the Currency.jsx file:
```
> @ test /Users/aike/react-native/expo-template-blank
> jest

 FAIL  ./Currency.test.js
  ● Test suite failed to run

    /Users/aike/react-native/expo-template-blank/Currency.jsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import renderer from 'react-test-renderer';
      3 | 
    > 4 | import Currency from './Currency';
        | ^
      5 | 
      6 | describe('<Currency />', () => {
      7 |   it('has 1 child', () => {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (Currency.test.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.118s
Ran all test suites.
```

By changing the file extension from Currency from .jsx to .js the problem is solved:
```
> @ test /Users/aike/react-native/expo-template-blank
> jest

 PASS  ./Currency.test.js (6.494s)
  <Currency />
    ✓ has 1 child (4898ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        6.751s
Ran all test suites.
```

**Comment by cruzach** [comment]
Have you tried searching for solutions to this error in SO and the `jest` repo? This is one issue with a few linked solutions https://github.com/facebook/jest/issues/9292

**Comment by aikewoody** [comment]
@cruzach Yes I followed all google hits by searching about this problem. An overview of the things I tried:
- Setting `transformIgnorePatterns ` in the `Jest` config
- Setting `moduleFileExtensions ` in the `Jest` config

**Comment by cruzach** [comment]
what did you set `transformIgnorePatterns` to?

**Comment by aikewoody** [comment]
@cruzach This is the Jest config:
```
  "jest": {
    "preset": "jest-expo",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|prop-types|react)"
    ]
  }
```

**Comment by EvanBacon** [comment]
`jest-expo` extends the default React Native jest preset and adds multi-platform support. Using just the React Native jest preset I couldn't get `.jsx` to work. It seems like this means they now recommend using `.js` instead of `.jsx`.

**Comment by aikewoody** [comment]
@EvanBacon Thanks for giving this insight. It gave me a clue in the right direction to solve it. The following comment in an issue in the Jest GitHub page gave the right solution: https://github.com/facebook/jest/issues/9395#issuecomment-583799300

For me it was only necessary to use babel-jest to transform the JavaScript code used in my project. For people having the same issue as me, the following steps solved my problem:

1. `yarn add --dev 'babel-jest'`
2. Add this to the Jest config:
```
"transform": {
  "^.+\\.jsx?$": "babel-jest"
},
```
