### ISSUE TITLE
Cannot import metro.config.js from a subdirectory

### ISSUE THREAD

**Issue by walidvb** [expo/expo#7295]
## 🐛 Bug Report
Please provide the following:
1. SDK version: 36
2. Platforms(Android/iOS/web/all): iOS / Android

After fighting with upgrading from 35 to 36, i have realized that `packagerOpts.config` must be a path to the same directory. Setting it to `config/metro.config.js` or `./config/metro.config.js` yields the following errors in my case: 

Moving the file to be a sibling of `app.json` fixes the issue

### Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.11.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.13.1
```

The app is targeting iOS and Android, but fails at compilation time

### Steps to Reproduce

Add the following to your app.json:

```
"packagerOpts": {
      "config": "config/metro.config.js",
    },
```
### Expected Behavior

It finds the file, or tells me it cannot find the file

### Actual Behavior

It fails to compile, with errors that are of no help – `AppEntry.js` does exist at that location:
```
 Expo  Press ? to show a list of all available commands.
Error: ENOENT: no such file or directory, scandir '/Users/gaston/dev/reveel/app/config/assets/images'

Error: Unable to resolve module `./node_modules/expo/AppEntry` from ``: 

None of these files exist:
  * node_modules/expo/AppEntry(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json)
  * node_modules/expo/AppEntry/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/Users/gaston/dev/reveel/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/gaston/dev/reveel/app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/gaston/dev/reveel/app/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /Users/gaston/dev/reveel/app/node_modules/metro/src/lib/transformHelpers.js:267:42
    at Server.<anonymous> (/Users/gaston/dev/reveel/app/node_modules/metro/src/Server.js:1088:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/gaston/dev/reveel/app/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/gaston/dev/reveel/app/node_modules/metro/src/Server.js:119:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
### Reproducible Demo

https://github.com/walidvb/expo-metro-bug-example

Thanks to @schellack(maybe the wrong one?) for helping me debug this 🙌

**Comment by brentvatne** [comment]
you might need to change the `main` in package.json to point to `../node_modules` rather than `./` or change the `projectRoot` in metro: https://facebook.github.io/metro/docs/en/configuration#projectroot

not an expo issue though, this is about metro so i will close
