### ISSUE TITLE
Expo jest - Unexpected Identifier require for non-standard assets

### ISSUE THREAD

**Issue by jmbeach** [expo/expo#7436]
### Environment

```
  Expo CLI 3.15.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
```

iOS, and Android (using TypeScript)

### Steps to Reproduce

* Create a new expo project using `expo init`
* Choose "minimal (TypeScript)"
* Give it a name
* Add a sqlite db called 'database.db' in the root folder
* Add line `const test = require('./database.db');` to App.tsx
* Run `yarn test`

### Expected Behavior

Test runs without error

### Actual Behavior

``` FAIL  __tests__/App.js
  ● Test suite failed to run

    C:\Users\jared\Code\sandbox\expo-test-require\exporequire\database.db:1      
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){SQLite format 3

                   ^^^^^^

    SyntaxError: Unexpected identifier

      1 | import React from 'react';
      2 | import { StyleSheet, Text, View } from 'react-native';
    > 3 | const test = require('./database.db');
        |              ^
      4 | 
      5 | export default function App() {
      6 |   return (

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (App.tsx:3:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.646s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

### Reproducible Demo

Clone this and run `yarn test`

https://github.com/jmbeach/expo-test-test-require-example

### Additional Notes

This problem does not occur if you require a `json` file. Only asset files. I have not tested images. Just a sqlite file. Initially I was very confused because I thought the issue was the `require` keyword itself, but after some debugging I get now that the problem is that it's trying to read the sqlite file as javascript. This is unlikely an expo problem, but I would appreciate help solving it since I'm using valid require syntax [similar to the docs](https://docs.expo.io/versions/latest/guides/assets/) and others will likely run into the issue too.

**Comment by jmbeach** [comment]
Actually, I figured out the fix. You just need to mock the dependency.

Example solution:

Create a file `jest/setup.js` with contents:

```js
jest.mock('../assets/database.db', () => {
  return 3
});
```

Then in package.json add this to jest config:

```json
    "setupFiles": [
      "./jest/setup.js"
    ]
```
