### ISSUE TITLE
Expo SDK 37 android build fails with 'xxxhdpi/shell_launch_background_image.png' timed out, attempting to stop daemon.'

### ISSUE THREAD

**Issue by asakalou-exadel** [expo/expo#7762]
## 🐛 Bug Report
After upgrade to expo SDK 37 our android build started to fail on Expo servers with error listed below.
iOS builds are working fine.

### Environment
Android build
```
Expo CLI 3.17.18 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.4 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 

```
### Steps to Reproduce

We've been using the same assets while building apps before update to sdk37.
Current android builds are failing with error provided above.

### Expected Behavior

Android build succeeds.

### Actual Behavior

Android build fails on expo servers with the same assets as we use before upgrade to SDK37.
**Links to builds:** 
https://expo.io/dashboard/yatskevich/builds/9b989851-259e-4ad1-9d17-f502d7180612
https://expo.io/dashboard/yatskevich/builds/9388ff11-ff19-4d26-8f85-13f92db626c8

**Console output:**
```
> Task :unimodules-react-native-adapter:assembleRelease
[stderr] AAPT2 aapt2-3.5.3-5435860-linux Daemon #0: Unexpected error output: Done
> Task :app:mergeReleaseResources FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeReleaseResources'.
[stderr] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]    > AAPT2 aapt2-3.5.3-5435860-linux Daemon #0: Compile '/app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/drawable-xxxhdpi/shell_launch_background_image.png' timed out, attempting to stop daemon.
[stderr]      This should not happen under normal circumstances, please file an issue if it does.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 4m 9s
1916 actionable tasks: 1916 executed
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
```

**Comment by sjchmiela** [comment]
That's a strange problem 🤔 — the `shell_launch_background_image` is created from `android.splash` from `app.json` — could you please ensure that it is a valid PNG file? If it looks like it is, could you please try resaving it in some graphics editor and rebuilding the app?

**Comment by asakalou** [comment]
We've made one more build
https://expo.io/dashboard/yatskevich/builds/ed3bdee3-e036-46c8-8994-b06310f6ed1e

And it's failed. We didn't make any changes to file.
`file splash.png` returns:
```
/expo/splash.png: PNG image data, 1500 x 2668, 8-bit/color RGBA, non-interlaced
```

Are there any ways to determine the problem?

Thanks!

**Comment by sjchmiela** [comment]
Maybe you could try making the image smaller? Compressing it a little bit more? Resizing it to a smaller picture? Swapping the nice-looking background for a solid oclor?

It looks like AAPT2 runs some PNG optimization behind the scenes (see [`--no-crunch` among AAPT2 compile options](https://developer.android.com/studio/command-line/aapt2#compile-syntax)), maybe this particular image is somehow too complex? I have never encountered such situation before, but running [ImageOptim](https://imageoptim.com/) (with all the PNG optimizations enabled) makes the image 25% smaller (not losing quality!) and it takes a long while.

![2494e34614bb0c7c136586bf48d9a473](https://user-images.githubusercontent.com/1151041/78909699-34e64780-7a84-11ea-95f9-1ccf7e234ccb.png)

**Comment by asakalou** [comment]
Hello Team,

We've used png of smaller size with less effects inside and it id work. Thanks.

But it's really strange that starting from expo sdk 37 (may be anything has changed in the build process) we noticed this problem for the same assets. These assets were used in our builds before and there were no errors.

**Comment by LuHugo** [comment]
I'm having the same problem. My app splash image with 1242 pixels wide and 2436 pixels tall. expo sdk version is 37.
``` bash
> Task :app:mergeReleaseResources FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeReleaseResources'.
[stderr] > Multiple task action failures occurred:
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]       > Android resource compilation failed
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]             
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: file failed to compile.
[stderr]             
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]       > Android resource compilation failed
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-mdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]             
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-mdpi/ic_launcher.png: AAPT: error: file failed to compile.
[stderr]             
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]       > Android resource compilation failed
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]             
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: AAPT: error: file failed to compile.
[stderr]             
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]       > Android resource compilation failed
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]             
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: file failed to compile.
[stderr]             
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]       > Android resource compilation failed
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/drawable-xxxhdpi/shell_launch_background_image.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]             
[stderr]         /app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/res/drawable-xxxhdpi/shell_launch_background_image.png: AAPT: error: file failed to compile.
[stderr]             
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 52s
14 actionable tasks: 14 executed
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:190:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:912:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:406:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:83:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:31:28)
    at async build (/app/turtle/build/jobManager.js:158:24)
    at async processJob (/app/turtle/build/jobManager.js:103:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:35:5)
    at async main (/app/turtle/build/server.js:44:13)

```
