### ISSUE TITLE
EXPO SDK 27. Developer menu Android Device do not open.

### ISSUE THREAD

**Issue by diegolaciar** [expo/expo#7772]
### Environment

  Expo CLI 3.17.20 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      npm: 6.14.2 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^3.13.0 => 3.13.0

target: Android device

### Steps to Reproduce

expo start
launch on a USB conected andorid device

### Expected Behavior

shake and open de developer menu to allow remote JS debug.

### Actual Behavior

shake don' t do nothing.
 I cant open developer menu
alternative as run 
  adb shell input keyevent 82
do not work.

I updated to expo 37 , I cant open the Developer menu.

Shaking  don't work (maybe the phone issue ?),  Running `adb shell input keyevent 82` doesn't work either .

I there an alternative ?   Right now  can' t debug.

https://docs.expo.io/versions/latest/workflow/debugging/#developer-menu

**Comment by brentvatne** [comment]
@diegolaciar - can you try closing the client, then opening it manually (without pressing `a` in expo-cli) and reopening the app that way?

**Comment by diegolaciar** [comment]
Hi @brentvatne ,

Thanks for your fast response.
I did the update.
then I got this errror
using bash  or zsh is the same.
```
$ expo start
Starting project at /Users/[...........]/app_dir
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)```

this error happens on my machine every time I kill expo. 

I will restart and try again. Maybe is fixed, I will let you know.

**Comment by brentvatne** [comment]
https://github.com/voidcosmos/npkill/issues/25#issuecomment-522968839

maybe there is a low limit on the number of processes on your machine or the process isn't being properly killed

**Comment by diegolaciar** [comment]
@brentvatne ,

I did restarted my Mac. started the project and now the Developer menu and debugger works!

but when I do CTRL-CMD to kill ,  this happens.

```
Opening on Android device
Finished building JavaScript bundle in 70207ms.
Running application on XT1032.

Stopping packager...
› Closing Expo server
› Stopping Metro bundler
Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! the-app@0.0.0 start: `npm install && expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the the-app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/diegolaciar/.npm/_logs/2020-04-09T19_14_50_407Z-debug.log 
```
So I updated the values,  
```
   launchctl limit maxfiles
	maxfiles    65536          200000
```

Sadly expo do not want start     !

```
   npx expo start
Starting project at /Users/diegolaciar/workspace/providerCustomer/the-app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by diegolaciar** [comment]
Update:

If I remove this folder, project starts ok.

```
 rm -rf .expo/
```

**Comment by brentvatne** [comment]
hmm i am not sure how to reproduce this.. when i exit i see this:

```
Stopping packager...
› Closing Expo server
› Stopping Metro bundler
Packager stopped.
```

**Comment by brentvatne** [comment]
oh - also - what if you don't use npx? just use global install instead. not sure if that will make a difference but curious

**Comment by diegolaciar** [comment]
@brentvatne I suppose you work for expo ?

Do you need any log ? Or if is need I can share my screen or any related file.

**Comment by diegolaciar** [comment]
ok  I will try installing globally.

**Comment by diegolaciar** [comment]
@brentvatne ,
I did run with expo installed globally and issue is the same. 

Each time kill expo closes bad.
For start again, I have to delete the folder .expo/

```
Stopping packager...
› Closing Expo server
› Stopping Metro bundler
Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by brentvatne** [comment]
@diegolaciar - create an issue on the expo-cli repo please :)

**Comment by diegolaciar** [comment]
new issue on expo-cli repo: https://github.com/expo/expo-cli/issues/1852
