### ISSUE TITLE
Android standalone: `Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference`

### ISSUE THREAD

**Issue by secantoni** [expo/expo#787]
To reproduce it:

Just create a blank project, set minimum info to build a standalone app for android (package and no special permissions), and build it. When you open the app the first time, it works well, but when you tap the app icon once it is open, it crashes. If you use the recent apps menu of Android to go back to the app, it works.

The model of the Android is a Vivo Xplay5, in case it helps.

Here you go the error it gives:

```
10-16 08:06:39.187 14675-14675/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: dev.secantoni.exporaw, PID: 14675
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
                                                       at host.exp.exponent.experience.ExperienceActivity.onNewIntent(ExperienceActivity.java:228)
                                                       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1220)
                                                       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1232)
                                                       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2535)
                                                       at android.app.ActivityThread.performNewIntents(ActivityThread.java:2547)
                                                       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2556)
                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:175)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

And the app.json

```
{
  "expo": {
    "name": "expo-raw",
    "description": "An empty new project",
    "slug": "expo-raw",
    "privacy": "public",
    "sdkVersion": "21.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app-icon.png",
    "loading": {
      "icon": "./assets/icons/loading-icon.png"
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "android" : {
      "package": "dev.secantoni.exporaw",
      "permissions": []
    },
    "ios": {
      "supportsTablet": true
    }
  }
}
```

**Comment by xcarpentier** [comment]
Any news on that?

**Comment by terribleben** [comment]
Hi there, can anybody who has seen this issue let us know if you're still experiencing it?

Also, for people who saw this, do you remember if you ran `exp publish` prior to building? If you weren't, what happens if you do that first?

**Comment by sjchmiela** [comment]
I'll let myself close this issue, as it has been inactive for quite a long time and we've deprecated SDK21 since. I believe this issue won't happen on supported SDK versions anymore. 🙂
