### ISSUE TITLE
Bare Expo Bundle Assets - 403

### ISSUE THREAD

**Issue by mdcuk34** [expo/expo#7986]
### Environment

 Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.18.6

IOS 
Bare Workflow

### Steps to Reproduce

Using the [ejected-example-fonts](https://github.com/brentvatne/ejected-example-fonts) repo as a base line:
1. Alter the code to require the` icon.png`
2. Run `expo export --public-url https://YOUR_NGROK.ngrok.io`
3. `serve` up the build folder
4. Edit the `Build Configuration` to `Release` on `Run` on Xcode
5. Press `play` and watch your app build happily
6. Now add your own image to the assets folder and switch to require that in your image
7. Re-run `expo export`
8. Press `play` and watch it error with a 403

### Expected Behavior

IOS builds with local assets successfully.
Please note if you run an `expo publish` before the `expo export` it works fine.

### Actual Behavior
```
~/PROJECT/apps/native ~/PROJECT/apps/native/ios
3.18.6
[10:40:12] Request failed with status code 403
[10:40:12] Error: Request failed with status code 403
    at createError (/Users/mitch/.nvm/versions/node/v12.6.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/mitch/.nvm/versions/node/v12.6.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/Users/mitch/.nvm/versions/node/v12.6.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:211:9)
    at RedirectableRequest.emit (events.js:315:20)
    at RedirectableRequest._processResponse (/Users/mitch/.nvm/versions/node/v12.6.0/lib/node_modules/expo-cli/node_modules/axios/node_modules/follow-redirects/index.js:269:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/mitch/.nvm/versions/node/v12.6.0/lib/node_modules/expo-cli/node_modules/axios/node_modules/follow-redirects/index.js:50:10)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
Command PhaseScriptExecution failed with a nonzero exit code
```

### Reproducible Demo
Please see above

**Comment by mdcuk34** [comment]
Also mentioned here: https://forums.expo.io/t/ios-bundle-assets-error-when-building-release-403/36616

**Comment by samithaf** [comment]
Issue exists in Android release build too. Also updated the Expo forum page with bit more information.

**Comment by mdcuk34** [comment]
closed by https://github.com/expo/expo/issues/7986
