### ISSUE TITLE
Depreciated Lottie version causing Android apps to crash

### ISSUE THREAD

**Issue by pcooney10** [expo/expo#803]
Hey folks, I am able to get Lottie working in iOS but it's causing Android apps to crash.

I did a little research, and it seems the latest version of [airbnb/lottie-react-native](https://github.com/airbnb/lottie-react-native) (**2.2.7**) addresses these issues.

In the Play Store, my logs look like this:

    FATAL EXCEPTION: AsyncTask #1
    Process: com.myCompany.myApp, PID: 12345
    java.lang.RuntimeException: An error occured while executing doInBackground()
      at android.os.AsyncTask$3.done(AsyncTask.java:300)
      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
    Caused by: java.lang.UnsupportedOperationException: JSONReadableMap does not implement this method
      at abi21_0_0.host.exp.exponent.modules.api.components.lottie.JSONReadableMap.put(JSONReadableMap.java:70)
      at com.airbnb.lottie.ap$a.a(GradientFill.java:91)
      at com.airbnb.lottie.ck.a(ShapeGroup.java:27)
      at com.airbnb.lottie.ck$a.b(ShapeGroup.java:68)
      at com.airbnb.lottie.ck$a.a(ShapeGroup.java:58)
      at com.airbnb.lottie.ck.a(ShapeGroup.java:19)
      at com.airbnb.lottie.be$a.a(Layer.java:275)
      at com.airbnb.lottie.bf$a.a(LottieComposition.java:283)
      at com.airbnb.lottie.bf$a.a(LottieComposition.java:267)
      at com.airbnb.lottie.az.a(JsonCompositionLoader.java:17)
      at com.airbnb.lottie.az.doInBackground(JsonCompositionLoader.java:7)
      at android.os.AsyncTask$2.call(AsyncTask.java:288)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)

Here are the threads where users were experiencing similar issues:

  - [#118](https://github.com/airbnb/lottie-react-native/issues/118)
  - [#78](https://github.com/airbnb/lottie-react-native/issues/78)

And this commit seems to fix the error I was getting with JSONReadableMap: [link](https://github.com/airbnb/lottie-react-native/commit/9868a704d76869c1d96348d589ddc2d62168f768)

**Comment by brentvatne** [comment]
thanks for pointing this out, I just bumped the lottie version to the latest and it will be included in SDK22 which we plan to release shortly

https://github.com/expo/expo/commit/00807bc8a1ab6fd961cfc03c884be8bae194bfba
