### ISSUE TITLE
[expo-notifications][bare] Android push handling crashes due to SoundResolver

### ISSUE THREAD

**Issue by awinograd** [expo/expo#8142]
## 🐛 Bug Report

@sjchmiela I'm seeing this crash in my bare app when upgrading expo-notifications from 1.2 -> 1.4. I think the issue was introduced when you added support for custom sound on android. Now, I can't get the push to work if I dont have a custom sound configured (i.e. I just want the default sound)

### Environment

```

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nodenv/versions/12.14.0/bin/node
      Yarn: 1.12.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nodenv/versions/12.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.11.17 => 0.11.17 
      expo: ^37.0.0 => 37.0.3 
      react: ~16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ^0.11.7 => 0.11.7 
```

Bare expo

### Steps to Reproduce

Send a push notification to android via expo push tool with expo-notifications@1.4.0.

```js
fetch("https://exp.host/--/api/v2/push/send", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9,es-US;q=0.8,es;q=0.7",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "https://expo.io/",
  "referrerPolicy": "origin",
  "body": "[{\"to\":\"ExponentPushToken[...]\",\"title\":\"test\",\"body\":\"this\",\"sound\":\"default\",\"data\":{},\"channelId\":\"bedtime-checklist\"}]",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```

### Expected Behavior

Push is displayed in notification tray

### Actual Behavior

```
05-04 14:11:55.223 29457 29526 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at java.lang.String.substring(String.java:2064)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at expo.modules.notifications.notifications.SoundResolver.resolve(SoundResolver.java:35)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at expo.modules.notifications.notifications.JSONNotificationContentBuilder.getSound(JSONNotificationContentBuilder.java:109)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at expo.modules.notifications.notifications.JSONNotificationContentBuilder.shouldPlayDefaultSound(JSONNotificationContentBuilder.java:96)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at expo.modules.notifications.notifications.JSONNotificationContentBuilder.setPayload(JSONNotificationContentBuilder.java:41)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at expo.modules.notifications.FirebaseListenerService.createNotification(FirebaseListenerService.java:94)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at expo.modules.notifications.FirebaseListenerService.onMessageReceived(FirebaseListenerService.java:85)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.0:78)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.0:2)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
05-04 14:11:55.223 29457 29526 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

### Reproducible Demo

Can work on a minimal repro if the issue isn't apparent.

**Comment by awinograd** [comment]
If I modify the native code to always useDefaultSound() then I get the following stacktrace when receiving the notification while the app is running:

```
05-04 16:30:56.215 11331 11360 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()                                                     
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:399)                                                                          
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)                                                    
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)                                                        
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)                                                                 
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)                                          
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)                                          
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)                                                                                    
05-04 16:30:56.215 11331 11360 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Could not put a value of class org.json.JSONObject$1 to bundle.                
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at org.unimodules.core.arguments.MapArguments.toBundle(MapArguments.java:160)                                               
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.NotificationSerializer.toBundle(NotificationSerializer.java:107)                
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.NotificationSerializer.toBundle(NotificationSerializer.java:60)                 
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.NotificationSerializer.toBundle(NotificationSerializer.java:47)                 
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.NotificationSerializer.toBundle(NotificationSerializer.java:39)                 
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.handling.SingleNotificationHandlerTask.start(SingleNotificationHandlerTask.java$
76)                                                                                                                                                                                 
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.handling.NotificationsHandler.onNotificationReceived(NotificationsHandler.java:$
16)                                                                                                                                                                                 
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.NotificationManager.onNotificationReceived(NotificationManager.java:83)         
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.service.ExpoNotificationsService.onNotificationReceived(ExpoNotificationsServic$
.java:106)                                                                                                                                                                          
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at expo.modules.notifications.notifications.service.BaseNotificationsService.onHandleWork(BaseNotificationsService.java:193$
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)                            
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)                            
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:378)                                                                          
05-04 16:30:56.215 11331 11360 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by byCedric** [comment]
Hi @awinograd! Thanks again for the detailed issue report! We will get on this. 😄

**Comment by bayoremit** [comment]
Hi @awinograd Sorry for the random question. I am also having issues w/ expo notifications but not a sound issue. I have an issue opened but no traction on it yet. Since you are ahead of me on getting push to work on a bare app, I would love to know how you are building your release binaries. Are you using turtle-cli or something else?

Thanks!!

**Comment by awinograd** [comment]
@bayoremit unfortunately I'm not that far ahead! I just started the migration to "bare" today and haven't done a release yet. My guess is i'll be building locally on my laptop using normal react-native commands

**Comment by joaocosta9** [comment]
@awinograd I have currently version 1.3 of expo-notifications. You were facing no problems in version 1.2, am I correct?

**Comment by awinograd** [comment]
@joaocosta9 I didn't test as many cases in 1.2 because it doesn't support custom notification icons and I wanted that functionality. I was definitely able to receive background notifications without issue

**Comment by joaocosta9** [comment]
@awinograd thanks! I will give it try until this issue is resolved

**Comment by sjchmiela** [comment]
`expo-notifications@0.1.5` should fix both this issue (crash due to `SoundResolver`) and the one described in https://github.com/expo/expo/issues/8142#issuecomment-623718799. Let me know if it works as it should and sorry for the trouble!

**Comment by awinograd** [comment]
@sjchmiela thanks for the fix! I'm trying to upgrade to test it out but running into some compilation issues due to some library upgrades (maybe related to https://github.com/expo/expo/commit/132117e5cfd1f259f776b8fa5bd93e723aa58183). If you have any leads on how to resolve that would be appreciated! Otherwise, I'm trying what I can on my end

```
e: /Users/awinograd/programming/oui-aviva/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (6, 33
): Unresolved reference: HeadlessAppLoader                                                
e: /Users/awinograd/programming/oui-aviva/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (12, 8
3): Unresolved reference: HeadlessAppLoader                                               
e: /Users/awinograd/programming/oui-aviva/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (16, 3
): 'loadApp' overrides nothing               
e: /Users/awinograd/programming/oui-aviva/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (16, 5
0): Unresolved reference: HeadlessAppLoader                                               
e: /Users/awinograd/programming/oui-aviva/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (42, 3
): 'invalidateApp' overrides nothing                                                      
e: /Users/awinograd/programming/oui-aviva/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (56, 3
): 'isRunning' overrides nothing  
```

**Comment by joaocosta9** [comment]
@sjchmiela when I try to upgrade to 1.5 and when running `npm run android` I get a warning that unimodules-core is duplicated and the following error `> Task :unimodules-react-native-adapter:compileDebugKotlin FAILED
346 actionable tasks: 343 executed, 3 up-to-date
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/joaocosta9/telepathy_app/node_modules/expo-application/android/src/main/java/expo/modules/application/ApplicationModule.java uses or overrides a deprecated API.
`

**Comment by awinograd** [comment]
@unimodules/core -> 5.1.1
@unimodules/react-native-adapter -> 5.2.0
react-native-unimodules  -> 0.9.0

**Comment by amiceli-torstar** [comment]
@awinograd I'm seeing the same issues as you right now (your most recent ones re: adapter) for unrelated reasons. Is it because of a recent update?

**Comment by sjchmiela** [comment]
Hm… interesting. Let me think what may have gone wrong, I'll try to fix it ASAP.

**Comment by sjchmiela** [comment]
Ok, `react-native-unimodules@0.9.1` and `expo-notifications@0.1.6` should do the trick. 😅

**Comment by awinograd** [comment]
@sjchmiela seems to be working now. Thank you!
