### ISSUE TITLE
Unable to symbolicate stack trace: The stack is null

### ISSUE THREAD

**Issue by ScottPierce** [expo/expo#8143]
## Description

I'm not getting a properly output stack trace when running expo in Android.

## Expected Behavior

I get a properly desymbolicated stack trace, showing the line number from my source code. It should show somewhere in the stacktrace that the exception happens in `ReactNativeMain.kt line 15`, instead of `react-native-kotlin.js`. When I run this for web instead of Android, I it gives me the proper file and line.

<img width="1043" alt="Screen Shot 2020-05-03 at 4 57 19 PM" src="https://user-images.githubusercontent.com/871169/80925606-2aeff580-8d5f-11ea-87be-e460ab67ecd9.png">

## Observed Behavior

```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``: 

None of these files exist:
  * debugger-ui/debuggerWorker.d9da4ed7(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
  * debugger-ui/debuggerWorker.d9da4ed7/index(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (/Users/scott.pierce/Desktop/BehindTheWheel/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/scott.pierce/Desktop/BehindTheWheel/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/scott.pierce/Desktop/BehindTheWheel/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /Users/scott.pierce/Desktop/BehindTheWheel/node_modules/metro/src/lib/transformHelpers.js:267:42
    at /Users/scott.pierce/Desktop/BehindTheWheel/node_modules/metro/src/Server.js:1305:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/scott.pierce/Desktop/BehindTheWheel/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/scott.pierce/Desktop/BehindTheWheel/node_modules/metro/src/Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Running application on AOSP on IA Emulator.
Unable to symbolicate stack trace: The stack is null
```

The given stacktrace is showing the compiled code and doesn't use the provided source-maps. I'd like to know the error and line number for the code in my source code.
![Screenshot_1588538741](https://user-images.githubusercontent.com/871169/80925416-8de08d00-8d5d-11ea-9aa0-90276c757506.png)

## Environment

```
  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.1.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1
```

## Reproducible Demo

here is a link to a zipped project that reproduces this. It was too big to upload to github:
https://www.dropbox.com/s/kxkdsj5lry2oyoj/BehindTheWheel-Error.zip?dl=0

**Comment by ScottPierce** [comment]
@cruzach That's basically what this is. This project is fairly minimal.
