### ISSUE TITLE
keytool error: java.lang.Exception: Keystore file does not exist: /home/oleg/codes/cm/creatorapp/Creator.tmp.jks

### ISSUE THREAD

**Issue by ORESoftware** [expo/expo#8179]
I ran this:

```
$ expo fetch:android:hashes
```

and I got this:

```
Configuring credentials for oresoftware in project Creator
There is no valid Keystore defined for this app
keytool error: java.lang.Exception: Keystore file does not exist: /home/oleg/codes/cm/creatorapp/Creator.tmp.jks

keytool exited with non-zero code: 1
Error: keytool exited with non-zero code: 1
    at ChildProcess.completionListener (/home/oleg/.nvm/versions/node/v12.16.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)
    ...
    at spawnAsync (/home/oleg/.nvm/versions/node/v12.16.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at exportCertBinary (/@expo/xdl@57.9.1/src/credentials/AndroidCredentials.ts:40:12)
    at Object.logKeystoreHashes (/@expo/xdl@57.9.1/src/credentials/AndroidCredentials.ts:195:11)
    at fetchAndroidHashesAsync (/home/oleg/.nvm/versions/node/v12.16.1/lib/node_modules/expo-cli/src/commands/fetch/android.ts:52:30)
    at Command.<anonymous> (/home/oleg/.nvm/versions/node/v12.16.1/lib/node_modules/expo-cli/src/exp.ts:85:7)
```

My goal is to generate the certificate in order to get a google oauth client id.

**Comment by byCedric** [comment]
Hi @ORESoftware, thanks for the report! Could you give a bit more context about your app? like if it's managed or bare. If it's managed, it should be something for us to fix. If it's bare, it could be related to some confusion about the keystores ([as mentioned here](https://github.com/facebook/react-native/issues/25629) for example).
