### ISSUE TITLE
[Urgent] Video doesn't play on Android (expo-av@8.0.0, SDK 36)

### ISSUE THREAD

**Issue by n-sviridenko** [expo/expo#8209]
### Environment

We do this on both emulators and real devices with Ejected ExpoKit:

```
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
```

### Steps to Reproduce

0. `expo install expo-av`

1. working on expo-av (a dummy mp4 file from the Internet):

```js
import { Video } from 'expo-av';

...

<Video source={{ uri: 'http://techslides.com/demos/sample-videos/small.mp4' }} /> 
```

Video file details: https://www.metadata2go.com/result/a353b505-fe9e-4309-b9ef-c12ce6b22268

2. not working on expo-av (video from Vimeo):

It redirects you to https://vod-progressive.akamaized.net/exp=1588939420~acl=%2A%2F1783259610.mp4%2A~hmac=5012ecfbf5aac3b4a009d0fca3aafdeba4ec058f20c4a636bd9e9cc33524f600/vimeo-prod-skyfire-std-us/01/2896/16/414482682/1783259610.mp4?download=1&filename=Untitled.mp4 (link may be expired when you read this), but even when referring to this link instead, it still doesn't play. So the issue is not in redirection.

```js
import { Video } from 'expo-av';

...

<Video source={{ uri: 'https://player.vimeo.com/play/1783259610?s=414482682_1588966348_57aedfac8cb567424660848618823be5&loc=external&context=Vimeo%5CController%5CApi%5CResources%5CUser%5CVideoController.&download=1&filename=Untitled175.mp4' }} />
```

Video file details: https://www.metadata2go.com/result/d6350ef4-1f12-4084-9116-8ec12427bec9

### Expected Behavior

We expect both of the videos to play.

### Actual Behavior

The Vimeo video doesn't play.

### Reproducible Demo

It doesn't work on Ejected SDK v36 (Android) but works on Expo Client.

**Comment by n-sviridenko** [comment]
The Vimeo video link may be expired as well when you'll be reading this. So attaching it here: 
[Untitled (8).mp4.zip](https://github.com/expo/expo/files/4597740/Untitled.8.mp4.zip)

**Comment by n-sviridenko** [comment]
Here are the response headers of the Vimeo video which redirects to Akamai:

```
curl -X HEAD -v https://player.vimeo.com/play/1783259610\?s\=414482682_1588966348_57aedfac8cb567424660848618823be5\&loc\=external\&context\=Vimeo%5CController%5CApi%5CResources%5CUser%5CVideoController.\&download\=1\&filename\=Untitled175.mp4
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
*   Trying 151.101.192.217...
* TCP_NODELAY set
* Connected to player.vimeo.com (151.101.192.217) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Fastly, Inc.; CN=vimeo.map.fastly.net
*  start date: Apr 23 20:08:56 2020 GMT
*  expire date: Apr 24 20:08:56 2021 GMT
*  subjectAltName: host "player.vimeo.com" matched cert's "*.vimeo.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
*  SSL certificate verify ok.
> HEAD /play/1783259610?s=414482682_1588966348_57aedfac8cb567424660848618823be5&loc=external&context=Vimeo%5CController%5CApi%5CResources%5CUser%5CVideoController.&download=1&filename=Untitled175.mp4 HTTP/1.1
> Host: player.vimeo.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
< Content-Length: 0
< Server: nginx
< Content-Type: text/html; charset=UTF-8
< X-Xss-Protection: 1; mode=block
< Content-Security-Policy: default-src 'self'; script-src 'self' https://f.vimeocdn.com; style-src 'self' https://f.vimeocdn.com; img-src 'self' https://i.vimeocdn.com https://f.vimeocdn.com; report-uri /_csp
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Access-Control-Allow-Origin: *
< Location: https://vod-progressive.akamaized.net/exp=1588939420~acl=%2A%2F1783259610.mp4%2A~hmac=5012ecfbf5aac3b4a009d0fca3aafdeba4ec058f20c4a636bd9e9cc33524f600/vimeo-prod-skyfire-std-us/01/2896/16/414482682/1783259610.mp4?download=1&filename=Untitled.mp4
< Cache-Control: private, max-age=14400
< P3p: CP="This is not a P3P policy! See https://vimeo.com/privacy"
< Expires: Fri, 08 May 2020 12:03:40 GMT
< Accept-Ranges: bytes
< Age: 0
< Via: 1.1 varnish
< X-Varnish-Cache: 0
< X-VServer: infra-playproxy-a-20
< X-Vimeo-DC: ge
< Accept-Ranges: bytes
< Date: Fri, 08 May 2020 08:03:40 GMT
< Via: 1.1 varnish
< Age: 0
< X-Served-By: cache-fra19166-FRA
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1588925021.587904,VS0,VE105
< Vary: Accept-Encoding
<
* Connection #0 to host player.vimeo.com left intact
* Closing connection 0
```

**Comment by n-sviridenko** [comment]
The issue is caused by integration with `tipsi/tipsi-stripe#2edbd84f1e4caf51649c694e91a1cd90740c7364`. That's really weird.

The error is following:

```log

E/ExperienceActivityUtils: java.lang.StringIndexOutOfBoundsException: length=0; index=0
D/Event: No subscribers registered for event class host.exp.exponent.experience.ReactNativeActivity$ExperienceDoneLoadingEvent
    No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
E/LoadTask: Unexpected exception loading stream
    java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:274)
        at java.util.jar.JarVerifier.update(JarVerifier.java:229)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:393)
        at java.util.jar.JarFile.getInputStream(JarFile.java:460)
        at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
        at java.net.URL.openStream(URL.java:1072)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:989)
        at java.lang.Class.getResourceAsStream(Class.java:2215)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheList(PublicSuffixDatabase.java:313)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheListUninterruptibly(PublicSuffixDatabase.java:292)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.java:112)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.java:85)
        at okhttp3.Cookie.parse(Cookie.java:311)
        at okhttp3.Cookie.parse(Cookie.java:219)
        at okhttp3.Cookie.parseAll(Cookie.java:445)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:315)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:160)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
I/ExoPlayerImpl: Release feb564f [ExoPlayerLib/2.9.2] [generic_x86, Android SDK built for x86, Google, 29] [goog.exo.core, goog.exo.okhttp]
V/FA: Inactivity, disconnecting from the service
```

Caused by:

```grandle
implementation project(':tipsi-stripe')
```

**Comment by mczernek** [comment]
Hello @n-sviridenko!

I am a little confused. The second video you provided does not work in bare workflow, while working perfectly in Expo Client, is that correct?

**Comment by mczernek** [comment]
If I understand correctly, this issue is related to `tipsi-stripe`. Since I haven't heard from you for a while, and there is great possibility that this issue is not related to expo-av, let me close it for now.

Whenever I hear back from you with some more details or suspicions that this is indeed expo-av issue, I will reopen it eagerly!
