### ISSUE TITLE
Expo Error

### ISSUE THREAD

**Issue by SunsetShimmer-ops** [expo/expo#8262]
ERROR
16:32
internal/fs/watchers.js:177
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/icaprita/Desktop/Ioana/node_modules/create-react-class/node_modules/core-js/library'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1339:11)
    at NodeWatcher.watchdir (/home/icaprita/Desktop/Ioana/node_modules/sane/src/node_watcher.js:159:22)
    at Walker.<anonymous> (/home/icaprita/Desktop/Ioana/node_modules/sane/src/common.js:109:31)
    at Walker.emit (events.js:310:20)
    at /home/icaprita/Desktop/Ioana/node_modules/walker/lib/walker.js:69:16
    at FSReqCallback.oncomplete (fs.js:155:23) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/icaprita/Desktop/Ioana/node_modules/create-react-class/node_modules/core-js/library',
  filename: '/home/icaprita/Desktop/Ioana/node_modules/create-react-class/node_modules/core-js/library'
}

This is the error Expo is giving me in the console.

**Comment by zanona** [comment]
Hi, @SunsetShimmer-ops. Did you manage to sort this out?
I'm also getting this issue, unfortunately.
