### ISSUE TITLE
[jest-expo] incompatibility with jest 26

### ISSUE THREAD

**Issue by tonnenpinguin** [expo/expo#8344]
### Environment

```
  Expo CLI 3.17.11 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.0 - ~/.npm-global/bin/npm
    npmPackages:
      expo: ^37.0.11 => 37.0.11 
    npmGlobalPackages:
      expo-cli: 3.17.11
```

This is an issue with jest-expo 37.0.0

### Steps to Reproduce
Upgrade jest to 26.

Jest-expo still uses the long deprecated [and now removed](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2600) `require.requireActual` which has been moved to `jest.requireActual`. The following changeset fixes the error for me:

```diff
--- a/src/preset/setup.js
+++ b/src/preset/setup.js
@@ -156,2 +156,2 @@ export const includesLowercase = (searchTerm: string) =>
  jest.mock('@unimodules/react-native-adapter', () => {
-   const ReactNativeAdapter = require.requireActual('@unimodules/react-native-adapter');
+   const ReactNativeAdapter = jest.requireActual('@unimodules/react-native-adapter');
    const { NativeModulesProxy } = ReactNativeAdapter;
 
 ```

### Expected Behavior
Tests are running with jest 26

### Actual Behavior
The tests fail to compile and start throwing the following error:

```
  ● Test suite failed to run

    TypeError: require.requireActual is not a function

      at ../../node_modules/jest-expo/src/preset/setup.js:157:40
      at Object.<anonymous> (../../node_modules/@unimodules/core/src/AdapterProxy.ts:1:1)
      at Object.<anonymous> (../../node_modules/@unimodules/core/src/index.ts:1:1)
```

**Comment by byCedric** [comment]
Hi @tonnenpinguin! Thanks for the issue report, I've created a PR that takes care of the deprecated and removed methods. Should be resolved fairly soon.
