### ISSUE TITLE
ESOCKETTIMEDOUT on expo react-native SDK (expo init or yarn install)

### ISSUE THREAD

**Issue by ndantonio** [expo/expo#8562]
Hi, I am encountering this error while doing **expo init <project>**. I've also tried **yarn install** but to no avail. I'm on Fedora 30 with good internet connection. Please help.

![image](https://user-images.githubusercontent.com/20949522/83248369-8a62e900-a1d7-11ea-85f3-23a4a3417bcc.png)

**UPDATED:** This is what I am encountering right now:

Error: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz: unexpected end of file
      at Zlib.zlibOnError [as onerror] (zlib.js:180:17)

**Comment by byCedric** [comment]
Hi @ndantonio! This seems to be an issue with either Yarn, GitHub or your network. There are a couple of things that you can try to remedy this. The first one I would try is removing `yarn.lock` and `node_modules` manually, and retrying `yarn install`. If that didn't help, [you can try one of these methods](https://github.com/yarnpkg/yarn/issues/5259) (like clearing Yarn's cache and/or disable any proxy you might have).

Hope it helps!

**Comment by Olaide-EO** [comment]
I have the same issue.

At first I was getting this error:

Trace: 
  SyntaxError: C:\Users\DELL\AppData\Local\Yarn\Cache\v6\npm-@types-lodash-4.14.155-e2b4514f46a261fd11542e47519c20ebce7bc23a-integrity\node_modules\@types\lodash\.yarn-metadata.json: Unexpected token <0x00> in JSON at position 0
      at JSON.parse (<anonymous>)
      at C:\Users\DELL\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:1625:59
      at Generator.next (<anonymous>)
      at step (C:\Users\DELL\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
      at C:\Users\DELL\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:321:13


I ran: yarn cache clean
upgraded to node 12

and now I am getting this error: 

Trace: 
  Error: https://registry.yarnpkg.com/core-js/-/core-js-2.6.11.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Users\DELL\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141375:19)
      at Object.onceWrapper (events.js:421:28)
      at ClientRequest.emit (events.js:315:20)
      at TLSSocket.emitRequestTimeout (_http_client.js:709:9)
      at Object.onceWrapper (events.js:421:28)
      at TLSSocket.emit (events.js:327:22)
      at TLSSocket.Socket._onTimeout (net.js:481:8)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
