### ISSUE TITLE
expo login error

### ISSUE THREAD

**Issue by Davidzhu001** [expo/expo#8592]
### macos 
```
Uploading JavaScript bundles
socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at TLSSocket.socketOnEnd (_http_client.js:433:23)
    at TLSSocket.emit (events.js:208:15)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by byCedric** [comment]
Hi @Davidzhu001! Could you provide a bit more info about your system? The template for a bug report should contain the necessary steps to provide them. Without that, I'm not sure what's going on. You could try to remedy this by doing the following:

- Remove `node_modules` and `package-lock.json` or `yarn.lock`, and reinstall.
- Make sure you are using the latest Node LTS version (currently v12)
- Make sure you have a stable internet connection

Hope it helps!

**Comment by Davidzhu001** [comment]
it is fix after remove node_modules and rerun yarn install @byCedric thanks so mucch
