### ISSUE TITLE
> Task :app:processDebugManifest FAILED

### ISSUE THREAD

**Issue by usama-asfar** [expo/expo#8849]
I'm new to react native while I'm developing my app with Expo managed workflow I need to install `react-native-snackbar` and `react-native-fast-image` because of those are native module I created a new Expo bare workflow move my code it. 

After I start the app with `npm start` and `npm run android` it gives a huge error, I search all over the internet for a solution, unfortunately, I don't find any solution that could fix this issue.

I get this 
```
chawki@chawki:~/Documents/adex-android
$ npm run android

> @ android /home/chawki/Documents/adex-android
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1408 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Configure project :app

Installing unimodules:
 unimodules-core@5.1.2 from /home/chawki/Documents/adex-android/node_modules/@unimodules/core
 unimodules-react-native-adapter@5.2.0 from /home/chawki/Documents/adex-android/node_modules/@unimodules/react-native-adapter
 expo-app-auth@9.0.0 from /home/chawki/Documents/adex-android/node_modules/expo-app-auth
 expo-constants@9.0.0 from /home/chawki/Documents/adex-android/node_modules/expo-constants
 expo-error-recovery@1.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-error-recovery
 expo-facebook@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-facebook
 expo-file-system@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-file-system
 expo-font@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-font
 expo-image-loader@1.0.1 from /home/chawki/Documents/adex-android/node_modules/expo-image-loader
 expo-keep-awake@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-keep-awake
 expo-linear-gradient@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-linear-gradient
 expo-location@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-location
 expo-permissions@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-permissions
 expo-splash-screen@0.2.3 from /home/chawki/Documents/adex-android/node_modules/expo-splash-screen
 expo-sqlite@8.1.0 from /home/chawki/Documents/adex-android/node_modules/expo-sqlite
 expo-updates@0.2.9 from /home/chawki/Documents/adex-android/node_modules/expo-updates
 expo-web-browser@8.2.0 from /home/chawki/Documents/adex-android/node_modules/expo-web-browser
 unimodules-app-loader@1.0.2 from /home/chawki/Documents/adex-android/node_modules/unimodules-app-loader
 unimodules-barcode-scanner-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-barcode-scanner-interface
 unimodules-camera-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-camera-interface
 unimodules-constants-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-constants-interface
 unimodules-face-detector-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-face-detector-interface
 unimodules-file-system-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-file-system-interface
 unimodules-font-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-font-interface
 unimodules-image-loader-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-image-loader-interface
 unimodules-permissions-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-permissions-interface
 unimodules-sensors-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-sensors-interface
 unimodules-task-manager-interface@5.1.0 from /home/chawki/Documents/adex-android/node_modules/unimodules-task-manager-interface

> Task :app:processDebugManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

447 actionable tasks: 2 executed, 445 up-to-date
/home/chawki/Documents/adex-android/android/app/src/debug/AndroidManifest.xml Error:
        Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/home/chawki/Documents/adex-android/android/app/src/debug/AndroidManifest.xml Error:
	Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at runOnAllDevices (/home/chawki/Documents/adex-android/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/home/chawki/Documents/adex-android/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /home/chawki/Documents/adex-android/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/home/chawki/Documents/adex-android/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ android: `react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chawki/.npm/_logs/2020-06-17T08_19_59_983Z-debug.log

```

But my app works fine if I run in expo client by `expo start` and when I installed `react-native-snackbar`  I get this

`
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RnSnackbar.LENGTH_LONG')
`

Now how can I use those two native modules in my project without any issues?
AND here my problem starting expo bare project with `npm run android`

**Comment by byCedric** [comment]
HI @usama-asfar, thanks for the issue. Normally, I would not recommend creating a new bare project and move over all files you already have in your managed project. Ejecting is much better because it takes your manifest settings into account when ejecting, updating files like AndroidManifest.xml automatically. I would only recommend moving files over if you encounter issues.

I'm not 100% sure about your current issue. It doesn't seem to be related to the modules you mentioned, or any Expo modules, but I could be wrong. Without a repro it's hard for us to determine the cause, I can install both dependencies just fine on a blank bare project. If you use the [`react-native-app-auth` package](https://github.com/FormidableLabs/react-native-app-auth), make sure to check out [their documentation as well](https://github.com/FormidableLabs/react-native-app-auth#android-setup). If you are using this library, please do know that Expo first-class support for this functionality without a lot of native code, like [AuthSession](https://docs.expo.io/versions/latest/sdk/auth-session/). If this issue wasn't solved by that, please create a new issue and provide a small repro so we can investigate the cause. 

Hope it helps!

**Comment by usama-asfar** [comment]
I was a fool, After going through too hard in debugging I found my phone storage is not enough to install the app, And I'm sorry  : )
