### ISSUE TITLE
expo app crushes in production. expo-updates is involved

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo#8872]
### Summary of Issue (just a few sentences)
After adding `expo-updates` to my bare workflow the build fails in production.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.7 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: 0.61.4 => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.18.6

### Reproducible Demo
It's hard to share my code, sorry. This is my stack-trace from production:

![image](https://user-images.githubusercontent.com/1548235/85072754-448bb600-b1c2-11ea-9817-d3ef91e7b4c1.png)

I've completed all steps from all over the places.
- run expo publish
- update `app.json`
- followed `README` instruction from `expo-updates` page

But still, the build somehow misses the valid app.manifest file.

Sorry for not being more helpful. But help me :)

### Expected Behavior vs Actual Behavior
The app crushes.

**Comment by RohovDmytro** [comment]
As far as I can tell one of the features on expo-updates v 0.2.x was about automatically creating manifesto files. But somehow it's failing.

Maybe there is a problem in this script:
````
apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle"
````

**Comment by RohovDmytro** [comment]
I'm also using android flavors if that can be the case.

**Comment by brentvatne** [comment]
create a new bare project with `expo init` and compare your config with the one in that project to see what config might be incorrect / missing :)

**Comment by RohovDmytro** [comment]
@brentvatne thank you, that is a nice idea. I've done that I see nothing that can help.

I'm juggling for a day here, I think I've added all the line all over the places.

I just deleted yarn lock & node_modules, run expo publish, made a fresh build. Same.

**Comment by brentvatne** [comment]
@RohovDmytro - if you do a release build of a new app you will see that you won't have this issue. so there is some config missing :) cc @esamelson maybe there's something we can do to help people diagnose expo-update configuration issues

**Comment by RohovDmytro** [comment]
✅  This module requires expo-cli@3.17.6 or later
✅  make sure your global installation is at least this version before proceeding.
✅  Finally, this module is not compatible with ExpoKit. Make sure you do not have expokit listed as a dependency in package.json before adding this module.
✅ 
✅

**Comment by RohovDmytro** [comment]
Tripple checking everything...

What should be `EXPO_UPDATE_URL` if I use `expo publish`?

My android manifest is this:
```
<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@mynick/appname" />
      <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="37.0.0" />

      <meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="default" />
```

**Comment by RohovDmytro** [comment]
I've trippled check. Here is quick todo:

✅ This module requires expo-cli@3.17.6 or later
✅ make sure your global installation is at least this version before proceeding.
✅ Finally, this module is not compatible with ExpoKit. Make sure you do not have expokit listed as a dependency in package.json before adding this module.
✅ expo@37.0.10
✅ expo-asset@8.1.5
✅ Delete the app.manifest and app.bundle files from your Xcode project and android/app/src/main/assets directory
✅ Add a metro.config.js file to your project with these contents
✅ n android/app/build.gradle, apply the following diff (done)
✅ expo install expo-updates
✅ expo-asset
✅metro.config.js
✅ Set up app.json
✅ app/build.gradle
✅ AndroidManifest.xml
✅ EXPO_SDK_VERSION should match the SDK version in your app.json.
✅ MainApplication.java

Still my app crashes in production. maybe @brentvatne is right and  there is some config missing :) :) :) Not sure what config.

**Comment by brentvatne** [comment]
can you update to a newer version of expo-cli and try?

**Comment by RohovDmytro** [comment]
Yeap, I've already update `explo-cli` to the latest verion.

I am following your first advice:
```
create a new bare project with expo init and compare your config with the one in that project to see what config might be incorrect / missing :)
```

I found that I can bump my grade build version from 5.1.1 to 5.4.1. Will try now if it will make a difference.

**Comment by RohovDmytro** [comment]
I also started having this while doing releases. Maybe it's part of the puzzle...

![image](https://user-images.githubusercontent.com/1548235/85082707-66903300-b1d8-11ea-8cb0-7a82263519bd.png)

**Comment by RohovDmytro** [comment]
Okay. So I've disabled `updates` for now. Now my build is 5mb smaller (!) and it actually works.

Will happy to provide any details to find the problem.

Sorry for not sharing code, I have a big set up.

**Comment by esamelson** [comment]
Hey @RohovDmytro - sorry this is causing you so much trouble! 😞 Are you able to access the debug logs for your device via `adb logcat`? If so, could you try running `adb logcat | grep "EmbeddedLoader"`, launch the app and paste the output here? That will hopefully give us some more information to work with.

**Comment by RohovDmytro** [comment]
@esamelson . Thank you for spending time trying to help. I appreciate that. I MIGHT miss some config, cause they are all over the place. But it's unbearable hard to find what is wrong. Thank for jumping in.

I don't know how to grasp logs from a production build. So I've done this thing in order to crash my app in development mode.

I've updates `MailApplication.java` file to use expo-updates in development mode.
```
@Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    UpdatesController.initialize(this);
    if (!BuildConfig.DEBUG) {
      
    }
  }
```

Now I have exact same error and behavior as in production.

Here is an output from `logcat`:
```
06-19 18:12:54.806 30512 30512 E EmbeddedLoader: java.io.FileNotFoundException: app.manifest
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.content.res.AssetManager.open(AssetManager.java:824)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.content.res.AssetManager.open(AssetManager.java:801)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at expo.modules.updates.loader.EmbeddedLoader.readEmbeddedManifest(EmbeddedLoader.java:73)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at expo.modules.updates.UpdatesController.start(UpdatesController.java:285)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at expo.modules.updates.UpdatesController.initialize(UpdatesController.java:96)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at com.trackerion.MainApplication.onCreate(MainApplication.java:77)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.os.Handler.dispatchMessage(Handler.java:107)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.os.Looper.loop(Looper.java:214)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at android.app.ActivityThread.main(ActivityThread.java:7356)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at java.lang.reflect.Method.invoke(Native Method)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-19 18:12:54.806 30512 30512 E EmbeddedLoader:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
06-19 18:12:54.807 30512 30512 E AndroidRuntime:        at expo.modules.updates.loader.EmbeddedLoader.readEmbeddedManifest(EmbeddedLoader.java:78)
```

**Comment by RohovDmytro** [comment]
This is me first time debugging Java code. Maybe this would make sense to somebody: :) 

````
![image](https://user-images.githubusercontent.com/1548235/85158493-27f48a00-b265-11ea-89c5-f43aeeaebc1e.png)

````

**Comment by RohovDmytro** [comment]
Sorry, but I will throw all the slightly relevant  information here. It might be important to solve the issue or to those who might have similar issue.

THis is my unimodules setup:

````
addUnimodulesDependencies([exclude: ['expo-location', 'expo-linear-gradient', 'unimodules-app-loader', 'unimodules-barcode-scanner-interface', 'unimodules-camera-interface', 'unimodules-sensors-interface', 'unimodules-task-manager-interface', 'expo-sqlite', 'expo-web-browser', 'unimodules-face-detector-interface']])
````

I am excluding some of the components. Maybe that is the deal.

**Comment by brentvatne** [comment]
can you share your project privately on github?

**Comment by RohovDmytro** [comment]
@brentvatne Would it be sufficient enough to provide `MainApplication.java`, `build.gradle`, `app/build.gradle` file contents? Maybe something else?

**Comment by brentvatne** [comment]
ideally the entire project otherwise it's a lot harder to help, but if that's all you can share then we could try

**Comment by RohovDmytro** [comment]
`AndroidManifest`

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.trackerion">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:screenOrientation="portrait"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:usesCleartextTraffic="true"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@***/***" />
      <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="37.0.0" />

      <meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="default" />

  <activity
    android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

**Comment by RohovDmytro** [comment]
build.gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.1.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
    	maven { url 'https://jitpack.io' }
      }
}


wrapper{
    gradleVersion = '5.1.1'
    distributionUrl = distributionUrl.replace("bin", "all")
}

```

**Comment by RohovDmytro** [comment]
app/build.gradle

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false
]

apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false
[]
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    flavorDimensions "default"
    

    defaultConfig {
        applicationId "com.trackerion"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 41
        versionName "1.0"
        multiDexEnabled true
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    productFlavors {
        trackerion {
            minSdkVersion rootProject.ext.minSdkVersion
            applicationId 'com.trackerion'
            targetSdkVersion rootProject.ext.targetSdkVersion
            resValue "string", "build_config_package", "com.myapp"
        }
        energon {
            minSdkVersion rootProject.ext.minSdkVersion
            applicationId 'com.energon'
            targetSdkVersion rootProject.ext.targetSdkVersion
            resValue "string", "build_config_package", "com.myapp"
        }
        houserion {
            minSdkVersion rootProject.ext.minSdkVersion
            applicationId 'com.houserion'
            targetSdkVersion rootProject.ext.targetSdkVersion
            resValue "string", "build_config_package", "com.myapp"
        }
        feelings {
            minSdkVersion rootProject.ext.minSdkVersion
            applicationId 'com.feelings'
            targetSdkVersion rootProject.ext.targetSdkVersion
            resValue "string", "build_config_package", "com.myapp"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }
}

def jscFlavor = 'org.webkit:android-jsc:+'

def enableHermes = project.ext.react.get("enableHermes", false);

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.firebase:firebase-analytics:17.4.3'
    implementation 'com.google.firebase:firebase-crashlytics:17.0.1'

    addUnimodulesDependencies([exclude: ['expo-location', 'expo-linear-gradient', 'unimodules-app-loader', 'unimodules-barcode-scanner-interface', 'unimodules-camera-interface', 'unimodules-sensors-interface', 'unimodules-task-manager-interface', 'expo-sqlite', 'expo-web-browser', 'unimodules-face-detector-interface']])

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
```

**Comment by RohovDmytro** [comment]
index.js

import 'react-native-gesture-handler';
import './src/user-subscription-handler';

import App from './App';
import { registerRootComponent } from 'expo';

registerRootComponent(App);

**Comment by RohovDmytro** [comment]
MainApplication.java

package com.trackerion;

import android.app.Application;
import android.net.Uri;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import com.trackerion.generated.BasePackageList;

import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;
import org.unimodules.core.interfaces.SingletonModule;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Nullable;

import expo.modules.updates.UpdatesController;

public class MainApplication extends Application implements ReactApplication {
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(
    new BasePackageList().getPackageList(),
    Arrays.<SingletonModule>asList()
  );


  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new ModuleRegistryAdapter(mModuleRegistryProvider));
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }

    @Override
    protected @Nullable String getJSBundleFile() {
      
      if (BuildConfig.DEBUG) {
        return super.getJSBundleFile();
      } else {
        return UpdatesController.getInstance().getLaunchAssetFile();
      }
       
    }

    @Override
    protected @Nullable String getBundleAssetName() {      
      if (BuildConfig.DEBUG) {
        return super.getBundleAssetName();
      } else {
        return UpdatesController.getInstance().getBundleAssetName();
      }
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    
    if (!BuildConfig.DEBUG) {
      UpdatesController.initialize(this);  
    }
  }
}

**Comment by brentvatne** [comment]
oh also, what's the exact version of expo-updates installed in your project?

**Comment by RohovDmytro** [comment]
`package.json`

```
{
  "main": "index.js",
  "scripts": {},
  "dependencies": {
    "@react-native-community/datetimepicker": "^2.3.2",
    "@react-native-community/google-signin": "^4.0.3",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-firebase/app": "^7.2.1",
    "@react-native-firebase/auth": "^8.0.5",
    "@react-native-firebase/firestore": "^7.1.7",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/material-bottom-tabs": "^5.2.10",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "emoji-datasource": "^5.0.1",
    "emoji-datasource-facebook": "^5.0.1",
    "emoji-mart-native": "^0.5.0-beta",
    "expo": "^37.0.12",
    "expo-asset": "^8.1.5",
    "expo-in-app-purchases": "~8.1.0",
    "expo-updates": "^0.2.9",
    "gatsby": "^2.20.2",
    "gatsby-plugin-react-native-web": "^3.0.0-beta.7",
    "lodash": "^4.17.15",
    "moment": "^2.25.3",
    "react": "16.9.0",
    "react-addons-shallow-compare": "^15.6.2",
    "react-dom": "16.9.0",
    "react-hook-thunk-reducer": "^0.2.4",
    "react-native": "0.61.4",
    "react-native-build-config": "^0.3.2",
    "react-native-chart-kit": "^5.5.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-material-color": "^1.0.15",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "^2.5.0",
    "react-native-svg": "^12.1.0",
    "react-native-swipe-list-view": "^3.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-typography": "^1.4.1",
    "react-native-unimodules": "^0.9.1",
    "react-native-web": "^0.11.7",
    "react-use-mailchimp": "^0.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.2.0",
    "babel-jest": "~24.9.0",
    "emojilib": "^2.4.0",
    "inflection": "^1.12.0",
    "jest": "~24.9.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-refresh": "^0.8.3",
    "react-test-renderer": "~16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

**Comment by brentvatne** [comment]
sorry i don't know what the problem is. we'll need to have access to the project or a minimal reproducible example (https://stackoverflow.com/help/mcve) in order to help any further

**Comment by RohovDmytro** [comment]
It works now. Bad news: I can say exactly what did help, cause I made changes all over.

My BEST guess (If any will run into a similar issue) is that it was something about `expo-asset`. I've switched to using `registerRootComponent ` vs `registerComponent ` and pured all of my cashes.

`expo` is a good piece of software.

**Comment by grifotv** [comment]
@RohovDmytro it would be great if you could share the solution!

- Did you end up with `expo-asset` listed in your package.json? What version?
- Did you use `registerRootComponent` or `registerComponent` at the end?

Thanks!

**Comment by brentvatne** [comment]
you should use `registerRootComponent` @grifotv.

compare your project setup to a new bare project using `expo init` with the bare template :)

**Comment by grifotv** [comment]
@brentvatne I'm already using `registerRootComponent` as I created my project with `expo init` with bare workflow + typescript. Hope typescript is not the issue here.

**Comment by brentvatne** [comment]
it is not. please create a new issue and provide a https://stackoverflow.com/help/mcve and we'd be happy to help! this issue is closed, and so it's best to create a new issue since what you are facing appears to be different. in general it's best to avoid commenting on closed issues
