### ISSUE TITLE
Expo should work locally even when Expo is down

### ISSUE THREAD

**Issue by mikescott** [expo/expo#8945]
### Summary of Issue 

* Expo is currently down
* I cannot log in to the Expo client app or access my profile on a phone where I'm already logged in: "An unexpected error has occurred"
* Expo CLI crashes with the exception:

```
Error: Request failed with status code 503
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Request failed with status code 503
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Request failed with status code 503
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Request failed with status code 503
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Request failed with status code 503
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

* This prevents the Expo app in a simulator or device on the same LAN/WLAN from retrieving the app: "There was a problem loading the requested app. Looks like you may be using a LAN URL..."

### Reproducible Demo

- Reproducible in any app when Expo is down (does not seem related to specific code)

### Steps to Reproduce

- Happens when Expo is down

### Expected Behavior vs Actual Behavior
Expected: Expo client should be able to access apps on the LAN even when the Expo service is down

Actual: Expo client cannot load LAN apps when Expo service is down

**Comment by mikescott** [comment]
After this happens, it seems to trigger the 'black screen' problem: https://github.com/expo/expo-cli/issues/866#issuecomment-647077550 which is fixable only by rebooting my system

**Comment by rafmrs** [comment]
I'm also experiencing this, didn't know this would happen. Feels awkward, any way to still run it?

**Comment by brentvatne** [comment]
Hi there! You can run `expo-cli` with `expo start --offline` to work while offline (either because server is down or some other reason, eg: you're actually offline).

**Comment by brentvatne** [comment]
@byCedric - can you investigate making expo-cli fall back to offline mode if the server is unreachable?

**Comment by rafmrs** [comment]
Didn't know about that, thanks for the tip :)

**Comment by sourabhCCSD** [comment]
I just closed and re-opned the VS Code and VOILAA happened. Easiest Fix on the Planet
