### ISSUE TITLE
[JEST-EXPO] Error on pathResolve

### ISSUE THREAD

**Issue by ptondereau** [expo/expo#8983]
### Summary of Issue (just a few sentences)

I am using Jest-expo 38 for my tests and since my upgrade from 37 to 38, I got this error below.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
$ expo diagnostics

  Expo CLI 3.21.12 environment info:
    System:
      OS: Linux 5.6 Manjaro Linux
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.5 - /usr/bin/npm
    npmPackages:
      expo: ^38.0.0 => 38.0.3
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.12
```

```
> @ test /home/me/code
> jest

internal/validators.js:121
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:121:11)
    at Object.resolve (path.js:980:7)
    at Object.<anonymous> (/home/me/code/node_modules/jest-expo/bin/jest.js:20:30)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest`
npm ERR! Exit status 1
```

I fixed this issue by editing `node_modules/jest-expo/bin/jest.js` at line 20 by:
```
const jestProgramPath = path.resolve(jestPackagePath, jestPackageJson.bin.jest);
```

What do you think

**Comment by bernardobelchior** [comment]
I have exactly the same issue after installing `jest-expo@38.0.0`.

**Comment by brentvatne** [comment]
@ptondereau @bernardobelchior - can you share your package.json?

**Comment by ptondereau** [comment]
@brentvatne 
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "lint": "eslint src/**/*.{ts,tsx} App.tsx",
    "fix": "eslint src/**/*.{ts,tsx} App.tsx --fix",
    "test": "jest --detectOpenHandles",
    "test-debug": "jest -o --watch --coverage=false",
    "generate-types": "node scripts/generateTypes.js",
    "generate-types:check": "node scripts/checkTypes.js",
    "ts-check": "npx tsc"
  },
  "dependencies": {
    "@bugsnag/expo": "^7.1.1",
    "@expo/react-native-action-sheet": "^3.8.0",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.9.2",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "@rematch/core": "^1.4.0",
    "@rematch/loading": "^1.2.1",
    "@rematch/persist": "^1.1.6",
    "axios": "^0.19.2",
    "base-64": "^0.1.0",
    "dayjs": "^1.8.28",
    "expo": "^38.0.0",
    "expo-font": "~8.2.1",
    "expo-image-picker": "~8.3.0",
    "expo-location": "~8.2.1",
    "expo-svg-uri": "^1.1.0",
    "formik": "^2.1.4",
    "native-base": "2.13.12",
    "native-base-autocomplete": "^1.3.2",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
    "react-native-actionsheet": "^2.4.2",
    "react-native-form-validator": "^0.3.2",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-image-picker": "^2.3.1",
    "react-native-image-viewing": "^0.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-modal-picker": "0.0.16",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "3.0.2",
    "react-native-screens": "~2.9.0",
    "react-native-sectioned-multi-select": "^0.7.7",
    "react-native-svg": "12.1.0",
    "react-native-web": "~0.11.7",
    "react-redux": "^7.2.0",
    "react-timeago": "^4.4.0",
    "ts-debounce": "^2.0.1",
    "yup": "^0.29.1",
    "expo-splash-screen": "~0.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.3",
    "@types/jest": "^26.0.3",
    "@types/node": "^14.0.14",
    "@types/react": "~16.9.41",
    "@types/react-native": "~0.62.13",
    "@types/react-native-actionsheet": "^2.4.1",
    "@types/react-redux": "^7.1.9",
    "@types/react-timeago": "^4.1.1",
    "@types/yup": "^0.29.3",
    "@typescript-eslint/eslint-plugin": "^2.34.0",
    "@typescript-eslint/parser": "^2.34.0",
    "babel-preset-expo": "^8.2.3",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-native": "^3.8.1",
    "jest-expo": "^37.0.0",
    "prettier": "^2.0.5",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-testing-library": "^2.1.0",
    "react-test-renderer": "^16.13.1",
    "swagger-typescript-api": "^1.8.4",
    "typescript": "~3.9.5"
  },
  "jest": {
    "preset": "jest-expo",
    "setupFiles": [
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*|@ptomasroos/react-native-multi-slider|@bugsnag/.*)"
    ],
    "moduleNameMapper": {
      "\\.svg": "<rootDir>/__mocks__/svgMock.js"
    }
  },
  "private": true
}

```

**Comment by bernardobelchior** [comment]
```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "~38.0.1",
    "expo-splash-screen": "~0.3.1",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "jest-expo": "^38.0.0",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "private": true
}
```

**Comment by abmantis** [comment]
This was caused by the following change: https://github.com/expo/expo/pull/7556/files#diff-68c0f5a3773234e2ed284864d5b4003bR20

Editing the jest bin wrapper and adding back `jestPackageJson.bin.jest`, fixes the issue.

**Comment by byCedric** [comment]
It looks like the [bin change should be introduced starting from `jest@25.2.0`](https://github.com/facebook/jest/commit/10d3cef30b4fc7261909aa3d8f0298c3266fcd01#diff-6b17a4749020285151b7870160a8caf1L12-R12). But apparently, this isn't always updated by NPM/Yarn.

To avoid this issue, we might want to do either one of these:

- Try `.bin.jest` and if it doesn't exist, use `.bin` (should fix pre and post 25.2.0 jest)
- Update `jest-expo` to 26 (major change should "force" a new install of jest in node_modules)

What do you think @brentvatne?

**Comment by mdbiscan** [comment]
I just upgraded to Expo 38.0.0 and having the same issue. Downgrading to `jest-expo@37.0.0` does fix this issue.

**Comment by abmantis** [comment]
@byCedric I have jest@25.5.4 and still have this issue.

![image](https://user-images.githubusercontent.com/974569/86060647-14170800-ba5d-11ea-8e4c-7122d77a21a0.png)

**Comment by byCedric** [comment]
So this is kinda weird, but I think you are using NPM right? If I do `yarn add jest@25.5.4`, I get the proper `"bin": "./bin/jest.js"`. But if I do `npm install jest@25.5.4` I get the object you mentioned @abmantis. I guess we need to add support for both to get this working properly.

**Comment by bernardobelchior** [comment]
@byCedric I am also using NPM, which confirms your hypothesis.

**Comment by ptondereau** [comment]
@byCedric I'm also using NPM

**Comment by byCedric** [comment]
Thanks for the confirmation, that's it then. I have no clue whatsoever [why NPM decided `bin: "some/string.js"` is actually short for `bin: { myapp: "some/string.js" }`](https://docs.npmjs.com/files/package.json#bin). But a PR to fix it is on it's way! 😄

**Comment by bernardobelchior** [comment]
Thanks for the fast turnaround!

**Comment by esdrasevt** [comment]
Was this fixed? I still have this issue, and it seems to be fixed after downgrading to jest-expo@37

**Comment by kopax** [comment]
I just updated to expo SDK38 and my CI fail with that error.

I am using `jest-expo` 38.0.0 and I am trying to upgrade to latest 38.0.2

I do not have `jest` installed in my `package.json`.

**Comment by brentvatne** [comment]
you can use patch-package to apply https://github.com/expo/expo/pull/9022 to your local copy of jest-expo

**Comment by ikidnapmyself** [comment]
Downgrading from @38.0.2 to @37.0.0 solved my issue.

**Comment by igorbrandao** [comment]
Also happening on my CI after upgrading to SDK 38. Will be downgrading to jest-expo 37 for now and waiting for the merge and release to have it properly versioned. Thanks!
