### ISSUE TITLE
Upgrading to SDK 38 Broke Bare App

### ISSUE THREAD

**Issue by ksitko** [expo/expo#9019]
### Summary of Issue (just a few sentences)

Upgrading to the latest version of Expo using `expo upgrade` has broken my Bare workflow app. Attempting to start it results in the following:
```
 react-native start
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-video: https://npmjs.com/package/react-native-video
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error (0 , _metro(...).createBlacklist) is not a function. Run CLI with --verbose flag for more details.
TypeError: (0 , _metro(...).createBlacklist) is not a function
    at getBlacklistRE (/Users/k/alz-mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/loadMetroConfig.js:66:59)
    at getDefaultConfig (/Users/k/alz-mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/loadMetroConfig.js:82:20)
    at load (/Users/k/alz-mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/loadMetroConfig.js:118:25)
    at Object.runServer [as func] (/Users/k/alz-mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/server/runServer.js:97:58)
    at Command.handleAction (/Users/k/alz-mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:23)
    at Command.listener (/Users/k/alz-mobile/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/Users/k/alz-mobile/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/k/alz-mobile/node_modules/commander/index.js:474:21)
    at setupAndRun (/Users/k/alz-mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:255:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

expo diagnostics

 ```
 Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.4 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7
```
### Steps to Reproduce

Upgrade Bare workflow app from Expo 37 to Expo 38 and start the app

### Expected Behavior vs Actual Behavior

Regular start of the app

**Comment by tsapeta** [comment]
cc @brentvatne @fson as it seems to be related with `expo-cli` 🤔

**Comment by ksitko** [comment]
Deleting node_modules folder along with yarn.lock file and reinstalling all modules with yarn fixed issue.
