### ISSUE TITLE
[SDK38][jest-expo] The "path" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by tills98** [expo/expo#9039]
### Summary of Issue (just a few sentences)
When I run `npm run test` it returns following exception since upgrade to SDK 38:
```
> @ test /Users/..../my_new_awesome_test
> jest

internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:117:11)
    at Object.resolve (path.js:980:7)
    at Object.<anonymous> (/Users/.../my_new_awesome_test/node_modules/jest-expo/bin/jest.js:20:30)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-06-30T15_02_55_540Z-debug.log
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.4 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Reproducible Demo
1. Create a new blank typescript project
2. Install the following packages:
```
npm install --save-dev jest jest-expo react-native-test-renderer @types/jest
```
3. Create a simple test in \_\_tests\_\_/App.test.tsx with following content:
```
describe("App", () => {
  it("should render", async () => {
    expect(true).toBeTruthy();
  });
});
```

### Steps to Reproduce
1. Run `npm run test`

### Expected Behavior vs Actual Behavior
Actual behavior: Following error
> @ test /Users/..../my_new_awesome_test
> jest

internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:117:11)
    at Object.resolve (path.js:980:7)
    at Object.<anonymous> (/Users/.../my_new_awesome_test/node_modules/jest-expo/bin/jest.js:20:30)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-06-30T15_02_55_540Z-debug.log
```

Expected behavior: Test will run successfully

**Comment by xn3cr0nx** [comment]
I faced this too. You need to update jest to the latest version. This fixed for me https://stackoverflow.com/a/46245846

**Comment by tills98** [comment]
Oh yes, I found my issue. I need to upgrade jest with the following command and it works:
```
npm install jest@latest --save-dev
```
Thank you!

**Comment by andresmanikis** [comment]
I'm not sure this is the correct solution. In the [Expo documentation](https://docs.expo.io/guides/testing-with-jest/) it seems there's no need to install Jest as a separate package.

**Comment by actuallymentor** [comment]
> I'm not sure this is the correct solution. In the Expo documentation it seems there's no need to install Jest as a separate package.

Correct solution or not, my tests run again and I see little harm in this.

**Comment by gyoung-panopto** [comment]
@actuallymentor Could you share your working package.json for jest-related packages? I ran into the same issue as on this thread but am now hitting this error with every single test and feel like I am missing a crucial piece of config.

SyntaxError: C:\tfs\Panopto\react-native-mobile\node_modules\react-native\Libraries\polyfills\error-guard.js: Unexpected token, expected ";" (14:5)

      12 | let _inGuard = 0;
      13 |
    > 14 | type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         |      ^
      15 | type Fn<Args, Return> = (...Args) => Return;
      16 |
      17 | /**

      at Parser._raise (node_modules/@babel/parser/lib/index.js:757:17)
      at Parser.raiseWithData (node_modules/@babel/parser/lib/index.js:750:17)
      at Parser.raise (node_modules/@babel/parser/lib/index.js:744:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:8834:16)
      at Parser.semicolon (node_modules/@babel/parser/lib/index.js:8816:40)
      at Parser.parseExpressionStatement (node_modules/@babel/parser/lib/index.js:11736:10)
      at Parser.parseStatementContent (node_modules/@babel/parser/lib/index.js:11337:19)
      at Parser.parseStatement (node_modules/@babel/parser/lib/index.js:11203:17)
      at Parser.parseBlockOrModuleBlockBody (node_modules/@babel/parser/lib/index.js:11778:25)
      at Parser.parseBlockBody (node_modules/@babel/parser/lib/index.js:11764:10)

**Comment by gyoung-panopto** [comment]
I figured it out - was missing the recommended babel.config.js file at the root. Thanks!

**Comment by amber-pli** [comment]
@tills98 sorry `npm install jest@latest --save-dev` works, but if I do a clean install of my project i.e., `npm i` (in CI) then run jest will cause above error again.

**Comment by WolfyUK** [comment]
@amber-pli None of the solutions above worked for me either. However, this is also discussed [here](https://github.com/expo/expo/issues/8983), along with a [PR](https://github.com/expo/expo/pull/9022) that patches `jest-expo/bin/jest.js`. This seems to work for my CI scenario.

**Comment by kopax** [comment]
I just updated to expo SDK38 and my CI fail with that error., I have tried to see if it's fixed but apparently the fix is not released.

I am using `jest-expo` 38.0.0 and I have just tried to upgrade to latest 38.0.2 and this fix is not in yet. I do not have `jest` installed in my `package.json`, I am reverting to jest-expo@37

**Comment by IvanMtz97** [comment]
For me, downgrading `jest-expo` from `38.0.0` to `37.0.0` worked, for clean install node modules and CI.

**Comment by PedroBern** [comment]
`npm install jest@latest --save-dev` worked for me
