### ISSUE TITLE
Error running jest tests for files that import expo-file-system after Expo 38 upgrade

### ISSUE THREAD

**Issue by gyoung-panopto** [expo/expo#9171]
### Summary of Issue 

Some tests that were passing before the version upgrade are now failing with an obtuse error. The only difference between these files and others that work is that the components they have an import of expo-file-system.

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      10 | {
      11 |     session: Session;
    > 12 |     download: Download;
         |                ^
      13 | }
      14 |
      15 | /**

      at executeSql (node_modules/@expo/websql/lib/websql/WebSQLTransaction.js:101:3)
      at WebSQLTransaction.Object.<anonymous>.WebSQLTransaction.executeSql (node_modules/@expo/websql/lib/websql/WebSQLTransaction.js:125:3)
      at TransactionTask.txnCallback (src/database/DownloadedSessionsTable.ts:12:16)
      at node_modules/@expo/websql/lib/websql/WebSQLDatabase.js:61:23
      at Item.Object.<anonymous>.Item.run (node_modules/immediate/lib/index.js:72:12)
C:\tfs\Panopto\react-native-mobile\node_modules\@expo\websql\lib\websql\WebSQLTransaction.js:101
  require('immediate')(function () {
                      ^

TypeError: require(...) is not a function
    at executeSql (C:\tfs\Panopto\react-native-mobile\node_modules\@expo\websql\lib\websql\WebSQLTransaction.js:101:23)
    at WebSQLTransaction.Object.<anonymous>.WebSQLTransaction.executeSql (C:\tfs\Panopto\react-native-mobile\node_modules\@expo\websql\lib\websql\WebSQLTransaction.js:125:3)
    at TransactionTask.txnCallback (C:\tfs\Panopto\react-native-mobile\src\database\DownloadedSessionsTable.ts:12:16)
    at C:\tfs\Panopto\react-native-mobile\node_modules\@expo\websql\lib\websql\WebSQLDatabase.js:61:23
    at Item.Object.<anonymous>.Item.run (C:\tfs\Panopto\react-native-mobile\node_modules\immediate\lib\index.js:72:12)
    at nextTick (C:\tfs\Panopto\react-native-mobile\node_modules\immediate\lib\index.js:43:32)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Test suite failed to run

    Call retries were exceeded

      at ChildProcessWorker.initialize (node_modules/jest/node_modules/jest-worker/build/workers/ChildProcessWorker.js:191:21)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.22.1 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^3.11.0 => 3.13.0

Relevant jest packages and config:
    "jest": "^26.1.0",
    "jest-cli": "^24.8.0",
    "jest-expo": "^38.0.0",
    "react-test-renderer": "^16.13.1",
    "ts-jest": "^26.1.1",
"jest": {
    "preset": "jest-expo",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
      "^.+\\.tsx?$": "ts-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ],
    "testMatch": [
      "**/__tests__/**/*.ts?(x)",
      "**/?(*.)+(spec|test).ts?(x)"
    ],
    "moduleFileExtensions": [
      "js",
      "ts",
      "tsx"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/setupTests.js"
    ],
    "globals": {
      "ts-jest": {
        "tsConfig": {
          "jsx": "react"
        }
      }
    }
  }

### Reproducible Demo

I doubt I will be able to create a demo for this issue, but I'm wondering if you could advise me on any missing config or package updates that I need to take because I can't find any information about this issue.
 
### Steps to Reproduce

Create a file that imports expo-file-system
Create a test file that imports the file
Run the test using jest and the above config

### Expected Behavior vs Actual Behavior

These tests were passing before the upgrade but now they repeatedly fail and time out.

**Comment by byCedric** [comment]
Hi @gyoung-panopto, thanks for your issue report! Unfortunately, I can't reproduce this in a new tabs project. The configuration you mentioned contains a lot of stuff that `jest-expo` should take care of already.

Have you tried running your project with the following configuration instead? If not, it might be related to something in your `setupTests.js`. But, without a reproducible example, it's hard to pinpoint the exact issue here.

```
"jest": {
    "preset": "jest-expo",
    "testMatch": [
      "/tests//.ts?(x)",
      "**/?(.)+(spec|test).ts?(x)"
    ],
    "setupFilesAfterEnv": [
      "/setupTests.js"
    ]
}
```
> I removed the custom typescript integration and extensions, `jest-expo` already supports typescript out of the box. And the transform ignore is also set for you, so I removed that one as well.

**Comment by gyoung-panopto** [comment]
Thank you for taking a look at this! I decided to try removing all the packages and following Expo's guide to set up jest from scratch, which basically resulted in removing all the config you specified. I'm now getting a different error on every test - I feel like I'm getting close but still missing a crucial piece of config:

SyntaxError: C:\tfs\Panopto\react-native-mobile\node_modules\react-native\Libraries\polyfills\error-guard.js: Unexpected token, expected ";" (14:5)

      12 | let _inGuard = 0;
      13 |
    > 14 | type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         |      ^
      15 | type Fn<Args, Return> = (...Args) => Return;
      16 |
      17 | /**

      at Parser._raise (node_modules/@babel/parser/lib/index.js:757:17)
      at Parser.raiseWithData (node_modules/@babel/parser/lib/index.js:750:17)
      at Parser.raise (node_modules/@babel/parser/lib/index.js:744:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:8834:16)
      at Parser.semicolon (node_modules/@babel/parser/lib/index.js:8816:40)
      at Parser.parseExpressionStatement (node_modules/@babel/parser/lib/index.js:11736:10)
      at Parser.parseStatementContent (node_modules/@babel/parser/lib/index.js:11337:19)
      at Parser.parseStatement (node_modules/@babel/parser/lib/index.js:11203:17)
      at Parser.parseBlockOrModuleBlockBody (node_modules/@babel/parser/lib/index.js:11778:25)
      at Parser.parseBlockBody (node_modules/@babel/parser/lib/index.js:11764:10)

And here is the relevant package.json now:

"devDependencies": {
    "jest": "^26.1.0",
    "jest-expo": "^38.0.2",
    "react-test-renderer": "^16.13.1"
},

"jest": {
    "preset": "jest-expo",
    "testMatch": [
      "**/__tests__/**/*.ts?(x)",
      "**/?(*.)+(spec|test).ts?(x)"
    ]
  }

Is there anything missing here? Thanks again for working with me on this.

**Comment by gyoung-panopto** [comment]
I figured this out - I was missing the recommended babel.config.js at the root directory. Thanks!
