### ISSUE TITLE
[sentry-expo] Source code was not found

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#9175]
### Summary of Issue 

In Expo SDK 38 with `sentry-expo` + `expo-updates` the source maps never are found.
The bug happen in iOS and Android.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Reproducible Demo

1. Clone demo repo: https://github.com/RodolfoGS/expo-sentry-source-map
2. `npm install`
3. Configure Sentry following this instructions https://github.com/RodolfoGS/expo-sentry-source-map
4. Build your app with Android Studio
5. Install the APK in your device
6. Tap on `Crash Now` button in the app
7. The crash in Sentry appear like this:
```
Error: Test Error
  at forEach([native code])
  at value([native code])
```

Maybe that happen because you never make `expo publish` to send the source map to Sentry with the `postPublish` script. To solve this, publish an update:

8. `expo publish` (your source maps will be send to Sentry)
9. Open app and restart to make sure that the updated was installed
10. Tap on `Crash Now` button in the app
11. The crash in Sentry appear like this:
```
Error: Test Error
  at handleCrash(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:589:168)
  at onPress(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:215:2097)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:216:7541)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:216:6754)
  at onResponderRelease(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:216:5557)
  at y(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1126)
  at k(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1269)
  at w(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1323)
  at R(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1618)
  at M(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:2402)
  at forEach([native code])
  at U(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:2202)
  at ? (/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:13819)
  at Pe(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:90853)
  at Re(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:13479)
  at Ie(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:13665)
  at receiveTouches(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:14449)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:3545)
  at ? (/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:841)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:2799)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:813)
  at value([native code])
```

### Steps to Reproduce

1. `expo init SentryIssue`
2. `cd SentryIssue`
3. `npm install sentry-expo`
4. Configure Sentry following the Docs: https://docs.expo.io/guides/using-sentry/#how-to-add-sentry-to-your-expo
5. Add a crash button. Example: `throw new Error('Test error')`
6. `expo publish`
7. Restart the app to install the update
8. Dispatch the crash
9. Sentry can't found the source maps.

### Expected Behavior vs Actual Behavior

**Expected Behavior**: Sentry found the source maps
**Actual Behavior**: Sentry can't found the source maps

I think that this happen because the expo-updates run the app in a file with a name like this:
`..../files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js`

But the source maps are sent to Sentry with the name `~/main.android.bundle` and `~/main.ios.bundle`

Sentry artifacts:
![image](https://user-images.githubusercontent.com/870365/87226220-f2205e00-c357-11ea-8ecd-ff9e4724cb27.png)

Error:
![image](https://user-images.githubusercontent.com/870365/87226238-0d8b6900-c358-11ea-9087-38f72d3f97e3.png)

Raw error:
```
Error: Test Error
  at handleCrash(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:589:168)
  at onPress(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:215:2097)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:216:7541)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:216:6754)
  at onResponderRelease(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:216:5557)
  at y(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1126)
  at k(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1269)
  at w(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1323)
  at R(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:1618)
  at M(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:2402)
  at forEach([native code])
  at U(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:2202)
  at ? (/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:13819)
  at Pe(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:90853)
  at Re(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:13479)
  at Ie(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:13665)
  at receiveTouches(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:96:14449)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:3545)
  at ? (/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:841)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:2799)
  at value(/data/user/0/com.sentryissue/files/.expo-internal/39FA8ADAFC39C79109D0D4480479C5132420E32B7D3602A07125653273B13136.js:28:813)
  at value([native code])
```

**Comment by changLiuUNSW** [comment]
I have exactly the same issue in my app which is based on Expo 37 Bare workflow.
![image](https://user-images.githubusercontent.com/7379922/87260918-8543ca00-c4f7-11ea-8682-6cda4d713b69.png)

**Comment by byCedric** [comment]
Hi people! Thanks for the issue reports. We are currently working on integrating `sentry-expo` in Expo bare, including the no-publish workflow. I'll put in some efforts to merge and release a new version once it's done. It will be a breaking change because there are a lot of changes to support the bare workflow.

Let's keep this issue open until a new version is released!

**Comment by cruzach** [comment]
We have an RC version of `sentry-expo` published as `next` right now, so you guys can give that a try and let me know if it fixes the issue? You'll also need to follow the additional [bare workflow setup steps](https://github.com/expo/sentry-expo#bare-workflow-setup)

**Comment by RodolfoGS** [comment]
@cruzach wow thanks, I'll test in next weekend, I keep you updated if it works! Again, thank you so much for your help!

**Comment by changLiuUNSW** [comment]
@cruzach 
Hi I have tried sentry-expo ```3.0.0-rc3``` and followed bare workflow setup steps but the sourcemap still not working.

![image](https://user-images.githubusercontent.com/7379922/90846435-76302180-e3ab-11ea-9392-307bc724ec44.png)

**Comment by ezequielrozen** [comment]
@changLiuUNSW I'm having the same problem. The source maps are there but Android is looking for them in an expo path. How did you fix it? I'm using sentry-expo@3.0.0
