### ISSUE TITLE
expo start error

### ISSUE THREAD

**Issue by chinnanaresh** [expo/expo#9196]
expo start
EPERM: operation not permitted, read
Error: EPERM: operation not permitted, read
    at Object.readSync (fs.js:524:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:378:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1152:22)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Namani\AppData\Roaming\npm\node_modules\expo-cli\node_modules\request\index.js:18:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)

**Comment by chinnanaresh** [comment]
Help !!!

**Comment by cruzach** [comment]
Hi @chinnanaresh, this is most likely not a bug with Expo but rather with your npm permissions - https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows
