### ISSUE TITLE
Error while updating property 'selectionColor' of a view managed by: AndroidTextInput

### ISSUE THREAD

**Issue by fabiocastrodev** [expo/expo#925]
Hi,

I am compiling an application for client expo and am having the following problem: Error while updating propert 'selectionColor' of a view managed by: AndroidTextInput

expo-sdk: 20.0.0
react-native: 0.47.1

**Comment by dikaiosune** [comment]
Hi! It's very difficult to help with bug reports that don't include code or an explanation of the code that's causing a problem. Can you create a minimal reproduction of your issue on https://snack.expo.io and post back? I'll reopen the issue if we can get enough information to help you troubleshoot.

**Comment by fabiocastrodev** [comment]
Hello, the problem started after I used exp detach and I'm compiling with ExpoKit, the compilation does not have any problem, however when rendering the TextInput component with the selectionColor property the error is triggered, however this only happens in applications that use exp detach, follows the Snack however the error will not be triggered. I could simply not use the property, but several libraries I use in the project use the property, I also tested only with react-native, without ExpoKit and the problem does not exist.

Snack: https://snack.expo.io/H1UDozk1G

expo-sdk: 20.0.0
react-native: 0.47.1

**Comment by kadoshms** [comment]
+1,
Im experiencing the same issue

**Comment by chochihim** [comment]
I eject with ExpoKit from create-react-native-app and encounter the same issue. Is it problem with expo sdk?

**Comment by aniltirola** [comment]
same problem; the property 'selectionColor' used on the component 'TextInput' works on:
- expo-client: ios
- expo-client: android
- standalone with exp:build:android

it does not work and throws the error when:
- detaching and running on android

**Comment by pendo324** [comment]
I'm running into the same issue here, @aniltirola. Works perfectly fine until detached.

**Comment by ArsenyYankovsky** [comment]
Same here. Can't change windowSoftInputMode without detaching to work around an [other issue](https://github.com/expo/expo/issues/1211). Can't use detached app because of this one.

**Comment by RoWaiR** [comment]
### Error

> Error while updating prop selectionColor
                                                      java.lang.reflect.InvocationTargetException
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
                                                          at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
                                                          at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
                                                          at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
                                                          at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214)
                                                          at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
                                                          at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006)
                                                          at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977)
                                                          at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                          at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                          at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                          at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                       Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                          at android.content.res.Resources.getValue(Resources.java:2596)
                                                          at android.content.res.Resources.getDrawable(Resources.java:2039)
                                                          at android.content.res.Resources.getDrawable(Resources.java:2025)
                                                          at android.content.Context.getDrawable(Context.java:464)
                                                          at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
                                                          at com.facebook.react.views.textinput.ReactTextInputManager.setCursorColor(ReactTextInputManager.java:334)
                                                          at com.facebook.react.views.textinput.ReactTextInputManager.setSelectionColor(ReactTextInputManager.java:321)
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
                                                          at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
                                                          at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
                                                          at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                          at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214) 
                                                          at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                          at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006) 
                                                          at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977) 
                                                          at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                          at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                          at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
                                                          at android.view.Choreographer.doFrame(Choreographer.java:619) 
                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                          at android.os.Handler.handleCallback(Handler.java:739) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                          at android.os.Looper.loop(Looper.java:148) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
05-17 11:12:28.139 8384-8384/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.wupplier.app, PID: 8384
                                                 com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'selectionColor' of a view managed by: AndroidTextInput
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:92)
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
                                                     at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
                                                     at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977)
                                                     at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                     at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                     at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
                                                     at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                     at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214) 
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006) 
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977) 
                                                     at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                     at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                     at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
                                                     at android.view.Choreographer.doFrame(Choreographer.java:619) 
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                  Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                     at android.content.res.Resources.getValue(Resources.java:2596)
                                                     at android.content.res.Resources.getDrawable(Resources.java:2039)
                                                     at android.content.res.Resources.getDrawable(Resources.java:2025)
                                                     at android.content.Context.getDrawable(Context.java:464)
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
                                                     at com.facebook.react.views.textinput.ReactTextInputManager.setCursorColor(ReactTextInputManager.java:334)
                                                     at com.facebook.react.views.textinput.ReactTextInputManager.setSelectionColor(ReactTextInputManager.java:321)
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
                                                     at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                     at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214) 
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006) 
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977) 
                                                     at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                     at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                     at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
                                                     at android.view.Choreographer.doFrame(Choreographer.java:619) 
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

sdk 23.0.0

It just happens to me creating the release, debug works fine.

Any solution ?

**Comment by mikeumus** [comment]
@lilymGoh's [solution](https://github.com/n4kz/react-native-material-textfield/issues/54#issuecomment-340553507) worked for me here:

> Remove `selectionColor={}` on line 484 in `src/components/field/index.js` should fix it.

**Comment by RoWaiR** [comment]
I do not have that file.

**Comment by mikeumus** [comment]
@RoWaiR, search your code for where your culprit `selectionColor` is located.

**Comment by sjchmiela** [comment]
I've just run an ejected project on SDK31 in release mode and the code provided in Snack didn't crash the app. 🎉 I hope the issue is solved now. 🙂
