### ISSUE TITLE
java.lang.RuntimeException: Unable to create application host.exp.exponent.MainApplication: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.f

### ISSUE THREAD

**Issue by indrasan88** [expo/expo#9318]
Hello i got this error when release expokit and didn't happen last month, build success and when tried to open released app, it will close and error like this. please help

Expo CLI 3.22.3 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.22.3

ERROR : 

java.lang.RuntimeException: Unable to create application host.exp.exponent.MainApplication: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.f
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.f
        at host.exp.exponent.l.a.a(NativeModuleDepsProvider.java:12)
        at host.exp.exponent.l.a.b(NativeModuleDepsProvider.java:2)
        at g.a.a.b.<init>(Exponent.java:9)
        at g.a.a.b.a(Exponent.java:4)
        at host.exp.exponent.d.onCreate(ExpoApplication.java:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by byCedric** [comment]
Hi @indrasan88, thanks for your issue report. Unfortunately, we need a repro to help you find the issue. Without that, we can't  help much. There are other issues reported that look similar, maybe you can try [one of their solutions](https://github.com/expo/expo/issues/3934#issuecomment-480604395). I'd also want to mention that we are dropping support for Expokit after SDK 38, you can [read more about that here](https://dev.to/expo/time-to-start-using-expo-s-bare-workflow-expokit-is-now-deprecated-51ih).

Hope it helps!
