### ISSUE TITLE
[expo-updates] File download was successful, but failed to move from temporary to permanent location 

### ISSUE THREAD

**Issue by arberK** [expo/expo#9367]
I am encountering this problem on Android (iOS works fine) in my existing project initiated with react-native init.

Here is a snippet from Flipper:
```
	Time	Tag	Message
	17:43:31.596	FileDownloader	Failed to download file to destination /data/user/0/com.mobile.appxy/files/.expo-internal/5AE07E9DA351235EB71600E1C4E49168BF380425A683BA8CAEEDF397AB967852.js
java.io.IOException: File download was successful, but failed to move from temporary to permanent location /data/user/0/com.mobile.appxy/files/.expo-internal/5AE07E9DA351235EB71600E1C4E49168BF380425A683BA8CAEEDF397AB967852.js
	at expo.modules.updates.UpdatesUtils.sha256AndWriteToFile(UpdatesUtils.java:87)
	at expo.modules.updates.loader.FileDownloader$1.onResponse(FileDownloader.java:68)
	at expo.modules.updates.loader.FileDownloader$4.onResponse(FileDownloader.java:187)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

	17:43:31.597	DatabaseLauncher	Failed to load asset from disk or network
java.io.IOException: File download was successful, but failed to move from temporary to permanent location /data/user/0/com.mobile.appxy/files/.expo-internal/5AE07E9DA351235EB71600E1C4E49168BF380425A683BA8CAEEDF397AB967852.js
	at expo.modules.updates.UpdatesUtils.sha256AndWriteToFile(UpdatesUtils.java:87)
	at expo.modules.updates.loader.FileDownloader$1.onResponse(FileDownloader.java:68)
	at expo.modules.updates.loader.FileDownloader$4.onResponse(FileDownloader.java:187)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

	17:43:31.597	DatabaseLauncher	Could not launch; failed to load update from disk or network
```
Sadly, I cant share a reproducible repo due to c. policies? 

Another issue I am facing (on iOS also), is that expo-updates does not trigger download requests for assets. I host app bundles & assets from my own server  (See  #[9380](https://github.com/expo/expo/issues/9380) )

```
...
"react-native": "0.62.2",
"expo-updates": "^0.2.11",
...

**Comment by brentvatne** [comment]
> Sadly, I cant share a reproducible repo due to c. policies?

you don't need to share your entire app to reproduce! in fact we really don't want your app. see https://stackoverflow.com/help/mcve for more information on how to create a reproducible example
