### ISSUE TITLE
expo  android App crash on launch 

### ISSUE THREAD

**Issue by omar-bakhsh** [expo/expo#9462]
expo  android App crash on launch Apk
```
  "dependencies": {
    "expo": "^38.0.0",
    "expo-ads-admob": "~8.2.1",
    "expo-localization": "~8.2.1",
    "expo-updates": "~0.2.8",
    "i18n-js": "^3.7.1",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "~0.11.7"
  },
```

log cat-file 
   ******************************************************************************
```

    Process: com.codigGroup.vatApp, PID: 21258
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to *
    * find your app ID.                                                          *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to *
    * find your app ID.                                                          *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.g0.attachInfo(Unknown Source:10)
```

**Comment by RodolfoGS** [comment]
> Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to find your app ID.

You forgot config admob. Read the doc: https://docs.expo.io/versions/latest/sdk/admob/#configuration

**Comment by byCedric** [comment]
Hi @omar-bakhsh, the error shows indeed that you are missing the app ID. As @RodolfoGS mentioned (thanks!), you need to configure that before you can use admob. If you think this is a problem with the admobs integration, please let us know in a new issue. Also, please fill in the issue form so we can reproduce it (and possibly) fix it on our end.

Thanks!

**Comment by omar-bakhsh** [comment]
solved after replace **_key_** of **googleMobileAdsAppId** instead of **_ad banner key_** that looks like each other 
ca-app-pub-00004454..
ca-app-pub-15524185..
