### ISSUE TITLE
Jest setupFiles doesn't seem to be firing when using universal preset

### ISSUE THREAD

**Issue by Trashpants** [expo/expo#9541]
### Summary of Issue 
Trying to follow the setup of jest with react navigation on a fresh project - it requires adding setupFiles, which when using the universal preset never seems to be run no matter the location

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/local/opt/node/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.23.1

```
### Steps to Reproduce

Create a new project add new file at root:

```
jest.setup.js
---- with content ----
console.log('run on every test');
```

update package.json
```
"jest": {
    "preset": "jest-expo/universal",
    "setupFiles": [
      "<rootDir>/jest.setup.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ]
  },
```

### Expected Behavior vs Actual Behavior
when you run 'yarn test' it won't display any console.log statements, switch to "preset": "jest-expo" and the console.log will be displayed

Also to add into this following this guide exactly from the docs flat out fails. (if it makes a difference im using blank+typescript)

https://docs.expo.io/guides/testing-with-jest/

Attempting to even run the initial unit test breaks with:

```
yarn run v1.22.4
$ node_modules/.bin/jest
Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected
 FAIL  __tests__/Example-test.native.tsx
  <App />
    ✕ has 1 child (23ms)

  ● <App /> › has 1 child

    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14410:21)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14433:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4982:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5042:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7241:28)
      at updateHostRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7709:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9047:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12649:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12622:22)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12333:9)

  console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

       6 | describe('<App />', () => {
       7 |   it('has 1 child', () => {
    >  8 |     const tree = renderer.create(<App />).toJSON();
         |                                  ^
       9 |     expect(tree.children.length).toBe(1);
      10 |   });
      11 | });

      at warningWithoutStack (node_modules/react/cjs/react.development.js:167:32)
      at warning (node_modules/react/cjs/react.development.js:638:27)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2035:5)
      at Object.<anonymous> (__tests__/Example-test.native.tsx:8:34)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.761s, estimated 1s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jbernhardt23** [comment]
Can confirm this issue with `jest-expo: 38.0.0`

**Comment by markneh** [comment]
Same issue. It works if you change .tsx extensions to .js so it might be related to jest typescript configuration

**Comment by markneh** [comment]
I added `"moduleFileExtensions": ["ts", "tsx", "js"]` to jest configuration in package.json and now it works for me

**Comment by Trashpants** [comment]
Started a new project with SDK 39 and added the moduleFileExtensions as per markneh suggestion. it doesn't seem to work for me, I still get errors with setupFiles and setupFilesAfterEnv not making an impact at all

**Comment by ezequielrozen** [comment]
Hi! Any update about this issue? I'm not able to use `setupFiles` configuration also. I'm using `expor sdk v39.0.2`

**Comment by extrct** [comment]
Based on `setup of jest with react navigation on a fresh project` and the error message, this looks related to an error with the jest < 27.0.6/27.0.0-next `moduleFileExtensions` default config value. Here's a related PR with an equivalent solution to @markneh above: https://github.com/expo/expo/pull/11580

**Comment by Justinohallo** [comment]
Ran into this same issue. Why do the docs not reflect this?
