### ISSUE TITLE
exp whoami fails

### ISSUE THREAD

**Issue by slorber** [expo/expo#956]
I am using a recent Node version 8.7.0 with latest Expo cli 45.1.0 

I get an error which seems related to es6 generators / async/await / regenerator runtime or something 

```
~  2.4.1  EXPO_DEBUG=true exp whoami                                                                                                                                               1 ↵  3800  13:45:10
[exp] Unexpected Error: Couldn't get user information
[exp] Error: Unexpected Error: Couldn't get user information
    at _callee$ (/Users/david/Dev/_expo/universe/dev/exp/src/commands/whoami.js:17:11)
    at tryCatch (/Users/sebastienlorber/.nvm/versions/node/v8.7.0/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/sebastienlorber/.nvm/versions/node/v8.7.0/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sebastienlorber/.nvm/versions/node/v8.7.0/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/sebastienlorber/.nvm/versions/node/v8.7.0/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/sebastienlorber/.nvm/versions/node/v8.7.0/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
```

It seems I'm logged in:

```
 ~  2.4.1  exp login                                                                                                                                                                  ✓  3805  13:47:13
? You are already logged in as undefined. Log in as new user? (Y/n)
```

Note that after redoing login it seems to fix it

**Comment by slorber** [comment]
Hmmm closing as it is probably duplicate of https://github.com/expo/expo/issues/871
