### ISSUE TITLE
pod install error.

### ISSUE THREAD

**Issue by hyunjun19** [expo/expo#994]
I was ``exp detach`` and ``pod install``.
but ``pod install`` fail.

How can i fix it?

## Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'gajago-app-malibu' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.1.2",
    :subspecs => [
      "Core",
      "CPP"
    ]

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'GLog',
    :podspec => "../node_modules/react-native/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    if target.pod_name == 'AppAuth'
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
```

## error log
```bash
$ pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.1.2`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `GLog` from `../node_modules/react-native/third-party-podspecs/GLog.podspec`
Fetching podspec for `React` from `../node_modules/react-native`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.1 (17B48)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8ec37d7aae41bf6cfc8c589ed41ebfc72a009a11
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'gajago-app-malibu' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.1.2",
    :subspecs => [
      "Core",
      "CPP"
    ]

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'GLog',
    :podspec => "../node_modules/react-native/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    if target.pod_name == 'AppAuth'
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
```

### Error

```
ArgumentError - Illformed requirement `"https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz.React"`
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/dependency.rb:116:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification/consumer.rb:200:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification/consumer.rb:200:in `block in dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification/consumer.rb:199:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification/consumer.rb:199:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification/consumer.rb:199:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification.rb:326:in `block in dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification.rb:325:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/specification.rb:325:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/validator.rb:32:in `block in initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/validator.rb:32:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/validator.rb:32:in `all?'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/validator.rb:32:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:191:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:191:in `validator_for_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:178:in `validate_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/abstract_external_source.rb:173:in `store_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:686:in `fetch_external_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:662:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:661:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:661:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:660:in `fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22https%3A%2F%2Fgithub.com%2Fexpo%2Freact-native%2Farchive%2Fsdk-23.0.0.tar.gz.React%22%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
```

**Comment by terribleben** [comment]
Hi, check out your project's `node_modules/react-native/package.json` and make sure the `version` field matches [this one](https://github.com/expo/react-native/blob/fdf598975aed7392891e83032f89cb907c1d230e/package.json#L3). If it doesn't, it's probably a bug with your JS package manager. To resolve it, I recommend:

- Make sure you're not using npm 5
- from your project root directory, `rm -rf node_modules`
- reinstall JS dependencies (either `npm i` or `yarn` depending on what you use)
- now retry `cd ios && pod install` and see if the problem is fixed.

**Comment by hyunjun19** [comment]
@terribleben great~! thank u.

my package.json(created via create-react-native-app)
```
"react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
```

so i changed react-native version
```bash
$ npm remove react-native --save
$ npm install react-native@0.49 --save
```

changed package.json
```
"react-native": "^0.49.5",
```

pod install working
```
$ pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.1.2`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `GLog` from `../node_modules/react-native/third-party-podspecs/GLog.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing Amplitude-iOS (3.14.1)
Installing Analytics (3.6.7)
Installing AppAuth (0.91.0)
Installing Bolts (1.8.4)
Installing Branch (0.14.12)
Installing CocoaLumberjack (3.2.1)
Installing Crashlytics (3.9.3)
Installing DoubleConversion (1.1.5)
Installing ExpoKit (2.1.2)
Installing FBAudienceNetwork (4.26.1)
Installing FBSDKCoreKit (4.28.0)
Installing FBSDKLoginKit (4.28.0)
Installing FBSDKShareKit (4.28.0)
Installing Fabric (1.7.2)
Installing Folly (2016.09.26.00)
Installing GLog (0.3.4)
Installing GPUImage (0.1.7)
Installing Google-Mobile-Ads-SDK (7.22.0)
Installing GoogleAppUtilities (1.1.2)
Installing GoogleAuthUtilities (2.0.2)
Installing GoogleMaps (2.2.0)
Installing GoogleNetworkingUtilities (1.2.2)
Installing GoogleSignIn (3.0.0)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleUtilities (1.3.2)
Installing React (0.49.5)
Installing boost (1.59.0)
Installing lottie-ios (2.1.4)
Installing yoga (0.49.5.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 19 dependencies from the Podfile and 29 total pods installed.
```

**Comment by terribleben** [comment]
You probably don't need to change your own react-native dependency. Simply reinstalling existing dependencies (with the instructions I gave) should be sufficient.

**Comment by SCasarotto** [comment]
@terribleben I wanted to let you know that I tried to accomplish this without changing the RN version as @hyunjun19 had done and received the same error back.

Following @hyunjun19 instruction worked expect I used the current 0.50.3 version. Idk if this is a problem with Expo or what but wanted to provide additional information here.

**Comment by zibs** [comment]
npm 5.8.0 seemed to work for me fwiw - npm 5.3.0 did not.
